import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8')
test('client root delegates legacy style composition to feature boundary',async()=>{const[root,styles]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/clientStyles.ts')]);assert.match(root,/features\/client\/clientStyles/);assert.doesNotMatch(root,/client-guided-request\.css/);for(const css of ['clientGuidedRequest.css','clientAiStudioProductionLock.css','client-premium-2026.css','client-profile-premium-2026.css'])assert.ok(styles.includes(css))})
test('client real-test fixes reuse global tokens for shared spacing and surface values',async()=>{const css=await read('src/mvp/client/client-real-test-fixes.css');for(const token of ['--ugo-space-6','--ugo-space-3','--ugo-space-2','--ugo-color-surface','--ugo-color-text-muted'])assert.ok(css.includes(`var(${token})`));assert.doesNotMatch(css,/background:#fff/);assert.doesNotMatch(css,/color:#667085/)})
test('client persistent header rendering lives behind the client feature UI boundary',async()=>{const[root,header]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/ui/ClientPersistentHeader.tsx')]);assert.match(root,/ClientPersistentHeader onHome=\{goHome\}/);assert.doesNotMatch(root,/ugo-client-header-menu|ugo-client-header-logo|querySelector<HTMLButtonElement>/);assert.match(header,/ugo-client-header-menu/);assert.match(header,/ugo-client-header-logo/);assert.match(header,/ugo-client-global-trigger/)})
test('client persistent header CSS lives beside its feature UI without changing composition order',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.match(styles,/\.\/ui\/clientPersistentHeader\.css/);assert.doesNotMatch(styles,/mvp\/client\/client-persistent-header\.css/);const css=await read('src/features/client/ui/clientPersistentHeader.css');assert.match(css,/\.ugo-client-root \.ugo-client-persistent-header/);assert.match(css,/\.ugo-client-root \.ugo-client-screen-overlay/)})

test('client home layout CSS is isolated behind the client feature style boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.match(styles,/\.\/ui\/clientHomeScreen\.css/);assert.doesNotMatch(styles,/mvp\/client\/client-home-screen\.css/);const css=await read('src/features/client/ui/clientHomeScreen.css');assert.match(css,/\.ugo-home-screen\{/);assert.match(css,/\.ugo-home-map-recenter\{/)});
test('client payment choice CSS keeps cascade slot two behind its payment feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const guided=styles.indexOf("./request/clientGuidedRequest.css");const payment=styles.indexOf("./payments/clientPaymentChoice.css");const responsive=styles.indexOf("./ui/clientResponsiveLayout.css");assert.ok(guided>=0&&payment>guided&&responsive>payment);assert.doesNotMatch(styles,/mvp\/client\/client-payment-choice\.css/);const css=await read('src/features/client/payments/clientPaymentChoice.css');assert.match(css,/\.ugo-client-payment-choice\{/);assert.match(css,/\.ugo-client-payment-options/)});

test('client guided request CSS keeps the first cascade slot behind its request feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.ok(styles.startsWith("import'./request/clientGuidedRequest.css'"));assert.doesNotMatch(styles,/mvp\/client\/client-guided-request\.css/);const css=await read('src/features/client/request/clientGuidedRequest.css');assert.match(css,/\.ugo-guided-request/);assert.ok(css.length>1000)})

test('client responsive layout CSS keeps cascade slot three behind the client UI boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const guided=styles.indexOf("./request/clientGuidedRequest.css");const payment=styles.indexOf("./payments/clientPaymentChoice.css");const responsive=styles.indexOf("./ui/clientResponsiveLayout.css");const conversational=styles.indexOf("./conversation/clientConversationalStage.css");assert.ok(guided>=0&&payment>guided&&responsive>payment&&conversational>responsive);assert.doesNotMatch(styles,/mvp\/client\/client-responsive-layout\.css/);const css=await read('src/features/client/ui/clientResponsiveLayout.css');assert.match(css,/@media \(min-width:900px\)/);assert.match(css,/\.ugo-client-root/)});

test('client conversational stage CSS keeps cascade slot four behind its conversation feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const responsive=styles.indexOf("./ui/clientResponsiveLayout.css");const conversational=styles.indexOf("./conversation/clientConversationalStage.css");const web=styles.indexOf("./conversation/clientWebConversational.css");assert.ok(responsive>=0&&conversational>responsive&&web>conversational);assert.doesNotMatch(styles,/mvp\/client\/client-conversational-stage\.css/);const css=await read('src/features/client/conversation/clientConversationalStage.css');assert.match(css,/\.ugo-hugo-stage-composer/);assert.ok(css.length>1000)})

test('client web conversational CSS keeps cascade slot five behind its conversation feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const stage=styles.indexOf("./conversation/clientConversationalStage.css");const web=styles.indexOf("./conversation/clientWebConversational.css");const polish=styles.indexOf("./legacy/clientVisualPolish.css");assert.ok(stage>=0&&web>stage&&polish>web);assert.doesNotMatch(styles,/mvp\/client\/client-web-conversational\.css/);const css=await read('src/features/client/conversation/clientWebConversational.css');assert.match(css,/@media \(min-width:900px\)/);assert.match(css,/\.ugo-client-premium-home/);assert.ok(css.length>10000)})

test('client visual polish compatibility CSS keeps cascade slot six inside the feature legacy boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const web=styles.indexOf("./conversation/clientWebConversational.css");const polish=styles.indexOf("./legacy/clientVisualPolish.css");const redesign=styles.indexOf("./legacy/request/clientGuidedRequestRedesign.css");assert.ok(web>=0&&polish>web&&redesign>polish);assert.doesNotMatch(styles,/mvp\/client\/client-visual-polish\.css/);const css=await read('src/features/client/legacy/clientVisualPolish.css');assert.match(css,/UGO Client visual polish/);assert.match(css,/--ugo-client-green/);assert.ok(css.length>15000)})

test('guided request redesign compatibility CSS keeps cascade slot seven inside the feature legacy boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const polish=styles.indexOf("./legacy/clientVisualPolish.css");const redesign=styles.indexOf("./legacy/request/clientGuidedRequestRedesign.css");const review=styles.indexOf("./request/clientGuidedRequestReview.css");assert.ok(polish>=0&&redesign>polish&&review>redesign);assert.doesNotMatch(styles,/mvp\/client\/client-guided-request-redesign\.css/);const css=await read('src/features/client/legacy/request/clientGuidedRequestRedesign.css');assert.match(css,/Guided request redesign/);assert.match(css,/Solicitud guiada por Hugo/);assert.ok(css.length>20000)})

test('guided request review CSS keeps cascade slot eight behind the request feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const redesign=styles.indexOf("./legacy/request/clientGuidedRequestRedesign.css");const review=styles.indexOf("./request/clientGuidedRequestReview.css");const next=styles.indexOf("./legacy/clientRedesign2026.css");assert.ok(redesign>=0&&review>redesign&&next>review);assert.doesNotMatch(styles,/mvp\/client\/client-guided-request-review\.css/);const css=await read('src/features/client/request/clientGuidedRequestReview.css');assert.match(css,/Review state for the guided request/);assert.match(css,/Solicitud guiada por Hugo/);assert.ok(css.length>3000)})

test('client redesign 2026 compatibility CSS keeps cascade slot nine inside the feature legacy boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const review=styles.indexOf("./request/clientGuidedRequestReview.css");const redesign=styles.indexOf("./legacy/clientRedesign2026.css");const ai=styles.indexOf("./ai/clientAiStudioFlow.css");assert.ok(review>=0&&redesign>review&&ai>redesign);assert.doesNotMatch(styles,/mvp\/client\/client-redesign-2026\.css/);const css=await read('src/features/client/legacy/clientRedesign2026.css');assert.match(css,/coherent UI\/UX layer 2026/);assert.match(css,/--client-green/);assert.ok(css.length>14000)})

test('client AI Studio flow CSS keeps cascade slot ten behind the client AI feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const redesign=styles.indexOf("./legacy/clientRedesign2026.css");const ai=styles.indexOf("./ai/clientAiStudioFlow.css");const google=styles.indexOf("./ai/clientGoogleAiStudio.css");assert.ok(redesign>=0&&ai>redesign&&google>ai);assert.doesNotMatch(styles,/mvp\/client\/client-ai-studio-flow\.css/);const css=await read('src/features/client/ai/clientAiStudioFlow.css');assert.match(css,/UGO real flow/);assert.match(css,/\.ugo-client-root \.ugo-guided-request/);assert.ok(css.length>7000)})

test('client Google AI Studio CSS keeps cascade slot eleven behind the client AI feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const ai=styles.indexOf("./ai/clientAiStudioFlow.css");const google=styles.indexOf("./ai/clientGoogleAiStudio.css");const ref=styles.indexOf("./ai/clientStudioReference.css");assert.ok(ai>=0&&google>ai&&ref>google);assert.doesNotMatch(styles,/mvp\/client\/client-google-ai-studio\.css/);const css=await read('src/features/client/ai/clientGoogleAiStudio.css');assert.match(css,/Google AI Studio UGO visual source-of-truth/);assert.match(css,/--studio-primary/);assert.ok(css.length>33000)})

test('client Studio reference CSS keeps cascade slot twelve behind the client AI feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const google=styles.indexOf("./ai/clientGoogleAiStudio.css");const ref=styles.indexOf("./ai/clientStudioReference.css");const radar=styles.indexOf("./radar/clientStudioRadar.css");assert.ok(google>=0&&ref>google&&radar>ref);assert.doesNotMatch(styles,/mvp\/client\/client-studio-reference\.css/);const css=await read('src/features/client/ai/clientStudioReference.css');assert.match(css,/visual source of truth/);assert.match(css,/--ugo-ref-primary/);assert.ok(css.length>35000)})

test('client Studio radar CSS keeps cascade slot thirteen behind the radar feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const ref=styles.indexOf("./ai/clientStudioReference.css");const radar=styles.indexOf("./radar/clientStudioRadar.css");const lock=styles.indexOf("./legacy/ai/clientAiStudioProductionLock.css");assert.ok(ref>=0&&radar>ref&&lock>radar);assert.doesNotMatch(styles,/mvp\/client\/client-studio-radar\.css/);const css=await read('src/features/client/radar/clientStudioRadar.css');assert.match(css,/\.ugo-studio-radar-page/);assert.match(css,/\.ugo-studio-radar-ticker/);assert.ok(css.length>12000)})

test('client AI Studio production lock compatibility CSS keeps cascade slot fourteen inside the feature legacy boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const radar=styles.indexOf("./radar/clientStudioRadar.css");const lock=styles.indexOf("./legacy/ai/clientAiStudioProductionLock.css");const ops=styles.indexOf("client-ai-studio-production-ops.css");assert.ok(radar>=0&&lock>radar&&ops>lock);assert.doesNotMatch(styles,/mvp\/client\/client-ai-studio-production-lock\.css/);const css=await read('src/features/client/legacy/ai/clientAiStudioProductionLock.css');assert.match(css,/production presentation lock/);assert.match(css,/--ugo-studio-primary/);assert.ok(css.length>8000)})
