import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8')
test('client root delegates legacy style composition to feature boundary',async()=>{const[root,styles]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/clientStyles.ts')]);assert.match(root,/features\/client\/clientStyles/);assert.doesNotMatch(root,/client-guided-request\.css/);for(const css of ['clientGuidedRequest.css','client-ai-studio-production-lock.css','client-premium-2026.css','client-profile-premium-2026.css'])assert.ok(styles.includes(css))})
test('client real-test fixes reuse global tokens for shared spacing and surface values',async()=>{const css=await read('src/mvp/client/client-real-test-fixes.css');for(const token of ['--ugo-space-6','--ugo-space-3','--ugo-space-2','--ugo-color-surface','--ugo-color-text-muted'])assert.ok(css.includes(`var(${token})`));assert.doesNotMatch(css,/background:#fff/);assert.doesNotMatch(css,/color:#667085/)})
test('client persistent header rendering lives behind the client feature UI boundary',async()=>{const[root,header]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/ui/ClientPersistentHeader.tsx')]);assert.match(root,/ClientPersistentHeader onHome=\{goHome\}/);assert.doesNotMatch(root,/ugo-client-header-menu|ugo-client-header-logo|querySelector<HTMLButtonElement>/);assert.match(header,/ugo-client-header-menu/);assert.match(header,/ugo-client-header-logo/);assert.match(header,/ugo-client-global-trigger/)})
test('client persistent header CSS lives beside its feature UI without changing composition order',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.match(styles,/\.\/ui\/clientPersistentHeader\.css/);assert.doesNotMatch(styles,/mvp\/client\/client-persistent-header\.css/);const css=await read('src/features/client/ui/clientPersistentHeader.css');assert.match(css,/\.ugo-client-root \.ugo-client-persistent-header/);assert.match(css,/\.ugo-client-root \.ugo-client-screen-overlay/)})

test('client home layout CSS is isolated behind the client feature style boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.match(styles,/\.\/ui\/clientHomeScreen\.css/);assert.doesNotMatch(styles,/mvp\/client\/client-home-screen\.css/);const css=await read('src/features/client/ui/clientHomeScreen.css');assert.match(css,/\.ugo-home-screen\{/);assert.match(css,/\.ugo-home-map-recenter\{/)});
test('client payment choice CSS keeps cascade slot two behind its payment feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const guided=styles.indexOf("./request/clientGuidedRequest.css");const payment=styles.indexOf("./payments/clientPaymentChoice.css");const responsive=styles.indexOf("./ui/clientResponsiveLayout.css");assert.ok(guided>=0&&payment>guided&&responsive>payment);assert.doesNotMatch(styles,/mvp\/client\/client-payment-choice\.css/);const css=await read('src/features/client/payments/clientPaymentChoice.css');assert.match(css,/\.ugo-client-payment-choice\{/);assert.match(css,/\.ugo-client-payment-options/)});

test('client guided request CSS keeps the first cascade slot behind its request feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.ok(styles.startsWith("import'./request/clientGuidedRequest.css'"));assert.doesNotMatch(styles,/mvp\/client\/client-guided-request\.css/);const css=await read('src/features/client/request/clientGuidedRequest.css');assert.match(css,/\.ugo-guided-request/);assert.ok(css.length>1000)})

test('client responsive layout CSS keeps cascade slot three behind the client UI boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const guided=styles.indexOf("./request/clientGuidedRequest.css");const payment=styles.indexOf("./payments/clientPaymentChoice.css");const responsive=styles.indexOf("./ui/clientResponsiveLayout.css");const conversational=styles.indexOf("./conversation/clientConversationalStage.css");assert.ok(guided>=0&&payment>guided&&responsive>payment&&conversational>responsive);assert.doesNotMatch(styles,/mvp\/client\/client-responsive-layout\.css/);const css=await read('src/features/client/ui/clientResponsiveLayout.css');assert.match(css,/@media \(min-width:900px\)/);assert.match(css,/\.ugo-client-root/)});

test('client conversational stage CSS keeps cascade slot four behind its conversation feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const responsive=styles.indexOf("./ui/clientResponsiveLayout.css");const conversational=styles.indexOf("./conversation/clientConversationalStage.css");const web=styles.indexOf("./conversation/clientWebConversational.css");assert.ok(responsive>=0&&conversational>responsive&&web>conversational);assert.doesNotMatch(styles,/mvp\/client\/client-conversational-stage\.css/);const css=await read('src/features/client/conversation/clientConversationalStage.css');assert.match(css,/\.ugo-hugo-stage-composer/);assert.ok(css.length>1000)})

test('client web conversational CSS keeps cascade slot five behind its conversation feature boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const stage=styles.indexOf("./conversation/clientConversationalStage.css");const web=styles.indexOf("./conversation/clientWebConversational.css");const polish=styles.indexOf("./legacy/clientVisualPolish.css");assert.ok(stage>=0&&web>stage&&polish>web);assert.doesNotMatch(styles,/mvp\/client\/client-web-conversational\.css/);const css=await read('src/features/client/conversation/clientWebConversational.css');assert.match(css,/@media \(min-width:900px\)/);assert.match(css,/\.ugo-client-premium-home/);assert.ok(css.length>10000)})

test('client visual polish compatibility CSS keeps cascade slot six inside the feature legacy boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');const web=styles.indexOf("./conversation/clientWebConversational.css");const polish=styles.indexOf("./legacy/clientVisualPolish.css");const redesign=styles.indexOf("client-guided-request-redesign.css");assert.ok(web>=0&&polish>web&&redesign>polish);assert.doesNotMatch(styles,/mvp\/client\/client-visual-polish\.css/);const css=await read('src/features/client/legacy/clientVisualPolish.css');assert.match(css,/UGO Client visual polish/);assert.match(css,/--ugo-client-green/);assert.ok(css.length>15000)})
