import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8')
test('client root delegates legacy style composition to feature boundary',async()=>{const[root,styles]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/clientStyles.ts')]);assert.match(root,/features\/client\/clientStyles/);assert.doesNotMatch(root,/client-guided-request\.css/);for(const css of ['client-guided-request.css','client-ai-studio-production-lock.css','client-premium-2026.css','client-profile-premium-2026.css'])assert.ok(styles.includes(css))})
test('client real-test fixes reuse global tokens for shared spacing and surface values',async()=>{const css=await read('src/mvp/client/client-real-test-fixes.css');for(const token of ['--ugo-space-6','--ugo-space-3','--ugo-space-2','--ugo-color-surface','--ugo-color-text-muted'])assert.ok(css.includes(`var(${token})`));assert.doesNotMatch(css,/background:#fff/);assert.doesNotMatch(css,/color:#667085/)})
test('client persistent header rendering lives behind the client feature UI boundary',async()=>{const[root,header]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/ui/ClientPersistentHeader.tsx')]);assert.match(root,/ClientPersistentHeader onHome=\{goHome\}/);assert.doesNotMatch(root,/ugo-client-header-menu|ugo-client-header-logo|querySelector<HTMLButtonElement>/);assert.match(header,/ugo-client-header-menu/);assert.match(header,/ugo-client-header-logo/);assert.match(header,/ugo-client-global-trigger/)})
test('client persistent header CSS lives beside its feature UI without changing composition order',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.match(styles,/\.\/ui\/clientPersistentHeader\.css/);assert.doesNotMatch(styles,/mvp\/client\/client-persistent-header\.css/);const css=await read('src/features/client/ui/clientPersistentHeader.css');assert.match(css,/\.ugo-client-root \.ugo-client-persistent-header/);assert.match(css,/\.ugo-client-root \.ugo-client-screen-overlay/)})

test('client home layout CSS is isolated behind the client feature style boundary',async()=>{const styles=await read('src/features/client/clientStyles.ts');assert.match(styles,/\.\/ui\/clientHomeScreen\.css/);assert.doesNotMatch(styles,/mvp\/client\/client-home-screen\.css/);const css=await read('src/features/client/ui/clientHomeScreen.css');assert.match(css,/\.ugo-home-screen\{/);assert.match(css,/\.ugo-home-map-recenter\{/)});
