import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const catalog=await readFile(new URL('../../src/mvp/voiceCatalog.ts',import.meta.url),'utf8'),radarStore=await readFile(new URL('../../src/features/client/radar/providerRadarStore.ts',import.meta.url),'utf8'),radar=await readFile(new URL('../../src/mvp/ClientQuantumExperience.tsx',import.meta.url),'utf8'),radarBridge=await readFile(new URL('../../src/features/client/radar/ClientProviderRadarBridge.tsx',import.meta.url),'utf8'),dock=await readFile(new URL('../../src/features/client/hugo/ClientVoiceHugoDock.tsx',import.meta.url),'utf8'),bridge=await readFile(new URL('../../src/features/client/hugo/ClientHugoBridge.tsx',import.meta.url),'utf8'),browserVoice=await readFile(new URL('../../src/lib/browserVoiceBridge.ts',import.meta.url),'utf8'),hugoApi=await readFile(new URL('../../api/hugo/chat.ts',import.meta.url),'utf8'),intent=await readFile(new URL('../../src/features/client/hugo/hugoVoiceIntent.ts',import.meta.url),'utf8'),multirubroMigration=await readFile(new URL('../../supabase/migrations/20260914210000_provider_radar_multirubro_view.sql',import.meta.url),'utf8'),matchingMigration=await readFile(new URL('../../supabase/migrations/20260914212500_matching_multirubro_consistency.sql',import.meta.url),'utf8')
test('voice categories come from the live UGO catalog',()=>{assert.match(catalog,/from\('categorias'\)/);assert.match(catalog,/eq\('activa',true\)/);assert.match(catalog,/resolveVoiceCategory/);assert.match(catalog,/resolveVoiceCategoryFromCatalog/)})
test('voice availability and post-confirm matching share one multirubro provider source of truth',()=>{assert.match(catalog,/refreshProviderRadar\(sb,true\)/);assert.match(catalog,/providerRadarForCategory\(category\.id,\{onlyAvailable:true\}\)/);assert.match(radarStore,/from\('proveedores_mapa'\)/);assert.match(radarStore,/categoryIds\.includes\(categoryId\)/);assert.match(radarStore,/provider\.online&&provider\.disponible/);assert.match(radar,/setProviderRadarRows\(rows\)/);assert.match(radar,/p\.categoria_ids\.includes\(selectedCategoryId\)/);assert.match(radarBridge,/return null/);assert.match(multirubroMigration,/as categoria_ids/);assert.match(multirubroMigration,/proveedor_subcategorias/)})
test('automatic and directed matching honor active provider rubros',()=>{assert.match(matchingMigration,/create or replace function private\.iniciar_matching_impl/);assert.match(matchingMigration,/create or replace function public\.iniciar_matching_dirigido/);assert.match(matchingMigration,/public\.proveedor_subcategorias/);assert.match(matchingMigration,/sc\.categoria_id=v_servicio\.categoria_id/);assert.match(matchingMigration,/v_secondary_match/)})
test('client can finish a real request by voice without duplicate inserts',()=>{assert.match(dock,/from\('servicios'\)\.insert/);assert.match(dock,/preferredProviderId/);assert.match(dock,/getDispatchProvider\(\)/);assert.match(dock,/current\.serviceId=serviceId/);assert.match(dock,/dispatch\.getStatus\(serviceId\)/);assert.match(dock,/23505/);assert.match(dock,/reintentar búsqueda/);assert.match(dock,/¿Está bien\?/)})
test('explicit search recommendations use the same Live draft and real availability',()=>{assert.match(dock,/name==='search_providers'/);assert.match(dock,/draft\.current=current/);assert.match(dock,/loadVoiceAvailability\(current\.category\)/);assert.match(dock,/providers:result\.providers\.slice\(0,5\)/);assert.doesNotMatch(dock,/geminiProviderLead/)})
test('Live tool execution keeps shared schedule parsing while Gemini owns conversational interpretation',()=>{assert.match(dock,/parseHugoWhen/);assert.match(dock,/name==='set_schedule'/);assert.match(dock,/name==='create_service_request'/);assert.doesNotMatch(dock,/companion\?\.confirm/)})
test('Hugo recommends only from real provider signals',()=>{assert.match(catalog,/servicios_completados/);assert.match(catalog,/experiencia_anos/);assert.match(catalog,/Mi recomendación es/);assert.match(catalog,/Por los datos reales de UGO/);assert.match(dock,/voiceAvailabilityText/)})
test('Gemini Live is the canonical browser transcription path and keeps one streaming session across turns',()=>{assert.match(browserVoice,/BidiGenerateContentConstrained/);assert.match(browserVoice,/voice_live_token:true/);assert.match(browserVoice,/audio\/pcm;rate=16000/);assert.match(browserVoice,/CHUNK_SAMPLES=1600/);assert.match(browserVoice,/interimInputTranscription/);assert.match(browserVoice,/inputTranscription/);assert.match(browserVoice,/pauseListening/);assert.match(browserVoice,/resumeListening/);assert.match(browserVoice,/audioStreamEnd:true/);assert.doesNotMatch(browserVoice,/MediaRecorder/);assert.doesNotMatch(browserVoice,/voice_transcription:true/);assert.doesNotMatch(browserVoice,/hasWebSpeech/)})
test('client Hugo output is owned by the persistent Gemini Live audio session',()=>{assert.match(browserVoice,/responseModalities:\['AUDIO'\]/);assert.match(browserVoice,/playConversationPcm/);assert.match(dock,/stopSpeechPlayback/);assert.doesNotMatch(dock,/playDeviceSpeech|SpeechSynthesisUtterance|speechSynthesis|ttsCooldownUntil/)})
test('stop voice keeps the orb reusable and navigation is wired to ClientFlow',()=>{assert.match(dock,/onNavigateHome/);assert.match(dock,/ugo-hugo-voice-controller/);assert.doesNotMatch(dock,/inputRef|placeholder="Escribile a Hugo…"|sendTyped/);assert.doesNotMatch(dock,/disabled=\{state==='connecting'\}/);assert.match(bridge,/onNavigateHome=\{\(\)=>flow\.navigate\('home'\)\}/)})

test('new category requests are isolated in the Live request draft',()=>{assert.match(dock,/name==='set_request_category'/);assert.match(dock,/current=emptyVoiceDraft\(null\)/);assert.match(dock,/current!\.category=category/);assert.doesNotMatch(dock,/companion\?\.action==='prepare_request'/)})

test('painter aliases remain resolvable through the real voice catalog used by the Live category tool',()=>{assert.match(catalog,/pintor\|pintura/);assert.match(catalog,/\['pintura','reparaciones','reparacao','manutencao'\]/);assert.match(dock,/resolveVoiceCategory\(String\(args\.category\|\|''\)\)/)})



test('water leak language resolves to plumbing before generic repair intent',()=>{assert.match(catalog,/perdida de agua\|fuga de agua\|fuga/);assert.match(catalog,/caño\|caneria\|cañeria\|desague\|vazamento/);const plumbing=catalog.indexOf("['plomeria','encanamento','hidraulica']"),generic=catalog.indexOf("['reparaciones','reparacao','manutencao']");assert.ok(plumbing>=0&&generic>plumbing)})
