import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const read=path=>readFile(new URL('../../'+path,import.meta.url),'utf8')

test('disputes v2 freeze context, support structured reasons and amicable agreement',async()=>{
 const[migration,hook,dock,policy]=await Promise.all([read('supabase/migrations/20260920151000_dispute_rules_ai_snapshot.sql'),read('src/hooks/useDisputes.ts'),read('src/mvp/DisputeDock.tsx'),read('docs/UGO_DISPUTE_RULES_MASTER.md')])
 assert.match(migration,/reglas_motivos_disputa/)
 assert.match(migration,/capture_dispute_snapshot/)
 assert.match(migration,/acuerdos_previos_disputa/)
 assert.match(migration,/dispute-evidence/)
 assert.match(migration,/abrir_disputa_v2/)
 assert.match(migration,/revoke execute on function public\.abrir_disputa\(uuid,text,jsonb\) from authenticated/)
 assert.match(hook,/proponer_acuerdo_previo/)
 assert.match(hook,/abrir_disputa_v2/)
 assert.match(hook,/dispute-evidence/)
 assert.match(dock,/DISPUTA FORMAL/)
 assert.match(dock,/Enviar propuesta amistosa/)
 assert.match(policy,/48 horas/)
 assert.match(policy,/168 horas/)
 assert.match(policy,/Una foto demuestra sólo lo que se observa/)
})

test('AI dispute analysis is admin-only decision support and can inspect images',async()=>{
 const[api,panel,policy,vercel]=await Promise.all([read('api/test.ts'),read('src/mvp/AdminDisputeAssistant.tsx'),read('docs/UGO_DISPUTE_RULES_MASTER.md'),read('vercel.json')])
 assert.match(api,/Solo Admin puede analizar disputas/)
 assert.match(api,/inlineData/)
 assert.match(api,/nunca atribuyas quién causó un daño/i)
 assert.match(api,/disputa_ai_analisis/)
 assert.match(vercel,/"source": "\/api\/disputes\/analyze"[\s\S]*?"destination": "\/api\/test\?ugo_dispute_ai=1"/)
 assert.match(panel,/no ejecuta pagos ni resuelve el caso por sí sola/i)
 assert.match(panel,/from\('evidencias_servicio'\)/)
 assert.match(panel,/storage\.from\(item\.bucket\)/)
 assert.match(panel,/service-evidence/)
 assert.match(panel,/dispute-evidence/)
 assert.match(panel,/Antes\/Durante\/Después/)
 assert.match(panel,/Usar como borrador del fundamento/)
 assert.match(policy,/toda resolución final la confirma Admin/i)
 const matrix=await read('supabase/migrations/20260920153000_dispute_resolution_policy_matrix.sql')
 assert.match(matrix,/criterio_resolucion/)
 assert.match(matrix,/resultado_preferido/)
 assert.match(matrix,/check\(auto_aplicar=false\)/)
 assert.match(matrix,/when 'danio' then 'revision_humana'/)
 assert.match(api,/criterio_resolucion,resultado_preferido,auto_aplicar/)
 const admin=await read('src/mvp/AdminDecisionCenter.tsx')
 assert.match(admin,/REGLA APLICABLE/)
 assert.match(admin,/No resuelve el caso ni ejecuta movimientos de dinero automáticamente/)
})
