import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8')
test('provider Hugo runtime uses guarded real provider actions',async()=>{const bridge=await read('src/mvp/provider/ProviderHugoBridge.tsx');for(const token of["provider_get_context","provider_set_online","provider_set_offline","provider_get_active_service","provider_accept_job","provider_reject_job","provider_update_service_status","CONFIRMATION_REQUIRED","INVALID_TRANSITION","data.advance","data.completeService","data.setOnline(true)","data.setOnline(false)"])assert.ok(bridge.includes(token),token)})
test('provider Hugo context exposes live work, opportunities and finances before reasoning',async()=>{const bridge=await read('src/mvp/provider/ProviderHugoBridge.tsx'),live=await read('src/lib/browserVoiceBridge.ts');assert.match(bridge,/provider_get_context/);assert.match(bridge,/pendingDebtCount:data\.pendingDebtCount/);assert.match(live,/provider_get_context/);assert.match(live,/qué conviene/);assert.match(live,/qué deuda tiene/)})
test('provider Hugo lifecycle remains constrained by GPS and evidence aware flow',async()=>{const live=await read('src/lib/browserVoiceBridge.ts');assert.match(live,/GPS reciente, preciso y geofence válido/);assert.match(live,/barreras de evidencia/);assert.match(live,/enum:\['en_camino','llegado','en_progreso','esperando_aprobacion'\]/)})

test('provider Hugo allows the Gemini Live token plus websocket setup window to complete',async()=>{const bridge=await read('src/mvp/provider/ProviderHugoBridge.tsx'),live=await read('src/lib/browserVoiceBridge.ts');assert.match(bridge,/PROVIDER_VOICE_CONNECT_TIMEOUT_MS=16_000/);assert.match(bridge,/PROVIDER_VOICE_CONNECT_TIMEOUT_MS\);try\{await bridge\.startListening\(\)/);assert.match(live,/AbortSignal\.timeout\(5000\)/);assert.match(live,/Gemini Live setup timeout/);assert.match(live,/\},6000\)/)})
