import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const read=path=>readFile(new URL(`../../${path}`,import.meta.url),'utf8')
test('client home uses the canonical completed service state',async()=>{const home=await read('src/mvp/client/ClientPremiumHome.tsx');assert.match(home,/completado:'Completado'/);assert.match(home,/services\.filter\(item=>item\.estado==='completado'\)\.length/)})
test('Activity opens its exact order detail in one action',async()=>{const[root,nav,overlay,history]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/navigation/useClientRootNavigation.ts'),read('src/features/client/ui/ClientHistoryOverlay.tsx'),read('src/mvp/ServiceHistoryPanel.tsx')]);assert.match(root,/ClientHistoryOverlay onHome=\{goHome\} onOpenService=\{openService\}/);assert.match(overlay,/ServiceHistoryPanel role="client" embedded onOpenService=\{onOpenService\}/);assert.match(nav,/setSelectedServiceId\(serviceId\)/);assert.match(history,/onOpenService/)})
test('client detail is the only operational order surface while open',async()=>{const[root,nav,boundary,detail]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/navigation/useClientRootNavigation.ts'),read('src/features/client/ui/ClientOrderDetailBoundary.tsx'),read('src/mvp/client/ClientServiceDetail.tsx')]);assert.match(nav,/detailOpen:Boolean\(selectedServiceId\)/);assert.match(root,/!canonical&&!detailOpen&&<ClientPaymentChoice\/>/);assert.match(root,/!canonical&&!detailOpen&&<ClientLiveTracking\/>/);assert.match(root,/!canonical&&!detailOpen&&<ClientCompletionReview/);assert.match(root,/flow\.screen!=='request'&&!detailOpen&&<ClientRatingPrompt\/>/);assert.match(root,/!canonical&&!detailOpen&&<ServiceChat role="client"\/>/);assert.match(root,/selectedServiceId&&<ClientOrderDetailBoundary serviceId=\{selectedServiceId\} onClose=\{closeService\}/);assert.match(boundary,/SentinelErrorBoundary role="client" serviceId=\{serviceId\}/);assert.match(detail,/<ClientRatingPrompt serviceId=\{service\.id\} embedded\/>/)})
test('client navbar exposes only working primary actions',async()=>{const[navbar,styles,css]=await Promise.all([read('src/mvp/client/ClientStudioNavbar.tsx'),read('src/features/client/clientStyles.ts'),read('src/mvp/client/client-ai-studio-production-lock.css')]);assert.doesNotMatch(navbar,/Recados/);assert.doesNotMatch(navbar,/se habilitará cuando/);assert.match(navbar,/ugo-studio-nav-services/);assert.match(navbar,/ugo-studio-nav-pro/);assert.doesNotMatch(styles,/client-navbar-cleanup\.css/);assert.match(styles,/client-ai-studio-production-lock\.css/);assert.match(css,/\.ugo-studio-nav-services/);assert.match(css,/\.ugo-studio-nav-pro/)})
test('development dashboard gives validated a distinct visual state',async()=>{const[main,css]=await Promise.all([read('src/main.tsx'),read('src/mvp/development-dashboard-status.css')]);assert.match(main,/development-dashboard-status\.css/);assert.match(css,/\.devdash-task\.status-validated/);assert.match(css,/\.devdash-pill\.status-validated/);assert.match(css,/\.event-dot\.status-validated/)})
