import test from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
const read=path=>readFile(new URL(`../../${path}`,import.meta.url),'utf8')
test('client history panel uses the canonical completed service state',async()=>{const home=await read('src/mvp/ServiceHistoryPanel.tsx');assert.match(home,/LABELS:[\s\S]*?completado:'Completado'/);assert.match(home,/CLIENT_STATE_COPY:[\s\S]*?completado:{title:'Servicio completado'/);assert.match(home,/FINAL_STATES=new Set\([^)]*'completado'[^)]*\)/);assert.match(home,/finalCount=rows\.filter\(isFinal\)\.length/);assert.match(home,/filter==='finalizados'[\s\S]*?isFinal\(row\)/);})
test('Activity opens its exact order detail in one action',async()=>{const[root,nav,overlay,history]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/navigation/useClientRootNavigation.ts'),read('src/features/client/ui/ClientHistoryOverlay.tsx'),read('src/mvp/ServiceHistoryPanel.tsx')]);assert.match(root,/ClientHistoryOverlay onHome=\{goHome\} onOpenService=\{openService\}/);assert.match(overlay,/ServiceHistoryPanel role="client" embedded onOpenService=\{onOpenService\}/);assert.match(nav,/setSelectedServiceId\(serviceId\)/);assert.match(history,/onOpenService/)})
test('client detail is the only operational order surface while open',async()=>{const[root,nav,boundary,surfaces,detail]=await Promise.all([read('src/mvp/client/ClientRoot.tsx'),read('src/features/client/navigation/useClientRootNavigation.ts'),read('src/features/client/ui/ClientOrderDetailBoundary.tsx'),read('src/features/client/ui/ClientOperationalSurfaces.tsx'),read('src/features/client/order/ClientServiceDetail.tsx')]);assert.match(nav,/detailOpen:Boolean\(selectedServiceId\)/);assert.match(root,/ClientOperationalSurfaces canonical=\{canonical\} detailOpen=\{detailOpen\} screen=\{flow\.screen\} openDispute=\{flow\.actions\.openDispute\}/);assert.match(surfaces,/!canonical&&!detailOpen&&<ClientPaymentChoice\/>/);assert.match(surfaces,/!canonical&&!detailOpen&&<ClientLiveTracking\/>/);assert.match(surfaces,/!canonical&&!detailOpen&&<ClientCompletionReview/);assert.match(surfaces,/screen!=='request'&&!detailOpen&&<ClientRatingPrompt\/>/);assert.match(surfaces,/!canonical&&!detailOpen&&<ServiceChat role="client"\/>/);assert.match(root,/selectedServiceId&&<ClientOrderDetailBoundary serviceId=\{selectedServiceId\} onClose=\{closeService\}/);assert.match(boundary,/SentinelErrorBoundary role="client" serviceId=\{serviceId\}/);assert.match(detail,/<ClientRatingPrompt serviceId=\{service\.id\} embedded\/>/)})
test('client persistent header exposes only working primary actions',async()=>{const[header,styles,css]=await Promise.all([read('src/features/client/ui/ClientPersistentHeader.tsx'),read('src/features/client/clientStyles.ts'),read('src/features/client/ui/clientPersistentHeader.css')]);assert.doesNotMatch(header,/Recados/);assert.doesNotMatch(header,/se habilitará cuando/);assert.match(header,/ugo-client-header-menu/);assert.match(header,/ugo-client-header-logo/);assert.match(header,/onClick=\{onHome\}/);assert.match(header,/ugo-client-global-trigger/);assert.match(styles,/clientPersistentHeader\.css/);assert.match(css,/\.ugo-client-persistent-header/);assert.match(css,/\.ugo-client-header-menu/);assert.match(css,/\.ugo-client-header-logo/)})
test('development dashboard gives validated a distinct visual state',async()=>{const[main,css]=await Promise.all([read('src/main.tsx'),read('src/mvp/development-dashboard-status.css')]);assert.match(main,/development-dashboard-status\.css/);assert.match(css,/\.devdash-task\.status-validated/);assert.match(css,/\.devdash-pill\.status-validated/);assert.match(css,/\.event-dot\.status-validated/)})
