import { useMemo } from 'react'
import { AdminMapNative } from './AdminNativeModules'
import { useAdminActiveServices } from '../hooks/useAdminActiveServices'
import './admin-home-stitch.css'

type Metrics = { active: number; online: number; users: number; pendingProviders: number; pendingPix: number; completedToday: number }
type Props = { metrics: Metrics; loading: boolean; onOpenServices: () => void; onOpenVerification: () => void; onOpenPix: () => void }
const stateLabel: Record<string, string> = { buscando: 'Esperando match', ofrecido: 'Ofertado', asignado: 'Asignado', en_camino: 'En camino', llegado: 'Llegó', en_progreso: 'En progreso', esperando_aprobacion: 'Esperando aprobación' }

export function AdminHomeStitch({ metrics, loading, onOpenServices, onOpenVerification, onOpenPix }: Props) {
  const { services } = useAdminActiveServices()
  const stateCounts = useMemo(() => services.reduce<Record<string, number>>((counts, service) => { counts[service.estado] = (counts[service.estado] || 0) + 1; return counts }, {}), [services])
  const value = (number: number) => loading ? '—' : number
  const pending = metrics.pendingProviders + metrics.pendingPix
  return <div className="admin-home-stitch">
    <section className="ahs-command-bar" aria-labelledby="ahs-title"><div><span className="ahs-eyebrow">CENTRO DE CONTROL OPERACIONAL</span><h2 id="ahs-title">Monitoreo en tiempo real de UGO</h2><p>{loading ? 'Sincronizando datos reales…' : `Florianópolis · ${pending ? `${pending} prioridades requieren atención` : 'operación estable'}`}</p></div><div className="ahs-command-actions"><span className="ahs-live-dot"><i/> Sincronizado</span><button type="button" className="ahs-primary" onClick={onOpenServices}>Ver operación <span aria-hidden="true">→</span></button></div></section>
    <section className="ahs-kpis" aria-label="Indicadores operativos" aria-busy={loading}>{[['Servicios activos ahora',metrics.active,'En operación real'],['Proveedores online',metrics.online,'Disponibles para matching'],['Usuarios activos',metrics.users,'Clientes y proveedores'],['Completados hoy',metrics.completedToday,'Servicios cerrados'],['Atención pendiente',pending,pending?'Revisión requerida':'Sin pendientes']].map(([label,number,caption], index) => <article className={index===4&&pending?'attention':''} key={String(label)}><span>{label}</span><strong>{value(Number(number))}</strong><small>{caption}</small></article>)}</section>
    <section className="ahs-decision" aria-labelledby="ahs-decision-title"><div className="ahs-section-title"><div><span className="ahs-eyebrow">CENTRO DE DECISIONES</span><h2 id="ahs-decision-title">Atención inmediata</h2></div><span>{pending} requerimientos</span></div><div className="ahs-decision-grid"><button type="button" onClick={onOpenVerification}><b className="danger">KYC</b><span><strong>Verificaciones pendientes</strong><small>Documentos esperando validación</small></span><em>{value(metrics.pendingProviders)}</em><i aria-hidden="true">→</i></button><button type="button" onClick={onOpenPix}><b className="warning">PIX</b><span><strong>Conciliaciones PIX</strong><small>Pagos reales esperando control</small></span><em>{value(metrics.pendingPix)}</em><i aria-hidden="true">→</i></button><button type="button" onClick={onOpenServices}><b className="info">OPS</b><span><strong>Servicios en vivo</strong><small>Seguimiento del ciclo de vida</small></span><em>{value(metrics.active)}</em><i aria-hidden="true">→</i></button></div></section>
    <section className="ahs-main-grid"><div className="ahs-panel ahs-services"><div className="ahs-panel-head"><div><span className="ahs-eyebrow">ACTIVIDAD EN VIVO</span><h2>Servicios críticos y actividad</h2></div><button type="button" onClick={onOpenServices}>Ver todos →</button></div><div className="ahs-service-list">{services.slice(0, 5).map(service => <button type="button" key={service.id} className="ahs-service-row" onClick={onOpenServices}><span className={`ahs-state state-${service.estado}`}><i/>{stateLabel[service.estado] || service.estado}</span><strong>#{service.numero || '—'}</strong><span>{service.categoria?.emoji} {service.categoria?.nombre || 'Servicio'}</span><span>{service.cliente?.nombre || 'Cliente'}</span><span>{service.proveedor?.nombre || 'Sin asignar'}</span><b>R$ {Number(service.tarifa || 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</b></button>)}{!services.length && <p className="ahs-empty">No hay servicios activos para mostrar.</p>}</div></div><div className="ahs-panel ahs-map-panel"><div className="ahs-panel-head"><div><span className="ahs-eyebrow">COBERTURA OPERATIVA</span><h2>Mapa en vivo</h2></div><span className="ahs-map-meta">{value(metrics.online)} online</span></div><div className="ahs-map"><AdminMapNative/></div></div></section>
    <section className="ahs-bottom-grid"><div className="ahs-panel ahs-flow"><div className="ahs-panel-head"><div><span className="ahs-eyebrow">DISTRIBUCIÓN DEL FLUJO</span><h2>Estado de servicios</h2></div></div><div className="ahs-bars">{Object.entries(stateCounts).length ? Object.entries(stateCounts).slice(0, 6).map(([state, count]) => <div key={state}><span>{stateLabel[state] || state}</span><i><b style={{ width: `${Math.min(100, count / Math.max(1, services.length) * 100)}%` }}/></i><strong>{count}</strong></div>) : <p className="ahs-empty">Aún no hay actividad para graficar.</p>}</div></div><aside className="ahs-panel ahs-hugo"><div className="ahs-hugo-title"><b>✦</b><div><span className="ahs-eyebrow">HUGO COPILOT</span><h2>Insights operativos</h2></div></div><p>{pending ? `Hay ${pending} controles pendientes que requieren una decisión administrativa.` : 'La operación no tiene controles pendientes en este momento.'}</p><button type="button" onClick={onOpenServices}>Abrir centro de decisiones →</button></aside></section>
  </div>
}
