import React,{useMemo,useState}from'react'
import{
 useDashboardMetrics,useConversionKPIs,useSystemAlerts,useActiveServices,useOpenDisputes,
 usePendingDocuments,useVault,usePendingWithdrawals,useTarifas,useCategorias,useConfigSistema,
 useNotificaciones,useExport
}from'../hooks/useAdminData'
import{SecMapaOperativo}from'../components/MapaOperativo'
import{SecScout}from'../components/ScoutSection'
import{SecValidacionPaises,SecImportProviders}from'../components/AdvancedSections'
import{AdminTariffsPanel}from'./AdminTariffsPanel'

const money=(v:any)=>`R$ ${Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const when=(v:any)=>v?new Date(v).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'
const box:React.CSSProperties={background:'var(--ugo-color-surface-lowest)',color:'var(--ugo-color-on-surface)',border:'1px solid var(--ugo-color-outline-variant)',borderRadius:16,padding:16}
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}
const table:React.CSSProperties={width:'100%',borderCollapse:'collapse',fontSize:12,color:'var(--ugo-color-on-surface)'}
const th:React.CSSProperties={textAlign:'left',padding:'11px 10px',borderBottom:'1px solid var(--ugo-color-outline-variant)',color:'var(--ugo-color-on-surface-variant)',fontSize:10,textTransform:'uppercase',letterSpacing:'.04em'}
const td:React.CSSProperties={padding:'12px 10px',borderBottom:'1px solid var(--ugo-color-outline-variant)',verticalAlign:'middle',color:'var(--ugo-color-on-surface)'}

export function AdminOverviewNative(){
 const{metrics,loading}=useDashboardMetrics();const k=useConversionKPIs()
 if(loading&&!metrics)return <div style={box}>Cargando operación…</div>
 const cards=[['Servicios activos',metrics?.servicios_activos],['Proveedores online',metrics?.proveedores_online],['Clientes',metrics?.clientes_total],['Disputas abiertas',metrics?.disputas_abiertas],['Ingresos hoy',money(metrics?.ingresos_hoy)],['Bóveda',money(metrics?.boveda_total)],['Conversión',k?.conversion_pct!=null?`${Number(k.conversion_pct).toFixed(1)}%`:'—'],['Comisión 30d',money(k?.comision_total)]]
 return <div style={grid}>{cards.map(([a,b])=><article key={String(a)} style={box}><small style={{fontWeight:800,color:'#667085'}}>{a}</small><strong style={{display:'block',fontSize:28,marginTop:7}}>{b??0}</strong></article>)}</div>
}

export function AdminServicesNative(){
 const{services,loading,refetch}=useActiveServices();
 return <div style={box}><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><strong>Servicios</strong><button onClick={refetch}>Actualizar</button></div>{loading?<p>Cargando…</p>:<div style={{overflowX:'auto'}}><table style={table}><thead><tr><th style={th}>Estado</th><th style={th}>Servicio</th><th style={th}>Cliente</th><th style={th}>Proveedor</th><th style={th}>Tarifa</th><th style={th}>Fecha</th></tr></thead><tbody>{services.map((s:any)=><tr key={s.id}><td style={td}><b>{s.estado}</b></td><td style={td}>{s.categorias?.emoji} {s.categorias?.nombre||s.descripcion||'Servicio'}</td><td style={td}>{s.clientes?.nombre||'—'}</td><td style={td}>{s.proveedores?.nombre||'Sin asignar'}</td><td style={td}>{money(s.tarifa)}</td><td style={td}>{when(s.created_at)}</td></tr>)}</tbody></table>{!services.length&&<p>Sin servicios registrados.</p>}</div>}</div>
}

export function AdminAlertsNative(){
 const{alerts,criticalCount,warningCount,refetch}=useSystemAlerts();
 return <div><div style={{...grid,marginBottom:10}}><article style={box}><small>Críticas</small><strong style={{display:'block',fontSize:28}}>{criticalCount}</strong></article><article style={box}><small>Advertencias</small><strong style={{display:'block',fontSize:28}}>{warningCount}</strong></article><button style={box} onClick={refetch}>↻ Actualizar alertas</button></div>{alerts.map((a:any,i)=><article key={a.id||i} style={{...box,marginBottom:8,borderLeft:`4px solid ${a.severidad==='critical'?'#d92d20':a.severidad==='warning'?'#dc6803':'#1570ef'}`}}><strong>{a.titulo||a.tipo||'Alerta'}</strong><p style={{marginBottom:0,color:'#667085'}}>{a.descripcion||a.mensaje||JSON.stringify(a.detalles||{})}</p></article>)}{!alerts.length&&<div style={box}>Sin alertas activas.</div>}</div>
}

export function AdminDisputesNative(){
 const{disputes,loading,resolverDisputa}=useOpenDisputes();const[selected,setSelected]=useState<any>(null);const[text,setText]=useState('');const[favor,setFavor]=useState<'cliente'|'proveedor'>('cliente');const[message,setMessage]=useState('')
 const resolve=async()=>{if(!selected||text.trim().length<8)return;const ok=window.confirm(`Resolver ${selected.numero||selected.id.slice(0,8)} a favor de ${favor}. Esta decisión modifica el cierre financiero y queda auditada. ¿Confirmar?`);if(!ok)return;setMessage('');try{await resolverDisputa(selected.id,text.trim(),favor);setSelected(null);setText('');setMessage('Disputa resuelta y auditada.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo resolver la disputa.')}}
 return <div style={box}>{loading?<p>Cargando…</p>:<><table style={table}><thead><tr><th style={th}>Caso</th><th style={th}>Motivo</th><th style={th}>Monto</th><th style={th}>Partes</th><th style={th}></th></tr></thead><tbody>{disputes.map((d:any)=><tr key={d.id}><td style={td}><b>{d.numero||d.id.slice(0,8)}</b><br/><small>{d.estado}</small></td><td style={td}>{d.motivo}</td><td style={td}>{money(d.monto_disputado)}</td><td style={td}>{d.clientes?.nombre||'Cliente'} / {d.proveedores?.nombre||'Proveedor'}</td><td style={td}><button onClick={()=>setSelected(d)}>Resolver</button></td></tr>)}</tbody></table>{!disputes.length&&<p>Sin disputas abiertas.</p>}</>}{selected&&<div style={{marginTop:14,paddingTop:14,borderTop:'1px solid #e4e7ec'}}><strong>Resolver {selected.numero}</strong><div style={{display:'flex',gap:8,margin:'10px 0'}}><button onClick={()=>setFavor('cliente')} disabled={favor==='cliente'}>A favor cliente</button><button onClick={()=>setFavor('proveedor')} disabled={favor==='proveedor'}>A favor proveedor</button></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Resolución y justificación (mínimo 8 caracteres)" style={{width:'100%',minHeight:90,padding:10}}/><button onClick={()=>void resolve()} disabled={text.trim().length<8} style={{marginTop:8}}>Revisar y confirmar resolución</button></div>}{message&&<p role="status" style={{fontWeight:700}}>{message}</p>}</div>
}

export function AdminMapNative(){return <div style={{height:'100%',minHeight:560}}><SecMapaOperativo/></div>}
export function AdminScoutNative(){return <div style={{height:'100%',overflow:'auto'}}><SecScout/></div>}
export function AdminKycNative(){return <SecValidacionPaises/>}
export function AdminImportNative(){return <SecImportProviders/>}

export function AdminDocumentsNative(){
 const{docs,loading,updateEstado,getSignedUrl}=usePendingDocuments();const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState('')
 const open=async(d:any)=>{setBusy(d.id);setMessage('');try{const u=await getSignedUrl(d.url_storage);if(!u)throw new Error('No se pudo generar un acceso privado al documento.');window.open(u,'_blank','noopener,noreferrer')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo abrir el documento.')}finally{setBusy(null)}}
 const approve=async(d:any)=>{const ok=window.confirm(`Aprobar ${d.tipo} de ${d.usuarios?.nombre||'este proveedor'}? La decisión queda asociada a tu usuario Admin y auditada.`);if(!ok)return;setBusy(d.id);setMessage('');try{await updateEstado(d.id,'aprobado','Aprobado después de revisión manual en Admin UGO');setMessage('Documento aprobado.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo aprobar el documento.')}finally{setBusy(null)}}
 const reject=async(d:any)=>{const raw=window.prompt(`Motivo de rechazo para ${d.tipo}. Indicá qué debe corregir el proveedor (mínimo 8 caracteres).`,'');if(raw===null)return;const reason=raw.trim();if(reason.length<8){setMessage('El motivo de rechazo debe tener al menos 8 caracteres.');return}const ok=window.confirm(`Rechazar ${d.tipo} de ${d.usuarios?.nombre||'este proveedor'}?\nMotivo: ${reason}\nLa decisión queda auditada.`);if(!ok)return;setBusy(d.id);setMessage('');try{await updateEstado(d.id,'rechazado',undefined,reason);setMessage('Documento rechazado con motivo registrado.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo rechazar el documento.')}finally{setBusy(null)}}
 return <div style={box} className="ugo-admin-documents">{loading?<div className="ugo-admin-documents-loading">Cargando documentos…</div>:<>{docs.length?<div className="ugo-admin-documents-scroll"><table style={table}><thead><tr><th style={th}>Proveedor</th><th style={th}>Documento</th><th style={th}>Estado</th><th style={th}>OCR</th><th style={th}>Fecha</th><th style={th}>Acciones</th></tr></thead><tbody>{docs.map((d:any)=><tr key={d.id}><td style={td}><strong className="ugo-admin-documents-provider">{d.usuarios?.nombre||'Proveedor'} {d.usuarios?.apellido||''}</strong></td><td style={td}><span className="ugo-admin-documents-type">{String(d.tipo||'Documento').replace(/_/g,' ')}</span></td><td style={td}><span className={`ugo-admin-documents-status ${String(d.estado||'pendiente').toLowerCase()}`}>{d.estado||'pendiente'}</span></td><td style={td}>{typeof d.ocr_confianza==='number'?<span className="ugo-admin-documents-ocr">{Math.round(d.ocr_confianza*100)}%</span>:<span className="ugo-admin-documents-muted">Sin OCR</span>}</td><td style={td}><span className="ugo-admin-documents-date">{when(d.created_at)}</span></td><td style={td}><div className="ugo-admin-documents-actions"><button className="view" onClick={()=>void open(d)} disabled={busy===d.id}>{busy===d.id?'Procesando…':'Ver'}</button><button className="approve" onClick={()=>void approve(d)} disabled={busy===d.id}>Aprobar</button><button className="reject" onClick={()=>void reject(d)} disabled={busy===d.id}>Rechazar</button></div></td></tr>)}</tbody></table></div>:<div className="ugo-admin-documents-empty"><strong>Sin documentos pendientes</strong><span>No hay documentación esperando revisión.</span></div>}</>}{message&&<p className="ugo-admin-documents-message" role="status">{message}</p>}</div>
}

export function AdminVaultNative(){
 const{escrows}=useVault();const withdrawals=usePendingWithdrawals();const total=useMemo(()=>escrows.reduce((a:any,e:any)=>a+Number(e.monto_total||0),0),[escrows])
 return <div><div style={{...grid,marginBottom:10}}><article style={box}><small>Retenido</small><strong style={{display:'block',fontSize:27}}>{money(total)}</strong></article><article style={box}><small>Escrows</small><strong style={{display:'block',fontSize:27}}>{escrows.length}</strong></article><article style={box}><small>Retiros pendientes</small><strong style={{display:'block',fontSize:27}}>{withdrawals.length}</strong></article></div><div style={box}><p>Vista histórica de bóveda. Las acciones de dinero real se procesan exclusivamente desde <b>Finanzas · Bóveda y retiros</b>, con confirmación y referencia externa.</p></div></div>
}

export function AdminTariffsNative(){return <AdminTariffsPanel/>}

export function AdminCategoriesNative(){
 const{categorias,toggleActiva}=useCategorias();const toggle=async(c:any)=>{const next=!c.activa;const ok=window.confirm(`${next?'Activar':'Desactivar'} la categoría “${c.nombre}”? El cambio afecta la disponibilidad del catálogo para nuevos pedidos.`);if(!ok)return;await toggleActiva(c.id,next)};return <div style={{display:'grid',gap:8}}>{categorias.map((c:any)=><article key={c.id} style={{...box,display:'flex',alignItems:'center',gap:10,opacity:c.activa?1:.6}}><span style={{fontSize:24}}>{c.emoji}</span><div style={{flex:1}}><strong>{c.nombre}</strong><small style={{display:'block',color:'#667085'}}>{c.subcategorias?.length||0} subcategorías</small></div><button onClick={()=>void toggle(c)}>{c.activa?'Desactivar':'Activar'}</button></article>)}</div>
}

export function AdminSystemNative(){
 const{config,loading,error,update,refetch}=useConfigSistema();
 const entries=Object.entries(config||{}).filter(([k])=>!k.startsWith('api_'));
 if(loading)return <div style={{...box,minHeight:130,display:'grid',placeItems:'center',color:'#667085'}}>Cargando configuración del sistema…</div>;
 if(error)return <div style={{...box,borderColor:'#fecdca',background:'#fffafa'}}><small style={{fontWeight:900,color:'#b42318'}}>NO SE PUDO CARGAR CONFIGURACIÓN</small><p style={{color:'#667085'}}>{error}</p><button onClick={()=>{void refetch()}}>Reintentar</button></div>;
 if(!entries.length)return <div style={{display:'grid',gap:12}}><section style={{...box,borderColor:'#fedf89',background:'#fffcf5'}}><small style={{fontWeight:900,color:'#b54708'}}>CONFIGURACIÓN DEL SISTEMA</small><h3 style={{margin:'7px 0 5px'}}>Todavía no hay parámetros visibles</h3><p style={{margin:0,color:'#667085',lineHeight:1.5}}>La conexión funciona, pero la tabla <b>config_sistema</b> no devolvió parámetros administrables. No se muestran claves API ni secretos en esta pantalla.</p></section><section style={{...box,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><div><small style={{color:'#667085'}}>ESTADO</small><strong style={{display:'block',marginTop:5}}>Sin parámetros</strong></div><div><small style={{color:'#667085'}}>ORIGEN</small><strong style={{display:'block',marginTop:5}}>config_sistema</strong></div><div><small style={{color:'#667085'}}>ACCIÓN</small><button style={{marginTop:5}} onClick={()=>{void refetch()}}>↻ Volver a cargar</button></div></section></div>;
 return <div style={{display:'grid',gap:12}}><section style={{...box,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><small style={{fontWeight:900,color:'#667085'}}>PARÁMETROS ADMINISTRABLES</small><strong style={{display:'block',fontSize:22,marginTop:4}}>{entries.length}</strong></div><button onClick={()=>{void refetch()}}>↻ Actualizar</button></section><section style={box}>{entries.map(([k,v]:any)=><label key={k} style={{display:'grid',gridTemplateColumns:'minmax(180px,1fr) minmax(220px,2fr)',gap:10,padding:'10px 0',borderBottom:'1px solid #f2f4f7',alignItems:'center'}}><span><b style={{display:'block'}}>{k.replace(/_/g,' ')}</b><small style={{color:'#98a2b3'}}>{k}</small></span><input defaultValue={String(v??'')} onBlur={async e=>{const next=e.target.value;if(next===String(v??''))return;const ok=window.confirm(`Cambiar “${k}” de “${String(v??'')}” a “${next}”? El cambio queda auditado.`);if(ok)await update(k,next);else e.target.value=String(v??'')}} style={{minHeight:40,border:'1px solid #d0d5dd',borderRadius:10,padding:'0 10px'}}/></label>)}</section></div>
}

export function AdminNotificationsNative(){
 const{hist,enviar}=useNotificaciones();const[titulo,setTitulo]=useState('');const[cuerpo,setCuerpo]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const send=async()=>{const title=titulo.trim(),body=cuerpo.trim();if(!title||!body)return;const ok=window.confirm(`Enviar esta notificación a todos los usuarios activos de UGO?\n\n${title}\n${body}\n\nEl envío queda auditado.`);if(!ok)return;setBusy(true);setMessage('');try{const count=await enviar(title,body,'todos');setTitulo('');setCuerpo('');setMessage(`Notificación enviada a ${Number(count||0)} usuario(s).`)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo enviar la notificación.')}finally{setBusy(false)}}
 return <div><div style={{...box,marginBottom:10}}><strong>Enviar notificación</strong><input value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="Título" style={{width:'100%',marginTop:10,padding:9}}/><textarea value={cuerpo} onChange={e=>setCuerpo(e.target.value)} placeholder="Mensaje" style={{width:'100%',minHeight:90,marginTop:8,padding:9}}/><button onClick={()=>void send()} disabled={busy||!titulo.trim()||!cuerpo.trim()}>{busy?'Enviando…':'Revisar y enviar a todos'}</button>{message&&<p role="status">{message}</p>}</div><div style={box}><strong>Historial</strong>{(hist||[]).slice(0,30).map((n:any)=><div key={n.id} style={{padding:'8px 0',borderBottom:'1px solid #f2f4f7'}}><b>{n.titulo}</b><small style={{display:'block',color:'#667085'}}>{n.cuerpo} · {when(n.created_at)}</small></div>)}</div></div>
}

export function AdminReportsNative(){
 const{exportServicios,exportUsuarios}=useExport();return <div style={grid}><button style={box} onClick={()=>{void exportServicios()}}><strong>Exportar servicios</strong><span style={{display:'block',color:'#667085',marginTop:5}}>Preparar datos de operación</span></button><button style={box} onClick={()=>{void exportUsuarios()}}><strong>Exportar usuarios</strong><span style={{display:'block',color:'#667085',marginTop:5}}>Preparar datos de personas</span></button></div>
}
