import React,{useMemo,useState}from'react'
import{AutonomousWorkforceControlCenter}from'./AutonomousWorkforceControlCenter'
import'./autonomous-corporation.css'
type View='overview'|'departments'|'agents'|'inbox'|'ledgers'|'audit'|'qa'|'models'|'launch'|'empresas'|'controls'
const views:[View,string][]=[['overview','Centro de mando'],['departments','Departamentos'],['agents','Agentes IA'],['inbox','Inbox ejecutivo'],['ledgers','Ledgers'],['audit','Riesgo & Auditoría'],['qa','QA Lab'],['models','Model Router'],['launch','Launch Gate'],['empresas','UGO Empresas'],['controls','Kill Switch']]
const active=(s:string)=>['QUEUED','RUNNING','WAITING_APPROVAL','BLOCKED'].includes(s)
const card=(label:string,value:React.ReactNode,detail?:string)=><article className="ugo-admin2-module-card"><small>{label.toUpperCase()}</small><strong style={{display:'block',fontSize:26,margin:'5px 0'}}>{value}</strong>{detail&&<span>{detail}</span>}</article>
export function AutonomousCorporationDashboard(p:{autonomy:any;departments:any[];agents:any[];jobs:any[];decisions:any[];evidence:any[];findings:any[];killSwitches:any[];qaSimulators:any[];qaScenarios:any[];qaRuns:any[];qaCoverage:any[];releaseGate:any;modelCandidates:any[];modelRoutes:any[];modelMetrics:any[];riskMap:any[];controlCoverage:any[];challenges:any[];empresasReadiness:any;authorized:boolean;db:any;reload:()=>void;setError:(s:string)=>void;onDecision:(id:string,approve:boolean)=>void;onKillSwitch:(scopeType:string,scopeKey:string,enabled:boolean)=>void;onModeChange:(mode:string)=>void;onEvaluateGate:()=>void}){
 const[v,setV]=useState<View>('overview'),[search,setSearch]=useState('')
 const pending=p.jobs.filter(j=>j.status==='WAITING_APPROVAL'||j.status==='BLOCKED'),openFindings=p.findings.filter(x=>x.status!=='CLOSED'),enabledAgents=p.agents.filter(a=>a.status!=='DISABLED')
 const timeline=useMemo(()=>{const q=search.trim();if(!q)return[];return p.jobs.filter(j=>[j.correlation_id,j.id,j.service_id].some(x=>String(x||'').includes(q))).slice(0,20)},[search,p.jobs])
 const shell:React.CSSProperties={display:'grid',gridTemplateColumns:'minmax(150px,190px) minmax(0,1fr)',gap:12},grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8}
 return <div style={shell} className="ugo-autonomous-corporation"><aside className="ugo-admin2-module-card ugo-autonomous-nav" style={{alignSelf:'start',display:'grid',gap:4,padding:8}}><small style={{padding:'7px 8px'}}>EMPRESA AUTÓNOMA</small>{views.map(([id,label])=><button key={id} type="button" className={v===id?'active':''} onClick={()=>setV(id)} style={{textAlign:'left'}}>{label}</button>)}</aside><div className="ugo-autonomous-content" style={{minWidth:0,display:'grid',gap:12}}>
 <header className="ugo-admin2-module-card"><small>SUPER ADMIN · CONTROL CORPORATIVO</small><h3 style={{margin:'5px 0'}}>UGO Empresa Autónoma</h3><p style={{margin:'0 0 8px'}}>Control sobre estado persistido real. Ninguna actividad se inventa para completar el tablero.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><span><strong>Modo:</strong> {p.autonomy?.mode||'NO INICIALIZADO'}</span><span>·</span><span><strong>Policy:</strong> {p.autonomy?.policy_version||'—'}</span><span>·</span><span><strong>Launch:</strong> {p.releaseGate?.status||'NO EVALUADO'}</span></div></header>
 {v==='overview'&&<><div style={grid}>{card('Departamentos',p.departments.length)}{card('Agentes habilitados',enabledAgents.length,String(p.agents.length)+' persistidos')}{card('Jobs activos',p.jobs.filter(j=>active(j.status)).length)}{card('Findings abiertos',openFindings.length)}{card('Kill switches',p.killSwitches.filter(x=>x.enabled).length,'activos')}{card('Customer #1',p.releaseGate?.status||'NO EVALUADO')}</div><section className="ugo-admin2-module-card"><h3>Estado ejecutivo</h3><p><strong>Prioridad:</strong> cerrar el journey real Cliente → Proveedor ≤20 km → GPS/llegada → evidencia → trabajo → aprobación → pago → rating → auditoría.</p><p><strong>Excepciones:</strong> {pending.length?String(pending.length)+' requieren atención':'sin jobs persistidos esperando intervención'}.</p><p><strong>QA:</strong> {p.qaCoverage.filter(x=>x.status==='COVERED').length}/{p.qaCoverage.length} controles de cobertura marcados COVERED.</p></section></>}
 {v==='departments'&&<section className="ugo-admin2-module-card"><h3>Departamentos corporativos</h3>{p.departments.length?<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>#</th><th>Departamento</th><th>Estado</th><th>Agentes</th><th>Jobs activos</th><th>Última acción</th></tr></thead><tbody>{p.departments.map(d=><tr key={d.department_id}><td>D{d.department_id}</td><td><strong>{d.name}</strong><small style={{display:'block'}}>{d.objective}</small></td><td>{d.status}</td><td>{p.agents.filter(a=>a.department_id===d.department_id).length}</td><td>{p.jobs.filter(j=>j.department_id===d.department_id&&active(j.status)).length}</td><td>{d.last_action_at?new Date(d.last_action_at).toLocaleString('es-AR'):'—'}</td></tr>)}</tbody></table></div>:<p>Sin departamentos persistidos. No se muestran departamentos ficticios.</p>}</section>}
 {v==='agents'&&<AutonomousWorkforceControlCenter agents={p.agents} jobs={p.jobs} departments={p.departments} decisions={p.decisions} evidence={p.evidence} findings={p.findings} killSwitches={p.killSwitches} authorized={p.authorized} db={p.db} reload={p.reload} setError={p.setError} onDecision={p.onDecision} onKillSwitch={p.onKillSwitch}/>}
 {v==='inbox'&&<section className="ugo-admin2-module-card"><h3>Inbox ejecutivo</h3><p><strong>Decisión directa:</strong> no hace falta escribir un motivo. UGO registra automáticamente que la decisión fue tomada desde Super Admin.</p>{p.autonomy?.mode!=='ON'&&<div role="status" className="ugo-superadmin-inline-warning"><strong>Autonomía {p.autonomy?.mode||'OFF'}.</strong> Podés revisar o rechazar trabajos, pero una aprobación no podrá entrar en ejecución hasta que el modo corporativo sea ON.</div>}{pending.length?pending.map(j=>{const yellow=j.authority_class==='YELLOW',first=Number(j.approval_count||0)===1;return <article key={j.id} className="ugo-autonomous-inbox-job"><div><strong>{j.objective||'Trabajo autónomo'}</strong><small style={{display:'block'}}>D{j.department_id} · Autoridad {j.authority_class} · {j.status}</small>{yellow&&<small style={{display:'block'}}>{first?'Primera aprobación registrada · falta un segundo Super Admin distinto':'Requiere 2 aprobaciones de Super Admin distintos'}</small>}{j.blocked_reason&&<small style={{display:'block'}}>Motivo actual: {j.blocked_reason}</small>}</div>{j.status==='WAITING_APPROVAL'&&<div className="ugo-autonomous-decision-actions"><button type="button" className="ugo-autonomous-approve" disabled={p.autonomy?.mode!=='ON'} title={p.autonomy?.mode!=='ON'?'Activá modo ON para autorizar ejecución':''} onClick={()=>p.onDecision(j.id,true)}>{yellow?(first?'Aprobar 2/2':'Aprobar 1/2'):'Aprobar'}</button><button type="button" className="ugo-autonomous-reject" onClick={()=>p.onDecision(j.id,false)}>Rechazar</button></div>}</article>}):<p>No hay excepciones persistidas que requieran intervención.</p>}</section>}
 {v==='ledgers'&&<><div style={grid}>{card('Decision Ledger',p.decisions.length)}{card('Evidence Ledger',p.evidence.length)}{card('Jobs',p.jobs.length)}</div><section className="ugo-admin2-module-card"><h3>Timeline por correlación</h3><input style={{width:'100%'}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="correlation_id, job id o serviceId"/>{search.trim()?(timeline.length?timeline.map(j=><div key={j.id} style={{padding:'9px 0',borderTop:'1px solid rgba(127,127,127,.2)'}}><strong>{j.status} · {j.authority_class}</strong> · {j.objective}<small style={{display:'block'}}>serviceId {j.service_id||'—'} · correlation {j.correlation_id}</small>{p.decisions.filter(d=>d.job_id===j.id||d.correlation_id===j.correlation_id).map(d=><small key={d.id} style={{display:'block'}}>DECISION · {d.decision} · {d.reason}</small>)}{p.evidence.filter(e=>e.job_id===j.id||e.correlation_id===j.correlation_id).map(e=><small key={e.id} style={{display:'block'}}>EVIDENCE · {e.evidence_type} · {e.reference}</small>)}</div>):<p>Sin coincidencias.</p>):<p>Ingresá un identificador. No se generan timelines ficticios.</p>}</section></>}
 {v==='audit'&&<><div style={grid}>{card('Riesgos',p.riskMap.length)}{card('Controles',p.controlCoverage.length)}{card('Challenges D14',p.challenges.length)}{card('Findings abiertos',openFindings.length)}</div><section className="ugo-admin2-module-card"><h3>Control Coverage Map</h3>{p.controlCoverage.length?p.controlCoverage.map(x=><p key={x.id}><strong>{x.control_key}</strong> — {x.status}<small style={{display:'block'}}>{x.control_description}</small></p>):<p>Sin controles persistidos.</p>}<h3>Findings</h3>{openFindings.length?openFindings.map(x=><p key={x.id}><strong>{x.severity} · {x.finding_type}</strong> — D{x.department_id||'—'} · {x.status}<small style={{display:'block'}}>{x.description}</small></p>):<p>Sin findings abiertos persistidos.</p>}</section></>}
 {v==='qa'&&<><div style={grid}>{card('Simuladores',p.qaSimulators.length)}{card('Escenarios',p.qaScenarios.length)}{card('Runs',p.qaRuns.length)}{card('Coverage',String(p.qaCoverage.filter(x=>x.status==='COVERED').length)+'/'+String(p.qaCoverage.length))}</div><section className="ugo-admin2-module-card"><h3>Quality Coverage Map</h3>{p.qaCoverage.length?p.qaCoverage.map(x=><p key={x.id}><strong>{x.coverage_key}</strong> — {x.status}<small style={{display:'block'}}>{x.requirement}</small></p>):<p>Sin cobertura persistida.</p>}</section></>}
 {v==='models'&&<><div style={grid}>{card('Candidatos',p.modelCandidates.length)}{card('Rutas',p.modelRoutes.length)}{card('Métricas',p.modelMetrics.length)}</div><section className="ugo-admin2-module-card"><h3>Model Router · zero-budget-first</h3>{p.modelRoutes.length?p.modelRoutes.map(r=><p key={r.id}><strong>{r.task_class}</strong> — {r.status} · costo máximo {r.max_cost}<small style={{display:'block'}}>primary {r.primary_candidate_id||'sin seleccionar'} · fallback {r.fallback_candidate_id||'sin seleccionar'}</small></p>):<p>No hay rutas persistidas.</p>}</section></>}
 {v==='launch'&&<section className="ugo-admin2-module-card"><small>CUSTOMER #1</small><h3>Launch Gate · {p.releaseGate?.status||'NO EVALUADO'}</h3>{p.releaseGate?.blockers?.length?<><strong>Bloqueadores</strong>{p.releaseGate.blockers.map((b:string)=><p key={b}>● {b}</p>)}</>:<p>No hay bloqueadores persistidos o el gate aún no fue evaluado.</p>}<button type="button" onClick={p.onEvaluateGate}>Evaluar Launch Gate</button></section>}
 {v==='empresas'&&<section className="ugo-admin2-module-card"><h3>UGO Empresas</h3>{p.empresasReadiness?<><p><strong>D{p.empresasReadiness.owner_department_id} · {p.empresasReadiness.stage} · {p.empresasReadiness.status}</strong></p><p>Blockers: {(p.empresasReadiness.blockers||[]).join(', ')||'ninguno persistido'}</p></>:<p>Readiness no disponible. No se inventa estado de piloto.</p>}<p>Flujo: demanda empresa → slots → matching → workers + backups → reconfirmación → check-in → reemplazo → validación → settlement → reporte.</p></section>}
 {v==='controls'&&<><section className="ugo-admin2-module-card"><h3>Modo global de autonomía</h3><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['OFF','SHADOW','ON','SAFE_MODE'].map(mode=><button key={mode} className={p.autonomy?.mode===mode?'active':''} onClick={()=>p.onModeChange(mode)}>{mode}</button>)}</div><p><strong>OFF</strong> observa · <strong>SHADOW</strong> simula · <strong>ON</strong> ejecuta sólo lo autorizado · <strong>SAFE_MODE</strong> contiene riesgo.</p></section><section className="ugo-admin2-module-card"><h3>Kill Switches</h3>{p.killSwitches.length?p.killSwitches.map(s=><div key={s.id} style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',padding:'7px 0'}}><span><strong>{s.scope_type} · {s.scope_key}</strong> — {s.enabled?'ACTIVO':'inactivo'}{s.reason?' · '+s.reason:''}</span><button onClick={()=>p.onKillSwitch(s.scope_type,s.scope_key,!s.enabled)}>{s.enabled?'Recuperar':'Activar'}</button></div>):<p>No hay kill switches persistidos.</p>}</section></>}
 </div></div>
}