import React,{useMemo,useState}from'react'

const HUMAN_STATUS:Record<string,string>={DISABLED:'Deshabilitado',IDLE:'Disponible',RUNNING:'Trabajando',WAITING_APPROVAL:'Esperando aprobación',FAILED:'Error',PAUSED:'Pausado',QUEUED:'En cola',BLOCKED:'Bloqueado'}
const AUTH:Record<string,string>={GREEN:'Puede ejecutar automáticamente acciones seguras.',YELLOW:'Necesita aprobación de dos administradores.',RED:'Necesita aprobación humana explícita.'}
const activeJob=(jobs:any[],id:string)=>jobs.find((j:any)=>j.agent_id===id&&['QUEUED','RUNNING','WAITING_APPROVAL','BLOCKED'].includes(j.status))
const MATURITY_LABEL:Record<string,string>={CATALOGED:'Catalogado',ENABLED:'Habilitado',EXECUTED:'Ejecutado',VERIFIED:'Verificado'}
const maturityFor=(agent:any,jobs:any[],evidence:any[])=>{
 if(agent.status==='DISABLED')return 'CATALOGED'
 const agentJobs=jobs.filter((j:any)=>j.agent_id===agent.id)
 const executed=agentJobs.some((j:any)=>j.status==='SUCCEEDED')
 if(!executed)return 'ENABLED'
 const ids=new Set(agentJobs.map((j:any)=>j.id))
 const judge=evidence.some((e:any)=>ids.has(e.job_id)&&e.evidence_type==='AGENT_JUDGE_PROOF')
 const sentinel=evidence.some((e:any)=>ids.has(e.job_id)&&e.evidence_type==='AGENT_SENTINEL_PROOF')
 return judge&&sentinel?'VERIFIED':'EXECUTED'
}
export function AutonomousWorkforceControlCenter({agents,jobs,departments,decisions,evidence,findings,killSwitches,authorized,db,reload,setError,onDecision,onKillSwitch}:{agents:any[];jobs:any[];departments:any[];decisions:any[];evidence:any[];findings:any[];killSwitches:any[];authorized:boolean;db:any;reload:()=>void;setError:(s:string)=>void;onDecision:(id:string,approve:boolean)=>void;onKillSwitch:(scopeType:string,scopeKey:string,enabled:boolean)=>void}){
 const[q,setQ]=useState(''),[dept,setDept]=useState('ALL'),[status,setStatus]=useState('ALL'),[maturity,setMaturity]=useState('ALL'),[authority,setAuthority]=useState('ALL'),[attention,setAttention]=useState(false),[selected,setSelected]=useState<any>(null),[tab,setTab]=useState('Resumen'),[page,setPage]=useState(0),[busy,setBusy]=useState(''),[consultQuestion,setConsultQuestion]=useState(''),[consultAnswer,setConsultAnswer]=useState(''),[consulting,setConsulting]=useState(false)
 const pageSize=20
 const rows=useMemo(()=>agents.filter(a=>{const job=activeJob(jobs,a.id);const effective=job?.status||a.status;const agentMaturity=maturityFor(a,jobs,evidence);return(!q||String(a.name+' '+a.agent_key+' '+a.capability).toLowerCase().includes(q.toLowerCase()))&&(dept==='ALL'||String(a.department_id)===dept)&&(status==='ALL'||effective===status)&&(maturity==='ALL'||agentMaturity===maturity)&&(authority==='ALL'||a.authority_class===authority)&&(!attention||['WAITING_APPROVAL','FAILED','BLOCKED'].includes(effective)||killSwitches.some(s=>s.enabled&&((s.scope_type==='AGENT'&&s.scope_key===a.id)||(s.scope_type==='DEPARTMENT'&&s.scope_key===String(a.department_id))||s.scope_type==='GLOBAL')))}),[agents,jobs,evidence,q,dept,status,maturity,authority,attention,killSwitches])
 const counts={total:agents.length,active:agents.filter(a=>a.status!=='DISABLED').length,running:jobs.filter(j=>j.status==='RUNNING').length,paused:agents.filter(a=>a.status==='PAUSED').length,disabled:agents.filter(a=>a.status==='DISABLED').length,approval:jobs.filter(j=>j.status==='WAITING_APPROVAL').length,error:jobs.filter(j=>j.status==='FAILED').length,contained:killSwitches.filter(s=>s.enabled).length}
 const execute=async(a:any)=>{if(!authorized||a.status==='DISABLED')return;setBusy(a.id);setError('');try{const key='superadmin:'+a.agent_key+':'+Date.now();const{error}=await db.rpc('autonomous_enqueue_job',{p_department_id:a.department_id,p_agent_id:a.id,p_objective:a.capability||('Ejecutar '+a.name),p_trigger_type:'SUPERADMIN_MANUAL',p_target_type:'AGENT',p_target_id:a.id,p_service_id:null,p_authority_class:a.authority_class,p_idempotency_key:key,p_input_evidence:[]});if(error)throw error;reload()}catch(e){setError(e instanceof Error?e.message:'No se pudo crear el trabajo.')}finally{setBusy('')}}
 const consultAgent=async()=>{if(!selected||selected.status==='DISABLED'||consulting)return;const q=consultQuestion.trim();if(!q)return;setConsulting(true);setConsultAnswer('Consultando evidencia persistida autorizada…');try{const{data:{session}}=await db.auth.getSession();if(!session)throw new Error('SESIÓN REQUERIDA');const response=await fetch('/api/test?ugo_autonomy_model=1',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({agent_id:selected.id,question:q})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Model Router no disponible');setConsultAnswer(`${payload.answer}\n\nModelo: ${payload.model} · correlation_id: ${payload.correlation_id}`)}catch(e){setConsultAnswer(`NO SE PUDO CONSULTAR EL MODEL ROUTER. ${e instanceof Error?e.message:''}`.trim())}finally{setConsulting(false)}}
 const cards=[['Total agentes',counts.total],['Activos',counts.active],['Trabajando ahora',counts.running],['Pausados',counts.paused],['Deshabilitados',counts.disabled],['Esperando aprobación',counts.approval],['Con error',counts.error],['Bloqueados por seguridad',counts.contained]]
 const selectedJobs=selected?jobs.filter(j=>j.agent_id===selected.id):[],ids=new Set(selectedJobs.map(j=>j.id)),selectedDecisions=selected?decisions.filter(d=>d.agent_id===selected.id||ids.has(d.job_id)):[],selectedEvidence=selected?evidence.filter(e=>ids.has(e.job_id)):[],selectedFindings=selected?findings.filter(f=>ids.has(f.job_id)):[]
 return <section style={{display:'grid',gap:12}}>
  <div><small>UGO AI WORKFORCE CONTROL CENTER</small><h3 style={{margin:'4px 0'}}>Trabajadores de IA</h3><p style={{margin:0}}>Control operativo sobre estado persistido real. Las acciones no disponibles se explican, no se simulan.</p></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:8}}>{cards.map(([l,v])=><article className="ugo-admin2-module-card" key={String(l)}><small>{String(l).toUpperCase()}</small><strong style={{display:'block',fontSize:25}}>{String(v)}</strong></article>)}</div>
  <div className="ugo-admin2-module-card" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8}}>
   <input aria-label="Buscar agente" placeholder="Buscar agente…" value={q} onChange={e=>{setQ(e.target.value);setPage(0)}}/>
   <select aria-label="Departamento" value={dept} onChange={e=>{setDept(e.target.value);setPage(0)}}><option value="ALL">Todos los departamentos</option>{departments.map(d=><option key={d.department_id} value={String(d.department_id)}>D{d.department_id} — {d.name}</option>)}</select>
   <select aria-label="Estado" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="ALL">Todos los estados</option>{['RUNNING','IDLE','PAUSED','DISABLED','WAITING_APPROVAL','FAILED','BLOCKED'].map(s=><option key={s} value={s}>{HUMAN_STATUS[s]}</option>)}</select>
   <select aria-label="Madurez" value={maturity} onChange={e=>{setMaturity(e.target.value);setPage(0)}}><option value="ALL">Toda madurez</option>{['CATALOGED','ENABLED','EXECUTED','VERIFIED'].map(x=><option key={x} value={x}>{MATURITY_LABEL[x]}</option>)}</select>
   <select aria-label="Autoridad" value={authority} onChange={e=>{setAuthority(e.target.value);setPage(0)}}><option value="ALL">Toda autoridad</option>{['GREEN','YELLOW','RED'].map(x=><option key={x}>{x}</option>)}</select>
   <label style={{gridColumn:'1/-1'}}><input type="checkbox" checked={attention} onChange={e=>setAttention(e.target.checked)}/> Mostrar solo los que necesitan mi atención</label>
  </div>
  <div className="ugo-admin2-module-card"><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center'}}><h3 style={{margin:0}}>Agentes</h3><small>{rows.length} resultados · página {page+1} de {Math.max(1,Math.ceil(rows.length/pageSize))}</small></div>
   <div style={{display:'grid',gap:7,marginTop:10}}>{rows.slice(page*pageSize,(page+1)*pageSize).map(a=>{const job=activeJob(jobs,a.id),effective=job?.status||a.status,contained=killSwitches.some(s=>s.enabled&&((s.scope_type==='AGENT'&&s.scope_key===a.id)||(s.scope_type==='DEPARTMENT'&&s.scope_key===String(a.department_id))||s.scope_type==='GLOBAL'));return <article key={a.id} style={{border:'1px solid rgba(127,127,127,.25)',borderRadius:10,padding:10,display:'grid',gridTemplateColumns:'minmax(220px,1fr) auto',gap:10}}>
    <button type="button" onClick={()=>{setSelected(a);setTab('Resumen')}} style={{textAlign:'left',border:0,background:'transparent',padding:0}}><strong>{a.name}</strong><small style={{display:'block'}}>D{a.department_id} · {a.capability||'Función todavía no declarada'}</small><span>{HUMAN_STATUS[effective]||effective} · {MATURITY_LABEL[maturityFor(a,jobs,evidence)]} · Autoridad {a.authority_class}</span>{job&&<small style={{display:'block'}}>Trabajo: {job.objective}</small>}</button>
    <div style={{display:'flex',gap:6,flexWrap:'wrap',justifyContent:'flex-end'}}>
     {a.status!=='DISABLED'&&!contained&&<button type="button" disabled={busy===a.id} onClick={()=>void execute(a)}>{busy===a.id?'Creando…':'Ejecutar ahora'}</button>}
     {job?.status==='WAITING_APPROVAL'&&<button type="button" onClick={()=>onDecision(job.id,true)}>Aprobar {job.authority_class==='YELLOW'?String((job.approval_count||0)+1)+'/2':''}</button>}
     {a.status==='DISABLED'&&<button type="button" disabled title="Falta validación completa de ejecución">No listo para habilitar</button>}
     <button type="button" onClick={()=>onKillSwitch('AGENT',a.id,!contained)}>{contained?'Recuperar':'Kill switch'}</button>
     <button type="button" onClick={()=>setSelected(a)}>Ver actividad</button>
    </div>
   </article>})}</div>
   {!rows.length&&<p>No hay agentes que coincidan con los filtros.</p>}
   <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:10}}><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))}>Anterior</button><button disabled={(page+1)*pageSize>=rows.length} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div>
  </div>
  {selected&&<div role="dialog" aria-label="Detalle del agente" className="ugo-admin2-module-card" style={{position:'fixed',right:12,top:70,bottom:12,width:'min(560px,calc(100vw - 24px))',zIndex:50,overflow:'auto',boxShadow:'0 16px 60px rgba(0,0,0,.25)'}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:8}}><div><small>D{selected.department_id} · {selected.agent_key}</small><h3>{selected.name}</h3></div><button onClick={()=>setSelected(null)} aria-label="Cerrar">×</button></div>
   <p>{selected.capability||'Función todavía no declarada.'}</p><p><strong>{HUMAN_STATUS[activeJob(jobs,selected.id)?.status||selected.status]||selected.status}</strong> · Madurez {MATURITY_LABEL[maturityFor(selected,jobs,evidence)]} · Autoridad {selected.authority_class}</p><p><small title={AUTH[selected.authority_class]}>¿Qué significa {selected.authority_class}?</small> {AUTH[selected.authority_class]}</p>
   {selected.status==='DISABLED'&&<div role="status"><strong>NO LISTO PARA HABILITAR</strong><p>Este trabajador todavía está en preparación. Falta validación completa de ejecución. UGO no habilita especialistas sólo para completar el tablero.</p></div>}
   <nav style={{display:'flex',gap:5,flexWrap:'wrap'}}>{['Resumen','Actividad','Decisiones','Evidencia','Configuración','Auditoría'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
   {tab==='Resumen'&&<div><h4>¿Qué está haciendo?</h4>{selectedJobs.length?selectedJobs.slice(0,5).map(j=><p key={j.id}><strong>{HUMAN_STATUS[j.status]||j.status}</strong> · {j.objective}<small style={{display:'block'}}>correlation {j.correlation_id}</small></p>):<p>No tiene trabajos persistidos.</p>}<h4>Consultar agente</h4><p>La consulta se resuelve del lado servidor usando sólo resúmenes persistidos autorizados; la interfaz no envía evidencia del caller.</p><textarea aria-label="Pregunta para el agente" rows={3} value={consultQuestion} onChange={e=>setConsultQuestion(e.target.value)} placeholder="Preguntá por su estado, evidencia o próxima acción…"/><div><button type="button" disabled={consulting||selected.status==='DISABLED'||!consultQuestion.trim()} onClick={()=>void consultAgent()}>{consulting?'Consultando…':'Consultar agente'}</button></div>{consultAnswer&&<pre style={{whiteSpace:'pre-wrap'}}>{consultAnswer}</pre>}</div>}
   {tab==='Actividad'&&<div>{selectedJobs.length?selectedJobs.map(j=><p key={j.id}><strong>{HUMAN_STATUS[j.status]||j.status}</strong> · {j.objective}<small style={{display:'block'}}>{j.created_at?new Date(j.created_at).toLocaleString('es-AR'):'—'}</small></p>):<p>Sin actividad persistida.</p>}</div>}
   {tab==='Decisiones'&&<div>{selectedDecisions.length?selectedDecisions.map(d=><p key={d.id}><strong>{d.decision}</strong> · {d.reason}</p>):<p>Sin decisiones persistidas.</p>}</div>}
   {tab==='Evidencia'&&<div>{selectedEvidence.length?selectedEvidence.map(e=><p key={e.id}><strong>{e.evidence_type}</strong> · {e.reference}</p>):<p>Sin evidencia persistida.</p>}</div>}
   {tab==='Configuración'&&<div><h4>Permisos</h4><p>{(selected.permissions||[]).join(' · ')||'Sin permisos declarados'}</p><h4>Modo</h4><p>El modo corporativo se gobierna arriba. No se ofrecen interruptores individuales ficticios.</p></div>}
   {tab==='Auditoría'&&<div><h4>Auditar agente</h4><p>UGO muestra aquí hallazgos independientes persistidos de este trabajador. Una auditoría nueva sólo se ofrecerá cuando exista un RPC gobernado específico; no se crea evidencia falsa desde la interfaz.</p>{selectedFindings.length?selectedFindings.map(f=><p key={f.id}><strong>{f.severity} · {f.finding_type}</strong> — {f.status}<small style={{display:'block'}}>{f.description}</small></p>):<p>No hay hallazgos persistidos para este agente.</p>}</div>}
  </div>}
 </section>
}
