import React,{useEffect,useMemo,useRef,useState}from'react'
import type{SupabaseClient}from'@supabase/supabase-js'
import maplibregl from'maplibre-gl'
import'maplibre-gl/dist/maplibre-gl.css'
import'./client-quantum.css'
import'./client-reference.css'
import type{Category}from'./shared'
import{parseClientIntent}from'./hugoIntent'
import type{ClientHugoIntent,ClientScreen}from'./client/clientTypes'
import{getRoutingProvider}from'../lib/routing/provider'

export type ProviderMapRow={id:string;nombre:string|null;foto_url:string|null;karma:number|string|null;servicios_completados:number|null;tarifa_base:number|string|null;online:boolean|null;disponible:boolean|null;estado_verificacion:string|null;categoria_principal_id:string|null;categoria_nombre:string|null;categoria_emoji:string|null;lat:number|null;lng:number|null;pais?:string|null;zona?:string|null;bio?:string|null;experiencia_anos?:number|null;especialidades?:string|null;idiomas?:string|null;disponibilidad_horaria?:string|null;telefono_profesional?:string|null;ciudad_base?:string|null}
type IntentPayload={categoryId?:string;categoryName?:string;urgency:boolean;description:string}
type Props={supabase:SupabaseClient;categories:Category[];selectedCategoryId:string;requestedScreen?:ClientScreen;requestedProviderId?:string|null;hugoIntent?:ClientHugoIntent|null;onCategorySelect:(id:string)=>void;onProviderPick:(provider:ProviderMapRow)=>void;onSearchClose?:()=>void;onIntent?:(intent:IntentPayload)=>void}
type EtaMeta={etaSeconds:number;distanceMeters:number}
const FLORIPA:[number,number]=[-48.5482,-27.5949]
const ROUTE_SOURCE='ugo-selected-route-source',ROUTE_LAYER='ugo-selected-route-layer'
const MAP_STYLE:any={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}
type RadarIconName='menu'|'search'|'pin'|'bell'|'sparkle'|'home'|'grid'|'chevron'|'locate'|'shield'|'star'|'clock'|'tool'|'language'|'check'
function RadarIcon({name,size=20}:{name:RadarIconName;size?:number}){
 const paths:Record<RadarIconName,React.ReactNode>={
  menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>,search:<><circle cx="10.8" cy="10.8" r="5.8"/><path d="m16 16 4 4"/></>,pin:<><path d="M12 21s6-5.1 6-11a6 6 0 1 0-12 0c0 5.9 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></>,bell:<><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 22h4"/></>,sparkle:<><path d="m12 3 1.6 5.4L19 10l-5.4 1.6L12 17l-1.6-5.4L5 10l5.4-1.6L12 3ZM19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z"/></>,home:<><path d="m3 11 9-7 9 7v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1v-9Z"/></>,grid:<><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></>,chevron:<path d="m9 18 6-6-6-6"/>,locate:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></>,shield:<><path d="M12 3 19 6v5c0 4.6-2.9 8.1-7 10-4.1-1.9-7-5.4-7-10V6l7-3Z"/><path d="m9 12 2 2 4-4"/></>,star:<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,tool:<><path d="M14.5 6.5a4.5 4.5 0 0 0-5.8 5.8L3.5 17.5a2 2 0 1 0 2.8 2.8l5.2-5.2a4.5 4.5 0 0 0 5.8-5.8l-2.7 2.1-2.3-2.3 2.2-2.6Z"/></>,language:<><circle cx="12" cy="12" r="9"/><path d="M3.5 12h17M12 3c2.1 2.5 3.1 5.5 3.1 9S14.1 18.5 12 21M12 3C9.9 5.5 8.9 8.5 8.9 12s1 6.5 3.1 9"/></>,check:<path d="m5 12 4 4L19 6"/>,
 }
 return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>
}
function avatarNode(p:ProviderMapRow){const wrap=document.createElement('span');wrap.className='ugo-provider-avatar';if(p.foto_url){const img=document.createElement('img');img.src=p.foto_url;img.alt='';wrap.appendChild(img)}else wrap.textContent=((p.nombre||'P')[0]||'P').toUpperCase();return wrap}
function markerNode(p:ProviderMapRow,active:boolean){const el=document.createElement('button');el.type='button';el.className=`ugo-provider-marker${active?' active':''}`;el.appendChild(avatarNode(p));const copy=document.createElement('span');copy.className='ugo-provider-copy';const name=document.createElement('b');name.textContent=(p.nombre||'Profesional').split(' ')[0];const cat=document.createElement('small');cat.textContent=p.categoria_nombre||'Especialista';const meta=document.createElement('em');meta.textContent=`R$ ${Number(p.tarifa_base||0).toFixed(0)}/h · ★ ${Number(p.karma||5).toFixed(1)}`;copy.append(name,cat,meta);el.appendChild(copy);const dot=document.createElement('i');dot.className=p.online&&p.disponible?'online':'offline';el.appendChild(dot);return el}
function categoryByHint(categories:Category[],hint:string|null|undefined){if(!hint)return null;const q=hint.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');return categories.find(c=>[c.nombre,c.slug].filter(Boolean).some(v=>{const n=String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');return n.includes(q)||q.includes(n)}))||null}
function etaLabel(meta:EtaMeta|undefined){if(!meta)return'';return`${Math.max(1,Math.round(meta.etaSeconds/60))} min`}
function clearRoute(map:maplibregl.Map){if(map.getLayer(ROUTE_LAYER))map.removeLayer(ROUTE_LAYER);if(map.getSource(ROUTE_SOURCE))map.removeSource(ROUTE_SOURCE)}

export function ClientQuantumExperience({supabase,categories,selectedCategoryId,requestedScreen,requestedProviderId,hugoIntent,onCategorySelect,onProviderPick,onSearchClose,onIntent}:Props){
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),markers=useRef<maplibregl.Marker[]>([]),searchInput=useRef<HTMLInputElement|null>(null),drawerSearchInput=useRef<HTMLInputElement|null>(null)
 const[userPos,setUserPos]=useState<[number,number]>(FLORIPA),[providers,setProviders]=useState<ProviderMapRow[]>([]),[selected,setSelected]=useState<string|null>(null),[drawer,setDrawer]=useState(false),[searchView,setSearchView]=useState(false),[menuOpen,setMenuOpen]=useState(false),[etaByProvider,setEtaByProvider]=useState<Record<string,EtaMeta>>({}),[search,setSearch]=useState('')
 const categoryFiltered=useMemo(()=>providers.filter(p=>!selectedCategoryId||!p.categoria_principal_id||p.categoria_principal_id===selectedCategoryId),[providers,selectedCategoryId])
 const filtered=useMemo(()=>[...categoryFiltered].filter(p=>!search.trim()||`${p.nombre||''} ${p.categoria_nombre||''} ${p.especialidades||''}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>{const availability=Number(Boolean(b.online&&b.disponible))-Number(Boolean(a.online&&a.disponible));if(availability)return availability;const ae=etaByProvider[a.id]?.etaSeconds??Number.MAX_SAFE_INTEGER,be=etaByProvider[b.id]?.etaSeconds??Number.MAX_SAFE_INTEGER;if(ae!==be)return ae-be;return Number(b.karma||0)-Number(a.karma||0)}),[categoryFiltered,etaByProvider,search])
 const selectedProvider=useMemo(()=>filtered.find(p=>p.id===selected)||providers.find(p=>p.id===selected)||null,[filtered,providers,selected])
 const featured=filtered.slice(0,3)
 useEffect(()=>{let alive=true;async function load(){const{data,error}=await supabase.from('proveedores_mapa').select('*').order('online',{ascending:false}).order('disponible',{ascending:false}).limit(50);if(alive&&!error)setProviders((data||[])as ProviderMapRow[])}load().catch(()=>{});const ch=supabase.channel('client-provider-map').on('postgres_changes',{event:'*',schema:'public',table:'perfiles_proveedor'},()=>load()).subscribe();return()=>{alive=false;supabase.removeChannel(ch)}},[supabase])
 useEffect(()=>{if(!hugoIntent)return;const matched=categoryByHint(categories,hugoIntent.categoryHint);if(matched)onCategorySelect(matched.id);setDrawer(true);onIntent?.({categoryId:matched?.id,categoryName:matched?.nombre||'',urgency:Boolean(hugoIntent.urgent),description:String(hugoIntent.description||hugoIntent.text||'').trim()})},[categories,hugoIntent,onCategorySelect,onIntent])
 useEffect(()=>{if(requestedScreen==='search'){setSelected(null);setSearchView(true);setDrawer(true)}if(requestedScreen==='provider'&&requestedProviderId){setSearchView(false);setSelected(requestedProviderId);setDrawer(true)}},[requestedProviderId,requestedScreen])
 useEffect(()=>{if(drawer&&searchView)window.setTimeout(()=>drawerSearchInput.current?.focus(),80)},[drawer,searchView])
 useEffect(()=>{navigator.geolocation?.getCurrentPosition(pos=>{const next:[number,number]=[pos.coords.longitude,pos.coords.latitude];setUserPos(next);try{sessionStorage.setItem('ugo:last-client-location',JSON.stringify({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,at:Date.now()}))}catch{}},()=>{},{enableHighAccuracy:true,timeout:8000,maximumAge:60000})},[])
 useEffect(()=>{let alive=true;const candidates=categoryFiltered.filter(p=>p.lat!=null&&p.lng!=null&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng))).map(p=>({providerId:p.id,location:{latitude:Number(p.lat),longitude:Number(p.lng)},available:Boolean(p.online&&p.disponible)}));if(!candidates.length){setEtaByProvider({});return()=>{alive=false}};getRoutingProvider().rankByEta({latitude:userPos[1],longitude:userPos[0]},candidates).then(rows=>{if(!alive)return;const next:Record<string,EtaMeta>={};rows.forEach(row=>{next[row.providerId]={etaSeconds:row.etaSeconds,distanceMeters:row.distanceMeters}});setEtaByProvider(next)}).catch(()=>{if(alive)setEtaByProvider({})});return()=>{alive=false}},[categoryFiltered,userPos])
 useEffect(()=>{if(!mapEl.current||mapRef.current)return;const map=new maplibregl.Map({container:mapEl.current,style:MAP_STYLE,center:userPos,zoom:14,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-left');mapRef.current=map;return()=>{markers.current.forEach(m=>m.remove());markers.current=[];if(map.isStyleLoaded())clearRoute(map);map.remove();mapRef.current=null}},[])
 useEffect(()=>{if(!selected)mapRef.current?.easeTo({center:userPos,zoom:14,duration:700})},[selected,userPos])
 useEffect(()=>{const map=mapRef.current;if(!map)return;markers.current.forEach(m=>m.remove());markers.current=[];const user=document.createElement('div');user.className='ugo-user-marker';user.appendChild(document.createElement('span'));markers.current.push(new maplibregl.Marker({element:user}).setLngLat(userPos).addTo(map));filtered.forEach(p=>{if(p.lat==null||p.lng==null||!Number.isFinite(Number(p.lat))||!Number.isFinite(Number(p.lng)))return;const el=markerNode(p,p.id===selected);el.onclick=()=>{setSelected(p.id);setDrawer(true)};markers.current.push(new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat([Number(p.lng),Number(p.lat)]).addTo(map))})},[filtered,selected,userPos])
 useEffect(()=>{const map=mapRef.current;if(!map)return;let alive=true;const provider=selectedProvider;if(!provider||provider.lat==null||provider.lng==null||!Number.isFinite(Number(provider.lat))||!Number.isFinite(Number(provider.lng))){if(map.isStyleLoaded())clearRoute(map);return()=>{alive=false}}const origin={latitude:Number(provider.lat),longitude:Number(provider.lng)},destination={latitude:userPos[1],longitude:userPos[0]};getRoutingProvider().route(origin,destination).then(route=>{if(!alive||!mapRef.current)return;const current=mapRef.current;const geometry=(route.geometry&&typeof route.geometry==='object'&&(route.geometry as any).type==='LineString')?route.geometry:{type:'LineString',coordinates:[[origin.longitude,origin.latitude],[destination.longitude,destination.latitude]]};const render=()=>{if(!alive||!current.isStyleLoaded())return;clearRoute(current);current.addSource(ROUTE_SOURCE,{type:'geojson',data:{type:'Feature',properties:{},geometry} as any});current.addLayer({id:ROUTE_LAYER,type:'line',source:ROUTE_SOURCE,layout:{'line-cap':'round','line-join':'round'},paint:{'line-width':5,'line-opacity':.88,'line-color':'#079455'}});const bounds=new maplibregl.LngLatBounds();(geometry as any).coordinates.forEach((c:[number,number])=>bounds.extend(c));if(!bounds.isEmpty())current.fitBounds(bounds,{padding:90,maxZoom:15,duration:700})};if(current.isStyleLoaded())render();else current.once('load',render)}).catch(()=>{});return()=>{alive=false}},[selectedProvider,userPos])
 function pickProvider(p:ProviderMapRow){setSearchView(false);setSelected(p.id);setDrawer(true)}
 function goHome(){setMenuOpen(false);setSearch('');onCategorySelect('');setSelected(null);setDrawer(false);mapRef.current?.easeTo({center:userPos,zoom:14,duration:500})}
 function focusSearch(){setMenuOpen(false);setSelected(null);setSearchView(true);setDrawer(true)}
 function centerOnUser(){mapRef.current?.easeTo({center:userPos,zoom:15,duration:500})}
 function closeDrawer(){const closingSearch=searchView;setDrawer(false);setSearchView(false);if(closingSearch)onSearchClose?.()}
 function openHugo(){setMenuOpen(false)}
 return <section className="ugo-quantum-shell ugo-responsive-home ugo-ref-client">
  <div className="ugo-map-stage"><div ref={mapEl} className="ugo-map-canvas"/></div>
  <header className="ugo-ref-topbar">
   <button type="button" className="ugo-ref-circle ugo-client-menu-trigger" aria-label="Abrir menú" onClick={()=>setMenuOpen(true)}><RadarIcon name="menu"/></button>
   <button type="button" className="ugo-ref-location" onClick={centerOnUser} aria-label="Centrar mapa en mi ubicación"><span><RadarIcon name="pin" size={15}/></span><div><b>Mi ubicación</b><small>Florianópolis</small></div><em><RadarIcon name="chevron" size={15}/></em></button>
   <button type="button" className="ugo-ref-circle ugo-ref-bell" aria-label="Notificaciones"><RadarIcon name="bell"/><i/></button>
  </header>
  {menuOpen&&<div className="ugo-client-menu-backdrop" onClick={()=>setMenuOpen(false)}><aside className="ugo-client-menu" onClick={e=>e.stopPropagation()}>
   <div className="ugo-client-menu-head"><div className="ugo-client-menu-brand"><strong>UGO</strong><span>Cliente</span></div><button type="button" onClick={()=>setMenuOpen(false)} aria-label="Cerrar menú">×</button></div>
   <div className="ugo-client-menu-account"><span>C</span><div><b>Tu cuenta UGO</b><small>Todo lo que necesitás, en un lugar</small></div></div>
   <nav className="ugo-client-menu-list">
    <button type="button" className="active" onClick={goHome}><span>⌂</span><div><b>Inicio</b><small>Volver al radar</small></div><em>›</em></button>
    <button type="button" onClick={focusSearch}><span>⌕</span><div><b>Buscar profesional</b><small>Encontrá el servicio que necesitás</small></div><em>›</em></button>
    <button type="button" onClick={openHugo}><span>✦</span><div><b>Hablar con Hugo</b><small>Pedí ayuda por voz</small></div><em>›</em></button>
   </nav>
   <div className="ugo-client-menu-tip"><span>✓</span><div><b>Profesionales verificados</b><small>UGO prioriza confianza, cercanía y reputación.</small></div></div>
   <div className="ugo-client-menu-footer"><small>UGO Cliente</small><span>Servicios para una vida en movimiento.</span></div>
  </aside></div>}
  <button type="button" className="ugo-ref-locate" onClick={centerOnUser} aria-label="Centrar en mi ubicación"><RadarIcon name="locate"/></button>
  <button type="button" className="ugo-ref-hugo" onClick={openHugo} aria-label="Hablar con Hugo"><span><RadarIcon name="sparkle" size={35}/></span><small>Pedile ayuda a Hugo</small></button>
  <aside className="ugo-home-panel ugo-ref-sheet">
   <div className="ugo-drawer-handle"/>
   <div className="ugo-radar-heading"><div><h1>¿Qué necesitás resolver?</h1><p>Encontrá ayuda confiable cerca tuyo.</p></div><span><RadarIcon name="shield" size={17}/></span></div>
   <label className="ugo-home-search ugo-ref-search"><span><RadarIcon name="search"/></span><input ref={searchInput} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar un servicio"/></label>
   <div className="ugo-category-row ugo-ref-categories">{categories.slice(0,5).map(c=><button type="button" key={c.id} aria-pressed={selectedCategoryId===c.id} className={selectedCategoryId===c.id?'active':''} onClick={()=>onCategorySelect(selectedCategoryId===c.id?'':c.id)}><b>{c.emoji||'•'}</b><span>{c.nombre}</span></button>)}</div>
   <div className="ugo-featured-head ugo-ref-feature-title"><div><h2>{selectedCategoryId?'Disponibles ahora':'Profesionales cerca'}</h2></div><button type="button" onClick={focusSearch}>Ver todos <RadarIcon name="chevron" size={14}/></button></div>
   <div className="ugo-featured-grid ugo-ref-featured">{featured.length===0?<div className="ugo-home-empty">No hay profesionales disponibles para este filtro.</div>:featured.map(p=><button type="button" key={p.id} className="ugo-feature-card" onClick={()=>pickProvider(p)}><span className="ugo-feature-avatar">{p.foto_url?<img src={p.foto_url} alt=""/>:(p.nombre?.[0]||'P').toUpperCase()}</span><span className="ugo-feature-copy"><b>{p.nombre||'Profesional UGO'}</b><small>{p.categoria_emoji} {p.categoria_nombre||'Especialista'}</small><em>★ {Number(p.karma||5).toFixed(1)} · {p.servicios_completados||0} servicios</em><strong>R$ {Number(p.tarifa_base||0).toFixed(0)} / hora</strong></span>{etaByProvider[p.id]&&<span className="ugo-feature-eta">{etaLabel(etaByProvider[p.id])}</span>}</button>)}</div>
  </aside>
  <nav className="ugo-mobile-nav ugo-ref-nav"><button className="active" type="button" onClick={goHome}><b><RadarIcon name="home"/></b><span>Inicio</span></button><button type="button" onClick={focusSearch}><b><RadarIcon name="search"/></b><span>Buscar</span></button><button type="button" className="ugo-ref-nav-hugo" onClick={openHugo}><b><RadarIcon name="sparkle"/></b><span>Hugo</span></button><button type="button" onClick={()=>setMenuOpen(true)}><b><RadarIcon name="grid"/></b><span>Menú</span></button></nav>
  {drawer&&<div className="ugo-drawer-backdrop ugo-ref-backdrop" onClick={closeDrawer}><div className={`ugo-provider-drawer ugo-ref-provider-sheet${searchView?' ugo-search-sheet':''}`} onClick={e=>e.stopPropagation()}><div className="ugo-drawer-handle"/><div className="ugo-drawer-title-row"><div><h2>{selectedProvider?'Revisá los detalles':searchView?'Buscar profesionales':'Elegí con confianza'}</h2></div><button type="button" onClick={closeDrawer} aria-label="Cerrar búsqueda">×</button></div>{!selectedProvider&&<>{searchView&&<div className="ugo-search-controls"><label className="ugo-search-field"><RadarIcon name="search"/><input ref={drawerSearchInput} value={search} onChange={e=>setSearch(e.target.value)} placeholder="¿Qué servicio necesitás?"/></label><div className="ugo-search-categories" aria-label="Filtrar por categoría"><button type="button" className={!selectedCategoryId?'active':''} aria-pressed={!selectedCategoryId} onClick={()=>onCategorySelect('')}>Todos</button>{categories.map(c=><button type="button" key={c.id} className={selectedCategoryId===c.id?'active':''} aria-pressed={selectedCategoryId===c.id} onClick={()=>onCategorySelect(selectedCategoryId===c.id?'':c.id)}>{c.emoji} {c.nombre}</button>)}</div><p className="ugo-search-result-count">{filtered.length===1?'1 profesional encontrado':`${filtered.length} profesionales encontrados`}</p></div>}<div className="ugo-provider-list">{filtered.length===0&&<div className="ugo-search-empty"><span><RadarIcon name="search" size={22}/></span><b>No encontramos profesionales</b><p>Probá con otro servicio o quitá el filtro de categoría.</p><button type="button" onClick={()=>{setSearch('');onCategorySelect('')}}>Limpiar filtros</button></div>}{filtered.map(p=><button type="button" key={p.id} className="ugo-provider-card" onClick={()=>setSelected(p.id)}><span className="ugo-card-avatar">{p.foto_url?<img src={p.foto_url} alt=""/>:(p.nombre?.[0]||'P').toUpperCase()}</span><span className="ugo-card-main"><b>{p.nombre||'Profesional UGO'}</b><small>{p.categoria_nombre||'Especialista'}</small><em><span className={p.online&&p.disponible?'available':'offline'}>{p.online&&p.disponible?'Disponible ahora':'No disponible'}</span>{etaByProvider[p.id]?` · ${etaLabel(etaByProvider[p.id])}`:''} · ★ {Number(p.karma||5).toFixed(1)}</em></span><strong>R$ {Number(p.tarifa_base||0).toFixed(0)}/h</strong><span className="ugo-search-provider-arrow"><RadarIcon name="chevron" size={16}/></span></button>)}</div></>}
   {selectedProvider&&<article className="ugo-provider-full-profile ugo-ref-profile"><button type="button" className="ugo-profile-back" onClick={()=>setSelected(null)}><RadarIcon name="chevron" size={16}/> Volver a resultados</button><header className="ugo-profile-hero"><span className="ugo-profile-avatar">{selectedProvider.foto_url?<img src={selectedProvider.foto_url} alt=""/>:(selectedProvider.nombre?.[0]||'P').toUpperCase()}</span><div><div className="ugo-profile-status"><i className={selectedProvider.online&&selectedProvider.disponible?'available':'offline'}/>{selectedProvider.online&&selectedProvider.disponible?'Disponible ahora':'No disponible ahora'}</div><h3>{selectedProvider.nombre||'Profesional UGO'}</h3><p>{selectedProvider.categoria_emoji} {selectedProvider.categoria_nombre||'Especialista'}</p></div></header><div className="ugo-profile-trust">{selectedProvider.estado_verificacion==='verificado'&&<span><RadarIcon name="check" size={14}/> Verificado por UGO</span>}{selectedProvider.experiencia_anos!=null&&<span><RadarIcon name="clock" size={14}/>{selectedProvider.experiencia_anos}+ años de experiencia</span>}</div><dl className="ugo-profile-stats"><div><dt><RadarIcon name="star" size={15}/> Calificación</dt><dd>{Number(selectedProvider.karma||5).toFixed(1)}</dd></div><div><dt>Servicios</dt><dd>{selectedProvider.servicios_completados||0}</dd></div><div><dt>Tarifa</dt><dd>R$ {Number(selectedProvider.tarifa_base||0).toFixed(0)}<small>/hora</small></dd></div></dl><p className="ugo-profile-bio">{selectedProvider.bio||`Especialista en ${selectedProvider.especialidades||selectedProvider.categoria_nombre||'servicios para el hogar'}.`}</p><section className="ugo-profile-details" aria-label="Información del profesional"><div><span><RadarIcon name="tool" size={17}/></span><p><b>Especialidad</b><small>{selectedProvider.especialidades||selectedProvider.categoria_nombre||'Especialista'}</small></p></div>{etaByProvider[selectedProvider.id]&&<div><span><RadarIcon name="clock" size={17}/></span><p><b>Tiempo estimado</b><small>Llega en {etaLabel(etaByProvider[selectedProvider.id])}</small></p></div>}{(selectedProvider.ciudad_base||selectedProvider.zona)&&<div><span><RadarIcon name="pin" size={17}/></span><p><b>Zona de atención</b><small>{selectedProvider.ciudad_base||selectedProvider.zona}</small></p></div>}{selectedProvider.idiomas&&<div><span><RadarIcon name="language" size={17}/></span><p><b>Idiomas</b><small>{selectedProvider.idiomas}</small></p></div>}</section><button type="button" className="ugo-hire-button" onClick={()=>{onProviderPick(selectedProvider);setDrawer(false)}}>Elegir a {selectedProvider.nombre?.split(' ')[0]||'este profesional'} <span><RadarIcon name="chevron" size={17}/></span></button></article>}
  </div></div>}
 </section>
}
