import React,{useCallback,useEffect,useState}from'react'
import type{Service}from'./shared'
import{supabase}from'../lib/supabase'

type Props={service:Service;accessToken?:string}
type PixState={estado?:string;pix_copia_cola?:string|null;pix_qr_code?:string|null;pix_expira_at?:string|null;mp_payment_id?:string|null;metodo?:string|null;pix_informado_at?:string|null;pix_e2e_id?:string|null;pix_txid?:string|null}

export function ClientPixPaymentPanel({service,accessToken}:Props){
 const[pix,setPix]=useState<PixState|null>(null)
 const[pixKey,setPixKey]=useState('')
 const[demoAllowed,setDemoAllowed]=useState(false)
 const[busy,setBusy]=useState(false)
 const[msg,setMsg]=useState('')
 const load=useCallback(async()=>{const{data}=await supabase.from('pagos').select('estado,metodo,pix_copia_cola,pix_qr_code,pix_expira_at,mp_payment_id,pix_informado_at,pix_e2e_id,pix_txid').eq('servicio_id',service.id).limit(1).maybeSingle();setPix((data as PixState|null)||null)},[service.id])
 useEffect(()=>{load();supabase.auth.getUser().then(({data})=>setDemoAllowed(Boolean(data.user?.email&&/@ugo\.test$/i.test(data.user.email))));const ch=supabase.channel(`client-pix-${service.id}`).on('postgres_changes',{event:'*',schema:'public',table:'pagos',filter:`servicio_id=eq.${service.id}`},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[load,service.id])
 if(!['asignado','en_camino','llegado','en_progreso','esperando_aprobacion'].includes(service.estado))return null
 if(pix?.estado==='retenido'||pix?.estado==='liberado')return null

 async function createPix(metodo:'pix'|'pix_direto'){if(!accessToken)return setMsg('Sesión requerida.');setBusy(true);setMsg('');try{const r=await fetch('/api/pagos/crear',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({servicioId:service.id,metodo})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'No se pudo generar Pix.');if(body.alreadyPaid){await load();return}setPix({estado:body.estado||'pendiente',metodo,pix_copia_cola:body.pixCopiaCola,pix_qr_code:body.pixQrCode||null,pix_expira_at:body.pixExpiraAt||null,mp_payment_id:body.paymentId?String(body.paymentId):null,pix_informado_at:body.informadoAt||null,pix_txid:body.pixTxid||null});setPixKey(body.pixChave||'');setMsg(metodo==='pix_direto'?'Pix direto gerado. Depois de pagar, toque em “Já paguei” para enviar à conciliação.':'Pix gerado. O serviço será habilitado quando o pagamento for confirmado.')}catch(e){setMsg(e instanceof Error?e.message:'No se pudo generar Pix.')}finally{setBusy(false)}}
 async function simulatePix(){setBusy(true);setMsg('');try{const{error}=await(supabase as any).rpc('crear_pix_demo',{p_servicio_id:service.id});if(error)throw error;setMsg('Pix DEMO aprovado. Nenhum dinheiro real foi movimentado.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível simular o Pix.')}finally{setBusy(false)}}
 async function copy(){if(!pix?.pix_copia_cola)return;try{await navigator.clipboard.writeText(pix.pix_copia_cola);setMsg('Código Pix copiado.')}catch{setMsg('Copie manualmente o código Pix.')}}
 async function informPaid(){if(pix?.metodo!=='pix_direto')return;setBusy(true);setMsg('');try{const{error}=await(supabase as any).rpc('informar_pix_direto',{p_servicio_id:service.id});if(error)throw error;setMsg('Pagamento informado. O Admin UGO vai conciliar antes de liberar o serviço.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível informar o pagamento.')}finally{setBusy(false)}}
 const qr=pix?.pix_qr_code?`data:image/png;base64,${pix.pix_qr_code}`:null
 const direct=pix?.metodo==='pix_direto'
 return <div style={{position:'fixed',left:'50%',bottom:86,transform:'translateX(-50%)',zIndex:74,width:'min(380px,calc(100vw - 28px))',background:'#fff',borderRadius:22,padding:16,boxShadow:'0 16px 44px rgba(0,0,0,.2)'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><small style={{fontWeight:800}}>PIX · BRASIL</small><div style={{fontWeight:900,fontSize:18}}>Pagar serviço #{service.numero}</div></div><span style={{fontSize:26}}>◆</span></div>
  {!pix?.pix_copia_cola&&<><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:12}}><button type="button" onClick={()=>createPix('pix')} disabled={busy} style={{padding:'13px 10px',border:0,borderRadius:14,fontWeight:900,cursor:'pointer'}}>{busy?'Gerando…':'Pix automático'}</button><button type="button" onClick={()=>createPix('pix_direto')} disabled={busy} style={{padding:'13px 10px',border:'1px solid #ddd',borderRadius:14,fontWeight:900,cursor:'pointer',background:'#fff'}}>Pix direto UGO</button></div>{demoAllowed&&<button type="button" onClick={simulatePix} disabled={busy} style={{width:'100%',marginTop:9,padding:'12px 14px',border:'1px dashed #666',borderRadius:14,fontWeight:900,background:'#f7f7f7',cursor:'pointer'}}>🧪 Simular Pix aprovado</button>}{demoAllowed&&<small style={{display:'block',marginTop:6,opacity:.65}}>Modo DEMO · não movimenta dinheiro real</small>}</>}
  {pix?.pix_copia_cola&&<div style={{marginTop:12,textAlign:'center'}}>{qr&&<img src={qr} alt="QR Code Pix" style={{width:190,height:190,objectFit:'contain',borderRadius:12}}/>}{direct&&<div style={{padding:'10px 12px',borderRadius:12,background:'#f6f6f6',fontSize:12,textAlign:'left'}}><b>Pix direto para UGO</b>{pixKey&&<div style={{marginTop:4}}>Chave: <strong>{pixKey}</strong></div>}<div style={{marginTop:4}}>Referência: {pix.pix_txid||'vinculada ao serviço'}</div></div>}<textarea readOnly value={pix.pix_copia_cola} style={{width:'100%',minHeight:76,marginTop:10,borderRadius:10,padding:10,fontSize:11}}/><button type="button" onClick={copy} style={{width:'100%',padding:'11px 14px',border:0,borderRadius:12,fontWeight:900}}>Copiar Pix copia e cola</button>{pix.pix_expira_at&&<small style={{display:'block',marginTop:8}}>Expira {new Date(pix.pix_expira_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small>}{direct&&!pix.pix_informado_at&&<button type="button" onClick={informPaid} disabled={busy} style={{width:'100%',marginTop:9,padding:'11px 14px',border:'1px solid #ddd',borderRadius:12,fontWeight:900,background:'#fff'}}>{busy?'Enviando…':'Já paguei'}</button>}{direct&&pix.pix_informado_at&&<div style={{marginTop:9,padding:10,borderRadius:12,background:'#f6f6f6',fontSize:12,fontWeight:800}}>Pagamento informado · aguardando conciliação UGO</div>}</div>}
  {msg&&<p style={{fontSize:12,margin:'10px 0 0'}}>{msg}</p>}
 </div>
}
