import React,{useCallback,useEffect,useState}from'react'
import type{FormEvent}from'react'
import{AuthScreen,LoadingScreen,useRoleSession}from'./shared'
import{ClientApp}from'./ClientApp'
import'./client-onboarding.css'

const TERMS_VERSION='2026-09-04'
type Form={nombre:string;apellido:string;telefono:string;direccion:string;barrio:string;ciudad:string;idioma:string;contacto:string;lat:number|null;lng:number|null}
const empty:Form={nombre:'',apellido:'',telefono:'',direccion:'',barrio:'',ciudad:'Florianópolis',idioma:'pt-BR',contacto:'whatsapp',lat:null,lng:null}

export function ClientOnboardingGate(){
 const auth=useRoleSession('client'),{supabase,session,profile}=auth
 const[loading,setLoading]=useState(true),[complete,setComplete]=useState(false),[busy,setBusy]=useState(false),[terms,setTerms]=useState(false),[msg,setMsg]=useState(''),[locating,setLocating]=useState(false),[form,setForm]=useState<Form>(empty)
 const load=useCallback(async()=>{if(!session||!profile){setLoading(false);return}setLoading(true);try{const[{data:u,error:ue},{data:p,error:pe}]=await Promise.all([supabase.from('usuarios').select('nombre,apellido,lat,lng').eq('id',session.user.id).single(),supabase.from('perfiles_cliente').select('telefono,direccion,barrio,ciudad,idioma_preferido,contacto_preferido,termos_aceitos_at,onboarding_completo_at').eq('usuario_id',session.user.id).maybeSingle()]);if(ue)throw ue;if(pe)throw pe;setComplete(Boolean(p?.onboarding_completo_at&&p?.termos_aceitos_at&&p?.telefono&&p?.direccion&&p?.ciudad));setTerms(Boolean(p?.termos_aceitos_at));setForm({nombre:u?.nombre||profile.nombre||'',apellido:u?.apellido||'',telefono:p?.telefono||'',direccion:p?.direccion||'',barrio:p?.barrio||'',ciudad:p?.ciudad||'Florianópolis',idioma:p?.idioma_preferido||'pt-BR',contacto:p?.contacto_preferido||'whatsapp',lat:u?.lat??null,lng:u?.lng??null})}catch(e:any){setMsg(e.message||'No se pudo cargar tu perfil.')}finally{setLoading(false)}},[profile,session,supabase])
 useEffect(()=>{load()},[load])
 function locate(){if(!navigator.geolocation){setMsg('Este dispositivo no permite obtener ubicación.');return}setLocating(true);navigator.geolocation.getCurrentPosition(pos=>{setForm(v=>({...v,lat:pos.coords.latitude,lng:pos.coords.longitude}));setMsg('Ubicación guardada para mostrar correctamente tus pedidos en UGO.');setLocating(false)},()=>{setMsg('No pudimos obtener tu ubicación. Podés continuar y activarla después.');setLocating(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
 async function submit(e:FormEvent){e.preventDefault();if(!session)return;setMsg('');setBusy(true);try{const digits=form.telefono.replace(/\D/g,'');if(!form.nombre.trim())throw new Error('Escribí tu nombre.');if(digits.length<8)throw new Error('Ingresá un teléfono/WhatsApp válido.');if(!form.direccion.trim())throw new Error('Ingresá tu dirección.');if(!form.ciudad.trim())throw new Error('Ingresá tu ciudad.');if(!terms)throw new Error('Aceptá los términos y la política de privacidad para continuar.');const{error}=await supabase.rpc('completar_onboarding_cliente',{p_nombre:form.nombre.trim(),p_apellido:form.apellido.trim(),p_telefono:form.telefono.trim(),p_direccion:form.direccion.trim(),p_barrio:form.barrio.trim(),p_ciudad:form.ciudad.trim(),p_idioma_preferido:form.idioma,p_contacto_preferido:form.contacto,p_termos_versao:TERMS_VERSION,p_lat:form.lat,p_lng:form.lng});if(error)throw error;setComplete(true);setMsg('Perfil listo. Ya podés pedir servicios en UGO.')}catch(e:any){setMsg(e.message||'No se pudo completar el registro.')}finally{setBusy(false)}}
 if(auth.loading||loading)return<LoadingScreen label="Preparando tu cuenta U.G.O.…"/>
 if(!session||!profile)return<AuthScreen role="client" supabase={supabase} error={auth.error} onError={auth.setError}/>
 if(complete)return<ClientApp/>
 return <main className="ugo-client-onboarding"><form className="ugo-client-onboarding-card" onSubmit={submit}><div className="ugo-client-onboarding-head"><div><small>U.G.O. · CLIENTE</small><h1>Terminá tu perfil</h1><p>Necesitamos estos datos para enviar al profesional a la dirección correcta y mantenerte informado.</p></div><span className="ugo-client-onboarding-icon">👤</span></div><div className="ugo-client-onboarding-body"><div className="ugo-client-grid-2"><label className="ugo-client-field">Nombre<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label className="ugo-client-field">Apellido<input value={form.apellido} onChange={e=>setForm({...form,apellido:e.target.value})}/></label></div><label className="ugo-client-field">Email de acceso<input className="readonly" value={session.user.email||''} readOnly/></label><label className="ugo-client-field">Teléfono / WhatsApp<input placeholder="+55…" value={form.telefono} onChange={e=>setForm({...form,telefono:e.target.value})}/></label><label className="ugo-client-field">Dirección<input placeholder="Calle, número" value={form.direccion} onChange={e=>setForm({...form,direccion:e.target.value})}/></label><div className="ugo-client-grid-2"><label className="ugo-client-field">Barrio / zona<input value={form.barrio} onChange={e=>setForm({...form,barrio:e.target.value})}/></label><label className="ugo-client-field">Ciudad<input value={form.ciudad} onChange={e=>setForm({...form,ciudad:e.target.value})}/></label></div><button type="button" className="ugo-client-secondary" onClick={locate} disabled={locating}>{locating?'Obteniendo ubicación…':form.lat!=null?'📍 Ubicación capturada':'📍 Usar mi ubicación actual'}</button><div className="ugo-client-grid-2"><label className="ugo-client-field">Idioma<select value={form.idioma} onChange={e=>setForm({...form,idioma:e.target.value})}><option value="pt-BR">Português</option><option value="es-AR">Español</option><option value="en">English</option></select></label><label className="ugo-client-field">Contacto preferido<select value={form.contacto} onChange={e=>setForm({...form,contacto:e.target.value})}><option value="whatsapp">WhatsApp</option><option value="telefono">Teléfono</option><option value="chat">Chat UGO</option></select></label></div><label className="ugo-client-terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Acepto los términos de uso y la política de privacidad de UGO para gestionar mis pedidos, contacto y dirección de servicio.</span></label>{msg&&<div className="ugo-client-message">{msg}</div>}<div className="ugo-client-actions"><button type="button" className="ugo-client-secondary" onClick={()=>auth.signOut()}>Cerrar sesión</button><button className="ugo-client-primary" disabled={busy}>{busy?'Guardando…':'Guardar y entrar a UGO'}</button></div></div></form></main>
}
