import React,{useCallback,useEffect,useMemo,useState}from'react'
import{getRoleSupabase}from'../lib/roleSupabase'

type Row={id:string;storage_path:string;descripcion:string|null;created_at:string;url?:string|null}
const BUCKET='request-evidence'

export function ClientRequestEvidence(){
 const supabase=useMemo(()=>getRoleSupabase('client'),[])
 const[rows,setRows]=useState<Row[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=useCallback(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data,error}=await supabase.from('evidencias_solicitud').select('id,storage_path,descripcion,created_at').eq('cliente_id',user.id).is('servicio_id',null).order('created_at',{ascending:true});if(error){setError(error.message);return}const signed=await Promise.all(((data||[])as Row[]).map(async r=>{const{data:s}=await supabase.storage.from(BUCKET).createSignedUrl(r.storage_path,900);return{...r,url:s?.signedUrl||null}}));setRows(signed)},[supabase])
 useEffect(()=>{load().catch(()=>{})},[load])
 async function upload(file:File|null){if(!file)return;if(file.size>10*1024*1024){setError('La foto supera el límite de 10 MB.');return}setBusy(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Iniciá sesión para adjuntar fotos.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const{error:u}=await supabase.storage.from(BUCKET).upload(path,file,{contentType:file.type||'image/jpeg'});if(u)throw u;const{error:i}=await supabase.from('evidencias_solicitud').insert({cliente_id:user.id,storage_path:path,descripcion:'Evidencia aportada por el cliente antes del matching',metadata:{mime:file.type||null,size:file.size}});if(i){await supabase.storage.from(BUCKET).remove([path]);throw i}await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo subir la foto.')}finally{setBusy(false)}}
 async function remove(row:Row){setBusy(true);setError('');try{const{error}=await supabase.from('evidencias_solicitud').delete().eq('id',row.id).is('servicio_id',null);if(error)throw error;await supabase.storage.from(BUCKET).remove([row.storage_path]);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo quitar la foto.')}finally{setBusy(false)}}
 return <div className="ugo-request-evidence-dock"><button type="button" className="ugo-request-evidence-trigger" onClick={()=>setOpen(v=>!v)}>📷 Fotos del trabajo {rows.length?`(${rows.length})`:''}</button>{open&&<section className="ugo-request-evidence-panel"><header><div><strong>Mostrale el trabajo al profesional</strong><p>Subí fotos antes de enviar el pedido. El proveedor podrá analizarlas al recibir la oportunidad.</p></div><button type="button" onClick={()=>setOpen(false)}>×</button></header><label className="ugo-request-evidence-upload">{busy?'Subiendo…':'＋ Agregar foto'}<input type="file" accept="image/*" capture="environment" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]||null);e.currentTarget.value=''}}/></label>{error&&<div className="ugo-request-evidence-error">{error}</div>}<div className="ugo-request-evidence-grid">{rows.map(r=><figure key={r.id}>{r.url?<img src={r.url} alt="Foto del trabajo a realizar"/>:<div/>}<button type="button" disabled={busy} onClick={()=>void remove(r)}>Quitar</button></figure>)}</div><small>Estas fotos son evidencia de la solicitud. No reemplazan las evidencias Antes/Durante/Después que registra el proveedor durante el servicio.</small></section>}</div>
}
