import React,{useEffect,useMemo,useRef,useState}from'react'
import type{SupabaseClient}from'@supabase/supabase-js'
import maplibregl from'maplibre-gl'
import'maplibre-gl/dist/maplibre-gl.css'
import'./client-quantum.css'
import type{Category}from'./shared'
import{parseClientIntent}from'./hugoIntent'
import{getRoutingProvider}from'../lib/routing/provider'

export type ProviderMapRow={id:string;nombre:string|null;foto_url:string|null;karma:number|string|null;servicios_completados:number|null;tarifa_base:number|string|null;online:boolean|null;disponible:boolean|null;estado_verificacion:string|null;categoria_principal_id:string|null;categoria_nombre:string|null;categoria_emoji:string|null;lat:number|null;lng:number|null;pais?:string|null;zona?:string|null;bio?:string|null;experiencia_anos?:number|null;especialidades?:string|null;idiomas?:string|null;disponibilidad_horaria?:string|null;telefono_profesional?:string|null;ciudad_base?:string|null}
type IntentPayload={categoryId?:string;categoryName?:string;urgency:boolean;description:string}
type Props={supabase:SupabaseClient;categories:Category[];selectedCategoryId:string;onCategorySelect:(id:string)=>void;onProviderPick:(provider:ProviderMapRow)=>void;onIntent?:(intent:IntentPayload)=>void}
type EtaMeta={etaSeconds:number;distanceMeters:number}
const FLORIPA:[number,number]=[-48.5482,-27.5949]
const ROUTE_SOURCE='ugo-selected-route-source',ROUTE_LAYER='ugo-selected-route-layer'
const MAP_STYLE:any={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}
function avatarNode(p:ProviderMapRow){const wrap=document.createElement('span');wrap.className='ugo-provider-avatar';if(p.foto_url){const img=document.createElement('img');img.src=p.foto_url;img.alt='';wrap.appendChild(img)}else wrap.textContent=((p.nombre||'P')[0]||'P').toUpperCase();return wrap}
function markerNode(p:ProviderMapRow,active:boolean){const el=document.createElement('button');el.type='button';el.className=`ugo-provider-marker${active?' active':''}`;el.appendChild(avatarNode(p));const copy=document.createElement('span');copy.className='ugo-provider-copy';const name=document.createElement('b');name.textContent=(p.nombre||'Profissional').split(' ')[0];const cat=document.createElement('small');cat.textContent=p.categoria_nombre||'Especialista';const meta=document.createElement('em');meta.textContent=`R$ ${Number(p.tarifa_base||0).toFixed(0)}/h · ★ ${Number(p.karma||5).toFixed(1)}`;copy.append(name,cat,meta);el.appendChild(copy);const dot=document.createElement('i');dot.className=p.online&&p.disponible?'online':'offline';el.appendChild(dot);return el}
function categoryByHint(categories:Category[],hint:string|null|undefined){if(!hint)return null;const q=hint.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');return categories.find(c=>[c.nombre,c.slug].filter(Boolean).some(v=>{const n=String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');return n.includes(q)||q.includes(n)}))||null}
function etaLabel(meta:EtaMeta|undefined){if(!meta)return'';const minutes=Math.max(1,Math.round(meta.etaSeconds/60));return`${minutes} min`}
function clearRoute(map:maplibregl.Map){if(map.getLayer(ROUTE_LAYER))map.removeLayer(ROUTE_LAYER);if(map.getSource(ROUTE_SOURCE))map.removeSource(ROUTE_SOURCE)}

export function ClientQuantumExperience({supabase,categories,selectedCategoryId,onCategorySelect,onProviderPick,onIntent}:Props){
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),markers=useRef<maplibregl.Marker[]>([])
 const[userPos,setUserPos]=useState<[number,number]>(FLORIPA),[providers,setProviders]=useState<ProviderMapRow[]>([]),[selected,setSelected]=useState<string|null>(null),[drawer,setDrawer]=useState(false),[etaByProvider,setEtaByProvider]=useState<Record<string,EtaMeta>>({}),[search,setSearch]=useState('')
 const categoryFiltered=useMemo(()=>providers.filter(p=>!selectedCategoryId||!p.categoria_principal_id||p.categoria_principal_id===selectedCategoryId),[providers,selectedCategoryId])
 const filtered=useMemo(()=>[...categoryFiltered].filter(p=>!search.trim()||`${p.nombre||''} ${p.categoria_nombre||''} ${p.especialidades||''}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>{const availability=Number(Boolean(b.online&&b.disponible))-Number(Boolean(a.online&&a.disponible));if(availability)return availability;const ae=etaByProvider[a.id]?.etaSeconds??Number.MAX_SAFE_INTEGER,be=etaByProvider[b.id]?.etaSeconds??Number.MAX_SAFE_INTEGER;if(ae!==be)return ae-be;return Number(b.karma||0)-Number(a.karma||0)}),[categoryFiltered,etaByProvider,search])
 const selectedProvider=useMemo(()=>filtered.find(p=>p.id===selected)||providers.find(p=>p.id===selected)||null,[filtered,providers,selected])
 const featured=filtered.slice(0,3)
 useEffect(()=>{let alive=true;async function load(){const{data,error}=await supabase.from('proveedores_mapa').select('*').order('online',{ascending:false}).order('disponible',{ascending:false}).limit(50);if(alive&&!error)setProviders((data||[])as ProviderMapRow[])}load().catch(()=>{});const ch=supabase.channel('client-provider-map').on('postgres_changes',{event:'*',schema:'public',table:'perfiles_proveedor'},()=>load()).subscribe();return()=>{alive=false;supabase.removeChannel(ch)}},[supabase])
 useEffect(()=>{function local(event:Event){const text=String((event as CustomEvent<{text?:string}>).detail?.text||'').trim();if(!text)return;const intent=parseClientIntent(text,categories);if(intent.categoryId){onCategorySelect(intent.categoryId);setDrawer(true);onIntent?.({categoryId:intent.categoryId,categoryName:intent.categoryName||'',urgency:intent.urgency,description:text})}}function ai(event:Event){const d=(event as CustomEvent<{text?:string;categoryHint?:string|null;urgent?:boolean;description?:string|null}>).detail||{};const matched=categoryByHint(categories,d.categoryHint);if(!matched)return;onCategorySelect(matched.id);setDrawer(true);onIntent?.({categoryId:matched.id,categoryName:matched.nombre,urgency:Boolean(d.urgent),description:String(d.description||d.text||'').trim()})}window.addEventListener('ugo:hugo-user-text',local as EventListener);window.addEventListener('ugo:hugo-ai-intent',ai as EventListener);return()=>{window.removeEventListener('ugo:hugo-user-text',local as EventListener);window.removeEventListener('ugo:hugo-ai-intent',ai as EventListener)}},[categories,onCategorySelect,onIntent])
 useEffect(()=>{navigator.geolocation?.getCurrentPosition(pos=>{const next:[number,number]=[pos.coords.longitude,pos.coords.latitude];setUserPos(next);try{sessionStorage.setItem('ugo:last-client-location',JSON.stringify({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,at:Date.now()}))}catch{}},()=>{},{enableHighAccuracy:true,timeout:8000,maximumAge:60000})},[])
 useEffect(()=>{let alive=true;const candidates=categoryFiltered.filter(p=>p.lat!=null&&p.lng!=null&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng))).map(p=>({providerId:p.id,location:{latitude:Number(p.lat),longitude:Number(p.lng)},available:Boolean(p.online&&p.disponible)}));if(!candidates.length){setEtaByProvider({});return()=>{alive=false}};getRoutingProvider().rankByEta({latitude:userPos[1],longitude:userPos[0]},candidates).then(rows=>{if(!alive)return;const next:Record<string,EtaMeta>={};rows.forEach(row=>{next[row.providerId]={etaSeconds:row.etaSeconds,distanceMeters:row.distanceMeters}});setEtaByProvider(next)}).catch(()=>{if(alive)setEtaByProvider({})});return()=>{alive=false}},[categoryFiltered,userPos])
 useEffect(()=>{if(!mapEl.current||mapRef.current)return;const map=new maplibregl.Map({container:mapEl.current,style:MAP_STYLE,center:userPos,zoom:14,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-left');mapRef.current=map;return()=>{markers.current.forEach(m=>m.remove());markers.current=[];if(map.isStyleLoaded())clearRoute(map);map.remove();mapRef.current=null}},[])
 useEffect(()=>{if(!selected)mapRef.current?.easeTo({center:userPos,zoom:14,duration:700})},[selected,userPos])
 useEffect(()=>{const map=mapRef.current;if(!map)return;markers.current.forEach(m=>m.remove());markers.current=[];const user=document.createElement('div');user.className='ugo-user-marker';user.appendChild(document.createElement('span'));markers.current.push(new maplibregl.Marker({element:user}).setLngLat(userPos).addTo(map));filtered.forEach(p=>{if(p.lat==null||p.lng==null||!Number.isFinite(Number(p.lat))||!Number.isFinite(Number(p.lng)))return;const el=markerNode(p,p.id===selected);el.onclick=()=>{setSelected(p.id);setDrawer(true)};markers.current.push(new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat([Number(p.lng),Number(p.lat)]).addTo(map))})},[filtered,selected,userPos])
 useEffect(()=>{const map=mapRef.current;if(!map)return;let alive=true;const provider=selectedProvider;if(!provider||provider.lat==null||provider.lng==null||!Number.isFinite(Number(provider.lat))||!Number.isFinite(Number(provider.lng))){if(map.isStyleLoaded())clearRoute(map);return()=>{alive=false}}const origin={latitude:Number(provider.lat),longitude:Number(provider.lng)},destination={latitude:userPos[1],longitude:userPos[0]};getRoutingProvider().route(origin,destination).then(route=>{if(!alive||!mapRef.current)return;const current=mapRef.current;const geometry=(route.geometry&&typeof route.geometry==='object'&&(route.geometry as any).type==='LineString')?route.geometry:{type:'LineString',coordinates:[[origin.longitude,origin.latitude],[destination.longitude,destination.latitude]]};const render=()=>{if(!alive||!current.isStyleLoaded())return;clearRoute(current);current.addSource(ROUTE_SOURCE,{type:'geojson',data:{type:'Feature',properties:{},geometry} as any});current.addLayer({id:ROUTE_LAYER,type:'line',source:ROUTE_SOURCE,layout:{'line-cap':'round','line-join':'round'},paint:{'line-width':5,'line-opacity':0.82,'line-color':'#0a9f5a'}});const bounds=new maplibregl.LngLatBounds();(geometry as any).coordinates.forEach((c:[number,number])=>bounds.extend(c));if(!bounds.isEmpty())current.fitBounds(bounds,{padding:90,maxZoom:15,duration:700})};if(current.isStyleLoaded())render();else current.once('load',render)}).catch(()=>{});return()=>{alive=false}},[selectedProvider,userPos])
 function pickProvider(p:ProviderMapRow){setSelected(p.id);setDrawer(true)}
 return <section className="ugo-quantum-shell ugo-responsive-home">
  <div className="ugo-map-stage"><div ref={mapEl} className="ugo-map-canvas"/></div>
  <aside className="ugo-home-panel">
   <div className="ugo-home-brand-row"><div className="ugo-home-brand">UGO</div><div className="ugo-location-pill"><b>●</b><span>Mi ubicación<small>Florianópolis</small></span><em>⌄</em></div></div>
   <div className="ugo-home-copy"><h1>¿Qué servicio necesitás?</h1><p>Encontrá profesionales verificados cerca tuyo.</p></div>
   <label className="ugo-home-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar un servicio o profesional..."/></label>
   <div className="ugo-category-row">{categories.slice(0,5).map(c=><button type="button" key={c.id} className={selectedCategoryId===c.id?'active':''} onClick={()=>onCategorySelect(selectedCategoryId===c.id?'':c.id)}><b>{c.emoji||'•'}</b><span>{c.nombre}</span></button>)}</div>
   <div className="ugo-featured-head"><div><small>PROFESIONALES CERCA</small><h2>{selectedCategoryId?'Disponibles ahora':'Destacados'}</h2></div><button type="button" onClick={()=>setDrawer(true)}>Ver todos →</button></div>
   <div className="ugo-featured-grid">{featured.length===0?<div className="ugo-home-empty">No hay profesionales disponibles para este filtro.</div>:featured.map(p=><button type="button" key={p.id} className="ugo-feature-card" onClick={()=>pickProvider(p)}><span className="ugo-feature-avatar">{p.foto_url?<img src={p.foto_url} alt=""/>:(p.nombre?.[0]||'P').toUpperCase()}</span><span className="ugo-feature-copy"><b>{p.nombre||'Profesional UGO'}</b><small>{p.categoria_emoji} {p.categoria_nombre||'Especialista'}</small><em>★ {Number(p.karma||5).toFixed(1)} · {p.servicios_completados||0} servicios</em><strong>R$ {Number(p.tarifa_base||0).toFixed(0)} / hora</strong></span><span className={p.online&&p.disponible?'ugo-verified live':'ugo-verified'}>{p.estado_verificacion==='verificado'?'✓ Verificado':'En revisión'}</span>{etaByProvider[p.id]&&<span className="ugo-feature-eta">{etaLabel(etaByProvider[p.id])}</span>}</button>)}</div>
  </aside>
  <div className="ugo-hugo-badge"><span>⌣</span><small>Hola, soy Hugo<br/>Siempre listo para ayudarte</small></div>
  <nav className="ugo-mobile-nav"><button className="active">⌂<span>Inicio</span></button><button>▣<span>Mis servicios</span></button><button>□<span>Mensajes</span></button><button>♙<span>Perfil</span></button></nav>
  {drawer&&<div className="ugo-drawer-backdrop" onClick={()=>setDrawer(false)}><div className="ugo-provider-drawer" onClick={e=>e.stopPropagation()}><div className="ugo-drawer-handle"/><div className="ugo-drawer-title-row"><div><small>PROFESIONALES</small><h2>Elegí con confianza</h2></div><button type="button" onClick={()=>setDrawer(false)}>×</button></div><div className="ugo-provider-list">{filtered.length===0&&<p className="ugo-empty">No hay profesionales disponibles para esta categoría.</p>}{filtered.map(p=>{const active=p.id===selected;return <button type="button" key={p.id} className={`ugo-provider-card${active?' selected':''}`} onClick={()=>setSelected(p.id)}><span className="ugo-card-avatar">{p.foto_url?<img src={p.foto_url} alt=""/>:(p.nombre?.[0]||'P').toUpperCase()}</span><span className="ugo-card-main"><b>{p.nombre||'Profesional UGO'}</b><small>{p.categoria_nombre||'Especialista'}</small><em><span className={p.online&&p.disponible?'available':'offline'}>{p.online&&p.disponible?'Disponible ahora':'No disponible'}</span>{etaByProvider[p.id]?` · ${etaLabel(etaByProvider[p.id])}`:''} · ★ {Number(p.karma||5).toFixed(1)}</em></span><strong>R$ {Number(p.tarifa_base||0).toFixed(0)}/h</strong></button>})}</div>{selectedProvider&&<div className="ugo-provider-full-profile"><h3>{selectedProvider.nombre}</h3><p>{selectedProvider.bio||'Profesional verificado por UGO.'}</p><div className="ugo-provider-facts"><span>✅ {selectedProvider.estado_verificacion==='verificado'?'Verificado':'Verificación pendiente'}</span><span>📍 {selectedProvider.ciudad_base||selectedProvider.zona||'Florianópolis'}</span>{etaByProvider[selectedProvider.id]&&<span>🚗 Llegada estimada: {etaLabel(etaByProvider[selectedProvider.id])}</span>}<span>🧰 {selectedProvider.especialidades||selectedProvider.categoria_nombre||'Especialidad no informada'}</span><span>🏅 {selectedProvider.experiencia_anos!=null?`${selectedProvider.experiencia_anos} años de experiencia`:'Experiencia no informada'}</span><span>🗣 {selectedProvider.idiomas||'Idiomas no informados'}</span></div><button type="button" className="ugo-hire-button" onClick={()=>{onProviderPick(selectedProvider);setDrawer(false)}}>Contratar</button></div>}</div></div>}
 </section>
}
