import React,{useCallback,useEffect,useState}from'react'
import{AuthScreen,LoadingScreen,useRoleSession}from'./shared'
import{ClientApp}from'./ClientApp'
import'./onboarding-steps.css'

const TERMS_VERSION='2026-09-07'
type Form={nombre:string;apellido:string;telefono:string;direccion:string;barrio:string;ciudad:string;idioma:string;contacto:string;horarios:string;acceso:string;preferencias:string;observaciones:string;lat:number|null;lng:number|null}
const empty:Form={nombre:'',apellido:'',telefono:'',direccion:'',barrio:'',ciudad:'Florianópolis',idioma:'pt-BR',contacto:'whatsapp',horarios:'',acceso:'',preferencias:'',observaciones:'',lat:null,lng:null}

export function ClientFirstRunOnboarding(){
 const auth=useRoleSession('client'),{supabase,session,profile}=auth
 const[loading,setLoading]=useState(true),[complete,setComplete]=useState(false),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[terms,setTerms]=useState(false),[msg,setMsg]=useState(''),[form,setForm]=useState<Form>(empty)
 const load=useCallback(async()=>{if(!session||!profile){setLoading(false);return}setLoading(true);try{const[{data:u,error:ue},{data:p,error:pe}]=await Promise.all([supabase.from('usuarios').select('nombre,apellido,lat,lng').eq('id',session.user.id).single(),supabase.from('perfiles_cliente').select('*').eq('usuario_id',session.user.id).maybeSingle()]);if(ue)throw ue;if(pe)throw pe;setComplete(Boolean(p?.onboarding_completo_at));setTerms(Boolean(p?.termos_aceitos_at));setForm({nombre:u?.nombre||profile.nombre||'',apellido:u?.apellido||'',telefono:p?.telefono||'',direccion:p?.direccion||'',barrio:p?.barrio||'',ciudad:p?.ciudad||'Florianópolis',idioma:p?.idioma_preferido||'pt-BR',contacto:p?.contacto_preferido||'whatsapp',horarios:p?.horarios_preferidos||'',acceso:p?.instrucciones_acceso||'',preferencias:p?.preferencias_servicio||'',observaciones:p?.observaciones||'',lat:u?.lat??null,lng:u?.lng??null})}catch(e:any){setMsg(e.message||'No se pudo cargar tu ficha.')}finally{setLoading(false)}},[profile,session,supabase])
 useEffect(()=>{load()},[load])
 function validate(s:number){if(s===1){if(!form.nombre.trim())throw new Error('Ingresá tu nombre.');if(form.telefono.replace(/\D/g,'').length<8)throw new Error('Ingresá un WhatsApp válido.')}if(s===2){if(!form.direccion.trim())throw new Error('Ingresá la dirección del servicio.');if(!form.ciudad.trim())throw new Error('Ingresá tu ciudad.')}}
 async function next(){try{setMsg('');validate(step);setStep(v=>Math.min(4,v+1))}catch(e:any){setMsg(e.message)}}
 function locate(){if(!navigator.geolocation)return setMsg('Este dispositivo no ofrece ubicación.');setBusy(true);navigator.geolocation.getCurrentPosition(pos=>{setForm(v=>({...v,lat:pos.coords.latitude,lng:pos.coords.longitude}));setBusy(false);setMsg('Ubicación capturada.')},()=>{setBusy(false);setMsg('No se pudo obtener la ubicación. Podés escribir la dirección manualmente.')},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
 async function finish(){if(!session)return;setMsg('');setBusy(true);try{validate(1);validate(2);if(!terms)throw new Error('Aceptá los términos para continuar.');const{error:extra}=await supabase.from('perfiles_cliente').upsert({usuario_id:session.user.id,horarios_preferidos:form.horarios||null,instrucciones_acceso:form.acceso||null,preferencias_servicio:form.preferencias||null,observaciones:form.observaciones||null},{onConflict:'usuario_id'});if(extra)throw extra;const{error}=await supabase.rpc('completar_onboarding_cliente',{p_nombre:form.nombre.trim(),p_apellido:form.apellido.trim(),p_telefono:form.telefono.trim(),p_direccion:form.direccion.trim(),p_barrio:form.barrio.trim(),p_ciudad:form.ciudad.trim(),p_idioma_preferido:form.idioma,p_contacto_preferido:form.contacto,p_termos_versao:TERMS_VERSION,p_lat:form.lat,p_lng:form.lng});if(error)throw error;setComplete(true)}catch(e:any){setMsg(e.message||'No se pudo completar el cadastro.')}finally{setBusy(false)}}
 if(auth.loading||loading)return<LoadingScreen label="Preparando tu cuenta UGO…"/>
 if(!session||!profile)return<AuthScreen role="client" supabase={supabase} error={auth.error} onError={auth.setError}/>
 if(complete)return<ClientApp/>
 return <main className="ugo-onboard"><section className="ugo-onboard-card"><div className="ugo-onboard-brand"><div><small>UGO · CLIENTE</small><h1>Creá tu ficha</h1><p>Te pedimos solo lo necesario y lo guardamos paso a paso.</p></div><span className="ugo-onboard-role">👤</span></div><div className="ugo-onboard-progress" style={{'--steps':4} as React.CSSProperties}>{[1,2,3,4].map(n=><i key={n} className={n<=step?'on':''}/>)}</div><div className="ugo-onboard-step">PASO {step} DE 4</div>
 {step===1&&<><h2 className="ugo-onboard-title">Datos personales</h2><div className="ugo-onboard-fields"><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Nombre<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label className="ugo-onboard-field">Apellido<input value={form.apellido} onChange={e=>setForm({...form,apellido:e.target.value})}/></label></div><label className="ugo-onboard-field">Email<input className="ugo-onboard-readonly" value={session.user.email||''} readOnly/></label><label className="ugo-onboard-field">WhatsApp / teléfono<input placeholder="+55…" value={form.telefono} onChange={e=>setForm({...form,telefono:e.target.value})}/></label></div></>}
 {step===2&&<><h2 className="ugo-onboard-title">¿Dónde usás UGO?</h2><div className="ugo-onboard-fields"><label className="ugo-onboard-field">Dirección<input placeholder="Calle y número" value={form.direccion} onChange={e=>setForm({...form,direccion:e.target.value})}/></label><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Barrio / zona<input value={form.barrio} onChange={e=>setForm({...form,barrio:e.target.value})}/></label><label className="ugo-onboard-field">Ciudad<input value={form.ciudad} onChange={e=>setForm({...form,ciudad:e.target.value})}/></label></div><button type="button" className="ugo-onboard-location" onClick={locate} disabled={busy}>{form.lat!=null?'📍 Ubicación capturada':'📍 Usar mi ubicación actual'}</button></div></>}
 {step===3&&<><h2 className="ugo-onboard-title">Preferencias</h2><div className="ugo-onboard-fields"><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Idioma<select value={form.idioma} onChange={e=>setForm({...form,idioma:e.target.value})}><option value="pt-BR">Português</option><option value="es-AR">Español</option><option value="en">English</option></select></label><label className="ugo-onboard-field">Contacto preferido<select value={form.contacto} onChange={e=>setForm({...form,contacto:e.target.value})}><option value="whatsapp">WhatsApp</option><option value="telefono">Teléfono</option><option value="chat">Chat UGO</option></select></label></div><label className="ugo-onboard-field">Horarios preferidos<input value={form.horarios} onChange={e=>setForm({...form,horarios:e.target.value})} placeholder="Ej: tardes, después de las 14"/></label><label className="ugo-onboard-field">Instrucciones de acceso<input value={form.acceso} onChange={e=>setForm({...form,acceso:e.target.value})} placeholder="Portería, bloque, referencia…"/></label><label className="ugo-onboard-field">Preferencias de servicio<textarea value={form.preferencias} onChange={e=>setForm({...form,preferencias:e.target.value})}/></label><label className="ugo-onboard-field">Observaciones<textarea value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label></div></>}
 {step===4&&<><h2 className="ugo-onboard-title">Confirmá tu ficha</h2><div className="ugo-onboard-summary"><span><b>{form.nombre} {form.apellido}</b></span><span>📞 {form.telefono}</span><span>📍 {[form.direccion,form.barrio,form.ciudad].filter(Boolean).join(', ')}</span><span>🗣 {form.idioma} · {form.contacto}</span></div><label className="ugo-onboard-terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Acepto los términos de uso y la política de privacidad de UGO para gestionar mi cuenta, contacto, ubicación y pedidos.</span></label></>}
 {msg&&<div className="ugo-onboard-message">{msg}</div>}<div className="ugo-onboard-actions">{step>1&&<button type="button" className="ugo-onboard-back" onClick={()=>{setMsg('');setStep(step-1)}}>Atrás</button>}{step<4?<button type="button" className="ugo-onboard-next" onClick={next}>Continuar</button>:<button type="button" className="ugo-onboard-next" onClick={finish} disabled={busy}>{busy?'Guardando…':'Guardar y entrar a UGO'}</button>}</div><button type="button" className="ugo-onboard-signout" onClick={auth.signOut}>Cerrar sesión</button></section></main>
}
