import React,{useCallback,useEffect,useState}from'react'
import type{FormEvent}from'react'
import{ACTIVE_STATES,AppHeader,AuthScreen,LoadingScreen,StateTimeline,STATUS_LABELS,money,useRoleSession,type Category,type Offer,type Payment,type Service,type Notice}from'./shared'
import{VoiceHugoDock}from'./VoiceHugoDock'
import{ClientQuantumExperience}from'./ClientQuantumExperience'

type MercadoPagoPayment=Payment&{mp_payment_id?:string|null;mp_preference_id?:string|null;mp_status?:string|null}

export function ClientApp(){
 const auth=useRoleSession('client'),{supabase,session,profile}=auth;const[categories,setCategories]=useState<Category[]>([]),[service,setService]=useState<Service|null>(null),[offers,setOffers]=useState<Offer[]>([]),[payment,setPayment]=useState<MercadoPagoPayment|null>(null),[reviewed,setReviewed]=useState(false),[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(false),[rating,setRating]=useState(5),[comment,setComment]=useState('');const[form,setForm]=useState({categoria_id:'',descripcion:'',direccion:'',tarifa:'120',urgencia:false})
 const loadData=useCallback(async()=>{if(!session)return;const[{data:cats},{data:rows}]=await Promise.all([supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.from('servicios').select('*,categoria:categorias(nombre,emoji),proveedor:usuarios!servicios_proveedor_id_fkey(nombre,karma)').eq('cliente_id',session.user.id).order('created_at',{ascending:false}).limit(10)]);setCategories((cats||[])as Category[]);if(cats?.[0])setForm(v=>v.categoria_id?v:{...v,categoria_id:cats[0].id});const list=(rows||[])as Service[],next=list.find(r=>ACTIVE_STATES.includes(r.estado))||list[0]||null;setService(next);if(next){const[{data:o},{data:p},{data:r}]=await Promise.all([supabase.from('ofertas_servicio').select('*').eq('servicio_id',next.id).order('ranking'),supabase.from('pagos').select('*').eq('servicio_id',next.id).order('created_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('resenas').select('id').eq('servicio_id',next.id).maybeSingle()]);setOffers((o||[])as Offer[]);setPayment((p as MercadoPagoPayment|null)||null);setReviewed(Boolean(r))}else{setOffers([]);setPayment(null);setReviewed(false)}},[session,supabase])
 useEffect(()=>{loadData().catch((e:Error)=>setNotice({type:'error',text:e.message}))},[loadData]);useEffect(()=>{if(!session)return;const ch=supabase.channel(`client-${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'servicios',filter:`cliente_id=eq.${session.user.id}`},loadData).on('postgres_changes',{event:'*',schema:'public',table:'ofertas_servicio'},loadData).on('postgres_changes',{event:'*',schema:'public',table:'pagos'},loadData).subscribe();return()=>{supabase.removeChannel(ch)}},[loadData,session,supabase])
 useEffect(()=>{const params=new URLSearchParams(window.location.search),result=params.get('pago');if(!result)return;if(result==='confirmado')setNotice({type:'ok',text:'Mercado Pago confirmó el checkout. Estamos verificando el pago en la bóveda.'});else if(result==='pendiente')setNotice({type:'info',text:'El pago quedó pendiente en Mercado Pago.'});else if(result==='fallido')setNotice({type:'error',text:'El pago no se completó. Podés intentarlo nuevamente.'});const clean=new URL(window.location.href);clean.searchParams.delete('pago');clean.searchParams.delete('svc');window.history.replaceState({},'',clean.toString());loadData().catch(()=>{})},[loadData])
 async function create(e:FormEvent){e.preventDefault();if(!session)return;setBusy(true);setNotice(null);try{const amount=Number(form.tarifa);if(!form.categoria_id||form.descripcion.trim().length<8)throw new Error('Elegí categoría y describí mejor el trabajo.');if(!Number.isFinite(amount)||amount<=0)throw new Error('Ingresá un presupuesto válido.');const{data,error}=await supabase.from('servicios').insert({cliente_id:session.user.id,categoria_id:form.categoria_id,estado:'buscando',descripcion:form.descripcion.trim(),direccion_cliente:form.direccion.trim()||null,tarifa:amount,urgencia:form.urgencia,metadata:{source:'mvp-react',demo:false}}).select('*').single();if(error)throw error;const{data:m,error:x}=await supabase.rpc('iniciar_matching',{p_servicio_id:data.id});if(x)throw x;const n=Array.isArray(m)?m.length:0;setNotice({type:n?'ok':'info',text:n?`Hugo envió ${n} oferta${n===1?'':'s'}.`:'Pedido creado. Activá un proveedor compatible para recibirlo.'});await loadData()}catch(x){setNotice({type:'error',text:x instanceof Error?x.message:'No se pudo crear el servicio.'})}finally{setBusy(false)}}
 async function pay(){if(!service||!session)return;setBusy(true);setNotice(null);try{const response=await fetch('/api/pagos/crear',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({servicioId:service.id})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No se pudo iniciar Mercado Pago.');if(data.alreadyPaid){setNotice({type:'ok',text:'El pago ya está confirmado y protegido en la bóveda.'});await loadData();return}if(!data.initPoint)throw new Error('Mercado Pago no devolvió el enlace de checkout.');window.location.assign(data.initPoint)}catch(x){setNotice({type:'error',text:x instanceof Error?x.message:'No se pudo iniciar el pago.'});setBusy(false)}}
 async function rpc(name:string){if(!service)return;setBusy(true);const{error}=await supabase.rpc(name,{p_servicio_id:service.id});setBusy(false);if(error)return setNotice({type:'error',text:error.message});setNotice({type:'ok',text:name==='aprobar_servicio'?'Trabajo aprobado y pago liberado.':'Servicio cancelado.'});await loadData()}
 async function review(e:FormEvent){e.preventDefault();if(!service?.proveedor_id||!session)return;setBusy(true);const{error}=await supabase.from('resenas').insert({servicio_id:service.id,cliente_id:session.user.id,proveedor_id:service.proveedor_id,puntuacion:rating,comentario:comment.trim()||null});setBusy(false);if(error)return setNotice({type:'error',text:error.message});setReviewed(true);setNotice({type:'ok',text:'Reseña guardada y Karma actualizado.'})}
 if(auth.loading)return<LoadingScreen/>;if(!session||!profile)return<AuthScreen role="client" supabase={supabase} error={auth.error} onError={auth.setError}/>;const active=Boolean(service&&ACTIVE_STATES.includes(service.estado)),completed=service?.estado==='completado',funded=payment?.estado==='retenido'&&Boolean(payment.mp_payment_id),needsPayment=service?.estado==='asignado'&&!funded
 return <div className="mvp-shell"><AppHeader role="CLIENTE" name={profile.nombre} onLogout={auth.signOut}/><main className="mvp-layout"><section className="mvp-hero-card"><div><span className="mvp-live"><i/>Hugo está operativo</span><h1>{active&&service?STATUS_LABELS[service.estado]:'¿Qué necesitás resolver?'}</h1><p>{active&&service?`Servicio #${service.numero} · ${service.descripcion}`:'Buscá profesionales reales en el mapa o pedile a Hugo que arme la misión.'}</p></div><div className="mvp-map-art"><span className="pulse-a"/><span className="pulse-b"/><b>📍</b></div></section>{notice&&<div className={`mvp-notice ${notice.type}`}>{notice.text}</div>}
 {!active&&!completed&&<ClientQuantumExperience supabase={supabase} categories={categories} selectedCategoryId={form.categoria_id} onCategorySelect={id=>setForm(v=>({...v,categoria_id:id}))} onProviderPick={p=>{setForm(v=>({...v,categoria_id:p.categoria_principal_id||v.categoria_id,tarifa:p.tarifa_base?String(p.tarifa_base):v.tarifa,descripcion:v.descripcion||`Necesito contratar a ${p.nombre||'este profesional'} para este trabajo.`}));setNotice({type:'info',text:`Elegiste a ${p.nombre||'un profesional'}. Hugo usará su categoría y tarifa como referencia para el matching.`});setTimeout(()=>document.querySelector('.mvp-service-form')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}}/>}
 {!active&&!completed&&<form className="mvp-card mvp-service-form" onSubmit={create}><div className="mvp-card-title"><div><small>NUEVA SOLICITUD</small><h2>Hugo arma la misión</h2></div><span>01</span></div><div className="mvp-category-grid">{categories.map(c=><button type="button" key={c.id} className={form.categoria_id===c.id?'selected':''} onClick={()=>setForm({...form,categoria_id:c.id})}><b>{c.emoji}</b><span>{c.nombre}</span></button>)}</div><label>Descripción<textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} placeholder="La ducha pierde agua y necesito repararla hoy."/></label><div className="mvp-two-cols"><label>Dirección<input value={form.direccion} onChange={e=>setForm({...form,direccion:e.target.value})} placeholder="Calle, número y barrio"/></label><label>Presupuesto<input type="number" min="1" value={form.tarifa} onChange={e=>setForm({...form,tarifa:e.target.value})}/></label></div><label className="mvp-toggle-line"><input type="checkbox" checked={form.urgencia} onChange={e=>setForm({...form,urgencia:e.target.checked})}/><span>Es una urgencia</span></label><button className="mvp-primary" disabled={busy}>{busy?'Buscando…':'Crear servicio y hacer matching'}</button></form>}
 {service&&<section className="mvp-card"><div className="mvp-card-title"><div><small>OPERACIÓN EN VIVO</small><h2>Servicio #{service.numero}</h2></div><span className={`mvp-status status-${service.estado}`}>{STATUS_LABELS[service.estado]}</span></div><StateTimeline state={service.estado}/><div className="mvp-operation-grid"><div><small>CATEGORÍA</small><strong>{service.categoria?.emoji} {service.categoria?.nombre||'Servicio'}</strong></div><div><small>PROVEEDOR</small><strong>{service.proveedor?.nombre||'Pendiente'}</strong></div><div><small>TOTAL</small><strong>{money(service.tarifa,service.moneda)}</strong></div><div><small>BÓVEDA</small><strong>{funded?'Pago protegido':payment?.estado==='liberado'?'Pago liberado':needsPayment?'Esperando tu pago':payment?STATUS_LABELS[payment.estado]||payment.estado:'Sin pago'}</strong></div></div>{offers.length>0&&service.estado==='ofrecido'&&<div className="mvp-offer-strip">{offers.filter(o=>o.estado==='pendiente').map(o=><span key={o.id}>Oferta #{o.ranking||'—'} · {money(o.tarifa_ofrecida,service.moneda)}</span>)}</div>}{needsPayment&&<div className="mvp-waiting">El profesional ya aceptó. Para habilitar el inicio del trabajo, protegé el importe con Mercado Pago.</div>}<div className="mvp-actions">{needsPayment&&<button className="mvp-primary" onClick={pay} disabled={busy}>{busy?'Abriendo Mercado Pago…':`Pagar ${money(service.tarifa,service.moneda)}`}</button>}{service.estado==='esperando_aprobacion'&&<button className="mvp-primary" onClick={()=>rpc('aprobar_servicio')} disabled={busy}>Aprobar y liberar pago</button>}{['buscando','ofrecido','asignado','en_camino'].includes(service.estado)&&<button className="mvp-danger" onClick={()=>window.confirm('¿Cancelar?')&&rpc('cancelar_servicio')} disabled={busy}>Cancelar</button>}</div></section>}
 {completed&&!reviewed&&<form className="mvp-card mvp-review" onSubmit={review}><div className="mvp-card-title"><div><small>CIERRE</small><h2>Calificá la experiencia</h2></div><span>★</span></div><div className="mvp-stars">{[1,2,3,4,5].map(v=><button type="button" key={v} onClick={()=>setRating(v)} className={v<=rating?'on':''}>★</button>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Comentario opcional"/><button className="mvp-primary" disabled={busy}>Guardar reseña</button></form>}</main><VoiceHugoDock role="client" accessToken={session.access_token} service={service} availableOffers={offers.filter(o=>o.estado==='pendiente').length}/></div>
}
