import React,{useCallback,useEffect,useMemo,useState}from'react'
import{supabase}from'../lib/supabase'
import{parseClientIntent}from'./hugoIntent'
import{getDispatchProvider}from'../lib/dispatch/provider'
import type{Category}from'./shared'

type Draft={categoryId:string;categoryName:string;categorySlug:string;description:string;urgent:boolean;address:string;amount:number}
function norm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function byHint(categories:Category[],hint:string){const q=norm(hint);return categories.find(c=>[c.nombre,c.slug].some(x=>{const n=norm(String(x||''));return n.includes(q)||q.includes(n)}))||null}

export function ClientQuickOrder(){
 const[categories,setCategories]=useState<Category[]>([]),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const loadBase=useCallback(async()=>{const[{data:cats},{data:user}]=await Promise.all([supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.auth.getUser()]);setCategories((cats||[])as Category[]);return user.user||null},[])
 useEffect(()=>{loadBase().catch(()=>{})},[loadBase])
 const prepare=useCallback(async(category:Category,description:string,urgent:boolean)=>{const{data:userData}=await supabase.auth.getUser();if(!userData.user)return;const[{data:profile},{data:providers}]=await Promise.all([supabase.from('perfiles_cliente').select('direccion,barrio,ciudad').eq('usuario_id',userData.user.id).maybeSingle(),supabase.from('proveedores_mapa').select('tarifa_base').eq('categoria_principal_id',category.id).eq('online',true).eq('disponible',true).limit(8)]);const address=[(profile as any)?.direccion,(profile as any)?.barrio,(profile as any)?.ciudad].filter(Boolean).join(', ');const prices=(providers||[]).map((p:any)=>Number(p.tarifa_base)).filter((n:number)=>Number.isFinite(n)&&n>0).sort((a:number,b:number)=>a-b);const amount=prices.length?prices[Math.floor(prices.length/2)]:120;setDraft({categoryId:category.id,categoryName:category.nombre,categorySlug:category.slug,description:description.trim(),urgent,address,amount});setMessage('')},[])
 useEffect(()=>{function local(event:Event){const text=String((event as CustomEvent<{text?:string}>).detail?.text||'').trim();if(!text||!categories.length)return;const intent=parseClientIntent(text,categories);const category=categories.find(c=>c.id===intent.categoryId);if(category)prepare(category,text,intent.urgency).catch(()=>{})}function ai(event:Event){const d=(event as CustomEvent<{text?:string;categoryHint?:string|null;urgent?:boolean;description?:string|null}>).detail||{};if(!d.categoryHint||!categories.length)return;const category=byHint(categories,String(d.categoryHint));if(category)prepare(category,String(d.description||d.text||'').trim(),Boolean(d.urgent)).catch(()=>{})}window.addEventListener('ugo:hugo-user-text',local as EventListener);window.addEventListener('ugo:hugo-ai-intent',ai as EventListener);return()=>{window.removeEventListener('ugo:hugo-user-text',local as EventListener);window.removeEventListener('ugo:hugo-ai-intent',ai as EventListener)}},[categories,prepare])
 const ready=useMemo(()=>Boolean(draft?.categoryId&&draft.description.length>=8&&draft.address&&draft.amount>0),[draft])
 async function confirm(){if(!draft||!ready)return;setBusy(true);setMessage('');try{const{data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user)throw new Error('Sesión requerida.');const{data,error}=await supabase.from('servicios').insert({cliente_id:user.id,categoria_id:draft.categoryId,estado:'buscando',descripcion:draft.description,direccion_cliente:draft.address,tarifa:draft.amount,urgencia:draft.urgent,metadata:{source:'hugo-one-tap',demo:false}}).select('id').single();if(error)throw error;const result=await getDispatchProvider().start({serviceId:data.id,category:draft.categorySlug});const n=Array.isArray(result.raw)?result.raw.length:result.providerId?1:0;setMessage(n?`Listo. Hugo ya avisó a ${n} profesional${n===1?'':'es'}.`:'Pedido creado. Hugo seguirá buscando profesionales disponibles.');setDraft(null)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo crear el pedido.')}finally{setBusy(false)}}
 if(!draft&&!message)return null
 return <div className="ugo-quick-order" style={{position:'fixed',left:'50%',bottom:154,transform:'translateX(-50%)',zIndex:78,width:'min(390px,calc(100vw - 28px))',background:'rgba(255,255,255,.96)',backdropFilter:'blur(16px)',borderRadius:22,padding:14,boxShadow:'0 18px 50px rgba(0,0,0,.22)'}}>{draft&&<><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><small style={{fontWeight:900}}>HUGO ENTENDIÓ</small><div style={{fontWeight:950,fontSize:18,marginTop:2}}>{draft.categoryName}{draft.urgent?' · Urgente':''}</div></div><button type="button" onClick={()=>setDraft(null)} style={{border:0,background:'transparent',fontSize:20}}>×</button></div><p style={{margin:'8px 0',fontSize:13,lineHeight:1.35}}>{draft.description}</p><div style={{display:'grid',gap:5,fontSize:12,padding:'9px 10px',borderRadius:13,background:'#f5f5f5'}}><span>📍 {draft.address||'Falta tu dirección'}</span><span>💰 Estimado: R$ {draft.amount.toFixed(0)}</span></div>{!draft.address&&<input autoFocus value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})} placeholder="Tu dirección" style={{width:'100%',marginTop:8,padding:11,borderRadius:12,border:'1px solid #ddd'}}/>}<button type="button" onClick={confirm} disabled={busy||!ready} style={{width:'100%',marginTop:10,padding:'13px 14px',border:0,borderRadius:14,fontWeight:950,fontSize:15,cursor:'pointer'}}>{busy?'Buscando…':'Confirmar pedido'}</button><button type="button" onClick={()=>setDraft(null)} style={{width:'100%',marginTop:6,padding:'8px',border:0,background:'transparent',fontWeight:800,fontSize:12}}>Elegir profesional en el mapa</button></>}{message&&<div style={{fontSize:13,fontWeight:800}}>{message}</div>}</div>
}
