import React,{useEffect,useMemo,useState}from'react'
import type{UgoRole}from'../lib/roleSupabase'
import{useParticipantDispute,type PreAgreement}from'../hooks/useDisputes'
import'./dispute-dock.css'

const label=(s:string)=>s==='abierta'?'Abierta':s==='en_revision'?'En revisión':s==='resuelta_cliente'?'Resuelta a favor del cliente':s==='resuelta_proveedor'?'Resuelta a favor del proveedor':s==='cerrada'?'Cerrada':s
const agreementLabel=(type:PreAgreement['tipo'])=>type==='retrabajo'?'Corregir o repetir parte del trabajo':type==='ajuste_precio'?'Ajustar el precio':type==='reagendar'?'Reagendar':'Otro acuerdo'

export function DisputeDock({role,openRequest=false,openRequestKey=0,serviceId=null,showLauncher=true}:{role:UgoRole;openRequest?:boolean;openRequestKey?:number;serviceId?:string|null;showLauncher?:boolean}){
 const{userId,service,dispute,messages,agreements,reasons,loading,error,ambiguous,uploadEvidence,open,reply,proposeAgreement,respondAgreement}=useParticipantDispute(role,serviceId)
 const[visible,setVisible]=useState(false),[text,setText]=useState(''),[reasonCode,setReasonCode]=useState(''),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null),[proposalType,setProposalType]=useState<PreAgreement['tipo']>('retrabajo'),[proposalText,setProposalText]=useState(''),[proposalAmount,setProposalAmount]=useState('')
 useEffect(()=>{if(openRequest||openRequestKey>0)setVisible(true)},[openRequest,openRequestKey])
 useEffect(()=>{if(!reasonCode&&reasons[0])setReasonCode(reasons[0].codigo)},[reasonCode,reasons])
 const pending=useMemo(()=>agreements.find(item=>item.estado==='propuesto')||null,[agreements])
 if(!service&&!dispute&&!ambiguous)return null
 const unresolved=Boolean(dispute&&['abierta','en_revision'].includes(dispute.estado))
 const submit=async()=>{if(!service)return setNotice('Elegí el pedido exacto desde Actividad antes de abrir una disputa.');const min=dispute?2:8;if(text.trim().length<min)return setNotice(dispute?'Escribí el mensaje que querés agregar.':'Contá un poco más qué pasó.');if(!dispute&&!reasonCode)return setNotice('Elegí el motivo del problema.');setBusy(true);setNotice(null);try{const evidence=await uploadEvidence(files);if(dispute)await reply(text.trim(),evidence);else await open(text.trim(),reasonCode,evidence);setText('');setFiles([]);setNotice(dispute?'Respuesta y evidencia agregadas al caso.':'Disputa abierta. UGO congeló el contexto del servicio para revisión.')}catch(e){setNotice(e instanceof Error?e.message:'No se pudo registrar la disputa.')}finally{setBusy(false)}}
 const propose=async()=>{if(proposalText.trim().length<8)return setNotice('Explicá la propuesta con un poco más de detalle.');const amount=proposalType==='ajuste_precio'&&proposalAmount?Number(proposalAmount):null;if(amount!=null&&(!Number.isFinite(amount)||amount<0))return setNotice('Ingresá un monto válido.');setBusy(true);setNotice(null);try{await proposeAgreement(proposalType,proposalText.trim(),amount);setProposalText('');setProposalAmount('');setNotice('Propuesta enviada. La otra parte puede aceptarla o rechazarla.')}catch(e){setNotice(e instanceof Error?e.message:'No se pudo enviar la propuesta.')}finally{setBusy(false)}}
 const answerAgreement=async(accept:boolean)=>{if(!pending)return;setBusy(true);setNotice(null);try{await respondAgreement(pending.id,accept);setNotice(accept?'Acuerdo aceptado. Si el problema queda resuelto, no hace falta abrir una disputa.':'Propuesta rechazada. Podés continuar con una disputa formal.')}catch(e){setNotice(e instanceof Error?e.message:'No se pudo responder la propuesta.')}finally{setBusy(false)}}
 const reason=reasons.find(item=>item.codigo===reasonCode)
 return <>
  {showLauncher&&<button className={'ugo-dispute-launch '+(unresolved?'open-case':'')} onClick={()=>setVisible(true)}>{unresolved?'⚖ Caso abierto':ambiguous?'⚖ Elegir servicio':'⚖ Ayuda / disputa'}</button>}
  {visible&&<div className="ugo-dispute-backdrop" onClick={()=>setVisible(false)}><section className="ugo-dispute-sheet" onClick={e=>e.stopPropagation()}><header><div><small>UGO · PROTECCIÓN DEL SERVICIO</small><h3>{dispute?'Disputa #'+(dispute.numero||String(dispute.id).slice(0,8)):service?'Servicio #'+service.numero:'Elegí un servicio'}</h3></div><button onClick={()=>setVisible(false)}>×</button></header>
   {loading&&<p>Cargando caso…</p>}{error&&<div className="ugo-dispute-note error">{error}</div>}
   {ambiguous&&!service&&<div className="ugo-dispute-note"><b>Tenés más de un servicio elegible.</b><span>Entrá a Actividad, abrí el servicio exacto y usá “Ayuda / disputa” desde ese pedido.</span></div>}
   {service&&(dispute?<>
    <div className={'ugo-dispute-status '+dispute.estado}><b>{label(dispute.estado)}</b><span>{dispute.motivo}</span>{dispute.requiere_humano&&<em>Revisión humana obligatoria</em>}</div>
    {dispute.resolucion&&<div className="ugo-dispute-resolution"><small>RESOLUCIÓN UGO</small><strong>{label(dispute.estado)}</strong><p>{dispute.resolucion}</p></div>}
    <div className="ugo-dispute-thread">{messages.map(m=><article key={m.id} className={m.autor_rol}><small>{m.autor_rol==='admin'?'UGO Admin':m.autor_rol==='cliente'?'Cliente':'Proveedor'} · {new Date(m.created_at).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small><p>{m.mensaje}</p>{m.evidencias?.length?<em>{m.evidencias.length} archivo(s) adjunto(s)</em>:null}</article>)}</div>
    {unresolved&&<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Agregá información para que UGO pueda revisar el caso…"/><label className="ugo-dispute-file">Adjuntar fotos o comprobante<input type="file" accept="image/*,.pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,5))}/><span>{files.length?files.map(file=>file.name).join(' · '):'Hasta 5 archivos · 10 MB cada uno'}</span></label><button className="primary" onClick={()=>void submit()} disabled={busy}>{busy?'Enviando…':'Enviar al caso'}</button></>}
   </>:<>
    <div className="ugo-dispute-note"><b>Primero podés intentar resolverlo entre ustedes.</b><span>UGO registra la propuesta. Si no hay acuerdo, podés abrir la disputa formal sin perder el historial.</span></div>
    {pending?<div className="ugo-preagreement-card"><small>PROPUESTA PENDIENTE</small><strong>{agreementLabel(pending.tipo)}</strong><p>{pending.detalle}</p>{pending.monto!=null&&<b>R$ {Number(pending.monto).toLocaleString('pt-BR',{minimumFractionDigits:2})}</b>}{pending.propuesto_por===userId?<span>Esperando respuesta de la otra parte.</span>:<div><button type="button" className="accept" disabled={busy} onClick={()=>void answerAgreement(true)}>Aceptar</button><button type="button" disabled={busy} onClick={()=>void answerAgreement(false)}>Rechazar</button></div>}</div>:<div className="ugo-preagreement-form"><select value={proposalType} onChange={e=>setProposalType(e.target.value as PreAgreement['tipo'])}><option value="retrabajo">Corregir / repetir tarea</option><option value="ajuste_precio">Ajustar precio</option><option value="reagendar">Reagendar</option><option value="otro">Otro acuerdo</option></select>{proposalType==='ajuste_precio'&&<input type="number" min="0" step="0.01" inputMode="decimal" value={proposalAmount} onChange={e=>setProposalAmount(e.target.value)} placeholder="Monto propuesto"/>}<textarea value={proposalText} onChange={e=>setProposalText(e.target.value)} placeholder="Proponé una solución concreta…"/><button type="button" className="secondary" disabled={busy} onClick={()=>void propose()}>{busy?'Enviando…':'Enviar propuesta amistosa'}</button></div>}
    {agreements[0]&&!pending&&<div className="ugo-dispute-note info"><b>Última propuesta: {agreements[0].estado}</b><span>{agreements[0].detalle}</span></div>}
    <div className="ugo-formal-dispute"><small>DISPUTA FORMAL</small><label>Motivo<select value={reasonCode} onChange={e=>setReasonCode(e.target.value)}>{reasons.map(item=><option key={item.codigo} value={item.codigo}>{item.etiqueta}</option>)}</select></label>{reason&&<p>{reason.evidencia_sugerida}{reason.requiere_humano?' · Este motivo siempre pasa a revisión humana.':''}</p>}<textarea value={text} onChange={e=>setText(e.target.value)} placeholder={role==='client'?'Explicá qué pasó con el proveedor o el trabajo…':'Explicá qué pasó con el cliente o el servicio…'}/><label className="ugo-dispute-file">Adjuntar fotos o comprobante<input type="file" accept="image/*,.pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,5))}/><span>{files.length?files.map(file=>file.name).join(' · '):'Hasta 5 archivos · 10 MB cada uno'}</span></label><button className="danger" onClick={()=>void submit()} disabled={busy}>{busy?'Abriendo…':'Abrir disputa formal'}</button></div>
   </>)}
   {notice&&<div className="ugo-dispute-note info">{notice}</div>}<footer>UGO conserva chat, estados, pagos y evidencias del momento de apertura. La IA puede ordenar la evidencia, pero los casos graves y las decisiones financieras requieren revisión humana.</footer>
  </section></div>}
 </>
}
