import React,{useCallback,useEffect,useMemo,useState}from'react'
import{AuthScreen,LoadingScreen,useRoleSession,type Category}from'./shared'
import{ProviderApp}from'./ProviderApp'
import'./onboarding-steps.css'

const TERMS_VERSION='2026-09-07'
type Form={nombre:string;apellido:string;telefono:string;direccion:string;zona:string;ciudad:string;categoria:string;bio:string;experiencia:string;especialidades:string;idiomas:string;horarios:string;radio:string;tarifa:string;cpf:string;pixTipo:string;pixChave:string;lat:number|null;lng:number|null}
const empty:Form={nombre:'',apellido:'',telefono:'',direccion:'',zona:'',ciudad:'Florianópolis',categoria:'',bio:'',experiencia:'',especialidades:'',idiomas:'Português',horarios:'',radio:'15',tarifa:'120',cpf:'',pixTipo:'cpf',pixChave:'',lat:null,lng:null}

export function ProviderFirstRunOnboarding(){
 const auth=useRoleSession('provider'),{supabase,session,profile}=auth
 const[categories,setCategories]=useState<Category[]>([]),[loading,setLoading]=useState(true),[complete,setComplete]=useState(false),[status,setStatus]=useState('registrado'),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[terms,setTerms]=useState(false),[msg,setMsg]=useState(''),[form,setForm]=useState<Form>(empty),[identity,setIdentity]=useState<string|null>(null),[photo,setPhoto]=useState(profile?.foto_url||'')
 const load=useCallback(async()=>{if(!session||!profile){setLoading(false);return}setLoading(true);try{const[{data:u,error:ue},{data:p,error:pe},{data:c},{data:d}]=await Promise.all([supabase.from('usuarios').select('nombre,apellido,endereco,zona,lat,lng,foto_url').eq('id',session.user.id).single(),supabase.from('perfiles_proveedor').select('*').eq('usuario_id',session.user.id).maybeSingle(),supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.from('documentos').select('id,tipo,estado,url_storage').eq('usuario_id',session.user.id).eq('tipo','identidad_frente').order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(ue)throw ue;if(pe)throw pe;let pp=p;if(!pp){const{data:newP,error}=await supabase.from('perfiles_proveedor').insert({usuario_id:session.user.id,estado_verificacion:'registrado',onboarding_paso:1}).select('*').single();if(error)throw error;pp=newP}setCategories((c||[])as Category[]);setStatus(pp.estado_verificacion||'registrado');setComplete(Boolean(pp.onboarding_completo_at)&&pp.estado_verificacion==='verificado');setTerms(Boolean(pp.termos_aceitos_at));setIdentity(d?.url_storage||null);setPhoto(u?.foto_url||'');setStep(Math.min(5,Math.max(1,Math.ceil(Number(pp.onboarding_paso||1)/3))));setForm({nombre:u?.nombre||profile.nombre||'',apellido:u?.apellido||'',telefono:pp.telefono_profesional||'',direccion:u?.endereco||'',zona:u?.zona||'',ciudad:pp.ciudad_base||'Florianópolis',categoria:pp.categoria_principal_id||'',bio:pp.bio||'',experiencia:pp.experiencia_anos==null?'':String(pp.experiencia_anos),especialidades:pp.especialidades||'',idiomas:pp.idiomas||'Português',horarios:pp.disponibilidad_horaria||'',radio:String(pp.zona_radio_km||15),tarifa:String(pp.tarifa_base||120),cpf:pp.cpf||'',pixTipo:pp.pix_tipo||'cpf',pixChave:pp.pix_chave||'',lat:u?.lat??null,lng:u?.lng??null})}catch(e:any){setMsg(e.message||'No se pudo cargar tu ficha profesional.')}finally{setLoading(false)}},[profile,session,supabase])
 useEffect(()=>{load()},[load])
 const category=useMemo(()=>categories.find(c=>c.id===form.categoria)||null,[categories,form.categoria])
 function validate(s:number){if(s===1){if(!form.nombre.trim())throw new Error('Ingresá tu nombre.');if(form.telefono.replace(/\D/g,'').length<8)throw new Error('Ingresá un WhatsApp válido.')}if(s===2){if(!form.ciudad.trim())throw new Error('Ingresá tu ciudad.');if(!form.zona.trim())throw new Error('Indicá tu zona o barrio.')}if(s===3){if(!form.categoria)throw new Error('Elegí una categoría principal.');if(Number(form.tarifa)<=0)throw new Error('Ingresá una tarifa válida.')}if(s===4){if(!form.cpf.trim())throw new Error('Ingresá tu CPF.');if(!form.pixChave.trim())throw new Error('Ingresá tu clave PIX.');if(!identity)throw new Error('Subí un documento de identidad.')}}
 async function saveProgress(nextStep:number){if(!session)return;const{error:ue}=await supabase.from('usuarios').update({nombre:form.nombre.trim(),apellido:form.apellido.trim()||null,endereco:form.direccion.trim()||null,zona:form.zona.trim()||null,lat:form.lat,lng:form.lng,pais:'BR'}).eq('id',session.user.id);if(ue)throw ue;const{error:pe}=await supabase.from('perfiles_proveedor').update({telefono_profesional:form.telefono.trim()||null,ciudad_base:form.ciudad.trim()||null,categoria_principal_id:form.categoria||null,bio:form.bio.trim()||null,experiencia_anos:form.experiencia?Number(form.experiencia):null,especialidades:form.especialidades.trim()||null,idiomas:form.idiomas.trim()||null,disponibilidad_horaria:form.horarios.trim()||null,zona_radio_km:Number(form.radio||15),tarifa_base:Number(form.tarifa||120),cpf:form.cpf.trim()||null,pix_tipo:form.pixTipo,pix_chave:form.pixChave.trim()||null,onboarding_paso:Math.min(13,nextStep*3)}).eq('usuario_id',session.user.id);if(pe)throw pe}
 async function next(){setBusy(true);setMsg('');try{validate(step);await saveProgress(step+1);setStep(v=>Math.min(5,v+1))}catch(e:any){setMsg(e.message||'No se pudo guardar este paso.')}finally{setBusy(false)}}
 function locate(){if(!navigator.geolocation)return setMsg('Este dispositivo no ofrece ubicación.');setBusy(true);navigator.geolocation.getCurrentPosition(pos=>{setForm(v=>({...v,lat:pos.coords.latitude,lng:pos.coords.longitude}));setBusy(false);setMsg('Ubicación capturada para tu zona de trabajo.')},()=>{setBusy(false);setMsg('No se pudo obtener la ubicación. Podés continuar con ciudad y zona.')},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
 async function uploadIdentity(file:File){if(!session)return;setBusy(true);setMsg('');try{const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${session.user.id}/identidad_frente-${Date.now()}.${ext}`;const{error:up}=await supabase.storage.from('provider-kyc').upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;const{data:current}=await supabase.from('documentos').select('id').eq('usuario_id',session.user.id).eq('tipo','identidad_frente').order('created_at',{ascending:false}).limit(1).maybeSingle();if(current?.id){const{error}=await supabase.from('documentos').update({url_storage:path,estado:'pendiente',notas_rechazo:null}).eq('id',current.id);if(error)throw error}else{const{error}=await supabase.from('documentos').insert({usuario_id:session.user.id,tipo:'identidad_frente',url_storage:path,descripcion:'Documento de identidad',estado:'pendiente'});if(error)throw error}setIdentity(path);setMsg('Documento cargado correctamente.')}catch(e:any){setMsg(e.message||'No se pudo cargar el documento.')}finally{setBusy(false)}}
 async function uploadPhoto(file:File){if(!session)return;setBusy(true);try{const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${session.user.id}/perfil.${ext}`;const{error}=await supabase.storage.from('provider-public').upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;const{data}=supabase.storage.from('provider-public').getPublicUrl(path);const{error:ue}=await supabase.from('usuarios').update({foto_url:data.publicUrl}).eq('id',session.user.id);if(ue)throw ue;setPhoto(data.publicUrl);setMsg('Foto profesional actualizada.')}catch(e:any){setMsg(e.message||'No se pudo subir la foto.')}finally{setBusy(false)}}
 async function finish(){if(!session)return;setBusy(true);setMsg('');try{validate(1);validate(2);validate(3);validate(4);if(!terms)throw new Error('Aceptá los términos para enviar tu registro.');await saveProgress(5);const now=new Date().toISOString();const{error}=await supabase.from('perfiles_proveedor').update({termos_aceitos_at:now,termos_versao:TERMS_VERSION,onboarding_completo_at:now,onboarding_paso:13,estado_verificacion:'pendiente',online:false,disponible:false}).eq('usuario_id',session.user.id);if(error)throw error;setStatus('pendiente')}catch(e:any){setMsg(e.message||'No se pudo enviar el registro.')}finally{setBusy(false)}}
 if(auth.loading||loading)return<LoadingScreen label="Preparando tu registro profesional…"/>
 if(!session||!profile)return<AuthScreen role="provider" supabase={supabase} error={auth.error} onError={auth.setError}/>
 if(status==='verificado'||complete)return<ProviderApp/>
 if(status==='suspendido')return<main className="ugo-onboard"><section className="ugo-onboard-card ugo-onboard-review"><div className="icon">⛔</div><h1>Cuenta suspendida</h1><p>Tu acceso como proveedor está suspendido. Contactá a UGO para revisión.</p><button className="ugo-onboard-signout" onClick={auth.signOut}>Cerrar sesión</button></section></main>
 if(status==='pendiente')return<main className="ugo-onboard"><section className="ugo-onboard-card ugo-onboard-review"><div className="icon">⏳</div><h1>Registro en revisión</h1><p>Recibimos tu ficha y documento. El Panel Admin debe verificar tu cuenta antes de que puedas aparecer Online y recibir trabajos.</p><button className="ugo-onboard-signout" onClick={auth.signOut}>Cerrar sesión</button></section></main>
 return <main className="ugo-onboard"><section className="ugo-onboard-card"><div className="ugo-onboard-brand"><div><small>UGO · PROVEEDOR</small><h1>Tu ficha profesional</h1><p>Completá un paso por vez. Guardamos el progreso automáticamente.</p></div><span className="ugo-onboard-role">🛠️</span></div><div className="ugo-onboard-progress" style={{'--steps':5} as React.CSSProperties}>{[1,2,3,4,5].map(n=><i key={n} className={n<=step?'on':''}/>)}</div><div className="ugo-onboard-step">PASO {step} DE 5</div>
 {step===1&&<><h2 className="ugo-onboard-title">Datos personales y contacto</h2><div className="ugo-onboard-fields"><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Nombre<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label className="ugo-onboard-field">Apellido<input value={form.apellido} onChange={e=>setForm({...form,apellido:e.target.value})}/></label></div><label className="ugo-onboard-field">Email<input className="ugo-onboard-readonly" value={session.user.email||''} readOnly/></label><label className="ugo-onboard-field">WhatsApp / teléfono<input placeholder="+55…" value={form.telefono} onChange={e=>setForm({...form,telefono:e.target.value})}/></label><div className="ugo-onboard-photo"><div className="ugo-onboard-avatar">{photo?<img src={photo} alt="" style={{width:'100%',height:'100%',borderRadius:'50%',objectFit:'cover'}}/>:'P'}</div><label className="ugo-onboard-upload">📷 Foto profesional<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadPhoto(e.target.files[0])}/></label></div></div></>}
 {step===2&&<><h2 className="ugo-onboard-title">Ubicación y zona de trabajo</h2><div className="ugo-onboard-fields"><label className="ugo-onboard-field">Dirección<input value={form.direccion} onChange={e=>setForm({...form,direccion:e.target.value})}/></label><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Zona / barrio<input value={form.zona} onChange={e=>setForm({...form,zona:e.target.value})}/></label><label className="ugo-onboard-field">Ciudad<input value={form.ciudad} onChange={e=>setForm({...form,ciudad:e.target.value})}/></label></div><button type="button" className="ugo-onboard-location" onClick={locate}>{form.lat!=null?'📍 Ubicación capturada':'📍 Usar mi ubicación actual'}</button></div></>}
 {step===3&&<><h2 className="ugo-onboard-title">Tu trabajo</h2><div className="ugo-onboard-fields"><label className="ugo-onboard-field">Categoría principal<select value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}><option value="">Elegir…</option>{categories.map(c=><option key={c.id} value={c.id}>{c.emoji} {c.nombre}</option>)}</select></label><label className="ugo-onboard-field">Especialidades<input value={form.especialidades} onChange={e=>setForm({...form,especialidades:e.target.value})} placeholder="Ej: poda, césped, mantenimiento"/></label><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Experiencia (años)<input type="number" min="0" value={form.experiencia} onChange={e=>setForm({...form,experiencia:e.target.value})}/></label><label className="ugo-onboard-field">Tarifa base R$/h<input type="number" min="1" value={form.tarifa} onChange={e=>setForm({...form,tarifa:e.target.value})}/></label></div><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Radio de trabajo (km)<input type="number" min="1" value={form.radio} onChange={e=>setForm({...form,radio:e.target.value})}/></label><label className="ugo-onboard-field">Idiomas<input value={form.idiomas} onChange={e=>setForm({...form,idiomas:e.target.value})}/></label></div><label className="ugo-onboard-field">Disponibilidad horaria<input value={form.horarios} onChange={e=>setForm({...form,horarios:e.target.value})}/></label><label className="ugo-onboard-field">Presentación / bio<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label></div></>}
 {step===4&&<><h2 className="ugo-onboard-title">Identidad y cobro</h2><div className="ugo-onboard-fields"><label className="ugo-onboard-field">CPF<input value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value})}/></label><div className="ugo-onboard-grid"><label className="ugo-onboard-field">Tipo de PIX<select value={form.pixTipo} onChange={e=>setForm({...form,pixTipo:e.target.value})}><option value="cpf">CPF</option><option value="email">Email</option><option value="telefone">Teléfono</option><option value="aleatoria">Clave aleatoria</option></select></label><label className="ugo-onboard-field">Clave PIX<input value={form.pixChave} onChange={e=>setForm({...form,pixChave:e.target.value})}/></label></div><label className="ugo-onboard-upload">{identity?'✅ Documento cargado':'🪪 Subir documento de identidad'}<input hidden type="file" accept="image/*,.pdf" onChange={e=>e.target.files?.[0]&&uploadIdentity(e.target.files[0])}/></label></div></>}
 {step===5&&<><h2 className="ugo-onboard-title">Revisá y enviá</h2><div className="ugo-onboard-summary"><span><b>{form.nombre} {form.apellido}</b></span><span>📞 {form.telefono}</span><span>📍 {[form.zona,form.ciudad].filter(Boolean).join(', ')}</span><span>🛠️ {category?.nombre||'Categoría sin definir'} · {form.experiencia||0} años</span><span>💰 R$ {form.tarifa}/h · PIX {form.pixTipo}</span><span>{identity?'✅ Identidad cargada':'❌ Falta identidad'}</span></div><label className="ugo-onboard-terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Acepto los términos de UGO, el tratamiento de mis datos profesionales y el proceso de verificación para recibir trabajos.</span></label></>}
 {msg&&<div className="ugo-onboard-message">{msg}</div>}<div className="ugo-onboard-actions">{step>1&&<button type="button" className="ugo-onboard-back" onClick={()=>{setMsg('');setStep(step-1)}}>Atrás</button>}{step<5?<button type="button" className="ugo-onboard-next" onClick={next} disabled={busy}>{busy?'Guardando…':'Guardar y continuar'}</button>:<button type="button" className="ugo-onboard-next" onClick={finish} disabled={busy}>{busy?'Enviando…':'Enviar a verificación'}</button>}</div><button type="button" className="ugo-onboard-signout" onClick={auth.signOut}>Cerrar sesión</button></section></main>
}
