import React,{useCallback,useEffect,useMemo,useState}from'react'
import{getRoleSupabase}from'../lib/roleSupabase'
import'./provider-onboarding.css'

type P={usuario_id:string;estado_verificacion:string;motivo_rechazo:string|null;onboarding_paso:number|null;telefono_profesional:string|null;ciudad_base:string|null;categoria_principal_id:string|null;cpf:string|null;pix_chave:string|null;pix_tipo:string|null;termos_aceitos_at:string|null;termos_versao:string|null;bio:string|null;experiencia_anos:number|null;especialidades:string|null;idiomas:string|null;disponibilidad_horaria:string|null;zona_radio_km:number|null}
type U={id:string;nombre:string;apellido:string|null;foto_url:string|null;pais:string|null;zona:string|null;endereco:string|null;tipo:string}
type Cat={id:string;nombre:string;emoji:string}
type Sub={id:string;categoria_id:string;nombre:string}
type Doc={id:string;tipo:string;estado:string;notas_rechazo:string|null;url_storage:string}
type ProviderOnboardingGateProps={onVerified?:()=>void|Promise<void>}
const TERMS_VERSION='2026-09-04'
const STEPS=[{name:'Cuenta',icon:'👤',title:'Tus datos',copy:'Lo básico para identificarte y contactarte.'},{name:'Servicio',icon:'🛠️',title:'¿Qué trabajos hacés?',copy:'Elegí tu rubro, especialidades y zona de trabajo.'},{name:'Perfil',icon:'✨',title:'Mostrá quién sos',copy:'Completá una presentación breve para generar confianza.'},{name:'Documentos',icon:'🪪',title:'Verificá tu identidad',copy:'Tus archivos son privados y sólo UGO puede revisarlos.'},{name:'Cobro',icon:'◆',title:'Dónde querés cobrar',copy:'Configurá tu chave PIX para recibir tus pagos.'},{name:'Revisión',icon:'✓',title:'Revisá y enviá',copy:'Confirmá los datos antes de solicitar la aprobación.'}]

export function ProviderOnboardingGate({onVerified}:ProviderOnboardingGateProps){
 const sb=useMemo(()=>getRoleSupabase('provider'),[])
 const[session,setSession]=useState<any>(null),[user,setUser]=useState<U|null>(null),[p,setP]=useState<P|null>(null),[cats,setCats]=useState<Cat[]>([]),[subs,setSubs]=useState<Sub[]>([]),[selectedSubs,setSelectedSubs]=useState<string[]>([]),[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[terms,setTerms]=useState(false),[step,setStep]=useState(1)
 const[form,setForm]=useState({nombre:'',apellido:'',telefono:'',endereco:'',zona:'',ciudad:'Florianópolis',cpf:'',pix_tipo:'cpf',pix_chave:'',bio:'',experiencia:'',especialidades:'',idiomas:'Português',horarios:'',radio:'15',categoria:''})
 const load=useCallback(async(s:any)=>{if(!s){setSession(null);setLoading(false);return}setSession(s);const[{data:u,error:ue},{data:pp,error:pe},{data:c},{data:d}]=await Promise.all([sb.from('usuarios').select('id,nombre,apellido,foto_url,pais,zona,endereco,tipo').eq('id',s.user.id).maybeSingle(),sb.from('perfiles_proveedor').select('usuario_id,estado_verificacion,motivo_rechazo,onboarding_paso,telefono_profesional,ciudad_base,categoria_principal_id,cpf,pix_chave,pix_tipo,termos_aceitos_at,termos_versao,bio,experiencia_anos,especialidades,idiomas,disponibilidad_horaria,zona_radio_km').eq('usuario_id',s.user.id).maybeSingle(),sb.from('categorias').select('id,nombre,emoji').eq('activa',true).order('nombre'),sb.from('documentos').select('id,tipo,estado,notas_rechazo,url_storage').eq('usuario_id',s.user.id)]);if(ue)throw ue;if(pe)throw pe;if(!u){setMsg('No se encontró el perfil UGO asociado a esta cuenta.');setLoading(false);return}if(u.tipo!=='proveedor'){setMsg('Esta cuenta no está registrada como proveedor.');setLoading(false);return}let prof=pp as P|null;if(!prof){const{data:newP,error}=await sb.from('perfiles_proveedor').insert({usuario_id:s.user.id,estado_verificacion:'registrado',onboarding_paso:1}).select('*').single();if(error)throw error;prof=newP as P}setUser(u as U);setP(prof);setCats((c||[])as Cat[]);setDocs((d||[])as Doc[]);setTerms(Boolean(prof?.termos_aceitos_at));setForm({nombre:u.nombre||'',apellido:u.apellido||'',telefono:prof?.telefono_profesional||'',endereco:u.endereco||'',zona:u.zona||'',ciudad:prof?.ciudad_base||'Florianópolis',cpf:prof?.cpf||'',pix_tipo:prof?.pix_tipo||'cpf',pix_chave:prof?.pix_chave||'',bio:prof?.bio||'',experiencia:prof?.experiencia_anos==null?'':String(prof.experiencia_anos),especialidades:prof?.especialidades||'',idiomas:prof?.idiomas||'Português',horarios:prof?.disponibilidad_horaria||'',radio:String(prof?.zona_radio_km||15),categoria:prof?.categoria_principal_id||''});if(prof?.categoria_principal_id){const{data:srows}=await sb.from('subcategorias').select('id,categoria_id,nombre').eq('categoria_id',prof.categoria_principal_id).eq('activa',true).order('nombre');setSubs((srows||[])as Sub[])}const{data:ps}=await sb.from('proveedor_subcategorias').select('subcategoria_id').eq('proveedor_id',s.user.id).eq('activa',true);setSelectedSubs((ps||[]).map((x:any)=>x.subcategoria_id));setLoading(false)},[sb])
 useEffect(()=>{sb.auth.getSession().then(({data})=>load(data.session).catch(e=>{setMsg(e.message);setLoading(false)}));const{data:l}=sb.auth.onAuthStateChange((_e,s)=>load(s).catch(e=>setMsg(e.message)));return()=>l.subscription.unsubscribe()},[load,sb])
 useEffect(()=>{if(!session?.user?.id)return;const ch=sb.channel(`provider-onboarding-${session.user.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'perfiles_proveedor',filter:`usuario_id=eq.${session.user.id}`},()=>load(session).catch(e=>setMsg(e instanceof Error?e.message:'No se pudo actualizar la verificación.'))).subscribe();return()=>{sb.removeChannel(ch)}},[load,sb,session])
 useEffect(()=>{if(p?.estado_verificacion==='verificado'&&onVerified)void onVerified()},[onVerified,p?.estado_verificacion])
 useEffect(()=>{if(!form.categoria){setSubs([]);return}sb.from('subcategorias').select('id,categoria_id,nombre').eq('categoria_id',form.categoria).eq('activa',true).order('nombre').then(({data})=>setSubs((data||[])as Sub[]))},[form.categoria,sb])
 const doc=(t:string)=>docs.find(d=>d.tipo===t&&d.estado!=='rechazado')||docs.find(d=>d.tipo===t)
 const categoryName=cats.find(c=>c.id===form.categoria)?.nombre||'Sin elegir'
 async function uploadDoc(type:string,file:File){if(!session)return;setBusy(true);setMsg('');try{const ext=(file.name.split('.').pop()||'bin').toLowerCase(),path=`${session.user.id}/${type}-${Date.now()}.${ext}`;const{error:upErr}=await sb.storage.from('provider-kyc').upload(path,file,{upsert:false,contentType:file.type});if(upErr)throw upErr;const current=docs.find(d=>d.tipo===type&&d.estado!=='rechazado');if(current){const{error}=await sb.from('documentos').update({url_storage:path,estado:'pendiente',notas_rechazo:null,updated_at:new Date().toISOString(),version:2}).eq('id',current.id);if(error)throw error}else{const{error}=await sb.from('documentos').insert({usuario_id:session.user.id,tipo:type,url_storage:path,descripcion:type.replaceAll('_',' '),estado:'pendiente'});if(error)throw error}setMsg('Documento cargado correctamente.');await load(session)}catch(e:any){setMsg(e.message||'No se pudo cargar el documento.')}finally{setBusy(false)}}
 async function uploadPhoto(file:File){if(!session)return;setBusy(true);setMsg('');try{const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${session.user.id}/perfil.${ext}`;const{error}=await sb.storage.from('provider-public').upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;const{data}=sb.storage.from('provider-public').getPublicUrl(path);const{error:ue}=await sb.from('usuarios').update({foto_url:data.publicUrl}).eq('id',session.user.id);if(ue)throw ue;setMsg('Foto de perfil actualizada.');await load(session)}catch(e:any){setMsg(e.message||'No se pudo cargar la foto.')}finally{setBusy(false)}}
 async function save(submit=false){if(!session||!p)return;setBusy(true);setMsg('');try{if(submit){if(!form.nombre.trim()||!form.telefono.trim()||!form.ciudad.trim()||!form.categoria)throw new Error('Completá nombre, teléfono, ciudad y categoría.');if(!form.cpf.trim()||!form.pix_chave.trim())throw new Error('Completá CPF y datos PIX.');if(!doc('identidad_frente')||doc('identidad_frente')?.estado==='rechazado')throw new Error('Subí un documento de identidad válido.');if(!terms)throw new Error('Tenés que aceptar los términos para enviar la revisión.')}const now=new Date().toISOString();const{error:ue}=await sb.from('usuarios').update({nombre:form.nombre.trim()||user?.nombre||'',apellido:form.apellido.trim()||null,endereco:form.endereco.trim()||null,zona:form.zona.trim()||null,pais:'BR'}).eq('id',session.user.id);if(ue)throw ue;const payload:any={telefono_profesional:form.telefono.trim()||null,ciudad_base:form.ciudad.trim()||null,categoria_principal_id:form.categoria||null,bio:form.bio.trim()||null,experiencia_anos:form.experiencia?Number(form.experiencia):null,especialidades:form.especialidades.trim()||null,idiomas:form.idiomas.trim()||null,disponibilidad_horaria:form.horarios.trim()||null,zona_radio_km:Number(form.radio||15),cpf:form.cpf.trim()||null,pix_tipo:form.pix_tipo,pix_chave:form.pix_chave.trim()||null,onboarding_paso:submit?13:Math.max(Number(p.onboarding_paso||0),step)};if(terms){payload.termos_aceitos_at=p.termos_aceitos_at||now;payload.termos_versao=TERMS_VERSION}if(submit){payload.estado_verificacion='pendiente';payload.online=false;payload.disponible=false}const{error:pe}=await sb.from('perfiles_proveedor').update(payload).eq('usuario_id',session.user.id);if(pe)throw pe;await sb.from('proveedor_subcategorias').delete().eq('proveedor_id',session.user.id);if(selectedSubs.length){const{error:se}=await sb.from('proveedor_subcategorias').insert(selectedSubs.map(id=>({proveedor_id:session.user.id,subcategoria_id:id,activa:true})));if(se)throw se}setMsg(submit?'Registro enviado. Quedó pendiente de revisión por UGO.':'Progreso guardado.');await load(session)}catch(e:any){setMsg(e.message||'No se pudo guardar.')}finally{setBusy(false)}}
 function validateStep(){setMsg('');if(step===1){if(!form.nombre.trim())return setMsg('Ingresá tu nombre.'),false;if(!form.telefono.trim())return setMsg('Ingresá tu teléfono o WhatsApp.'),false;if(!form.ciudad.trim())return setMsg('Ingresá tu ciudad.'),false}if(step===2&&!form.categoria)return setMsg('Elegí tu categoría principal.'),false;if(step===4){if(!form.cpf.trim())return setMsg('Ingresá tu CPF.'),false;if(!doc('identidad_frente')||doc('identidad_frente')?.estado==='rechazado')return setMsg('Cargá el frente de tu documento de identidad.'),false}if(step===5&&!form.pix_chave.trim())return setMsg('Ingresá tu chave PIX.'),false;return true}
 function next(){if(!validateStep())return;setStep(v=>Math.min(6,v+1));window.scrollTo({top:0,behavior:'smooth'})}
 function back(){setMsg('');setStep(v=>Math.max(1,v-1));window.scrollTo({top:0,behavior:'smooth'})}
 const upload=(type:string,title:string,required=false)=>{const d=doc(type),state=d?.estado||'Sin cargar';return <label className="ugo-provider-upload"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={e=>e.target.files?.[0]&&uploadDoc(type,e.target.files[0])}/><span className="ugo-provider-upload-copy"><b>{title}{required?' *':''}</b><span>{d?.notas_rechazo||'JPG, PNG, WEBP o PDF'}</span></span><span className={`ugo-provider-upload-badge ${state}`}>{state}</span></label>}
 if(loading)return <div className="mvp-loading"><p>Preparando registro profesional…</p></div>
 if(!session)return <div className="ugo-provider-state"><h2>Sesión de proveedor requerida</h2><p>Volvé al acceso de UGO Pro para iniciar sesión.</p><button className="primary" onClick={()=>window.location.replace(`${window.location.pathname}?app=provider`)}>Volver al acceso</button></div>
 if(!p||!user)return <div className="ugo-provider-state"><h2>Registro profesional</h2><p>{msg||'No se pudo cargar el perfil.'}</p><button className="secondary" onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
 if(p.estado_verificacion==='verificado')return <div className="mvp-loading"><p>Activando tu espacio UGO Pro…</p></div>
 if(p.estado_verificacion==='suspendido')return <div className="ugo-provider-state"><h2>Cuenta profesional suspendida</h2><p>Tu acceso operativo está suspendido. Contactá a UGO para revisión.</p><button className="secondary" onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
 if(p.estado_verificacion==='pendiente')return <div className="ugo-provider-state"><div style={{fontSize:42}}>⏳</div><h1>Registro en revisión</h1><p>Recibimos tus datos y documentos. UGO debe aprobarlos antes de que puedas aparecer como proveedor activo y recibir trabajos.</p>{msg&&<p>{msg}</p>}<div className="ugo-provider-state-actions"><button className="secondary" onClick={()=>{setP({...p,estado_verificacion:'registrado'});setStep(1)}}>Revisar mis datos</button><button className="secondary" onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div></div>
 const rejected=p.estado_verificacion==='rechazado',meta=STEPS[step-1]
 return <main className="ugo-provider-onboarding"><div className="ugo-provider-onboarding-card"><header className="ugo-provider-onboarding-head"><div className="ugo-provider-brand"><small>U.G.O. · PROVEEDOR</small><span>🛠️</span></div><h1>Registro profesional</h1><p>Configurá tu perfil paso a paso. Podés guardar y seguir después.</p></header>{rejected&&<div className="ugo-provider-rejected"><b>Revisión rechazada.</b><div>{p.motivo_rechazo||'Revisá los datos o documentos señalados y volvé a enviarlos.'}</div></div>}<div className="ugo-provider-progress"><div className="ugo-provider-progress-top"><b>Paso {step} de 6 · {meta.name}</b><span>{Math.round(step/6*100)}% completo</span></div><div className="ugo-provider-progress-track"><i style={{width:`${step/6*100}%`}}/></div><div className="ugo-provider-steps">{STEPS.map((s,i)=><button type="button" key={s.name} data-step={i+1} className={i+1===step?'active':i+1<step?'done':''} onClick={()=>i+1<step&&setStep(i+1)}>{s.name}</button>)}</div></div><section className="ugo-provider-step"><div className="ugo-provider-step-title"><span className="ugo-provider-step-icon">{meta.icon}</span><div><h2>{meta.title}</h2><p>{meta.copy}</p></div></div>
 {step===1&&<><div className="ugo-provider-grid"><label className="ugo-provider-field">Nombre<input autoComplete="given-name" value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label className="ugo-provider-field">Apellido<input autoComplete="family-name" value={form.apellido} onChange={e=>setForm({...form,apellido:e.target.value})}/></label></div><label className="ugo-provider-field">Email de acceso<input value={session.user.email||''} readOnly/></label><label className="ugo-provider-field">Teléfono / WhatsApp<input inputMode="tel" value={form.telefono} onChange={e=>setForm({...form,telefono:e.target.value})} placeholder="+55…"/></label><label className="ugo-provider-field">Dirección<input autoComplete="street-address" value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})} placeholder="Calle y número"/></label><div className="ugo-provider-grid"><label className="ugo-provider-field">Zona / barrio<input value={form.zona} onChange={e=>setForm({...form,zona:e.target.value})}/></label><label className="ugo-provider-field">Ciudad<input value={form.ciudad} onChange={e=>setForm({...form,ciudad:e.target.value})}/></label></div></>}
 {step===2&&<><label className="ugo-provider-field">Categoría principal<select value={form.categoria} onChange={e=>{setForm({...form,categoria:e.target.value});setSelectedSubs([])}}><option value="">Elegir categoría…</option>{cats.map(c=><option key={c.id} value={c.id}>{c.emoji} {c.nombre}</option>)}</select></label>{subs.length>0&&<><label className="ugo-provider-field">Servicios que realizás</label><div className="ugo-provider-subcats">{subs.map(s=><button type="button" key={s.id} className={selectedSubs.includes(s.id)?'selected':''} onClick={()=>setSelectedSubs(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])}>{s.nombre}</button>)}</div></>}<label className="ugo-provider-field">Especialidades<input value={form.especialidades} onChange={e=>setForm({...form,especialidades:e.target.value})} placeholder="Ej: instalaciones, mantenimiento…"/></label><div className="ugo-provider-grid"><label className="ugo-provider-field">Experiencia (años)<input type="number" min="0" inputMode="numeric" value={form.experiencia} onChange={e=>setForm({...form,experiencia:e.target.value})}/></label><label className="ugo-provider-field">Radio de trabajo (km)<input type="number" min="1" inputMode="numeric" value={form.radio} onChange={e=>setForm({...form,radio:e.target.value})}/></label></div></>}
 {step===3&&<><div className="ugo-provider-profile-photo">{user.foto_url?<img src={user.foto_url} alt="Foto de perfil"/>:<div className="ugo-provider-avatar-placeholder">👤</div>}<label className="ugo-provider-upload" style={{flex:1}}><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>e.target.files?.[0]&&uploadPhoto(e.target.files[0])}/><span className="ugo-provider-upload-copy"><b>Foto de perfil</b><span>Una foto clara genera más confianza</span></span><span className="ugo-provider-upload-badge">{user.foto_url?'Cambiar':'Subir'}</span></label></div><label className="ugo-provider-field">Bio / presentación<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} placeholder="Contá brevemente cómo trabajás y qué te diferencia."/></label><div className="ugo-provider-grid"><label className="ugo-provider-field">Idiomas<input value={form.idiomas} onChange={e=>setForm({...form,idiomas:e.target.value})}/></label><label className="ugo-provider-field">Disponibilidad<input value={form.horarios} onChange={e=>setForm({...form,horarios:e.target.value})} placeholder="Ej: Lun–Sáb, 8–18 h"/></label></div></>}
 {step===4&&<><div className="ugo-provider-privacy"><b>🔒 Documentación privada</b><br/>RG, CNH o pasaporte. La selfie se usa sólo para revisión manual; UGO no realiza reconocimiento facial automático en este flujo.</div>{upload('identidad_frente','Documento de identidad · frente',true)}{upload('identidad_dorso','Documento · dorso')}{upload('selfie','Selfie de verificación')}{upload('comprobante_domicilio','Comprobante de domicilio')}<label className="ugo-provider-field">CPF<input inputMode="numeric" value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value})} placeholder="000.000.000-00"/></label></>}
 {step===5&&<><div className="ugo-provider-privacy"><b>💸 Datos de cobro</b><br/>UGO usa esta información para identificar dónde recibirás tus pagos por servicios.</div><div className="ugo-provider-grid"><label className="ugo-provider-field">Tipo de chave<select value={form.pix_tipo} onChange={e=>setForm({...form,pix_tipo:e.target.value})}><option value="cpf">CPF</option><option value="email">Email</option><option value="telefone">Teléfono</option><option value="aleatoria">Aleatoria</option></select></label><label className="ugo-provider-field">Chave PIX<input value={form.pix_chave} onChange={e=>setForm({...form,pix_chave:e.target.value})} placeholder="Ingresá tu chave"/></label></div></>}
 {step===6&&<><div className="ugo-provider-review"><div className="ugo-provider-review-row"><span>Profesional</span><b>{form.nombre} {form.apellido}</b></div><div className="ugo-provider-review-row"><span>Servicio principal</span><b>{categoryName}</b></div><div className="ugo-provider-review-row"><span>Zona</span><b>{form.zona||form.ciudad}</b></div><div className="ugo-provider-review-row"><span>Experiencia</span><b>{form.experiencia?`${form.experiencia} años`:'No indicada'}</b></div><div className="ugo-provider-review-row"><span>Documento</span><b>{doc('identidad_frente')?.estado||'Sin cargar'}</b></div><div className="ugo-provider-review-row"><span>PIX</span><b>{form.pix_chave?'Configurado':'Pendiente'}</b></div></div><label className="ugo-provider-terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Acepto los términos de uso, política de privacidad y tratamiento de datos necesarios para validar mi registro profesional. Versión {TERMS_VERSION}.</span></label><div className="ugo-provider-privacy">Al enviar, tu estado pasa a <b>Pendiente de revisión</b>. Podrás recibir trabajos cuando UGO apruebe el registro.</div></>}
 </section>{msg&&<div className={`ugo-provider-message ${/no se|ingresá|elegí|completá|cargá|tenés/i.test(msg)?'error':''}`} role="status">{msg}</div>}<footer className="ugo-provider-actions">{step>1?<button type="button" className="ugo-provider-back" disabled={busy} onClick={back}>← Atrás</button>:<button type="button" className="ugo-provider-back" disabled={busy} onClick={()=>sb.auth.signOut()}>Salir</button>}<button type="button" className="ugo-provider-save" disabled={busy} onClick={()=>save(false)}>{busy?'Guardando…':'Guardar'}</button>{step<6?<button type="button" className="ugo-provider-next" disabled={busy} onClick={next}>Continuar →</button>:<button type="button" className="ugo-provider-submit" disabled={busy||!terms} onClick={()=>save(true)}>{busy?'Enviando…':'Enviar para revisión →'}</button>}</footer></div></main>
}
