import React,{useCallback,useEffect,useState}from'react'
import type{RealtimeChannel}from'@supabase/supabase-js'
import{AppHeader,AuthScreen,LoadingScreen,PROVIDER_ACTIVE_STATES,StateTimeline,STATUS_LABELS,money,timeAgo,useRoleSession,type Category,type Notice,type Offer,type Payment,type ProviderProfile,type Service}from'./shared'
import{VoiceHugoDock}from'./VoiceHugoDock'
export function ProviderApp(){const auth=useRoleSession('provider'),{supabase,session,profile}=auth;const[categories,setCategories]=useState<Category[]>([]),[provider,setProvider]=useState<ProviderProfile|null>(null),[offers,setOffers]=useState<Offer[]>([]),[service,setService]=useState<Service|null>(null),[payments,setPayments]=useState<Payment[]>([]),[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(false)
 const loadData=useCallback(async()=>{if(!session)return;const[{data:c},{data:p},{data:o},{data:s},{data:pay}]=await Promise.all([supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.from('perfiles_proveedor').select('*').eq('usuario_id',session.user.id).maybeSingle(),supabase.from('ofertas_servicio').select('*,servicio:servicios(*,categoria:categorias(nombre,emoji),cliente:usuarios!servicios_cliente_id_fkey(nombre))').eq('proveedor_id',session.user.id).eq('estado','pendiente').order('created_at',{ascending:false}),supabase.from('servicios').select('*,categoria:categorias(nombre,emoji),cliente:usuarios!servicios_cliente_id_fkey(nombre)').eq('proveedor_id',session.user.id).in('estado',PROVIDER_ACTIVE_STATES).order('created_at',{ascending:false}).limit(1),supabase.from('pagos').select('*').eq('proveedor_id',session.user.id).order('created_at',{ascending:false})]);setCategories((c||[])as Category[]);setProvider((p as ProviderProfile|null)||null);setOffers((o||[])as Offer[]);setService(((s||[])[0]as Service|undefined)||null);setPayments((pay||[])as Payment[])},[session,supabase])
 useEffect(()=>{loadData().catch((e:Error)=>setNotice({type:'error',text:e.message}))},[loadData]);useEffect(()=>{if(!session)return;const ch:RealtimeChannel=supabase.channel(`provider-${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'ofertas_servicio',filter:`proveedor_id=eq.${session.user.id}`},loadData).on('postgres_changes',{event:'*',schema:'public',table:'servicios',filter:`proveedor_id=eq.${session.user.id}`},loadData).on('postgres_changes',{event:'*',schema:'public',table:'pagos',filter:`proveedor_id=eq.${session.user.id}`},loadData).subscribe();return()=>{supabase.removeChannel(ch)}},[loadData,session,supabase])
 async function update(next:Partial<ProviderProfile>){if(!session||!provider)return;setBusy(true);const{error}=await supabase.from('perfiles_proveedor').update(next).eq('usuario_id',session.user.id);setBusy(false);if(error)return setNotice({type:'error',text:error.message});await loadData()}
 async function offer(id:string,accept:boolean){setBusy(true);const{error}=await supabase.rpc(accept?'aceptar_oferta':'rechazar_oferta',{p_oferta_id:id});setBusy(false);if(error)return setNotice({type:'error',text:error.message});setNotice({type:accept?'ok':'info',text:accept?'Misión aceptada. La bóveda quedó retenida.':'Oferta rechazada.'});await loadData()}
 async function advance(state:'en_camino'|'en_progreso'|'esperando_aprobacion'){if(!service)return;setBusy(true);const{error}=await supabase.rpc('avanzar_servicio',{p_servicio_id:service.id,p_estado:state});setBusy(false);if(error)return setNotice({type:'error',text:error.message});await loadData()}
 if(auth.loading)return<LoadingScreen/>;if(!session||!profile)return<AuthScreen role="provider" supabase={supabase} error={auth.error} onError={auth.setError}/>;if(!provider)return<LoadingScreen label="Preparando perfil profesional…"/>;const released=payments.filter(p=>p.estado==='liberado').reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0),retained=payments.filter(p=>p.estado==='retenido').reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0);const action=service?.estado==='asignado'?{label:'Salir hacia el cliente',state:'en_camino' as const}:service?.estado==='en_camino'?{label:'Confirmar llegada e iniciar',state:'en_progreso' as const}:service?.estado==='en_progreso'?{label:'Finalizar y pedir aprobación',state:'esperando_aprobacion' as const}:null
 return <div className="mvp-shell"><AppHeader role="PROVEEDOR" name={profile.nombre} onLogout={auth.signOut}/><main className="mvp-layout"><section className="mvp-provider-top"><div className="mvp-availability-card"><div><span className={`mvp-live ${provider.disponible?'':'off'}`}><i/>{provider.disponible?'Disponible':'No disponible'}</span><h1>{provider.disponible?'Radar operativo':'Activá tu disponibilidad'}</h1><p>Las solicitudes compatibles aparecen en tiempo real.</p></div><button className={`mvp-switch ${provider.disponible?'on':''}`} onClick={()=>update({disponible:!provider.disponible,online:!provider.disponible})} disabled={busy}><span/></button></div><div className="mvp-earnings-card"><small>GANANCIAS LIBERADAS</small><strong>{money(released)}</strong><span>{money(retained)} retenidos</span></div></section>{notice&&<div className={`mvp-notice ${notice.type}`}>{notice.text}</div>}
 <section className="mvp-card mvp-provider-settings"><div className="mvp-card-title"><div><small>CONFIGURACIÓN</small><h2>Perfil operativo</h2></div><span>★ {Number(profile.karma||5).toFixed(2)}</span></div><div className="mvp-two-cols"><label>Categoría principal<select value={provider.categoria_principal_id||''} onChange={e=>update({categoria_principal_id:e.target.value||null})}><option value="">Todas / sin definir</option>{categories.map(c=><option key={c.id} value={c.id}>{c.emoji} {c.nombre}</option>)}</select></label><label>Tarifa base<input type="number" min="0" value={provider.tarifa_base} onChange={e=>setProvider({...provider,tarifa_base:Number(e.target.value)})} onBlur={()=>update({tarifa_base:provider.tarifa_base})}/></label></div></section>
 {service&&<section className="mvp-card"><div className="mvp-card-title"><div><small>MISIÓN ACTIVA</small><h2>{service.categoria?.emoji} {service.categoria?.nombre}</h2></div><span className={`mvp-status status-${service.estado}`}>{STATUS_LABELS[service.estado]}</span></div><StateTimeline state={service.estado}/><div className="mvp-mission-detail"><div><small>CLIENTE</small><strong>{service.cliente?.nombre||'Cliente U.G.O.'}</strong></div><div><small>DIRECCIÓN</small><strong>{service.direccion_cliente||'Coordinación por Hugo'}</strong></div><div><small>GANANCIA NETA</small><strong>{money(service.ganancia_proveedor,service.moneda)}</strong></div></div><p>{service.descripcion}</p>{action&&<button className="mvp-primary" onClick={()=>advance(action.state)} disabled={busy}>{action.label}</button>}{service.estado==='esperando_aprobacion'&&<div className="mvp-waiting">Esperando aprobación. El pago sigue protegido.</div>}</section>}
 {!service&&<section className="mvp-card"><div className="mvp-card-title"><div><small>OPORTUNIDADES</small><h2>{offers.length?`${offers.length} pedido${offers.length===1?'':'s'} disponible${offers.length===1?'':'s'}`:'Sin pedidos pendientes'}</h2></div><span>{offers.length}</span></div><div className="mvp-offer-list">{offers.map(o=><article key={o.id}><div className="mvp-offer-rank">#{o.ranking||'—'}</div><div><small>{o.servicio?.categoria?.emoji} {o.servicio?.categoria?.nombre}</small><h3>{o.servicio?.descripcion}</h3><p>{o.servicio?.direccion_cliente||'Dirección por confirmar'} · {timeAgo(o.servicio?.created_at||new Date().toISOString())}</p></div><div className="mvp-offer-money"><strong>{money(o.tarifa_ofrecida,o.servicio?.moneda)}</strong><span>neto {money(Number(o.tarifa_ofrecida||0)*.85,o.servicio?.moneda)}</span></div><div className="mvp-actions"><button className="mvp-secondary" onClick={()=>offer(o.id,false)} disabled={busy}>Rechazar</button><button className="mvp-primary" onClick={()=>offer(o.id,true)} disabled={busy}>Aceptar misión</button></div></article>)}{!offers.length&&<div className="mvp-empty"><div className="mvp-mini-orb"/><h3>Hugo está escuchando la red</h3><p>Creá un servicio en Cliente o activá disponibilidad.</p></div>}</div></section>}</main><VoiceHugoDock role="provider" accessToken={session.access_token} service={service} availableOffers={offers.length}/></div>
}
