import React,{useCallback,useEffect,useMemo,useRef,useState}from'react'
import{getRoleSupabase}from'../lib/roleSupabase'
import'./provider-demand-map.css'

type DemandRow={zona_lat:number;zona_lng:number;pedidos:number;urgentes:number;tarifa_promedio:number|null;ultimo_pedido:string}
type Category={id:string;nombre:string;emoji:string}
type DemandSummary={hours:number;categoryId:string|null;total:number;zones:Array<DemandRow&{label?:string}>;top:(DemandRow&{label?:string})|null;updatedAt:string}

async function coarseLabel(lat:number,lng:number){try{const r=await fetch(`https://photon.komoot.io/reverse?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lng)}`,{headers:{accept:'application/json'}});const d:any=await r.json().catch(()=>null);const p=d?.features?.[0]?.properties||{};return String(p.district||p.name||p.city||p.state||'Zona aproximada')}catch{return'Zona aproximada'}}
function intensity(value:number,max:number){if(max<=1)return'high';const ratio=value/max;return ratio>=.67?'high':ratio>=.34?'medium':'low'}
function color(level:'low'|'medium'|'high'){return level==='high'?'#ef4444':level==='medium'?'#f59e0b':'#22c55e'}

export function ProviderDemandMap(){
 const sb=useMemo(()=>getRoleSupabase('provider'),[]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[rows,setRows]=useState<Array<DemandRow&{label?:string}>>([]),[hours,setHours]=useState(24),[categoryId,setCategoryId]=useState<string>(''),[categories,setCategories]=useState<Category[]>([]),[mainCategory,setMainCategory]=useState<string>('')
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any[]>([])
 useEffect(()=>{const onOpen=()=>setOpen(true),onClose=()=>setOpen(false);window.addEventListener('ugo:open-provider-demand',onOpen);window.addEventListener('ugo:close-provider-demand',onClose);return()=>{window.removeEventListener('ugo:open-provider-demand',onOpen);window.removeEventListener('ugo:close-provider-demand',onClose)}},[])
 useEffect(()=>{sb.auth.getSession().then(async({data})=>{if(!data.session)return;const[{data:p},{data:c}]=await Promise.all([sb.from('perfiles_proveedor').select('categoria_principal_id').eq('usuario_id',data.session.user.id).maybeSingle(),sb.from('categorias').select('id,nombre,emoji').eq('activa',true).order('nombre')]);const main=String((p as any)?.categoria_principal_id||'');setMainCategory(main);setCategoryId(main);setCategories((c||[])as Category[])})},[sb])
 const load=useCallback(async()=>{if(!open)return;setLoading(true);setError('');try{const{data,error:e}=await(sb as any).rpc('obtener_demanda_proveedor',{p_categoria_id:categoryId||null,p_horas:hours});if(e)throw e;const base=((data||[])as DemandRow[]).map(r=>({...r,pedidos:Number(r.pedidos||0),urgentes:Number(r.urgentes||0),tarifa_promedio:r.tarifa_promedio==null?null:Number(r.tarifa_promedio)}));const labeled=await Promise.all(base.slice(0,12).map(async r=>({...r,label:await coarseLabel(r.zona_lat,r.zona_lng)})));setRows(labeled);const summary:DemandSummary={hours,categoryId:categoryId||null,total:labeled.reduce((n,r)=>n+r.pedidos,0),zones:labeled,top:labeled[0]||null,updatedAt:new Date().toISOString()};(window as any).__UGO_PROVIDER_DEMAND__=summary;window.dispatchEvent(new CustomEvent('ugo:provider-demand-updated',{detail:summary}))}catch(e:any){setRows([]);setError(e?.message||'No pude cargar la demanda.');(window as any).__UGO_PROVIDER_DEMAND__={hours,categoryId:categoryId||null,total:0,zones:[],top:null,updatedAt:new Date().toISOString()}}finally{setLoading(false)}},[categoryId,hours,open,sb])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(!open||!mapEl.current)return;const L=(window as any).L;if(!L)return;const map=mapRef.current||L.map(mapEl.current,{zoomControl:false,attributionControl:true}).setView([-27.5949,-48.5482],11);if(!mapRef.current){L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);mapRef.current=map}layerRef.current.forEach(x=>{try{map.removeLayer(x)}catch{}});layerRef.current=[];if(rows.length){const max=Math.max(...rows.map(r=>r.pedidos),1);rows.forEach(r=>{const level=intensity(r.pedidos,max),marker=L.circle([r.zona_lat,r.zona_lng],{radius:1100,color:color(level),fillColor:color(level),fillOpacity:level==='high'?.36:level==='medium'?.28:.2,weight:2});marker.bindPopup(`<b>${r.label||'Zona aproximada'}</b><br>${r.pedidos} pedido${r.pedidos===1?'':'s'} · ${level==='high'?'Demanda alta':level==='medium'?'Demanda media':'Demanda baja'}`);marker.addTo(map);layerRef.current.push(marker)});const bounds=L.latLngBounds(rows.map(r=>[r.zona_lat,r.zona_lng]));if(bounds.isValid())map.fitBounds(bounds.pad(.45),{maxZoom:13})}else navigator.geolocation?.getCurrentPosition(p=>map.setView([p.coords.latitude,p.coords.longitude],12),()=>{});setTimeout(()=>map.invalidateSize(),80)},[open,rows])
 useEffect(()=>()=>{if(mapRef.current){try{mapRef.current.remove()}catch{}mapRef.current=null}},[])
 if(!open)return null
 const max=Math.max(...rows.map(r=>r.pedidos),1),top=rows[0]||null,categoryName=categoryId?categories.find(c=>c.id===categoryId)?.nombre:'Todas las categorías'
 return <section className="ugo-demand-overlay" aria-label="Mapa de demanda UGO">
  <header className="ugo-demand-head"><div><small>UGO PRO · DEMANDA REAL</small><h2>Mapa de trabajo</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></header>
  <div className="ugo-demand-filters"><label>Categoría<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Todas</option>{categories.map(c=><option key={c.id} value={c.id}>{c.emoji} {c.nombre}</option>)}</select></label><label>Período<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={3}>Últimas 3 h</option><option value={24}>Hoy / 24 h</option><option value={168}>Últimos 7 días</option></select></label><button type="button" onClick={()=>{setCategoryId(mainCategory);setHours(24)}}>Mi categoría</button></div>
  <div className="ugo-demand-map" ref={mapEl}/>
  <div className="ugo-demand-legend"><span><i className="low"/>Baja</span><span><i className="medium"/>Media</span><span><i className="high"/>Alta</span><small>Las áreas son celdas aproximadas de ~2 km. Nunca muestran la dirección exacta de un cliente.</small></div>
  <div className="ugo-demand-summary">{loading?<p>Cargando demanda real…</p>:error?<p className="error">{error}</p>:!rows.length?<><strong>Sin datos suficientes</strong><p>No hay demanda REAL geolocalizada suficiente para {categoryName||'esta categoría'} en este período. UGO no inventa zonas calientes.</p></>:<><strong>{top?.label||'Zona con mayor demanda'}</strong><p>{top?.pedidos||0} pedido{top?.pedidos===1?'':'s'} agregado{top?.pedidos===1?'':'s'} en la zona con mayor actividad. {top&&intensity(top.pedidos,max)==='high'?'Demanda alta.':''}</p></>}</div>
 </section>
}
