import React from'react'
import type{Category,Notice,Offer,Payment,ProviderProfile,Service,UgoUser}from'./shared'
import'./provider-home-structural.css'
import{ProviderActiveMap}from'./ProviderActiveMap'

type FullProviderProfile=ProviderProfile&{experiencia_anos?:number|null;especialidades?:string|null;idiomas?:string|null;disponibilidad_horaria?:string|null;telefono_profesional?:string|null;ciudad_base?:string|null}
type Props={profile:UgoUser;provider:FullProviderProfile;offers:Offer[];service:Service|null;payments:Payment[];busy:boolean;notice:Notice;categories:Category[];onToggleOnline:()=>void;onCenterMap:()=>void;onOffer:(id:string,accept:boolean)=>void;onAdvance:(state:'en_camino'|'llegado'|'en_progreso'|'esperando_aprobacion')=>void;onTab:(tab:'radar'|'jobs'|'earnings'|'profile')=>void;userPos:[number,number]|null}

const money=(v:unknown,currency?:string|null)=>`${currency==='ARS'?'$':'R$'} ${Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const stateLabel=(value:string)=>({asignado:'Asignado',en_camino:'En camino',llegado:'En el lugar',en_progreso:'En progreso',esperando_aprobacion:'Esperando aprobación'}[value]||value.replaceAll('_',' '))

export function ProviderHomeStructural({profile,provider,offers,service,payments,busy,notice,onToggleOnline,onCenterMap,onOffer,onAdvance,onTab,userPos}:Props){
 const currentPayment=service?payments.find(p=>p.servicio_id===service.id):null
 const funded=currentPayment?.estado==='retenido'&&Boolean((currentPayment as Payment&{mp_payment_id?:string|null}).mp_payment_id)
 const released=payments.filter(p=>p.estado==='liberado').reduce((sum,p)=>sum+Number(p.ganancia_proveedor||0),0)
 const retained=payments.filter(p=>p.estado==='retenido'&&Boolean((p as Payment&{mp_payment_id?:string|null}).mp_payment_id)).reduce((sum,p)=>sum+Number(p.ganancia_proveedor||0),0)
 const action=service?.estado==='asignado'&&funded?{label:'Navegar al cliente',state:'en_camino' as const}:service?.estado==='en_camino'?{label:'Confirmar llegada',state:'llegado' as const}:service?.estado==='llegado'?{label:'Iniciar servicio',state:'en_progreso' as const}:service?.estado==='en_progreso'?{label:'Finalizar y pedir aprobación',state:'esperando_aprobacion' as const}:null
 const step=service?.estado==='asignado'?1:service?.estado==='en_camino'?2:service?.estado==='llegado'?3:service?.estado==='en_progreso'?4:service?.estado==='esperando_aprobacion'?5:0
 const topOffer=offers[0]||null
 return <main className="ugo-provider-structural-home">
  <section className="ugo-provider-structural-map" aria-label="Radar de oportunidades en tu zona"><ProviderActiveMap userPos={userPos} /></section>
  <header className="ugo-provider-structural-header">
   <div className="ugo-provider-structural-brand" aria-label="UGO Pro">U.GO <span>PRO</span></div>
   <div className="ugo-provider-structural-greeting"><b>{profile.nombre||'Proveedor'}</b><small>★ {Number(profile.karma||5).toFixed(1)} · {provider.ciudad_base||'Tu zona'}</small></div>
   <button type="button" className={`ugo-provider-structural-presence ${provider.disponible?'on':''}`} onClick={onToggleOnline} disabled={busy} aria-pressed={provider.disponible} aria-label={provider.disponible?'Pausar recepción de oportunidades':'Activar recepción de oportunidades'}><i aria-hidden="true"/>{provider.disponible?'Online':'Offline'}</button>
  </header>
  <section className="ugo-provider-structural-sheet" aria-labelledby="ugo-provider-radar-title">
   <div className="ugo-provider-structural-sheet-head"><div><small>{service?'MISIÓN ACTIVA':offers.length?'DEMANDA CERCANA':'RADAR UGO'}</small><h1 id="ugo-provider-radar-title">{service?service.categoria?.nombre||'Servicio activo':offers.length?`${offers.length} oportunidad${offers.length===1?'':'es'} cerca`:'Tu radar está listo'}</h1><p>{service?service.cliente?.nombre||'Cliente UGO':provider.disponible?(offers.length?'Elegí la oportunidad que mejor encaja con tu jornada.':'Estamos buscando trabajos compatibles con tu zona.'):'Activá Online para recibir nuevas oportunidades.'}</p></div><span className={`ugo-provider-structural-kpi ${provider.disponible?'on':''}`}>{provider.disponible?'ACTIVO':'PAUSADO'}</span></div>
   {notice&&<div className={`ugo-provider-structural-notice ${notice.type}`} role={notice.type==='error'?'alert':'status'} aria-live={notice.type==='error'?'assertive':'polite'}>{notice.text}</div>}
   <div className="ugo-provider-structural-metrics" aria-label="Resumen de ganancias"><div><small>DISPONIBLE</small><b>{money(released)}</b><span>Ganancias liberadas</span></div><div><small>PROTEGIDO</small><b>{money(retained)}</b><span>Fondos retenidos por UGO</span></div></div>
   {service?<article className="ugo-provider-structural-service"><div className="ugo-provider-structural-service-top"><strong>{service.categoria?.emoji||'🧰'} {service.categoria?.nombre||'Servicio'}</strong><span>{stateLabel(service.estado)}</span></div><p>{service.descripcion||'Servicio asignado por UGO.'}</p><div className={`ugo-provider-structural-payment ${funded?'funded':'pending'}`}><span aria-hidden="true">{funded?'✓':'!'}</span><div><b>{funded?'Pago protegido confirmado':'Pago protegido pendiente'}</b><small>{funded?'Podés avanzar con seguridad.':'Esperá la confirmación antes de iniciar el traslado.'}</small></div></div><div className="ugo-provider-structural-progress" aria-label={`Progreso del servicio: paso ${step} de 5`}>{[1,2,3,4,5].map(n=><i key={n} className={n<=step?'done':''} aria-hidden="true"/>)}</div>{action&&<button type="button" className="ugo-provider-structural-cta" onClick={()=>onAdvance(action.state)} disabled={busy} aria-busy={busy}><span>{action.label}</span><i aria-hidden="true">→</i></button>}</article>:<div className="ugo-provider-structural-opportunities">{offers.length===0&&<div className="ugo-provider-structural-empty"><span aria-hidden="true">⌁</span><b>{provider.disponible?'Sin oportunidades por ahora':'Tu radar está pausado'}</b><p>{provider.disponible?'No necesitás actualizar la pantalla: UGO mostrará aquí la próxima demanda compatible.':'Activá tu disponibilidad para empezar a recibir trabajos.'}</p>{!provider.disponible&&<button type="button" onClick={onToggleOnline} disabled={busy}>Activar disponibilidad</button>}</div>}{offers.slice(0,3).map((o,index)=><article className={`ugo-provider-structural-opportunity ${index===0?'featured':''}`} key={o.id}><div><small>{index===0?'MEJOR COINCIDENCIA':'OPORTUNIDAD'}</small><strong>{o.servicio?.categoria?.emoji||'🧰'} {o.servicio?.categoria?.nombre||'Servicio'}</strong><p>{o.servicio?.cliente?.nombre||'Cliente UGO'} · {o.servicio?.descripcion||'Solicitud cercana'}</p></div><b>{money(o.tarifa_ofrecida,o.servicio?.moneda)}</b><div className="ugo-provider-structural-actions"><button type="button" onClick={()=>onOffer(o.id,false)} disabled={busy}>Rechazar</button><button type="button" onClick={()=>onOffer(o.id,true)} disabled={busy} aria-busy={busy}>Aceptar trabajo</button></div></article>)}</div>}
  </section>
  <button type="button" className="ugo-provider-structural-map-cta" onClick={onCenterMap} aria-label="Centrar el mapa en mi ubicación"><span aria-hidden="true">⌖</span><span>Mi ubicación</span></button>
  {topOffer&&!service&&<div className="ugo-provider-structural-offer" aria-hidden="true"><i/><span>{offers.length} oportunidad{offers.length===1?'':'es'} en radar</span></div>}
  <nav className="ugo-provider-structural-nav" aria-label="Navegación principal del proveedor"><button className="active" type="button" onClick={()=>onTab('radar')} aria-current="page"><b aria-hidden="true">⌁</b><span>RADAR</span></button><button type="button" onClick={()=>onTab('jobs')}><b aria-hidden="true">▤</b><span>TRABAJOS</span></button><button type="button" className="ugo-provider-structural-hugo" onClick={()=>onTab('radar')} aria-label="Abrir Hugo en el radar"><b aria-hidden="true">◉</b><span>HUGO</span></button><button type="button" onClick={()=>onTab('earnings')}><b aria-hidden="true">◌</b><span>GANANCIAS</span></button><button type="button" onClick={()=>onTab('profile')}><b aria-hidden="true">◯</b><span>PERFIL</span></button></nav>
 </main>
}
