import React,{useCallback,useEffect,useMemo,useState}from'react'
import{getRoleSupabase}from'../lib/roleSupabase'
import{ProviderApp}from'./ProviderApp'

type P={usuario_id:string;estado_verificacion:string;motivo_rechazo:string|null;onboarding_paso:number|null;telefono_profesional:string|null;ciudad_base:string|null;categoria_principal_id:string|null;cpf:string|null;pix_chave:string|null;pix_tipo:string|null;termos_aceitos_at:string|null;termos_versao:string|null;bio:string|null;experiencia_anos:number|null;especialidades:string|null;idiomas:string|null;disponibilidad_horaria:string|null;zona_radio_km:number|null}
type U={id:string;nombre:string;apellido:string|null;foto_url:string|null;pais:string|null;zona:string|null;endereco:string|null;tipo:string}
type Cat={id:string;nombre:string;emoji:string}
type Sub={id:string;categoria_id:string;nombre:string}
type Doc={id:string;tipo:string;estado:string;notas_rechazo:string|null;url_storage:string}
const TERMS_VERSION='2026-09-04'
const box:React.CSSProperties={maxWidth:760,margin:'32px auto',background:'#fff',border:'1px solid #e5e7eb',borderRadius:24,padding:22,boxShadow:'0 16px 50px rgba(0,0,0,.09)'}
const input:React.CSSProperties={width:'100%',padding:'11px 12px',border:'1px solid #d0d5dd',borderRadius:11,fontSize:14,boxSizing:'border-box'}
const label:React.CSSProperties={display:'grid',gap:5,fontSize:12,fontWeight:700,color:'#344054'}
const primary:React.CSSProperties={border:0,borderRadius:12,padding:'12px 16px',background:'#111820',color:'#fff',fontWeight:800,cursor:'pointer'}
const secondary:React.CSSProperties={border:'1px solid #d0d5dd',borderRadius:12,padding:'11px 14px',background:'#fff',fontWeight:700,cursor:'pointer'}

export function ProviderOnboardingGate(){
 const sb=useMemo(()=>getRoleSupabase('provider'),[]),[session,setSession]=useState<any>(null),[user,setUser]=useState<U|null>(null),[p,setP]=useState<P|null>(null),[cats,setCats]=useState<Cat[]>([]),[subs,setSubs]=useState<Sub[]>([]),[selectedSubs,setSelectedSubs]=useState<string[]>([]),[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[terms,setTerms]=useState(false),[form,setForm]=useState({nombre:'',apellido:'',telefono:'',endereco:'',zona:'',ciudad:'Florianópolis',cpf:'',pix_tipo:'cpf',pix_chave:'',bio:'',experiencia:'',especialidades:'',idiomas:'Português',horarios:'',radio:'15',categoria:''})
 const load=useCallback(async(s:any)=>{if(!s){setSession(null);setLoading(false);return}setSession(s);const[{data:u,error:ue},{data:pp,error:pe},{data:c},{data:d}]=await Promise.all([sb.from('usuarios').select('id,nombre,apellido,foto_url,pais,zona,endereco,tipo').eq('id',s.user.id).maybeSingle(),sb.from('perfiles_proveedor').select('usuario_id,estado_verificacion,motivo_rechazo,onboarding_paso,telefono_profesional,ciudad_base,categoria_principal_id,cpf,pix_chave,pix_tipo,termos_aceitos_at,termos_versao,bio,experiencia_anos,especialidades,idiomas,disponibilidad_horaria,zona_radio_km').eq('usuario_id',s.user.id).maybeSingle(),sb.from('categorias').select('id,nombre,emoji').eq('activa',true).order('nombre'),sb.from('documentos').select('id,tipo,estado,notas_rechazo,url_storage').eq('usuario_id',s.user.id)]);if(ue)throw ue;if(pe)throw pe;if(!u){setMsg('No se encontró el perfil UGO asociado a esta cuenta.');setLoading(false);return}if(u.tipo!=='proveedor'){setMsg('Esta cuenta no está registrada como proveedor.');setLoading(false);return}let prof=pp as P|null;if(!prof){const{data:newP,error}=await sb.from('perfiles_proveedor').insert({usuario_id:s.user.id,estado_verificacion:'registrado',onboarding_paso:1}).select('*').single();if(error)throw error;prof=newP as P}setUser(u as U);setP(prof);setCats((c||[])as Cat[]);setDocs((d||[])as Doc[]);setTerms(Boolean(prof?.termos_aceitos_at));setForm({nombre:u.nombre||'',apellido:u.apellido||'',telefono:prof?.telefono_profesional||'',endereco:u.endereco||'',zona:u.zona||'',ciudad:prof?.ciudad_base||'Florianópolis',cpf:prof?.cpf||'',pix_tipo:prof?.pix_tipo||'cpf',pix_chave:prof?.pix_chave||'',bio:prof?.bio||'',experiencia:prof?.experiencia_anos==null?'':String(prof.experiencia_anos),especialidades:prof?.especialidades||'',idiomas:prof?.idiomas||'Português',horarios:prof?.disponibilidad_horaria||'',radio:String(prof?.zona_radio_km||15),categoria:prof?.categoria_principal_id||''});if(prof?.categoria_principal_id){const{data:srows}=await sb.from('subcategorias').select('id,categoria_id,nombre').eq('categoria_id',prof.categoria_principal_id).eq('activa',true).order('nombre');setSubs((srows||[])as Sub[])}const{data:ps}=await sb.from('proveedor_subcategorias').select('subcategoria_id').eq('proveedor_id',s.user.id).eq('activa',true);setSelectedSubs((ps||[]).map((x:any)=>x.subcategoria_id));setLoading(false)},[sb])
 useEffect(()=>{sb.auth.getSession().then(({data})=>load(data.session).catch(e=>{setMsg(e.message);setLoading(false)}));const{data:l}=sb.auth.onAuthStateChange((_e,s)=>load(s).catch(e=>setMsg(e.message)));return()=>l.subscription.unsubscribe()},[load,sb])
 useEffect(()=>{if(!form.categoria){setSubs([]);return}sb.from('subcategorias').select('id,categoria_id,nombre').eq('categoria_id',form.categoria).eq('activa',true).order('nombre').then(({data})=>setSubs((data||[])as Sub[]))},[form.categoria,sb])
 const doc=(t:string)=>docs.find(d=>d.tipo===t&&d.estado!=='rechazado')||docs.find(d=>d.tipo===t)
 async function uploadDoc(type:string,file:File){if(!session)return;setBusy(true);setMsg('');try{const ext=(file.name.split('.').pop()||'bin').toLowerCase(),path=`${session.user.id}/${type}-${Date.now()}.${ext}`;const{error:upErr}=await sb.storage.from('provider-kyc').upload(path,file,{upsert:false,contentType:file.type});if(upErr)throw upErr;const current=docs.find(d=>d.tipo===type&&d.estado!=='rechazado');if(current){const{error}=await sb.from('documentos').update({url_storage:path,estado:'pendiente',notas_rechazo:null,updated_at:new Date().toISOString(),version:2}).eq('id',current.id);if(error)throw error}else{const{error}=await sb.from('documentos').insert({usuario_id:session.user.id,tipo:type,url_storage:path,descripcion:type.replaceAll('_',' '),estado:'pendiente'});if(error)throw error}setMsg('Documento cargado.');await load(session)}catch(e:any){setMsg(e.message||'No se pudo cargar el documento.')}finally{setBusy(false)}}
 async function uploadPhoto(file:File){if(!session)return;setBusy(true);try{const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${session.user.id}/perfil.${ext}`;const{error}=await sb.storage.from('provider-public').upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;const{data}=sb.storage.from('provider-public').getPublicUrl(path);const{error:ue}=await sb.from('usuarios').update({foto_url:data.publicUrl}).eq('id',session.user.id);if(ue)throw ue;setMsg('Foto de perfil actualizada.');await load(session)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function save(submit=false){if(!session||!p)return;setBusy(true);setMsg('');try{if(!form.nombre.trim()||!form.telefono.trim()||!form.ciudad.trim()||!form.categoria)throw new Error('Completá nombre, teléfono, ciudad y categoría.');if(submit){if(!form.cpf.trim()||!form.pix_chave.trim())throw new Error('Completá CPF y datos PIX.');if(!doc('identidad_frente')||doc('identidad_frente')?.estado==='rechazado')throw new Error('Subí un documento de identidad válido.');if(!terms)throw new Error('Tenés que aceptar los términos para enviar la revisión.')}const now=new Date().toISOString();const{error:ue}=await sb.from('usuarios').update({nombre:form.nombre.trim(),apellido:form.apellido.trim()||null,endereco:form.endereco.trim()||null,zona:form.zona.trim()||null,pais:'BR'}).eq('id',session.user.id);if(ue)throw ue;const payload:any={telefono_profesional:form.telefono.trim(),ciudad_base:form.ciudad.trim(),categoria_principal_id:form.categoria,bio:form.bio.trim()||null,experiencia_anos:form.experiencia?Number(form.experiencia):null,especialidades:form.especialidades.trim()||null,idiomas:form.idiomas.trim()||null,disponibilidad_horaria:form.horarios.trim()||null,zona_radio_km:Number(form.radio||15),cpf:form.cpf.trim()||null,pix_tipo:form.pix_tipo,pix_chave:form.pix_chave.trim()||null,onboarding_paso:submit?13:Math.max(Number(p.onboarding_paso||0),6)};if(terms){payload.termos_aceitos_at=p.termos_aceitos_at||now;payload.termos_versao=TERMS_VERSION}if(submit){payload.estado_verificacion='pendiente';payload.online=false;payload.disponible=false}const{error:pe}=await sb.from('perfiles_proveedor').update(payload).eq('usuario_id',session.user.id);if(pe)throw pe;await sb.from('proveedor_subcategorias').delete().eq('proveedor_id',session.user.id);if(selectedSubs.length){const{error:se}=await sb.from('proveedor_subcategorias').insert(selectedSubs.map(id=>({proveedor_id:session.user.id,subcategoria_id:id,activa:true})));if(se)throw se}setMsg(submit?'Registro enviado. Quedó pendiente de revisión por UGO.':'Progreso guardado.');await load(session)}catch(e:any){setMsg(e.message||'No se pudo guardar.')}finally{setBusy(false)}}
 if(loading)return <div className="mvp-loading"><p>Preparando registro profesional…</p></div>
 if(!session)return <ProviderApp/>
 if(!p||!user)return <div style={box}><h2>Registro profesional</h2><p>{msg||'No se pudo cargar el perfil.'}</p><button style={secondary} onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
 if(p.estado_verificacion==='verificado')return <ProviderApp/>
 if(p.estado_verificacion==='suspendido')return <div style={box}><h2>Cuenta profesional suspendida</h2><p>Tu acceso operativo está suspendido. Contactá a UGO para revisión.</p><button style={secondary} onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
 if(p.estado_verificacion==='pendiente')return <div style={box}><div style={{fontSize:42}}>⏳</div><h1>Registro en revisión</h1><p>Recibimos tus datos y documentos. Un administrador de UGO debe aprobarlos antes de que puedas aparecer como proveedor activo y recibir trabajos.</p>{msg&&<p>{msg}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button style={secondary} onClick={()=>setP({...p,estado_verificacion:'registrado'})}>Revisar mis datos</button><button style={secondary} onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div></div>
 const rejected=p.estado_verificacion==='rechazado'
 return <main style={{minHeight:'100vh',background:'#f6f7f8',padding:'1px 14px 40px'}}><div style={box}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start'}}><div><small style={{fontWeight:900,letterSpacing:1}}>U.G.O. · PROVEEDOR</small><h1 style={{margin:'5px 0'}}>Registro profesional</h1><p style={{margin:0,color:'#667085'}}>Completá tu perfil. Los documentos quedan privados y sólo UGO puede revisarlos.</p></div><span style={{fontSize:28}}>🛠️</span></div>{rejected&&<div style={{marginTop:14,padding:12,borderRadius:12,background:'#fff1f0',color:'#b42318'}}><b>Revisión rechazada.</b><div>{p.motivo_rechazo||'Revisá los datos o documentos señalados y volvé a enviarlos.'}</div></div>}
 <section style={{marginTop:22,display:'grid',gap:14}}><h3>1–4 · Cuenta, datos y contacto</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label style={label}>Nombre<input style={input} value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label style={label}>Apellido<input style={input} value={form.apellido} onChange={e=>setForm({...form,apellido:e.target.value})}/></label></div><label style={label}>Email de acceso<input style={{...input,background:'#f2f4f7'}} value={session.user.email||''} readOnly/></label><label style={label}>Teléfono / WhatsApp<input style={input} value={form.telefono} onChange={e=>setForm({...form,telefono:e.target.value})} placeholder="+55…"/></label><label style={label}>Dirección<input style={input} value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label style={label}>Zona / barrio<input style={input} value={form.zona} onChange={e=>setForm({...form,zona:e.target.value})}/></label><label style={label}>Ciudad<input style={input} value={form.ciudad} onChange={e=>setForm({...form,ciudad:e.target.value})}/></label></div></section>
 <section style={{marginTop:24,display:'grid',gap:12}}><h3>5 · Categoría y subcategorías</h3><label style={label}>Categoría principal<select style={input} value={form.categoria} onChange={e=>{setForm({...form,categoria:e.target.value});setSelectedSubs([])}}><option value="">Elegir…</option>{cats.map(c=><option key={c.id} value={c.id}>{c.emoji} {c.nombre}</option>)}</select></label>{subs.length>0&&<div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{subs.map(s=><button type="button" key={s.id} onClick={()=>setSelectedSubs(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])} style={{...secondary,background:selectedSubs.includes(s.id)?'#111820':'#fff',color:selectedSubs.includes(s.id)?'#fff':'#111'}}>{s.nombre}</button>)}</div>}<label style={label}>Especialidades<input style={input} value={form.especialidades} onChange={e=>setForm({...form,especialidades:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label style={label}>Experiencia (años)<input style={input} type="number" min="0" value={form.experiencia} onChange={e=>setForm({...form,experiencia:e.target.value})}/></label><label style={label}>Radio de trabajo (km)<input style={input} type="number" min="1" value={form.radio} onChange={e=>setForm({...form,radio:e.target.value})}/></label></div><label style={label}>Bio / presentación<textarea style={{...input,minHeight:80}} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label style={label}>Idiomas<input style={input} value={form.idiomas} onChange={e=>setForm({...form,idiomas:e.target.value})}/></label><label style={label}>Disponibilidad<input style={input} value={form.horarios} onChange={e=>setForm({...form,horarios:e.target.value})}/></label></div></section>
 <section style={{marginTop:24,display:'grid',gap:12}}><h3>6 · Foto de perfil</h3>{user.foto_url&&<img src={user.foto_url} alt="Perfil" style={{width:88,height:88,borderRadius:'50%',objectFit:'cover'}}/>}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>e.target.files?.[0]&&uploadPhoto(e.target.files[0])}/></section>
 <section style={{marginTop:24,display:'grid',gap:12}}><h3>7–10 · Identidad y documentos</h3><p style={{fontSize:12,color:'#667085'}}>RG, CNH o pasaporte. La selfie se usa sólo para revisión manual; UGO no realiza reconocimiento facial automático en este flujo.</p>{[['identidad_frente','Documento de identidad · frente (obligatorio)'],['identidad_dorso','Documento · dorso'],['selfie','Selfie de verificación'],['comprobante_domicilio','Comprobante de domicilio']].map(([t,n])=><label key={t} style={label}>{n}<span style={{fontWeight:500,color:doc(t)?.estado==='aprobado'?'#067647':doc(t)?.estado==='rechazado'?'#b42318':'#667085'}}>{doc(t)?`Estado: ${doc(t)?.estado}`:'Sin cargar'} {doc(t)?.notas_rechazo?`· ${doc(t)?.notas_rechazo}`:''}</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={e=>e.target.files?.[0]&&uploadDoc(t,e.target.files[0])}/></label>)}<label style={label}>CPF<input style={input} value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value})} placeholder="000.000.000-00"/></label></section>
 <section style={{marginTop:24,display:'grid',gap:12}}><h3>11 · Datos de cobro / PIX</h3><div style={{display:'grid',gridTemplateColumns:'160px 1fr',gap:10}}><label style={label}>Tipo de chave<select style={input} value={form.pix_tipo} onChange={e=>setForm({...form,pix_tipo:e.target.value})}><option value="cpf">CPF</option><option value="email">Email</option><option value="telefone">Teléfono</option><option value="aleatoria">Aleatoria</option></select></label><label style={label}>Chave PIX<input style={input} value={form.pix_chave} onChange={e=>setForm({...form,pix_chave:e.target.value})}/></label></div></section>
 <section style={{marginTop:24,display:'grid',gap:12}}><h3>12–15 · Términos y revisión</h3><label style={{display:'flex',gap:9,alignItems:'start',fontSize:13}}><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} style={{marginTop:3}}/><span>Acepto los términos de uso, política de privacidad y tratamiento de datos necesarios para validar mi registro profesional. Versión {TERMS_VERSION}.</span></label><div style={{padding:12,borderRadius:12,background:'#f2f4f7',fontSize:12,color:'#475467'}}>Al enviar, tu estado pasa a <b>Pendiente de revisión</b>. No podrás aparecer como proveedor operativo ni recibir trabajos hasta que un Admin de UGO apruebe el registro.</div>{msg&&<div style={{padding:11,borderRadius:11,background:'#fff7ed',fontSize:12}}>{msg}</div>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={busy} style={secondary} onClick={()=>save(false)}>{busy?'Guardando…':'Guardar progreso'}</button><button disabled={busy} style={primary} onClick={()=>save(true)}>{busy?'Enviando…':'Enviar para revisión →'}</button><button disabled={busy} style={secondary} onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div></section></div></main>
}
