import React,{useCallback,useEffect,useState}from'react'

type Props={accessToken:string}
type Status={connected:boolean;mpUserId?:string|null;expiresAt?:string|null;liveMode?:boolean|null;connectedAt?:string|null;configured?:boolean}

export function ProviderMercadoPagoConnect({accessToken}:Props){
 const[status,setStatus]=useState<Status>({connected:false}),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const call=useCallback(async(action:'status'|'connect'|'disconnect')=>{const r=await fetch('/api/test?mp_oauth=1',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({action})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Mercado Pago no respondió.');return data},[accessToken])
 const load=useCallback(()=>call('status').then(setStatus).catch(e=>setMessage(e.message)),[call])
 useEffect(()=>{load();const params=new URLSearchParams(window.location.search),mp=params.get('mp');if(mp){setMessage(mp==='connected'?'Mercado Pago vinculado correctamente.':mp==='invalid_state'?'La autorización venció. Intentá nuevamente.':'No se pudo vincular Mercado Pago.');const clean=new URL(window.location.href);clean.searchParams.delete('mp');window.history.replaceState({},'',clean.toString())}},[load])
 async function connect(){setBusy(true);setMessage('');try{const data=await call('connect');if(!data.authorizationUrl)throw new Error('No se recibió la URL de autorización.');window.location.assign(data.authorizationUrl)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo iniciar la vinculación.');setBusy(false)}}
 async function disconnect(){if(!confirm('¿Desvincular tu cuenta de Mercado Pago de UGO?'))return;setBusy(true);setMessage('');try{await call('disconnect');await load();setMessage('Cuenta desvinculada.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo desvincular.')}finally{setBusy(false)}}
 return <div style={{marginTop:16,padding:14,borderRadius:18,background:'#f7f9fa'}}><strong>Mercado Pago Marketplace</strong><p style={{fontSize:12,lineHeight:1.45,color:'#667085',margin:'6px 0 12px'}}>Vinculá tu cuenta para que Mercado Pago pueda dividir automáticamente el pago entre tu cuenta y la comisión de UGO.</p>{status.connected?<><div style={{fontSize:13}}>✅ Cuenta vinculada{status.mpUserId?` · ID ${status.mpUserId}`:''}</div>{status.connectedAt&&<small style={{display:'block',marginTop:4,opacity:.65}}>Desde {new Date(status.connectedAt).toLocaleString('pt-BR')}</small>}<button type="button" className="mvp-voice-btn" onClick={disconnect} disabled={busy} style={{marginTop:10}}>Desvincular Mercado Pago</button></>:<button type="button" className="mvp-voice-btn" onClick={connect} disabled={busy||status.configured===false}>{busy?'Abriendo Mercado Pago…':'Vincular Mercado Pago'}</button>}{status.configured===false&&<p style={{fontSize:11,color:'#b42318'}}>La aplicación marketplace de Mercado Pago todavía no tiene Client ID/Secret configurados en el servidor.</p>}{message&&<div style={{fontSize:12,marginTop:8}}>{message}</div>}</div>
}
