import React,{useCallback,useEffect,useMemo,useState}from'react'
import type{RealtimeChannel}from'@supabase/supabase-js'
import{AuthScreen,LoadingScreen,PROVIDER_ACTIVE_STATES,money,timeAgo,useRoleSession,type Category,type Notice,type Offer,type Payment,type ProviderProfile,type Service}from'./shared'
import{VoiceHugoDock}from'./VoiceHugoDock'
import'./provider-prototype.css'

type MercadoPagoPayment=Payment&{mp_payment_id?:string|null;mp_status?:string|null}
type Tab='radar'|'jobs'|'earnings'|'profile'

export function ProviderApp(){
 const auth=useRoleSession('provider'),{supabase,session,profile}=auth
 const[categories,setCategories]=useState<Category[]>([]),[provider,setProvider]=useState<ProviderProfile|null>(null),[offers,setOffers]=useState<Offer[]>([]),[service,setService]=useState<Service|null>(null),[payments,setPayments]=useState<MercadoPagoPayment[]>([]),[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(false),[tab,setTab]=useState<Tab>('radar'),[offerOpen,setOfferOpen]=useState(true)
 const loadData=useCallback(async()=>{if(!session)return;const[{data:c},{data:p},{data:o},{data:s},{data:pay}]=await Promise.all([supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.from('perfiles_proveedor').select('*').eq('usuario_id',session.user.id).maybeSingle(),supabase.from('ofertas_servicio').select('*,servicio:servicios(*,categoria:categorias(nombre,emoji),cliente:usuarios!servicios_cliente_id_fkey(nombre))').eq('proveedor_id',session.user.id).eq('estado','pendiente').order('created_at',{ascending:false}),supabase.from('servicios').select('*,categoria:categorias(nombre,emoji),cliente:usuarios!servicios_cliente_id_fkey(nombre)').eq('proveedor_id',session.user.id).in('estado',PROVIDER_ACTIVE_STATES).order('created_at',{ascending:false}).limit(1),supabase.from('pagos').select('*').eq('proveedor_id',session.user.id).order('created_at',{ascending:false})]);setCategories((c||[])as Category[]);setProvider((p as ProviderProfile|null)||null);setOffers((o||[])as Offer[]);setService(((s||[])[0]as Service|undefined)||null);setPayments((pay||[])as MercadoPagoPayment[])},[session,supabase])
 useEffect(()=>{loadData().catch((e:Error)=>setNotice({type:'error',text:e.message}))},[loadData])
 useEffect(()=>{if(!session)return;const ch:RealtimeChannel=supabase.channel(`provider-${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'ofertas_servicio',filter:`proveedor_id=eq.${session.user.id}`},()=>{setOfferOpen(true);loadData()}).on('postgres_changes',{event:'*',schema:'public',table:'servicios',filter:`proveedor_id=eq.${session.user.id}`},loadData).on('postgres_changes',{event:'*',schema:'public',table:'pagos',filter:`proveedor_id=eq.${session.user.id}`},loadData).subscribe();return()=>{supabase.removeChannel(ch)}},[loadData,session,supabase])
 async function update(next:Partial<ProviderProfile>){if(!session||!provider)return;setBusy(true);const{error}=await supabase.from('perfiles_proveedor').update(next).eq('usuario_id',session.user.id);setBusy(false);if(error)return setNotice({type:'error',text:error.message});await loadData()}
 async function toggleOnline(){if(!provider)return;const next=!provider.disponible;await update({disponible:next,online:next})}
 async function offer(id:string,accept:boolean){setBusy(true);const{error}=await supabase.rpc(accept?'aceptar_oferta':'rechazar_oferta',{p_oferta_id:id});setBusy(false);if(error)return setNotice({type:'error',text:error.message});setOfferOpen(false);setNotice({type:accept?'ok':'info',text:accept?'Misión aceptada. Esperando pago protegido del cliente.':'Oferta rechazada.'});await loadData()}
 async function advance(state:'en_camino'|'en_progreso'|'esperando_aprobacion'){if(!service)return;const currentPayment=payments.find(p=>p.servicio_id===service.id),funded=currentPayment?.estado==='retenido'&&Boolean(currentPayment.mp_payment_id);if(service.estado==='asignado'&&!funded)return setNotice({type:'info',text:'Todavía falta la confirmación de Mercado Pago.'});setBusy(true);const{error}=await supabase.rpc('avanzar_servicio',{p_servicio_id:service.id,p_estado:state});setBusy(false);if(error)return setNotice({type:'error',text:error.message});await loadData()}
 if(auth.loading)return<LoadingScreen/>;if(!session||!profile)return<AuthScreen role="provider" supabase={supabase} error={auth.error} onError={auth.setError}/>;if(!provider)return<LoadingScreen label="Preparando perfil profesional…"/>
 const released=payments.filter(p=>p.estado==='liberado').reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0),retained=payments.filter(p=>p.estado==='retenido'&&Boolean(p.mp_payment_id)).reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0),currentPayment=service?payments.find(p=>p.servicio_id===service.id):null,funded=currentPayment?.estado==='retenido'&&Boolean(currentPayment.mp_payment_id),topOffer=offers[0]||null
 const action=service?.estado==='asignado'&&funded?{label:'Navegar al cliente',state:'en_camino' as const}:service?.estado==='en_camino'?{label:'Llegué al cliente',state:'en_progreso' as const}:service?.estado==='en_progreso'?{label:'Finalizar y pedir aprobación',state:'esperando_aprobacion' as const}:null
 const step=service?.estado==='asignado'?1:service?.estado==='en_camino'?2:service?.estado==='en_progreso'?3:service?.estado==='esperando_aprobacion'?4:0
 const initials=(profile.nombre||'P').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()
 return <div className="ugo-provider-prototype">
  <div className="ugo-provider-map"><div className="ugo-provider-center-pin">{initials}</div><div className="ugo-provider-radar-status">{provider.disponible?'Buscando trabajos cerca tuyo':'Estás fuera de línea'}</div></div>
  <div className="ugo-provider-topbar"><div className="ugo-provider-identity"><div className="ugo-provider-avatar-proto">{initials}</div><div><b>{profile.nombre}</b><span>⭐ {Number(profile.karma||5).toFixed(1)} · Proveedor UGO</span></div></div><button className={`ugo-provider-online ${provider.disponible?'on':''}`} onClick={toggleOnline} disabled={busy}><i/>{provider.disponible?'Online':'Offline'}</button></div>
  {notice&&<div className={`ugo-provider-notice ${notice.type}`}>{notice.text}</div>}
  {tab==='radar'&&<>
    <div className="ugo-provider-summary"><div><small>HOY</small><strong>{offers.length} oportunidades</strong></div><div><small>GANANCIAS</small><strong>{money(released)}</strong></div></div>
    {service&&<div className="ugo-provider-mission-sheet"><small>MISIÓN ACTIVA</small><h3>{service.categoria?.emoji} {service.categoria?.nombre||'Servicio'}</h3><p>{service.cliente?.nombre||'Cliente UGO'} · {service.direccion_cliente||'Dirección por confirmar'}</p><div className="ugo-provider-step">{[1,2,3,4].map(n=><i key={n} className={n<=step?'done':''}/>)}</div><p>{service.descripcion}</p>{service.estado==='asignado'&&!funded&&<p style={{marginTop:10}}>Pago pendiente de protección.</p>}{action&&<button className="ugo-provider-primary" onClick={()=>advance(action.state)} disabled={busy}>{action.label}</button>}{service.estado==='esperando_aprobacion'&&<button className="ugo-provider-primary" disabled>Esperando aprobación del cliente</button>}</div>}
  </>}
  {tab==='jobs'&&<div className="ugo-provider-panel"><h2>Trabajos</h2>{service&&<div className="ugo-provider-panel-card"><small>MISIÓN ACTIVA</small><strong>{service.categoria?.emoji} {service.categoria?.nombre}</strong><p>{service.descripcion}</p></div>}{offers.map(o=><div className="ugo-provider-panel-card" key={o.id}><small>OPORTUNIDAD · {timeAgo(o.created_at)}</small><strong>{o.servicio?.categoria?.emoji} {o.servicio?.categoria?.nombre}</strong><p>{o.servicio?.descripcion}</p></div>)}{!service&&!offers.length&&<div className="ugo-provider-panel-card">No hay trabajos pendientes.</div>}</div>}
  {tab==='earnings'&&<div className="ugo-provider-panel"><h2>Ganancias</h2><div className="ugo-provider-panel-card"><small>LIBERADAS</small><strong>{money(released)}</strong></div><div className="ugo-provider-panel-card"><small>PROTEGIDAS EN UGO</small><strong>{money(retained)}</strong></div></div>}
  {tab==='profile'&&<div className="ugo-provider-panel"><h2>Perfil</h2><div className="ugo-provider-panel-card"><small>REPUTACIÓN</small><strong>⭐ {Number(profile.karma||5).toFixed(2)}</strong><label>Categoría principal</label><select value={provider.categoria_principal_id||''} onChange={e=>update({categoria_principal_id:e.target.value||null})}><option value="">Todas / sin definir</option>{categories.map(c=><option key={c.id} value={c.id}>{c.emoji} {c.nombre}</option>)}</select><label>Tarifa base</label><input type="number" min="0" value={provider.tarifa_base} onChange={e=>setProvider({...provider,tarifa_base:Number(e.target.value)})} onBlur={()=>update({tarifa_base:provider.tarifa_base})}/><button className="ugo-provider-primary" onClick={auth.signOut}>Cerrar sesión</button></div></div>}
  {topOffer&&offerOpen&&!service&&<div className="ugo-provider-sheet-backdrop"><div className="ugo-provider-sheet"><div className="ugo-provider-handle"/><div className="ugo-provider-job-label"><small>¡TRABAJO DISPONIBLE!</small><span>{topOffer.distancia_km!=null?`${topOffer.distancia_km} km`:'Cerca tuyo'}</span></div><h2>{topOffer.servicio?.categoria?.emoji} {topOffer.servicio?.categoria?.nombre||'Servicio'}</h2><p className="ugo-job-address">{topOffer.servicio?.direccion_cliente||'Dirección por confirmar'}</p><div className="ugo-job-description">{topOffer.servicio?.descripcion}</div><div className="ugo-provider-money-grid"><div><small>TOTAL</small><strong>{money(topOffer.tarifa_ofrecida,topOffer.servicio?.moneda)}</strong></div><div><small>UGO</small><strong>{money(Number(topOffer.tarifa_ofrecida||0)*.15,topOffer.servicio?.moneda)}</strong></div><div className="net"><small>NETO PARA VOS</small><strong>{money(Number(topOffer.tarifa_ofrecida||0)*.85,topOffer.servicio?.moneda)}</strong></div></div><div className="ugo-provider-actions"><button className="reject" onClick={()=>offer(topOffer.id,false)} disabled={busy}>Rechazar</button><button className="accept" onClick={()=>offer(topOffer.id,true)} disabled={busy}>Aceptar trabajo</button></div></div></div>}
  <div className="ugo-provider-hugo"/>
  <nav className="ugo-provider-bottomnav"><button className={tab==='radar'?'active':''} onClick={()=>setTab('radar')}><b>⌖</b>Radar</button><button className={tab==='jobs'?'active':''} onClick={()=>setTab('jobs')}><b>▣</b>Trabajos</button><button className={tab==='earnings'?'active':''} onClick={()=>setTab('earnings')}><b>$</b>Ganancias</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}><b>●</b>Perfil</button></nav>
  <VoiceHugoDock role="provider" accessToken={session.access_token} service={service} availableOffers={offers.length}/>
 </div>
}
