import React, { useCallback, useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import type { Session, SupabaseClient } from '@supabase/supabase-js'
import { getRoleSupabase, type UgoRole } from '../lib/roleSupabase'

export type Category = { id:string; slug:string; nombre:string; emoji:string }
export type UgoUser = { id:string; nombre:string; tipo:'cliente'|'proveedor'|'admin'; karma:number; servicios_completados:number }
export type ProviderProfile = { usuario_id:string; bio:string|null; tarifa_base:number; online:boolean; disponible:boolean; categoria_principal_id:string|null; estado_verificacion:string }
export type Service = { id:string; numero:number; cliente_id:string; proveedor_id:string|null; categoria_id:string; estado:string; descripcion:string; urgencia:boolean; direccion_cliente:string|null; tarifa:number|null; comision_ugo:number|null; ganancia_proveedor:number|null; moneda:string; created_at:string; updated_at:string; categoria?:{nombre:string;emoji:string}|null; proveedor?:{nombre:string;karma:number}|null; cliente?:{nombre:string}|null }
export type Offer = { id:string; servicio_id:string; proveedor_id:string; estado:string; ranking:number|null; distancia_km:number|null; tarifa_ofrecida:number|null; expira_at:string|null; servicio?:Service|null }
export type Payment = { id:string; servicio_id:string; monto_bruto:number; comision_ugo:number; ganancia_proveedor:number; moneda:string; estado:string }
export type Notice = { type:'ok'|'error'|'info'; text:string } | null

export const ACTIVE_STATES=['buscando','ofrecido','asignado','en_camino','en_progreso','esperando_aprobacion']
export const PROVIDER_ACTIVE_STATES=['asignado','en_camino','en_progreso','esperando_aprobacion']
export const STATUS_ORDER=['buscando','ofrecido','asignado','en_camino','en_progreso','esperando_aprobacion','completado']
export const STATUS_LABELS:Record<string,string>={borrador:'Borrador',buscando:'Buscando profesionales',ofrecido:'Ofertas enviadas',asignado:'Profesional asignado',en_camino:'En camino',en_progreso:'Trabajo en curso',esperando_aprobacion:'Esperando aprobación',completado:'Completado',cancelado:'Cancelado',disputado:'En disputa',pendiente:'Pendiente',autorizado:'Autorizado',retenido:'Retenido',liberado:'Liberado',reembolsado:'Reembolsado',fallido:'Fallido'}
export const money=(value:number|null|undefined,currency='BRL')=>new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(Number(value||0))
export function timeAgo(value:string){const m=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));if(m<1)return'ahora';if(m<60)return`hace ${m} min`;const h=Math.round(m/60);return h<24?`hace ${h} h`:new Date(value).toLocaleDateString('es-AR')}
export function go(app:'client'|'provider'|'admin'|'home'){window.location.href=app==='home'?window.location.pathname:`${window.location.pathname}?app=${app}`}

export function useRoleSession(role:UgoRole){
  const supabase=useMemo(()=>getRoleSupabase(role),[role]);const[session,setSession]=useState<Session|null>(null);const[profile,setProfile]=useState<UgoUser|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
  const loadProfile=useCallback(async(next:Session|null)=>{if(!next){setProfile(null);return}const{data,error:e}=await supabase.from('usuarios').select('id,nombre,tipo,karma,servicios_completados').eq('id',next.user.id).maybeSingle();if(e)throw e;if(!data)throw new Error('No se encontró el perfil conectado a esta cuenta.');const expected=role==='client'?'cliente':'proveedor';if(data.tipo!==expected){await supabase.auth.signOut();throw new Error(`Esta cuenta está registrada como ${data.tipo}. Abrí la aplicación correspondiente.`)}setProfile(data as UgoUser)},[role,supabase])
  useEffect(()=>{let active=true;supabase.auth.getSession().then(async({data})=>{if(!active)return;try{setSession(data.session);await loadProfile(data.session)}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar la sesión.')}finally{if(active)setLoading(false)}});const{data:l}=supabase.auth.onAuthStateChange((_event,next)=>{if(!active)return;setSession(next);loadProfile(next).catch((e:Error)=>setError(e.message))});return()=>{active=false;l.subscription.unsubscribe()}},[loadProfile,supabase])
  const signOut=useCallback(async()=>{await supabase.auth.signOut();setProfile(null);setSession(null)},[supabase]);return{supabase,session,profile,loading,error,setError,signOut}
}

export function AuthScreen({role,supabase,error,onError}:{role:UgoRole;supabase:SupabaseClient;error:string;onError:(v:string)=>void}){
  const[mode,setMode]=useState<'login'|'register'>('login');const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');const label=role==='client'?'Cliente':'Proveedor'
  async function submit(e:FormEvent){e.preventDefault();onError('');setNotice('');setBusy(true);try{if(mode==='login'){const{error:x}=await supabase.auth.signInWithPassword({email,password});if(x)throw x}else{if(!name.trim())throw new Error('Escribí tu nombre.');const{data,error:x}=await supabase.auth.signUp({email,password,options:{data:{nombre:name.trim(),tipo:role==='client'?'cliente':'proveedor'}}});if(x)throw x;if(!data.session)setNotice('Cuenta creada. Revisá tu correo para confirmar el acceso.')}}catch(x){onError(x instanceof Error?x.message:'No se pudo completar el acceso.')}finally{setBusy(false)}}
  return <div className="mvp-auth-page"><button className="mvp-back" onClick={()=>go('home')}>← U.G.O.</button><div className="mvp-auth-card"><div className="mvp-mini-orb"/><div className="mvp-kicker">U.G.O. · {label}</div><h1>{mode==='login'?'Entrar a tu espacio':'Crear tu cuenta'}</h1><p>{role==='client'?'Pedí, seguí y aprobá servicios con Hugo coordinando cada etapa.':'Recibí oportunidades, ejecutá trabajos y controlá tus ganancias.'}</p><div className="mvp-auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Ingresar</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Registrarse</button></div><form onSubmit={submit}>{mode==='register'&&<label>Nombre<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label>{(error||notice)&&<div className={error?'mvp-form-error':'mvp-form-notice'}>{error||notice}</div>}<button className="mvp-primary" disabled={busy}>{busy?'Procesando…':mode==='login'?'Ingresar':'Crear cuenta'}</button></form></div></div>
}

export function AppHeader({role,name,onLogout}:{role:string;name:string;onLogout:()=>void}){return <header className="mvp-header"><button className="mvp-brand" onClick={()=>go('home')}><span>U.G.O.</span><small>{role}</small></button><nav><button onClick={()=>go('client')}>Cliente</button><button onClick={()=>go('provider')}>Proveedor</button><button onClick={()=>go('admin')}>Control</button></nav><div className="mvp-user-chip"><span>{name.slice(0,1).toUpperCase()}</span>{name}<button onClick={onLogout}>Salir</button></div></header>}
export function StateTimeline({state}:{state:string}){const current=STATUS_ORDER.indexOf(state);return <div className="mvp-timeline">{STATUS_ORDER.map((item,index)=><div key={item} className={`mvp-step ${index<=current?'done':''} ${index===current?'current':''}`}><span>{index<current?'✓':index+1}</span><small>{STATUS_LABELS[item]}</small></div>)}</div>}
export function LoadingScreen({label='Conectando U.G.O.…'}:{label?:string}){return <div className="mvp-loading"><div className="mvp-orb"><span/></div><p>{label}</p></div>}
export function HugoDock({role,service,availableOffers=0}:{role:UgoRole;service?:Service|null;availableOffers?:number}){const[open,setOpen]=useState(false);const text=useMemo(()=>{if(role==='client'){if(!service)return'Contame qué necesitás y preparo el pedido.';if(service.estado==='buscando')return'Estoy buscando profesionales disponibles.';if(service.estado==='ofrecido')return`Envié ${availableOffers||'las'} ofertas. Te aviso cuando acepten.`;if(service.estado==='asignado')return'Ya hay profesional y el pago quedó retenido.';if(service.estado==='en_camino')return'El profesional está en camino.';if(service.estado==='en_progreso')return'El trabajo está en curso.';if(service.estado==='esperando_aprobacion')return'Revisá el trabajo. Al aprobarlo libero el pago.';return'Servicio cerrado. Tu reseña actualiza el Karma.'}if(!service)return'Ponete disponible para recibir oportunidades.';if(service.estado==='asignado')return'Aceptaste la misión. Salí hacia el cliente.';if(service.estado==='en_camino')return'Confirmá llegada para iniciar.';if(service.estado==='en_progreso')return'Finalizá y pedí aprobación.';return'El pago sigue retenido hasta la aprobación.'},[availableOffers,role,service]);return <><button className="mvp-orb" onClick={()=>setOpen(v=>!v)} aria-label="Abrir Hugo"><span/></button>{open&&<aside className="mvp-hugo-panel"><div><div className="mvp-mini-orb"/><strong>Hugo</strong><button onClick={()=>setOpen(false)}>×</button></div><p>{text}</p><small>Contexto: {role} · {service?STATUS_LABELS[service.estado]:'sin servicio'}</small></aside>}</>}
