import React,{useEffect,useMemo,useState}from'react'
import{supabase}from'../lib/supabase'

type Tab='command'|'flags'|'audit'|'integrations'|'metrics'|'roles'
type Metric={label:string;value:string;detail:string}
const tabs:[Tab,string][]=[['command','Command Center'],['flags','Feature Flags'],['audit','Audit Log'],['integrations','Integraciones'],['metrics','Métricas globales'],['roles','Roles y permisos']]

export function SuperAdminCommandCenter(){
 const[tab,setTab]=useState<Tab>('command'),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const[metrics,setMetrics]=useState<Metric[]>([]),[flags,setFlags]=useState<Record<string,boolean>>({matching_real:true,pagos_reales:true,whatsapp:true,scout:true})
 const[audit,setAudit]=useState<any[]>([]),[integrations,setIntegrations]=useState<any[]>([])
 const load=async()=>{setLoading(true);setError('');try{const db=supabase as any;const[{count:users},{count:services},{count:providers},{count:payments},{data:config},{data:events}]=await Promise.all([
  db.from('usuarios').select('id',{count:'exact',head:true}),db.from('servicios').select('id',{count:'exact',head:true}),db.from('perfiles_proveedor').select('usuario_id',{count:'exact',head:true}),db.from('pagos').select('id',{count:'exact',head:true}),db.from('config_sistema').select('clave,valor').limit(100),db.from('audit_log').select('*').order('created_at',{ascending:false}).limit(30)
 ]);setMetrics([{label:'Usuarios',value:String(users||0),detail:'cuentas registradas'},{label:'Servicios',value:String(services||0),detail:'órdenes totales'},{label:'Proveedores',value:String(providers||0),detail:'perfiles profesionales'},{label:'Pagos',value:String(payments||0),detail:'movimientos registrados'}]);const rows=(config||[]) as any[];setFlags(current=>rows.reduce((all,row)=>row.clave?.startsWith('feature_')?{...all,[row.clave.replace('feature_','')]:row.valor===true||row.valor==='true'}:all,current));setAudit(events||[]);setIntegrations(rows.filter(row=>/mercado|whatsapp|supabase|map|pix/i.test(row.clave||'')))}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el Command Center.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const auditRows=useMemo(()=>audit.map((row:any)=>({id:row.id,action:row.action||row.evento||row.tipo||'Evento administrativo',actor:row.actor_email||row.usuario_email||row.usuario_id||'Sistema',at:row.created_at})),[audit])
 const persistFlag=async(key:string,next:boolean)=>{setFlags(v=>({...v,[key]:next}));const{error:saveError}=await (supabase as any).from('config_sistema').upsert({clave:`feature_${key}`,valor:next,updated_at:new Date().toISOString()},{onConflict:'clave'});if(saveError){setFlags(v=>({...v,[key]:!next}));setError(saveError.message)}}
 return <section style={{display:'grid',gap:16}}><header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap'}}><div><small>SUPER ADMIN</small><h2 style={{margin:'4px 0'}}>Control global de UGO</h2><p style={{margin:0,color:'#667085'}}>Operación, despliegues y gobierno de plataforma.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?'Actualizando…':'↻ Actualizar'}</button></header><nav className="ugo-admin2-submenu">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{error&&<div style={{padding:12,borderRadius:10,background:'#fff1f0',color:'#b42318'}}>{error}</div>}{tab==='command'&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{metrics.map(m=><article key={m.label} className="ugo-admin2-module-card"><small>{m.label.toUpperCase()}</small><strong style={{display:'block',fontSize:28,margin:'6px 0'}}>{m.value}</strong><span>{m.detail}</span></article>)}</div></>}{tab==='roles'&&<div style={{display:'grid',gap:8}}>{[['superadmin','Control global y gobierno'],['admin','Operación, personas y finanzas'],['support','Atención, reclamos y notificaciones'],['auditor','Lectura de auditoría y métricas']].map(([role,scope])=><article className="ugo-admin2-module-card" key={role}><strong>{role}</strong><p>{scope}</p></article>)}</div>}{tab==='flags'&&<div style={{display:'grid',gap:8}}>{Object.entries(flags).map(([key,enabled])=><label key={key} className="ugo-admin2-module-card" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><span><b>{key.replaceAll('_',' ')}</b></span><input type="checkbox" checked={enabled} onChange={e=>void persistFlag(key,e.target.checked)}/></label>)}</div>}{tab==='audit'&&<div className="ugo-admin2-module-card">{auditRows.length?<table style={{width:'100%'}}><tbody>{auditRows.map(row=><tr key={row.id}><td>{row.action}</td><td>{row.actor}</td><td>{row.at?new Date(row.at).toLocaleString('es-AR'):'—'}</td></tr>)}</tbody></table>:<p>No hay eventos de auditoría disponibles.</p>}</div>}{tab==='integrations'&&<div style={{display:'grid',gap:8}}>{integrations.map((item:any)=><article className="ugo-admin2-module-card" key={item.clave}><strong>{item.clave}</strong><p>{String(item.valor??'Configurada')}</p></article>)}</div>}{tab==='metrics'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{metrics.map(m=><article className="ugo-admin2-module-card" key={m.label}><small>{m.detail}</small><strong style={{display:'block',fontSize:30}}>{m.value}</strong><span>{m.label}</span></article>)}</div>}</section>
}
