import React,{useMemo,useState}from'react'
import'./ugo-client-web.css'

const nav=[
 {id:'home',label:'Inicio',icon:'⌂'},
 {id:'search',label:'Buscar servicio',icon:'⌕'},
 {id:'request',label:'Nueva solicitud',icon:'+'},
 {id:'matching',label:'Matching en vivo',icon:'◎',badge:'live'},
 {id:'active',label:'Servicios activos',icon:'▣',count:'2'},
 {id:'activity',label:'Actividad',icon:'◷'},
 {id:'messages',label:'Mensajes',icon:'◒',count:'3'},
 {id:'payments',label:'Pagos',icon:'R$'},
 {id:'profile',label:'Perfil',icon:'◉'},
 {id:'help',label:'Ayuda',icon:'?'},
 {id:'settings',label:'Configuración',icon:'⚙'},
]as const

type PageId=typeof nav[number]['id']
type Pro={name:string;role:string;eta:string;km:string;rating:string;jobs:string;price:string;tag:string;avatar:string;status:string}
const pros:Pro[]=[
 {name:'Roberto Silva',role:'Plomero & gasista',eta:'12 min',km:'1.8 km',rating:'4.9',jobs:'186',price:'R$ 145',tag:'Mejor coincidencia',avatar:'RS',status:'Disponible ahora'},
 {name:'Lucía Barros',role:'Reparos generales',eta:'8 min',km:'900 m',rating:'4.8',jobs:'94',price:'R$ 120',tag:'Más cerca',avatar:'LB',status:'Responde rápido'},
 {name:'Carlos Méndez',role:'Plomería y mantenimiento',eta:'14 min',km:'2.2 km',rating:'4.9',jobs:'221',price:'R$ 155',tag:'Alta reputación',avatar:'CM',status:'Agenda abierta'},
]
const services=[['Limpieza & Hogar','24 pros cerca','◌'],['Electricidad','12 pros cerca','ϟ'],['Plomería & Gas','8 pros cerca','⌁'],['Climatización','15 pros cerca','✺'],['Pintura Express','7 pros cerca','▧'],['Cerrajería','5 pros activos','⌘']]
const categories=[['Todos los servicios','148','▦'],['Hogar y mantenimiento','45','🛠'],['Plomería y sanitarios','14','⌁'],['Electricidad residencial','18','ϟ'],['Gas y climatización','8','✺'],['Limpieza y desinfección','32','◌'],['Reformas y pintura','21','▧'],['Tecnología y línea blanca','26','▤']]
const timeline=[['07:42','Pedido recibido','UGO registró tu solicitud.'],['07:44','Matching en vivo','3 profesionales respondieron cerca de Canasvieiras.'],['07:47','Profesional seleccionado','Roberto quedó primero por cercanía y reputación.'],['07:59','En camino','ETA actualizado según distancia disponible.']]

export function UgoClientWeb(){
 const[active,setActive]=useState<PageId>('home')
 const title=useMemo(()=>nav.find(x=>x.id===active)?.label||'Inicio',[active])
 return <main className="ugo-client-web" data-page={active}>
  <Sidebar active={active} setActive={setActive}/>
  <section className="ucw-shell">
   <Topbar title={title} setActive={setActive}/>
   <div className="ucw-content">
    {active==='home'&&<HomePage setActive={setActive}/>} 
    {active==='search'&&<SearchPage setActive={setActive}/>} 
    {active==='request'&&<RequestPage setActive={setActive}/>} 
    {active==='matching'&&<MatchingPage setActive={setActive}/>} 
    {active==='active'&&<ActiveServicePage setActive={setActive}/>} 
    {active==='activity'&&<ActivityPage setActive={setActive}/>} 
    {active==='messages'&&<MessagesPage/>} 
    {active==='payments'&&<PaymentsPage/>} 
    {active==='profile'&&<ProfilePage setActive={setActive}/>} 
    {(active==='help'||active==='settings')&&<SupportPage title={title}/>} 
   </div>
  </section>
  <nav className="ucw-mobile-nav">{nav.slice(0,5).map(item=><button key={item.id} className={active===item.id?'active':''} onClick={()=>setActive(item.id)}><b>{item.icon}</b><span>{item.label.replace(' servicio','').replace(' en vivo','')}</span></button>)}</nav>
 </main>
}
function Sidebar({active,setActive}:{active:PageId;setActive:(page:PageId)=>void}){return <aside className="ucw-sidebar"><div className="ucw-logo-row"><div className="ucw-logo-mark">UGO</div><div><b>UGO Cliente</b><small>v2.4</small></div></div><nav>{nav.map(item=><button key={item.id} className={active===item.id?'active':''} onClick={()=>setActive(item.id)}><i>{item.icon}</i><span>{item.label}</span>{item.badge&&<em/>}{item.count&&<strong>{item.count}</strong>}</button>)}</nav><div className="ucw-side-footer"><button onClick={()=>setActive('help')}>?</button><span>Ayuda</span><button onClick={()=>setActive('settings')}>⚙</button></div></aside>}
function Topbar({title,setActive}:{title:string;setActive:(page:PageId)=>void}){return <header className="ucw-topbar"><div className="ucw-location"><b>Ubicación actual</b><span>Canasvieiras, Florianópolis · SC</span></div><label className="ucw-search"><span>⌕</span><input placeholder="Buscar servicio, profesional o pedido"/></label><button className="ucw-hugo" onClick={()=>setActive('request')}>✦ Hugo IA</button><button className="ucw-bell">●</button><button className="ucw-user" onClick={()=>setActive('profile')}><img alt="" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBJTZHuaDQ_ZXWdIg1yuieUS7ctAw-ip5JVVIdMvxQ533zw65P31dEbK8EuWG6VcqKzkQIPKM8HZsdnUKc1YD8Xm3R0e7sbYRtrW59sxlHgwdZVzIeHuwSdiSlI7PCBFPqB3fGx6esrYeotKDt71a"/><span><b>Mariana Costa</b><small>Verificada</small></span></button><div className="ucw-page-title"><small>Panel principal</small><h1>{title}</h1></div></header>}
function HomePage({setActive}:{setActive:(page:PageId)=>void}){return <div className="ucw-dashboard ucw-home"><section className="ucw-main"><HeroCard setActive={setActive}/><Panel kicker="Servicios populares" title="42 en total" action="Ver todos" onAction={()=>setActive('search')}><div className="ucw-service-grid">{services.map(([name,meta,icon])=><button key={name} onClick={()=>setActive('search')}><i>{icon}</i><b>{name}</b><span>{meta}</span></button>)}</div></Panel><Panel kicker="Profesionales destacados" title="Disponibles cerca"><div className="ucw-pro-row">{pros.map(p=><ProviderCard key={p.name} pro={p} onPick={()=>setActive('active')} compact/>)}</div></Panel></section><RightRail setActive={setActive}/></div>}
function HeroCard({setActive}:{setActive:(page:PageId)=>void}){return <section className="ucw-home-hero"><div className="ucw-hello"><span className="ucw-sos">SOS 24/7</span><small>Red express</small><h2>¡Hola Mariana!<br/>¿Qué resolvemos hoy?</h2><p>Pedí asistencia profesional al instante o agendá para tu hogar en Canasvieiras.</p><label><span>⌕</span><input placeholder="Contale a Hugo qué necesitás"/><button onClick={()=>setActive('request')}>Crear pedido</button></label></div><MapPanel/></section>}
function RightRail({setActive}:{setActive:(page:PageId)=>void}){return <aside className="ucw-right"><div className="ucw-protection"><b>Protección UGO activa</b><span>Perfiles visibles, reputación y seguimiento dentro de la plataforma.</span><strong>71 profesionales activos en Canasvieiras</strong></div><Panel kicker="Pedido activo" title="Pérdida de agua"><Timeline compact/><button className="ucw-primary" onClick={()=>setActive('active')}>Ver seguimiento</button></Panel><Panel kicker="Hugo IA" title="Resumen rápido"><p className="ucw-muted">Dirección guardada, urgencia media y categoría recomendada: Plomería.</p><button className="ucw-secondary" onClick={()=>setActive('request')}>Continuar solicitud</button></Panel></aside>}
function SearchPage({setActive}:{setActive:(page:PageId)=>void}){return <div className="ucw-dashboard"><section className="ucw-filter"><Panel kicker="Búsqueda rápida" title="Categorías de servicio"><div className="ucw-category-list">{categories.map(([name,count,icon])=><button key={name}><i>{icon}</i><span>{name}</span><b>{count}</b></button>)}</div></Panel><Panel kicker="Disponibilidad" title="Filtros"><div className="ucw-chip-list"><button>Inmediata &lt;45 min</button><button>Durante el día</button><button>Mejor calificación</button><button>Presupuesto visible</button></div></Panel></section><section className="ucw-main"><Panel kicker="Resultados" title="Profesionales disponibles ahora"><div className="ucw-result-grid">{pros.concat(pros).map((p,i)=><ServiceResult key={`${p.name}-${i}`} pro={p} onPick={()=>setActive('active')} index={i}/>)}</div></Panel></section><RightRail setActive={setActive}/></div>}
function RequestPage({setActive}:{setActive:(page:PageId)=>void}){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="Crear nueva solicitud de servicio" title="Descripción & fotos"><Stepper/><div className="ucw-form"><label>Detalle del problema o síntoma<textarea defaultValue="Tengo una pérdida continua debajo del vanitory del baño principal. La flexible gotea y humedece el mueble. Necesito reemplazo de flexible y revisión de desagüe."/></label><div className="ucw-media-row"><div></div><div></div><button>+ Agregar foto</button></div><div className="ucw-urgency"><button>Urgente<br/><small>&lt; 2 horas</small></button><button className="active">Hoy<br/><small>Recomendado</small></button><button>Programar<br/><small>Elegir horario</small></button></div><button className="ucw-primary wide" onClick={()=>setActive('matching')}>Buscar profesionales compatibles</button></div></Panel></section><RightRail setActive={setActive}/></div>}
function MatchingPage({setActive}:{setActive:(page:PageId)=>void}){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="Buscando en un radio de 8 km" title="Matching algorítmico UGO en curso"><div className="ucw-matching-layout"><RadarMap/><div className="ucw-live-list">{pros.map((p,i)=><ProviderCard key={p.name} pro={p} onPick={()=>setActive('active')} rank={i+1}/>)}</div></div></Panel></section><RightRail setActive={setActive}/></div>}
function ActiveServicePage({setActive}:{setActive:(page:PageId)=>void}){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="Solicitud #UG-8492 · Canasvieiras Centro" title="Roberto Silva está en camino"><div className="ucw-service-active"><RouteMap/><div className="ucw-service-card"><ProviderCard pro={pros[0]} onPick={()=>setActive('messages')}/><div className="ucw-progress"><span style={{width:'65%'}}/></div><p className="ucw-muted">Arribo estimado en 11 min · Tráfico fluido · Actualizado hace 1 min.</p><div className="ucw-actions"><button className="ucw-primary" onClick={()=>setActive('messages')}>Abrir chat</button><button className="ucw-secondary" onClick={()=>setActive('request')}>Ampliar servicio</button></div></div></div></Panel></section><RightRail setActive={setActive}/></div>}
function ActivityPage({setActive}:{setActive:(page:PageId)=>void}){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="Actividad" title="Historial reciente"><div className="ucw-history-grid">{['Servicio concluido','Calificación enviada','Solicitud abierta','Comprobante guardado'].map((x,i)=><article key={x}><b>{x}</b><span>{i+1} Sep · Canasvieiras</span><small>Seguimiento y registro disponibles.</small><button onClick={()=>setActive('active')}>Ver detalle</button></article>)}</div></Panel></section><RightRail setActive={setActive}/></div>}
function MessagesPage(){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="Chat en vivo" title="Roberto Silva en camino"><div className="ucw-chat-layout"><div className="ucw-chat"><p><b>Roberto</b><span>Estoy saliendo desde Jurerê. Llego en aproximadamente 12 minutos.</span></p><p className="me"><b>Mariana</b><span>Perfecto. El acceso es por portería principal, departamento 402.</span></p><p><b>Hugo IA</b><span>Guardé la instrucción para el seguimiento del servicio.</span></p></div><aside><ProviderCard pro={pros[0]} onPick={()=>{}}/><div className="ucw-chip-list"><button>Enviar foto</button><button>Compartir ubicación</button><button>Llamar</button></div></aside></div><label className="ucw-message"><input placeholder="Escribir mensaje"/><button>Enviar</button></label></Panel></section><RightRail setActive={()=>{}}/></div>}
function PaymentsPage(){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="Gestión de pagos" title="Billetera UGO"><div className="ucw-money-grid"><article><span>R$</span><b>485,00</b><small>Total estimado</small></article><article><span>R$</span><b>68,50</b><small>Servicios recientes</small></article><article><span>R$</span><b>205,00</b><small>Pendiente</small></article></div><div className="ucw-breakdown"><p><span>Servicio activo</span><b>R$ 145,00</b></p><p><span>Trabajo adicional</span><b>Pendiente</b></p><p><span>Forma de pago</span><b>Mercado Pago / Pix</b></p></div></Panel></section><RightRail setActive={()=>{}}/></div>}
function ProfilePage({setActive}:{setActive:(page:PageId)=>void}){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="Cliente UGO" title="Mariana Costa"><div className="ucw-profile-head"><img alt="" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBJTZHuaDQ_ZXWdIg1yuieUS7ctAw-ip5JVVIdMvxQ533zw65P31dEbK8EuWG6VcqKzkQIPKM8HZsdnUKc1YD8Xm3R0e7sbYRtrW59sxlHgwdZVzIeHuwSdiSlI7PCBFPqB3fGx6esrYeotKDt71a"/><div><h2>Mariana Costa</h2><p>Canasvieiras, Florianópolis · SC · Depto 402</p><button className="ucw-secondary" onClick={()=>setActive('settings')}>Editar perfil</button></div></div><div className="ucw-metrics"><article><b>18</b><span>Servicios completados</span></article><article><b>5.0</b><span>Reputación cliente</span></article><article><b>4.280,00</b><span>Historial BRL</span></article><article><b>570,00</b><span>Ahorro estimado</span></article></div><div className="ucw-history-grid"><article><b>Datos personales</b><span>Teléfono, dirección y contacto preferido</span></article><article><b>Preferencias</b><span>Horarios, acceso y notificaciones</span></article><article><b>Direcciones guardadas</b><span>Casa, trabajo y ubicaciones frecuentes</span></article></div></Panel></section><RightRail setActive={setActive}/></div>}
function SupportPage({title}:{title:string}){return <div className="ucw-dashboard"><section className="ucw-main"><Panel kicker="UGO Cliente" title={title}><div className="ucw-history-grid"><article><b>Centro de ayuda</b><span>Preguntas frecuentes y soporte.</span></article><article><b>Preferencias</b><span>Notificaciones, seguridad y cuenta.</span></article><article><b>Estado del servicio</b><span>Seguimiento y solicitudes recientes.</span></article></div></Panel></section><RightRail setActive={()=>{}}/></div>}
function Panel({kicker,title,children,action,onAction}:{kicker:string;title:string;children:React.ReactNode;action?:string;onAction?:()=>void}){return <section className="ucw-panel"><header><div><small>{kicker}</small><h3>{title}</h3></div>{action&&<button onClick={onAction}>{action} →</button>}</header>{children}</section>}
function Stepper(){return <ol className="ucw-stepper"><li className="done"><b>1</b><span>Categoría</span></li><li className="current"><b>2</b><span>Descripción & fotos</span></li><li><b>3</b><span>Ubicación</span></li><li><b>4</b><span>Fecha y horario</span></li><li><b>5</b><span>Resumen</span></li></ol>}
function MapPanel(){return <div className="ucw-map-panel"><div className="ucw-map"><span className="home">Mariana</span><span className="pro one">Roberto · 12 min</span><span className="pro two">Lucía · 8 min</span><span className="route"/></div><footer><b>Mapa de cobertura</b><small>Profesionales disponibles en Canasvieiras.</small></footer></div>}
function RadarMap(){return <div className="ucw-radar-map"><i/><i/><i/><span>Mariana<br/><small>Tu hogar</small></span><b className="a">RS</b><b className="b">LB</b><b className="c">CM</b></div>}
function RouteMap(){return <div className="ucw-route-map"><span className="truck">Roberto · 38 km/h</span><span className="home">Tu domicilio</span><i/></div>}
function Timeline({compact=false}:{compact?:boolean}){return <ol className={`ucw-timeline${compact?' compact':''}`}>{timeline.map(([time,title,text],i)=><li key={time} className={i<3?'done':'current'}><b>{time}</b><div><strong>{title}</strong>{!compact&&<span>{text}</span>}</div></li>)}</ol>}
function ProviderCard({pro,onPick,compact=false,rank}:{pro:Pro;onPick:()=>void;compact?:boolean;rank?:number}){return <button className={`ucw-provider${compact?' compact':''}`} onClick={onPick}><span>{pro.avatar}</span><div><small>{rank?`#${rank} · `:''}{pro.tag}</small><b>{pro.name}</b><em>{pro.role} · {pro.jobs} servicios</em><strong>★ {pro.rating} · {pro.eta} · {pro.price}</strong></div><i>›</i></button>}
function ServiceResult({pro,onPick,index}:{pro:Pro;onPick:()=>void;index:number}){return <article className="ucw-result"><div className="ucw-photo">{pro.avatar}</div><div><small>{pro.status}</small><h4>{pro.role}</h4><p>{pro.name} · ★ {pro.rating} · {pro.jobs} servicios</p><b>{pro.price}</b></div><button onClick={onPick}>{index%2?'Reservar':'Ver perfil'}</button></article>}
