import React,{useState}from'react'
import{go}from'./shared'
import'./ugo-landing.css'
import'./ugo-landing-responsive.css'

type View='home'|'how'|'services'|'providers'|'safety'|'faq'|'contact'|'terms'|'privacy'|'access'|'signup'
const nav:[View,string][]=[['how','Cómo funciona'],['services','Servicios'],['providers','Para profesionales'],['safety','Seguridad']]
const common=[['Simple','Florianópolis, SC · información pública y placeholder.'],['Seguro','Florianópolis, SC · información pública y placeholder.'],['Cerca de vos','Florianópolis, SC · información pública y placeholder.'],['Acción pública','Conocé UGO, explorá servicios o iniciá tu acceso.']]

function Header({setView}:{setView:(view:View)=>void}){return <header className="ugo-landing-header"><button className="ugo-landing-brand" onClick={()=>setView('home')}>UGO</button><nav>{nav.map(([id,label])=><button key={id} onClick={()=>setView(id)}>{label}</button>)}<button onClick={()=>setView('faq')}>Ayuda</button></nav><div><button className="ugo-landing-login" onClick={()=>setView('access')}>Iniciar sesión</button><button className="ugo-landing-primary" onClick={()=>setView('signup')}>Crear cuenta</button></div></header>}
function Cards(){return <div className="ugo-landing-cards">{common.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div>}
function Page({view}:{view:View}){if(view==='home')return <><section className="ugo-landing-home"><div><span className="ugo-landing-badge">FLORIANÓPOLIS · BR</span><h1>Encontrá ayuda confiable cerca de vos.</h1><p>Pedí servicios para tu casa de forma rápida, segura y simple.</p><button className="ugo-landing-search">¿Qué necesitás? · Florianópolis, SC</button><p className="ugo-landing-actions"><button className="ugo-landing-primary" onClick={()=>go('client')}>Buscar profesionales</button><button className="ugo-landing-secondary" onClick={()=>go('provider')}>Quiero ofrecer mis servicios</button></p></div><aside className="ugo-landing-map"><b>Cobertura prevista · Florianópolis</b><div className="ugo-landing-provider">Rafael Oliveira<small>4,9 ★ · 12 min · R$ 145</small></div><span className="ugo-landing-orb">H</span><em>“Preciso de ajuda hoje”</em></aside></section><Cards/><section className="ugo-landing-near"><p>Profissionais e serviços com informações claras antes de contratar.</p><h2>Profesionales cerca de vos</h2><article><h3>Rafael Oliveira</h3><p>Electricista · Verificado · 4,9 ★ · desde R$ 145,00</p></article></section></>
 if(view==='how')return <PageShell title="Así funciona UGO" subtitle="Contanos qué necesitás, elegí un profesional, seguí el servicio y pagá en BRL."><Cards/><ol className="ugo-landing-steps">{[['1 · Pedís','Contanos qué necesitás'],['2 · Elegís','Compará perfiles'],['3 · Seguís','Acompañá el servicio'],['4 · Pagás','Pagá y calificá']].map(([a,b])=><li key={a}><b>{a}</b><span>{b}</span></li>)}</ol><button className="ugo-landing-primary" onClick={()=>go('client')}>Pedir un servicio</button></PageShell>
 if(view==='services')return <PageShell title="Servicios para tu casa" subtitle="Electricidad · Limpieza · Encanamento · Montaje · Reparaciones · Mantenimiento."><Cards/><button className="ugo-landing-primary" onClick={()=>go('client')}>Pedir un servicio</button></PageShell>
 if(view==='providers')return <PageShell title="¿Sos profesional? Trabajá con UGO." subtitle="Oportunidades cerca, portfolio, cobros y reputación. Requiere verificación antes de operar."><Cards/><section className="ugo-landing-provider-banner"><div><h2>¿Sos profesional? Trabajá con UGO.</h2><p>Oportunidades cerca, portfolio, cobros y reputación.</p></div><button className="ugo-landing-primary" onClick={()=>go('provider')}>Quiero ser proveedor</button></section></PageShell>
 if(view==='faq'||view==='contact'||view==='terms'||view==='privacy'){const data={faq:['Preguntas frecuentes','Qué es UGO, pagos, cancelaciones, calificaciones, verificación y disponibilidad.'],contact:['Estamos para ayudarte','Centro de ayuda · Soporte · Reportar problema. No se publican contactos inventados.'],terms:['Términos de UGO','Información legal pública.'],privacy:['Privacidad de UGO','Cómo cuidamos la información y tus decisiones.']}[view];return <PageShell title={data[0]} subtitle={data[1]}><Cards/><button className="ugo-landing-primary" onClick={()=>go('client')}>Pedir un servicio</button></PageShell>}
 if(view==='access'||view==='signup'){const sign=view==='signup';return <PageShell title={sign?'Creá tu cuenta':'Accedé a UGO'} subtitle={sign?'Elegí el tipo de cuenta para continuar con el registro.':'Elegí el tipo de cuenta para continuar.'}><div className="ugo-landing-selectors"><button onClick={()=>go('client')}><b>{sign?'Cliente':'Acceso Cliente'}</b><span>{sign?'Pedí y seguí servicios para tu casa.':'Cliente → UGO Web / Cliente / Login'}</span></button><button onClick={()=>go('provider')}><b>{sign?'Proveedor':'Acceso Proveedor'}</b><span>{sign?'Gestioná oportunidades, cobros y portfolio.':'Proveedor → UGO Web / Proveedor / Login'}</span></button></div></PageShell>}
 return <PageShell title="Más confianza en cada servicio" subtitle="Perfiles verificados, evidencia, pagos trazables, soporte y resolución de incidencias."><Cards/><div className="ugo-landing-trust">{['Verificación','Reputación','Evidencia','Pagos','Soporte','Disputas'].map(x=><article key={x}><b>{x}</b><span>Información clara y trazable.</span></article>)}</div></PageShell>}
function PageShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="ugo-landing-page"><h1>{title}</h1><p>{subtitle}</p>{children}</section>}
export function UgoLanding(){const[view,setView]=useState<View>('home');return <main className="ugo-landing"><Header setView={setView}/><Page view={view}/><footer>Producto　 Compañía　 Legal　 Ayuda　 Acceso <span>Brasil · Florianópolis</span></footer></main>}
