import { useCallback, useEffect, useRef, useState } from 'react'
import { getRoleSupabase } from '../lib/roleSupabase'
import { getDispatchProvider } from '../lib/dispatch/provider'
import type { ClientActionHandlers, ClientHugoIntent } from './client/clientTypes'
import { resolveClientSavedAddress } from './hugoDefaultAddress'

export type HugoVoiceState = 'idle' | 'connecting' | 'ready' | 'hearing' | 'speaking' | 'error'
type VoiceOptions = { role:'client'|'provider'; accessToken?:string; context:string; clientActions?:ClientActionHandlers; onIntent?:(intent:Omit<ClientHugoIntent,'id'>)=>void }
type ChatTurn={role:'user'|'assistant';content:string}
type GeminiReply={reply:string;action?:'none'|'search_provider'|'prepare_request';category_hint?:string|null;urgent?:boolean;description?:string|null;model?:string}
type NativeVoiceBridge={startListening:()=>void;stopListening:()=>void;isAvailable?:()=>boolean}
type ClientVoiceAction='hire_provider'|'create_request'|'pay'|'cancel'|'approve'|'dispute'
type PendingAction={action:ClientVoiceAction}
type HugoLocale='es-AR'|'pt-BR'
type OrderStep='category'|'description'|'address'|'location_consent'|'when'|'confirm'
type RequestedWhen='ahora'|'hoy'|'programar'
type OrderDraft={step:OrderStep;categoryHint:string|null;categoryId:string|null;categorySlug:string|null;description:string;address:string;requestedWhen:RequestedWhen|null;scheduleAt:string;whenLabel:string;urgent:boolean;coords?:{lat:number;lng:number}|null}
type SavedPlace={address:string;label:string}

const CLIENT_BEHAVIOR=[
 'Sos Hugo, compañero operativo de UGO Cliente, no un chatbot genérico.',
 'Sos como un buen amigo que sabe resolver: cercano, breve, seguro y práctico.',
 'Preguntá solamente el dato imprescindible que falta y nunca repitas datos ya conocidos.',
 'Para un pedido reuní categoría, descripción, dirección y cuándo. La foto es opcional. Confirmá antes de crear.',
 'Si el cliente ya tiene una dirección predeterminada guardada, usala sin volver a preguntarla; solo pedí dirección si no existe una utilizable o si el cliente indica otro lugar.',
 'No obligues al cliente a definir presupuesto para iniciar un pedido.',
 'Cuando haya varias opciones reales, ayudá a decidir y explicá por qué conviene una, sin inventar datos.',
 'Si pide usar su ubicación actual, pedí autorización antes de solicitar GPS.',
 'Nunca inventes proveedor, precio, reputación, ETA, disponibilidad, pago, evidencia ni estado.',
 'La app y el backend son la fuente de verdad.',
 'Contratar, crear definitivamente un pedido, pagar, cancelar, liberar pago o abrir disputa requieren confirmación explícita.',
].join(' ')

const COPY={
 'es-AR':{heard:'Te escucho. Contame qué necesitás.',resume:'Seguimos donde quedamos. Te escucho.',noChange:'Perfecto, no hago ningún cambio.',unavailable:'Esa acción no está disponible en este momento.',fallback:'No pude responder ahora, pero tu pedido sigue intacto.',mic:'Permití el micrófono para hablar con Hugo.',noVoice:'El reconocimiento de voz no está disponible en este dispositivo.',voiceInterrupted:'Se interrumpió el reconocimiento de voz.',lang:'Listo. Seguimos en español.',needConfirm:'Necesito una confirmación clara.'},
 'pt-BR':{heard:'Estou ouvindo. Me conta o que você precisa.',resume:'Continuamos de onde paramos. Estou ouvindo.',noChange:'Perfeito, não vou fazer nenhuma alteração.',unavailable:'Essa ação não está disponível neste momento.',fallback:'Não consegui responder agora, mas seu pedido continua intacto.',mic:'Permita o microfone para falar com o Hugo.',noVoice:'O reconhecimento de voz não está disponível neste dispositivo.',voiceInterrupted:'O reconhecimento de voz foi interrompido.',lang:'Pronto. Continuamos em português.',needConfirm:'Preciso de uma confirmação clara.'},
} as const

function sessionKey(role:string,token?:string){let uid='anon';try{const payload=JSON.parse(atob(String(token||'').split('.')[1]?.replace(/-/g,'+').replace(/_/g,'/')||''));uid=String(payload?.sub||'anon')}catch{}return`ugo:hugo:history:${role}:${uid}`}
function readHistory(key:string):ChatTurn[]{try{const raw=sessionStorage.getItem(key),value=raw?JSON.parse(raw):[];return Array.isArray(value)?value.slice(-20):[]}catch{return[]}}
function writeHistory(key:string,history:ChatTurn[]){try{sessionStorage.setItem(key,JSON.stringify(history.slice(-20)))}catch{}}
function getNativeBridge(){return(window as any).UGOVoiceBridge as NativeVoiceBridge|undefined}
async function ensureMicrophoneAccess(){if(!navigator.mediaDevices?.getUserMedia)return;const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.getTracks().forEach(track=>track.stop())}
function normalizeText(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}\s:.,/-]/gu,' ').replace(/\s+/g,' ').trim()}
function contextLocale(context:string):HugoLocale{return/idioma preferido\s*:\s*(pt|pt br|portugues)/.test(normalizeText(context))?'pt-BR':'es-AR'}
function explicitLocale(text:string):HugoLocale|null{const m=normalizeText(text);if(/\b(fala|fale|responde|responda)\b.*\bportugues\b|\bem portugues\b/.test(m))return'pt-BR';if(/\b(habla|hablame|responde)\b.*\bespanol\b|\ben espanol\b/.test(m))return'es-AR';return null}
function inferredLocale(text:string,current:HugoLocale):HugoLocale{const m=normalizeText(text),pt=(m.match(/\b(quero|preciso|pode|voce|obrigado|servico|trabalho|encanador|jardineiro|chaveiro|agora|nao|sim|endereco)\b/g)||[]).length,es=(m.match(/\b(quiero|necesito|podes|puedes|vos|gracias|servicio|trabajo|plomero|jardinero|cerrajero|ahora|no|si|direccion)\b/g)||[]).length;if(pt>=2&&pt>es)return'pt-BR';if(es>=2&&es>pt)return'es-AR';return current}
function requestedCategory(text:string){const m=normalizeText(text);if(/\b(jardinero|jardinera|jardineria|jardin|jardineiro|jardinagem|pasto|cesped)\b/.test(m))return'jardineria';if(/\b(electricista|electricidad|electrico|electrica|eletricista|eletrica|eletrico|enchufe|enchufes|tomacorriente|tomacorrientes|ventilador de techo|punto de luz)\b/.test(m))return'electricidad';if(/\b(plomero|plomera|plomeria|fontanero|fontaneria|encanador|encanamento|canilla|grifo|perdida de agua)\b/.test(m))return'plomeria';if(/\b(limpieza|limpiador|limpiadora|faxina|limpeza|diarista)\b/.test(m))return'limpieza';if(/\b(pintor|pintora|pintura)\b/.test(m))return'pintura';if(/\b(cerrajero|cerrajeria|chaveiro)\b/.test(m))return'cerrajeria';if(/\b(mueble|muebles|puerta de cocina|puertas de cocina|bisagra|bisagras|carpintero|carpinteria|reparacion|reparar|arreglar)\b/.test(m))return'reparaciones';return null}
function serviceRequestIntent(text:string){const m=normalizeText(text);return/\b(necesito|quiero pedir|quiero contratar|preciso|quero pedir|quero contratar|me hace falta|necesitaria|necesito que|quiero que|tengo que arreglar|hay que arreglar|arreglar|reparar)\b/.test(m)}
function searchOnlyIntent(text:string){const m=normalizeText(text);return/\b(busca|buscame|buscar|mostrame|mostre|encontra|encontre|quienes hay|quem tem|disponibles|disponiveis)\b/.test(m)&&!serviceRequestIntent(text)}
function urgencyFrom(text:string){return/\b(urgente|urgencia|ahora mismo|ya mismo|agora|emergencia)\b/.test(normalizeText(text))}
function descriptionFrom(text:string,category:string|null){const clean=String(text||'').trim();if(clean.length<12)return'';const m=normalizeText(clean);if(category&&new RegExp(`^(necesito|quiero|preciso|quero)\\s+(un|una|um|uma)?\\s*${category}`).test(m)&&m.split(' ').length<5)return'';return clean}
function problemDescriptionFrom(text:string,category:string|null){const clean=String(text||'').trim();if(clean.length<5)return'';const issue=clean.match(/(?:se me\s+)?(?:rompi[oó]|rompieron|quebr[oó]|quebraron|quem[oó]|quemaron)\b[^,.!?]*|(?:no|nao|não)\s+(?:funciona|funcionan|anda|andan|liga|ligam)\b[^,.!?]*|(?:pierde\s+agua|gotea|vaza|tem\s+vazamento)\b[^,.!?]*|(?:hay|tengo|tem|tenho)\s+(?:un|una|um|uma)?\s*(?:p[eé]rdida|fuga|problema|chispa|fa[ií]sca)\b[^,.!?]*|(?:cortar|instalar|limpiar|limpar|pintar|arreglar|reparar|cambiar|trocar|montar|consertar)\b[^,.!?]*/i);if(issue?.[0]?.trim())return issue[0].trim();const generic=descriptionFrom(clean,category);if(!generic)return'';const m=normalizeText(generic);const onlyRequest=/^(necesito|quiero|preciso|quero)\b/.test(m)&&!/(romp|quebr|quem|no funciona|no anda|pierde|gotea|vaza|perdida|fuga|problema|chispa|cortar|instalar|limpiar|limpar|pintar|arreglar|reparar|cambiar|trocar|montar|consertar)/.test(m);return onlyRequest?'':generic}
function wantsCurrentLocation(text:string){return/\b(mi ubicacion actual|mi direccion actual|donde estoy|ubicacion de ahora|usar mi ubicacion|tomar mi ubicacion|toma mi ubicacion|minha localizacao atual|meu endereco atual|onde estou|usar minha localizacao|pegue minha localizacao)\b/.test(normalizeText(text))}
function savedPlaceLabel(text:string):'Casa'|'Trabajo'|null{const m=normalizeText(text);if(/\b(mi casa|en casa|casa|hogar|minha casa|em casa)\b/.test(m))return'Casa';if(/\b(mi trabajo|en el trabajo|trabajo|oficina|meu trabalho|no trabalho|trabalho|escritorio)\b/.test(m))return'Trabajo';return null}
function affirmative(text:string){return/^(si|sim|dale|confirmo|confirmar|hacelo|faca|pode fazer|adelante|okey|okay|ok|de acuerdo|de acordo|correcto|correto|vamos|esta bien|esta bien asi)$/.test(normalizeText(text))}
function negative(text:string){return/^(no|nao|no gracias|nao obrigado|nao obrigada|dejalo|deja|deixe|melhor nao|mejor no)$/.test(normalizeText(text))}
function compactSpeech(text:string,max=320){const cleaned=String(text||'').replace(/[*_#`]/g,'').replace(/\s+/g,' ').trim();if(cleaned.length<=max)return cleaned;const cut=cleaned.slice(0,max),end=Math.max(cut.lastIndexOf('. '),cut.lastIndexOf('? '),cut.lastIndexOf('! '));return(end>120?cut.slice(0,end+1):cut).trim()}
function localInputValue(date:Date){const p=(n:number)=>String(n).padStart(2,'0');return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`}
function parseTiming(text:string){const m=normalizeText(text),now=new Date();if(/\b(ahora|ya mismo|agora)\b/.test(m))return{requestedWhen:'ahora' as const,scheduleAt:'',whenLabel:'Ahora',urgent:true};if(/\b(hoy|hoje)\b/.test(m)&&!/manana|amanha/.test(m))return{requestedWhen:'hoy' as const,scheduleAt:'',whenLabel:'Hoy',urgent:false};if(/\b(manana|amanha)\b/.test(m)){const d=new Date(now);d.setDate(d.getDate()+1);let hour=10,minute=0;const clock=m.match(/(?:a las|a la|as|às)\s*(\d{1,2})(?:[:h](\d{2}))?/);if(clock){hour=Math.min(23,Math.max(0,Number(clock[1])));minute=Math.min(59,Math.max(0,Number(clock[2]||0)))}else if(/\btarde\b/.test(m))hour=15;else if(/\bnoche|noite\b/.test(m))hour=19;else if(/\bmanana temprano|cedo\b/.test(m))hour=9;d.setHours(hour,minute,0,0);return{requestedWhen:'programar' as const,scheduleAt:localInputValue(d),whenLabel:`Mañana ${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`,urgent:false}}return null}
function safetyAdvice(text:string,locale:HugoLocale){const m=normalizeText(text);if(/\b(chispa|chispas|faísca|faisca|faíscas|faiscas|olor a quemado|cheiro de queimado)\b/.test(m))return locale==='pt-BR'?'Não use esse ponto elétrico até o profissional revisar. ':'No uses ese enchufe o punto eléctrico hasta que lo revise el profesional. ';return''}
function nextOrderStep(draft:OrderDraft):OrderStep{if(!draft.categoryHint)return'category';if(!draft.description)return'description';if(!draft.address)return'address';if(!draft.requestedWhen)return'when';return'confirm'}
function requestedAction(text:string):ClientVoiceAction|null{const m=normalizeText(text);if(/\b(contratalo|contratala|contratarlo|contratarla|contrata este|contrate ele|elegi este|escolha esse)\b/.test(m))return'hire_provider';if(/\b(enviar pedido|manda el pedido|mandalo|crear pedido|criar pedido|confirmar pedido|pedir el servicio|pedir o servico|envia o pedido)\b/.test(m))return'create_request';if(/\b(pagar|paga|pagalo|pague|hacer el pago|fazer o pagamento)\b/.test(m))return'pay';if(/\b(cancelar pedido|cancelar servicio|cancelar servico|cancela el pedido|cancele o pedido)\b/.test(m))return'cancel';if(/\b(estoy conforme|estou de acordo|libera el pago|liberar el pago|aproba el trabajo|aprovar o trabalho|todo quedo bien|ficou tudo certo)\b/.test(m))return'approve';if(/\b(abrir disputa|quiero una disputa|quero abrir uma disputa|tengo un problema|tenho um problema|no quedo bien|nao ficou bom|no estoy conforme|nao estou de acordo)\b/.test(m))return'dispute';return null}
function actionCopy(action:ClientVoiceAction,locale:HugoLocale){const pt=locale==='pt-BR';const map:Record<ClientVoiceAction,{prompt:string;success:string}>={hire_provider:{prompt:pt?'Confirma que quer contratar este profissional?':'¿Confirmás que querés contratar a este profesional?',success:pt?'Pronto. Abri o pedido com este profissional selecionado.':'Listo. Abrí el pedido con este profesional seleccionado.'},create_request:{prompt:pt?'Confirma que quer enviar este pedido?':'¿Confirmás que querés enviar este pedido?',success:pt?'Pronto. Enviei o pedido.':'Listo. Envié el pedido.'},pay:{prompt:pt?'Confirma que quer iniciar o pagamento deste serviço?':'¿Confirmás que querés iniciar el pago de este servicio?',success:pt?'Pronto. Abri o pagamento.':'Listo. Abrí el pago.'},cancel:{prompt:pt?'Confirma que quer cancelar este serviço?':'¿Confirmás que querés cancelar este servicio?',success:pt?'Pronto. Cancelei o serviço.':'Listo. Cancelé el servicio.'},approve:{prompt:pt?'Confirma que está de acordo e quer aprovar o trabalho?':'¿Confirmás que estás conforme y querés aprobar el trabajo?',success:pt?'Pronto. Aprovei o trabalho.':'Listo. Aprobé el trabajo.'},dispute:{prompt:pt?'Confirma que quer abrir uma disputa por este serviço?':'¿Confirmás que querés abrir una disputa por este servicio?',success:pt?'Pronto. Abri a disputa.':'Listo. Abrí la disputa.'}};return map[action]}
async function executeClientAction(action:ClientVoiceAction,actions?:ClientActionHandlers){if(!actions)return false;if(action==='hire_provider'){actions.openProvider();return true}if(action==='create_request')return actions.createService();if(action==='pay')return actions.openPayment();if(action==='cancel')return actions.cancelService();if(action==='approve')return actions.approveService();if(action==='dispute'){actions.openDispute();return true}return false}
async function reverseGeocode(lat:number,lng:number){try{const r=await fetch(`https://photon.komoot.io/reverse?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lng)}`,{headers:{accept:'application/json'}}),data:any=await r.json().catch(()=>null),p=data?.features?.[0]?.properties||{},parts=[p.name,p.street&&p.housenumber?`${p.street} ${p.housenumber}`:p.street,p.district,p.city,p.state].filter(Boolean);return Array.from(new Set(parts.map(String))).join(', ')||null}catch{return null}}
async function resolveCategory(hint:string){const sb=getRoleSupabase('client'),{data,error}=await sb.from('categorias').select('id,slug,nombre').eq('activa',true);if(error)throw error;const h=normalizeText(hint);return(data||[]).find((c:any)=>{const slug=normalizeText(c.slug||''),name=normalizeText(c.nombre||'');return slug.includes(h)||h.includes(slug)||name.includes(h)||h.includes(name)})||null}
async function resolveSavedPlace(text:string):Promise<SavedPlace|null>{const label=savedPlaceLabel(text);return resolveClientSavedAddress(label)}
async function harvestOrderFacts(draft:OrderDraft,text:string,{description=true,address=true}:{description?:boolean;address?:boolean}={}){if(!draft.categoryHint){const hint=requestedCategory(text);if(hint){draft.categoryHint=hint;const cat=await resolveCategory(hint);draft.categoryId=cat?.id||null;draft.categorySlug=cat?.slug||null}}if(description&&!draft.description){const desc=problemDescriptionFrom(text,draft.categoryHint);if(desc)draft.description=desc}if(!draft.requestedWhen){const timing=parseTiming(text);if(timing){draft.requestedWhen=timing.requestedWhen;draft.scheduleAt=timing.scheduleAt;draft.whenLabel=timing.whenLabel;draft.urgent=draft.urgent||timing.urgent}}if(address&&!draft.address&&!wantsCurrentLocation(text)){const saved=await resolveSavedPlace(text);if(saved)draft.address=saved.address}draft.step=nextOrderStep(draft)}
async function createVoiceOrder(draft:OrderDraft){const sb=getRoleSupabase('client'),{data:sess}=await sb.auth.getSession(),user=sess.session?.user;if(!user)throw new Error('Sesión requerida');let categoryId=draft.categoryId,categorySlug=draft.categorySlug;if(!categoryId&&draft.categoryHint){const cat=await resolveCategory(draft.categoryHint);categoryId=cat?.id||null;categorySlug=cat?.slug||null}if(!categoryId)throw new Error('No pude identificar la categoría');const metadata:any={source:'hugo-conversational',demo:false,voice:true,requested_when:draft.requestedWhen,scheduled_at:draft.requestedWhen==='programar'?draft.scheduleAt||null:null};if(draft.coords)metadata.client_location={latitude:draft.coords.lat,longitude:draft.coords.lng};const{data,error}=await sb.from('servicios').insert({cliente_id:user.id,categoria_id:categoryId,estado:'buscando',descripcion:draft.description,direccion_cliente:draft.address,tarifa:null,urgencia:draft.urgent,metadata}).select('id').single();if(error)throw error;await getDispatchProvider().start({serviceId:data.id,category:categorySlug||categoryId});return data.id}

export function useHugoVoice({role,accessToken,context,clientActions,onIntent}:VoiceOptions){
 const[state,setState]=useState<HugoVoiceState>('idle'),[error,setError]=useState(''),[userTranscript,setUserTranscript]=useState(''),[assistantTranscript,setAssistantTranscript]=useState('')
 const recognitionRef=useRef<any>(null),nativeModeRef=useRef(false),runningRef=useRef(false),busyRef=useRef(false),historyRef=useRef<ChatTurn[]>([]),roleRef=useRef(role),contextRef=useRef(context),tokenRef=useRef(accessToken),historyKeyRef=useRef(sessionKey(role,accessToken)),pendingActionRef=useRef<PendingAction|null>(null),localeRef=useRef<HugoLocale>(contextLocale(context)),orderRef=useRef<OrderDraft|null>(null)
 useEffect(()=>{roleRef.current=role},[role]);useEffect(()=>{contextRef.current=context;localeRef.current=contextLocale(context)},[context]);useEffect(()=>{tokenRef.current=accessToken},[accessToken]);useEffect(()=>{historyKeyRef.current=sessionKey(role,accessToken);historyRef.current=readHistory(historyKeyRef.current)},[role,accessToken])
 const startRecognition=useCallback(()=>{if(!runningRef.current||busyRef.current)return;if(nativeModeRef.current){try{getNativeBridge()?.startListening();setState('ready')}catch{}return}if(!recognitionRef.current)return;try{recognitionRef.current.lang=localeRef.current;recognitionRef.current.start();setState('ready')}catch{}},[])
 const speak=useCallback((text:string)=>new Promise<void>(resolve=>{const spoken=compactSpeech(text);if(!window.speechSynthesis){busyRef.current=false;if(runningRef.current)window.setTimeout(startRecognition,80);resolve();return}try{window.speechSynthesis.resume()}catch{}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(spoken);u.lang=localeRef.current;u.rate=1.08;u.pitch=1;u.onstart=()=>setState('speaking');u.onend=()=>{busyRef.current=false;if(runningRef.current){setState('ready');window.setTimeout(startRecognition,80)}resolve()};u.onerror=()=>{busyRef.current=false;if(runningRef.current)window.setTimeout(startRecognition,100);resolve()};window.speechSynthesis.speak(u)}),[startRecognition])
 const remember=useCallback((userText:string,reply:string)=>{const next=[...historyRef.current,{role:'user',content:userText},{role:'assistant',content:reply}] as ChatTurn[];historyRef.current=next.slice(-20);writeHistory(historyKeyRef.current,historyRef.current)},[])
 const say=useCallback(async(userText:string,reply:string)=>{remember(userText,reply);setAssistantTranscript(reply);await speak(reply)},[remember,speak])
 const promptOrder=useCallback(async(userText:string,draft:OrderDraft)=>{draft.step=nextOrderStep(draft);const pt=localeRef.current==='pt-BR';if(draft.step==='category'){await say(userText,pt?'Que tipo de profissional você precisa?':'¿Qué tipo de profesional necesitás?');return}if(draft.step==='description'){await say(userText,pt?'O que precisa ser feito?':'¿Qué hay que hacer?');return}if(draft.step==='address'){await say(userText,pt?'Não encontrei um endereço salvo para este serviço. Qual é o endereço?':'No encontré una dirección guardada para este servicio. ¿Cuál es la dirección?');return}if(draft.step==='when'){await say(userText,pt?'Quando você precisa? Agora, hoje ou outro momento?':'¿Cuándo lo necesitás? ¿Ahora, hoy o para otro momento?');return}const summary=pt?`Então ficou: ${draft.categoryHint}, ${draft.description}, em ${draft.address}, ${draft.whenLabel}. Confirmo e começo a busca?`:`Entonces queda: ${draft.categoryHint}, ${draft.description}, en ${draft.address}, ${draft.whenLabel}. ¿Confirmo y empiezo a buscar?`;await say(userText,summary)},[say])
 const handleOrder=useCallback(async(userText:string)=>{const draft=orderRef.current;if(!draft)return false;const pt=localeRef.current==='pt-BR';if(draft.step==='confirm'){if(negative(userText)){orderRef.current=null;await say(userText,COPY[localeRef.current].noChange);return true}if(!affirmative(userText)){await say(userText,pt?'Preciso de uma confirmação clara. Confirmo o pedido?':'Necesito una confirmación clara. ¿Confirmo el pedido?');return true}try{await createVoiceOrder(draft);orderRef.current=null;await say(userText,pt?'Pronto. O pedido foi criado e eu já comecei a busca.':'Listo. El pedido quedó creado y ya empecé a buscar un profesional.')}catch(e:any){await say(userText,pt?`Não consegui criar o pedido: ${e?.message||'erro'}.`:`No pude crear el pedido: ${e?.message||'error'}.`)}return true}
  if(draft.step==='location_consent'){if(negative(userText)){draft.step='address';await promptOrder(userText,draft);return true}if(!affirmative(userText)){await say(userText,pt?'Preciso de um sim para usar sua localização.':'Necesito un sí para usar tu ubicación actual.');return true}if(!navigator.geolocation){draft.step='address';await say(userText,pt?'Este dispositivo não oferece GPS. Me diga o endereço.':'Este dispositivo no ofrece GPS. Decime la dirección.');return true}busyRef.current=true;setState('connecting');await new Promise<void>(resolve=>navigator.geolocation.getCurrentPosition(async pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;draft.coords={lat,lng};draft.address=await reverseGeocode(lat,lng)||`Ubicación actual GPS ${lat.toFixed(6)}, ${lng.toFixed(6)}`;resolve()},()=>resolve(),{enableHighAccuracy:true,timeout:12000,maximumAge:30000}));if(!draft.address){draft.step='address';await say(userText,pt?'Não consegui obter sua localização. Me diga o endereço.':'No pude obtener tu ubicación. Decime la dirección.');return true}await promptOrder(userText,draft);return true}
  if(draft.step==='category'){const hint=requestedCategory(userText);if(!hint){await promptOrder(userText,draft);return true}await harvestOrderFacts(draft,userText);onIntent?.({text:userText,categoryHint:draft.categoryHint,urgent:draft.urgent,description:draft.description||null});if(!draft.address&&wantsCurrentLocation(userText)){draft.step='location_consent';await say(userText,pt?'Você me autoriza a usar sua localização atual?':'¿Me autorizás a usar tu ubicación actual?');return true}await promptOrder(userText,draft);return true}
  if(draft.step==='description'){const desc=problemDescriptionFrom(userText,draft.categoryHint)||userText.trim();if(desc.length<8){await say(userText,pt?'Me conte um pouco mais.':'Contame un poco más.');return true}draft.description=desc;await harvestOrderFacts(draft,userText,{description:false});onIntent?.({text:userText,categoryHint:draft.categoryHint,urgent:draft.urgent,description:draft.description});if(!draft.address&&wantsCurrentLocation(userText)){draft.step='location_consent';await say(userText,pt?'Você me autoriza a usar sua localização atual?':'¿Me autorizás a usar tu ubicación actual?');return true}await promptOrder(userText,draft);return true}
  if(draft.step==='address'){if(wantsCurrentLocation(userText)){draft.step='location_consent';await say(userText,pt?'Você me autoriza a usar sua localização atual?':'¿Me autorizás a usar tu ubicación actual?');return true}const alias=savedPlaceLabel(userText),saved=alias?await resolveSavedPlace(userText):null;if(saved)draft.address=saved.address;else if(alias){await say(userText,pt?'Não achei esse endereço salvo. Me diga o endereço completo.':'No encontré esa dirección guardada. Decime la dirección completa.');return true}else if(userText.trim().length>=5)draft.address=userText.trim();else{await promptOrder(userText,draft);return true}if(!draft.requestedWhen){const timing=parseTiming(userText);if(timing){draft.requestedWhen=timing.requestedWhen;draft.scheduleAt=timing.scheduleAt;draft.whenLabel=timing.whenLabel;draft.urgent=draft.urgent||timing.urgent}}await promptOrder(userText,draft);return true}
  if(draft.step==='when'){const timing=parseTiming(userText);if(!timing){await say(userText,pt?'Me diga quando: agora, hoje ou, por exemplo, amanhã à tarde.':'Decime cuándo: ahora, hoy o, por ejemplo, mañana por la tarde.');return true}draft.requestedWhen=timing.requestedWhen;draft.scheduleAt=timing.scheduleAt;draft.whenLabel=timing.whenLabel;draft.urgent=draft.urgent||timing.urgent;await promptOrder(userText,draft);return true}return false},[onIntent,promptOrder,say])
 const askHugo=useCallback(async(userText:string)=>{const token=tokenRef.current;if(!token)throw new Error('SESION_REQUERIDA');busyRef.current=true;setState('connecting');setError('');const explicit=explicitLocale(userText);if(explicit){localeRef.current=explicit;await say(userText,COPY[explicit].lang);return}localeRef.current=inferredLocale(userText,localeRef.current);if(roleRef.current==='client'&&orderRef.current){if(await handleOrder(userText))return}if(roleRef.current==='client'&&serviceRequestIntent(userText)&&!searchOnlyIntent(userText)){const urgent=urgencyFrom(userText),draft:OrderDraft={step:'category',categoryHint:null,categoryId:null,categorySlug:null,description:'',address:'',requestedWhen:null,scheduleAt:'',whenLabel:'',urgent,coords:null};await harvestOrderFacts(draft,userText);orderRef.current=draft;if(draft.categoryHint)onIntent?.({text:userText,categoryHint:draft.categoryHint,urgent:draft.urgent,description:draft.description||null});const pt=localeRef.current==='pt-BR';if(!draft.address&&wantsCurrentLocation(userText)){draft.step='location_consent';await say(userText,pt?'Você me autoriza a usar sua localização atual?':'¿Me autorizás a usar tu ubicación actual?');return}await promptOrder(userText,draft);return}if(roleRef.current==='client'){const pending=pendingActionRef.current;if(pending){if(affirmative(userText)){pendingActionRef.current=null;const copy=actionCopy(pending.action,localeRef.current),ok=await executeClientAction(pending.action,clientActions);await say(userText,ok?copy.success:COPY[localeRef.current].unavailable);return}if(negative(userText)){pendingActionRef.current=null;await say(userText,COPY[localeRef.current].noChange);return}pendingActionRef.current=null}const action=requestedAction(userText);if(action){pendingActionRef.current={action};await say(userText,actionCopy(action,localeRef.current).prompt);return}}
 const mergedContext=roleRef.current==='client'?`${CLIENT_BEHAVIOR} IDIOMA ACTUAL: ${localeRef.current}. CONTEXTO OPERATIVO REAL: ${contextRef.current}`:contextRef.current;let lastErr:any=null;for(let attempt=0;attempt<2;attempt++){try{const response=await fetch('/api/test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({message:userText,role:roleRef.current,context:mergedContext,history:historyRef.current.slice(-16)})}),data=await response.json().catch(()=>({})) as GeminiReply&{error?:string};if(!response.ok)throw Object.assign(new Error(data.error||`Hugo respondió ${response.status}`),{status:response.status});const raw=String(data.reply||'').trim();if(!raw)throw new Error('RESPUESTA_VACIA');const reply=roleRef.current==='client'?compactSpeech(raw):raw;remember(userText,reply);if(roleRef.current==='client')onIntent?.({text:userText,categoryHint:data.category_hint||null,urgent:Boolean(data.urgent),description:data.description||null});setAssistantTranscript(reply.slice(-500));await speak(reply);return}catch(e:any){lastErr=e;if(![429,502,503,504].includes(Number(e?.status)))break;await new Promise(r=>setTimeout(r,250))}}throw lastErr||new Error('Hugo no respondió')},[clientActions,handleOrder,onIntent,promptOrder,remember,say,speak])
 const sendText=useCallback(async(text:string)=>{const clean=text.trim();if(!clean)return;setUserTranscript(clean.slice(-900));try{await askHugo(clean)}catch{busyRef.current=false;setState('error');setError(COPY[localeRef.current].fallback)}},[askHugo])
 useEffect(()=>{const onState=(event:Event)=>{if(!runningRef.current)return;const s=String((event as CustomEvent<any>).detail?.state||'');if(s==='hearing'){try{window.speechSynthesis?.cancel()}catch{};busyRef.current=false;setState('hearing')}else if(s==='ready')setState('ready')};const onResult=(event:Event)=>{if(!runningRef.current)return;const d=(event as CustomEvent<any>).detail||{},text=String(d.text||'').trim();if(!text)return;setUserTranscript(text.slice(-900));if(d.final!==false)void sendText(text)};const onError=(event:Event)=>{if(!runningRef.current)return;const code=String((event as CustomEvent<any>).detail?.code||'');if(code==='no-speech'){window.setTimeout(startRecognition,160);return}runningRef.current=false;setError(code==='not-allowed'?COPY[localeRef.current].mic:code==='unavailable'?COPY[localeRef.current].noVoice:COPY[localeRef.current].voiceInterrupted);setState('error')};window.addEventListener('ugo:native-voice-state',onState);window.addEventListener('ugo:native-voice-result',onResult);window.addEventListener('ugo:native-voice-error',onError);return()=>{window.removeEventListener('ugo:native-voice-state',onState);window.removeEventListener('ugo:native-voice-result',onResult);window.removeEventListener('ugo:native-voice-error',onError)}},[sendText,startRecognition])
 const disconnect=useCallback(()=>{runningRef.current=false;busyRef.current=false;pendingActionRef.current=null;orderRef.current=null;try{recognitionRef.current?.abort?.()}catch{}try{getNativeBridge()?.stopListening()}catch{}try{window.speechSynthesis?.cancel()}catch{}recognitionRef.current=null;nativeModeRef.current=false;setState('idle');setError('');setUserTranscript('');setAssistantTranscript('')},[])
 useEffect(()=>disconnect,[disconnect])
 const connect=useCallback(async()=>{if(state!=='idle'&&state!=='error')return;if(!accessToken){setError('Iniciá sesión para hablar con Hugo.');setState('error');return}localeRef.current=contextLocale(contextRef.current);setState('connecting');setError('');historyRef.current=readHistory(historyKeyRef.current);pendingActionRef.current=null;orderRef.current=null;const welcome=historyRef.current.length?COPY[localeRef.current].resume:COPY[localeRef.current].heard,native=getNativeBridge();setAssistantTranscript(welcome);if(native){nativeModeRef.current=true;runningRef.current=true;try{native.startListening();return}catch{runningRef.current=false;nativeModeRef.current=false;setState('error');setError(COPY[localeRef.current].noVoice);return}}nativeModeRef.current=false;const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError(COPY[localeRef.current].noVoice);setState('error');return}try{await ensureMicrophoneAccess()}catch{setError(COPY[localeRef.current].mic);setState('error');return}runningRef.current=true;const recognition=new SR();recognition.lang=localeRef.current;recognition.continuous=false;recognition.interimResults=true;recognitionRef.current=recognition;recognition.onstart=()=>{if(runningRef.current&&!busyRef.current)setState('ready')};recognition.onspeechstart=()=>{if(runningRef.current){try{window.speechSynthesis?.cancel()}catch{};busyRef.current=false;setState('hearing')}};recognition.onresult=(event:any)=>{let text='',isFinal=false;for(let i=event.resultIndex||0;i<event.results.length;i++){const result=event.results[i];text+=String(result?.[0]?.transcript||'');if(result?.isFinal)isFinal=true}text=text.trim();if(!text||!runningRef.current)return;setUserTranscript(text.slice(-900));if(isFinal)void sendText(text)};recognition.onerror=(event:any)=>{if(!runningRef.current)return;const code=String(event?.error||'');if(code==='no-speech'||code==='aborted'){window.setTimeout(startRecognition,160);return}runningRef.current=false;setError(code==='not-allowed'?COPY[localeRef.current].mic:COPY[localeRef.current].voiceInterrupted);setState('error')};recognition.onend=()=>{if(runningRef.current&&!busyRef.current)window.setTimeout(startRecognition,90)};setState('ready');window.setTimeout(startRecognition,60)},[accessToken,sendText,startRecognition,state])
 return{state,error,userTranscript,assistantTranscript,transcript:assistantTranscript,active:state!=='idle'&&state!=='error',connect,disconnect,sendText}
}
