import { useCallback, useEffect, useRef, useState } from 'react'
import { getRoleSupabase } from '../lib/roleSupabase'
import { getDispatchProvider } from '../lib/dispatch/provider'

export type HugoVoiceState = 'idle' | 'connecting' | 'ready' | 'hearing' | 'speaking' | 'error'
type VoiceOptions = { role: 'client' | 'provider'; accessToken?: string; context: string }
type ChatTurn = { role: 'user' | 'assistant'; content: string }
type GeminiReply = { reply: string; action?: 'none'|'search_provider'|'prepare_request'; category_hint?: string|null; urgent?: boolean; description?: string|null; model?: string }
type NativeVoiceBridge={startListening:()=>void;stopListening:()=>void;isAvailable?:()=>boolean}
type VisibleCardReply={reply:string;categoryHint:string|null;selectedText?:string|null}
type ClientVoiceAction='hire_provider'|'create_request'|'pay'|'cancel'|'approve'|'dispute'
type PendingAction={action:ClientVoiceAction}
type HugoLocale='es-AR'|'pt-BR'
type OrderStep='category'|'description'|'address'|'location_consent'|'budget'|'confirm'
type OrderDraft={step:OrderStep;categoryHint:string|null;categoryId:string|null;categorySlug:string|null;description:string;address:string;amount:number|null;urgent:boolean;coords?:{lat:number;lng:number}|null}

const CLIENT_BEHAVIOR=[
 'Sos Hugo, asistente operativo de UGO Cliente, no un chatbot genérico.',
 'Hablá natural, cálido y directo. Respondé en el idioma preferido o en el idioma que use el cliente.',
 'Respondé normalmente en 1 o 2 frases cortas, fáciles de escuchar.',
 'Preguntá solamente el dato imprescindible que falta; no repitas datos ya conocidos.',
 'Si el usuario quiere pedir un servicio, guiá el pedido campo por campo: categoría, descripción del trabajo, ubicación/dirección y presupuesto. Confirmá antes de crear.',
 'Si pide usar su ubicación actual, pedí autorización primero y recién después solicitá GPS.',
 'Usá el historial para entender sí, dale, ese, el primero, o equivalentes en portugués, y las correcciones del usuario.',
 'Si cambia de intención o de tema, seguí el tema nuevo sin ejecutar una confirmación anterior.',
 'Nunca inventes proveedor, precio, reputación, ETA, pago, evidencia ni estado.',
 'La app y sus datos reales son la fuente de verdad.',
 'Buscar, filtrar, leer perfiles y mostrar estado no requieren confirmación.',
 'Contratar, crear definitivamente un pedido, pagar, cancelar, liberar pago o abrir disputa requieren confirmación explícita antes de ejecutar.',
].join(' ')

const COPY={
 'es-AR':{heard:'Te escucho.',resume:'Seguimos donde quedamos. Te escucho.',noChange:'Perfecto, no hago ningún cambio.',unavailable:'Esa acción no está disponible en este momento.',fallback:'No pude responder ahora, pero tu pedido sigue intacto.',mic:'Permití el micrófono para hablar con Hugo.',noVoice:'El reconocimiento de voz no está disponible en este dispositivo.',voiceInterrupted:'Se interrumpió el reconocimiento de voz.',lang:'Listo. Seguimos en español.',needConfirm:'Necesito una confirmación clara.'},
 'pt-BR':{heard:'Estou ouvindo.',resume:'Continuamos de onde paramos. Estou ouvindo.',noChange:'Perfeito, não vou fazer nenhuma alteração.',unavailable:'Essa ação não está disponível neste momento.',fallback:'Não consegui responder agora, mas seu pedido continua intacto.',mic:'Permita o microfone para falar com o Hugo.',noVoice:'O reconhecimento de voz não está disponível neste dispositivo.',voiceInterrupted:'O reconhecimento de voz foi interrompido.',lang:'Pronto. Continuamos em português.',needConfirm:'Preciso de uma confirmação clara.'},
} as const

function sessionKey(role:string,token?:string){let uid='anon';try{const payload=JSON.parse(atob(String(token||'').split('.')[1]?.replace(/-/g,'+').replace(/_/g,'/')||''));uid=String(payload?.sub||'anon')}catch{}return `ugo:hugo:history:${role}:${uid}`}
function readHistory(key:string):ChatTurn[]{try{const raw=sessionStorage.getItem(key);const value=raw?JSON.parse(raw):[];return Array.isArray(value)?value.slice(-20):[]}catch{return[]}}
function writeHistory(key:string,history:ChatTurn[]){try{sessionStorage.setItem(key,JSON.stringify(history.slice(-20)))}catch{}}
function getNativeBridge(){return (window as any).UGOVoiceBridge as NativeVoiceBridge|undefined}
async function ensureMicrophoneAccess(){if(!navigator.mediaDevices?.getUserMedia)return;const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.getTracks().forEach(track=>track.stop())}
function normalizeText(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}\s.,-]/gu,' ').replace(/\s+/g,' ').trim()}
function contextLocale(context:string):HugoLocale{const m=normalizeText(context);return /idioma preferido\s*:\s*(pt|pt br|portugues)/.test(m)?'pt-BR':'es-AR'}
function explicitLocale(text:string):HugoLocale|null{const m=normalizeText(text);if(/\b(fala|fale|responde|responda)\b.*\bportugues\b|\bem portugues\b/.test(m))return'pt-BR';if(/\b(habla|hablame|responde)\b.*\bespanol\b|\ben espanol\b/.test(m))return'es-AR';return null}
function inferredLocale(text:string,current:HugoLocale):HugoLocale{const m=normalizeText(text),pt=(m.match(/\b(quero|preciso|pode|voce|obrigado|servico|trabalho|encanador|jardineiro|chaveiro|agora|nao|sim|endereco)\b/g)||[]).length,es=(m.match(/\b(quiero|necesito|podes|puedes|vos|gracias|servicio|trabajo|plomero|jardinero|cerrajero|ahora|no|si|direccion)\b/g)||[]).length;if(pt>=2&&pt>es)return'pt-BR';if(es>=2&&es>pt)return'es-AR';return current}
function requestedCategory(text:string){const m=normalizeText(text);if(/\b(jardinero|jardinera|jardineria|jardin|jardineiro|jardinagem)\b/.test(m))return'jardineria';if(/\b(electricista|electricidad|electrico|electrica|eletricista|eletrica|eletrico)\b/.test(m))return'electricidad';if(/\b(plomero|plomera|plomeria|fontanero|fontaneria|encanador|encanamento)\b/.test(m))return'plomeria';if(/\b(limpieza|limpiador|limpiadora|faxina|limpeza|diarista)\b/.test(m))return'limpieza';if(/\b(pintor|pintora|pintura)\b/.test(m))return'pintura';if(/\b(cerrajero|cerrajeria|chaveiro)\b/.test(m))return'cerrajeria';return null}
function serviceRequestIntent(text:string){const m=normalizeText(text);return /\b(necesito|quiero pedir|quiero contratar|preciso|quero pedir|quero contratar|me hace falta|necesitaria|necesito que)\b/.test(m)}
function searchOnlyIntent(text:string){const m=normalizeText(text);return /\b(busca|buscame|buscar|mostrame|mostre|encontra|encontre|quienes hay|quem tem|disponibles|disponiveis)\b/.test(m)&&!serviceRequestIntent(text)}
function urgencyFrom(text:string){return /\b(urgente|urgencia|ahora mismo|ya mismo|hoje|agora|emergencia)\b/.test(normalizeText(text))}
function descriptionFrom(text:string,category:string|null){const clean=String(text||'').trim();if(clean.length<18)return'';const m=normalizeText(clean);if(category&&new RegExp(`^(necesito|quiero|preciso|quero)\\s+(un|una|um|uma)?\\s*${category}`).test(m)&&m.split(' ').length<5)return'';return clean}
function amountFrom(text:string){const m=normalizeText(text).match(/(?:r\$\s*)?(\d{2,5})(?:[.,]\d{1,2})?/);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)&&n>0?n:null}
function wantsCurrentLocation(text:string){return /\b(mi ubicacion actual|mi direccion actual|donde estoy|ubicacion de ahora|usar mi ubicacion|tomar mi ubicacion|toma mi ubicacion|minha localizacao atual|meu endereco atual|onde estou|usar minha localizacao|pegue minha localizacao)\b/.test(normalizeText(text))}
function ordinalIndex(text:string){const m=normalizeText(text);if(/\b(primero|primera|primeiro|primeira|1|uno|um)\b/.test(m))return 0;if(/\b(segundo|segunda|2|dos|dois|duas)\b/.test(m))return 1;if(/\b(tercero|tercera|terceiro|terceira|3|tres)\b/.test(m))return 2;return null}
function isShortReference(text:string){const m=normalizeText(text);return /^(ese|esa|esse|essa|el primero|la primera|o primeiro|a primeira|el segundo|la segunda|o segundo|a segunda|el tercero|la tercera|o terceiro|a terceira|primero|primeiro|segundo|tercero|terceiro)$/.test(m)}
function compactSpeech(text:string,max=320){const cleaned=String(text||'').replace(/[*_#`]/g,'').replace(/\s+/g,' ').trim();if(cleaned.length<=max)return cleaned;const cut=cleaned.slice(0,max);const end=Math.max(cut.lastIndexOf('. '),cut.lastIndexOf('? '),cut.lastIndexOf('! '));return (end>120?cut.slice(0,end+1):cut).trim()}
function providerCardNodes(){return Array.from(document.querySelectorAll<HTMLElement>('.ugo-feature-card,.ugo-provider-card'))}
function providerCards(){const nodes=providerCardNodes(),seen=new Set<string>();return nodes.map(node=>String(node.innerText||node.textContent||'').replace(/\s+/g,' ').trim()).filter(Boolean).filter(text=>{const key=normalizeText(text);if(seen.has(key))return false;seen.add(key);return true})}
function selectProviderReference(userText:string){const nodes=providerCardNodes(),ordinal=ordinalIndex(userText),m=normalizeText(userText);if(ordinal!=null&&nodes[ordinal]){nodes[ordinal].click();return true}const named=nodes.find(node=>{const text=normalizeText(String(node.innerText||node.textContent||''));const first=text.split(' ')[0];return first.length>2&&m.includes(first)});if(named){named.click();return true}return false}
function visibleProviderCardReply(userText:string,locale:HugoLocale):VisibleCardReply|null{const m=normalizeText(userText),category=requestedCategory(userText),ordinal=ordinalIndex(userText),lookup=/\b(busca|buscame|buscar|hay|encontra|encontre|procura|cerca|perto|disponible|disponivel|quien|quienes|quem|perfil|contame|conte|mostrame|mostre|lee|leeme)\b/.test(m)||isShortReference(userText);if(!category&&!lookup&&ordinal==null)return null;const cards=providerCards();if(!cards.length)return null;if(ordinal!=null&&cards[ordinal]){const selected=cards[ordinal];const which=locale==='pt-BR'?(ordinal===0?'primeiro':ordinal===1?'segundo':'terceiro'):(ordinal===0?'primero':ordinal===1?'segundo':'tercero');return{reply:locale==='pt-BR'?`Este é o ${which}: ${selected}.`:`Este es el ${which}: ${selected}.`,categoryHint:category,selectedText:selected}}let matches=cards.filter(text=>!category||normalizeText(text).includes(category));const named=cards.filter(text=>{const first=normalizeText(text).split(' ')[0];return first.length>2&&m.includes(first)});if(named.length)matches=named;if(!matches.length)return null;matches=matches.slice(0,3);if(matches.length===1)return{reply:locale==='pt-BR'?`Encontrei este profissional: ${matches[0]}.`:`Encontré este profesional: ${matches[0]}.`,categoryHint:category,selectedText:matches[0]};return{reply:locale==='pt-BR'?`Encontrei ${matches.length} opções. Vou te mostrar as melhores.`:`Encontré ${matches.length} opciones. Te muestro las mejores.`,categoryHint:category}}
function isVisible(el:HTMLElement){const style=window.getComputedStyle(el);return style.display!=='none'&&style.visibility!=='hidden'&&style.opacity!=='0'&&!el.hasAttribute('disabled')}
function clickByText(patterns:RegExp[],allowHidden=false){const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('button'));const target=buttons.find(button=>{const text=normalizeText(button.innerText||button.textContent||'');return (allowHidden||isVisible(button))&&patterns.some(p=>p.test(text))});if(!target)return false;target.click();return true}
function executeClientAction(action:ClientVoiceAction){if(action==='hire_provider'){const btn=document.querySelector<HTMLButtonElement>('.ugo-hire-button');if(btn&&isVisible(btn)){btn.click();return true}return false}if(action==='create_request')return clickByText([/confirmar y buscar profesional/,/enviar pedido/,/crear pedido/,/criar pedido/,/pedir servico/,/confirmar pedido/,/solicitar servico/]);if(action==='pay')return clickByText([/pagar con pix/,/pagar com pix/,/pagar servicio/,/pagar servico/,/^pagar r\$/,/^pagar$/]);if(action==='cancel')return clickByText([/cancelar pedido/,/cancelar servicio/,/cancelar servico/]);if(action==='approve')return clickByText([/estoy conforme/,/estou de acordo/,/aprobar y liberar pago/,/aprovar e liberar pagamento/,/liberar pago/,/liberar pagamento/]);if(action==='dispute'){const btn=document.querySelector<HTMLButtonElement>('.ugo-dispute-launch');if(btn){btn.click();return true}return clickByText([/abrir disputa/,/tengo un problema/,/tenho um problema/],true)}return false}
function affirmative(text:string){return /^(si|sim|dale|confirmo|confirmar|hacelo|faca|pode fazer|adelante|okey|okay|ok|de acuerdo|de acordo|correcto|correto)$/.test(normalizeText(text))}
function negative(text:string){return /^(no|nao|no gracias|nao obrigado|nao obrigada|cancelalo|cancela eso|cancele isso|dejalo|deja|deixe|melhor nao|mejor no)$/.test(normalizeText(text))}
function requestedAction(text:string):ClientVoiceAction|null{const m=normalizeText(text);if(/\b(contratalo|contratala|contratarlo|contratarla|contrata este|contrate ele|contratar esse|elegi este|escolha esse)\b/.test(m))return'hire_provider';if(/\b(enviar pedido|manda el pedido|mandalo|crear pedido|criar pedido|confirmar pedido|pedir el servicio|pedir o servico|envia o pedido)\b/.test(m))return'create_request';if(/\b(pagar|paga|pagalo|pague|pagar con pix|pagar com pix|hacer el pago|fazer o pagamento)\b/.test(m))return'pay';if(/\b(cancelar pedido|cancelar servicio|cancelar servico|cancela el pedido|cancele o pedido)\b/.test(m))return'cancel';if(/\b(estoy conforme|estou de acordo|estou conforme|libera el pago|liberar el pago|liberar pagamento|aproba el trabajo|aprovar o trabalho|todo quedo bien|ficou tudo certo)\b/.test(m))return'approve';if(/\b(abrir disputa|quiero una disputa|quero abrir uma disputa|tengo un problema|tenho um problema|no quedo bien|nao ficou bom|no estoy conforme|nao estou de acordo)\b/.test(m))return'dispute';return null}
function actionCopy(action:ClientVoiceAction,locale:HugoLocale){const pt=locale==='pt-BR';const map:Record<ClientVoiceAction,{prompt:string;success:string}>={hire_provider:{prompt:pt?'Confirma que quer contratar este profissional?':'¿Confirmás que querés contratar a este profesional?',success:pt?'Pronto. Abri o pedido com este profissional selecionado.':'Listo. Abrí el pedido con este profesional seleccionado.'},create_request:{prompt:pt?'Confirma que quer enviar este pedido?':'¿Confirmás que querés enviar este pedido?',success:pt?'Pronto. Enviei o pedido.':'Listo. Envié el pedido.'},pay:{prompt:pt?'Confirma que quer iniciar o pagamento deste serviço?':'¿Confirmás que querés iniciar el pago de este servicio?',success:pt?'Pronto. Abri o pagamento.':'Listo. Abrí el pago.'},cancel:{prompt:pt?'Confirma que quer cancelar este serviço?':'¿Confirmás que querés cancelar este servicio?',success:pt?'Pronto. Cancelei o serviço.':'Listo. Cancelé el servicio.'},approve:{prompt:pt?'Confirma que está de acordo e quer liberar o pagamento?':'¿Confirmás que estás conforme y querés liberar el pago?',success:pt?'Pronto. Aprovei o trabalho e liberei o pagamento.':'Listo. Aprobé el trabajo y liberé el pago.'},dispute:{prompt:pt?'Confirma que quer abrir uma disputa por este serviço?':'¿Confirmás que querés abrir una disputa por este servicio?',success:pt?'Pronto. Abri a disputa para você informar o problema.':'Listo. Abrí la disputa para que puedas informar el problema.'}};return map[action]}
async function reverseGeocode(lat:number,lng:number){try{const r=await fetch(`https://photon.komoot.io/reverse?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lng)}`,{headers:{accept:'application/json'}});const data:any=await r.json().catch(()=>null);const p=data?.features?.[0]?.properties||{};const parts=[p.name,p.street&&p.housenumber?`${p.street} ${p.housenumber}`:p.street,p.district,p.city,p.state].filter(Boolean);const unique=Array.from(new Set(parts.map(String)));return unique.join(', ')||null}catch{return null}}
async function resolveCategory(hint:string){const sb=getRoleSupabase('client');const{data,error}=await sb.from('categorias').select('id,slug,nombre').eq('activa',true);if(error)throw error;const h=normalizeText(hint);const row=(data||[]).find((c:any)=>{const slug=normalizeText(c.slug||''),name=normalizeText(c.nombre||'');return slug.includes(h)||h.includes(slug)||name.includes(h)||h.includes(name)});return row||null}
async function createVoiceOrder(draft:OrderDraft){const sb=getRoleSupabase('client');const{data:sess}=await sb.auth.getSession();const user=sess.session?.user;if(!user)throw new Error('Sesión requerida');let categoryId=draft.categoryId,categorySlug=draft.categorySlug;if(!categoryId&&draft.categoryHint){const cat=await resolveCategory(draft.categoryHint);categoryId=cat?.id||null;categorySlug=cat?.slug||null}if(!categoryId)throw new Error('No pude identificar la categoría');const metadata:any={source:'hugo-voice',demo:false,voice:true};if(draft.coords)metadata.client_location={latitude:draft.coords.lat,longitude:draft.coords.lng};const{data,error}=await sb.from('servicios').insert({cliente_id:user.id,categoria_id:categoryId,estado:'buscando',descripcion:draft.description,direccion_cliente:draft.address,tarifa:draft.amount,urgencia:draft.urgent,metadata}).select('id').single();if(error)throw error;const dispatch=getDispatchProvider();await dispatch.start({serviceId:data.id,category:categorySlug||categoryId});return data.id}

export function useHugoVoice({ role, accessToken, context }: VoiceOptions) {
 const[state,setState]=useState<HugoVoiceState>('idle'),[error,setError]=useState(''),[userTranscript,setUserTranscript]=useState(''),[assistantTranscript,setAssistantTranscript]=useState('')
 const recognitionRef=useRef<any>(null),nativeModeRef=useRef(false),runningRef=useRef(false),busyRef=useRef(false),historyRef=useRef<ChatTurn[]>([]),roleRef=useRef(role),contextRef=useRef(context),tokenRef=useRef(accessToken),historyKeyRef=useRef(sessionKey(role,accessToken)),lastCategoryRef=useRef<string|null>(null),pendingActionRef=useRef<PendingAction|null>(null),localeRef=useRef<HugoLocale>(contextLocale(context)),orderRef=useRef<OrderDraft|null>(null)
 useEffect(()=>{roleRef.current=role},[role]);useEffect(()=>{contextRef.current=context;localeRef.current=contextLocale(context)},[context]);useEffect(()=>{tokenRef.current=accessToken},[accessToken]);useEffect(()=>{historyKeyRef.current=sessionKey(role,accessToken);historyRef.current=readHistory(historyKeyRef.current)},[role,accessToken])
 const startRecognition=useCallback(()=>{if(!runningRef.current||busyRef.current)return;if(nativeModeRef.current){try{getNativeBridge()?.startListening();setState('ready')}catch{}return}if(!recognitionRef.current)return;try{recognitionRef.current.lang=localeRef.current;recognitionRef.current.start();setState('ready')}catch{}},[])
 const speak=useCallback((text:string)=>new Promise<void>(resolve=>{const spoken=compactSpeech(text);if(!window.speechSynthesis){busyRef.current=false;if(runningRef.current)window.setTimeout(startRecognition,80);resolve();return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(spoken);u.lang=localeRef.current;u.rate=1.1;u.pitch=1;u.onstart=()=>setState('speaking');u.onend=()=>{busyRef.current=false;if(runningRef.current){setState('ready');window.setTimeout(startRecognition,80)}resolve()};u.onerror=()=>{busyRef.current=false;if(runningRef.current)window.setTimeout(startRecognition,100);resolve()};window.speechSynthesis.speak(u)}),[startRecognition])
 const remember=useCallback((userText:string,reply:string)=>{const next=[...historyRef.current,{role:'user',content:userText},{role:'assistant',content:reply}] as ChatTurn[];historyRef.current=next.slice(-20);writeHistory(historyKeyRef.current,historyRef.current)},[])
 const say=useCallback(async(userText:string,reply:string)=>{remember(userText,reply);setAssistantTranscript(reply);await speak(reply)},[remember,speak])
 const handleOrder=useCallback(async(userText:string)=>{const draft=orderRef.current;if(!draft)return false;const pt=localeRef.current==='pt-BR';if(draft.step==='category'){const hint=requestedCategory(userText);if(!hint){await say(userText,pt?'Que tipo de profissional você precisa? Por exemplo, eletricista, jardineiro ou encanador.':'¿Qué tipo de profesional necesitás? Por ejemplo electricista, jardinero o plomero.');return true}const cat=await resolveCategory(hint);draft.categoryHint=hint;draft.categoryId=cat?.id||null;draft.categorySlug=cat?.slug||null;draft.step='description';window.dispatchEvent(new CustomEvent('ugo:hugo-ai-intent',{detail:{text:userText,action:'prepare_request',categoryHint:hint,urgent:draft.urgent,description:null}}));await say(userText,pt?'Perfeito. O que exatamente precisa ser feito?':'Perfecto. ¿Qué trabajo necesitás hacer exactamente?');return true}
 if(draft.step==='description'){if(userText.trim().length<8){await say(userText,pt?'Me conte um pouco mais sobre o trabalho.':'Contame un poco más sobre el trabajo.');return true}draft.description=userText.trim();draft.step='address';window.dispatchEvent(new CustomEvent('ugo:hugo-ai-intent',{detail:{text:userText,action:'prepare_request',categoryHint:draft.categoryHint,urgent:draft.urgent,description:draft.description}}));await say(userText,pt?'Em que endereço é o serviço? Você também pode dizer “use minha localização atual”.':'¿En qué dirección es el servicio? También podés decir “usá mi ubicación actual”.');return true}
 if(draft.step==='address'){if(wantsCurrentLocation(userText)){draft.step='location_consent';await say(userText,pt?'Você me autoriza a usar sua localização atual para este pedido?':'¿Me autorizás a usar tu ubicación actual para este pedido?');return true}draft.address=userText.trim();draft.step='budget';await say(userText,pt?'Qual orçamento você quer colocar, em reais?':'¿Qué presupuesto querés poner, en reales?');return true}
 if(draft.step==='location_consent'){if(negative(userText)){draft.step='address';await say(userText,pt?'Tudo bem. Me diga o endereço do serviço.':'Está bien. Decime la dirección del servicio.');return true}if(!affirmative(userText)){await say(userText,pt?'Preciso de um “sim” para usar sua localização atual.':'Necesito un “sí” para usar tu ubicación actual.');return true}if(!navigator.geolocation){draft.step='address';await say(userText,pt?'Este dispositivo não oferece GPS. Me diga o endereço.':'Este dispositivo no ofrece GPS. Decime la dirección.');return true}busyRef.current=true;setState('connecting');await new Promise<void>(resolve=>navigator.geolocation.getCurrentPosition(async pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;draft.coords={lat,lng};const address=await reverseGeocode(lat,lng);draft.address=address||`Ubicación actual GPS ${lat.toFixed(6)}, ${lng.toFixed(6)}`;try{const sb=getRoleSupabase('client');const{data:sess}=await sb.auth.getSession();const uid=sess.session?.user?.id;if(uid){await sb.from('usuarios').update({lat,lng}).eq('id',uid);await (sb as any).from('perfiles_cliente').update({ubicacion:`POINT(${lng} ${lat})`}).eq('usuario_id',uid)}}catch{}draft.step='budget';resolve()},()=>{draft.step='address';resolve()},{enableHighAccuracy:true,timeout:12000,maximumAge:30000}));if(draft.step==='address'){await say(userText,pt?'Não consegui obter sua localização. Me diga o endereço do serviço.':'No pude obtener tu ubicación. Decime la dirección del servicio.');return true}await say(userText,pt?`Localização definida: ${draft.address}. Qual orçamento você quer colocar, em reais?`:`Ubicación definida: ${draft.address}. ¿Qué presupuesto querés poner, en reales?`);return true}
 if(draft.step==='budget'){const amount=amountFrom(userText);if(!amount){await say(userText,pt?'Me diga um valor em reais, por exemplo 120.':'Decime un valor en reales, por ejemplo 120.');return true}draft.amount=amount;draft.step='confirm';const summary=pt?`Resumo: ${draft.categoryHint}, ${draft.description}, em ${draft.address}, orçamento de R$ ${amount}. Confirma o pedido?`:`Resumen: ${draft.categoryHint}, ${draft.description}, en ${draft.address}, presupuesto de R$ ${amount}. ¿Confirmás el pedido?`;await say(userText,summary);return true}
 if(draft.step==='confirm'){if(negative(userText)){orderRef.current=null;await say(userText,COPY[localeRef.current].noChange);return true}if(!affirmative(userText)){await say(userText,pt?'Preciso de uma confirmação clara. Confirma o pedido?':'Necesito una confirmación clara. ¿Confirmás el pedido?');return true}try{const id=await createVoiceOrder(draft);orderRef.current=null;await say(userText,pt?`Pronto. Pedido criado e enviado para busca. Serviço ${id}.`:`Listo. Pedido creado y enviado a búsqueda. Servicio ${id}.`)}catch(e:any){await say(userText,pt?`Não consegui criar o pedido: ${e?.message||'erro desconhecido'}.`:`No pude crear el pedido: ${e?.message||'error desconocido'}.`)}return true}return false},[say])
 const askHugo=useCallback(async(userText:string)=>{const token=tokenRef.current;if(!token)throw new Error('SESION_REQUERIDA');busyRef.current=true;setState('connecting');setError('');const explicit=explicitLocale(userText);if(explicit){localeRef.current=explicit;await say(userText,COPY[explicit].lang);return}localeRef.current=inferredLocale(userText,localeRef.current);if(roleRef.current==='client')window.dispatchEvent(new CustomEvent('ugo:hugo-user-text',{detail:{text:userText}}));if(roleRef.current==='client'&&orderRef.current){const handled=await handleOrder(userText);if(handled)return}
 if(roleRef.current==='client'&&serviceRequestIntent(userText)&&!searchOnlyIntent(userText)){const hint=requestedCategory(userText),desc=descriptionFrom(userText,hint),urgent=urgencyFrom(userText);orderRef.current={step:hint?(desc?'address':'description'):'category',categoryHint:hint,categoryId:null,categorySlug:null,description:desc,address:'',amount:null,urgent,coords:null};if(hint){const cat=await resolveCategory(hint);if(orderRef.current){orderRef.current.categoryId=cat?.id||null;orderRef.current.categorySlug=cat?.slug||null}window.dispatchEvent(new CustomEvent('ugo:hugo-ai-intent',{detail:{text:userText,action:'prepare_request',categoryHint:hint,urgent,description:desc||null}}))}const pt=localeRef.current==='pt-BR';if(!hint){await say(userText,pt?'Claro. Que tipo de profissional você precisa?':'Claro. ¿Qué tipo de profesional necesitás?');return}if(!desc){await say(userText,pt?'O que exatamente precisa ser feito?':'¿Qué trabajo necesitás hacer exactamente?');return}await say(userText,pt?'Em que endereço é o serviço? Você também pode dizer “use minha localização atual”.':'¿En qué dirección es el servicio? También podés decir “usá mi ubicación actual”.');return}
 if(roleRef.current==='client'){const pending=pendingActionRef.current;if(pending){if(affirmative(userText)){pendingActionRef.current=null;const copy=actionCopy(pending.action,localeRef.current),ok=executeClientAction(pending.action);await say(userText,ok?copy.success:COPY[localeRef.current].unavailable);return}if(negative(userText)){pendingActionRef.current=null;await say(userText,COPY[localeRef.current].noChange);return}const replacement=requestedAction(userText);if(replacement&&replacement!==pending.action){pendingActionRef.current={action:replacement};await say(userText,actionCopy(replacement,localeRef.current).prompt);return}pendingActionRef.current=null}
 const action=requestedAction(userText);if(action){pendingActionRef.current={action};await say(userText,actionCopy(action,localeRef.current).prompt);return}await new Promise(resolve=>window.setTimeout(resolve,70));const category=requestedCategory(userText);if(category)lastCategoryRef.current=category;if(isShortReference(userText)||ordinalIndex(userText)!=null)selectProviderReference(userText);const visible=visibleProviderCardReply(userText,localeRef.current);if(visible){const reply=compactSpeech(visible.reply);remember(userText,reply);window.dispatchEvent(new CustomEvent('ugo:hugo-ai-intent',{detail:{text:userText,action:'search_provider',categoryHint:visible.categoryHint||lastCategoryRef.current,urgent:false,description:null,selectedText:visible.selectedText||null}}));setAssistantTranscript(reply);await speak(reply);return}}
 const mergedContext=roleRef.current==='client'?`${CLIENT_BEHAVIOR} IDIOMA ACTUAL: ${localeRef.current}. CONTEXTO OPERATIVO REAL: ${contextRef.current}`:contextRef.current;let lastErr:any=null;for(let attempt=0;attempt<2;attempt++){try{const response=await fetch('/api/test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({message:userText,role:roleRef.current,context:mergedContext,history:historyRef.current.slice(-16)})});const data=await response.json().catch(()=>({})) as GeminiReply&{error?:string};if(!response.ok)throw Object.assign(new Error(data.error||`Hugo respondió ${response.status}`),{status:response.status});const raw=String(data.reply||'').trim();if(!raw)throw new Error('RESPUESTA_VACIA');const reply=roleRef.current==='client'?compactSpeech(raw):raw;remember(userText,reply);if(roleRef.current==='client'){if(data.category_hint)lastCategoryRef.current=data.category_hint;window.dispatchEvent(new CustomEvent('ugo:hugo-ai-intent',{detail:{text:userText,action:data.action||'none',categoryHint:data.category_hint||lastCategoryRef.current,urgent:Boolean(data.urgent),description:data.description||null}}))}setAssistantTranscript(reply.slice(-500));await speak(reply);return}catch(e:any){lastErr=e;if(![429,502,503,504].includes(Number(e?.status)))break;await new Promise(r=>setTimeout(r,250))}}throw lastErr||new Error('Hugo no respondió')},[handleOrder,remember,say,speak])
 useEffect(()=>{const onState=(event:Event)=>{if(!runningRef.current)return;const s=String((event as CustomEvent<any>).detail?.state||'');if(s==='hearing'){try{window.speechSynthesis?.cancel()}catch{};busyRef.current=false;setState('hearing')}else if(s==='ready')setState('ready')};const onResult=async(event:Event)=>{if(!runningRef.current)return;const d=(event as CustomEvent<any>).detail||{},text=String(d.text||'').trim();if(!text)return;setUserTranscript(text.slice(-900));if(!d.final)return;try{await askHugo(text)}catch{busyRef.current=false;const fallback=COPY[localeRef.current].fallback;setAssistantTranscript(fallback);if(runningRef.current)window.setTimeout(startRecognition,160)}};const onError=(event:Event)=>{if(!runningRef.current)return;const code=String((event as CustomEvent<any>).detail?.code||'');if(code==='no-speech'){window.setTimeout(startRecognition,160);return}runningRef.current=false;setError(code==='not-allowed'?COPY[localeRef.current].mic:code==='unavailable'?COPY[localeRef.current].noVoice:COPY[localeRef.current].voiceInterrupted);setState('error')};window.addEventListener('ugo:native-voice-state',onState);window.addEventListener('ugo:native-voice-result',onResult);window.addEventListener('ugo:native-voice-error',onError);return()=>{window.removeEventListener('ugo:native-voice-state',onState);window.removeEventListener('ugo:native-voice-result',onResult);window.removeEventListener('ugo:native-voice-error',onError)}},[askHugo,startRecognition])
 const disconnect=useCallback(()=>{runningRef.current=false;busyRef.current=false;pendingActionRef.current=null;orderRef.current=null;try{recognitionRef.current?.abort?.()}catch{}try{getNativeBridge()?.stopListening()}catch{}try{window.speechSynthesis?.cancel()}catch{}recognitionRef.current=null;nativeModeRef.current=false;setState('idle');setError('');setUserTranscript('');setAssistantTranscript('')},[])
 useEffect(()=>disconnect,[disconnect])
 const connect=useCallback(async()=>{if(state!=='idle'&&state!=='error')return;if(!accessToken){setError('Iniciá sesión para hablar con Hugo.');setState('error');return}localeRef.current=contextLocale(contextRef.current);setState('connecting');setError('');setUserTranscript('');setAssistantTranscript('');historyRef.current=readHistory(historyKeyRef.current);pendingActionRef.current=null;orderRef.current=null;const welcome=historyRef.current.length?COPY[localeRef.current].resume:COPY[localeRef.current].heard;const native=getNativeBridge();if(native){nativeModeRef.current=true;runningRef.current=true;setAssistantTranscript(welcome);try{native.startListening();return}catch{runningRef.current=false;nativeModeRef.current=false;setState('error');setError(COPY[localeRef.current].noVoice);return}}nativeModeRef.current=false;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setError(COPY[localeRef.current].noVoice);setState('error');return}try{await ensureMicrophoneAccess()}catch{setError(COPY[localeRef.current].mic);setState('error');return}runningRef.current=true;const recognition=new SR();recognition.lang=localeRef.current;recognition.continuous=false;recognition.interimResults=true;recognitionRef.current=recognition;recognition.onstart=()=>{if(runningRef.current&&!busyRef.current)setState('ready')};recognition.onspeechstart=()=>{if(runningRef.current){try{window.speechSynthesis?.cancel()}catch{};busyRef.current=false;setState('hearing')}};recognition.onresult=async(event:any)=>{let text='',isFinal=false;for(let i=event.resultIndex||0;i<event.results.length;i++){const result=event.results[i];text+=String(result?.[0]?.transcript||'');if(result?.isFinal)isFinal=true}text=text.trim();if(!text||!runningRef.current)return;setUserTranscript(text.slice(-900));if(!isFinal)return;try{await askHugo(text)}catch{busyRef.current=false;setAssistantTranscript(COPY[localeRef.current].fallback);if(runningRef.current)window.setTimeout(startRecognition,160)}};recognition.onerror=(event:any)=>{if(!runningRef.current)return;const code=String(event?.error||'');if(code==='no-speech'||code==='aborted'){window.setTimeout(startRecognition,160);return}runningRef.current=false;setError(code==='not-allowed'?COPY[localeRef.current].mic:COPY[localeRef.current].voiceInterrupted);setState('error')};recognition.onend=()=>{if(runningRef.current&&!busyRef.current)window.setTimeout(startRecognition,90)};setAssistantTranscript(welcome);setState('ready');window.setTimeout(startRecognition,60)},[accessToken,askHugo,startRecognition,state])
 return{state,error,userTranscript,assistantTranscript,transcript:assistantTranscript,active:state!=='idle'&&state!=='error',connect,disconnect}
}
