import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {getRoleSupabase} from '../lib/roleSupabase'
import type{Service} from './shared'
import type{HugoVoiceState} from './useHugoVoice'

type Props={accessToken?:string;context:string;service?:Service|null;availableOffers?:number}
type Turn={role:'user'|'assistant';content:string}
type Action='accept'|'reject'|'go'|'arrive'|'start'|'finish'|'online'|'offline'
type Locale='es-AR'|'pt-BR'

const normalize=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim()
const yes=(v:string)=>/^(si|sim|dale|confirmo|confirmar|hacelo|faca|pode fazer|ok|okay|de acuerdo|de acordo|correcto|correto)$/.test(normalize(v))
const no=(v:string)=>/^(no|nao|mejor no|melhor nao|dejalo|deixe|cancelar|cancela)$/.test(normalize(v))
const compact=(v:string)=>{const t=v.replace(/[*_#`]/g,'').replace(/\s+/g,' ').trim();return t.length<=320?t:t.slice(0,317)+'…'}
function langFrom(text:string,current:Locale){const m=normalize(text);if(/\b(portugues|portuguese)\b/.test(m))return'pt-BR';if(/\b(espanol|castellano)\b/.test(m))return'es-AR';const pt=(m.match(/\b(quero|preciso|voce|agora|trabalho|servico|cheguei|aceito|rejeitar|finalizei|foto|evidencia)\b/g)||[]).length;const es=(m.match(/\b(quiero|necesito|ahora|trabajo|servicio|llegue|acepto|rechazar|termine|foto|evidencia)\b/g)||[]).length;return pt>=2&&pt>es?'pt-BR':es>=2&&es>pt?'es-AR':current}
function visible(el:HTMLElement){const s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&!el.hasAttribute('disabled')}
function clickText(patterns:RegExp[]){const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('button'));const button=buttons.find(b=>visible(b)&&patterns.some(p=>p.test(normalize(b.innerText||b.textContent||''))));if(!button)return false;button.click();return true}
function requestAction(text:string):Action|null{const m=normalize(text);if(/\b(acepto|aceptar trabajo|aceptar pedido|aceita|aceito|aceitar trabalho)\b/.test(m))return'accept';if(/\b(rechazo|rechazalo|rechazar trabajo|rejeito|rejeitar|recusar)\b/.test(m))return'reject';if(/\b(salir al cliente|salir hacia el cliente|ir al cliente|navegar al cliente|voy al cliente|ir para o cliente|navegar para o cliente)\b/.test(m))return'go';if(/\b(ya llegue|llegue al cliente|marcar llegada|cheguei|ja cheguei)\b/.test(m))return'arrive';if(/\b(iniciar servicio|empezar trabajo|empezar servicio|ya puedo empezar|iniciar trabalho|comecar trabalho|iniciar servico)\b/.test(m))return'start';if(/\b(termine|terminar trabajo|finalizar trabajo|finalizar servicio|enviar al cliente|terminei|finalizar trabalho|finalizar servico)\b/.test(m))return'finish';if(/\b(ponerme online|poneme online|activar online|ficar online|me colocar online)\b/.test(m))return'online';if(/\b(ponerme offline|dejame offline|salir de online|ficar offline|me colocar offline)\b/.test(m))return'offline';return null}
function prompt(action:Action,locale:Locale){const pt=locale==='pt-BR';const map:Record<Action,string>={accept:pt?'Confirma que quer aceitar este trabalho?':'¿Confirmás que querés aceptar este trabajo?',reject:pt?'Confirma que quer rejeitar este trabalho?':'¿Confirmás que querés rechazar este trabajo?',go:pt?'Confirma que quer iniciar o trajeto até o cliente?':'¿Confirmás que querés salir hacia el cliente?',arrive:pt?'Confirma que chegou e quer marcar a chegada?':'¿Confirmás que llegaste y querés marcar la llegada?',start:pt?'Confirma que quer iniciar o serviço agora?':'¿Confirmás que querés iniciar el servicio ahora?',finish:pt?'Confirma que terminou e quer enviar o trabalho para revisão do cliente?':'¿Confirmás que terminaste y querés enviarlo a revisión del cliente?',online:pt?'Confirma que quer ficar Online para receber trabalhos?':'¿Confirmás que querés ponerte Online para recibir trabajos?',offline:pt?'Confirma que quer ficar Offline?':'¿Confirmás que querés ponerte Offline?'};return map[action]}
function success(action:Action,locale:Locale){const pt=locale==='pt-BR';const map:Record<Action,string>={accept:pt?'Pronto. O trabalho foi aceito. Agora aguardamos a proteção do pagamento antes de sair.':'Listo. Trabajo aceptado. Ahora esperamos la protección del pago antes de salir.',reject:pt?'Pronto. A oferta foi rejeitada.':'Listo. Oferta rechazada.',go:pt?'Pronto. Você está a caminho do cliente.':'Listo. Estás en camino al cliente.',arrive:pt?'Pronto. Chegada confirmada. Agora revise a evidência Antes antes de começar.':'Listo. Llegada confirmada. Ahora revisá la evidencia Antes antes de empezar.',start:pt?'Pronto. Serviço iniciado.':'Listo. Servicio iniciado.',finish:pt?'Pronto. O trabalho foi enviado para revisão do cliente.':'Listo. El trabajo fue enviado a revisión del cliente.',online:pt?'Pronto. Você está Online.':'Listo. Estás Online.',offline:pt?'Pronto. Você está Offline.':'Listo. Estás Offline.'};return map[action]}
function actionAllowed(action:Action,service?:Service|null,offers=0){if(action==='accept'||action==='reject')return !service&&offers>0;if(action==='go')return service?.estado==='asignado';if(action==='arrive')return service?.estado==='en_camino';if(action==='start')return service?.estado==='llegado';if(action==='finish')return service?.estado==='en_progreso';return true}
function execute(action:Action){if(action==='accept')return clickText([/^aceptar trabajo$/,/^aceitar trabalho$/]);if(action==='reject')return clickText([/^rechazar$/,/^rejeitar$/,/^recusar$/]);if(action==='go')return clickText([/^navegar al cliente$/,/^navegar para o cliente$/]);if(action==='arrive')return clickText([/^llegue al cliente$/,/^cheguei ao cliente$/]);if(action==='start')return clickText([/^iniciar servicio$/,/^iniciar servico$/]);if(action==='finish')return clickText([/^finalizar y pedir aprobacion$/,/^finalizar e pedir aprovacao$/]);if(action==='online'){const b=Array.from(document.querySelectorAll<HTMLButtonElement>('.ugo-provider-online')).find(visible);if(!b)return false;if(/offline/.test(normalize(b.innerText)))b.click();return true}if(action==='offline'){const b=Array.from(document.querySelectorAll<HTMLButtonElement>('.ugo-provider-online')).find(visible);if(!b)return false;if(/online/.test(normalize(b.innerText)))b.click();return true}return false}

export function useProviderHugoVoice({accessToken,context,service,availableOffers=0}:Props){
 const[state,setState]=useState<HugoVoiceState>('idle'),[error,setError]=useState(''),[userTranscript,setUserTranscript]=useState(''),[assistantTranscript,setAssistantTranscript]=useState('')
 const running=useRef(false),busy=useRef(false),recognition=useRef<any>(null),pending=useRef<Action|null>(null),history=useRef<Turn[]>([]),locale=useRef<Locale>('es-AR'),serviceRef=useRef(service),offersRef=useRef(availableOffers),contextRef=useRef(context)
 useEffect(()=>{serviceRef.current=service},[service]);useEffect(()=>{offersRef.current=availableOffers},[availableOffers]);useEffect(()=>{contextRef.current=context},[context])
 const start=useCallback(()=>{if(!running.current||busy.current||!recognition.current)return;try{recognition.current.lang=locale.current;recognition.current.start();setState('ready')}catch{}},[])
 const speak=useCallback((text:string)=>new Promise<void>(resolve=>{const out=compact(text);setAssistantTranscript(out);if(!window.speechSynthesis){busy.current=false;setTimeout(start,80);resolve();return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(out);u.lang=locale.current;u.rate=1.08;u.onstart=()=>setState('speaking');u.onend=()=>{busy.current=false;if(running.current)setTimeout(start,90);resolve()};u.onerror=()=>{busy.current=false;if(running.current)setTimeout(start,120);resolve()};window.speechSynthesis.speak(u)}),[start])
 const remember=(u:string,a:string)=>{history.current=[...history.current,{role:'user',content:u},{role:'assistant',content:a}].slice(-20)}
 const say=useCallback(async(u:string,a:string)=>{remember(u,a);await speak(a)},[speak])
 const evidenceStatus=useCallback(async()=>{if(!serviceRef.current)return{antes:false,durante:false,despues:false};const sb=getRoleSupabase('provider');const{data}=await(sb as any).from('evidencias_servicio').select('tipo').eq('servicio_id',serviceRef.current.id);const kinds=new Set((data||[]).map((r:any)=>r.tipo));return{antes:kinds.has('antes'),durante:kinds.has('durante'),despues:kinds.has('despues')}},[])
 const nextStep=useCallback(async()=>{const s=serviceRef.current,pt=locale.current==='pt-BR';if(!s){if(offersRef.current>0)return pt?`Você tem ${offersRef.current} oferta pendente. Revise o pedido e decida se aceita ou rejeita.`:`Tenés ${offersRef.current} oferta pendiente. Revisá el pedido y decidí si aceptás o rechazás.`;return pt?'Você não tem serviço ativo. Fique Online se quiser receber oportunidades.':'No tenés servicio activo. Ponete Online si querés recibir oportunidades.'}if(s.estado==='asignado')return pt?'O serviço está atribuído. Aguarde o pagamento protegido; depois você poderá sair para o cliente.':'El servicio está asignado. Esperá el pago protegido; después vas a poder salir hacia el cliente.';if(s.estado==='en_camino')return pt?'Você está a caminho. O próximo passo é chegar e confirmar a chegada.':'Estás en camino. El próximo paso es llegar y confirmar la llegada.';if(s.estado==='llegado'){const e=await evidenceStatus();return e.antes?(pt?'A evidência Antes já está registrada. Você pode iniciar o serviço quando estiver pronto.':'La evidencia Antes ya está registrada. Podés iniciar el servicio cuando estés listo.'):(pt?'Você já chegou. Antes de começar, registre a evidência Antes.':'Ya llegaste. Antes de empezar, registrá la evidencia Antes.')}if(s.estado==='en_progreso'){const e=await evidenceStatus();return e.despues?(pt?'O trabalho está em andamento e a evidência Depois já existe. Quando terminar, você pode enviar para revisão.':'El trabajo está en curso y ya existe evidencia Después. Cuando termines, podés enviarlo a revisión.'):(pt?'O trabalho está em andamento. Antes de finalizar, você precisa registrar a evidência Depois.':'El trabajo está en curso. Antes de finalizar necesitás registrar la evidencia Después.')}if(s.estado==='esperando_aprobacion')return pt?'O cliente está revisando o trabalho. Agora é só aguardar a decisão.':'El cliente está revisando el trabajo. Ahora corresponde esperar su decisión.';return pt?'Vou usar o estado real do serviço para te orientar.':'Voy a usar el estado real del servicio para orientarte.'},[evidenceStatus])
 const handle=useCallback(async(text:string)=>{busy.current=true;setState('connecting');locale.current=langFrom(text,locale.current);const m=normalize(text),pt=locale.current==='pt-BR';if(/\b(que hago ahora|que sigue|necesito ayuda|ayudame|o que faco agora|o que vem agora|preciso de ajuda|me ajuda)\b/.test(m)){const answer=await nextStep();await say(text,answer);return}if(/\b(que foto me falta|me falta alguna foto|que evidencia falta|qual foto falta|falta alguma foto|qual evidencia falta)\b/.test(m)){const e=await evidenceStatus();const missing=['antes','durante','despues'].filter(k=>!(e as any)[k]);const answer=!serviceRef.current?(pt?'Não há serviço ativo.':'No hay servicio activo.'):(missing.length?pt?`Ainda faltam: ${missing.join(', ')}.`:`Todavía faltan: ${missing.join(', ')}.`:pt?'As evidências Antes, Durante e Depois já estão registradas.':'Las evidencias Antes, Durante y Después ya están registradas.');await say(text,answer);return}const ev=/\b(foto de antes|evidencia antes|foto antes)\b/.test(m)?'antes':/\b(foto durante|evidencia durante)\b/.test(m)?'durante':/\b(foto de despues|foto despues|evidencia despues|foto depois|evidencia depois)\b/.test(m)?'despues':null;if(ev){window.dispatchEvent(new CustomEvent('ugo:provider-evidence-open',{detail:{kind:ev}}));await say(text,pt?`Abri as evidências em ${ev}. Toque em “Tirar ou escolher foto” para usar a câmera.`:`Abrí Evidencias en ${ev}. Tocá “Tomar o elegir foto” para usar la cámara.`);return}
 if(pending.current){if(yes(text)){const action=pending.current;pending.current=null;if(!actionAllowed(action,serviceRef.current,offersRef.current)){await say(text,pt?'Essa ação já não corresponde ao estado atual. Vou atualizar o próximo passo.':'Esa acción ya no corresponde al estado actual. Voy a actualizar el siguiente paso.');return}const ok=execute(action);await say(text,ok?success(action,locale.current):(pt?'Não encontrei a ação disponível na tela. Não alterei nada.':'No encontré la acción disponible en pantalla. No cambié nada.'));return}if(no(text)){pending.current=null;await say(text,pt?'Perfeito. Não alterei nada.':'Perfecto. No cambié nada.');return}const replacement=requestAction(text);if(replacement){if(!actionAllowed(replacement,serviceRef.current,offersRef.current)){pending.current=null;await say(text,pt?'Essa ação não corresponde ao estado atual do serviço.':'Esa acción no corresponde al estado actual del servicio.');return}pending.current=replacement;await say(text,prompt(replacement,locale.current));return}pending.current=null}
 const action=requestAction(text);if(action){if(!actionAllowed(action,serviceRef.current,offersRef.current)){await say(text,pt?'Essa ação não corresponde ao estado atual. Pergunte “o que faço agora?” e eu te digo o próximo passo.':'Esa acción no corresponde al estado actual. Preguntame “¿qué hago ahora?” y te digo el próximo paso.');return}pending.current=action;await say(text,prompt(action,locale.current));return}
 if(!accessToken){await say(text,pt?'Sua sessão não está disponível.':'Tu sesión no está disponible.');return}try{const response=await fetch('/api/test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({message:text,role:'provider',context:contextRef.current,history:history.current.slice(-12)})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||'Hugo no respondió');await say(text,compact(String(data?.reply||'')))}catch{await say(text,pt?'Não consegui responder agora, mas não alterei o serviço.':'No pude responder ahora, pero no cambié el servicio.')}},[accessToken,evidenceStatus,nextStep,say])
 const connect=useCallback(async()=>{if(state!=='idle'&&state!=='error')return;if(!accessToken){setError('Iniciá sesión para hablar con Hugo.');setState('error');return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setError('El reconocimiento de voz no está disponible en este dispositivo.');setState('error');return}try{const stream=await navigator.mediaDevices?.getUserMedia?.({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream?.getTracks().forEach(t=>t.stop())}catch{setError('Permití el micrófono para hablar con Hugo.');setState('error');return}running.current=true;busy.current=false;pending.current=null;setError('');setUserTranscript('');setAssistantTranscript('Te escucho.');const r=new SR();r.lang=locale.current;r.continuous=false;r.interimResults=true;r.onstart=()=>{if(running.current&&!busy.current)setState('ready')};r.onspeechstart=()=>{window.speechSynthesis?.cancel();setState('hearing')};r.onresult=async(e:any)=>{let text='',final=false;for(let i=e.resultIndex||0;i<e.results.length;i++){text+=String(e.results[i]?.[0]?.transcript||'');if(e.results[i]?.isFinal)final=true}text=text.trim();if(!text||!running.current)return;setUserTranscript(text.slice(-900));if(final)await handle(text)};r.onerror=(e:any)=>{const code=String(e?.error||'');if(code==='no-speech'||code==='aborted'){if(running.current)setTimeout(start,150);return}running.current=false;setState('error');setError(code==='not-allowed'?'Permití el micrófono para hablar con Hugo.':'Se interrumpió el reconocimiento de voz.')};r.onend=()=>{if(running.current&&!busy.current)setTimeout(start,100)};recognition.current=r;setState('ready');setTimeout(start,60)},[accessToken,handle,start,state])
 const disconnect=useCallback(()=>{running.current=false;busy.current=false;pending.current=null;try{recognition.current?.abort?.()}catch{}try{window.speechSynthesis?.cancel()}catch{}recognition.current=null;setState('idle');setError('');setUserTranscript('');setAssistantTranscript('')},[])
 useEffect(()=>disconnect,[disconnect])
 return useMemo(()=>({state,error,userTranscript,assistantTranscript,transcript:assistantTranscript,active:state!=='idle'&&state!=='error',connect,disconnect}),[assistantTranscript,connect,disconnect,error,state,userTranscript])
}
