import React,{useCallback,useEffect,useState}from'react'
import{supabase}from'../lib/supabase'

type Conv={telefono:string;usuario_id?:string|null;nombre?:string|null;idioma:string;estado:string;borrador:Record<string,unknown>;ultimo_servicio_id?:string|null;updated_at:string}
type Event={message_id:string;telefono:string;direccion:'in'|'out';tipo:string;payload:any;created_at:string}

export function WhatsAppAdminInbox(){
 const[open,setOpen]=useState(false),[rows,setRows]=useState<Conv[]>([]),[selected,setSelected]=useState<Conv|null>(null),[events,setEvents]=useState<Event[]>([]),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const db=supabase as any
 const load=useCallback(async()=>{const{data,error}=await db.from('whatsapp_conversaciones').select('*').order('updated_at',{ascending:false}).limit(50);if(error)throw error;setRows((data||[])as Conv[])},[db])
 const loadEvents=useCallback(async(phone:string)=>{const{data,error}=await db.from('whatsapp_eventos').select('*').eq('telefono',phone).order('created_at',{ascending:true}).limit(80);if(error)throw error;setEvents((data||[])as Event[])},[db])
 useEffect(()=>{if(!open)return;load().catch(e=>setMsg(e.message));const ch=supabase.channel('admin-whatsapp-inbox').on('postgres_changes',{event:'*',schema:'public',table:'whatsapp_conversaciones'},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'whatsapp_eventos'},()=>{load();if(selected)loadEvents(selected.telefono)}).subscribe();return()=>{supabase.removeChannel(ch)}},[open,load,loadEvents,selected])
 useEffect(()=>{if(selected)loadEvents(selected.telefono).catch(e=>setMsg(e.message))},[selected,loadEvents])
 async function send(){if(!selected||!reply.trim())return;setBusy(true);setMsg('');try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sesión Admin requerida.');const r=await fetch('/api/whatsapp/send',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({to:selected.telefono,message:reply.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo enviar.');setReply('');await loadEvents(selected.telefono)}catch(e){setMsg(e instanceof Error?e.message:'No se pudo enviar.')}finally{setBusy(false)}}
 const textOf=(e:Event)=>String(e.payload?.text||e.payload?.location?`📍 ${e.payload?.location?.latitude||''}, ${e.payload?.location?.longitude||''}`:'Mensaje')
 return <>
  <button type="button" onClick={()=>setOpen(v=>!v)} style={{position:'fixed',right:18,bottom:18,zIndex:12050,border:0,borderRadius:999,padding:'11px 15px',background:'#25D366',color:'#fff',fontWeight:900,boxShadow:'0 8px 28px rgba(0,0,0,.22)',cursor:'pointer'}}>WA {rows.length?`· ${rows.length}`:''}</button>
  {open&&<div style={{position:'fixed',right:18,bottom:70,zIndex:12049,width:'min(780px,calc(100vw - 36px))',height:'min(560px,calc(100vh - 100px))',background:'#fff',borderRadius:20,boxShadow:'0 18px 60px rgba(0,0,0,.28)',overflow:'hidden',display:'grid',gridTemplateColumns:'280px 1fr',border:'1px solid rgba(0,0,0,.1)'}}>
   <aside style={{borderRight:'1px solid #eee',overflowY:'auto'}}><div style={{padding:14,fontWeight:900,borderBottom:'1px solid #eee'}}>WhatsApp · Hugo</div>{rows.map(r=><button key={r.telefono} onClick={()=>setSelected(r)} style={{display:'block',width:'100%',padding:'11px 13px',textAlign:'left',border:0,borderBottom:'1px solid #f1f1f1',background:selected?.telefono===r.telefono?'#f0fff5':'#fff',cursor:'pointer'}}><strong style={{display:'block'}}>{r.nombre||r.telefono}</strong><small>{r.telefono} · {r.estado}</small>{r.ultimo_servicio_id&&<small style={{display:'block'}}>servicio {r.ultimo_servicio_id.slice(0,8)}</small>}</button>)}</aside>
   <section style={{display:'flex',flexDirection:'column',minWidth:0}}>{!selected?<div style={{margin:'auto',color:'#777'}}>Seleccioná una conversación</div>:<><div style={{padding:13,borderBottom:'1px solid #eee'}}><strong>{selected.nombre||selected.telefono}</strong><small style={{display:'block'}}>Estado: {selected.estado} · Idioma: {selected.idioma}</small>{Object.keys(selected.borrador||{}).length>0&&<small style={{display:'block',marginTop:4}}>Borrador: {JSON.stringify(selected.borrador)}</small>}</div><div style={{flex:1,overflowY:'auto',padding:14,background:'#f7f7f7'}}>{events.map(e=><div key={e.message_id} style={{maxWidth:'78%',margin:`6px ${e.direccion==='out'?'0 6px auto':'auto 6px 0'}`,padding:'9px 11px',borderRadius:13,background:e.direccion==='out'?'#dcf8c6':'#fff',boxShadow:'0 1px 2px rgba(0,0,0,.08)',fontSize:12}}>{textOf(e)}<small style={{display:'block',opacity:.5,marginTop:4}}>{new Date(e.created_at).toLocaleString('pt-BR')}</small></div>)}</div><div style={{padding:10,borderTop:'1px solid #eee',display:'flex',gap:8}}><input value={reply} onChange={e=>setReply(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Responder como UGO…" style={{flex:1,border:'1px solid #ddd',borderRadius:12,padding:'10px 12px'}}/><button onClick={send} disabled={busy||!reply.trim()} style={{border:0,borderRadius:12,padding:'0 15px',fontWeight:800,cursor:'pointer'}}>{busy?'…':'Enviar'}</button></div>{msg&&<div style={{padding:'6px 12px',fontSize:11,color:'#b00020'}}>{msg}</div>}</>}</section>
  </div>}
 </>
}
