import React,{useCallback,useEffect,useState}from'react'
import{supabase}from'../lib/supabase'

type Conv={telefono:string;usuario_id?:string|null;nombre?:string|null;idioma:string;estado:string;borrador:Record<string,unknown>;ultimo_servicio_id?:string|null;updated_at:string}
type Event={message_id:string;telefono:string;direccion:'in'|'out';tipo:string;payload:any;created_at:string}
type LinkedService={id:string;numero:number;estado:string;descripcion:string;tarifa:number|null;moneda:string;direccion_cliente:string|null;created_at:string;categoria?:{nombre?:string|null;emoji?:string|null}|null;cliente?:{nombre?:string|null}|null;proveedor?:{nombre?:string|null}|null}

export function WhatsAppAdminInbox(){
 const[open,setOpen]=useState(false),[rows,setRows]=useState<Conv[]>([]),[selected,setSelected]=useState<Conv|null>(null),[events,setEvents]=useState<Event[]>([]),[service,setService]=useState<LinkedService|null>(null),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const db=supabase as any
 const load=useCallback(async()=>{const{data,error}=await db.from('whatsapp_conversaciones').select('*').order('updated_at',{ascending:false}).limit(50);if(error)throw error;setRows((data||[])as Conv[])},[db])
 const loadEvents=useCallback(async(phone:string)=>{const{data,error}=await db.from('whatsapp_eventos').select('*').eq('telefono',phone).order('created_at',{ascending:true}).limit(80);if(error)throw error;setEvents((data||[])as Event[])},[db])
 const loadService=useCallback(async(id?:string|null)=>{if(!id){setService(null);return}const{data,error}=await db.from('servicios').select('id,numero,estado,descripcion,tarifa,moneda,direccion_cliente,created_at,categoria:categorias(nombre,emoji),cliente:usuarios!servicios_cliente_id_fkey(nombre),proveedor:usuarios!servicios_proveedor_id_fkey(nombre)').eq('id',id).maybeSingle();if(error)throw error;setService((data||null)as LinkedService|null)},[db])
 useEffect(()=>{if(!open)return;load().catch(e=>setMsg(e.message));const ch=supabase.channel('admin-whatsapp-inbox').on('postgres_changes',{event:'*',schema:'public',table:'whatsapp_conversaciones'},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'whatsapp_eventos'},()=>{load();if(selected)loadEvents(selected.telefono)}).on('postgres_changes',{event:'*',schema:'public',table:'servicios'},()=>{if(selected?.ultimo_servicio_id)loadService(selected.ultimo_servicio_id)}).subscribe();return()=>{supabase.removeChannel(ch)}},[open,load,loadEvents,loadService,selected])
 useEffect(()=>{if(!selected){setService(null);return}Promise.all([loadEvents(selected.telefono),loadService(selected.ultimo_servicio_id)]).catch(e=>setMsg(e.message))},[selected,loadEvents,loadService])
 async function send(){if(!selected||!reply.trim())return;setBusy(true);setMsg('');try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sesión Admin requerida.');const r=await fetch('/api/whatsapp/send',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({to:selected.telefono,message:reply.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo enviar.');setReply('');await loadEvents(selected.telefono)}catch(e){setMsg(e instanceof Error?e.message:'No se pudo enviar.')}finally{setBusy(false)}}
 const textOf=(e:Event)=>{if(e.payload?.text)return String(e.payload.text);if(e.payload?.location)return`📍 ${e.payload.location.latitude||''}, ${e.payload.location.longitude||''}`;return'Mensaje'}
 const money=(n:number|null,c='BRL')=>n==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:String(c||'BRL').trim()||'BRL'}).format(Number(n))
 return <>
  <button type="button" onClick={()=>setOpen(v=>!v)} style={{position:'fixed',right:18,bottom:18,zIndex:12050,border:0,borderRadius:999,padding:'11px 15px',background:'#25D366',color:'#fff',fontWeight:900,boxShadow:'0 8px 28px rgba(0,0,0,.22)',cursor:'pointer'}}>WA {rows.length?`· ${rows.length}`:''}</button>
  {open&&<div style={{position:'fixed',right:18,bottom:70,zIndex:12049,width:'min(900px,calc(100vw - 36px))',height:'min(620px,calc(100vh - 100px))',background:'#fff',borderRadius:20,boxShadow:'0 18px 60px rgba(0,0,0,.28)',overflow:'hidden',display:'grid',gridTemplateColumns:'290px 1fr',border:'1px solid rgba(0,0,0,.1)'}}>
   <aside style={{borderRight:'1px solid #eee',overflowY:'auto'}}><div style={{padding:14,fontWeight:900,borderBottom:'1px solid #eee'}}>WhatsApp · Hugo</div>{rows.length===0&&<div style={{padding:16,fontSize:12,color:'#777'}}>Todavía no hay conversaciones entrantes.</div>}{rows.map(r=><button key={r.telefono} onClick={()=>setSelected(r)} style={{display:'block',width:'100%',padding:'11px 13px',textAlign:'left',border:0,borderBottom:'1px solid #f1f1f1',background:selected?.telefono===r.telefono?'#f0fff5':'#fff',cursor:'pointer'}}><strong style={{display:'block'}}>{r.nombre||r.telefono}</strong><small>{r.telefono} · {r.estado}</small>{r.ultimo_servicio_id&&<small style={{display:'block'}}>pedido asociado</small>}</button>)}</aside>
   <section style={{display:'flex',flexDirection:'column',minWidth:0}}>{!selected?<div style={{margin:'auto',color:'#777'}}>Seleccioná una conversación</div>:<><div style={{padding:13,borderBottom:'1px solid #eee'}}><strong>{selected.nombre||selected.telefono}</strong><small style={{display:'block'}}>Estado conversación: {selected.estado} · Idioma: {selected.idioma}</small>{service&&<div style={{marginTop:9,padding:'9px 10px',borderRadius:12,background:'#f5f7f7',display:'grid',gridTemplateColumns:'1fr auto',gap:5,fontSize:11}}><div><b>#{service.numero} · {service.categoria?.emoji||'🛠'} {service.categoria?.nombre||'Servicio'}</b><div>{service.descripcion}</div><div style={{color:'#666'}}>{service.direccion_cliente||'Dirección pendiente'} · Cliente: {service.cliente?.nombre||'—'} · Proveedor: {service.proveedor?.nombre||'Buscando'}</div></div><div style={{textAlign:'right'}}><b>{money(service.tarifa,service.moneda)}</b><div style={{textTransform:'uppercase',fontSize:9,fontWeight:800,marginTop:3}}>{service.estado}</div></div></div>}{Object.keys(selected.borrador||{}).length>0&&<details style={{marginTop:6,fontSize:10}}><summary>Borrador de Hugo</summary><pre style={{whiteSpace:'pre-wrap',margin:5,background:'#fafafa',padding:6,borderRadius:8}}>{JSON.stringify(selected.borrador,null,2)}</pre></details>}</div><div style={{flex:1,overflowY:'auto',padding:14,background:'#f7f7f7'}}>{events.map(e=><div key={e.message_id} style={{maxWidth:'78%',margin:`6px ${e.direccion==='out'?'0 6px auto':'auto 6px 0'}`,padding:'9px 11px',borderRadius:13,background:e.direccion==='out'?'#dcf8c6':'#fff',boxShadow:'0 1px 2px rgba(0,0,0,.08)',fontSize:12}}>{textOf(e)}<small style={{display:'block',opacity:.5,marginTop:4}}>{new Date(e.created_at).toLocaleString('pt-BR')}</small></div>)}</div><div style={{padding:10,borderTop:'1px solid #eee',display:'flex',gap:8}}><input value={reply} onChange={e=>setReply(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Responder como UGO…" style={{flex:1,border:'1px solid #ddd',borderRadius:12,padding:'10px 12px'}}/><button onClick={send} disabled={busy||!reply.trim()} style={{border:0,borderRadius:12,padding:'0 15px',fontWeight:800,cursor:'pointer'}}>{busy?'…':'Enviar'}</button></div>{msg&&<div style={{padding:'6px 12px',fontSize:11,color:'#b00020'}}>{msg}</div>}</>}</section>
  </div>}
 </>
}
