import React,{useEffect,useMemo,useRef,useState}from'react'
import{useRoleSession,type Category}from'../../../mvp/shared'
import{ClientRequestEvidence}from'../../../mvp/ClientRequestEvidence'
import{resolveVoiceCategoryFromCatalog}from'../../../mvp/voiceCatalog'
import{useClientFlow}from'../../../mvp/client/clientFlow'
import{ClientLocationScreen}from'../../../mvp/client/ClientLocationScreen'
import{ClientPostConfirmFlow}from'../../../mvp/client/ClientPostConfirmFlow'
import{UGO_UI_EVENTS}from'../../../mvp/uiEvents'
import'./clientNeedScreen.css'

const QUICK:Record<string,string[]>={electricidad:['Reparar toma de corriente','Instalar luminaria','Revisar tablero eléctrico','Otro…'],plomeria:['Reparar pérdida de agua','Destapar cañería','Cambiar grifería','Otro…'],limpieza:['Limpieza general','Limpieza profunda','Limpieza después de obra','Otro…'],reparaciones:['Montaje o instalación','Reparación en el hogar','Ajuste o mantenimiento','Otro…']}
const norm=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
export function ClientNeedScreen(){
 const flow=useClientFlow(),{supabase,session}=useRoleSession('client'),[categories,setCategories]=useState<Category[]>([]),[description,setDescription]=useState(''),[message,setMessage]=useState(''),[stage,setStage]=useState<'need'|'location'|'post'>('need'),[draftId,setDraftId]=useState(''),[photoBusy,setPhotoBusy]=useState(false),[photoCount,setPhotoCount]=useState(0),appliedIntentId=useRef(0)
 useEffect(()=>{if(!session){setDraftId('');return}let id='';try{id=sessionStorage.getItem(`ugo:guided-request:${session.user.id}`)||''}catch{}if(!id){id=crypto.randomUUID();try{sessionStorage.setItem(`ugo:guided-request:${session.user.id}`,id)}catch{}}setDraftId(id)},[session])
 useEffect(()=>{if(!session)return;let alive=true;void supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre').then(({data})=>{if(alive)setCategories((data||[])as Category[])});return()=>{alive=false}},[session,supabase])
 const hint=norm(`${flow.hugoIntent?.categoryHint||''} ${flow.hugoIntent?.text||''}`),intentCategory=useMemo(()=>categories.find(item=>{const text=norm(`${item.slug} ${item.nombre}`);return hint&&text.split(/\s+/).some(token=>token.length>3&&hint.includes(token))})||null,[categories,hint]),descriptionCategory=useMemo(()=>description.trim().length>=5?resolveVoiceCategoryFromCatalog(categories,description):null,[categories,description]),category=descriptionCategory||intentCategory,key=category?norm(category.slug||category.nombre):'',quick=Object.entries(QUICK).find(([name])=>key.includes(name))?.[1]||(!category?Object.entries(QUICK).find(([name])=>hint.includes(name))?.[1]:null)||['Describir el trabajo','Instalación','Reparación','Otro…'],categoryAdjusted=Boolean(descriptionCategory&&intentCategory&&descriptionCategory.id!==intentCategory.id),canContinue=Boolean(category&&description.trim().length>=8)
 useEffect(()=>{if(!session)return;const onVoiceDraft=(event:Event)=>{const detail=(event as CustomEvent<{category?:{id?:string;slug?:string|null;nombre?:string|null};description?:string;voiceJourney?:boolean}>).detail||{},nextDescription=String(detail.description||'').trim(),voiceCategory=detail.category;if(!voiceCategory?.id||nextDescription.length<8)return;setDescription(nextDescription);setMessage('');try{const storageKey=`ugo:guided-request-draft:${session.user.id}`,raw=sessionStorage.getItem(storageKey),previous=raw?JSON.parse(raw):{};sessionStorage.setItem(storageKey,JSON.stringify({...previous,categoryId:String(voiceCategory.id),categoryName:String(voiceCategory.nombre||''),categorySlug:String(voiceCategory.slug||voiceCategory.id),description:nextDescription,voiceJourney:true}))}catch{}setStage('location')};window.addEventListener(UGO_UI_EVENTS.clientHugoDraft,onVoiceDraft);return()=>window.removeEventListener(UGO_UI_EVENTS.clientHugoDraft,onVoiceDraft)},[session])
 useEffect(()=>{if(!session)return;const intent=flow.hugoIntent;if(intent?.id&&intent.id!==appliedIntentId.current){appliedIntentId.current=intent.id;const nextDescription=String(intent.description||'').trim();setDescription(nextDescription);setMessage('');setStage('need');try{const storageKey=`ugo:guided-request-draft:${session.user.id}`;sessionStorage.setItem(storageKey,JSON.stringify({categoryId:category?.id||'',categoryName:category?.nombre||intent.categoryHint||'',categorySlug:category?.slug||intent.categoryHint||'',description:nextDescription,hugoIntentId:intent.id}))}catch{}return}try{const raw=sessionStorage.getItem(`ugo:guided-request-draft:${session.user.id}`);if(raw){const draft=JSON.parse(raw)as{description?:string};if(draft.description)setDescription(draft.description)}}catch{}},[category?.id,category?.nombre,category?.slug,flow.hugoIntent,session])
 const saveNeed=()=>{const value=description.trim();if(value.length<8){setMessage('Contanos un poco más sobre lo que necesitás.');return false}if(!session||!category){setMessage('No pudimos identificar la categoría. Volvé y elegila nuevamente.');return false}try{const storageKey=`ugo:guided-request-draft:${session.user.id}`,raw=sessionStorage.getItem(storageKey),previous=raw?JSON.parse(raw):{};sessionStorage.setItem(storageKey,JSON.stringify({...previous,categoryId:category.id,categoryName:category.nombre,categorySlug:category.slug,description:value}))}catch{}return true}
 const continueNeed=()=>{if(photoBusy){setMessage('Esperá a que termine de subir la foto o quitála para continuar.');return}if(saveNeed())setStage('location')}
 if(!session)return null
 if(stage==='post')return <ClientPostConfirmFlow onExit={()=>flow.navigate('home')}/>
 if(stage==='location')return <ClientLocationScreen onBack={()=>setStage('need')} onContinue={()=>setStage('post')}/>
 return <main className="ugo-need-screen" aria-label="Qué hay que hacer"><header className="ugo-need-top"><button type="button" onClick={()=>flow.navigate('home')} aria-label="Volver">←</button><strong>UGO</strong><div className="ugo-need-progress"><i/><i/><i/><i/><i/></div><small>1 de 5</small></header><section className="ugo-need-body"><div className="ugo-need-category"><span>{category?.emoji||'🧰'}</span><div><div className="ugo-need-category-title"><h1>{category?.nombre||flow.hugoIntent?.categoryHint||'Servicio'}</h1>{categoryAdjusted&&<b>AJUSTADO POR HUGO</b>}</div><p>Contanos qué necesitás</p>{categoryAdjusted&&<small className="ugo-need-category-adjusted">Hugo ajustó la categoría según lo que escribiste. “{flow.hugoIntent?.categoryHint||'La categoría anterior'}” no coincidía con la descripción. Usaremos {category?.nombre}.</small>}</div></div><label className="ugo-need-field-label" htmlFor="ugo-need-description">¿Qué hay que hacer?</label><textarea id="ugo-need-description" autoFocus maxLength={500} value={description} onChange={event=>{setDescription(event.target.value);setMessage('')}} placeholder="Ej: No funciona una toma de corriente en la cocina…" aria-label="Descripción del trabajo"/><div className="ugo-need-counter">{description.length}/500</div><h2>Opciones rápidas</h2><div className="ugo-need-quick">{quick.map(option=><button type="button" key={option} className={description.trim()===option?'selected':''} aria-pressed={description.trim()===option} onClick={()=>{if(option==='Otro…'){document.getElementById('ugo-need-description')?.focus();return}setDescription(option);setMessage('')}}><span>{option}</span>{option!=='Otro…'&&<i>→</i>}</button>)}</div><div className="ugo-need-evidence"><h2>Fotos del trabajo <small>(opcional)</small></h2>{draftId&&<ClientRequestEvidence draftId={draftId} inline onBusyChange={setPhotoBusy} onCountChange={count=>{setPhotoCount(count);if(session){try{const storageKey=`ugo:guided-request-draft:${session.user.id}`,raw=sessionStorage.getItem(storageKey),previous=raw?JSON.parse(raw):{};sessionStorage.setItem(storageKey,JSON.stringify({...previous,requestPhotoCount:count}))}catch{}}}}/>}<small>{photoCount?`${photoCount} foto${photoCount===1?'':'s'} lista${photoCount===1?'':'s'} para el profesional.`:'Podés continuar sin fotos.'}</small></div>{message&&<p className="ugo-need-error" role="alert">{message}</p>}</section><footer><div className="ugo-need-footer-inner"><small>{canContinue?'Listo para seguir':'Describí el trabajo para continuar'}</small><button type="button" disabled={!canContinue||photoBusy} onClick={continueNeed}>Continuar <span>→</span></button></div></footer></main>
}
export default ClientNeedScreen
