import React,{useEffect,useRef,useState}from'react'
import{useRoleSession}from'../../../mvp/shared'
import{UGO_UI_EVENTS}from'../../../mvp/uiEvents'
import'./clientSummaryScreen.css'
type Draft={categoryName?:string;description?:string;address?:string;complement?:string;when?:string;scheduleAt?:string;paymentMethod?:string;requestPhotoCount?:number;zone?:string;tariffQuote?:{zona?:string;precio_base?:number;precio_hora?:number;precio_min?:number;precio_max?:number|null;precio_referencia?:number}}
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))
const whenLabel=(d:Draft)=>d.when==='ahora'?'Lo antes posible':d.when==='hoy'?'Hoy':d.when==='manana'?'Mañana':d.scheduleAt?new Date(d.scheduleAt).toLocaleString('es-AR'):'Programado'
export function ClientSummaryScreen({onBack,onConfirm}:{onBack:()=>void;onConfirm:()=>void}){const{session}=useRoleSession('client'),[d,setD]=useState<Draft>({}),[message,setMessage]=useState(''),voiceConfirmed=useRef(false);useEffect(()=>{if(!session)return;try{setD(JSON.parse(sessionStorage.getItem(`ugo:guided-request-draft:${session.user.id}`)||'{}'))}catch{}},[session]);const ready=Boolean(d.categoryName&&d.description?.trim()&&d.address?.trim()&&d.when);const confirmOrder=()=>{if(!ready){setMessage('Falta completar algún dato del pedido. Volvé y revisalo antes de confirmar.');return}onConfirm()};useEffect(()=>{const confirm=()=>{if(voiceConfirmed.current||!ready)return;voiceConfirmed.current=true;onConfirm()};window.addEventListener(UGO_UI_EVENTS.clientHugoConfirmRequest,confirm);return()=>window.removeEventListener(UGO_UI_EVENTS.clientHugoConfirmRequest,confirm)},[onConfirm,ready]);if(!session)return null;return <main className="ugo-summary-screen"><header><button onClick={onBack}>←</button><strong>UGO</strong><div><i/><i/><i/><i/><i/></div><small>5 de 5</small></header><section><h1>Resumen del pedido</h1><p>Revisá los detalles antes de confirmar</p><article><h2>⚡ {d.categoryName||'Servicio'}</h2><dl><div><dt>▣ Qué hay que hacer</dt><dd>{d.description||'—'}</dd></div><div><dt>⌖ Dirección</dt><dd>{d.address||'—'}{d.complement?<><br/>{d.complement}</>:null}</dd></div><div><dt>▣ Cuándo</dt><dd>{whenLabel(d)}</dd></div><div><dt>▣ Forma de pago</dt><dd>{d.paymentMethod==='pix'?'PIX · se confirma con el profesional asignado':'Efectivo · pagás al finalizar'}</dd></div><div><dt>📷 Fotos</dt><dd>{Number(d.requestPhotoCount||0)>0?`${Number(d.requestPhotoCount)} adjunta${Number(d.requestPhotoCount)===1?'':'s'}`:'Sin fotos · opcional'}</dd></div>{d.tariffQuote&&<div><dt>💰 Tarifa UGO · {d.tariffQuote.zona||d.zone||'General'}</dt><dd>{Number(d.tariffQuote.precio_referencia||0)>0?<>Referencia desde <b>{money(Number(d.tariffQuote.precio_referencia||0))}</b>{Number(d.tariffQuote.precio_hora||0)>0?<><br/><small>{money(Number(d.tariffQuote.precio_hora||0))} por hora</small></>:null}</>:<>Referencia configurada</>}</dd></div>}</dl></article>{message&&<p className="ugo-summary-error" role="alert">{message}</p>}</section><footer><button disabled={!ready} onClick={confirmOrder}>Confirmar y buscar profesional</button></footer></main>}
export default ClientSummaryScreen
