import React,{useCallback,useEffect,useState}from'react'
import type{FormEvent,ReactNode}from'react'
import{AuthScreen,LoadingScreen,useRoleSession}from'../../../mvp/shared'
import'../../../mvp/client-stitch-alignment.css'
import'../../../mvp/client-onboarding.css'

const TERMS_VERSION='2026-09-04'
type Form={nombre:string;apellido:string;telefono:string;direccion:string;barrio:string;ciudad:string;idioma:string;contacto:string;lat:number|null;lng:number|null}
const empty:Form={nombre:'',apellido:'',telefono:'',direccion:'',barrio:'',ciudad:'Florianópolis',idioma:'pt-BR',contacto:'whatsapp',lat:null,lng:null}

export function ClientOnboardingGate({children}:{children:ReactNode}){
 const auth=useRoleSession('client'),{supabase,session,profile}=auth
 const[loading,setLoading]=useState(true),[complete,setComplete]=useState(false),[busy,setBusy]=useState(false),[terms,setTerms]=useState(false),[msg,setMsg]=useState(''),[locating,setLocating]=useState(false),[form,setForm]=useState<Form>(empty)
 const load=useCallback(async()=>{if(!session||!profile){setLoading(false);return}setLoading(true);try{const[{data:u,error:ue},{data:p,error:pe}]=await Promise.all([supabase.from('usuarios').select('nombre,apellido,lat,lng').eq('id',session.user.id).single(),supabase.from('perfiles_cliente').select('telefono,direccion,barrio,ciudad,idioma_preferido,contacto_preferido,termos_aceitos_at,onboarding_completo_at').eq('usuario_id',session.user.id).maybeSingle()]);if(ue)throw ue;if(pe)throw pe;setComplete(Boolean(p?.onboarding_completo_at&&p?.termos_aceitos_at&&p?.telefono&&p?.direccion&&p?.ciudad));setTerms(Boolean(p?.termos_aceitos_at));setForm({nombre:u?.nombre||profile.nombre||'',apellido:u?.apellido||'',telefono:p?.telefono||'',direccion:p?.direccion||'',barrio:p?.barrio||'',ciudad:p?.ciudad||'Florianópolis',idioma:p?.idioma_preferido||'pt-BR',contacto:p?.contacto_preferido||'whatsapp',lat:u?.lat??null,lng:u?.lng??null})}catch(e){setMsg(e instanceof Error?e.message:'No se pudo cargar tu perfil.')}finally{setLoading(false)}},[profile,session,supabase])
 useEffect(()=>{void load()},[load])
 function locate(){if(!navigator.geolocation){setMsg('Este dispositivo no permite obtener ubicación.');return}setLocating(true);navigator.geolocation.getCurrentPosition(pos=>{setForm(v=>({...v,lat:pos.coords.latitude,lng:pos.coords.longitude}));setMsg('Ubicación lista. La usaremos para encontrar profesionales cerca.');setLocating(false)},()=>{setMsg('No pudimos obtener tu ubicación. Podés continuar y activarla después.');setLocating(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
 async function submit(e:FormEvent){e.preventDefault();if(!session)return;setMsg('');setBusy(true);try{const digits=form.telefono.replace(/\D/g,'');if(!form.nombre.trim())throw new Error('Escribí tu nombre.');if(digits.length<8)throw new Error('Ingresá un teléfono/WhatsApp válido.');if(!form.direccion.trim())throw new Error('Ingresá tu dirección.');if(!form.ciudad.trim())throw new Error('Ingresá tu ciudad.');if(!terms)throw new Error('Aceptá los términos y la política de privacidad para continuar.');const{error}=await supabase.rpc('completar_onboarding_cliente',{p_nombre:form.nombre.trim(),p_apellido:form.apellido.trim(),p_telefono:form.telefono.trim(),p_direccion:form.direccion.trim(),p_barrio:form.barrio.trim(),p_ciudad:form.ciudad.trim(),p_idioma_preferido:form.idioma,p_contacto_preferido:form.contacto,p_termos_versao:TERMS_VERSION,p_lat:form.lat,p_lng:form.lng});if(error)throw error;setComplete(true)}catch(e){setMsg(e instanceof Error?e.message:'No se pudo completar el registro.')}finally{setBusy(false)}}
 if(auth.loading||loading)return <div className="ugo-client-stitch-scope"><LoadingScreen label="Preparando tu cuenta U.G.O.…"/></div>
 if(!session||!profile)return <div className="ugo-client-stitch-scope"><AuthScreen role="client" supabase={supabase} error={auth.error} onError={auth.setError}/></div>
 if(complete)return <div className="ugo-client-stitch-scope">{children}</div>
 return <div className="ugo-client-stitch-scope"><main className="ugo-client-onboarding"><form className="ugo-client-onboarding-card" onSubmit={submit}>
  <header className="ugo-client-onboarding-head"><div><small>U.G.O. · CLIENTE</small><h1>Terminemos tu perfil</h1><p>Lo hacés una sola vez. Después pedir un servicio es mucho más rápido.</p><span className="ugo-client-time-pill">Menos de 1 minuto</span></div><span className="ugo-client-onboarding-icon" aria-hidden="true">✦</span></header>
  <div className="ugo-client-onboarding-body">
   <section className="ugo-client-section"><div className="ugo-client-section-title"><span>1</span><div><strong>Tus datos</strong><small>Para identificarte y mantenerte en contacto.</small></div></div><div className="ugo-client-grid-2"><label className="ugo-client-field">Nombre<input autoComplete="given-name" value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label className="ugo-client-field">Apellido <em>opcional</em><input autoComplete="family-name" value={form.apellido} onChange={e=>setForm({...form,apellido:e.target.value})}/></label></div><label className="ugo-client-field">Email<input className="readonly" value={session.user.email||''} readOnly/></label><label className="ugo-client-field">WhatsApp / teléfono<input inputMode="tel" autoComplete="tel" placeholder="+55 48 99999-9999" value={form.telefono} onChange={e=>setForm({...form,telefono:e.target.value})}/></label></section>
   <section className="ugo-client-section"><div className="ugo-client-section-title"><span>2</span><div><strong>Dónde necesitás servicios</strong><small>Usamos esta dirección para buscar profesionales cerca.</small></div></div><label className="ugo-client-field">Dirección<input autoComplete="street-address" placeholder="Calle y número" value={form.direccion} onChange={e=>setForm({...form,direccion:e.target.value})}/></label><div className="ugo-client-grid-2"><label className="ugo-client-field">Barrio / zona<input placeholder="Ej. Canasvieiras" value={form.barrio} onChange={e=>setForm({...form,barrio:e.target.value})}/></label><label className="ugo-client-field">Ciudad<input autoComplete="address-level2" value={form.ciudad} onChange={e=>setForm({...form,ciudad:e.target.value})}/></label></div><button type="button" className={`ugo-client-location ${form.lat!=null?'is-ready':''}`} onClick={locate} disabled={locating}><span>{form.lat!=null?'✓':'⌖'}</span><div><strong>{locating?'Obteniendo ubicación…':form.lat!=null?'Ubicación capturada':'Usar mi ubicación actual'}</strong><small>{form.lat!=null?'Listo para encontrar profesionales cerca':'Más rápido y preciso'}</small></div></button></section>
   <section className="ugo-client-section"><div className="ugo-client-section-title"><span>3</span><div><strong>Preferencias</strong><small>Podés cambiarlas más adelante desde tu perfil.</small></div></div><div className="ugo-client-grid-2"><label className="ugo-client-field">Idioma<select value={form.idioma} onChange={e=>setForm({...form,idioma:e.target.value})}><option value="pt-BR">Português</option><option value="es-AR">Español</option><option value="en">English</option></select></label><label className="ugo-client-field">Contacto preferido<select value={form.contacto} onChange={e=>setForm({...form,contacto:e.target.value})}><option value="whatsapp">WhatsApp</option><option value="telefono">Teléfono</option><option value="chat">Chat UGO</option></select></label></div></section>
   <label className="ugo-client-terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Acepto los <strong>términos de uso</strong> y la <strong>política de privacidad</strong> de UGO.</span></label>
   {msg&&<div className="ugo-client-message" role="status">{msg}</div>}
   <div className="ugo-client-actions"><button className="ugo-client-primary" disabled={busy}>{busy?'Guardando…':'Entrar a UGO'}</button><button type="button" className="ugo-client-signout" onClick={()=>auth.signOut()}>Cerrar sesión</button></div>
  </div>
 </form></main></div>
}
