import React,{useCallback,useEffect,useMemo,useState}from'react'
import{getRoleSupabase}from'../../lib/roleSupabase'
import{reportSentinelIncident}from'../../lib/sentinel'
import{ServiceChat}from'../ServiceChat'
import type{Service}from'../shared'
import{money,useProviderData}from'./providerData'
import{useProviderFlow}from'./providerFlow'
import{ProviderEvidencePanel}from'./ProviderEvidencePanel'
import{advanceProviderService,cancelProviderService}from'./providerService'

type AgendaCategory={nombre?:string|null;emoji?:string|null}
type AgendaRow={id:string;numero:number|null;estado:string;descripcion:string|null;direccion_cliente:string|null;programado_para:string|null;tarifa:number|null;ganancia_proveedor:number|null;moneda:string|null;categoria:AgendaCategory|null}
type StateEvent={id:string;estado_anterior:string|null;estado_nuevo:string;actor_role:string;motivo:string|null;created_at:string}

const AGENDA_STATES=['asignado','en_camino','llegado','en_progreso','esperando_aprobacion']
const STATE_LABELS:Record<string,string>={asignado:'Asignado',en_camino:'En camino',llegado:'En el lugar',en_progreso:'Trabajo en curso',esperando_aprobacion:'Esperando validación del cliente',completado:'Completado',cancelado:'Cancelado'}
const FLOW=['asignado','en_camino','llegado','en_progreso','esperando_aprobacion','completado']
const FLOW_NAMES:Record<string,string>={asignado:'Asignado',en_camino:'En camino',llegado:'Llegué',en_progreso:'Trabajo iniciado',esperando_aprobacion:'Trabajo finalizado',completado:'Validado'}
const CANCELLABLE=new Set(['asignado','en_camino','llegado'])
const TRAVEL_LEAD_MS=60*60*1000

function scheduleLabel(value:string|null){if(!value)return'Atención inmediata';const date=new Date(value);return Number.isNaN(date.getTime())?'Horario por confirmar':date.toLocaleString('es-AR',{weekday:'long',day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'})}
function relativeLabel(value:string|null){if(!value)return'Ahora';const time=new Date(value).getTime();if(!Number.isFinite(time))return'';const minutes=Math.round((time-Date.now())/60000);if(Math.abs(minutes)<2)return'Ahora';if(minutes>0&&minutes<60)return`En ${minutes} min`;if(minutes>=60&&minutes<1440)return`En ${Math.round(minutes/60)} h`;if(minutes>=1440)return`En ${Math.round(minutes/1440)} día${Math.round(minutes/1440)===1?'':'s'}`;return'Hora programada alcanzada'}

export function ProviderAgenda(){
 const db=useMemo(()=>getRoleSupabase('provider'),[]),flow=useProviderFlow(),provider=useProviderData()
 const[userId,setUserId]=useState<string|null>(null),[rows,setRows]=useState<AgendaRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selectedId,setSelectedId]=useState<string|null>(null),[events,setEvents]=useState<StateEvent[]>([]),[actionBusy,setActionBusy]=useState(false),[actionError,setActionError]=useState(''),[cancelOpen,setCancelOpen]=useState(false),[cancelReason,setCancelReason]=useState(''),[readiness,setReadiness]=useState({initial:false,final:false}),[clock,setClock]=useState(()=>Date.now())
 const reportAgenda=useCallback((eventType:string,message:string,cause?:unknown)=>{void reportSentinelIncident({eventType,message,error:cause,role:'provider',severity:'P1',action:'provider.agenda.load',checklistCode:'PROVIDER-AGENDA'})},[])
 const load=useCallback(async(id:string)=>{setLoading(true);setError('');try{const{data,error:queryError}=await db.from('servicios').select('id,numero,estado,descripcion,direccion_cliente,programado_para,tarifa,ganancia_proveedor,moneda,categoria:categorias(nombre,emoji)').eq('proveedor_id',id).in('estado',AGENDA_STATES).order('programado_para',{ascending:true,nullsFirst:true}).limit(50);if(queryError)throw queryError;setRows((data||[])as unknown as AgendaRow[])}catch(loadError){const message=loadError instanceof Error?loadError.message:'No pudimos cargar tu agenda.';setError(message);reportAgenda('provider_agenda_load_error',message,loadError)}finally{setLoading(false)}},[db,reportAgenda])
 const loadEvents=useCallback(async(serviceId:string)=>{const{data,error:eventError}=await db.from('servicio_estado_eventos').select('id,estado_anterior,estado_nuevo,actor_role,motivo,created_at').eq('servicio_id',serviceId).order('created_at',{ascending:true}).limit(100);if(eventError){setEvents([]);return}setEvents((data||[])as StateEvent[])},[db])
 useEffect(()=>{let alive=true;let channel:ReturnType<typeof db.channel>|null=null;db.auth.getSession().then(({data})=>{const id=data.session?.user.id||null;if(!alive)return;setUserId(id);if(!id){setLoading(false);return}void load(id);channel=db.channel(`provider-agenda-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'servicios',filter:`proveedor_id=eq.${id}`},()=>void load(id)).subscribe(status=>{if(status==='SUBSCRIBED')void load(id);else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){reportAgenda('provider_agenda_realtime_error',`Canal agenda: ${status}`);void load(id)}})}).catch(sessionError=>{if(alive){const message=sessionError instanceof Error?sessionError.message:'No pudimos iniciar tu agenda.';setError(message);setLoading(false);reportAgenda('provider_agenda_session_error',message,sessionError)}});return()=>{alive=false;if(channel)void db.removeChannel(channel)}},[db,load,reportAgenda])
 useEffect(()=>{if(!selectedId){setEvents([]);setActionError('');setCancelOpen(false);setCancelReason('');setReadiness({initial:false,final:false});return}void loadEvents(selectedId)},[loadEvents,selectedId])
 useEffect(()=>{if(!selectedId)return;setClock(Date.now());const timer=window.setInterval(()=>setClock(Date.now()),30_000);return()=>window.clearInterval(timer)},[selectedId])
 const now=Date.now(),todayStart=new Date();todayStart.setHours(0,0,0,0);const tomorrowStart=todayStart.getTime()+86400000
 const immediateRows=rows.filter(row=>!row.programado_para||new Date(row.programado_para).getTime()<todayStart.getTime())
 const todayRows=rows.filter(row=>{if(!row.programado_para)return false;const time=new Date(row.programado_para).getTime();return time>=todayStart.getTime()&&time<tomorrowStart})
 const upcomingRows=rows.filter(row=>row.programado_para&&new Date(row.programado_para).getTime()>=tomorrowStart)
 const active=rows.find(row=>provider.service?.id===row.id)||null
 const next=active||immediateRows[0]||todayRows.find(row=>new Date(row.programado_para||0).getTime()>=now)||todayRows[0]||upcomingRows[0]||null
 const selected=rows.find(row=>row.id===selectedId)||null
 const selectedService=selected as unknown as Service|null
 const selectedPayment=selected?provider.payments.find(payment=>payment.servicio_id===selected.id)||null:null
 const selectedPaymentReady=Boolean(selectedPayment&&((selectedPayment.metodo==='efectivo'&&['pendiente','liberado'].includes(selectedPayment.estado))||(selectedPayment.estado==='retenido'&&Boolean(selectedPayment.mp_payment_id||selectedPayment.pago_externo_id||selectedPayment.pix_e2e_id))))
 const scheduledTime=selected?.programado_para?new Date(selected.programado_para).getTime():null
 const departureAt=scheduledTime!=null&&Number.isFinite(scheduledTime)?scheduledTime-TRAVEL_LEAD_MS:null
 const departureReady=departureAt==null||clock>=departureAt
 const departureLabel=departureAt==null?'':new Date(departureAt).toLocaleString('es-AR',{weekday:'long',day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'})
 const refreshSelected=async(id:string)=>{if(userId)await load(userId);await provider.reload();await loadEvents(id)}
 const advance=async(target:'en_camino'|'llegado'|'en_progreso'|'esperando_aprobacion')=>{if(!selected||actionBusy)return;if(target==='en_camino'&&!departureReady){setActionError(`Este trabajo está programado para más adelante. Podés iniciar el traslado desde ${departureLabel}.`);return}if(target==='en_camino'&&!selectedPaymentReady){setActionError('La forma de pago todavía no está confirmada. UGO habilita la salida automáticamente cuando el pago queda listo.');return}if(target==='en_progreso'&&!readiness.initial){setActionError('Primero registrá la evidencia de cómo encontraste el trabajo.');return}if(target==='esperando_aprobacion'&&!readiness.final){setActionError('Primero registrá la evidencia final del trabajo.');return}setActionBusy(true);setActionError('');try{await advanceProviderService(db,selected.id,target);await refreshSelected(selected.id)}catch(actionFailure){setActionError(actionFailure instanceof Error?actionFailure.message:'No se pudo actualizar el estado.')}finally{setActionBusy(false)}}
 const cancelSelected=async()=>{if(!selected||actionBusy)return;setActionBusy(true);setActionError('');try{await cancelProviderService(db,selected.id,cancelReason);setCancelOpen(false);setSelectedId(null);if(userId)await load(userId);await provider.reload()}catch(actionFailure){setActionError(actionFailure instanceof Error?actionFailure.message:'No se pudo cancelar el pedido.')}finally{setActionBusy(false)}}
 const card=(row:AgendaRow)=>{const current=provider.service?.id===row.id;return <article className="provider-card provider-opportunity" key={row.id}><div className="provider-opportunity-main"><div className="provider-opportunity-meta"><span className="provider-chip">{current?'Servicio activo':STATE_LABELS[row.estado]||row.estado}</span><span>#{row.numero??String(row.id).slice(0,8)}</span></div><h2>{row.categoria?.emoji||'🧰'} {row.categoria?.nombre||'Servicio UGO'}</h2><p>🗓 {scheduleLabel(row.programado_para)}</p><p>📍 {row.direccion_cliente||'Dirección por confirmar'}</p>{row.descripcion&&<p>{row.descripcion}</p>}<strong className="provider-price">{money(row.ganancia_proveedor||row.tarifa,row.moneda||'BRL')}</strong><span className="provider-match">{relativeLabel(row.programado_para)}</span></div><button type="button" className={current?'provider-primary':'provider-secondary'} onClick={()=>setSelectedId(row.id)}>Gestionar pedido</button></article>}
 const progressIndex=selected?Math.max(0,FLOW.indexOf(selected.estado)):0
 return <section className="provider-screen" aria-labelledby="provider-agenda-title">
  <header className="provider-section-head"><div><span className="provider-kicker">AGENDA UGO</span><h1 id="provider-agenda-title">Mis trabajos</h1><p>Cada pedido conserva su serviceId, chat, estados, evidencias y registro operativo.</p></div><button type="button" className="provider-link" onClick={flow.actions.openHistory}>Ver historial</button></header>
  {next&&!loading&&!error&&<article className="provider-priority-summary"><small>{provider.service?.id===next.id?'SERVICIO ACTIVO':'SIGUIENTE'}</small><strong>{next.categoria?.emoji||'🧰'} {next.categoria?.nombre||'Servicio UGO'}</strong><span>{scheduleLabel(next.programado_para)} · {relativeLabel(next.programado_para)}</span><button type="button" className="provider-secondary" onClick={()=>setSelectedId(next.id)}>Gestionar pedido</button></article>}
  {loading&&<article className="provider-card provider-empty"><strong>Cargando agenda…</strong><span>Estamos leyendo todos tus trabajos asignados.</span></article>}
  {error&&<article className="provider-card provider-empty" role="alert"><strong>No pudimos cargar tu agenda</strong><span>{error}</span>{userId&&<button type="button" className="provider-secondary provider-wide" onClick={()=>void load(userId)}>Reintentar</button>}</article>}
  {!loading&&!error&&rows.length===0&&<article className="provider-card provider-empty"><strong>No tenés trabajos asignados</strong><span>Cuando aceptes un pedido, inmediato o programado, va a aparecer acá automáticamente.</span><button type="button" className="provider-secondary provider-wide" onClick={flow.actions.openOpportunities}>Ver oportunidades</button></article>}
  {!loading&&!error&&immediateRows.length>0&&<div className="provider-agenda-group"><span className="provider-kicker">AHORA</span><div className="provider-list">{immediateRows.map(card)}</div></div>}
  {!loading&&!error&&todayRows.length>0&&<div className="provider-agenda-group"><span className="provider-kicker">HOY</span><div className="provider-list">{todayRows.map(card)}</div></div>}
  {!loading&&!error&&upcomingRows.length>0&&<div className="provider-agenda-group"><span className="provider-kicker">PRÓXIMOS</span><div className="provider-list">{upcomingRows.map(card)}</div></div>}
  {selected&&<div className="ugo-dispute-backdrop provider-job-detail-backdrop" onClick={()=>setSelectedId(null)}><section className="ugo-dispute-sheet provider-job-detail-sheet" onClick={event=>event.stopPropagation()}><header><div><small>PEDIDO · #{selected.numero??String(selected.id).slice(0,8)}</small><h3>{selected.categoria?.emoji||'🧰'} {selected.categoria?.nombre||'Servicio UGO'}</h3></div><button type="button" onClick={()=>setSelectedId(null)}>×</button></header>
   <div className="provider-job-state"><small>ESTADO ACTUAL</small><strong>{STATE_LABELS[selected.estado]||selected.estado}</strong></div>
   <div className="provider-job-state-flow" aria-label="Estados del pedido">{FLOW.map((state,index)=><div key={state} className={index<=progressIndex?'done':''}><span>{index<progressIndex?'✓':index+1}</span><small>{FLOW_NAMES[state]}</small></div>)}</div>
   <div className="ugo-dispute-note"><b>{scheduleLabel(selected.programado_para)}</b><span>{selected.direccion_cliente||'Dirección por confirmar'}</span>{selected.descripcion&&<span>{selected.descripcion}</span>}<span>{money(selected.ganancia_proveedor||selected.tarifa,selected.moneda||'BRL')}</span></div>
   <section className="provider-job-control-card"><small>CONTROL DEL PEDIDO</small>{selected.estado==='asignado'&&!departureReady&&<><button type="button" className="provider-primary provider-wide" disabled>ESTOY YENDO</button><div className="provider-payment-lock" role="status"><b>Trabajo programado</b><span>Podés iniciar el traslado desde {departureLabel}. UGO habilita el botón automáticamente 60 minutos antes.</span></div></>}{selected.estado==='asignado'&&departureReady&&!selectedPaymentReady&&<><button type="button" className="provider-primary provider-wide" disabled>ESTOY YENDO</button><div className="provider-payment-lock" role="status"><b>Esperando forma de pago</b><span>UGO habilita la salida en cuanto Efectivo o PIX quede confirmado para este pedido.</span></div></>}{selected.estado==='asignado'&&departureReady&&selectedPaymentReady&&<button type="button" className="provider-primary provider-wide" disabled={actionBusy} onClick={()=>void advance('en_camino')}>{actionBusy?'Actualizando…':'ESTOY YENDO'}</button>}{selected.estado==='en_camino'&&<button type="button" className="provider-primary provider-wide" disabled={actionBusy} onClick={()=>void advance('llegado')}>{actionBusy?'Confirmando…':'YA LLEGUÉ'}</button>}{selected.estado==='llegado'&&<><ProviderEvidencePanel service={selectedService} compact forceKind="antes" onReadinessChange={setReadiness}/><button type="button" className="provider-primary provider-wide" disabled={actionBusy||!readiness.initial} onClick={()=>void advance('en_progreso')}>{actionBusy?'Actualizando…':'EMPEZAR TRABAJO'}</button></>}{selected.estado==='en_progreso'&&<><ProviderEvidencePanel service={selectedService} compact forceKind="despues" onReadinessChange={setReadiness}/><button type="button" className="provider-primary provider-wide" disabled={actionBusy||!readiness.final} onClick={()=>void advance('esperando_aprobacion')}>{actionBusy?'Actualizando…':'TRABAJO LISTO'}</button></>}{selected.estado==='esperando_aprobacion'&&<div className="provider-simple-done"><strong>✓ Trabajo enviado a validación</strong><span>{selectedPayment?.metodo==='efectivo'?'El cliente revisa el resultado. Después de aprobarlo, UGO le indica cuánto pagarte; el pedido se cierra cuando confirma el pago.':'El cliente revisa el resultado. Al aprobarlo, UGO completa el pedido y libera el pago protegido.'}</span></div>}{actionError&&<div className="provider-payment-lock" role="alert">{actionError}</div>}</section>
   <section className="provider-card provider-job-chat"><div className="provider-job-chat-head"><small>CHAT DEL PEDIDO</small><strong>Cliente ↔ Proveedor</strong></div><ServiceChat role="provider" serviceId={selected.id} compact/></section>
   <section className="provider-job-audit"><small>REGISTRO DEL PEDIDO</small>{events.length?<ol>{events.map(event=><li key={event.id}><b>{STATE_LABELS[event.estado_nuevo]||event.estado_nuevo}</b><span>{new Date(event.created_at).toLocaleString('es-AR')} · {event.actor_role}</span>{event.motivo&&<em>{event.motivo}</em>}</li>)}</ol>:<p>Los cambios de estado de este pedido se registran automáticamente.</p>}</section>
   {CANCELLABLE.has(selected.estado)&&<section className="provider-job-cancel"><button type="button" className="provider-reject provider-wide" onClick={()=>setCancelOpen(value=>!value)}>No voy a poder realizar este pedido</button>{cancelOpen&&<div><label>Motivo de cancelación<textarea maxLength={500} value={cancelReason} onChange={event=>setCancelReason(event.target.value)} placeholder="Ej: Tuve un imprevisto y no voy a llegar a horario."/></label><p>La cancelación, el motivo, la fecha y tu usuario quedan registrados en el pedido.</p><button type="button" className="provider-reject provider-wide" disabled={actionBusy||cancelReason.trim().length<5} onClick={()=>void cancelSelected()}>{actionBusy?'Cancelando…':'Confirmar cancelación'}</button></div>}</section>}
   <footer>Todos los cambios se aplican únicamente al serviceId {selected.id.slice(0,8)}… y se sincronizan con el cliente.</footer></section></div>}
 </section>
}

export default ProviderAgenda
