import React,{useCallback,useEffect,useMemo,useState}from'react'
import{loadServiceEvidence,providerEvidenceDb,uploadServiceEvidence,type EvidenceType,type ProviderEvidenceRow as EvidenceRow}from'../../features/provider/services/providerEvidenceService'
import type{Service}from'../shared'
import{Card,Select}from'../../shared/ui'

type Readiness={initial:boolean;final:boolean}
type Props={service:Service|null;onReadinessChange?:(ready:Readiness)=>void;compact?:boolean;forceKind?:EvidenceType;actionLabel?:string;actionBusyLabel?:string;onUploaded?:(kind:EvidenceType)=>void|Promise<unknown>;disabled?:boolean}
const LABELS:Record<EvidenceType,string>={antes:'Antes',durante:'Durante',despues:'Después'}

export function ProviderEvidencePanel({service,onReadinessChange,compact=false,forceKind,actionLabel='📷 Tomar o elegir foto',actionBusyLabel='Guardando…',onUploaded,disabled=false}:Props){
 const supabase=useMemo(()=>providerEvidenceDb(),[])
 const[kind,setKind]=useState<EvidenceType>('antes'),[rows,setRows]=useState<EvidenceRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const allowedKinds=useMemo<EvidenceType[]>(()=>service?.estado==='llegado'?['antes']:service?.estado==='en_progreso'?['durante','despues']:service?.estado==='esperando_aprobacion'?['despues']:[],[service?.estado])
 const effectiveKind=forceKind&&allowedKinds.includes(forceKind)?forceKind:allowedKinds.includes(kind)?kind:(allowedKinds[0]||kind)
 const load=useCallback(async()=>{if(!service){setRows([]);onReadinessChange?.({initial:false,final:false});return}let signed:EvidenceRow[];try{signed=await loadServiceEvidence(service.id)}catch(error){setError(error instanceof Error?error.message:'No se pudieron cargar las evidencias.');return}setError('');onReadinessChange?.({initial:signed.some(r=>r.tipo==='antes'),final:signed.some(r=>r.tipo==='despues')});setRows(signed)},[onReadinessChange,service,supabase])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);if(!service)return()=>window.clearTimeout(timer);const refresh=()=>void load().catch(()=>{});const ch=supabase.channel(`provider-evidence-${service.id}`).on('postgres_changes',{event:'*',schema:'public',table:'evidencias_servicio',filter:`servicio_id=eq.${service.id}`},refresh).subscribe(status=>{if(status==='SUBSCRIBED')refresh()});const onOnline=()=>refresh();const onVisibility=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('online',onOnline);document.addEventListener('visibilitychange',onVisibility);return()=>{window.clearTimeout(timer);window.removeEventListener('online',onOnline);document.removeEventListener('visibilitychange',onVisibility);supabase.removeChannel(ch)}},[load,service,supabase])
 if(!service||!['llegado','en_progreso','esperando_aprobacion'].includes(service.estado))return null
 async function finishUpload(uploadedKind:EvidenceType){await load();await onUploaded?.(uploadedKind)}
 async function upload(file:File|null){if(!file)return;setError('');if(!allowedKinds.includes(effectiveKind)){setError('Ese registro no corresponde al estado actual del servicio.');return}if(file.size>10*1024*1024){setError('La foto supera el límite de 10 MB.');return}setBusy(true);try{await uploadServiceEvidence(service.id,effectiveKind,file);await finishUpload(effectiveKind)}catch(e){await load().catch(()=>{});setError(e instanceof Error?e.message:'No se pudo guardar la evidencia.')}finally{setBusy(false)}}
 const hasInitial=rows.some(r=>r.tipo==='antes'),hasFinal=rows.some(r=>r.tipo==='despues')
 if(compact)return <div className="provider-capture-action"><label className={`provider-primary provider-main-action provider-evidence-compact ${busy||disabled||!allowedKinds.length?'is-disabled':''}`}>{busy?actionBusyLabel:actionLabel}<input type="file" accept="image/*" capture="environment" disabled={busy||disabled||!allowedKinds.length} onChange={e=>{void upload(e.target.files?.[0]||null);e.currentTarget.value=''}}/></label><small>UGO guarda el registro necesario por detrás.</small>{error&&<div className="provider-payment-lock" role="alert">{error}</div>}</div>
 const guidance=service.estado==='llegado'?'Registrá cómo encontraste el trabajo. Esta foto “Antes” es obligatoria para poder iniciar.':service.estado==='esperando_aprobacion'?'Este estado sólo admite evidencia final “Después” para recuperar un cierre histórico incompleto.':'Documentá avances como “Durante” y, cuando termines realmente el trabajo, registrá una foto “Después”.'
 return <Card className="provider-card provider-evidence"><div className="provider-evidence-head"><div><small>EVIDENCIAS</small><strong>{hasFinal?'Registro completo':hasInitial?'Registro iniciado':'Falta evidencia inicial'}</strong></div><span>{rows.length}</span></div><p>{guidance}</p>{allowedKinds.length>1&&!forceKind?<Select value={effectiveKind} onChange={e=>setKind(e.target.value as EvidenceType)}>{allowedKinds.map(value=><option value={value} key={value}>{LABELS[value]}</option>)}</Select>:allowedKinds[0]?<div className="provider-chip">Tipo: {LABELS[effectiveKind]}</div>:null}<label className="provider-evidence-upload">{busy?'Subiendo…':'📷 Tomar o elegir foto'}<input type="file" accept="image/*" capture="environment" disabled={busy||disabled||!allowedKinds.length} onChange={e=>{void upload(e.target.files?.[0]||null);e.currentTarget.value=''}}/></label>{error&&<div className="provider-payment-lock">{error}</div>}<div className="provider-evidence-grid">{rows.slice(-6).map(r=><figure key={r.id}>{r.url?<img src={r.url} alt={`Evidencia ${r.tipo}`}/>:<div/>}<figcaption>{r.tipo}</figcaption></figure>)}</div>{service.estado==='llegado'&&!hasInitial&&<div className="provider-payment-lock">Necesitás una evidencia inicial antes de comenzar.</div>}{service.estado==='en_progreso'&&!hasFinal&&<div className="provider-payment-lock">Para finalizar vas a necesitar una evidencia “Después” tomada con el trabajo en curso.</div>}{service.estado==='esperando_aprobacion'&&!hasFinal&&<div className="provider-payment-lock">Necesitás una evidencia final para que el cliente pueda aprobar.</div>}</Card>
}