import React,{useCallback,useEffect,useMemo,useState}from'react'
import{getRoleSupabase}from'../../lib/roleSupabase'
import type{Service}from'../shared'

type EvidenceType='antes'|'durante'|'despues'
type EvidenceRow={id:string;tipo:EvidenceType;storage_path:string;descripcion:string|null;created_at:string;url?:string|null}
type Props={service:Service|null;onReadinessChange?:(ready:{initial:boolean;final:boolean})=>void}
const BUCKET='service-evidence'
const LABELS:Record<EvidenceType,string>={antes:'Antes',durante:'Durante',despues:'Después'}

export function ProviderEvidencePanel({service,onReadinessChange}:Props){
 const supabase=useMemo(()=>getRoleSupabase('provider'),[])
 const[kind,setKind]=useState<EvidenceType>('antes'),[rows,setRows]=useState<EvidenceRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const allowedKinds=useMemo<EvidenceType[]>(()=>service?.estado==='llegado'?['antes']:service?.estado==='en_progreso'?['durante','despues']:service?.estado==='esperando_aprobacion'?['despues']:[],[service?.estado])
 const effectiveKind=allowedKinds.includes(kind)?kind:(allowedKinds[0]||kind)
 const load=useCallback(async()=>{if(!service){setRows([]);onReadinessChange?.({initial:false,final:false});return}const{data,error}=await supabase.from('evidencias_servicio').select('id,tipo,storage_path,descripcion,created_at').eq('servicio_id',service.id).order('created_at',{ascending:true});if(error){setError(error.message);return}const base=(data||[])as EvidenceRow[];onReadinessChange?.({initial:base.some(r=>r.tipo==='antes'),final:base.some(r=>r.tipo==='despues')});const signed=await Promise.all(base.map(async row=>{const{data:s,error:e}=await supabase.storage.from(BUCKET).createSignedUrl(row.storage_path,900);return{...row,url:e?null:s?.signedUrl||null}}));setRows(signed)},[onReadinessChange,service,supabase])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);if(!service)return()=>window.clearTimeout(timer);const ch=supabase.channel(`provider-evidence-${service.id}`).on('postgres_changes',{event:'*',schema:'public',table:'evidencias_servicio',filter:`servicio_id=eq.${service.id}`},()=>void load()).subscribe();return()=>{window.clearTimeout(timer);supabase.removeChannel(ch)}},[load,service,supabase])
 if(!service||!['llegado','en_progreso','esperando_aprobacion'].includes(service.estado))return null
 async function upload(file:File|null){if(!file)return;setError('');if(!allowedKinds.includes(effectiveKind)){setError('Ese tipo de evidencia no corresponde al estado actual del servicio.');return}if(file.size>10*1024*1024){setError('La foto supera el límite de 10 MB.');return}setBusy(true);try{const{data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user)throw new Error('Sesión no disponible.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${service.id}/${user.id}/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await supabase.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});if(uploadError)throw uploadError;const{error:insertError}=await supabase.from('evidencias_servicio').insert({servicio_id:service.id,usuario_id:user.id,tipo:effectiveKind,storage_path:path,descripcion:effectiveKind==='antes'?'Estado inicial al llegar':effectiveKind==='despues'?'Resultado final del trabajo':'Evidencia durante el servicio',metadata:{mime:file.type||null,size:file.size}});if(insertError){await supabase.storage.from(BUCKET).remove([path]);throw insertError}await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo subir la evidencia.')}finally{setBusy(false)}}
 const hasInitial=rows.some(r=>r.tipo==='antes'),hasFinal=rows.some(r=>r.tipo==='despues')
 const guidance=service.estado==='llegado'?'Registrá cómo encontraste el trabajo. Esta foto “Antes” es obligatoria para poder iniciar.':service.estado==='esperando_aprobacion'?'Este estado sólo admite evidencia final “Después” para recuperar un cierre histórico incompleto.':'Documentá avances como “Durante” y, cuando termines realmente el trabajo, registrá una foto “Después”.'
 return <section className="provider-card provider-evidence"><div className="provider-evidence-head"><div><small>EVIDENCIAS</small><strong>{hasFinal?'Registro completo':hasInitial?'Registro iniciado':'Falta evidencia inicial'}</strong></div><span>{rows.length}</span></div><p>{guidance}</p>{allowedKinds.length>1?<select value={effectiveKind} onChange={e=>setKind(e.target.value as EvidenceType)}>{allowedKinds.map(value=><option value={value} key={value}>{LABELS[value]}</option>)}</select>:allowedKinds[0]?<div className="provider-chip">Tipo: {LABELS[allowedKinds[0]]}</div>:null}<label className="provider-evidence-upload">{busy?'Subiendo…':'📷 Tomar o elegir foto'}<input type="file" accept="image/*" capture="environment" disabled={busy||!allowedKinds.length} onChange={e=>{void upload(e.target.files?.[0]||null);e.currentTarget.value=''}}/></label>{error&&<div className="provider-payment-lock">{error}</div>}<div className="provider-evidence-grid">{rows.slice(-6).map(r=><figure key={r.id}>{r.url?<img src={r.url} alt={`Evidencia ${r.tipo}`}/>:<div/>}<figcaption>{r.tipo}</figcaption></figure>)}</div>{service.estado==='llegado'&&!hasInitial&&<div className="provider-payment-lock">Necesitás una evidencia inicial antes de comenzar.</div>}{service.estado==='en_progreso'&&!hasFinal&&<div className="provider-payment-lock">Para finalizar vas a necesitar una evidencia “Después” tomada con el trabajo en curso.</div>}{service.estado==='esperando_aprobacion'&&!hasFinal&&<div className="provider-payment-lock">Necesitás una evidencia final para que el cliente pueda aprobar.</div>}</section>
}