import React,{createContext,useCallback,useContext,useEffect,useState}from'react'
import{AuthScreen,LoadingScreen,timeAgo,money,useRoleSession,type Notice,type Offer,type Service}from'../shared'
import{ProviderOnboardingGate}from'../ProviderOnboardingGate'
import{acceptProviderOpportunity,advanceProviderService,cancelProviderService,loadProviderSnapshot,rejectProviderOpportunity,setProviderAvailability,type ProviderAdvanceOptions,type ProviderDebt,type ProviderPayment,type ProviderProfileFull}from'./providerService'
import{useProviderRealtime}from'./useProviderRealtime'
import{isAtOrBeyondProviderState,type ProviderLifecycleState}from'../../lib/marketplace/lifecycle'
import type{DemandSignal,ProviderOpportunity}from'./providerTypes'

type ProviderData={name:string;karma:number;provider:ProviderProfileFull;offers:Offer[];opportunities:ProviderOpportunity[];demand:DemandSignal[];demandError:string|null;service:Service|null;payments:ProviderPayment[];debts:ProviderDebt[];online:boolean;released:number;retained:number;cashReceived:number;ugoDebt:number;pendingDebtCount:number;debtBlocked:boolean;busy:boolean;notice:Notice;reload:()=>Promise<void>;toggleOnline:()=>Promise<boolean>;acceptOpportunity:(id:string)=>Promise<boolean>;rejectOpportunity:(id:string)=>Promise<boolean>;advance:(state:'en_camino'|'llegado'|'en_progreso'|'esperando_aprobacion',options?:ProviderAdvanceOptions)=>Promise<boolean>;completeService:()=>Promise<boolean>;cancelService:(reason:string)=>Promise<boolean>;funded:boolean;cashSelected:boolean;paymentPreferenceSelected:boolean;accessToken:string;profilePhotoUrl:string|null;saveProfile:(input:{bio:string|null;tarifa_base:number;ciudad_base:string|null;zona_radio_km:number})=>Promise<boolean>;uploadProfilePhoto:(file:File)=>Promise<boolean>;changePassword:(password:string)=>Promise<boolean>;signOut:()=>Promise<void>}
type DemandRow={zona_lat:number|string|null;zona_lng:number|string|null;pedidos:number|string|null;urgentes:number|string|null;tarifa_promedio:number|string|null;ultimo_pedido:string|null}
type PixAwarePayment=ProviderPayment&{pix_e2e_id?:string|null}
type OpportunityMetadata={requested_when?:unknown;preferences?:unknown;estimated_duration_minutes?:unknown}
type OpportunityService=Service&{zona_cliente?:string|null;programado_para?:string|null;metadata?:OpportunityMetadata|null}
type ProviderServiceWithPaymentPreference=Service&{tarifa?:number|string|null;metadata?:Record<string,unknown>|null}
const C=createContext<ProviderData|null>(null)
const isProtectedPayment=(payment:ProviderPayment|null|undefined)=>Boolean(payment&&(payment.mp_payment_id||payment.pago_externo_id||(payment as PixAwarePayment).pix_e2e_id))
const coordinate=(value:number|string|null)=>{if(value==null||value==='')return null;const parsed=Number(value);return Number.isFinite(parsed)?parsed:null}
const textValue=(value:unknown)=>typeof value==='string'&&value.trim()?value.trim():null
const positiveNumber=(value:unknown)=>{const parsed=Number(value);return Number.isFinite(parsed)&&parsed>0?parsed:null}
const PROFILE_PHOTO_MAX_BYTES=5*1024*1024
const PROFILE_PHOTO_EXT:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}

export function ProviderDataProvider({children}:{children:React.ReactNode}){
 const auth=useRoleSession('provider'),{supabase,session,profile}=auth
 const[provider,setProvider]=useState<ProviderProfileFull|null>(null),[offers,setOffers]=useState<Offer[]>([]),[service,setService]=useState<Service|null>(null),[payments,setPayments]=useState<ProviderPayment[]>([]),[debts,setDebts]=useState<ProviderDebt[]>([]),[demand,setDemand]=useState<DemandSignal[]>([]),[demandError,setDemandError]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null)
 const reload=useCallback(async()=>{if(!session){setDemand([]);setDemandError(null);setLoading(false);return}const{data:gateProfile,error:gateError}=await supabase.from('perfiles_proveedor').select('*').eq('usuario_id',session.user.id).maybeSingle();if(gateError)throw gateError;const verifiedProfile=(gateProfile as ProviderProfileFull|null)||null;setProvider(verifiedProfile);setLoading(false);const snap=await loadProviderSnapshot(supabase,session.user.id);const effectiveProvider=snap.provider||verifiedProfile;setProvider(effectiveProvider);setOffers(snap.offers);setService(snap.service);setPayments(snap.payments);setDebts(snap.debts);let nextDemand:DemandSignal[]=[];setDemandError(null);if(effectiveProvider?.estado_verificacion==='verificado'){const categoryId=effectiveProvider.categoria_principal_id||null;const[{data:market,error:marketError},{data:category}]=await Promise.all([supabase.rpc('obtener_demanda_proveedor',{p_categoria_id:categoryId,p_horas:24}),categoryId?supabase.from('categorias').select('nombre').eq('id',categoryId).maybeSingle():Promise.resolve({data:null,error:null})]);if(marketError){setDemandError('No pudimos actualizar el radar de demanda. Podés reintentar sin perder tus oportunidades.')}else{const categoryName=String(category?.nombre||'Tu categoría');nextDemand=((market||[])as DemandRow[]).map((row,index)=>{const requests=Math.max(0,Number(row.pedidos||0)),urgent=Math.max(0,Number(row.urgentes||0)),ratio=requests?urgent/requests:0,latitude=coordinate(row.zona_lat),longitude=coordinate(row.zona_lng);return{id:`demand-${latitude??'x'}-${longitude??'x'}-${index}`,category:categoryName,zone:`Zona activa ${index+1} · ${requests} pedido${requests===1?'':'s'} reciente${requests===1?'':'s'}`,latitude,longitude,distanceKm:0,estimatedValue:Number(row.tarifa_promedio||0),requestedAt:row.ultimo_pedido||new Date().toISOString(),urgency:ratio>=.5?'high':urgent>0?'medium':'low',demandLevel:requests>=6||ratio>=.5?'high':requests>=3?'medium':'low'}})}}setDemand(nextDemand);setLoading(false)},[session,supabase])
 const handleRealtime=useCallback(()=>{reload().catch(()=>{})},[reload])
 useEffect(()=>{if(session)reload().catch((e:Error)=>{setNotice({type:'error',text:e.message});setLoading(false)});else setLoading(false)},[reload,session])
 const marketAutoRefresh=Boolean(session&&provider?.estado_verificacion==='verificado'&&provider.disponible)
 useEffect(()=>{if(!marketAutoRefresh)return;let disposed=false;const refresh=()=>{if(!disposed&&document.visibilityState!=='hidden')void reload().catch(()=>{})};const timer=window.setInterval(refresh,45_000);const onFocus=()=>refresh();const onVisibility=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisibility);return()=>{disposed=true;window.clearInterval(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisibility)}},[marketAutoRefresh,reload])
 useProviderRealtime(supabase,session?.user.id||null,handleRealtime)
 if(auth.loading||loading)return <LoadingScreen label="Preparando UGO Pro…"/>
 if(!session||!profile)return <AuthScreen role="provider" supabase={supabase} error={auth.error} onError={auth.setError}/>
 if(!provider||provider.estado_verificacion!=='verificado')return <ProviderOnboardingGate onVerified={reload}/>
 const run=async(fn:()=>Promise<void>,ok:string)=>{setBusy(true);setNotice(null);try{await fn();setNotice({type:'ok',text:ok});await reload();return true}catch(e){try{await reload()}catch{}setNotice({type:'error',text:e instanceof Error?e.message:'No se pudo completar la acción. Actualizamos el estado real para que puedas reintentar.'});return false}finally{setBusy(false)}}
 const unresolvedDebts=debts.filter(debt=>debt.ambiente==='real'&&!['pagado','anulado'].includes(debt.estado)&&Number(debt.saldo_pendiente||0)>0)
 const pendingDebtCount=unresolvedDebts.length,debtBlocked=pendingDebtCount>=3
 const toggleOnline=()=>{if(debtBlocked&&!provider.disponible){setNotice({type:'error',text:`Tenés ${pendingDebtCount} comisiones UGO pendientes. Pagá al menos una para volver a recibir pedidos.`});return Promise.resolve(false)}return run(()=>setProviderAvailability(supabase,session.user.id,!provider.disponible),provider.disponible?'Quedaste Offline.':'Ya estás Online.')}
 const acceptOpportunity=(id:string)=>{if(debtBlocked){setNotice({type:'error',text:'Llegaste al límite de 3 servicios con comisión UGO pendiente. Pagá a UGO antes de aceptar otro pedido.'});return Promise.resolve(false)}return run(()=>acceptProviderOpportunity(supabase,id),'Trabajo aceptado.')}
 const rejectOpportunity=(id:string)=>run(()=>rejectProviderOpportunity(supabase,id),'Pedido rechazado.')
 const currentPayment=service?payments.find(p=>p.servicio_id===service.id):null
 const servicePaymentMetadata=(service as ProviderServiceWithPaymentPreference|null)?.metadata||{},requestedPaymentMethod=String(servicePaymentMetadata.requested_payment_method||servicePaymentMetadata.payment_method||'').toLowerCase().replace('cash','efectivo'),amountReady=Boolean(service&&Number((service as ProviderServiceWithPaymentPreference).tarifa||0)>0),effectivePaymentMethod=String(currentPayment?.metodo||requestedPaymentMethod||'').toLowerCase()
 const funded=currentPayment?.estado==='retenido'&&isProtectedPayment(currentPayment)
 const cashSelected=currentPayment?.metodo==='efectivo'
 const paymentPreferenceSelected=Boolean(service&&!amountReady&&['efectivo','pix'].includes(effectivePaymentMethod))
 const transitionPersisted=async(serviceId:string,target:ProviderLifecycleState)=>{const{data}=await supabase.from('servicios').select('estado').eq('id',serviceId).eq('proveedor_id',session.user.id).maybeSingle();return isAtOrBeyondProviderState(String(data?.estado||''),target)}
 const advance=async(state:'en_camino'|'llegado'|'en_progreso'|'esperando_aprobacion',options?:ProviderAdvanceOptions)=>{if(!service)return false;if(service.estado==='asignado'&&state==='en_camino'&&!funded&&!cashSelected&&!paymentPreferenceSelected){setNotice({type:'info',text:'Todavía falta que el cliente confirme la forma de pago.'});return false}if(service.estado==='llegado'&&state==='en_progreso'){if(!amountReady){setNotice({type:'info',text:'Definí y conseguí la aprobación del importe antes de empezar el trabajo.'});return false}if(effectivePaymentMethod==='pix'&&!funded){setNotice({type:'info',text:'El cliente eligió Pix, pero todavía falta confirmar el pago antes de empezar.'});return false}if(effectivePaymentMethod==='efectivo'&&!cashSelected){setNotice({type:'info',text:'UGO todavía está confirmando el pago en efectivo con el importe aprobado.'});return false}if(!effectivePaymentMethod){setNotice({type:'info',text:'Falta que el cliente confirme la forma de pago antes de empezar.'});return false}}const serviceId=service.id;setBusy(true);setNotice(null);try{await advanceProviderService(supabase,serviceId,state,options);setNotice({type:'ok',text:state==='en_camino'?'UGO avisó que estás yendo.':state==='llegado'?'Llegada confirmada.':state==='en_progreso'?'Trabajo iniciado.':'Estado del servicio actualizado.'});await reload();return true}catch(e){if(await transitionPersisted(serviceId,state)){setNotice({type:'ok',text:'Estado del servicio actualizado.'});await reload();return true}try{await reload()}catch{}setNotice({type:'error',text:e instanceof Error?e.message:'No se pudo actualizar el servicio. Actualizamos el estado real para que puedas reintentar.'});return false}finally{setBusy(false)}}
 const completeService=async()=>{if(!service||service.estado!=='en_progreso')return false;const serviceId=service.id;setBusy(true);setNotice(null);try{try{await advanceProviderService(supabase,serviceId,'esperando_aprobacion')}catch(e){if(!(await transitionPersisted(serviceId,'esperando_aprobacion')))throw e}setNotice({type:'ok',text:'Listo. UGO avisó al cliente y sigue el cierre por detrás.'});await reload();return true}catch(e){try{await reload()}catch{}setNotice({type:'error',text:e instanceof Error?e.message:'No pudimos cerrar el trabajo. Tu avance quedó guardado para reintentar.'});return false}finally{setBusy(false)}}
 const cancelService=async(reason:string)=>{if(!service)return false;const serviceId=service.id;return run(()=>cancelProviderService(supabase,serviceId,reason),'Pedido cancelado y registrado.')}
 const opportunities:ProviderOpportunity[]=(debtBlocked?[]:offers).map(offer=>{const serviceData=(offer.servicio||null)as OpportunityService|null,duration=positiveNumber(serviceData?.metadata?.estimated_duration_minutes);return{id:offer.id,serviceId:offer.servicio_id,category:serviceData?.categoria?.nombre||'Servicio',title:serviceData?.descripcion||'Nueva oportunidad',description:serviceData?.descripcion||'',zone:serviceData?.zona_cliente||'Zona por confirmar',distanceKm:Number(offer.distancia_km||0),estimatedValue:Number(serviceData?.tarifa||offer.tarifa_ofrecida||0),requestedAt:serviceData?.created_at||new Date().toISOString(),scheduledAt:serviceData?.programado_para||null,durationMinutes:duration,preferences:textValue(serviceData?.metadata?.preferences),urgency:serviceData?.urgencia?'urgent':'normal',matchScore:offer.ranking==null?undefined:Number(offer.ranking),expiresAt:offer.expira_at||null}})
 const released=payments.filter(p=>p.estado==='liberado'&&p.metodo!=='efectivo').reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0),retained=payments.filter(p=>p.estado==='retenido'&&isProtectedPayment(p)).reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0),cashReceived=payments.filter(p=>p.estado==='liberado'&&p.metodo==='efectivo').reduce((n,p)=>n+Number(p.monto_bruto||0),0),ugoDebt=debts.filter(debt=>debt.ambiente==='real'&&!['pagado','anulado'].includes(debt.estado)&&Number(debt.saldo_pendiente||0)>0).reduce((n,debt)=>n+Number(debt.saldo_pendiente||0),0)
 const profilePhotoUrl=provider?.foto_perfil_path?supabase.storage.from('provider-public').getPublicUrl(provider.foto_perfil_path).data.publicUrl:null
 const saveProfile=(input:{bio:string|null;tarifa_base:number;ciudad_base:string|null;zona_radio_km:number})=>run(async()=>{const{error}=await(supabase as any).from('perfiles_proveedor').update(input).eq('usuario_id',session.user.id);if(error)throw error},'Perfil profesional actualizado.')
 const uploadProfilePhoto=(file:File)=>run(async()=>{const ext=PROFILE_PHOTO_EXT[file.type];if(!ext)throw new Error('Usá una imagen JPG, PNG o WebP.');if(file.size<=0||file.size>PROFILE_PHOTO_MAX_BYTES)throw new Error('La foto debe pesar hasta 5 MB.');const unique=typeof crypto!=='undefined'&&'randomUUID'in crypto?crypto.randomUUID():Math.random().toString(36).slice(2);const path=session.user.id+'/profile/'+Date.now()+'-'+unique+'.'+ext;const upload=await supabase.storage.from('provider-public').upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(upload.error)throw upload.error;const update=await(supabase as any).from('perfiles_proveedor').update({foto_perfil_path:path}).eq('usuario_id',session.user.id);if(update.error){await supabase.storage.from('provider-public').remove([path]).catch(()=>{});throw update.error}},'Foto de perfil actualizada.')
 const changePassword=(password:string)=>run(async()=>{const{error}=await supabase.auth.updateUser({password});if(error)throw error},'Contraseña actualizada correctamente.')
 const signOut=async()=>{setBusy(true);const{error}=await supabase.auth.signOut();setBusy(false);if(error){setNotice({type:'error',text:error.message});return}window.location.replace(window.location.pathname+'?app=provider')}
 const value:ProviderData={name:profile.nombre,karma:Number(profile.karma||5),provider,offers,opportunities,demand,demandError,service,payments,debts,online:Boolean(provider.disponible),released,retained,cashReceived,ugoDebt,pendingDebtCount,debtBlocked,busy,notice,reload,toggleOnline,acceptOpportunity,rejectOpportunity,advance,completeService,cancelService,funded,cashSelected,paymentPreferenceSelected,accessToken:session.access_token,profilePhotoUrl,saveProfile,uploadProfilePhoto,changePassword,signOut}
 return <C.Provider value={value}>{children}</C.Provider>
}
export function useProviderData(){const v=useContext(C);if(!v)throw new Error('useProviderData debe usarse dentro de ProviderDataProvider');return v}
export{timeAgo,money}
