import React from'react'
import{useProviderFlow}from'./providerFlow'
import{useProviderData,money}from'./providerData'

export function ProviderHome(){
 const flow=useProviderFlow(),d=useProviderData()
 const activeText=d.cashSelected?'El cliente eligió efectivo. UGO registra el cobro por detrás.':d.funded?'El pago está listo. Andá, resolvé y marcá listo.':'Esperá a que el cliente confirme la forma de pago.'
 const next=d.service?{title:'Tenés un trabajo para resolver',text:activeText,action:flow.actions.openActiveJob,label:'Resolver trabajo'}:d.opportunities.length?{title:`Tenés ${d.opportunities.length} pedido${d.opportunities.length===1?'':'s'} para revisar`,text:'Mirá el problema y decidí si lo podés resolver.',action:flow.actions.openOpportunities,label:'Ver problemas'}:{title:d.online?'Estás disponible para recibir trabajos':'Estás fuera del radar',text:d.online?'UGO te avisa cuando aparece un problema compatible con vos.':'Activá tu disponibilidad para recibir pedidos.',action:d.toggleOnline,label:d.online?'Actualizar':'Ponerme Online'}
 return <section className="provider-screen provider-home" aria-labelledby="provider-home-title"><header className="provider-top"><div><span className="provider-kicker">UGO PRO · HOY</span><h1 id="provider-home-title">Hola, {d.name}</h1><p>⭐ {d.karma.toFixed(1)}</p></div><button style={{minHeight:48}} className={`provider-status ${d.online?'is-online':'is-offline'}`} type="button" onClick={d.toggleOnline} disabled={d.busy} aria-pressed={d.online}>● {d.online?'Online':'Offline'}</button></header><article className="provider-hero"><span>Ahora</span><h2>{next.title}</h2><p>{next.text}</p><button className="provider-primary provider-wide" onClick={next.action} disabled={d.busy}>{next.label}</button></article><div className="provider-grid provider-home-grid"><button className="provider-card" onClick={flow.actions.openOpportunities}><small>PEDIDOS PARA VOS</small><strong>{d.opportunities.length} pedidos</strong><span>Ver problemas →</span></button><button className="provider-card" onClick={flow.actions.openAgenda}><small>AGENDA</small><strong>Próximos trabajos</strong><span>Ver agenda →</span></button><button className="provider-card" onClick={flow.actions.openEarnings}><small>DINERO</small><strong>{money(d.retained)}</strong><span>{money(d.released)} liberado/registrado →</span></button></div></section>
}
