import React,{useEffect}from'react'
import{ServiceHistoryPanel}from'../ServiceHistoryPanel'
import{DisputeDock}from'../DisputeDock'
import{AppLocationButton}from'../AppLocationButton'
import{ProviderLocationTracker}from'../ProviderLocationTracker'
import{NotificationCenter,type UgoNotification}from'../NotificationCenter'
import{useProviderFlow}from'./providerFlow'
import{ProviderDataProvider,useProviderData}from'./providerData'
import{ProviderHome}from'./ProviderHome'
import{ProviderDemand}from'./ProviderDemand'
import{ProviderOpportunities,ProviderOpportunityDetail}from'./ProviderOpportunities'
import{ProviderActiveJob}from'./ProviderActiveJob'
import{ProviderAgenda}from'./ProviderAgenda'
import{ProviderProfileScreen}from'./ProviderProfile'
import{ProviderEarnings}from'./ProviderEarnings'
import{ProviderStudioSidebar}from'./ProviderStudioSidebar'
import{ProviderRatingPrompt}from'../ProviderRatingPrompt'
import{ProviderCalendarSyncBridge}from'./ProviderCalendarSyncBridge'
import{ProviderHugoBridge}from'./ProviderHugoBridge'
import'../ugo-dark-premium.css'
import'./provider-flow.css'
import'./provider-responsive-layout.css'
import'./provider-simple-flow.css'
import'./provider-ux-v2.css'
import'./provider-redesign-2026.css'
import'./provider-nav-cleanup.css'
import'./provider-ai-studio-production-lock.css'
import'./provider-studio-sidebar.css'
import'../provider-rating.css'
import'./provider-premium-2026.css'
const ACTIONABLE_SCHEDULE_LEAD_MS=60*60*1000
export function ProviderRoot(){return <ProviderDataProvider><ProviderOperationalRoot/></ProviderDataProvider>}
function ProviderOperationalRoot(){const flow=useProviderFlow(),data=useProviderData();useEffect(()=>{const params=new URLSearchParams(window.location.search),calendar=params.get('calendar'),serviceId=params.get('serviceId');if(calendar==='connected'||calendar==='error'||calendar==='cancelled')flow.navigate('profile');else if(serviceId)flow.navigate('agenda',serviceId)},[flow.navigate]);useEffect(()=>flow.registerActions({openHome:()=>flow.navigate('home'),openDemand:()=>flow.navigate('demand'),openOpportunities:()=>flow.navigate('opportunities'),openOpportunity:id=>flow.navigate('opportunity-detail',id),acceptOpportunity:async id=>{const opportunity=data.opportunities.find(item=>item.id===id),scheduledAt=opportunity?.scheduledAt?new Date(opportunity.scheduledAt).getTime():null,isFuture=scheduledAt!=null&&Number.isFinite(scheduledAt)&&scheduledAt>Date.now()+ACTIONABLE_SCHEDULE_LEAD_MS,alreadyWorking=Boolean(data.service&&['asignado','en_camino','llegado','en_progreso'].includes(data.service.estado));const ok=await data.acceptOpportunity(id);if(ok){if(alreadyWorking||isFuture)flow.navigate('agenda',opportunity?.serviceId||null);else flow.navigate('active-job')}return ok},rejectOpportunity:async id=>{const ok=await data.rejectOpportunity(id);if(ok)flow.navigate('opportunities');return ok},openActiveJob:()=>flow.navigate('active-job'),openAgenda:()=>flow.navigate('agenda'),openAgendaService:serviceId=>flow.navigate('agenda',serviceId),openEarnings:()=>flow.navigate('earnings'),openProfile:()=>flow.navigate('profile'),openHistory:()=>flow.navigate('history'),openDispute:()=>flow.navigate('dispute')}),[data.acceptOpportunity,data.opportunities,data.rejectOpportunity,flow.navigate,flow.registerActions]);const screen=flow.screen,marketScreen=screen==='demand'||screen==='opportunities'||screen==='opportunity-detail',workScreen=screen==='active-job'||screen==='agenda'||screen==='history',missionActive=screen==='active-job'&&Boolean(data.service);const openNotice=(notice:UgoNotification)=>{const offerId=typeof notice.datos.oferta_id==='string'?notice.datos.oferta_id:null,serviceId=typeof notice.datos.servicio_id==='string'?notice.datos.servicio_id:null;if(notice.tipo==='nueva_oferta')return offerId?flow.actions.openOpportunity(offerId):flow.actions.openOpportunities();if(notice.tipo==='trabajo_asignado'){void data.reload().then(()=>serviceId?flow.actions.openAgendaService(serviceId):flow.actions.openActiveJob());return}if(notice.tipo.includes('disputa'))return flow.actions.openDispute();if(notice.tipo==='pago_liberado')return flow.actions.openEarnings();if(notice.tipo==='pago_efectivo_confirmado')return flow.actions.openHistory();if(notice.tipo==='servicio_completado'||notice.tipo==='servicio_cancelado')return flow.actions.openHistory();if(serviceId)return flow.actions.openAgendaService(serviceId);return data.service?flow.actions.openActiveJob():flow.actions.openHome()};const current=(active:boolean):'page'|undefined=>active?'page':undefined;return <div className={`ugo-provider-root ${missionActive?'is-mission-active':''}`}><ProviderStudioSidebar/>{data.notice&&<div className={`provider-notice ${data.notice.type}`} role="status">{data.notice.text}</div>}<NotificationCenter role="provider" attentionEnabled={data.online&&!data.debtBlocked} onOpenNotice={openNotice}/><ProviderCalendarSyncBridge/><ProviderHugoBridge/>{screen==='home'&&<ProviderHome/>}{screen==='demand'&&<ProviderDemand/>}{screen==='opportunities'&&<ProviderOpportunities/>}{screen==='opportunity-detail'&&<ProviderOpportunityDetail id={flow.opportunityId}/>} {screen==='active-job'&&<ProviderActiveJob/>}{screen==='agenda'&&<ProviderAgenda key={flow.agendaServiceId||'agenda'}/>}{screen==='earnings'&&<ProviderEarnings/>}{screen==='profile'&&<ProviderProfileScreen/>}{screen==='history'&&<div className="provider-screen"><ServiceHistoryPanel role="provider" embedded/></div>}<DisputeDock role="provider" openRequest={screen==='dispute'}/><ProviderRatingPrompt suspended={Boolean(data.service)}/><ProviderLocationTracker service={data.service} onAutoArrival={data.service?.estado==='en_camino'?()=>data.advance('llegado'):undefined}/>{!missionActive&&<AppLocationButton role="provider"/>}<nav className="provider-bottom-nav" aria-label="Navegación proveedor"><button aria-current={current(screen==='home')} className={screen==='home'?'active':''} onClick={flow.actions.openHome}>Inicio</button><button aria-current={current(marketScreen)} className={marketScreen?'active':''} onClick={flow.actions.openOpportunities}>Pedidos{data.opportunities.length>0&&<b className="provider-nav-badge">{data.opportunities.length}</b>}</button><button aria-current={current(workScreen)} className={workScreen?'active':''} onClick={data.service?flow.actions.openActiveJob:flow.actions.openAgenda}>Trabajo</button><button aria-current={current(screen==='profile'||screen==='earnings')} className={screen==='profile'||screen==='earnings'?'active':''} onClick={flow.actions.openProfile}>Perfil</button></nav></div>}
