import React from'react'
import type{Service}from'../shared'

type Props={service:Service;funded:boolean;cashSelected:boolean;cashConfirmed:boolean;initialEvidence:boolean;finalEvidence:boolean}
type AssistantStage={title:string;summary:string;items:string[];tone:'ready'|'attention'|'working'|'done'}

function buildStage({service,funded,cashSelected,cashConfirmed,initialEvidence,finalEvidence}:Props):AssistantStage{
 const paymentReady=funded||cashSelected
 if(service.estado==='asignado')return paymentReady?{title:'Prepará la salida',summary:cashSelected?'El cliente eligió efectivo. UGO registrará el cobro dentro de este servicio.':'El pago electrónico está protegido. Ya podés preparar el traslado.',items:['Revisá descripción, dirección y alcance antes de salir.','Llevá herramientas y elementos de seguridad adecuados al servicio.','Usá “Salir hacia el cliente” únicamente cuando estés listo para iniciar el traslado.'],tone:'ready'}:{title:'Esperá la forma de pago',summary:'Todavía no avances al traslado. UGO debe tener un medio de pago válido para este servicio.',items:['Revisá el pedido y prepará lo necesario.','No coordines cobros ni trabajos por fuera de UGO.','Cuando el cliente confirme el pago, esta guía se actualizará automáticamente.'],tone:'attention'}
 if(service.estado==='en_camino')return{title:'Llegá con el contexto claro',summary:'Estás en traslado. La próxima transición válida es confirmar llegada.',items:['Verificá dirección y referencias antes de estacionar o ingresar.','No marques llegada antes de estar realmente en el lugar.','Si UGO tiene ubicación exacta, la llegada puede requerir validación dentro del radio operativo.'],tone:'working'}
 if(service.estado==='llegado')return{title:'Documentá antes de empezar',summary:initialEvidence?'La evidencia “Antes” ya está registrada. Podés iniciar el servicio.':'Falta la evidencia “Antes”. UGO no debe iniciar el trabajo sin registrar el estado inicial.',items:[initialEvidence?'Confirmá que la foto representa el estado inicial real.':'Subí una foto clara del estado inicial del trabajo.','Acordá con el cliente únicamente el alcance ya aprobado.','Si aparece trabajo adicional, usá “Ampliar servicio” para mantener costo, tiempo y aprobación dentro de UGO.'],tone:initialEvidence?'ready':'attention'}
 if(service.estado==='en_progreso')return{title:'Trabajá con trazabilidad',summary:finalEvidence?'El trabajo tiene evidencia final registrada. Revisá cobro y cierre.':'El servicio está en curso. Hugo te guía para cerrar sin saltar pasos.',items:['Seguí el alcance aprobado y registrá cualquier ampliación antes de ejecutarla.','Si surge un problema técnico o de seguridad, detené el avance y resolvelo antes de continuar.',finalEvidence?'Verificá que la evidencia “Después” muestre el resultado final.':'Al terminar, subí evidencia “Después” antes de pedir aprobación.',cashSelected&&!cashConfirmed?'Si el cliente paga en efectivo, confirmá la recepción real antes del cierre.':'No marques dinero como recibido o liberado si no ocurrió realmente.'],tone:finalEvidence?'ready':'working'}
 if(service.estado==='esperando_aprobacion')return{title:'Cierre en revisión',summary:cashSelected&&!cashConfirmed?'El trabajo terminó, pero falta registrar la recepción del efectivo.':'El cliente está revisando el cierre. No hace falta crear otro estado ni repetir el trabajo.',items:[cashSelected&&!cashConfirmed?'Confirmá efectivo únicamente si ya lo recibiste.':'Mantené disponible la evidencia final por si el cliente la revisa.','No agregues alcance nuevo mientras este cierre está pendiente.','Si el cliente abre una disputa, respondé desde UGO con evidencia y contexto del mismo servicio.'],tone:cashSelected&&!cashConfirmed?'attention':'done'}
 return{title:'Servicio actualizado',summary:'Hugo usa el estado real del servicio para orientarte.',items:['Revisá la actividad e historial antes de realizar una nueva acción.'],tone:'done'}
}

export function ProviderWorkAssistant(props:Props){
 const stage=buildStage(props)
 return <article className={`provider-hugo-assistant is-${stage.tone}`} aria-labelledby="provider-hugo-title"><header><div className="provider-hugo-orb" aria-hidden="true">H</div><div><small>HUGO · ASISTENTE DE TRABAJO</small><h2 id="provider-hugo-title">{stage.title}</h2></div></header><p>{stage.summary}</p><ul>{stage.items.map(item=><li key={item}>{item}</li>)}</ul><footer>Guía contextual basada en el estado real del servicio. Hugo no modifica pagos, estados ni alcance sin una acción válida.</footer></article>
}
