import{useCallback,useEffect,useRef,useState}from'react'
import{useProviderFlow}from'./providerFlow'
import{useProviderData}from'./providerData'
import'../voice.css'

type VoiceState='idle'|'connecting'|'ready'|'hearing'|'speaking'|'error'
type NativeBridge={startListening:()=>void|Promise<void>;stopListening:()=>void;isAvailable?:()=>boolean;stopSpeaking?:()=>void;sendToolResponse?:(id:string,name:string,response:Record<string,unknown>)=>boolean}
type UgoWindow=Window&typeof globalThis&{UGOVoiceBridge?:NativeBridge}

const LABELS:Record<VoiceState,string>={idle:'Toca para hablar',connecting:'Procesando...',ready:'Te escucho',hearing:'Escuchando...',speaking:'Hablando...',error:'Voz no disponible'}
const ugoWindow=()=>window as UgoWindow
const ignoreError=(value:unknown)=>{void value}

export function ProviderHugoBridge(){
 const flow=useProviderFlow(),data=useProviderData()
 const{actions}=flow
 const[state,setState]=useState<VoiceState>('idle'),[error,setError]=useState(''),[assistantTranscript,setAssistantTranscript]=useState(''),[voiceRunning,setVoiceRunning]=useState(false),[panelOpen,setPanelOpen]=useState(false)
 const running=useRef(false)

 const setRunning=useCallback((value:boolean)=>{running.current=value;setVoiceRunning(value)},[])
 const stopSpeech=useCallback(()=>{try{ugoWindow().UGOVoiceBridge?.stopSpeaking?.()}catch(caught){ignoreError(caught)}},[])
 const executeTool=useCallback(async(name:string,args:Record<string,unknown>)=>{
  if(name==='provider_set_online'){if(data.online)return{ok:true,data:{online:true}};const ok=await data.toggleOnline();return ok?{ok:true,data:{online:true}}:{ok:false,code:'AVAILABILITY_FAILED',message:'UGO no pudo poner al proveedor Online'}}
  if(name==='provider_set_offline'){if(!data.online)return{ok:true,data:{online:false}};const ok=await data.toggleOnline();return ok?{ok:true,data:{online:false}}:{ok:false,code:'AVAILABILITY_FAILED',message:'UGO no pudo poner al proveedor Offline'}}
  if(name==='provider_list_opportunities')return{ok:true,data:{opportunities:data.opportunities.map(item=>({id:item.id,serviceId:item.serviceId,category:item.category,title:item.title,zone:item.zone,distanceKm:item.distanceKm,estimatedValue:item.estimatedValue,urgency:item.urgency,status:'ofrecido'}))}}
  if(name==='provider_accept_job'){const serviceId=String(args.service_id||'');const item=data.opportunities.find(item=>String(item.serviceId)===serviceId||String(item.id)===serviceId);if(!item)return{ok:false,code:'SERVICE_NOT_FOUND',message:'No encontré esa oportunidad'};const ok=await actions.acceptOpportunity(item.id);return ok?{ok:true,data:{serviceId:item.serviceId}}:{ok:false,code:'ACCEPT_FAILED',message:'UGO no permitió aceptar ese trabajo'}}
  if(name==='provider_reject_job'){const serviceId=String(args.service_id||'');const item=data.opportunities.find(item=>String(item.serviceId)===serviceId||String(item.id)===serviceId);if(!item)return{ok:false,code:'SERVICE_NOT_FOUND',message:'No encontré esa oportunidad'};const ok=await actions.rejectOpportunity(item.id);return ok?{ok:true,data:{serviceId:item.serviceId}}:{ok:false,code:'REJECT_FAILED',message:'UGO no permitió rechazar ese trabajo'}}
  if(name==='provider_get_current_job'){if(!data.service)return{ok:false,code:'NO_ACTIVE_JOB',message:'No tenés un trabajo operativo activo ahora'};return{ok:true,data:{serviceId:data.service.id,state:data.service.estado,category:data.service.categoria?.nombre||'Servicio',description:data.service.descripcion||''}}}
  if(name==='provider_mark_en_route'){if(!data.service)return{ok:false,code:'NO_ACTIVE_JOB',message:'No tenés un trabajo activo'};if(data.service.estado==='en_camino')return{ok:true,data:{serviceId:data.service.id,status:'en_camino',idempotent:true}};if(data.service.estado!=='asignado')return{ok:false,code:'INVALID_TRANSITION',message:'Este trabajo no está listo para iniciar el traslado'};const ok=await data.advance('en_camino');return ok?{ok:true,data:{serviceId:data.service.id,status:'en_camino'}}:{ok:false,code:'STATUS_FAILED',message:'UGO no permitió iniciar el traslado'}}
  if(name==='provider_mark_arrived'){if(!data.service)return{ok:false,code:'NO_ACTIVE_JOB',message:'No tenés un trabajo activo'};if(['llegado','en_progreso','esperando_aprobacion'].includes(String(data.service.estado)))return{ok:true,data:{serviceId:data.service.id,status:data.service.estado,idempotent:true}};if(data.service.estado!=='en_camino')return{ok:false,code:'INVALID_TRANSITION',message:'Primero tenés que estar en camino'};const ok=await data.advance('llegado');return ok?{ok:true,data:{serviceId:data.service.id,status:'llegado'}}:{ok:false,code:'ARRIVAL_REJECTED',message:'UGO no pudo validar la llegada. Revisá GPS, precisión y distancia e intentá de nuevo.'}}
  if(name==='provider_start_job'){if(!data.service)return{ok:false,code:'NO_ACTIVE_JOB',message:'No tenés un trabajo activo'};if(['en_progreso','esperando_aprobacion'].includes(String(data.service.estado)))return{ok:true,data:{serviceId:data.service.id,status:data.service.estado,idempotent:true}};if(data.service.estado!=='llegado')return{ok:false,code:'INVALID_TRANSITION',message:'La llegada debe estar confirmada antes de empezar'};const ok=await data.advance('en_progreso');return ok?{ok:true,data:{serviceId:data.service.id,status:'en_progreso'}}:{ok:false,code:'STATUS_FAILED',message:'UGO no permitió iniciar el trabajo'}}
  if(name==='provider_complete_job'){if(!data.service)return{ok:false,code:'NO_ACTIVE_JOB',message:'No tenés un trabajo activo'};if(data.service.estado==='esperando_aprobacion')return{ok:true,data:{serviceId:data.service.id,status:'esperando_aprobacion',idempotent:true}};if(data.service.estado!=='en_progreso')return{ok:false,code:'INVALID_TRANSITION',message:'El trabajo debe estar en progreso antes de terminarlo'};const ok=await data.completeService();return ok?{ok:true,data:{serviceId:data.service.id,status:'esperando_aprobacion'}}:{ok:false,code:'STATUS_FAILED',message:'UGO no pudo cerrar el trabajo'}}
  return{ok:false,code:'UNKNOWN_TOOL',message:'Herramienta no disponible para Proveedor'}
 },[actions,data])


 const stop=useCallback(()=>{setPanelOpen(false);setRunning(false);stopSpeech();try{ugoWindow().UGOVoiceBridge?.stopListening?.()}catch{}setState('idle');setError('')},[setRunning,stopSpeech])
 const start=useCallback(async()=>{setPanelOpen(true);setError('');setState('connecting');const bridge=ugoWindow().UGOVoiceBridge;if(!bridge||bridge.isAvailable?.()===false){setState('error');setError('Gemini Live no está disponible. Tocá el orbe para reconectar.');return}setRunning(true);try{await bridge.startListening();if(running.current)setState('ready')}catch(caught){console.warn('Gemini Live no disponible.',caught);try{bridge.stopListening()}catch(stopError){ignoreError(stopError)}setRunning(false);setState('error');setError('Gemini Live no está disponible. Tocá el orbe para reconectar.')}},[setRunning])


 useEffect(()=>{const tool=async(event:Event)=>{if(!running.current)return;const detail=(event as CustomEvent<{id?:string;name?:string;args?:Record<string,unknown>}>).detail||{},id=String(detail.id||''),name=String(detail.name||''),bridge=ugoWindow().UGOVoiceBridge;if(!id||!name||!bridge?.sendToolResponse)return;setState('connecting');try{const response=await executeTool(name,detail.args||{});bridge.sendToolResponse(id,name,response)}catch(error){bridge.sendToolResponse(id,name,{ok:false,code:'TOOL_FAILED',message:error instanceof Error?error.message:'La acción falló'})}};const output=(event:Event)=>{const text=String((event as CustomEvent<{text?:string}>).detail?.text||'').trim();if(text)setAssistantTranscript(text)};const stateEvent=(event:Event)=>{if(!running.current)return;const value=String((event as CustomEvent<{state?:string}>).detail?.state||'');if(value==='hearing'){stopSpeech();setState('hearing')}else if(value==='connecting')setState('connecting');else if(value==='speaking')setState('speaking');else if(value==='ready')setState('ready')};const voiceError=(event:Event)=>{const code=String((event as CustomEvent<{code?:string}>).detail?.code||'');setRunning(false);setState('error');setError(code==='not-allowed'?'Permití el micrófono para hablar con Hugo.':code==='session'?'Tu sesión venció. Volvé a iniciar sesión.':'Gemini Live no está disponible. Tocá el orbe para reconectar.')};window.addEventListener('ugo:native-voice-tool-call',tool);window.addEventListener('ugo:native-voice-output',output);window.addEventListener('ugo:native-voice-state',stateEvent);window.addEventListener('ugo:native-voice-error',voiceError);return()=>{window.removeEventListener('ugo:native-voice-tool-call',tool);window.removeEventListener('ugo:native-voice-output',output);window.removeEventListener('ugo:native-voice-state',stateEvent);window.removeEventListener('ugo:native-voice-error',voiceError)}},[executeTool,setRunning,stopSpeech])

 useEffect(()=>()=>stop(),[stop])

 const visual=state==='speaking'?'speaking':state==='connecting'?'thinking':state==='hearing'?'listening':state==='ready'?'ready':state==='error'?'error':'idle'
 return <section className={`ugo-real-hugo prototype-hugo provider-global-hugo state-${visual}`} aria-label="Hugo, controlador por voz del proveedor">{panelOpen&&<div className="ugo-hugo-voice-controller" role="status" aria-live="polite"><small>HUGO · PROVEEDOR</small><strong>{LABELS[state]}</strong>{assistantTranscript&&<span>{assistantTranscript}</span>}{error&&<span className="ugo-hugo-stage-error">{error}</span>}</div>}<button type="button" className="ugo-real-orb" onClick={()=>voiceRunning?stop():void start()} aria-label={voiceRunning?'Cortar conversación con Hugo':'Hablar con Hugo'}><span className="ugo-orb-glass"/><span className="ugo-orb-ring ring-1"/><span className="ugo-orb-ring ring-2"/><span className="ugo-orb-icon">{state==='connecting'?'✦':state==='hearing'?'●':'⌁'}</span></button><div className="ugo-real-state"><i/><span>{LABELS[state]}</span></div></section>
}

export default ProviderHugoBridge
