import React,{createContext,useCallback,useContext,useEffect,useState}from'react'
import{AuthScreen,LoadingScreen,timeAgo,money,useRoleSession,type Notice,type Offer,type Service}from'../shared'
import{ProviderOnboardingGate}from'../ProviderOnboardingGate'
import{acceptProviderOpportunity,advanceProviderService,loadProviderSnapshot,rejectProviderOpportunity,setProviderAvailability,type ProviderPayment,type ProviderProfileFull}from'./providerService'
import{useProviderRealtime}from'./useProviderRealtime'
import type{DemandSignal,ProviderOpportunity}from'./providerTypes'

type ProviderData={name:string;karma:number;provider:ProviderProfileFull;offers:Offer[];opportunities:ProviderOpportunity[];demand:DemandSignal[];demandError:string|null;service:Service|null;payments:ProviderPayment[];online:boolean;released:number;retained:number;busy:boolean;notice:Notice;reload:()=>Promise<void>;toggleOnline:()=>Promise<boolean>;acceptOpportunity:(id:string)=>Promise<boolean>;rejectOpportunity:(id:string)=>Promise<boolean>;advance:(state:'en_camino'|'llegado'|'en_progreso'|'esperando_aprobacion')=>Promise<boolean>;completeService:()=>Promise<boolean>;funded:boolean;cashSelected:boolean;cashConfirmed:boolean;confirmCash:()=>Promise<boolean>;accessToken:string;saveProfile:(input:{bio:string|null;tarifa_base:number;ciudad_base:string|null;zona_radio_km:number})=>Promise<boolean>;signOut:()=>Promise<void>}
type DemandRow={zona_lat:number|string|null;zona_lng:number|string|null;pedidos:number|string|null;urgentes:number|string|null;tarifa_promedio:number|string|null;ultimo_pedido:string|null}
type PixAwarePayment=ProviderPayment&{pix_e2e_id?:string|null}
type OpportunityMetadata={requested_when?:unknown;preferences?:unknown;estimated_duration_minutes?:unknown}
type OpportunityService=Service&{zona_cliente?:string|null;programado_para?:string|null;metadata?:OpportunityMetadata|null}
const C=createContext<ProviderData|null>(null)
const isProtectedPayment=(payment:ProviderPayment|null|undefined)=>Boolean(payment&&(payment.mp_payment_id||payment.pago_externo_id||(payment as PixAwarePayment).pix_e2e_id))
const coordinate=(value:number|string|null)=>{if(value==null||value==='')return null;const parsed=Number(value);return Number.isFinite(parsed)?parsed:null}
const textValue=(value:unknown)=>typeof value==='string'&&value.trim()?value.trim():null
const positiveNumber=(value:unknown)=>{const parsed=Number(value);return Number.isFinite(parsed)&&parsed>0?parsed:null}
const LIFECYCLE_ORDER=['asignado','en_camino','llegado','en_progreso','esperando_aprobacion','completado'] as const

export function ProviderDataProvider({children}:{children:React.ReactNode}){
 const auth=useRoleSession('provider'),{supabase,session,profile}=auth
 const[provider,setProvider]=useState<ProviderProfileFull|null>(null),[offers,setOffers]=useState<Offer[]>([]),[service,setService]=useState<Service|null>(null),[payments,setPayments]=useState<ProviderPayment[]>([]),[demand,setDemand]=useState<DemandSignal[]>([]),[demandError,setDemandError]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null)
 const reload=useCallback(async()=>{if(!session){setDemand([]);setDemandError(null);setLoading(false);return}const snap=await loadProviderSnapshot(supabase,session.user.id);setProvider(snap.provider);setOffers(snap.offers);setService(snap.service);setPayments(snap.payments);let nextDemand:DemandSignal[]=[];setDemandError(null);if(snap.provider?.estado_verificacion==='verificado'){const categoryId=snap.provider.categoria_principal_id||null;const[{data:market,error:marketError},{data:category}]=await Promise.all([supabase.rpc('obtener_demanda_proveedor',{p_categoria_id:categoryId,p_horas:24}),categoryId?supabase.from('categorias').select('nombre').eq('id',categoryId).maybeSingle():Promise.resolve({data:null,error:null})]);if(marketError){setDemandError('No pudimos actualizar el radar de demanda. Podés reintentar sin perder tus oportunidades.')}else{const categoryName=String(category?.nombre||'Tu categoría');nextDemand=((market||[])as DemandRow[]).map((row,index)=>{const requests=Math.max(0,Number(row.pedidos||0)),urgent=Math.max(0,Number(row.urgentes||0)),ratio=requests?urgent/requests:0,latitude=coordinate(row.zona_lat),longitude=coordinate(row.zona_lng);return{id:`demand-${latitude??'x'}-${longitude??'x'}-${index}`,category:categoryName,zone:`Zona activa ${index+1} · ${requests} pedido${requests===1?'':'s'} reciente${requests===1?'':'s'}`,latitude,longitude,distanceKm:0,estimatedValue:Number(row.tarifa_promedio||0),requestedAt:row.ultimo_pedido||new Date().toISOString(),urgency:ratio>=.5?'high':urgent>0?'medium':'low',demandLevel:requests>=6||ratio>=.5?'high':requests>=3?'medium':'low'}})}}setDemand(nextDemand);setLoading(false)},[session,supabase])
 const handleRealtime=useCallback(()=>{reload().catch(()=>{})},[reload])
 useEffect(()=>{if(session)reload().catch((e:Error)=>{setNotice({type:'error',text:e.message});setLoading(false)});else setLoading(false)},[reload,session])
 const marketAutoRefresh=Boolean(session&&provider?.estado_verificacion==='verificado'&&provider.disponible)
 useEffect(()=>{if(!marketAutoRefresh)return;let disposed=false;const refresh=()=>{if(!disposed&&document.visibilityState!=='hidden')void reload().catch(()=>{})};const timer=window.setInterval(refresh,45_000);const onFocus=()=>refresh();const onVisibility=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisibility);return()=>{disposed=true;window.clearInterval(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisibility)}},[marketAutoRefresh,reload])
 useProviderRealtime(supabase,session?.user.id||null,handleRealtime)
 if(auth.loading||loading)return <LoadingScreen label="Preparando UGO Pro…"/>
 if(!session||!profile)return <AuthScreen role="provider" supabase={supabase} error={auth.error} onError={auth.setError}/>
 if(!provider||provider.estado_verificacion!=='verificado')return <ProviderOnboardingGate onVerified={reload}/>
 const run=async(fn:()=>Promise<void>,ok:string)=>{setBusy(true);setNotice(null);try{await fn();setNotice({type:'ok',text:ok});await reload();return true}catch(e){try{await reload()}catch{}setNotice({type:'error',text:e instanceof Error?e.message:'No se pudo completar la acción. Actualizamos el estado real para que puedas reintentar.'});return false}finally{setBusy(false)}}
 const toggleOnline=()=>run(()=>setProviderAvailability(supabase,session.user.id,!provider.disponible),provider.disponible?'Quedaste Offline.':'Ya estás Online.')
 const acceptOpportunity=(id:string)=>{if(service){setNotice({type:'info',text:'Ya tenés un trabajo activo. Finalizalo antes de aceptar otro.'});return Promise.resolve(false)}return run(()=>acceptProviderOpportunity(supabase,id),'Trabajo aceptado.')}
 const rejectOpportunity=(id:string)=>run(()=>rejectProviderOpportunity(supabase,id),'Pedido rechazado.')
 const currentPayment=service?payments.find(p=>p.servicio_id===service.id):null
 const funded=currentPayment?.estado==='retenido'&&isProtectedPayment(currentPayment)
 const cashSelected=currentPayment?.metodo==='efectivo'
 const cashConfirmed=cashSelected&&currentPayment?.estado==='liberado'
 const transitionPersisted=async(serviceId:string,target:string)=>{const{data}=await supabase.from('servicios').select('estado').eq('id',serviceId).eq('proveedor_id',session.user.id).maybeSingle();const current=LIFECYCLE_ORDER.indexOf(String(data?.estado||'') as typeof LIFECYCLE_ORDER[number]),wanted=LIFECYCLE_ORDER.indexOf(target as typeof LIFECYCLE_ORDER[number]);return wanted>=0&&current>=wanted}
 const advance=async(state:'en_camino'|'llegado'|'en_progreso'|'esperando_aprobacion')=>{if(!service)return false;if(service.estado==='asignado'&&!funded&&!cashSelected){setNotice({type:'info',text:'Todavía falta que el cliente confirme la forma de pago.'});return false}if(state==='esperando_aprobacion'&&cashSelected&&!cashConfirmed){setNotice({type:'info',text:'Primero confirmá que recibiste el efectivo. Después UGO habilita la aprobación del cliente.'});return false}const serviceId=service.id;setBusy(true);setNotice(null);try{await advanceProviderService(supabase,serviceId,state);setNotice({type:'ok',text:state==='en_camino'?'UGO avisó que estás yendo.':state==='llegado'?'Llegada confirmada.':state==='en_progreso'?'Trabajo iniciado.':'Estado del servicio actualizado.'});await reload();return true}catch(e){if(await transitionPersisted(serviceId,state)){setNotice({type:'ok',text:'Estado del servicio actualizado.'});await reload();return true}try{await reload()}catch{}setNotice({type:'error',text:e instanceof Error?e.message:'No se pudo actualizar el servicio. Actualizamos el estado real para que puedas reintentar.'});return false}finally{setBusy(false)}}
 const confirmCash=async()=>{if(!service)return false;const serviceId=service.id;setBusy(true);setNotice(null);try{const{error}=await supabase.rpc('confirmar_pago_efectivo',{p_servicio_id:serviceId});if(error){const{data:persisted}=await supabase.from('pagos').select('id').eq('servicio_id',serviceId).eq('proveedor_id',session.user.id).eq('metodo','efectivo').eq('estado','liberado').limit(1);if(persisted?.length){setNotice({type:'ok',text:'Efectivo recibido y registrado.'});await reload();return true}throw error}setNotice({type:'ok',text:'Efectivo recibido y registrado.'});await reload();return true}catch(e){try{await reload()}catch{}setNotice({type:'error',text:e instanceof Error?e.message:'No se pudo confirmar el efectivo. Actualizamos el estado real para que puedas reintentar.'});return false}finally{setBusy(false)}}
 const completeService=async()=>{if(!service||service.estado!=='en_progreso')return false;const serviceId=service.id;setBusy(true);setNotice(null);try{if(cashSelected&&!cashConfirmed){const{error}=await supabase.rpc('confirmar_pago_efectivo',{p_servicio_id:serviceId});if(error){const{data:persisted}=await supabase.from('pagos').select('id').eq('servicio_id',serviceId).eq('proveedor_id',session.user.id).eq('metodo','efectivo').eq('estado','liberado').limit(1);if(!persisted?.length)throw error}}try{await advanceProviderService(supabase,serviceId,'esperando_aprobacion')}catch(e){if(!(await transitionPersisted(serviceId,'esperando_aprobacion')))throw e}setNotice({type:'ok',text:'Listo. UGO avisó al cliente y sigue el cierre por detrás.'});await reload();return true}catch(e){try{await reload()}catch{}setNotice({type:'error',text:e instanceof Error?e.message:'No pudimos cerrar el trabajo. Tu avance quedó guardado para reintentar.'});return false}finally{setBusy(false)}}
 const opportunities:ProviderOpportunity[]=offers.map(offer=>{const serviceData=(offer.servicio||null)as OpportunityService|null,duration=positiveNumber(serviceData?.metadata?.estimated_duration_minutes);return{id:offer.id,serviceId:offer.servicio_id,category:serviceData?.categoria?.nombre||'Servicio',title:serviceData?.descripcion||'Nueva oportunidad',description:serviceData?.descripcion||'',zone:serviceData?.zona_cliente||'Zona por confirmar',distanceKm:Number(offer.distancia_km||0),estimatedValue:Number(offer.tarifa_ofrecida||serviceData?.tarifa||0),requestedAt:serviceData?.created_at||new Date().toISOString(),scheduledAt:serviceData?.programado_para||null,durationMinutes:duration,preferences:textValue(serviceData?.metadata?.preferences),urgency:serviceData?.urgencia?'urgent':'normal',matchScore:offer.ranking==null?undefined:Number(offer.ranking)}})
 const released=payments.filter(p=>p.estado==='liberado').reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0),retained=payments.filter(p=>p.estado==='retenido'&&isProtectedPayment(p)).reduce((n,p)=>n+Number(p.ganancia_proveedor||0),0)
 const saveProfile=(input:{bio:string|null;tarifa_base:number;ciudad_base:string|null;zona_radio_km:number})=>run(async()=>{const{error}=await(supabase as any).from('perfiles_proveedor').update(input).eq('usuario_id',session.user.id);if(error)throw error},'Perfil profesional actualizado.')
 const signOut=async()=>{setBusy(true);const{error}=await supabase.auth.signOut();setBusy(false);if(error){setNotice({type:'error',text:error.message});return}window.location.replace(window.location.pathname+'?app=provider')}
 const value:ProviderData={name:profile.nombre,karma:Number(profile.karma||5),provider,offers,opportunities,demand,demandError,service,payments,online:Boolean(provider.disponible),released,retained,busy,notice,reload,toggleOnline,acceptOpportunity,rejectOpportunity,advance,completeService,funded,cashSelected,cashConfirmed,confirmCash,accessToken:session.access_token,saveProfile,signOut}
 return <C.Provider value={value}>{children}</C.Provider>
}
export function useProviderData(){const v=useContext(C);if(!v)throw new Error('useProviderData debe usarse dentro de ProviderDataProvider');return v}
export{timeAgo,money}
