import{useCallback,useEffect,useRef,useState}from'react'
import{useProviderFlow}from'./providerFlow'
import{useProviderData}from'./providerData'
import{UGO_UI_EVENTS}from'../uiEvents'
import'../voice.css'

type VoiceState='idle'|'connecting'|'ready'|'hearing'|'speaking'|'error'
type NativeBridge={startListening:()=>void|Promise<void>;stopListening:()=>void;isAvailable?:()=>boolean;stopSpeaking?:()=>void;sendToolResponse?:(id:string,name:string,response:Record<string,unknown>)=>boolean}
type UgoWindow=Window&typeof globalThis&{UGOVoiceBridge?:NativeBridge}

const LABELS:Record<VoiceState,string>={idle:'Toca para hablar',connecting:'Procesando...',ready:'Te escucho',hearing:'Escuchando...',speaking:'Hablando...',error:'Voz no disponible'}
const ugoWindow=()=>window as UgoWindow
const ignoreError=(value:unknown)=>{void value}

export function ProviderHugoBridge(){
 const flow=useProviderFlow(),data=useProviderData()
 const{actions}=flow
 const[state,setState]=useState<VoiceState>('idle'),[error,setError]=useState(''),[assistantTranscript,setAssistantTranscript]=useState(''),[voiceRunning,setVoiceRunning]=useState(false),[panelOpen,setPanelOpen]=useState(false)
 const running=useRef(false)

 const setRunning=useCallback((value:boolean)=>{running.current=value;setVoiceRunning(value)},[])
 const stopSpeech=useCallback(()=>{try{ugoWindow().UGOVoiceBridge?.stopSpeaking?.()}catch(caught){ignoreError(caught)}},[])
 const executeTool=useCallback(async(name:string,args:Record<string,unknown>)=>{
  if(name==='provider_set_online'){if(args.confirmed!==true)return{ok:false,code:'CONFIRMATION_REQUIRED',message:'Necesito que confirmes explícitamente que querés quedar Online'};if(data.online)return{ok:true,data:{online:true}};const ok=await data.toggleOnline(true);return ok?{ok:true,data:{online:true}}:{ok:false,code:'AVAILABILITY_FAILED',message:'UGO no pudo poner al proveedor Online'}}
  if(name==='provider_set_offline'){if(args.confirmed!==true)return{ok:false,code:'CONFIRMATION_REQUIRED',message:'Necesito que confirmes explícitamente que querés quedar Offline'};if(!data.online)return{ok:true,data:{online:false}};const ok=await data.toggleOnline(false);return ok?{ok:true,data:{online:false}}:{ok:false,code:'AVAILABILITY_FAILED',message:'UGO no pudo poner al proveedor Offline'}}
  if(name==='provider_list_opportunities')return{ok:true,data:{opportunities:data.opportunities.map(item=>({id:item.id,serviceId:item.serviceId,category:item.category,title:item.title,zone:item.zone,distanceKm:item.distanceKm,estimatedValue:item.estimatedValue,urgency:item.urgency,status:'ofrecido'}))}}
  if(name==='provider_get_active_service'){if(!data.service)return{ok:true,data:{service:null},message:'No tenés un trabajo activo en este momento'};return{ok:true,data:{service:{serviceId:data.service.id,state:data.service.estado,category:data.service.categoria?.nombre||null,client:data.service.cliente?.nombre||null}},message:'Trabajo activo encontrado'}}
  if(name==='provider_accept_job'){const requestedId=String(args.service_id||'');if(args.confirmed!==true)return{ok:false,code:'CONFIRMATION_REQUIRED',message:'Necesito que confirmes explícitamente que querés aceptar ese trabajo'};const item=data.opportunities.find(item=>String(item.id)===requestedId||String(item.serviceId)===requestedId);if(!item)return{ok:false,code:'SERVICE_NOT_FOUND',message:'No encontré esa oportunidad'};const ok=await actions.acceptOpportunity(item.id);return ok?{ok:true,data:{serviceId:item.serviceId,opportunityId:item.id}}:{ok:false,code:'ACCEPT_FAILED',message:'UGO no permitió aceptar ese trabajo'}}
  if(name==='provider_reject_job'){const requestedId=String(args.service_id||'');if(args.confirmed!==true)return{ok:false,code:'CONFIRMATION_REQUIRED',message:'Necesito que confirmes explícitamente que querés rechazar esa oportunidad'};const item=data.opportunities.find(item=>String(item.id)===requestedId||String(item.serviceId)===requestedId);if(!item)return{ok:false,code:'SERVICE_NOT_FOUND',message:'No encontré esa oportunidad'};const ok=await actions.rejectOpportunity(item.id);return ok?{ok:true,data:{serviceId:item.serviceId,opportunityId:item.id}}:{ok:false,code:'REJECT_FAILED',message:'UGO no permitió rechazar ese trabajo'}}
  if(name==='provider_update_service_status'){const serviceId=String(args.service_id||''),status=String(args.status||'');if(args.confirmed!==true)return{ok:false,code:'CONFIRMATION_REQUIRED',message:'Necesito que confirmes explícitamente el cambio de estado del trabajo'};if(!data.service||String(data.service.id)!==serviceId)return{ok:false,code:'SERVICE_NOT_FOUND',message:'Ese no es el servicio activo'};const allowed:Record<string,string[]>= {asignado:['en_camino'],en_camino:['llegado'],llegado:['en_progreso'],en_progreso:['esperando_aprobacion']};if(!(allowed[String(data.service.estado)]||[]).includes(status))return{ok:false,code:'INVALID_TRANSITION',message:'Ese cambio de estado no está permitido por el flujo actual'};const ok=status==='esperando_aprobacion'?await data.completeService():await data.advance(status as 'en_camino'|'llegado'|'en_progreso');return ok?{ok:true,data:{serviceId,status}}:{ok:false,code:'STATUS_FAILED',message:'UGO no pudo actualizar el estado'}}
  return{ok:false,code:'UNKNOWN_TOOL',message:'Herramienta no disponible para Proveedor'}
 },[actions,data])


 const stop=useCallback(()=>{setPanelOpen(false);setRunning(false);stopSpeech();try{ugoWindow().UGOVoiceBridge?.stopListening?.()}catch{}setState('idle');setError('')},[setRunning,stopSpeech])
 const start=useCallback(async()=>{setPanelOpen(true);setError('');setState('connecting');const bridge=ugoWindow().UGOVoiceBridge;if(!bridge||bridge.isAvailable?.()===false){setState('error');setError('La voz no está disponible en este navegador.');return}setRunning(true);const timeout=window.setTimeout(()=>{if(!running.current)return;try{bridge.stopListening()}catch(stopError){ignoreError(stopError)}setRunning(false);setState('error');setError('Hugo no pudo conectar con el servicio de voz. Reintentá en unos segundos.')},9000);try{await bridge.startListening();window.clearTimeout(timeout);if(running.current)setState('ready')}catch(caught){window.clearTimeout(timeout);console.warn('Gemini Live no disponible.',caught);try{bridge.stopListening()}catch(stopError){ignoreError(stopError)}setRunning(false);setState('error');setError('Hugo no pudo conectar con el servicio de voz. Reintentá en unos segundos.')}},[setRunning])


 useEffect(()=>{const tool=async(event:Event)=>{if(!running.current)return;const detail=(event as CustomEvent<{id?:string;name?:string;args?:Record<string,unknown>}>).detail||{},id=String(detail.id||''),name=String(detail.name||''),bridge=ugoWindow().UGOVoiceBridge;if(!id||!name||!bridge?.sendToolResponse)return;setState('connecting');try{const response=await executeTool(name,detail.args||{});bridge.sendToolResponse(id,name,response)}catch(error){bridge.sendToolResponse(id,name,{ok:false,code:'TOOL_FAILED',message:error instanceof Error?error.message:'La acción falló'})}};const output=(event:Event)=>{const text=String((event as CustomEvent<{text?:string}>).detail?.text||'').trim();if(text)setAssistantTranscript(text)};const stateEvent=(event:Event)=>{if(!running.current)return;const value=String((event as CustomEvent<{state?:string}>).detail?.state||'');if(value==='hearing'){stopSpeech();setState('hearing')}else if(value==='connecting')setState('connecting');else if(value==='speaking')setState('speaking');else if(value==='ready')setState('ready')};const voiceError=(event:Event)=>{const code=String((event as CustomEvent<{code?:string}>).detail?.code||'');setRunning(false);setState('error');setError(code==='not-allowed'?'Permití el micrófono para hablar con Hugo.':code==='no-microphone'?'No encontré un micrófono disponible en este dispositivo.':code==='microphone-busy'?'El micrófono está ocupado por otra aplicación.':code==='session'?'Tu sesión venció. Volvé a iniciar sesión.':'Gemini Live no está disponible. Tocá el orbe para reconectar.')};window.addEventListener('ugo:native-voice-tool-call',tool);window.addEventListener('ugo:native-voice-output',output);window.addEventListener('ugo:native-voice-state',stateEvent);window.addEventListener('ugo:native-voice-error',voiceError);return()=>{window.removeEventListener('ugo:native-voice-tool-call',tool);window.removeEventListener('ugo:native-voice-output',output);window.removeEventListener('ugo:native-voice-state',stateEvent);window.removeEventListener('ugo:native-voice-error',voiceError)}},[executeTool,setRunning,stopSpeech])

 useEffect(()=>{const stopGlobal=()=>stop();window.addEventListener(UGO_UI_EVENTS.globalVoiceStop,stopGlobal);return()=>window.removeEventListener(UGO_UI_EVENTS.globalVoiceStop,stopGlobal)},[stop])
 useEffect(()=>()=>stop(),[stop])

 const visual=state==='speaking'?'speaking':state==='connecting'?'thinking':state==='hearing'?'listening':state==='ready'?'ready':state==='error'?'error':'idle'
 return <section className={`ugo-real-hugo prototype-hugo provider-global-hugo state-${visual}`} aria-label="Hugo, controlador por voz del proveedor">{panelOpen&&<div className="ugo-hugo-voice-controller" role="status" aria-live="polite"><small>HUGO · PROVEEDOR</small><strong>{LABELS[state]}</strong>{assistantTranscript&&<span>{assistantTranscript}</span>}{error&&<span className="ugo-hugo-stage-error">{error}</span>}</div>}<button type="button" className="ugo-real-orb" onClick={()=>voiceRunning?stop():void start()} aria-label={voiceRunning?'Cortar conversación con Hugo':'Hablar con Hugo'}><span className="ugo-orb-glass"/><span className="ugo-orb-ring ring-1"/><span className="ugo-orb-ring ring-2"/><span className="ugo-orb-icon">{state==='connecting'?'✦':state==='hearing'?'●':'⌁'}</span></button><div className="ugo-real-state"><i/><span>{LABELS[state]}</span></div></section>
}

export default ProviderHugoBridge
