import React from'react'
import{useProviderFlow}from'./providerFlow'
import{useProviderData,money,timeAgo}from'./providerData'
import{ProviderRequestEvidence}from'./ProviderRequestEvidence'
import type{ProviderOpportunity}from'./providerTypes'

function rankOpportunity(item:ProviderOpportunity){const urgent=item.urgency==='urgent'?1000:0,match=Number(item.matchScore||0)*4,value=Math.min(Number(item.estimatedValue||0),1000)/20,distance=Math.min(Math.max(item.distanceKm,0),50)*6;return urgent+match+value-distance}

export function ProviderOpportunities(){const flow=useProviderFlow(),d=useProviderData();const items=[...d.opportunities].sort((a,b)=>rankOpportunity(b)-rankOpportunity(a));return <section className="provider-screen" aria-labelledby="provider-opportunities-title"><header className="provider-section-head"><div><span className="provider-kicker">PEDIDOS PARA VOS</span><h1 id="provider-opportunities-title">Oportunidades</h1><p>Priorizadas por urgencia, compatibilidad, valor y cercanía.</p></div><button className="provider-link" onClick={flow.actions.openDemand}>Ver radar</button></header>{items.length>0&&<article className="provider-priority-summary"><small>PRIORIDAD UGO</small><strong>{items[0].category}</strong><span>{items[0].urgency==='urgent'?'Urgente · ':''}{items[0].distanceKm>0?`${items[0].distanceKm.toFixed(1)} km · `:''}{money(items[0].estimatedValue)}</span><button className="provider-secondary" onClick={()=>flow.actions.openOpportunity(items[0].id)}>Revisar mejor oportunidad</button></article>}<div className="provider-list">{items.length===0?<article className="provider-card provider-empty"><strong>No hay oportunidades pendientes</strong><span>{d.online?'Seguimos buscando en tiempo real.':'Ponete Online desde Inicio para recibir trabajos.'}</span><button className="provider-secondary provider-wide" onClick={flow.actions.openDemand}>Explorar demanda</button></article>:items.map((item,index)=><article className={`provider-card provider-opportunity ${index===0?'is-priority':''}`} key={item.id}><div className="provider-opportunity-main"><div className="provider-opportunity-meta">{index===0&&<span className="provider-chip is-best">Mejor para vos</span>}<span className={`provider-chip ${item.urgency==='urgent'?'is-urgent':''}`}>{item.urgency==='urgent'?'Urgente':'Disponible'}</span><span>{timeAgo(item.requestedAt)}</span></div><h2>{item.category}</h2><p>📍 {item.zone}{item.distanceKm>0?` · ${item.distanceKm.toFixed(1)} km`:''}</p><strong className="provider-price">{money(item.estimatedValue)} estimados</strong>{item.matchScore!=null&&<span className="provider-match">Compatibilidad {Math.round(item.matchScore)}%</span>}</div><button className="provider-primary" onClick={()=>flow.actions.openOpportunity(item.id)} aria-label={`Ver oportunidad de ${item.category}`}>Ver oportunidad</button></article>)}</div></section>}

export function ProviderOpportunityDetail({id}:{id:string|null}){const flow=useProviderFlow(),d=useProviderData(),item=d.opportunities.find(x=>x.id===id);if(!item)return <section className="provider-screen"><button className="provider-back" onClick={flow.actions.openOpportunities}>← Oportunidades</button><h1>Oportunidad no disponible</h1><p>Puede haber sido tomada, cancelada o actualizada.</p></section>;return <section className="provider-screen provider-opportunity-detail"><button className="provider-back" onClick={flow.actions.openOpportunities}>← Oportunidades</button><span className="provider-kicker">DECIDÍ CON INFORMACIÓN</span><h1>{item.category}</h1><article className="provider-card provider-detail"><div className="provider-opportunity-meta"><span className={`provider-chip ${item.urgency==='urgent'?'is-urgent':''}`}>{item.urgency==='urgent'?'Urgente':'Disponible'}</span><span>{timeAgo(item.requestedAt)}</span></div><h2>{item.title}</h2><p>{item.description}</p><div className="provider-facts"><span><small>ZONA</small><strong>{item.zone}</strong></span><span><small>DISTANCIA</small><strong>{item.distanceKm>0?`${item.distanceKm.toFixed(1)} km`:'A confirmar'}</strong></span><span><small>ESTIMADO</small><strong>{money(item.estimatedValue)}</strong></span>{item.matchScore!=null&&<span><small>COMPATIBILIDAD</small><strong>{Math.round(item.matchScore)}%</strong></span>}</div></article><ProviderRequestEvidence serviceId={item.serviceId}/><div className="provider-decision"><button className="provider-primary provider-wide" disabled={d.busy||Boolean(d.service)} onClick={()=>flow.actions.acceptOpportunity(item.id)}>{d.busy?'Procesando…':d.service?'Ya tenés un trabajo':'Aceptar oportunidad'}</button><button className="provider-reject" disabled={d.busy} onClick={()=>flow.actions.rejectOpportunity(item.id)}>No me interesa esta oportunidad</button></div></section>}
