import React,{useEffect,useRef}from'react'
import * as maplibregl from'maplibre-gl'
import type{DemandSignal}from'./providerTypes'

const FLORIPA:[number,number]=[-48.5482,-27.5949]
const MAP_STYLE:maplibregl.StyleSpecification={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}
type Props={signals:DemandSignal[];online:boolean}

export function ProviderDemandMap({signals,online}:Props){
 const el=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),markers=useRef<maplibregl.Marker[]>([])
 const located=signals.filter((signal):signal is DemandSignal&{latitude:number;longitude:number}=>signal.latitude!=null&&signal.longitude!=null)
 useEffect(()=>{if(!el.current||mapRef.current)return;const map=new maplibregl.Map({container:el.current,style:MAP_STYLE,center:FLORIPA,zoom:11,attributionControl:false});mapRef.current=map;return()=>{markers.current.forEach(marker=>marker.remove());markers.current=[];map.remove();mapRef.current=null}},[])
 useEffect(()=>{const map=mapRef.current;if(!map)return;markers.current.forEach(marker=>marker.remove());markers.current=[];if(!located.length){map.easeTo({center:FLORIPA,zoom:11,duration:350});return}const bounds=new maplibregl.LngLatBounds();located.forEach(signal=>{const node=document.createElement('span');node.className=`provider-demand-marker is-${signal.demandLevel}`;node.setAttribute('role','img');node.setAttribute('aria-label',`${signal.demandLevel==='high'?'Alta':signal.demandLevel==='medium'?'Media':'Baja'} demanda en ${signal.zone}`);node.textContent=signal.demandLevel==='high'?'Alta':signal.demandLevel==='medium'?'Media':'Baja';Object.assign(node.style,{display:'grid',placeItems:'center',minWidth:'48px',minHeight:'48px',padding:'0 10px',borderRadius:'999px',background:signal.demandLevel==='high'?'#128c4a':'#ffffff',color:signal.demandLevel==='high'?'#ffffff':'#17211b',fontSize:'12px',fontWeight:'800',boxShadow:'0 5px 18px rgba(23,33,27,.22)',border:'2px solid #fff'});const point:[number,number]=[signal.longitude,signal.latitude];bounds.extend(point);markers.current.push(new maplibregl.Marker({element:node,anchor:'center'}).setLngLat(point).addTo(map))});if(located.length===1)map.easeTo({center:[located[0].longitude,located[0].latitude],zoom:13,duration:450});else map.fitBounds(bounds,{padding:48,maxZoom:14,duration:500})},[located])
 const status=!online?'Activá Online para entrar al radar':located.length?`${located.length} zona${located.length===1?'':'s'} con ubicación precisa`:signals.length?'Hay demanda, pero sin coordenadas precisas':'Sin demanda compatible ahora'
 return <div style={{height:260,marginBottom:16,position:'relative',overflow:'hidden',borderRadius:20,border:'1px solid rgba(23,33,27,.08)',background:'#e9f2ed',boxShadow:'0 8px 24px rgba(23,33,27,.06)'}}><div ref={el} style={{position:'absolute',inset:0}} role="img" aria-label="Mapa de demanda cercana con ubicaciones reales"/><div className="provider-map-label" style={{zIndex:2,background:'rgba(255,255,255,.92)',padding:'8px 10px',borderRadius:12}}>{status}</div>{signals.length>located.length&&<div style={{position:'absolute',zIndex:2,right:12,top:12,maxWidth:230,padding:'7px 9px',borderRadius:10,background:'rgba(255,255,255,.92)',fontSize:11,fontWeight:700}}>{signals.length-located.length} zona{signals.length-located.length===1?'':'s'} sin ubicación precisa no se dibuja{signals.length-located.length===1?'':'n'} en el mapa.</div>}</div>
}
