import React,{useCallback,useEffect,useMemo,useRef,useState}from'react'
import{detectProviderVoiceLocale,findProviderVoiceOpportunity,providerVoiceContext,providerVoiceSummary,type ProviderHugoLocale as Locale}from'../../features/provider/voice/providerVoiceHelpers'
import{runProviderVoiceCommand}from'../../features/provider/voice/providerVoiceCommands'
import{useProviderFlow}from'./providerFlow'
import{useProviderData}from'./providerData'
import'../voice.css'

type VoiceState='idle'|'connecting'|'ready'|'hearing'|'speaking'|'error'
type SpeechRecognitionAlternativeLike={transcript?:string}
type SpeechRecognitionResultLike={0?:SpeechRecognitionAlternativeLike;isFinal?:boolean}
type SpeechRecognitionEventLike={resultIndex?:number;results:ArrayLike<SpeechRecognitionResultLike>}
type SpeechRecognitionErrorEventLike={error?:string}
type SpeechRecognitionLike={lang:string;continuous:boolean;interimResults:boolean;onstart:(()=>void)|null;onspeechstart:(()=>void)|null;onresult:((event:SpeechRecognitionEventLike)=>void)|null;onerror:((event:SpeechRecognitionErrorEventLike)=>void)|null;onend:(()=>void)|null;start:()=>void;abort:()=>void}
type SpeechRecognitionConstructor=new()=>SpeechRecognitionLike
type NativeBridge={startListening:()=>void|Promise<void>;pauseListening?:()=>void;resumeListening?:()=>void|Promise<void>;stopListening:()=>void;isAvailable?:()=>boolean;speak?:(text:string,locale?:string)=>Promise<void>;stopSpeaking?:()=>void}
type UgoWindow=Window&typeof globalThis&{UGOVoiceBridge?:NativeBridge;SpeechRecognition?:SpeechRecognitionConstructor;webkitSpeechRecognition?:SpeechRecognitionConstructor;webkitAudioContext?:typeof AudioContext}
type TtsReply={audio_base64?:string;sample_rate?:number;error?:string;hugo_mensaje?:string}
type CompanionReply={reply?:string;model?:string;error?:string}
type StatusError=Error&{status?:number}

const LABELS:Record<VoiceState,string>={idle:'Toca para hablar',connecting:'Procesando...',ready:'Te escucho',hearing:'Escuchando...',speaking:'Hablando...',error:'Voz no disponible'}
const ugoWindow=()=>window as UgoWindow
const ignoreError=(value:unknown)=>{void value}
const errorStatus=(value:unknown)=>typeof value==='object'&&value!==null&&'status'in value?Number((value as{status?:unknown}).status||0):0

export function ProviderHugoBridge(){
 const flow=useProviderFlow(),data=useProviderData()
 const[state,setState]=useState<VoiceState>('idle'),[error,setError]=useState(''),[userTranscript,setUserTranscript]=useState(''),[assistantTranscript,setAssistantTranscript]=useState(''),[voiceRunning,setVoiceRunning]=useState(false),[panelOpen,setPanelOpen]=useState(false)
 const locale=useRef<Locale>('es-AR'),running=useRef(false),busy=useRef(false),native=useRef(false),voicePaused=useRef(false),recognition=useRef<SpeechRecognitionLike|null>(null),ttsAbort=useRef<AbortController|null>(null),ttsSequence=useRef(0),ttsCooldownUntil=useRef(0),audioContext=useRef<AudioContext|null>(null),audioSource=useRef<AudioBufferSourceNode|null>(null),conversation=useRef<Array<{role:'user'|'assistant';content:string}>>([])

 const summary=useMemo(()=>providerVoiceSummary(data),[data.online,data.opportunities.length,data.service])

 const setRunning=useCallback((value:boolean)=>{running.current=value;setVoiceRunning(value)},[])
 const stopSpeech=useCallback(()=>{ttsSequence.current++;try{ttsAbort.current?.abort()}catch(caught){ignoreError(caught)}ttsAbort.current=null;try{window.speechSynthesis?.cancel()}catch(caught){ignoreError(caught)}try{ugoWindow().UGOVoiceBridge?.stopSpeaking?.()}catch(caught){ignoreError(caught)}try{audioSource.current?.stop()}catch(caught){ignoreError(caught)}try{void audioContext.current?.close()}catch(caught){ignoreError(caught)}audioSource.current=null;audioContext.current=null},[])
 const pauseRecognition=useCallback(()=>{voicePaused.current=true;if(native.current){try{const bridge=ugoWindow().UGOVoiceBridge;if(bridge?.pauseListening)bridge.pauseListening();else bridge?.stopListening?.()}catch(caught){ignoreError(caught)}}else{try{recognition.current?.abort()}catch(caught){ignoreError(caught)}}},[])
 const resumeRecognition=useCallback(()=>{if(!running.current)return;voicePaused.current=false;window.setTimeout(()=>{if(!running.current||voicePaused.current)return;if(native.current){try{const bridge=ugoWindow().UGOVoiceBridge,resumed=bridge?.resumeListening?bridge.resumeListening():bridge?.startListening?.();if(resumed&&typeof (resumed as Promise<void>).catch==='function')void (resumed as Promise<void>).catch(ignoreError)}catch(caught){ignoreError(caught)}}else if(recognition.current){try{recognition.current.start()}catch(caught){ignoreError(caught)}}},80)},[])
 const playPcm=useCallback(async(base64:string,sampleRate=24000)=>{const binary=window.atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const even=bytes.byteLength-bytes.byteLength%2,Ctor=window.AudioContext||ugoWindow().webkitAudioContext;if(!Ctor)throw new Error('AudioContext no disponible');const ctx=new Ctor(),buffer=ctx.createBuffer(1,even/2,sampleRate),channel=buffer.getChannelData(0),view=new DataView(bytes.buffer,bytes.byteOffset,even);for(let i=0;i<channel.length;i++)channel[i]=view.getInt16(i*2,true)/32768;const source=ctx.createBufferSource();source.buffer=buffer;source.connect(ctx.destination);audioContext.current=ctx;audioSource.current=source;await ctx.resume();await new Promise<void>(resolve=>{source.onended=()=>resolve();source.start()});if(audioSource.current===source)audioSource.current=null;if(audioContext.current===ctx)audioContext.current=null;try{await ctx.close()}catch{}},[])
 const deviceSpeech=useCallback(async(text:string,lang:Locale)=>{if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined')throw new Error('Sin voz');const speech=new SpeechSynthesisUtterance(text);speech.lang=lang;speech.rate=1.03;await new Promise<void>((resolve,reject)=>{speech.onend=()=>resolve();speech.onerror=()=>reject(new Error('Sin voz'));window.speechSynthesis.cancel();window.speechSynthesis.speak(speech)})},[])
 const speak=useCallback(async(reply:string)=>{stopSpeech();setAssistantTranscript(reply);conversation.current=[...conversation.current,{role:'assistant' as const,content:reply}].slice(-10);setError('');if(!running.current){setState('idle');return}pauseRecognition();setState('speaking');const token=ttsSequence.current,liveBridge=ugoWindow().UGOVoiceBridge;if(!native.current||!liveBridge?.speak){setState('error');setError('Gemini Live no está disponible. Hugo no va a reemplazarla por la voz del navegador.');return}try{await liveBridge.speak(reply,locale.current);if(token===ttsSequence.current&&running.current){setState('ready');resumeRecognition()}}catch(liveVoiceError){console.error('UGO provider Gemini Live speaker unavailable',liveVoiceError);if(token===ttsSequence.current&&running.current){setState('error');setError('La voz Gemini Live falló. Tocá el orbe para reconectar.')}}},[pauseRecognition,resumeRecognition,stopSpeech])


 const context=useCallback(()=>providerVoiceContext(data,flow.screen),[data.cashReceived,data.online,data.opportunities,data.released,data.service,data.ugoDebt,flow.screen])

 const findOpportunity=useCallback((source:string)=>findProviderVoiceOpportunity(source,data.opportunities),[data.opportunities])

 const localCommand=useCallback((source:string)=>runProviderVoiceCommand({source,locale:locale.current,summary,flow:flow.actions,data,findOpportunity,speak}),[data,findOpportunity,flow.actions,speak,summary])

 const handleText=useCallback(async(source:string)=>{const clean=source.trim();if(!clean||busy.current)return;busy.current=true;setUserTranscript(clean);locale.current=detectProviderVoiceLocale(clean);conversation.current=[...conversation.current,{role:'user' as const,content:clean}].slice(-10);setState('connecting');setError('');try{if(await localCommand(clean))return;const response=await fetch('/api/test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.accessToken}`},body:JSON.stringify({role:'provider',companion_mode:true,message:clean,context:context(),history:conversation.current.slice(0,-1)})}),payload=await response.json().catch(()=>null)as CompanionReply|null;if(!response.ok||!payload?.reply)throw new Error(payload?.error||'Hugo no pudo responder');await speak(payload.reply)}catch(e){setState('error');setError(e instanceof Error?e.message:'No pude procesar eso.')}finally{busy.current=false}},[context,data.accessToken,localCommand,speak])

 const stop=useCallback(()=>{setPanelOpen(false);setRunning(false);busy.current=false;voicePaused.current=false;stopSpeech();try{recognition.current?.abort()}catch{}try{ugoWindow().UGOVoiceBridge?.stopListening?.()}catch{}recognition.current=null;native.current=false;setState('idle');setError('')},[setRunning,stopSpeech])
 const start=useCallback(async()=>{setPanelOpen(true);setError('');setState('connecting');const bridge=ugoWindow().UGOVoiceBridge;if(bridge&&bridge.isAvailable?.()!==false){native.current=true;setRunning(true);voicePaused.current=false;try{await bridge.startListening();if(running.current)setState('ready');return}catch(caught){console.warn('Gemini Live no disponible; usando reconocimiento del dispositivo.',caught);try{bridge.stopListening()}catch(stopError){ignoreError(stopError)}native.current=false;setRunning(false)}}const SR=ugoWindow().SpeechRecognition||ugoWindow().webkitSpeechRecognition;if(!SR){setState('error');setError('El reconocimiento de voz no está disponible. Revisá el permiso del micrófono y tocá el orbe para reintentar.');return}try{const stream=await navigator.mediaDevices?.getUserMedia?.({audio:true});stream?.getTracks().forEach(track=>track.stop())}catch{setState('error');setError('Permití el micrófono para hablar con Hugo.');return}setRunning(true);voicePaused.current=false;const rec=new SR();recognition.current=rec;rec.lang=locale.current;rec.continuous=false;rec.interimResults=true;rec.onstart=()=>setState('ready');rec.onspeechstart=()=>{stopSpeech();setState('hearing')};rec.onresult=(event:SpeechRecognitionEventLike)=>{let value='',final=false;for(let i=event.resultIndex||0;i<event.results.length;i++){value+=String(event.results[i]?.[0]?.transcript||'');final=final||Boolean(event.results[i]?.isFinal)}value=value.trim();if(value){setUserTranscript(value);if(final)void handleText(value)}};rec.onerror=(event:SpeechRecognitionErrorEventLike)=>{const code=String(event.error||'');if(code==='no-speech'||code==='aborted')return;setRunning(false);setState('error');setError(code==='not-allowed'?'Permití el micrófono para hablar con Hugo.':'Se interrumpió el reconocimiento de voz.')};rec.onend=()=>{if(running.current&&!busy.current&&!voicePaused.current)window.setTimeout(()=>{if(running.current&&!voicePaused.current)try{rec.start()}catch(caught){ignoreError(caught)}},100)};rec.start()},[handleText,setRunning,stopSpeech])

 useEffect(()=>{const result=(event:Event)=>{if(!running.current)return;const detail=(event as CustomEvent<{text?:string;final?:boolean}>).detail||{},value=String(detail.text||'').trim();if(value&&detail.final!==false)void handleText(value)};const stateEvent=(event:Event)=>{if(!running.current)return;const value=String((event as CustomEvent<{state?:string}>).detail?.state||'');if(value==='hearing'){stopSpeech();setState('hearing')}else if(value==='connecting')setState('connecting');else if(value==='speaking')setState('speaking');else if(value==='ready'&&!busy.current&&!voicePaused.current)setState('ready')};const voiceError=(event:Event)=>{const code=String((event as CustomEvent<{code?:string}>).detail?.code||'');native.current=false;setRunning(false);busy.current=false;setState('error');setError(code==='not-allowed'?'Permití el micrófono para hablar con Hugo.':code==='session'?'Tu sesión venció. Volvé a iniciar sesión.' :'No pude mantener la sesión de voz con Gemini Live. Tocá el orbe para reintentar o usá el reconocimiento del dispositivo si está disponible.')};window.addEventListener('ugo:native-voice-result',result);window.addEventListener('ugo:native-voice-state',stateEvent);window.addEventListener('ugo:native-voice-error',voiceError);return()=>{window.removeEventListener('ugo:native-voice-result',result);window.removeEventListener('ugo:native-voice-state',stateEvent);window.removeEventListener('ugo:native-voice-error',voiceError)}},[handleText,stopSpeech])
 useEffect(()=>()=>stop(),[stop])

 const visual=state==='speaking'?'speaking':state==='connecting'?'thinking':state==='hearing'?'listening':state==='ready'?'ready':state==='error'?'error':'idle'
 return <section className={`ugo-real-hugo prototype-hugo provider-global-hugo state-${visual}`} aria-label="Hugo, controlador por voz del proveedor">{panelOpen&&<div className="ugo-hugo-voice-controller" role="status" aria-live="polite"><small>HUGO · PROVEEDOR</small><strong>{LABELS[state]}</strong>{assistantTranscript&&<span>{assistantTranscript}</span>}{error&&<span className="ugo-hugo-stage-error">{error}</span>}</div>}<button type="button" className="ugo-real-orb" onClick={()=>voiceRunning?stop():void start()} aria-label={voiceRunning?'Cortar conversación con Hugo':'Hablar con Hugo'}><span className="ugo-orb-glass"/><span className="ugo-orb-ring ring-1"/><span className="ugo-orb-ring ring-2"/><span className="ugo-orb-icon">{state==='connecting'?'✦':state==='hearing'?'●':'⌁'}</span></button><div className="ugo-real-state"><i/><span>{LABELS[state]}</span></div></section>
}

export default ProviderHugoBridge
