import React,{useEffect,useRef,useState}from'react'
import type{SupabaseClient}from'@supabase/supabase-js'
import * as maplibregl from'maplibre-gl'
import{getRoutingProvider}from'../../../lib/routing/provider'
import{reportSentinelIncident}from'../../../lib/sentinel'

const FLORIPA:[number,number]=[-48.5482,-27.5949]
const MAP_STYLE:maplibregl.StyleSpecification={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}
type TrackingPhase='assigned'|'en_camino'
type Props={supabase:SupabaseClient;serviceId:string;phase?:TrackingPhase}
type TrackingRow={proveedor_id:string;provider_lat:number|null;provider_lng:number|null;client_lat:number|null;client_lng:number|null;provider_updated_at:string|null}
type TrackingRpcClient={rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:unknown}>}
type LineGeometry={type:'LineString';coordinates:[number,number][]}

function lineGeometry(value:unknown):LineGeometry|null{
 if(!value||typeof value!=='object')return null
 const candidate=value as{type?:unknown;coordinates?:unknown}
 if(candidate.type!=='LineString'||!Array.isArray(candidate.coordinates))return null
 const coordinates=candidate.coordinates.filter((item):item is[number,number]=>Array.isArray(item)&&item.length>=2&&typeof item[0]==='number'&&typeof item[1]==='number').map(item=>[item[0],item[1]] as[number,number])
 return coordinates.length>=2?{type:'LineString',coordinates}:null
}
function validPoint(value:[number,number]){return Number.isFinite(value[0])&&Number.isFinite(value[1])&&value[0]>=-180&&value[0]<=180&&value[1]>=-90&&value[1]<=90}
function removeMarker(marker:maplibregl.Marker){try{marker.remove()}catch(error){console.warn('UGO live map marker cleanup failed',error)}}
function clearRoute(map:maplibregl.Map){try{if(map.getLayer('ugo-active-route'))map.removeLayer('ugo-active-route');if(map.getSource('ugo-active-route'))map.removeSource('ugo-active-route')}catch(error){console.warn('UGO live route cleanup failed',error)}}
const FALLBACK='El mapa en vivo no está disponible ahora. El pedido y el chat siguen funcionando.'

export function ClientActiveMap({supabase,serviceId,phase='en_camino'}:Props){
 const el=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),marks=useRef<maplibregl.Marker[]>([])
 const[user,setUser]=useState<[number,number]>(FLORIPA),[provider,setProvider]=useState<[number,number]|null>(null),[eta,setEta]=useState<number|null>(null),[lastUpdate,setLastUpdate]=useState<string|null>(null),[mapError,setMapError]=useState('')
 useEffect(()=>{let alive=true;navigator.geolocation?.getCurrentPosition(p=>{const point:[number,number]=[p.coords.longitude,p.coords.latitude];if(alive&&validPoint(point))setUser(point)},()=>undefined,{enableHighAccuracy:true,timeout:7000,maximumAge:45000});return()=>{alive=false}},[])
 useEffect(()=>{let alive=true;const rpc=supabase as unknown as TrackingRpcClient;const load=async()=>{const{data,error}=await rpc.rpc('obtener_tracking_servicio_cliente',{p_servicio_id:serviceId});if(!alive)return;if(error){setProvider(null);void reportSentinelIncident({eventType:'client_tracking_rpc_error',message:'No pudimos sincronizar la ubicación del profesional.',error,role:'client',severity:'P2',serviceId,action:'client.order.tracking'});return}const raw=Array.isArray(data)?data[0]:data;const row=(raw||null)as TrackingRow|null;if(!row){setProvider(null);return}if(row.client_lat!=null&&row.client_lng!=null){const point:[number,number]=[Number(row.client_lng),Number(row.client_lat)];if(validPoint(point))setUser(point)}if(row.provider_lat!=null&&row.provider_lng!=null){const point:[number,number]=[Number(row.provider_lng),Number(row.provider_lat)];setProvider(validPoint(point)?point:null)}else setProvider(null);setLastUpdate(row.provider_updated_at||null)};void load().catch(error=>{setProvider(null);void reportSentinelIncident({eventType:'client_tracking_load_error',message:'No pudimos cargar el seguimiento del pedido.',error,role:'client',severity:'P2',serviceId,action:'client.order.tracking'})});const timer=window.setInterval(()=>void load().catch(error=>{setProvider(null);void reportSentinelIncident({eventType:'client_tracking_resync_error',message:'No pudimos resincronizar el seguimiento del pedido.',error,role:'client',severity:'P2',serviceId,action:'client.order.tracking'})}),10_000);return()=>{alive=false;window.clearInterval(timer)}},[serviceId,supabase])
 useEffect(()=>{if(!el.current||mapRef.current||mapError)return;let map:maplibregl.Map|null=null;try{map=new maplibregl.Map({container:el.current,style:MAP_STYLE,center:FLORIPA,zoom:14,attributionControl:false});mapRef.current=map;const onMapError=(event:unknown)=>{setMapError(current=>current||FALLBACK);void reportSentinelIncident({eventType:'client_map_runtime_error',message:FALLBACK,error:event,role:'client',severity:'P2',serviceId,action:'client.order.tracking.map'})};map.on('error',onMapError);return()=>{marks.current.forEach(removeMarker);marks.current=[];try{map?.off('error',onMapError);map?.remove()}catch(error){console.warn('UGO live map cleanup failed',error)}if(mapRef.current===map)mapRef.current=null}}catch(error){console.warn('UGO live map unavailable',error);queueMicrotask(()=>setMapError(FALLBACK));void reportSentinelIncident({eventType:'client_map_init_error',message:FALLBACK,error,role:'client',severity:'P2',serviceId,action:'client.order.tracking.map'});mapRef.current=null}},[mapError,serviceId])
 useEffect(()=>{const map=mapRef.current;if(!map||mapError)return;try{marks.current.forEach(removeMarker);marks.current=[];if(validPoint(user)){const u=document.createElement('div');u.className='ugo-active-user-dot';marks.current.push(new maplibregl.Marker({element:u}).setLngLat(user).addTo(map))}if(provider&&validPoint(provider)){const p=document.createElement('div');p.className='ugo-active-provider-dot';p.textContent='●';marks.current.push(new maplibregl.Marker({element:p}).setLngLat(provider).addTo(map))}}catch(error){console.warn('UGO live map markers unavailable',error);queueMicrotask(()=>setMapError(FALLBACK));void reportSentinelIncident({eventType:'client_map_marker_error',message:FALLBACK,error,role:'client',severity:'P2',serviceId,action:'client.order.tracking.map'})}},[mapError,provider,serviceId,user])
 useEffect(()=>{const map=mapRef.current;if(!map||mapError||phase!=='assigned')return;setEta(null);clearRoute(map);const frame=()=>{if(!mapRef.current)return;const current=mapRef.current;try{if(provider&&validPoint(provider)){const bounds=new maplibregl.LngLatBounds();bounds.extend(user);bounds.extend(provider);current.fitBounds(bounds,{padding:{top:70,bottom:90,left:45,right:45},maxZoom:15,duration:500})}else if(validPoint(user))current.easeTo({center:user,zoom:14,duration:500})}catch(error){console.warn('UGO assigned map viewport unavailable',error)}};if(map.isStyleLoaded())frame();else map.once('load',frame);return()=>{try{map.off('load',frame)}catch{}}},[mapError,phase,provider,user])
 useEffect(()=>{const map=mapRef.current;if(!map||!provider||mapError||phase!=='en_camino'){if(phase!=='en_camino')setEta(null);return}let alive=true;getRoutingProvider().route({latitude:provider[1],longitude:provider[0]},{latitude:user[1],longitude:user[0]}).then(route=>{if(!alive||!mapRef.current)return;const current=mapRef.current;const geometry=lineGeometry(route.geometry)||{type:'LineString' as const,coordinates:[provider,user]};setEta(Math.max(1,Math.round(route.durationSeconds/60)));const render=()=>{if(!alive||!current.isStyleLoaded())return;try{clearRoute(current);current.addSource('ugo-active-route',{type:'geojson',data:{type:'Feature',properties:{},geometry}});current.addLayer({id:'ugo-active-route',type:'line',source:'ugo-active-route',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#079455','line-width':5,'line-opacity':.92}});const b=new maplibregl.LngLatBounds();geometry.coordinates.forEach(c=>b.extend(c));if(!b.isEmpty())current.fitBounds(b,{padding:{top:100,bottom:150,left:50,right:50},maxZoom:15,duration:650})}catch(error){console.warn('UGO live route unavailable',error);setMapError(FALLBACK);void reportSentinelIncident({eventType:'client_route_render_error',message:FALLBACK,error,role:'client',severity:'P2',serviceId,action:'client.order.tracking.route'})}};if(current.isStyleLoaded())render();else current.once('load',render)}).catch(error=>{setEta(null);void reportSentinelIncident({eventType:'client_route_load_error',message:'No pudimos calcular la ruta del profesional.',error,role:'client',severity:'P2',serviceId,action:'client.order.tracking.route'})});return()=>{alive=false}},[mapError,phase,provider,serviceId,user])
 if(mapError)return <div className="ugo-active-map-fallback" role="status"><strong>Seguimiento protegido</strong><p>{mapError}</p>{provider&&<small>La última ubicación del profesional sigue registrada.</small>}</div>
 return <div className="ugo-active-map-wrap"><div ref={el} className="ugo-active-map"/>{phase==='assigned'?provider?<div className="ugo-active-eta is-waiting"><small>Ubicación del profesional</small><strong>Listo para salir</strong><span>El ETA aparecerá cuando inicie el viaje</span></div>:<div className="ugo-active-eta is-syncing"><small>Esperando ubicación del profesional…</small></div>:provider?eta?<div className="ugo-active-eta"><small>Llegando en</small><strong>{eta} min</strong>{lastUpdate&&<span>Ubicación actualizada</span>}</div>:<div className="ugo-active-eta is-syncing"><small>Calculando ruta…</small></div>:<div className="ugo-active-eta is-syncing"><small>Esperando ubicación del profesional…</small></div>}</div>
}
