import React,{useCallback,useEffect,useId,useMemo,useRef,useState}from'react'
import{clearSentinelContext,reportSentinelIncident}from'../../../lib/sentinel'
import{getDispatchProvider}from'../../../lib/dispatch/provider'
import{getRoleSupabase}from'../../../lib/roleSupabase'
import{ClientCompletionReview}from'./ClientCompletionReview'
import{ClientEvidenceGallery}from'./ClientEvidenceGallery'
import{ClientLiveTracking}from'./ClientLiveTracking'
import{DisputeDock}from'../../../mvp/DisputeDock'
import{SentinelErrorBoundary}from'../../../mvp/SentinelErrorBoundary'
import{ServiceChat}from'../../../mvp/ServiceChat'
import{ServiceExpansionPanel}from'../../../mvp/ServiceExpansionPanel'
import{STATUS_LABELS}from'../../../mvp/shared'
import{ClientPaymentChoice}from'../payments/ClientPaymentChoice'
import{ClientRatingPrompt}from'../rating/ClientRatingPrompt'
import{useClientFlow}from'../flow/clientFlow'

type DetailRow={id:string;numero:number|string|null;estado:string;categoria_id:string;descripcion:string|null;direccion_cliente:string|null;programado_para:string|null;created_at:string|null;tarifa:number|string|null;moneda:string|null;proveedor_id:string|null;categoria:{nombre?:string|null;emoji?:string|null}|null;proveedor:{nombre?:string|null;karma?:number|null}|null}
const CANCELLABLE=new Set(['borrador','buscando','ofrecido','asignado','en_camino','llegado'])
const money=(value:number|string|null,moneda:string|null)=>{const raw=String(moneda||'BRL').toUpperCase(),currency=/^[A-Z]{3}$/.test(raw)?raw:'BRL';try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(Number(value||0))}catch{return `R$ ${Number(value||0).toFixed(2)}`}}
const when=(value:string|null,created:string|null)=>{const raw=value||created;if(!raw)return'Horario por confirmar';const date=new Date(raw);return Number.isNaN(date.getTime())?'Horario por confirmar':date.toLocaleString('es-AR',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}

export function ClientServiceDetail({serviceId,onClose}:{serviceId:string;onClose:()=>void}){
 const supabase=useMemo(()=>getRoleSupabase('client'),[]),flow=useClientFlow(),instanceId=useId().replace(/:/g,''),channelGeneration=useRef(0)
 const[service,setService]=useState<DetailRow|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[channelEpoch,setChannelEpoch]=useState(0),[disputeOpenKey,setDisputeOpenKey]=useState(0)
 const load=useCallback(async()=>{setLoading(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sesión no disponible.');const{data,error:queryError}=await supabase.from('servicios').select('id,numero,estado,categoria_id,descripcion,direccion_cliente,programado_para,created_at,tarifa,moneda,proveedor_id,categoria:categorias(nombre,emoji),proveedor:usuarios!servicios_proveedor_id_fkey(nombre,karma)').eq('id',serviceId).eq('cliente_id',user.id).maybeSingle();if(queryError)throw queryError;if(!data)throw new Error('Este pedido no existe o no pertenece a tu cuenta.');setService(data as unknown as DetailRow);clearSentinelContext()}catch(loadError){const message=loadError instanceof Error?loadError.message:'No pudimos abrir este pedido.';setError(message);void reportSentinelIncident({eventType:'client_order_load_error',message,error:loadError,role:'client',severity:'P0',serviceId,action:'client.activity.open_order',checklistCode:'CLIENT-ORDER-OPEN'})}finally{setLoading(false)}},[serviceId,supabase])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{let alive=true;const resync=()=>{if(alive)void load()};const onVisibility=()=>{if(document.visibilityState==='visible')resync()};window.addEventListener('online',resync);document.addEventListener('visibilitychange',onVisibility);const generation=++channelGeneration.current,topic=`client-service-detail-${serviceId}-${instanceId}-${channelEpoch}-${generation}`;const ch=supabase.channel(topic).on('postgres_changes',{event:'*',schema:'public',table:'servicios',filter:`id=eq.${serviceId}`},resync).subscribe(status=>{if(status==='SUBSCRIBED')resync();if((status==='CHANNEL_ERROR'||status==='TIMED_OUT')&&document.visibilityState==='visible'&&navigator.onLine){void reportSentinelIncident({eventType:'realtime_subscription_error',message:`Detalle de pedido Realtime: ${status}`,role:'client',severity:'P1',serviceId,action:'client.order.realtime'});window.setTimeout(()=>{if(alive)setChannelEpoch(value=>value+1)},1000)}});return()=>{alive=false;window.removeEventListener('online',resync);document.removeEventListener('visibilitychange',onVisibility);void supabase.removeChannel(ch)}},[channelEpoch,instanceId,load,serviceId,supabase])
 const retryMatching=async()=>{if(!service||!['buscando','ofrecido'].includes(service.estado)||busy)return;setBusy(true);setNotice('');try{await getDispatchProvider().start({serviceId:service.id,category:service.categoria_id,pickupFallback:'none'});setNotice('Búsqueda reintentada. UGO volvió a avisar a profesionales disponibles.');await load()}catch(error){setNotice(error instanceof Error?error.message:'No pudimos reintentar la búsqueda. El pedido sigue guardado.')}finally{setBusy(false)}}
 const cancel=async()=>{if(!service||!CANCELLABLE.has(service.estado)||busy)return;if(!window.confirm('¿Realmente querés cancelar este pedido?'))return;setBusy(true);setNotice('');const ok=await flow.actions.cancelService(service.id);setBusy(false);if(ok){setNotice('Pedido cancelado. Los otros pedidos no fueron modificados.');await load()}else setNotice('No pudimos cancelar este pedido. Su estado actual fue preservado.')}
 const awaitingApproval=service?.estado==='esperando_aprobacion',disputeActive=service?.estado==='disputado'
 const openExactDispute=()=>setDisputeOpenKey(value=>value+1)
 return <div className="ugo-client-screen-overlay" role="dialog" aria-modal="true" aria-label="Detalle del pedido"><div className="ugo-client-history-wrap" style={{display:'grid',gap:12}}><button type="button" className="ugo-client-history-back" onClick={onClose} aria-label="Volver a mis pedidos">←</button>
  {loading&&<section className="ugo-history-panel embedded"><div className="ugo-history-empty">Cargando pedido…</div></section>}
  {error&&<section className="ugo-history-panel embedded"><div className="ugo-history-error">{error}</div><button type="button" className="ugo-guided-primary" onClick={()=>void load()}>Reintentar</button></section>}
  {!loading&&!error&&service&&<><section className="ugo-history-panel embedded"><header><div><small>PEDIDO #{service.numero??String(service.id).slice(0,8)}</small><h2>{service.categoria?.emoji||'🧰'} {service.categoria?.nombre||'Servicio UGO'}</h2><p>{service.descripcion||'Sin descripción adicional.'}</p></div><span className={`state-${service.estado}`}>{STATUS_LABELS[service.estado]||service.estado}</span></header><div className="ugo-history-meta"><div><small>{service.programado_para?'PROGRAMADO':'CREADO'}</small><b>{when(service.programado_para,service.created_at)}</b></div><div><small>PROVEEDOR</small><b>{service.proveedor?.nombre||'Todavía sin asignar'}</b></div><div><small>DIRECCIÓN</small><b>{service.direccion_cliente||'Por confirmar'}</b></div><div><small>IMPORTE</small><b>{money(service.tarifa,service.moneda)}</b></div></div>{notice&&<div className="ugo-history-action-notice" role="status">{notice}</div>}{['buscando','ofrecido'].includes(service.estado)&&<div className="ugo-history-row-actions"><button type="button" className="ugo-history-open-button" disabled={busy} onClick={()=>void retryMatching()}>{busy?'Reintentando…':'Reintentar búsqueda'}</button></div>}{CANCELLABLE.has(service.estado)&&<div className="ugo-history-row-actions"><button type="button" className="ugo-history-cancel-button" disabled={busy} onClick={()=>void cancel()}>{busy?'Cancelando…':'Cancelar este pedido'}</button></div>}</section>
   <SentinelErrorBoundary role="client" serviceId={service.id} action="client.order.evidence" title="Evidencias temporalmente no disponibles" compact><ClientEvidenceGallery serviceId={service.id} hideWhenEmpty/></SentinelErrorBoundary>
   {awaitingApproval&&<SentinelErrorBoundary role="client" serviceId={service.id} action="client.order.review" checklistCode="PAYMENT-CLOSE" severity="P0" title="Cierre temporalmente no disponible" compact><ClientCompletionReview serviceId={service.id} onCompleted={load} onOpenDispute={openExactDispute}/></SentinelErrorBoundary>}
   {disputeActive&&<section className="ugo-history-panel embedded"><div className="ugo-history-empty"><strong>⚖ Disputa abierta</strong><p>UGO pausó el cierre normal de este servicio mientras revisa el caso.</p><button type="button" className="ugo-history-open-button" onClick={openExactDispute}>VER DISPUTA</button></div></section>}
   <SentinelErrorBoundary role="client" serviceId={service.id} action="client.order.chat" checklistCode="CHAT-REALTIME" severity="P0" title="Chat temporalmente no disponible" compact><ServiceChat role="client" serviceId={service.id} compact/></SentinelErrorBoundary>
   {!awaitingApproval&&!disputeActive&&service.estado!=='completado'&&<SentinelErrorBoundary role="client" serviceId={service.id} action="client.order.tracking" title="Seguimiento temporalmente no disponible" compact><ClientLiveTracking serviceId={service.id} embedded/></SentinelErrorBoundary>}
   {!awaitingApproval&&!disputeActive&&service.estado!=='completado'&&<SentinelErrorBoundary role="client" serviceId={service.id} action="client.order.payment" checklistCode="PAYMENT-CLOSE" severity="P0" title="Pago temporalmente no disponible" compact><ClientPaymentChoice serviceId={service.id}/></SentinelErrorBoundary>}
   {!awaitingApproval&&!disputeActive&&service.estado!=='completado'&&<SentinelErrorBoundary role="client" serviceId={service.id} action="client.order.expansion" title="Cambios del servicio temporalmente no disponibles" compact><ServiceExpansionPanel role="client" serviceId={service.id} compact/></SentinelErrorBoundary>}
   {service.estado==='completado'&&<SentinelErrorBoundary role="client" serviceId={service.id} action="client.rating.submit" checklistCode="RATING" severity="P1" title="Calificación temporalmente no disponible" compact><ClientRatingPrompt serviceId={service.id} embedded/></SentinelErrorBoundary>}
   <SentinelErrorBoundary role="client" serviceId={service.id} action="client.order.dispute" title="Ayuda temporalmente no disponible" compact><DisputeDock role="client" serviceId={service.id} key={`client-dispute-${service.id}`} openRequestKey={disputeOpenKey} showLauncher={!awaitingApproval&&!disputeActive}/></SentinelErrorBoundary>
  </>}
 </div></div>
}

export default ClientServiceDetail
