import{getRoleSupabase}from'../../../lib/roleSupabase'
export type EvidenceType='antes'|'durante'|'despues'
export type ProviderEvidenceRow={id:string;tipo:EvidenceType;storage_path:string;descripcion:string|null;created_at:string;url?:string|null}
export type RequestEvidenceRow={id:string;storage_path:string;descripcion:string|null;url?:string|null;urlError?:string|null}
export const SERVICE_EVIDENCE_BUCKET='service-evidence',REQUEST_EVIDENCE_BUCKET='request-evidence'
export const providerEvidenceDb=()=>getRoleSupabase('provider')
export async function loadServiceEvidence(serviceId:string){const sb=providerEvidenceDb(),{data,error}=await sb.from('evidencias_servicio').select('id,tipo,storage_path,descripcion,created_at').eq('servicio_id',serviceId).order('created_at',{ascending:true});if(error)throw error;const base=(data||[])as ProviderEvidenceRow[];return Promise.all(base.map(async row=>{const{data:s,error:e}=await sb.storage.from(SERVICE_EVIDENCE_BUCKET).createSignedUrl(row.storage_path,900);return{...row,url:e?null:s?.signedUrl||null}}))}
export async function loadRequestEvidence(serviceId:string){const sb=providerEvidenceDb(),{data,error}=await sb.from('evidencias_solicitud').select('id,storage_path,descripcion').eq('servicio_id',serviceId).order('created_at',{ascending:true});if(error)throw error;return Promise.all(((data||[])as RequestEvidenceRow[]).map(async row=>{const{data:s,error:storageError}=await sb.storage.from(REQUEST_EVIDENCE_BUCKET).createSignedUrl(row.storage_path,900);return{...row,url:s?.signedUrl||null,urlError:storageError?.message||(!s?.signedUrl?'SIGNED_URL_MISSING':null)}}))}
export async function uploadServiceEvidence(serviceId:string,kind:EvidenceType,file:File){const sb=providerEvidenceDb(),{data:userData}=await sb.auth.getUser(),user=userData.user;if(!user)throw new Error('Sesión no disponible.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=`${serviceId}/${user.id}/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await sb.storage.from(SERVICE_EVIDENCE_BUCKET).upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});if(uploadError)throw uploadError;const{error:insertError}=await sb.from('evidencias_servicio').insert({servicio_id:serviceId,usuario_id:user.id,tipo:kind,storage_path:path,descripcion:kind==='antes'?'Estado inicial al llegar':kind==='despues'?'Resultado final del trabajo':'Evidencia durante el servicio',metadata:{mime:file.type||null,size:file.size}});if(insertError){const{data:persisted}=await sb.from('evidencias_servicio').select('id').eq('servicio_id',serviceId).eq('storage_path',path).maybeSingle();if(persisted)return;await sb.storage.from(SERVICE_EVIDENCE_BUCKET).remove([path]);throw insertError}}
