plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ugo.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ugo.mobile'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    flavorDimensions 'role'
    productFlavors {
        client {
            dimension 'role'
            applicationId 'com.ugo.client'
            resValue 'string', 'app_name', 'UGO Cliente'
            buildConfigField 'String', 'UGO_URL', '"https://ugo-admin-panel.vercel.app/?app=client"'
        }
        provider {
            dimension 'role'
            applicationId 'com.ugo.provider'
            resValue 'string', 'app_name', 'UGO Proveedor'
            buildConfigField 'String', 'UGO_URL', '"https://ugo-admin-panel.vercel.app/?app=provider"'
        }
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
