import{normalizeProviderVoice,type ProviderHugoLocale}from'./providerVoiceHelpers'
import type{ProviderOpportunity}from'../../../mvp/provider/providerTypes'
type Speak=(text:string)=>Promise<void>
type FlowActions={openHome:()=>void;openDemand:()=>void;openOpportunities:()=>void;openAgenda:()=>void;openEarnings:()=>void;openProfile:()=>void;openHistory:()=>void;openDispute:()=>void;openActiveJob:()=>void;acceptOpportunity:(id:string)=>Promise<boolean>;rejectOpportunity:(id:string)=>Promise<boolean>}
type Data={online:boolean;service:any;toggleOnline:()=>Promise<unknown>;advance:(state:string)=>Promise<boolean>}
export async function runProviderVoiceCommand(args:{source:string;locale:ProviderHugoLocale;summary:string;flow:FlowActions;data:Data;findOpportunity:(source:string)=>ProviderOpportunity|null;speak:Speak}){const{source,locale,summary,flow,data,findOpportunity,speak}=args,value=normalizeProviderVoice(source),pt=locale==='pt-BR'
if(/\b(inicio|home|principal)\b/.test(value)){flow.openHome();await speak(pt?'Voltei ao início.':'Volví al inicio.');return true}
if(/\b(demanda|radar|zonas?)\b/.test(value)){flow.openDemand();await speak(pt?'Abri o radar de demanda.':'Abrí el radar de demanda.');return true}
if(/\b(pedidos?|oportunidades?|ofertas?)\b/.test(value)&&/\b(abrir|ver|mostrar|mostra|quiero|quero)\b/.test(value)){flow.openOpportunities();await speak(pt?'Abri suas oportunidades.':'Abrí tus oportunidades.');return true}
if(/\b(agenda|calendario)\b/.test(value)){flow.openAgenda();await speak(pt?'Abri sua agenda.':'Abrí tu agenda.');return true}
if(/\b(ganancias?|ganhos?|cobros?|saldo|dinheiro)\b/.test(value)&&/\b(abrir|abre|ver|mostrar|mostra|ir|lleva|levame|levá|leva)\b/.test(value)){flow.openEarnings();await speak(pt?'Abri seus ganhos.':'Abrí tus ganancias.');return true}
if(/\b(perfil|cuenta|conta)\b/.test(value)&&/\b(abrir|ver|mostrar|mostra|ir)\b/.test(value)){flow.openProfile();await speak(pt?'Abri seu perfil.':'Abrí tu perfil.');return true}
if(/\b(historial|atividade|actividad)\b/.test(value)&&/\b(abrir|abre|ver|mostrar|mostra|ir|lleva|levame|levá|leva)\b/.test(value)){flow.openHistory();await speak(pt?'Abri seu histórico.':'Abrí tu historial.');return true}
if(/\b(disputa|problema|soporte|suporte)\b/.test(value)&&/\b(abrir|ver|mostrar|ajuda|ayuda)\b/.test(value)){flow.openDispute();await speak(pt?'Abri suporte e disputas.':'Abrí soporte y disputas.');return true}
if(/\b(trabalho atual|trabajo actual|servicio actual|missao|mision)\b/.test(value)){data.service?flow.openActiveJob():flow.openAgenda();await speak(data.service?(pt?'Abri o trabalho atual.':'Abrí el trabajo actual.'):(pt?'Você não tem um trabalho ativo. Abri sua agenda.':'No tenés un trabajo activo. Abrí tu agenda.'));return true}
if(/\b(poneme|ponerme|quedar|ficar|modo)\b.*\b(online|disponible)\b/.test(value)||value==='online'){if(!data.online)await data.toggleOnline();await speak(pt?'Você está online.':'Estás online.');return true}
if(/\b(poneme|ponerme|quedar|ficar|modo)\b.*\b(offline|desconectado)\b/.test(value)||value==='offline'){if(data.online)await data.toggleOnline();await speak(pt?'Você está offline.':'Estás offline.');return true}
if(/\b(aceptar|acepta|aceptalo|aceptá|aceito|aceitar|aceita)\b/.test(value)){const item=findOpportunity(source);if(!item){flow.openOpportunities();await speak(pt?'Tenho mais de uma oportunidade. Diga a categoria ou o número.':'Tenés más de una oportunidad. Decime la categoría o el número.');return true}const ok=await flow.acceptOpportunity(item.id);await speak(ok?(pt?'Trabalho aceito.':'Trabajo aceptado.'):(pt?'Não consegui aceitar esse pedido.':'No pude aceptar ese pedido.'));return true}
if(/\b(rechazar|rechaza|rechazalo|rechazá|recusar|recusa)\b/.test(value)){const item=findOpportunity(source);if(!item){flow.openOpportunities();await speak(pt?'Diga qual oportunidade quer recusar.':'Decime qué oportunidad querés rechazar.');return true}const ok=await flow.rejectOpportunity(item.id);await speak(ok?(pt?'Oportunidade recusada.':'Oportunidad rechazada.'):(pt?'Não consegui recusar agora.':'No pude rechazarla ahora.'));return true}
if(/\b(estoy yendo|voy para alla|vou indo|estou indo)\b/.test(value)){if(!data.service||data.service.estado!=='asignado'){await speak(pt?'Não há um trabalho atribuído pronto para iniciar o trajeto.':'No hay un trabajo asignado listo para iniciar el viaje.');return true}const ok=await data.advance('en_camino');if(ok){flow.openActiveJob();await speak(pt?'Certo. Marquei que você está a caminho.':'Listo. Marqué que estás yendo.')}else await speak(pt?'Não consegui mudar o estado. Revise o serviço.':'No pude cambiar el estado. Revisá el servicio.');return true}
if(/\b(ya llegue|llegue|estoy aca|ja cheguei|cheguei|estou aqui)\b/.test(value)){if(!data.service||data.service.estado!=='en_camino'){await speak(pt?'Primeiro o serviço precisa estar em caminho.':'Primero el servicio tiene que estar en camino.');return true}const ok=await data.advance('llegado');if(ok){flow.openActiveJob();await speak(pt?'Chegada confirmada com GPS.':'Llegada confirmada con GPS preciso.')}else await speak(pt?'Não pude confirmar a chegada. Preciso de GPS preciso e estar dentro da área permitida.':'No pude confirmar la llegada. Necesito GPS preciso y estar dentro del radio permitido.');return true}
if(/\b(empezar trabajo|iniciar trabajo|comenzar trabajo|iniciar servico|comecar trabalho)\b/.test(value)){flow.openActiveJob();await speak(data.service?.estado==='llegado'?(pt?'Abra o trabalho: a evidência inicial é obrigatória antes de começar.':'Abrí el trabajo: la evidencia inicial es obligatoria antes de empezar.'):(pt?'Primeiro confirme a chegada.':'Primero confirmá la llegada.'));return true}
if(/\b(trabajo listo|termine|finalizar trabajo|trabalho pronto|terminei|finalizar servico)\b/.test(value)){flow.openActiveJob();await speak(data.service?.estado==='en_progreso'?(pt?'Abra o trabalho e carregue a evidência final antes de marcar como pronto.':'Abrí el trabajo y cargá la evidencia final antes de marcarlo listo.'):(pt?'O trabalho ainda não está em andamento.':'El trabajo todavía no está en progreso.'));return true}
if(/\b(estado|status|como va|como viene|como esta|andamento)\b/.test(value)){await speak(summary);return true}return false}
