import{STATUS_LABELS}from'../../../mvp/shared'
import type{ProviderOpportunity}from'../../../mvp/provider/providerTypes'
export type ProviderHugoLocale='es-AR'|'pt-BR'
export const normalizeProviderVoice=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
export const detectProviderVoiceLocale=(value:string):ProviderHugoLocale=>{const text=normalizeProviderVoice(value);return/(^|\s)(quero|preciso|voce|servico|agora|nao|sim|trabalho|ganhos)(\s|$)/.test(text)?'pt-BR':'es-AR'}
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0))
export function providerVoiceSummary(data:any){if(data.service){const status=STATUS_LABELS[data.service.estado]||data.service.estado,category=data.service.categoria?.nombre||'servicio';return`Tenés un ${category} ${status.toLowerCase()}.`}if(data.opportunities.length)return`Tenés ${data.opportunities.length} oportunidad${data.opportunities.length===1?'':'es'} disponible${data.opportunities.length===1?'':'s'}.`;return data.online?'Estás online y disponible para recibir pedidos.':'Estás offline. Podés pedirme que te ponga online.'}
export function providerVoiceContext(data:any,screen:string){const opportunity=data.opportunities.slice(0,4).map((item:ProviderOpportunity,index:number)=>`${index+1}. ${item.category}: ${item.title}, ${item.zone}, ${money(item.estimatedValue)}`).join(' | '),service=data.service?`${data.service.categoria?.nombre||'Servicio'} #${data.service.numero||data.service.id}: ${STATUS_LABELS[data.service.estado]||data.service.estado}. ${data.service.descripcion||''}`:'sin trabajo activo';return`Pantalla=${screen}. Estado=${data.online?'online':'offline'}. Trabajo=${service}. Oportunidades=${opportunity||'ninguna'}. Ganancias liberadas=${money(data.released)}. Efectivo=${money(data.cashReceived)}. Deuda UGO=${money(data.ugoDebt)}.`}
export function findProviderVoiceOpportunity(source:string,opportunities:ProviderOpportunity[]){const value=normalizeProviderVoice(source),number=value.match(/(?:pedido|oportunidad|numero|nro|#)\s*(\d+)/)?.[1];if(number){const byIndex=opportunities[Number(number)-1];if(byIndex)return byIndex}const matches=opportunities.filter(item=>normalizeProviderVoice(`${item.category} ${item.title}`).split(/\s+/).filter(w=>w.length>=4).some(w=>value.includes(w)));return matches.length===1?matches[0]:opportunities.length===1?opportunities[0]:null}
