import{useCallback,useEffect,useMemo,useState}from'react'
import{supabase as adminSupabase}from'../lib/supabase'
import{getRoleSupabase,type UgoRole}from'../lib/roleSupabase'

export type DisputeEvidence={path:string;name:string;type:string;size?:number}
export type DisputeReason={codigo:string;actor:'cliente'|'proveedor'|'ambos';etiqueta:string;severidad:'baja'|'media'|'alta';requiere_humano:boolean;ventana_horas:number;evidencia_sugerida:string|null}
export type PreAgreement={id:string;servicio_id:string;propuesto_por:string;tipo:'retrabajo'|'ajuste_precio'|'reagendar'|'otro';detalle:string;monto:number|null;estado:'propuesto'|'aceptado'|'rechazado'|'cancelado'|'escalado';respondido_por:string|null;respuesta:string|null;created_at:string;responded_at:string|null}
export type DisputeRow={id:string;numero?:number|null;servicio_id:string;cliente_id?:string|null;proveedor_id?:string|null;abierta_por:string;estado:string;motivo:string;motivo_codigo?:string|null;evidencias?:DisputeEvidence[];nivel_revision?:string;requiere_humano?:boolean;monto_disputado?:number|null;resolucion?:string|null;resolucion_favor?:'cliente'|'proveedor'|null;ajuste_financiero_pendiente?:boolean;created_at:string;resuelta_at?:string|null;clientes?:{nombre?:string|null}|null;proveedores?:{nombre?:string|null}|null}
export type DisputeMessage={id:number;disputa_id:string;autor_id:string;autor_rol:'cliente'|'proveedor'|'admin';mensaje:string;evidencias?:DisputeEvidence[];created_at:string}

export function useAdminDisputes(){
 const[disputes,setDisputes]=useState<DisputeRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 const refetch=useCallback(async()=>{setLoading(true);setError(null);const{data,error:e}=await(adminSupabase as any).from('disputas').select('id,numero,servicio_id,cliente_id,proveedor_id,abierta_por,estado,motivo,motivo_codigo,evidencias,nivel_revision,requiere_humano,monto_disputado,resolucion,resolucion_favor,ajuste_financiero_pendiente,created_at,resuelta_at,clientes:usuarios!disputas_cliente_id_fkey(nombre),proveedores:usuarios!disputas_proveedor_id_fkey(nombre)').in('estado',['abierta','en_revision']).order('created_at',{ascending:true});if(e)setError(e.message);else setDisputes((data||[])as DisputeRow[]);setLoading(false)},[])
 const resolverDisputa=useCallback(async(id:string,resolucion:string,favorDe:'cliente'|'proveedor')=>{const{error}=await(adminSupabase as any).rpc('admin_resolver_disputa',{p_disputa_id:id,p_resolucion:resolucion,p_favor_de:favorDe});if(error)throw error;await refetch()},[refetch])
 useEffect(()=>{let alive=true;const refresh=()=>{if(alive)void refetch()};const onVisibility=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('online',refresh);document.addEventListener('visibilitychange',onVisibility);refresh();const ch=(adminSupabase as any).channel('ugo-admin-disputes').on('postgres_changes',{event:'*',schema:'public',table:'disputas'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'disputa_mensajes'},refresh).subscribe((status:string)=>{if(status==='SUBSCRIBED')refresh()});return()=>{alive=false;window.removeEventListener('online',refresh);document.removeEventListener('visibilitychange',onVisibility);(adminSupabase as any).removeChannel(ch)}},[refetch])
 return{disputes,loading,error,refetch,resolverDisputa}
}

export function useParticipantDispute(role:UgoRole,serviceId?:string|null){
 const sb=useMemo(()=>getRoleSupabase(role) as any,[role])
 const[userId,setUserId]=useState<string|null>(null),[service,setService]=useState<any|null>(null),[dispute,setDispute]=useState<DisputeRow|null>(null),[messages,setMessages]=useState<DisputeMessage[]>([]),[agreements,setAgreements]=useState<PreAgreement[]>([]),[reasons,setReasons]=useState<DisputeReason[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[ambiguous,setAmbiguous]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError(null);setAmbiguous(false);const{data:{session}}=await sb.auth.getSession();const uid=session?.user?.id||null;setUserId(uid);if(!uid){setService(null);setDispute(null);setMessages([]);setAgreements([]);setReasons([]);setLoading(false);return}
  const visibleStates=['asignado','en_camino','llegado','en_progreso','esperando_aprobacion','completado','disputado','cancelado'];let q=sb.from('servicios').select('id,numero,estado,tarifa,cliente_id,proveedor_id,descripcion').in('estado',visibleStates);q=role==='client'?q.eq('cliente_id',uid):q.eq('proveedor_id',uid);q=serviceId?q.eq('id',serviceId):q.order('created_at',{ascending:false}).limit(2);const{data:serviceRows,error:se}=await q;if(se){setError(se.message);setLoading(false);return}const rows=(serviceRows||[])as any[];if(!serviceId&&rows.length>1){setService(null);setDispute(null);setMessages([]);setAgreements([]);setAmbiguous(true);setLoading(false);return}const s=rows[0]||null;if(!s){setService(null);setDispute(null);setMessages([]);setAgreements([]);setLoading(false);return}
  const actor=role==='client'?'cliente':'proveedor'
  const[{data:d,error:de},{data:a,error:ae},{data:r,error:re}]=await Promise.all([
   sb.from('disputas').select('id,numero,servicio_id,cliente_id,proveedor_id,abierta_por,estado,motivo,motivo_codigo,evidencias,nivel_revision,requiere_humano,monto_disputado,resolucion,resolucion_favor,ajuste_financiero_pendiente,created_at,resuelta_at').eq('servicio_id',s.id).maybeSingle(),
   sb.from('acuerdos_previos_disputa').select('id,servicio_id,propuesto_por,tipo,detalle,monto,estado,respondido_por,respuesta,created_at,responded_at').eq('servicio_id',s.id).order('created_at',{ascending:false}).limit(10),
   sb.from('reglas_motivos_disputa').select('codigo,actor,etiqueta,severidad,requiere_humano,ventana_horas,evidencia_sugerida').eq('activo',true)
  ])
  if(de||ae||re){setError((de||ae||re)?.message||'No pudimos cargar el caso.');setLoading(false);return}
  const validReasons=((r||[])as DisputeReason[]).filter(item=>item.actor==='ambos'||item.actor===actor)
  if(!d&&s.estado==='cancelado'){setService(null);setDispute(null);setMessages([]);setAgreements([]);setReasons(validReasons);setLoading(false);return}
  setService(s);setDispute((d||null)as DisputeRow|null);setAgreements((a||[])as PreAgreement[]);setReasons(validReasons)
  if(d){const{data:m,error:me}=await sb.from('disputa_mensajes').select('id,disputa_id,autor_id,autor_rol,mensaje,evidencias,created_at').eq('disputa_id',d.id).order('created_at');if(me)setError(me.message);setMessages((m||[])as DisputeMessage[])}else setMessages([])
  setLoading(false)
 },[role,sb,serviceId])
 const uploadEvidence=useCallback(async(files:File[])=>{if(!service||!userId||!files.length)return[] as DisputeEvidence[];const selected=files.slice(0,5),uploaded:DisputeEvidence[]=[];for(const file of selected){if(file.size>10*1024*1024)throw new Error('Cada archivo puede pesar hasta 10 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-90)||'evidencia',id=globalThis.crypto?.randomUUID?.()||String(Date.now())+'-'+Math.random().toString(16).slice(2),path=service.id+'/'+userId+'/'+id+'-'+safe;const{error}=await sb.storage.from('dispute-evidence').upload(path,file,{contentType:file.type||undefined,upsert:false});if(error)throw error;uploaded.push({path,name:file.name,type:file.type||'application/octet-stream',size:file.size})}return uploaded},[sb,service,userId])
 const open=useCallback(async(motivo:string,motivoCodigo:string,evidencias:DisputeEvidence[]=[])=>{if(!service)throw new Error('Elegí el servicio exacto antes de abrir una disputa.');const{error}=await sb.rpc('abrir_disputa_v2',{p_servicio_id:service.id,p_motivo_codigo:motivoCodigo,p_motivo:motivo,p_evidencias:evidencias});if(error){await load();throw error}await load()},[service,sb,load])
 const reply=useCallback(async(mensaje:string,evidencias:DisputeEvidence[]=[])=>{if(!dispute)throw new Error('No hay disputa abierta');const{error}=await sb.rpc('responder_disputa',{p_disputa_id:dispute.id,p_mensaje:mensaje,p_evidencias:evidencias});if(error){await load();throw error}await load()},[dispute,sb,load])
 const proposeAgreement=useCallback(async(tipo:PreAgreement['tipo'],detalle:string,monto:number|null)=>{if(!service)throw new Error('Elegí el servicio exacto.');const{error}=await sb.rpc('proponer_acuerdo_previo',{p_servicio_id:service.id,p_tipo:tipo,p_detalle:detalle,p_monto:monto});if(error){await load();throw error}await load()},[service,sb,load])
 const respondAgreement=useCallback(async(id:string,accept:boolean,response='')=>{const{error}=await sb.rpc('responder_acuerdo_previo',{p_acuerdo_id:id,p_aceptar:accept,p_respuesta:response||null});if(error){await load();throw error}await load()},[sb,load])
 useEffect(()=>{void load();const refresh=()=>void load().catch(()=>{});const serviceFilter=serviceId?'id=eq.'+serviceId:role==='client'&&userId?'cliente_id=eq.'+userId:role==='provider'&&userId?'proveedor_id=eq.'+userId:undefined;let channel=sb.channel('ugo-dispute-'+role+'-'+(serviceId||userId||'session')).on('postgres_changes',{event:'*',schema:'public',table:'disputas'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'disputa_mensajes'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'acuerdos_previos_disputa'},refresh);channel=channel.on('postgres_changes',{event:'*',schema:'public',table:'servicios',...(serviceFilter?{filter:serviceFilter}:{})},refresh).subscribe((status:string)=>{if(status==='SUBSCRIBED')refresh()});const onOnline=()=>refresh();const onVisibility=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('online',onOnline);document.addEventListener('visibilitychange',onVisibility);return()=>{window.removeEventListener('online',onOnline);document.removeEventListener('visibilitychange',onVisibility);sb.removeChannel(channel)}},[load,role,sb,serviceId,userId])
 return{userId,service,dispute,messages,agreements,reasons,loading,error,ambiguous,refetch:load,uploadEvidence,open,reply,proposeAgreement,respondAgreement}
}
