import React,{useCallback,useEffect,useRef,useState}from'react'
import{getDispatchProvider}from'../../lib/dispatch/provider'
import{ServiceChat}from'../ServiceChat'
import{useRoleSession}from'../shared'
import{ClientServiceDetail}from'./ClientServiceDetail'
import{useClientFlow}from'./clientFlow'
import'./client-post-confirm.css'

type Draft={description?:string;categoryId?:string;categoryName?:string;categorySlug?:string;address?:string;addressLabel?:string;complement?:string;when?:string;scheduleAt?:string;urgent?:boolean;amount?:number|null;paymentMethod?:'pix'|'cash'}
type ServiceRow={id:string;estado:string;proveedor_id:string|null;proveedor?:{nombre?:string|null;karma?:number|null}|null;categoria?:{nombre?:string|null}|null}
type View='matching'|'assigned'|'chat'|'detail'
const MATCHING=new Set(['buscando','ofrecido'])
export function ClientPostConfirmFlow({onExit}:{onExit:()=>void}){
 const{session,supabase}=useRoleSession('client'),flow=useClientFlow(),[service,setService]=useState<ServiceRow|null>(null),[view,setView]=useState<View>('matching'),[seconds,setSeconds]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),creating=useRef(false)
 const draftKey=session?`ugo:guided-request-draft:${session.user.id}`:'',idKey=session?`ugo:canonical-active-service:${session.user.id}`:''
 const load=useCallback(async(id:string)=>{if(!session)return;const{data,error}=await supabase.from('servicios').select('id,estado,proveedor_id,proveedor:usuarios!servicios_proveedor_id_fkey(nombre,karma),categoria:categorias(nombre)').eq('id',id).eq('cliente_id',session.user.id).maybeSingle();if(error)throw error;if(data){const row=data as unknown as ServiceRow;setService(row);if(!MATCHING.has(row.estado)&&row.proveedor_id)setView('assigned')}},[session,supabase])
 const create=useCallback(async()=>{if(!session||creating.current)return;creating.current=true;setBusy(true);try{const existing=sessionStorage.getItem(idKey)||'';if(existing){await load(existing);return}const draft=JSON.parse(sessionStorage.getItem(draftKey)||'{}')as Draft;if(!draft.categoryId||!draft.description||!draft.address)throw new Error('El pedido perdió datos. Volvé al inicio y completalo nuevamente.');const requestDraftId=sessionStorage.getItem(`ugo:guided-request:${session.user.id}`)||crypto.randomUUID(),metadata={source:'canonical-client-12-screen',request_draft_id:requestDraftId,requested_when:draft.when||'hoy',scheduled_at:draft.scheduleAt||null,payment_method:draft.paymentMethod||'pix',address_label:draft.addressLabel||null,address_complement:draft.complement||null,demo:false};const{data,error}=await supabase.from('servicios').insert({cliente_id:session.user.id,categoria_id:draft.categoryId,estado:'buscando',descripcion:draft.description.trim(),direccion_cliente:[draft.address,draft.complement].filter(Boolean).join(' · '),tarifa:draft.amount??null,urgencia:Boolean(draft.urgent),metadata}).select('id,estado,proveedor_id').single();if(error)throw error;if(!data?.id)throw new Error('No se pudo crear el pedido.');const id=String(data.id);sessionStorage.setItem(idKey,id);setService(data as ServiceRow);setMessage('Pedido creado. Estamos avisando a profesionales verificados.');await getDispatchProvider().start({serviceId:id,category:draft.categorySlug||draft.categoryId});setMessage('Esperando respuestas de profesionales disponibles…')}catch(error){setMessage(error instanceof Error?error.message:'No pudimos publicar el pedido.')}finally{creating.current=false;setBusy(false)}},[draftKey,idKey,load,session,supabase])
 useEffect(()=>{void create()},[create])
 useEffect(()=>{if(view!=='matching')return;const t=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(t)},[view])
 useEffect(()=>{if(!service?.id)return;const id=service.id;const ch=supabase.channel(`client-canonical-${id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'servicios',filter:`id=eq.${id}`},()=>{void load(id)}).subscribe();return()=>{void supabase.removeChannel(ch)}},[load,service?.id,supabase])
 const cancel=async()=>{if(!service?.id||busy)return;setBusy(true);const ok=await flow.actions.cancelService(service.id);setBusy(false);if(ok){sessionStorage.removeItem(idKey);sessionStorage.removeItem(draftKey);onExit()}else setMessage('No pudimos cancelar. Reintentá.')}
 const retry=async()=>{if(!service?.id||busy)return;setBusy(true);try{const d=JSON.parse(sessionStorage.getItem(draftKey)||'{}')as Draft;await getDispatchProvider().start({serviceId:service.id,category:d.categorySlug||d.categoryId||''});setSeconds(0);setMessage('Búsqueda reintentada. Esperando respuestas…')}catch(error){setMessage(error instanceof Error?error.message:'No pudimos reintentar.')}finally{setBusy(false)}}
 if(view==='chat'&&service)return <div className="ugo-canonical-full"><header><button onClick={()=>setView('assigned')}>←</button><b>{service.proveedor?.nombre||'Profesional UGO'}</b></header><ServiceChat role="client" serviceId={service.id}/></div>
 if(view==='detail'&&service)return <ClientServiceDetail serviceId={service.id} onClose={()=>setView('assigned')}/>
 if(view==='assigned'&&service)return <main className="ugo-assigned-screen"><section><div className="ugo-assigned-avatar">👤<i>✓</i></div><h1>¡Profesional asignado!</h1><p>Tu pedido fue aceptado</p><article><span>👤</span><div><b>{service.proveedor?.nombre||'Profesional UGO'}</b><small>★ {service.proveedor?.karma??'Nuevo'} · {service.categoria?.nombre||'Servicio'}</small></div></article><button className="primary" onClick={()=>setView('chat')}>Abrir chat</button><button onClick={()=>setView('detail')}>Ver detalles del pedido</button></section></main>
 const timedOut=seconds>=90
 return <main className="ugo-matching-screen"><section><div className="ugo-matching-orb">⌁</div><h1>Buscando tu profesional…</h1><p>Estamos enviando tu pedido a profesionales verificados cerca tuyo.<br/>Te avisaremos cuando alguien lo acepte.</p><ol><li className="done">✓ <span>Pedido creado</span></li><li className={service?'done':''}>{service?'✓':'○'} <span>Enviando a profesionales</span></li><li className={seconds>2?'done':''}>{seconds>2?'✓':'○'} <span>Esperando respuestas</span></li><li>○ <span>Asignando profesional</span></li><li>○ <span>¡Listo!</span></li></ol>{message&&<p className="ugo-match-message">{message}</p>}{timedOut&&<div className="ugo-match-recovery"><b>Todavía no encontramos un profesional.</b><button disabled={busy} onClick={()=>void retry()}>Reintentar</button></div>}<button className="cancel" disabled={!service||busy} onClick={()=>void cancel()}>Cancelar pedido</button></section></main>
}
export default ClientPostConfirmFlow
