import React,{useEffect,useMemo,useState}from'react'
import{useRoleSession,type Category}from'../shared'
import{useClientFlow}from'./clientFlow'
import{ClientLocationScreen}from'./ClientLocationScreen'
import{ClientPostConfirmFlow}from'./ClientPostConfirmFlow'
import'./client-need-screen.css'

const QUICK:Record<string,string[]>={electricidad:['Reparar toma de corriente','Instalar luminaria','Revisar tablero eléctrico','Otro…'],plomeria:['Reparar pérdida de agua','Destapar cañería','Cambiar grifería','Otro…'],limpieza:['Limpieza general','Limpieza profunda','Limpieza después de obra','Otro…'],reparaciones:['Montaje o instalación','Reparación en el hogar','Ajuste o mantenimiento','Otro…']}
const norm=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
export function ClientNeedScreen(){
 const flow=useClientFlow(),{supabase,session}=useRoleSession('client'),[categories,setCategories]=useState<Category[]>([]),[description,setDescription]=useState(''),[message,setMessage]=useState(''),[stage,setStage]=useState<'need'|'location'|'post'>('need'),[paymentChecked,setPaymentChecked]=useState(false),[paymentAllowed,setPaymentAllowed]=useState(false)
 useEffect(()=>{if(!session)return;let alive=true;void supabase.from('preferencias_pago_cliente').select('metodo').eq('usuario_id',session.user.id).maybeSingle().then(({data,error})=>{if(!alive)return;const allowed=!error&&(data?.metodo==='pix'||data?.metodo==='efectivo');setPaymentAllowed(allowed);setPaymentChecked(true);if(!allowed)flow.navigate('home')});return()=>{alive=false}},[flow,session,supabase])
 useEffect(()=>{if(!session)return;let alive=true;void supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre').then(({data})=>{if(alive)setCategories((data||[])as Category[])});return()=>{alive=false}},[session,supabase])
 const hint=norm(`${flow.hugoIntent?.categoryHint||''} ${flow.hugoIntent?.text||''}`),category=useMemo(()=>categories.find(item=>{const text=norm(`${item.slug} ${item.nombre}`);return hint&&text.split(/\s+/).some(token=>token.length>3&&hint.includes(token))})||null,[categories,hint]),key=category?norm(category.slug||category.nombre):'',quick=Object.entries(QUICK).find(([name])=>key.includes(name)||hint.includes(name))?.[1]||['Describir el trabajo','Instalación','Reparación','Otro…']
 useEffect(()=>{if(!session)return;try{const raw=sessionStorage.getItem(`ugo:guided-request-draft:${session.user.id}`);if(raw){const draft=JSON.parse(raw)as{description?:string};if(draft.description)setDescription(draft.description)}}catch{}},[session])
 const saveNeed=()=>{if(!paymentAllowed){setMessage('Elegí una forma de pago en Inicio antes de pedir un servicio.');return false}const value=description.trim();if(value.length<8){setMessage('Contanos un poco más sobre lo que necesitás.');return false}if(!session||!category){setMessage('No pudimos identificar la categoría. Volvé y elegila nuevamente.');return false}try{const storageKey=`ugo:guided-request-draft:${session.user.id}`,raw=sessionStorage.getItem(storageKey),previous=raw?JSON.parse(raw):{};sessionStorage.setItem(storageKey,JSON.stringify({...previous,categoryId:category.id,categoryName:category.nombre,categorySlug:category.slug,description:value}))}catch{}return true}
 const continueNeed=()=>{if(saveNeed())setStage('location')}
 if(!session||!paymentChecked||!paymentAllowed)return null
 if(stage==='post')return <ClientPostConfirmFlow onExit={()=>flow.navigate('home')}/>
 if(stage==='location')return <ClientLocationScreen onBack={()=>setStage('need')} onContinue={()=>setStage('post')}/>
 return <main className="ugo-need-screen" aria-label="Qué hay que hacer"><header className="ugo-need-top"><button type="button" onClick={()=>flow.navigate('home')} aria-label="Volver">←</button><strong>UGO</strong><div className="ugo-need-progress"><i/><i/><i/><i/><i/></div><small>1 de 5</small></header><section className="ugo-need-body"><div className="ugo-need-category"><span>{category?.emoji||'🧰'}</span><div><h1>{category?.nombre||flow.hugoIntent?.categoryHint||'Servicio'}</h1><p>Contanos qué necesitás</p></div></div><textarea autoFocus maxLength={500} value={description} onChange={event=>{setDescription(event.target.value);setMessage('')}} placeholder="Ej: No funciona una toma de corriente en la cocina…" aria-label="Descripción del trabajo"/><div className="ugo-need-counter">{description.length}/500</div><h2>Opciones rápidas</h2><div className="ugo-need-quick">{quick.map(option=><button type="button" key={option} onClick={()=>{if(option==='Otro…')return;setDescription(option);setMessage('')}}>{option}</button>)}</div>{message&&<p className="ugo-need-error" role="alert">{message}</p>}</section><footer><button type="button" disabled={!category} onClick={continueNeed}>Continuar <span>→</span></button></footer></main>
}
export default ClientNeedScreen
