import React,{useCallback,useEffect,useMemo,useState}from'react'
import{supabase}from'../../lib/supabase'
import{getDispatchProvider}from'../../lib/dispatch/provider'
import{ClientRequestEvidence}from'../ClientRequestEvidence'
import{parseClientIntent}from'../hugoIntent'
import{UGO_UI_EVENTS}from'../uiEvents'
import type{Category}from'../shared'
import{useClientFlow}from'./clientFlow'

type Step='idle'|'need'|'photo'|'when'|'review'|'matching'
type Draft={description:string;categoryId:string;categoryName:string;categorySlug:string;address:string;when:'ahora'|'hoy'|'programar';urgent:boolean;amount:number}
const emptyDraft:Draft={description:'',categoryId:'',categoryName:'',categorySlug:'',address:'',when:'hoy',urgent:false,amount:120}
function normalize(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function categoryByHint(categories:Category[],hint:string){const q=normalize(hint);return categories.find(c=>[c.nombre,c.slug].some(v=>{const n=normalize(String(v||''));return n.includes(q)||q.includes(n)}))||null}

export function ClientGuidedRequest(){
 const flow=useClientFlow()
 const[categories,setCategories]=useState<Category[]>([]),[step,setStep]=useState<Step>('idle'),[draft,setDraft]=useState<Draft>(emptyDraft),[draftId,setDraftId]=useState(''),[photoCount,setPhotoCount]=useState(0),[photoBusy,setPhotoBusy]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[hasActive,setHasActive]=useState(false),[ready,setReady]=useState(false)
 const progress=step==='need'?1:step==='photo'?2:step==='when'?3:step==='review'?4:step==='matching'?5:0
 const selectedCategory=useMemo(()=>categories.find(c=>c.id===draft.categoryId)||null,[categories,draft.categoryId])

 const load=useCallback(async()=>{const{data:user}=await supabase.auth.getUser();if(!user.user){setReady(false);return}const[{data:cats},{data:profile},{data:active}]=await Promise.all([supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.from('perfiles_cliente').select('direccion,barrio,ciudad,onboarding_completo_at,termos_aceitos_at').eq('usuario_id',user.user.id).maybeSingle(),supabase.from('servicios').select('id').eq('cliente_id',user.user.id).in('estado',['solicitado','buscando','ofrecido','asignado','pago_pendiente','pago_habilitado','en_camino','llegado','en_progreso','esperando_aprobacion']).limit(1)]);const p=profile as{direccion?:string|null;barrio?:string|null;ciudad?:string|null;onboarding_completo_at?:string|null;termos_aceitos_at?:string|null}|null;setReady(Boolean(p?.onboarding_completo_at&&p?.termos_aceitos_at));setCategories((cats||[])as Category[]);setHasActive(Boolean(active?.length));const address=[p?.direccion,p?.barrio,p?.ciudad].filter(Boolean).join(', ');setDraft(v=>({...v,address:v.address||address}));let id='';try{id=sessionStorage.getItem(`ugo:guided-request:${user.user!.id}`)||''}catch{}if(!id)id=crypto.randomUUID();setDraftId(id);try{sessionStorage.setItem(`ugo:guided-request:${user.user.id}`,id)}catch{}},[])
 useEffect(()=>{void load()},[load])

 const infer=useCallback((text:string,hint?:string|null,urgent=false)=>{let category=hint?categoryByHint(categories,hint):null;if(!category){const intent=parseClientIntent(text,categories);category=categories.find(c=>c.id===intent.categoryId)||null;urgent=urgent||intent.urgency}if(category)setDraft(v=>({...v,description:text,categoryId:category!.id,categoryName:category!.nombre,categorySlug:category!.slug,urgent}));else setDraft(v=>({...v,description:text,urgent}));return category},[categories])

 useEffect(()=>{if(!ready)return;const onText=(event:Event)=>{const text=String((event as CustomEvent<{text?:string}>).detail?.text||'').trim();if(!text)return;infer(text);setStep('need')};const onIntent=(event:Event)=>{const d=(event as CustomEvent<{text?:string;description?:string|null;categoryHint?:string|null;urgent?:boolean}>).detail||{};const text=String(d.description||d.text||'').trim();if(!text)return;infer(text,d.categoryHint,Boolean(d.urgent));setStep('need')};window.addEventListener('ugo:hugo-user-text',onText as EventListener);window.addEventListener('ugo:hugo-ai-intent',onIntent as EventListener);return()=>{window.removeEventListener('ugo:hugo-user-text',onText as EventListener);window.removeEventListener('ugo:hugo-ai-intent',onIntent as EventListener)}},[infer,ready])

 function start(){if(hasActive){setMessage('Ya tenés un servicio en curso. Podés seguirlo desde Inicio.');return}setMessage('');setStep('need')}
 function askHugo(){window.dispatchEvent(new Event(UGO_UI_EVENTS.clientHugo))}
 async function confirmNeed(){const text=draft.description.trim();if(text.length<5){setMessage('Contame en una frase qué necesitás.');return}const category=selectedCategory||infer(text);if(!category){setMessage('Hugo necesita confirmar qué tipo de profesional corresponde. Elegí una categoría o contale un poco más.');return}setDraft(v=>({...v,categoryId:category.id,categoryName:category.nombre,categorySlug:category.slug}));setMessage('');setStep('photo')}
 function confirmWhen(value:Draft['when']){setDraft(v=>({...v,when:value,urgent:value==='ahora'}));setMessage('');setStep('review')}

 async function submit(){if(!draft.categoryId||draft.description.trim().length<5)return;if(photoCount<1){setMessage('Agregá al menos una foto del trabajo antes de enviar la solicitud.');setStep('photo');return}setBusy(true);setMessage('');try{const{data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user)throw new Error('Iniciá sesión para pedir el servicio.');const{data,error}=await supabase.from('servicios').insert({cliente_id:user.id,categoria_id:draft.categoryId,estado:'buscando',descripcion:draft.description.trim(),direccion_cliente:draft.address.trim()||null,tarifa:draft.amount,urgencia:draft.urgent,metadata:{source:'hugo-guided-request',request_draft_id:draftId,requested_when:draft.when,demo:false}}).select('id').single();if(error)throw error;if(!data?.id)throw new Error('No se pudo crear la solicitud.');setStep('matching');const result=await getDispatchProvider().start({serviceId:String(data.id),category:draft.categorySlug||draft.categoryId});const count=Array.isArray(result.raw)?result.raw.length:result.providerId?1:0;setMessage(count?`Listo. UGO avisó a ${count} profesional${count===1?'':'es'} y espera una aceptación.`:'Solicitud creada. UGO sigue buscando un profesional disponible.');setHasActive(true);flow.navigate('home');window.setTimeout(()=>setStep('idle'),1800)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo enviar la solicitud.')}finally{setBusy(false)}}

 if(!ready)return null
 if(hasActive&&step==='idle')return null
 if(step==='idle')return <button type="button" className="ugo-guided-launch" onClick={start}>Pedir un servicio</button>
 return <section className="ugo-guided-request" aria-label="Solicitud guiada por Hugo"><header><button type="button" className="ugo-guided-back" onClick={()=>step==='need'?setStep('idle'):step==='photo'?setStep('need'):step==='when'?setStep('photo'):step==='review'?setStep('when'):setStep('idle')} aria-label="Volver">←</button><div><small>{Math.min(progress,4)} de 4</small><div className="ugo-guided-progress"><i style={{width:`${Math.min(progress,4)*25}%`}}/></div></div><button type="button" className="ugo-guided-orb" onClick={askHugo} aria-label="Hablar con Hugo">⌁</button></header>
  {step==='need'&&<div className="ugo-guided-step"><p className="ugo-guided-kicker">Hugo te ayuda</p><h2>¿Qué necesitás?</h2><p>Contámelo como se lo contarías a un amigo. Yo armo el pedido.</p><textarea autoFocus value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))} placeholder="Ej: Necesito colocar azulejos en el baño"/><button type="button" className="ugo-guided-voice" onClick={askHugo}>🎙 Hablar con Hugo</button>{selectedCategory&&<div className="ugo-guided-understood"><span>Entendí</span><b>{selectedCategory.emoji} {selectedCategory.nombre}</b><small>{draft.description}</small></div>}{!selectedCategory&&draft.description.length>4&&<div className="ugo-guided-categories">{categories.slice(0,6).map(c=><button type="button" key={c.id} onClick={()=>setDraft(v=>({...v,categoryId:c.id,categoryName:c.nombre,categorySlug:c.slug}))}>{c.emoji} {c.nombre}</button>)}</div>}<button type="button" className="ugo-guided-primary" onClick={confirmNeed}>Sí, es eso</button></div>}
  {step==='photo'&&<div className="ugo-guided-step"><p className="ugo-guided-kicker">Evidencia del pedido</p><h2>Mostrame el problema</h2><p>Agregá al menos una foto. Ayuda a Hugo y al profesional a entender el trabajo antes de aceptar.</p><ClientRequestEvidence draftId={draftId} inline onBusyChange={setPhotoBusy} onCountChange={setPhotoCount}/><button type="button" className="ugo-guided-primary" disabled={photoBusy||photoCount<1} onClick={()=>setStep('when')}>{photoBusy?'Subiendo foto…':photoCount?'Usar esta foto':'Agregá una foto para continuar'}</button></div>}
  {step==='when'&&<div className="ugo-guided-step"><p className="ugo-guided-kicker">Casi listo</p><h2>¿Cuándo lo necesitás?</h2><div className="ugo-guided-options"><button type="button" onClick={()=>confirmWhen('ahora')}><b>⚡ Ahora</b><span>Lo antes posible</span></button><button type="button" onClick={()=>confirmWhen('hoy')}><b>Hoy</b><span>Durante el día</span></button><button type="button" onClick={()=>confirmWhen('programar')}><b>Elegir horario</b><span>El profesional coordina contigo</span></button></div><label>¿Dónde?<input value={draft.address} onChange={e=>setDraft(v=>({...v,address:e.target.value}))} placeholder="Tu dirección"/></label></div>}
  {step==='review'&&<div className="ugo-guided-step"><p className="ugo-guided-kicker">Hugo entendió esto</p><h2>Revisá y confirmá</h2><div className="ugo-guided-summary"><div><span>Servicio</span><b>{selectedCategory?.emoji} {draft.categoryName}</b></div><div><span>Necesidad</span><b>{draft.description}</b></div><div><span>Cuándo</span><b>{draft.when==='ahora'?'Ahora':draft.when==='hoy'?'Hoy':'A coordinar'}</b></div><div><span>Dónde</span><b>{draft.address||'Ubicación a confirmar'}</b></div><div><span>Fotos</span><b>{photoCount} adjunta{photoCount===1?'':'s'}</b></div></div><button type="button" className="ugo-guided-primary" onClick={submit} disabled={busy||photoCount<1}>{busy?'Buscando…':'Encontrar profesionales'}</button></div>}
  {step==='matching'&&<div className="ugo-guided-step ugo-guided-matching"><div className="ugo-guided-pulse">⌁</div><h2>Buscando profesionales…</h2><p>{message||'Hugo está buscando la mejor opción disponible para tu solicitud.'}</p></div>}
  {message&&step!=='matching'&&<div className="ugo-guided-message">{message}</div>}
 </section>
}
