import React,{useCallback,useEffect,useMemo,useRef,useState}from'react'
import{getDispatchProvider}from'../../lib/dispatch/provider'
import{UGO_UI_EVENTS}from'../uiEvents'
import{useRoleSession,type Category}from'../shared'
import{useClientFlow}from'./clientFlow'
import{EMPTY_HUGO_DRAFT,hugoAddress,hugoCategory,hugoDescription,hugoMissing,hugoQuestion,hugoTiming,isHugoAffirmative,isHugoCancel,isHugoEdit,wantsHugoLocation,type HugoDraft}from'./hugoOrderVoice'
import'./client-hugo-voice-order.css'

type ActiveService={id:string;estado:string;descripcion:string;direccion_cliente:string|null;categoria?:{nombre?:string;emoji?:string}|null;metadata?:{requested_when?:string;scheduled_at?:string}|null}
type VoiceWindow=Window&{UGOVoiceBridge?:{startListening:()=>void;stopListening:()=>void};SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any}
const ACTIVE=['buscando','ofrecido','asignado','en_camino','llegado','en_progreso','esperando_aprobacion','disputado']
const CANCELLABLE=['buscando','ofrecido','asignado','en_camino','llegado']
async function reverseGeocode(lat:number,lng:number){try{const r=await fetch(`https://photon.komoot.io/reverse?lat=${lat}&lon=${lng}`,{headers:{accept:'application/json'}}),j:any=await r.json();const p=j?.features?.[0]?.properties||{};return[p.name,p.street,p.district,p.city,p.state].filter(Boolean).join(', ')||null}catch{return null}}

export function ClientHugoVoiceOrder(){
 const flow=useClientFlow(),auth=useRoleSession('client'),{session,supabase}=auth
 const[categories,setCategories]=useState<Category[]>([]),[active,setActive]=useState<ActiveService|null>(null),[open,setOpen]=useState(false),[draft,setDraft]=useState<HugoDraft>(EMPTY_HUGO_DRAFT),[reply,setReply]=useState('Decime qué necesitás. Yo completo el pedido y vos solo confirmás.'),[heard,setHeard]=useState(''),[voice,setVoice]=useState(false),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[locationConsent,setLocationConsent]=useState(false)
 const recognition=useRef<any>(null),native=useRef(false)
 const ready=hugoMissing(draft).length===0,activeCategory=active?.categoria?.nombre||'Servicio'
 const activeWhen=useMemo(()=>{if(active?.metadata?.requested_when==='ahora')return'Ahora';if(active?.metadata?.requested_when==='hoy')return'Hoy';const at=active?.metadata?.scheduled_at;if(at){const d=new Date(at);if(!Number.isNaN(d.getTime()))return d.toLocaleString('es-AR')}return'—'},[active])
 const load=useCallback(async()=>{if(!session)return;const[{data:cats},{data:rows}]=await Promise.all([supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.from('servicios').select('id,estado,descripcion,direccion_cliente,metadata,categoria:categorias(nombre,emoji)').eq('cliente_id',session.user.id).in('estado',ACTIVE).order('created_at',{ascending:false}).limit(1)]);setCategories((cats||[])as Category[]);setActive((((rows||[])[0]||null)as unknown as ActiveService|null))},[session,supabase])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!session)return;const c=supabase.channel(`hugo-order-${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'servicios',filter:`cliente_id=eq.${session.user.id}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[load,session,supabase])
 useEffect(()=>{const show=()=>{setOpen(true);setReply(active?`Tenés un pedido activo: ${activeCategory}. Acá podés verlo o cancelarlo.`:'Decime qué necesitás. Yo completo el pedido y vos solo confirmás.')};window.addEventListener(UGO_UI_EVENTS.clientHugoVoice,show);return()=>window.removeEventListener(UGO_UI_EVENTS.clientHugoVoice,show)},[active,activeCategory])
 useEffect(()=>()=>{try{recognition.current?.abort?.()}catch{}try{(window as VoiceWindow).UGOVoiceBridge?.stopListening()}catch{}},[])

 function clearDraft(message='Pedido cancelado.'){setDraft(EMPTY_HUGO_DRAFT);setEditing(false);setLocationConsent(false);setReply(message)}
 async function cancelActive(){if(!active)return false;if(!CANCELLABLE.includes(active.estado)){setReply('Este servicio ya está en una etapa que no permite cancelación directa. Abrí Ayuda y disputas si necesitás intervenir.');return false}setBusy(true);const ok=await flow.actions.cancelService();setBusy(false);if(ok){setActive(null);clearDraft();return true}setReply('No pude cancelar el pedido. El servicio sigue activo y permanece visible.');return false}
 async function locate(){if(!navigator.geolocation){setLocationConsent(false);setReply('Este dispositivo no ofrece ubicación. Decime la dirección.');return}setBusy(true);navigator.geolocation.getCurrentPosition(async p=>{const address=await reverseGeocode(p.coords.latitude,p.coords.longitude);const next={...draft,address:address||`GPS ${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`};setDraft(next);setBusy(false);setLocationConsent(false);setReply(hugoQuestion(next)||`Perfecto. ${next.categoryName} · ${next.description}. ${next.address}. ${next.whenLabel}. ¿Confirmo el pedido?`)},()=>{setBusy(false);setLocationConsent(false);setReply('No pude obtener tu ubicación. Decime la dirección.')},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
 async function createOrder(){if(!session||!ready||busy)return;setBusy(true);try{const metadata={source:'hugo-voice-order',voice:true,demo:false,requested_when:draft.urgency==='now'?'ahora':draft.urgency==='today'?'hoy':'programar',scheduled_at:draft.scheduleAt||null};const{data,error}=await supabase.from('servicios').insert({cliente_id:session.user.id,categoria_id:draft.categoryId,estado:'buscando',descripcion:draft.description.trim(),direccion_cliente:draft.address.trim(),tarifa:null,urgencia:draft.urgency==='now',metadata}).select('id').single();if(error)throw error;if(!data?.id)throw new Error('No se pudo crear el pedido.');await getDispatchProvider().start({serviceId:String(data.id),category:draft.categorySlug||draft.categoryId});setReply(`${draft.categoryName} · ${draft.description}. Pedido confirmado. UGO ya está buscando profesionales.`);setDraft(EMPTY_HUGO_DRAFT);await load()}catch(e){setReply(e instanceof Error?`No pude crear el pedido: ${e.message}`:'No pude crear el pedido.')}finally{setBusy(false)}}
 async function handleText(raw:string){const text=raw.trim();if(!text)return;setHeard(text);if(isHugoCancel(text)){if(active)await cancelActive();else clearDraft();return}if(isHugoEdit(text)){setEditing(true);setReply('Decime qué querés cambiar: servicio, problema, ubicación o cuándo.');return}if(locationConsent){if(isHugoAffirmative(text)){await locate();return}setLocationConsent(false);setReply('Está bien. Decime la dirección del servicio.');return}if(active){setReply(`Tu pedido activo es ${activeCategory}: ${active.descripcion}. ${active.direccion_cliente||'Ubicación registrada'}. Podés decir “cancelar pedido”.`);return}if(wantsHugoLocation(text)){setLocationConsent(true);setReply('¿Me autorizás a usar tu ubicación actual para este pedido?');return}if(isHugoAffirmative(text)&&ready&&!editing){await createOrder();return}const category=hugoCategory(categories,text),timing=hugoTiming(text),address=hugoAddress(text),description=hugoDescription(text);let next={...draft};if(category)next={...next,categoryId:category.id,categoryName:category.nombre,categorySlug:category.slug};if(timing)next={...next,...timing};if(address)next={...next,address};if(editing){if(!category&&!timing&&!address&&description)next={...next,description};setEditing(false)}else if(description&&(!next.description||/\b(necesito|quiero|preciso|quero)\b/i.test(text)))next={...next,description};setDraft(next);const missing=hugoMissing(next);setReply(missing.length?hugoQuestion(next):`Perfecto. ${next.categoryName} · ${next.description}. ${next.address}. ${next.whenLabel}. ¿Confirmo el pedido?`)}

 function stopVoice(){setVoice(false);const w=window as VoiceWindow;if(native.current){try{w.UGOVoiceBridge?.stopListening()}catch{}native.current=false}try{recognition.current?.abort?.()}catch{}recognition.current=null}
 function startVoice(){if(voice){stopVoice();return}const w=window as VoiceWindow;if(w.UGOVoiceBridge){native.current=true;setVoice(true);const done=(e:Event)=>{const d=(e as CustomEvent<any>).detail||{},text=String(d.text||'').trim();if(d.final===false||!text)return;setVoice(false);void handleText(text)};window.addEventListener('ugo:native-voice-result',done as EventListener,{once:true});window.addEventListener('ugo:native-voice-error',()=>setVoice(false),{once:true});try{w.UGOVoiceBridge.startListening()}catch{setVoice(false);setReply('No pude iniciar el micrófono. Podés escribir el pedido.')}return}const R=w.SpeechRecognition||w.webkitSpeechRecognition;if(!R){setReply('La voz no está disponible en este navegador. Podés escribir el pedido.');return}const r=new R();r.lang='es-AR';r.continuous=false;r.interimResults=false;r.onresult=(e:any)=>{const text=String(e.results?.[0]?.[0]?.transcript||'').trim();if(text)void handleText(text)};r.onerror=()=>{setVoice(false);setReply('No pude escuchar. Intentá otra vez o escribí el pedido.')};r.onend=()=>setVoice(false);recognition.current=r;setVoice(true);try{r.start()}catch{setVoice(false)}}
 if(auth.loading||!session)return null
 const hasDraft=Boolean(draft.categoryName||draft.description||draft.address||draft.whenLabel)
 return <><button type="button" className="ugo-hugo-voice-fab" onClick={()=>setOpen(true)} aria-label="Hablar con Hugo"><span>⌁</span><small>Hugo</small></button>{active&&<aside className="ugo-active-order-chip"><div><small>PEDIDO ACTIVO</small><b>{active.categoria?.emoji||'🧰'} {activeCategory}</b><span>{active.descripcion}</span></div><button type="button" onClick={()=>setOpen(true)}>Ver</button></aside>}{open&&<div className="ugo-hugo-voice-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="ugo-hugo-voice-panel" role="dialog" aria-modal="true" aria-label="Hugo, asistente de voz de UGO"><header><div><span className="ugo-hugo-orb">⌁</span><strong>Hugo</strong></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></header><div className="ugo-hugo-reply"><b>Hugo</b><p>{busy?'Procesando…':reply}</p>{heard&&<small>Vos: {heard}</small>}</div>{(active||hasDraft)&&<div className="ugo-hugo-summary"><div><span>Servicio</span><b>{active?`${active.categoria?.emoji||'🧰'} ${activeCategory}`:draft.categoryName||'Pendiente'}</b></div><div><span>Pedido</span><b>{active?.descripcion||draft.description||'Pendiente'}</b></div><div><span>Ubicación</span><b>{active?.direccion_cliente||draft.address||'Pendiente'}</b></div><div><span>Cuándo</span><b>{active?activeWhen:draft.whenLabel||'Pendiente'}</b></div></div>}{!active&&<form className="ugo-hugo-text" onSubmit={e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('hugoText')as HTMLInputElement;if(input.value.trim()){void handleText(input.value);input.value=''}}}><input name="hugoText" placeholder="Ej: Necesito un plomero mañana a las 10 en Canasvieiras…"/><button>Enviar</button></form>}<button type="button" className={`ugo-hugo-mic${voice?' active':''}`} onClick={startVoice} disabled={busy}>{voice?'■ Detener':'🎙 Hablar con Hugo'}</button><div className="ugo-hugo-actions"><button type="button" className="danger" disabled={busy||(!active&&!hasDraft)} onClick={()=>void(active?cancelActive():Promise.resolve(clearDraft()))}>Cancelar pedido</button><button type="button" disabled={busy||Boolean(active)||!hasDraft} onClick={()=>{setEditing(true);setReply('Decime qué querés cambiar: servicio, problema, ubicación o cuándo.')}}>Editar pedido</button><button type="button" className="primary" disabled={busy||Boolean(active)||!ready} onClick={()=>void createOrder()}>Confirmar pedido</button></div></section></div>}</>
}
export default ClientHugoVoiceOrder
