import React,{useEffect,useMemo,useState}from'react'
import{useRoleSession,type Category}from'../shared'
import{useClientFlow}from'./clientFlow'
import'./client-home-screen.css'
const norm=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
const CORE=[['limpieza','Limpieza','🧹','Hogar y oficinas'],['repar','Reparaciones','🔧','Hogar en general'],['electric','Electricidad','⚡','Instalaciones y reparaciones'],['plomer','Plomería','🚰','Instalaciones y reparaciones']] as const
export function ClientHomeScreen(){
 const flow=useClientFlow(),{supabase,session}=useRoleSession('client'),[categories,setCategories]=useState<Category[]>([]),[query,setQuery]=useState(''),[showAll,setShowAll]=useState(false)
 useEffect(()=>{if(!session)return;let alive=true;void supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre').then(({data})=>{if(alive)setCategories((data||[])as Category[])});return()=>{alive=false}},[session,supabase])
 const cards=useMemo(()=>CORE.map(([key,label,emoji,sub])=>({key,label,emoji,sub,category:categories.find(c=>norm(`${c.slug} ${c.nombre}`).includes(key))||null})),[categories]),filtered=query.trim()?categories.filter(c=>norm(c.nombre).includes(norm(query.trim()))):[]
 const choose=(category:Category|null)=>{if(!category)return;flow.publishHugoIntent({text:`Necesito ${category.nombre}`,categoryHint:category.slug||category.id,urgent:false,description:null});flow.navigate('request')}
 if(!session)return null
 return <main className="ugo-home-screen" aria-label="Inicio UGO Cliente"><header><button type="button" className="ugo-home-menu" onClick={()=>document.querySelector<HTMLButtonElement>('.ugo-client-global-trigger')?.click()} aria-label="Abrir menú">☰</button><strong>UG<span>O</span></strong><button type="button" className="ugo-home-place">⌖ Florianópolis⌄</button><button type="button" className="ugo-home-bell" onClick={()=>document.querySelector<HTMLButtonElement>('.ugo-notification-center.role-client .ugo-notification-trigger')?.click()} aria-label="Notificaciones">♢</button></header><section><h1>¿Qué servicio<br/>necesitás?</h1><p>Profesionales verificados, cuando los necesitás.</p><label className="ugo-home-search">⌕<input value={query} onChange={e=>{setQuery(e.target.value);setShowAll(false)}} placeholder="Buscar servicios…"/></label>{filtered.length>0&&<div className="ugo-home-results">{filtered.slice(0,8).map(c=><button type="button" key={c.id} onClick={()=>choose(c)}>{c.emoji||'🧰'} {c.nombre}</button>)}</div>}<div className="ugo-home-categories">{cards.map(({key,label,emoji,sub,category})=><button type="button" key={key} disabled={!category} onClick={()=>choose(category)}><span>{category?.emoji||emoji}</span><b>{label}</b><small>{sub}</small></button>)}</div><button type="button" className="ugo-home-all" onClick={()=>setShowAll(v=>!v)}>{showAll?'Ocultar categorías':'Ver todas las categorías'} <span>{showAll?'↑':'→'}</span></button>{showAll&&<div className="ugo-home-results ugo-home-all-results" aria-label="Todas las categorías">{categories.map(c=><button type="button" key={c.id} onClick={()=>choose(c)}>{c.emoji||'🧰'} {c.nombre}</button>)}</div>}</section></main>
}
export default ClientHomeScreen
