import React,{useEffect,useMemo,useRef,useState}from'react'
import * as maplibregl from'maplibre-gl'
import'maplibre-gl/dist/maplibre-gl.css'
import{useRoleSession,type Category}from'../shared'
import{UGO_UI_EVENTS,emitUgoUiEvent}from'../uiEvents'
import{useClientFlow}from'./clientFlow'
import{refreshProviderRadar,subscribeProviderRadar,type ProviderRadarRow}from'./providerRadarStore'
import'./client-premium-home.css'

const FLORIPA:[number,number]=[-48.5482,-27.5949]
const MAP_STYLE:maplibregl.StyleSpecification={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}
const ACTIVE_STATES=['buscando','ofrecido','asignado','en_camino','llegado','en_progreso','esperando_aprobacion','disputado']
type ClientProfile={direccion?:string|null;barrio?:string|null;ciudad?:string|null}
type ServiceSummary={id:string;numero?:number|string|null;estado:string;created_at?:string|null;programado_para?:string|null;valor_total?:number|null;categoria?:{nombre?:string|null;emoji?:string|null}|null;proveedor?:{nombre?:string|null;karma?:number|string|null}|null}
const norm=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
const categoryText=(category:Category)=>norm(`${category.slug} ${category.nombre}`)
const CORE_SERVICES:Array<{key:string;label:string;emoji:string;matches:(category:Category)=>boolean}>=[
 {key:'cleaning',label:'Limpieza',emoji:'🧹',matches:category=>categoryText(category).includes('limpieza')},
 {key:'repairs',label:'Reparaciones',emoji:'🛠️',matches:category=>['repar','montaje'].some(key=>categoryText(category).includes(key))},
 {key:'electricity',label:'Electricidad',emoji:'⚡',matches:category=>categoryText(category).includes('electric')},
 {key:'plumbing',label:'Plomería',emoji:'🔧',matches:category=>categoryText(category).includes('plomer')},
]
const money=(value:number|null|undefined)=>Number.isFinite(Number(value))?`R$ ${Number(value).toLocaleString('pt-BR',{minimumFractionDigits:0,maximumFractionDigits:0})}`:'A confirmar'
const statusLabel=(status:string)=>({buscando:'Buscando profesional',ofrecido:'Recibiendo ofertas',asignado:'Profesional asignado',en_camino:'En camino',llegado:'Llegó',en_progreso:'Trabajo en curso',esperando_aprobacion:'Esperando aprobación',completado:'Completado',cancelado:'Cancelado'}[status]||status.replaceAll('_',' '))

export function ClientPremiumHome({onOpenService}:{onOpenService?:(serviceId:string)=>void}){
 const flow=useClientFlow(),auth=useRoleSession('client'),{supabase,session,profile}=auth
 const[categories,setCategories]=useState<Category[]>([]),[place,setPlace]=useState('Florianópolis - Canasvieiras'),[selectedId,setSelectedId]=useState(''),[providers,setProviders]=useState<ProviderRadarRow[]>([]),[services,setServices]=useState<ServiceSummary[]>([])
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),userMarkerRef=useRef<maplibregl.Marker|null>(null),providerMarkersRef=useRef<maplibregl.Marker[]>([])
 const coreCategories=useMemo(()=>CORE_SERVICES.map(item=>({item,category:categories.find(item.matches)||null})),[categories])
 const selected=useMemo(()=>categories.find(item=>item.id===selectedId)||coreCategories.find(item=>item.category)?.category||null,[categories,selectedId,coreCategories])
 const selectedProviders=useMemo(()=>providers.filter(provider=>{const ids=Array.isArray(provider.categoria_ids)?provider.categoria_ids:[];return Boolean(provider.online&&provider.disponible&&selected&&(provider.categoria_principal_id===selected.id||ids.includes(selected.id)))}),[providers,selected])
 const rates=useMemo(()=>selectedProviders.map(item=>Number(item.tarifa_base)).filter(value=>Number.isFinite(value)&&value>0).sort((a,b)=>a-b),[selectedProviders])
 const rate=rates.length?rates[Math.floor(rates.length/2)]:null,leadProvider=selectedProviders[0]||null
 const activeService=services.find(item=>ACTIVE_STATES.includes(item.estado))||null,completedCount=services.filter(item=>item.estado==='completado').length
 const openRequest=(category?:Category|null)=>{if(category)flow.publishHugoIntent({text:`Necesito ${category.nombre}`,categoryHint:category.slug||category.id,urgent:false,description:null});flow.actions.openSearch()}
 useEffect(()=>{const unsubscribe=subscribeProviderRadar(snapshot=>setProviders(snapshot.providers));return()=>{unsubscribe()}},[])
 useEffect(()=>{if(!session)return;let alive=true;Promise.all([supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre'),supabase.from('perfiles_cliente').select('direccion,barrio,ciudad').eq('usuario_id',session.user.id).maybeSingle(),supabase.from('servicios').select('id,numero,estado,created_at,programado_para,valor_total,categoria:categorias(nombre,emoji),proveedor:usuarios!servicios_proveedor_id_fkey(nombre,karma)').eq('cliente_id',session.user.id).order('created_at',{ascending:false}).limit(12)]).then(([cats,client,serviceRows])=>{if(!alive)return;const next=(cats.data||[])as Category[];setCategories(next);const firstCore=CORE_SERVICES.map(item=>next.find(item.matches)).find(Boolean);setSelectedId(value=>value&&next.some(item=>item.id===value)?value:firstCore?.id||'');const p=(client.data||null)as ClientProfile|null;const label=[p?.ciudad,p?.barrio].filter(Boolean).join(' - ');if(label)setPlace(label);setServices((serviceRows.data||[]) as unknown as ServiceSummary[])});void refreshProviderRadar(supabase,true).catch(()=>{});return()=>{alive=false}},[session,supabase])
 useEffect(()=>{if(auth.loading||!session||!profile||!mapEl.current||mapRef.current)return;const map=new maplibregl.Map({container:mapEl.current,style:MAP_STYLE,center:FLORIPA,zoom:12.7,interactive:true,attributionControl:false});mapRef.current=map;map.once('load',()=>map.resize());const dot=document.createElement('div');dot.className='ugo-client-home-marker';const marker=new maplibregl.Marker({element:dot}).setLngLat(FLORIPA).addTo(map);userMarkerRef.current=marker;navigator.geolocation?.getCurrentPosition(pos=>{const point:[number,number]=[pos.coords.longitude,pos.coords.latitude];map.easeTo({center:point,zoom:14});marker.setLngLat(point)},()=>{},{timeout:5000,maximumAge:60000});return()=>{providerMarkersRef.current.forEach(item=>item.remove());providerMarkersRef.current=[];marker.remove();userMarkerRef.current=null;map.remove();mapRef.current=null}},[auth.loading,session,profile])
 useEffect(()=>{const map=mapRef.current;if(!map)return;providerMarkersRef.current.forEach(item=>item.remove());providerMarkersRef.current=[];for(const provider of selectedProviders){if(!Number.isFinite(provider.lat)||!Number.isFinite(provider.lng))continue;const element=document.createElement('div');element.className='ugo-studio-provider-marker';element.title=provider.nombre||'Profesional UGO';providerMarkersRef.current.push(new maplibregl.Marker({element}).setLngLat([Number(provider.lng),Number(provider.lat)]).addTo(map))}},[selectedProviders])
 if(auth.loading||!session||!profile)return null
 const latest=activeService||services[0]||null
 const openLatest=()=>{if(latest&&ACTIVE_STATES.includes(latest.estado)&&onOpenService)return onOpenService(latest.id);flow.navigate('history')}
 return <main className="ugo-client-premium-home ugo-studio-home-page" data-ugo-source="UGO-PRODUCCION/HomeScreen">
  <section className="ugo-studio-home-main">
   <div className="ugo-studio-left-column">
    <article className="ugo-studio-service-card">
     <div className="ugo-studio-title-row"><div><div className="ugo-studio-title-inline"><h1>Elegí un servicio</h1><span className="ugo-studio-live"><i/> En vivo</span></div><p>4 rubros principales para resolver rápido. El catálogo completo sigue disponible cuando necesitás otra especialidad.</p></div><div className="ugo-studio-average"><small>Disponibilidad</small><b>{selectedProviders.length>0?'Ahora':'A confirmar'}</b></div></div>
     <button type="button" className="ugo-studio-address" onClick={()=>emitUgoUiEvent(UGO_UI_EVENTS.clientLocation)}><span className="material-symbols-outlined">location_on</span><div><small>Dirección de servicio</small><strong>{place}</strong><em>Usar o actualizar mi ubicación</em></div><b>Cambiar</b></button>
     <div className="ugo-studio-services">{coreCategories.map(({item,category})=>{const active=Boolean(category&&category.id===selected?.id);const count=category?providers.filter(provider=>Boolean(provider.online&&provider.disponible&&(provider.categoria_principal_id===category.id||(Array.isArray(provider.categoria_ids)&&provider.categoria_ids.includes(category.id))))).length:0;return <button type="button" key={item.key} disabled={!category} className={active?'selected':''} onClick={()=>category&&setSelectedId(category.id)}><span className="ugo-studio-service-icon">{category?.emoji||item.emoji}</span><div><strong>{item.label}</strong><small>{category?(count>0?`${count} profesional${count===1?'':'es'} disponible${count===1?'':'s'}`:'Profesionales verificados en tu zona'):'No disponible ahora'}</small></div><span className="ugo-studio-service-price">{active&&rate!=null?money(rate):category?'→':'—'}</span></button>})}</div>
     <button type="button" className="ugo-studio-catalog" onClick={()=>openRequest(null)}><span className="material-symbols-outlined">grid_view</span><span>Ver catálogo completo de especialidades</span><span className="material-symbols-outlined">arrow_forward</span></button>
     <div className="ugo-studio-payment"><div><span className="material-symbols-outlined">payments</span><b>Forma de pago</b></div><span>Mercado Pago / Efectivo</span><small>Se confirma dentro del pedido real</small></div>
     <button type="button" className="ugo-studio-book" disabled={!selected} onClick={()=>openRequest(selected)}><span><span className="material-symbols-outlined">handyman</span>Pedir {selected?.nombre||'servicio'}</span><b>{rate!=null?`desde ${money(rate)}`:'Continuar'} →</b></button>
     <div className="ugo-studio-care"><span className="material-symbols-outlined">verified_user</span><span>Pedido conectado al UGO real · seguimiento, chat y estados por serviceId</span></div>
    </article>
   </div>
   <div className="ugo-studio-right-column">
    <article className="ugo-studio-map-card">
     <div className="ugo-studio-map-bar"><span><i/>Cobertura en tiempo real: Florianópolis</span><b>{selectedProviders.length>0?`${selectedProviders.length} disponibles`:'Buscando disponibilidad'}</b></div>
     <div className="ugo-studio-map"><div ref={mapEl}/><div className="ugo-client-home-map-shade"/><div className="ugo-client-home-map-label"><span className="material-symbols-outlined">my_location</span><div><b>Tu zona de servicio</b><small>{place}</small></div></div>{selected&&<div className="ugo-studio-map-banner"><span className="material-symbols-outlined">handyman</span><div><b>{selected.nombre}</b><small>{selectedProviders.length>0?`${selectedProviders.length} profesionales online`:'UGO verificará disponibilidad al confirmar'}</small></div></div>}</div>
     <div className="ugo-studio-provider-summary">{leadProvider?<><div className="ugo-studio-provider-identity">{leadProvider.foto_url?<img src={leadProvider.foto_url} alt={leadProvider.nombre||'Profesional UGO'}/>:<span>{leadProvider.nombre?.slice(0,1).toUpperCase()||'U'}</span>}<div><strong>{leadProvider.nombre||'Profesional UGO'}</strong><small>{leadProvider.karma?`${Number(leadProvider.karma).toFixed(1)} ★ · `:''}{leadProvider.servicios_completados||0} servicios completados</small></div></div><button type="button" onClick={()=>flow.navigate('provider',leadProvider.id)}>Ver perfil <span className="material-symbols-outlined">arrow_forward</span></button></>:<><div><strong>Profesionales reales de UGO</strong><small>La disponibilidad se consulta en vivo para la especialidad elegida.</small></div><button type="button" onClick={()=>openRequest(selected)}>Continuar <span className="material-symbols-outlined">arrow_forward</span></button></>}</div>
    </article>
    <div className="ugo-studio-trust-grid"><div><span className="material-symbols-outlined">verified</span><b>Perfiles verificados</b><small>Datos del ecosistema UGO</small></div><div><span className="material-symbols-outlined">payments</span><b>Precio visible</b><small>Confirmación antes del trabajo</small></div><div><span className="material-symbols-outlined">shield</span><b>Soporte UGO</b><small>Actividad y disputa por pedido</small></div></div>
   </div>
  </section>
  <section className="ugo-studio-account-section"><header><div><h2>Tu cuenta y actividad</h2><p>Pedidos reales, seguimiento y herramientas de tu cuenta.</p></div><button type="button" onClick={()=>flow.navigate('history')}>Ver historial completo <span className="material-symbols-outlined">chevron_right</span></button></header><div className="ugo-studio-account-grid">
   <article>{latest?<><div className="ugo-studio-card-label"><span>{ACTIVE_STATES.includes(latest.estado)?'Servicio activo':'Más reciente'}</span><small>{latest.numero?`#${latest.numero}`:''}</small></div><h3>{latest.categoria?.emoji||'🧰'} {latest.categoria?.nombre||'Servicio UGO'}</h3><p>{statusLabel(latest.estado)}{latest.proveedor?.nombre?` · ${latest.proveedor.nombre}`:''}</p><button type="button" onClick={openLatest}>{ACTIVE_STATES.includes(latest.estado)?'Abrir pedido y chat':'Ver actividad'} <span className="material-symbols-outlined">arrow_forward</span></button></>:<><div className="ugo-studio-card-label"><span>Actividad</span></div><h3>Todavía no tenés pedidos</h3><p>Tu primer servicio aparecerá acá cuando lo confirmes.</p><button type="button" onClick={()=>openRequest(selected)}>Pedir un servicio <span className="material-symbols-outlined">arrow_forward</span></button></>}</article>
   <article><div className="ugo-studio-card-label"><span>Historial</span><small>{completedCount} finalizados</small></div><h3>Todos tus pedidos en un lugar</h3><p>Activos, programados, finalizados y cancelados con sus acciones válidas.</p><button type="button" onClick={()=>flow.navigate('history')}>Abrir Actividad <span className="material-symbols-outlined">receipt_long</span></button></article>
   <article><div className="ugo-studio-card-label"><span>Mi cuenta</span></div><h3>{profile.nombre||'Cliente UGO'}</h3><p>{session.user.email||'Datos, direcciones y preferencias de la cuenta.'}</p><button type="button" onClick={()=>flow.navigate('profile')}>Gestionar cuenta <span className="material-symbols-outlined">person</span></button></article>
  </div></section>
  <section className="ugo-studio-schedule-section"><div><span className="ugo-studio-eyebrow">PLANIFICÁ TU SERVICIO</span><h2>¿Lo necesitás para más adelante?</h2><p>Iniciá el pedido y elegí la opción programada dentro del flujo real de UGO.</p></div><button type="button" onClick={()=>openRequest(selected)}><span className="material-symbols-outlined">calendar_month</span>Programar un servicio</button></section>
 </main>
}
