import React,{useEffect,useMemo,useRef,useState}from'react'
import type{SupabaseClient}from'@supabase/supabase-js'
import * as maplibregl from'maplibre-gl'
import'maplibre-gl/dist/maplibre-gl.css'
import type{Category}from'../shared'
import type{ClientHugoIntent,ClientScreen}from'./clientTypes'
import{refreshProviderRadar,subscribeProviderRadar,type ProviderRadarRow}from'./providerRadarStore'

const FLORIPA:[number,number]=[-48.5482,-27.5949]
const MAP_STYLE:maplibregl.StyleSpecification={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}
type IntentPayload={categoryId?:string;categoryName?:string;urgency:boolean;description:string}
type Props={supabase:SupabaseClient;categories:Category[];selectedCategoryId:string;requestedScreen?:ClientScreen;requestedProviderId?:string|null;hugoIntent?:ClientHugoIntent|null;onCategorySelect:(id:string)=>void;onProviderPick:(provider:ProviderRadarRow)=>void;onSearchClose?:()=>void;onIntent?:(intent:IntentPayload)=>void}
const normalize=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()
function categoryByHint(categories:Category[],hint?:string|null){if(!hint)return null;const target=normalize(hint);return categories.find(category=>{const values=[category.nombre,category.slug].filter(Boolean).map(value=>normalize(String(value)));return values.some(value=>value.includes(target)||target.includes(value))})||null}
function distanceKm(a:[number,number],b:[number,number]){const rad=(n:number)=>n*Math.PI/180,R=6371,dLat=rad(b[1]-a[1]),dLng=rad(b[0]-a[0]),lat1=rad(a[1]),lat2=rad(b[1]);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function availability(provider:ProviderRadarRow){return Boolean(provider.online&&provider.disponible)}

export function ClientStudioProviderRadar({supabase,categories,selectedCategoryId,requestedScreen,requestedProviderId,hugoIntent,onCategorySelect,onProviderPick,onSearchClose,onIntent}:Props){
 const[providers,setProviders]=useState<ProviderRadarRow[]>([]),[selectedProviderId,setSelectedProviderId]=useState<string|null>(requestedProviderId||null),[userPos,setUserPos]=useState<[number,number]>(FLORIPA),[loading,setLoading]=useState(true),[error,setError]=useState(''),[expanded,setExpanded]=useState(false)
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),markersRef=useRef<maplibregl.Marker[]>([])
 const selectedCategory=useMemo(()=>categories.find(category=>category.id===selectedCategoryId)||categoryByHint(categories,hugoIntent?.categoryHint)||null,[categories,hugoIntent?.categoryHint,selectedCategoryId])
 const matches=useMemo(()=>providers.filter(provider=>{const ids=Array.isArray(provider.categoria_ids)?provider.categoria_ids:[];return !selectedCategory||provider.categoria_principal_id===selectedCategory.id||ids.includes(selectedCategory.id)}).sort((a,b)=>Number(availability(b))-Number(availability(a))||Number(b.karma||0)-Number(a.karma||0)),[providers,selectedCategory])
 const available=useMemo(()=>matches.filter(availability),[matches]),visible=(expanded?matches:matches.slice(0,5)),selectedProvider=matches.find(item=>item.id===selectedProviderId)||null
 useEffect(()=>{const unsubscribe=subscribeProviderRadar(snapshot=>{setProviders(snapshot.providers);setLoading(!snapshot.loaded);setError(snapshot.error||'')});void refreshProviderRadar(supabase,true).catch(err=>setError(err instanceof Error?err.message:'No pudimos cargar profesionales.')).finally(()=>setLoading(false));return()=>{unsubscribe()}},[supabase])
 useEffect(()=>{if(requestedProviderId)setSelectedProviderId(requestedProviderId)},[requestedProviderId])
 useEffect(()=>{const matched=categoryByHint(categories,hugoIntent?.categoryHint);if(matched&&matched.id!==selectedCategoryId){onCategorySelect(matched.id);onIntent?.({categoryId:matched.id,categoryName:matched.nombre,urgency:Boolean(hugoIntent?.urgent),description:String(hugoIntent?.description||hugoIntent?.text||'')})}},[categories,hugoIntent,onCategorySelect,onIntent,selectedCategoryId])
 useEffect(()=>{navigator.geolocation?.getCurrentPosition(pos=>setUserPos([pos.coords.longitude,pos.coords.latitude]),()=>{},{enableHighAccuracy:true,timeout:7000,maximumAge:60000})},[])
 useEffect(()=>{if(!mapEl.current||mapRef.current)return;const map=new maplibregl.Map({container:mapEl.current,style:MAP_STYLE,center:userPos,zoom:13.5,attributionControl:false});mapRef.current=map;map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');return()=>{markersRef.current.forEach(marker=>marker.remove());markersRef.current=[];map.remove();mapRef.current=null}},[])
 useEffect(()=>{const map=mapRef.current;if(!map)return;markersRef.current.forEach(marker=>marker.remove());markersRef.current=[];const user=document.createElement('div');user.className='ugo-studio-radar-user-marker';markersRef.current.push(new maplibregl.Marker({element:user}).setLngLat(userPos).addTo(map));for(const provider of matches){if(!Number.isFinite(provider.lat)||!Number.isFinite(provider.lng))continue;const node=document.createElement('button');node.type='button';node.className=`ugo-studio-radar-provider-marker${provider.id===selectedProviderId?' selected':''}${availability(provider)?' online':''}`;node.title=provider.nombre||'Profesional UGO';node.textContent=(provider.nombre||'U').slice(0,1).toUpperCase();node.onclick=()=>setSelectedProviderId(provider.id);markersRef.current.push(new maplibregl.Marker({element:node}).setLngLat([Number(provider.lng),Number(provider.lat)]).addTo(map))}if(selectedProvider?.lat!=null&&selectedProvider?.lng!=null){map.easeTo({center:[Number(selectedProvider.lng),Number(selectedProvider.lat)],zoom:14.3,duration:500})}else map.easeTo({center:userPos,zoom:13.5,duration:400})},[matches,selectedProvider,selectedProviderId,userPos])
 const retry=()=>{setLoading(true);setError('');void refreshProviderRadar(supabase,true).catch(err=>setError(err instanceof Error?err.message:'No pudimos actualizar el radar.')).finally(()=>setLoading(false))}
 const changeCategory=(id:string)=>{onCategorySelect(id);setSelectedProviderId(null)}
 const categoryName=selectedCategory?.nombre||'profesionales'
 return <main className="ugo-studio-radar-page" data-ugo-source="UGO-PRODUCCION/SearchingScreen">
  <div className="ugo-studio-radar-ticker"><div><span className="ugo-studio-radar-pulse"><i/><i/></span><b>{loading?'Sincronizando profesionales':`Buscando ${categoryName.toLowerCase()} en tu zona`}</b><span>• Red UGO · datos en tiempo real</span></div><strong>{available.length>0?`${available.length} disponible${available.length===1?'':'s'}`:'Sin disponibilidad inmediata'}</strong></div>
  <section className="ugo-studio-radar-layout">
   <div className="ugo-studio-radar-left">
    <article className="ugo-studio-radar-card">
     <header><div><span>Radar de asignación</span><h1>Elegí un profesional</h1><p>Mostramos primero quienes están online y disponibles para la especialidad seleccionada.</p></div><div className="ugo-studio-radar-count"><b>{available.length}</b><small>online</small></div></header>
     <div className="ugo-studio-radar-categories">{categories.slice(0,8).map(category=><button type="button" key={category.id} className={selectedCategory?.id===category.id?'active':''} onClick={()=>changeCategory(category.id)}>{category.emoji||'🧰'} {category.nombre}</button>)}</div>
     {error&&<div className="ugo-studio-radar-error" role="alert"><b>No pudimos actualizar el radar</b><span>{error}</span><button type="button" onClick={retry}>Reintentar</button></div>}
     {!loading&&!error&&matches.length===0&&<div className="ugo-studio-radar-empty"><span className="material-symbols-outlined">person_search</span><h2>No hay profesionales para esta búsqueda</h2><p>No dejamos la pantalla trabada. Podés cambiar de especialidad, reintentar o volver al inicio.</p><div><button type="button" onClick={retry}>Reintentar</button><button type="button" onClick={onSearchClose}>Volver al inicio</button></div></div>}
     <div className="ugo-studio-radar-list">{loading&&Array.from({length:3}).map((_,index)=><div className="ugo-studio-radar-skeleton" key={index}/>)}{!loading&&visible.map(provider=>{const dist=provider.lat!=null&&provider.lng!=null?distanceKm(userPos,[Number(provider.lng),Number(provider.lat)]):null;const isSelected=provider.id===selectedProviderId;return <button type="button" key={provider.id} className={`${isSelected?'selected ':''}${availability(provider)?'online':'offline'}`} onClick={()=>setSelectedProviderId(provider.id)}>{provider.foto_url?<img src={provider.foto_url} alt={provider.nombre||'Profesional UGO'}/>:<span className="ugo-studio-radar-avatar">{provider.nombre?.slice(0,1).toUpperCase()||'U'}</span>}<div><div className="ugo-studio-radar-name"><strong>{provider.nombre||'Profesional UGO'}</strong>{availability(provider)&&<em>Disponible</em>}</div><small>{provider.categoria_nombre||selectedCategory?.nombre||'Especialista'}{dist!=null?` · ${dist.toFixed(1)} km`:''}</small><span>★ {Number(provider.karma||0).toFixed(1)} · {provider.servicios_completados||0} servicios</span></div><b>{Number(provider.tarifa_base||0)>0?`R$ ${Number(provider.tarifa_base).toFixed(0)}`:'Ver tarifa'}</b></button>})}</div>
     {matches.length>5&&<button type="button" className="ugo-studio-radar-more" onClick={()=>setExpanded(value=>!value)}>{expanded?'Ver menos':'Ver todos los profesionales'} <span className="material-symbols-outlined">{expanded?'expand_less':'expand_more'}</span></button>}
    </article>
    <article className="ugo-studio-radar-summary"><div><small>Servicio solicitado</small><h2>{selectedCategory?.emoji||'🧰'} {selectedCategory?.nombre||'Elegí una especialidad'}</h2><p>{selectedProvider?`${selectedProvider.nombre||'Profesional UGO'} seleccionado. Revisá sus datos antes de continuar.`:'Seleccioná un profesional disponible para continuar con el pedido real.'}</p></div><div className="ugo-studio-radar-actions"><button type="button" className="secondary" onClick={onSearchClose}>Cancelar</button><button type="button" className="primary" disabled={!selectedProvider} onClick={()=>selectedProvider&&onProviderPick(selectedProvider)}>{selectedProvider?`Elegir a ${(selectedProvider.nombre||'profesional').split(' ')[0]}`:'Elegí un profesional'} <span className="material-symbols-outlined">arrow_forward</span></button></div></article>
   </div>
   <div className="ugo-studio-radar-right"><article className="ugo-studio-radar-map-card"><header><div><i/>Radar GPS activo</div><span>Florianópolis</span></header><div className="ugo-studio-radar-map"><div ref={mapEl}/><div className="ugo-studio-radar-home-label"><span className="material-symbols-outlined">home</span><div><b>Tu ubicación</b><small>Zona del servicio</small></div></div>{selectedProvider&&<div className="ugo-studio-radar-selected"><b>{selectedProvider.nombre||'Profesional UGO'}</b><small>{availability(selectedProvider)?'Online y disponible':'No disponible ahora'} · ★ {Number(selectedProvider.karma||0).toFixed(1)}</small></div>}</div></article><div className="ugo-studio-radar-note"><span className="material-symbols-outlined">verified_user</span><div><b>Datos reales del ecosistema UGO</b><small>No usamos profesionales ficticios: disponibilidad, tarifa y ubicación provienen del backend.</small></div></div></div>
  </section>
 </main>
}
