import React,{useCallback,useEffect,useMemo,useState}from'react'
import{useRoleSession,type Category}from'../shared'
import{useClientFlow}from'./clientFlow'
import{ClientPreOrderPayment}from'./ClientPreOrderPayment'
import'./client-home-screen.css'
const norm=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
const CORE=[['limpieza','Limpieza','🧹','Hogar y oficinas'],['repar','Reparaciones','🔧','Hogar en general'],['electric','Electricidad','⚡','Instalaciones y reparaciones'],['plomer','Plomería','🚰','Instalaciones y reparaciones']] as const
const ACTIVE_STATES=['buscando','ofrecido','asignado','en_camino','llegado','en_progreso','esperando_aprobacion']
const STATE_LABEL:Record<string,string>={buscando:'Buscando profesional',ofrecido:'Buscando profesional',asignado:'Profesional asignado',en_camino:'El profesional está yendo',llegado:'El profesional llegó',en_progreso:'Trabajo en curso',esperando_aprobacion:'Esperando tu validación'}
type ActiveOrder={id:string;numero:number|null;estado:string;proveedor_id:string|null;proveedor:{nombre?:string|null}|null;categoria:{nombre?:string|null;emoji?:string|null}|null}
type PaymentMethod='pix'|'efectivo'
type Props={onOpenService?:(serviceId:string)=>void}
export function ClientHomeScreen({onOpenService}:Props){
 const flow=useClientFlow(),{supabase,session}=useRoleSession('client'),[categories,setCategories]=useState<Category[]>([]),[orders,setOrders]=useState<ActiveOrder[]>([]),[query,setQuery]=useState(''),[showAll,setShowAll]=useState(false),[paymentMethod,setPaymentMethod]=useState<PaymentMethod|null>(null),[paymentReady,setPaymentReady]=useState(false),[paymentWarning,setPaymentWarning]=useState('')
 const loadOrders=useCallback(async()=>{if(!session){setOrders([]);return}const{data}=await supabase.from('servicios').select('id,numero,estado,proveedor_id,proveedor:usuarios!servicios_proveedor_id_fkey(nombre),categoria:categorias(nombre,emoji)').eq('cliente_id',session.user.id).in('estado',ACTIVE_STATES).order('created_at',{ascending:false}).limit(3);setOrders((data||[])as unknown as ActiveOrder[])},[session,supabase])
 useEffect(()=>{if(!session)return;let alive=true;void supabase.from('categorias').select('id,slug,nombre,emoji').eq('activa',true).order('nombre').then(({data})=>{if(alive)setCategories((data||[])as Category[])});return()=>{alive=false}},[session,supabase])
 useEffect(()=>{if(!session)return;void loadOrders();const ch=supabase.channel(`client-home-orders-${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'servicios',filter:`cliente_id=eq.${session.user.id}`},()=>void loadOrders()).subscribe(status=>{if(status==='SUBSCRIBED')void loadOrders()});return()=>{void supabase.removeChannel(ch)}},[loadOrders,session,supabase])
 const cards=useMemo(()=>CORE.map(([key,label,emoji,sub])=>({key,label,emoji,sub,category:categories.find(c=>norm(`${c.slug} ${c.nombre}`).includes(key))||null})),[categories]),filtered=query.trim()?categories.filter(c=>norm(c.nombre).includes(norm(query.trim()))):[]
 const choose=(category:Category|null)=>{if(!category)return;if(!paymentReady||!paymentMethod){setPaymentWarning('Primero elegí cómo vas a pagar. UGO no busca ningún profesional hasta que la forma de pago quede guardada.');document.querySelector('.ugo-preorder-payment')?.scrollIntoView({behavior:'smooth',block:'center'});return}setPaymentWarning('');flow.publishHugoIntent({text:`Necesito ${category.nombre}`,categoryHint:category.slug||category.id,urgent:false,description:null});flow.navigate('request')}
 const openOrder=(serviceId:string)=>{if(onOpenService){onOpenService(serviceId);return}flow.navigate('history')}
 if(!session)return null
 return <main className="ugo-home-screen" aria-label="Inicio UGO Cliente"><header><button type="button" className="ugo-home-menu" onClick={()=>document.querySelector<HTMLButtonElement>('.ugo-client-global-trigger')?.click()} aria-label="Abrir menú">☰</button><strong>UG<span>O</span></strong><button type="button" className="ugo-home-place">⌖ Florianópolis⌄</button><button type="button" className="ugo-home-bell" onClick={()=>document.querySelector<HTMLButtonElement>('.ugo-notification-center.role-client .ugo-notification-trigger')?.click()} aria-label="Notificaciones">♢</button></header><section><h1>¿Qué servicio<br/>necesitás?</h1><p>Profesionales verificados, cuando los necesitás.</p>{orders.length>0&&<div className="ugo-home-active-orders" aria-label="Pedidos activos">{orders.map(order=><button type="button" key={order.id} className={order.proveedor_id?'is-assigned':'is-searching'} onClick={()=>openOrder(order.id)}><span className="ugo-home-order-icon">{order.proveedor_id?'✓':'⌁'}</span><span className="ugo-home-order-copy"><small>PEDIDO #{order.numero??String(order.id).slice(0,8)}</small><b>{STATE_LABEL[order.estado]||'Pedido activo'}</b><strong>{order.proveedor_id?(order.proveedor?.nombre||'Profesional UGO'):(order.categoria?.nombre||'UGO está buscando')}</strong><em>{order.categoria?.emoji||'🧰'} {order.categoria?.nombre||'Servicio'} · Ver pedido →</em></span></button>)}</div>}<ClientPreOrderPayment onPreferenceChange={(method,ready)=>{setPaymentMethod(method);setPaymentReady(ready);if(method)setPaymentWarning('')}}/>{paymentWarning&&<p className="ugo-preorder-payment-warning" role="alert">{paymentWarning}</p>}<label className="ugo-home-search">⌕<input value={query} onChange={e=>{setQuery(e.target.value);setShowAll(false)}} placeholder="Buscar servicios…"/></label>{filtered.length>0&&<div className="ugo-home-results">{filtered.slice(0,8).map(c=><button type="button" key={c.id} onClick={()=>choose(c)}>{c.emoji||'🧰'} {c.nombre}</button>)}</div>}<div className="ugo-home-categories">{cards.map(({key,label,emoji,sub,category})=><button type="button" key={key} disabled={!category} onClick={()=>choose(category)}><span>{category?.emoji||emoji}</span><b>{label}</b><small>{sub}</small></button>)}</div><button type="button" className="ugo-home-all" onClick={()=>setShowAll(v=>!v)}>{showAll?'Ocultar categorías':'Ver todas las categorías'} <span>{showAll?'↑':'→'}</span></button>{showAll&&<div className="ugo-home-results ugo-home-all-results" aria-label="Todas las categorías">{categories.map(c=><button type="button" key={c.id} onClick={()=>choose(c)}>{c.emoji||'🧰'} {c.nombre}</button>)}</div>}</section></main>
}
export default ClientHomeScreen
