import React,{useCallback,useEffect,useState}from'react'
import{useRoleSession}from'../shared'
import{useClientFlow}from'./clientFlow'
import{UGO_UI_EVENTS}from'../uiEvents'
import'../../features/client/profile/clientProfilePanel.css'

type Detail={telefono?:string|null;direccion?:string|null;barrio?:string|null;ciudad?:string|null;idioma_preferido?:string|null;contacto_preferido?:string|null}
type PaymentMethod='efectivo'|'pix'
type SavedPlace={id:string;etiqueta:string;direccion:string;complemento:string|null;barrio:string|null;ciudad:string|null;es_predeterminada:boolean}
const empty:Detail={telefono:'',direccion:'',barrio:'',ciudad:'',idioma_preferido:'pt-BR',contacto_preferido:'WhatsApp'}

export function ClientProfilePanel(){
 const flow=useClientFlow(),auth=useRoleSession('client'),{supabase,session,profile}=auth
 const[detail,setDetail]=useState<Detail>(empty),[draft,setDraft]=useState<Detail>(empty),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[paymentMethod,setPaymentMethod]=useState<PaymentMethod>('efectivo'),[paymentSaving,setPaymentSaving]=useState(false),[places,setPlaces]=useState<SavedPlace[]>([]),[placeDraft,setPlaceDraft]=useState({etiqueta:'',direccion:'',complemento:''}),[placeBusy,setPlaceBusy]=useState(false)
 const load=useCallback(async()=>{if(!session)return;setLoading(true);setMessage('');const{data,error}=await supabase.from('perfiles_cliente').select('telefono,direccion,barrio,ciudad,idioma_preferido,contacto_preferido').eq('usuario_id',session.user.id).maybeSingle();if(error){setMessage('No pudimos cargar el perfil. Reintentá sin perder tu cuenta.');setLoading(false);return}const next={...empty,...((data||{})as Detail)};setDetail(next);setDraft(next);setLoading(false)},[session,supabase])
 const loadPayment=useCallback(async()=>{if(!session)return;const{data}=await supabase.from('preferencias_pago_cliente').select('metodo').eq('usuario_id',session.user.id).maybeSingle();setPaymentMethod(data?.metodo==='pix'?'pix':'efectivo')},[session,supabase])
 const loadPlaces=useCallback(async()=>{if(!session)return;const{data,error}=await (supabase as any).from('direcciones_cliente').select('id,etiqueta,direccion,complemento,barrio,ciudad,es_predeterminada').eq('usuario_id',session.user.id).order('es_predeterminada',{ascending:false}).order('created_at',{ascending:true});if(error){console.warn('UGO places unavailable',error);return}setPlaces((data||[]) as SavedPlace[])},[session,supabase])
 const addPlace=async()=>{if(!session||placeBusy)return;const etiqueta=placeDraft.etiqueta.trim(),direccion=placeDraft.direccion.trim();if(!etiqueta||direccion.length<5){setMessage('Poné un nombre y una dirección válida para el lugar.');return}setPlaceBusy(true);setMessage('');const{error}=await (supabase as any).from('direcciones_cliente').insert({usuario_id:session.user.id,etiqueta,direccion,complemento:placeDraft.complemento.trim()||null,es_predeterminada:places.length===0});setPlaceBusy(false);if(error){setMessage(error.message||'No pudimos guardar el lugar.');return}setPlaceDraft({etiqueta:'',direccion:'',complemento:''});setMessage('Lugar guardado.');await loadPlaces()}
 const makeDefault=async(id:string)=>{if(!session||placeBusy)return;setPlaceBusy(true);setMessage('');const{error}=await (supabase as any).rpc('set_direccion_cliente_predeterminada',{p_direccion_id:id});setPlaceBusy(false);if(error){setMessage(error.message||'No pudimos cambiar el lugar principal.');return}await loadPlaces()}
 const removePlace=async(id:string)=>{if(!session||placeBusy)return;if(!window.confirm('¿Eliminar este lugar guardado?'))return;setPlaceBusy(true);const{error}=await (supabase as any).from('direcciones_cliente').delete().eq('id',id).eq('usuario_id',session.user.id);setPlaceBusy(false);if(error){setMessage(error.message||'No pudimos eliminar el lugar.');return}await loadPlaces()}
 const orderAtPlace=(place:SavedPlace)=>{if(!session)return;try{const key='ugo:guided-request-draft:'+session.user.id,previous=JSON.parse(sessionStorage.getItem(key)||'{}');sessionStorage.setItem(key,JSON.stringify({...previous,address:place.direccion,addressLabel:place.etiqueta,complement:place.complemento||'',zone:place.barrio||place.ciudad||''}))}catch{}flow.navigate('request')}
 useEffect(()=>{void load()},[load])
 useEffect(()=>{void loadPayment()},[loadPayment])
 useEffect(()=>{void loadPlaces()},[loadPlaces])
 useEffect(()=>{const reveal=(id:string)=>{const node=document.getElementById(id);if(node instanceof HTMLDetailsElement)node.open=true;window.setTimeout(()=>node?.scrollIntoView({behavior:'smooth',block:'center'}),0)},payment=()=>reveal('ugo-client-profile-payment-section'),addresses=()=>reveal('ugo-client-profile-addresses-section');window.addEventListener(UGO_UI_EVENTS.clientProfilePayment,payment);window.addEventListener(UGO_UI_EVENTS.clientProfileAddresses,addresses);return()=>{window.removeEventListener(UGO_UI_EVENTS.clientProfilePayment,payment);window.removeEventListener(UGO_UI_EVENTS.clientProfileAddresses,addresses)}},[])
 if(!session)return null
 const address=[detail.direccion,detail.barrio,detail.ciudad].filter(Boolean).join(', ')||'Sin dirección cargada'
 const save=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setMessage('');const payload={telefono:draft.telefono?.trim()||null,direccion:draft.direccion?.trim()||null,barrio:draft.barrio?.trim()||null,ciudad:draft.ciudad?.trim()||null,idioma_preferido:draft.idioma_preferido||'pt-BR',contacto_preferido:draft.contacto_preferido||'WhatsApp'};const{error}=await(supabase as any).from('perfiles_cliente').upsert({usuario_id:session.user.id,...payload},{onConflict:'usuario_id'});setSaving(false);if(error)return setMessage(error.message||'No pudimos guardar el perfil.');setMessage('Perfil actualizado.');setEditing(false);await load()}
 const choosePayment=async(next:PaymentMethod)=>{if(paymentSaving||next===paymentMethod)return;const previous=paymentMethod;setPaymentMethod(next);setPaymentSaving(true);setMessage('');const{error}=await supabase.rpc('set_preorder_payment_preference',{p_metodo:next});setPaymentSaving(false);if(error){setPaymentMethod(previous);setMessage('No pudimos guardar la preferencia de pago. Podés seguir pidiendo servicios; Efectivo seguirá disponible por defecto.');return}setMessage(next==='pix'?'PIX quedó como preferencia para tus próximos pedidos.':'Efectivo quedó como forma de pago predeterminada.')}
 return <div className="ugo-client-screen-overlay" role="dialog" aria-modal="true" aria-label="Perfil del cliente"><section className="ugo-client-profile-panel">
  <header><button type="button" onClick={()=>flow.navigate('home')} aria-label="Volver">←</button><div><small>U.GO · CLIENTE</small><h2>Tu perfil</h2></div><span>{profile?.nombre?.slice(0,1).toUpperCase()||'U'}</span></header>
  {loading?<div className="ugo-client-profile-loading">Cargando perfil…</div>:<div className="ugo-client-profile-body">
   <article className="ugo-client-profile-identity"><span>{profile?.nombre?.slice(0,1).toUpperCase()||'U'}</span><div><strong>{profile?.nombre||'Cliente UGO'}</strong><small>{session.user.email||'Sin email'}</small></div><button type="button" onClick={()=>setEditing(value=>!value)}>{editing?'Cerrar':'Editar'}</button></article>
   {message&&<div className="ugo-client-profile-message" role="status">{message}</div>}
   {editing&&<form className="ugo-client-profile-form" onSubmit={save}><label>Teléfono<input value={draft.telefono||''} onChange={event=>setDraft(value=>({...value,telefono:event.target.value}))} inputMode="tel" placeholder="Tu teléfono"/></label><label>Dirección<input value={draft.direccion||''} onChange={event=>setDraft(value=>({...value,direccion:event.target.value}))} placeholder="Calle y número"/></label><div><label>Barrio<input value={draft.barrio||''} onChange={event=>setDraft(value=>({...value,barrio:event.target.value}))}/></label><label>Ciudad<input value={draft.ciudad||''} onChange={event=>setDraft(value=>({...value,ciudad:event.target.value}))}/></label></div><div><label>Idioma<select value={draft.idioma_preferido||'pt-BR'} onChange={event=>setDraft(value=>({...value,idioma_preferido:event.target.value}))}><option value="pt-BR">Português</option><option value="es">Español</option></select></label><label>Contacto<select value={draft.contacto_preferido||'WhatsApp'} onChange={event=>setDraft(value=>({...value,contacto_preferido:event.target.value}))}><option>WhatsApp</option><option>Teléfono</option><option>Email</option></select></label></div><button className="ugo-client-profile-primary" disabled={saving}>{saving?'Guardando…':'Guardar cambios'}</button></form>}
   <div className="ugo-client-profile-shortcuts"><button type="button" onClick={()=>flow.navigate('history')}><span>◷</span><strong>Actividad</strong><small>Pedidos, trabajos y pagos</small></button><button type="button" onClick={()=>flow.navigate('home')}><span>⌁</span><strong>Nuevo pedido</strong><small>Contale a Hugo qué necesitás</small></button></div>
   <div className="ugo-client-profile-sections"><details id="ugo-client-profile-payment-section" open><summary><span>💵</span><div><strong>Forma de pago</strong><small>{paymentMethod==='pix'?'PIX':'Efectivo'} · predeterminado</small></div></summary><div className="ugo-client-profile-payment" role="group" aria-label="Forma de pago predeterminada"><button type="button" className={paymentMethod==='efectivo'?'selected':''} disabled={paymentSaving} onClick={()=>void choosePayment('efectivo')}><b>💵 Efectivo</b><small>Predeterminado</small></button><button type="button" className={paymentMethod==='pix'?'selected':''} disabled={paymentSaving} onClick={()=>void choosePayment('pix')}><b>▦ PIX</b><small>Pago digital</small></button></div><p>Esta preferencia aparece preseleccionada al confirmar. Nunca bloquea que empieces a solicitar un servicio.</p></details><details id="ugo-client-profile-addresses-section" open><summary><span>⌖</span><div><strong>Lugares</strong><small>{places.length?places.length+' guardado'+(places.length===1?'':'s'):address}</small></div></summary><div className="ugo-client-places">{places.map(place=><article key={place.id}><div><strong>{place.etiqueta}{place.es_predeterminada&&<em>Principal</em>}</strong><span>{place.direccion}{place.complemento?' · '+place.complemento:''}</span></div><div><button type="button" onClick={()=>orderAtPlace(place)}>Pedir acá</button>{!place.es_predeterminada&&<button type="button" disabled={placeBusy} onClick={()=>void makeDefault(place.id)}>Hacer principal</button>}<button type="button" className="danger" disabled={placeBusy} onClick={()=>void removePlace(place.id)}>Eliminar</button></div></article>)}<div className="ugo-client-place-new"><input value={placeDraft.etiqueta} onChange={e=>setPlaceDraft(value=>({...value,etiqueta:e.target.value}))} placeholder="Nombre: Casa, Oficina, Mamá…"/><input value={placeDraft.direccion} onChange={e=>setPlaceDraft(value=>({...value,direccion:e.target.value}))} placeholder="Dirección"/><input value={placeDraft.complemento} onChange={e=>setPlaceDraft(value=>({...value,complemento:e.target.value}))} placeholder="Complemento (opcional)"/><button type="button" disabled={placeBusy} onClick={()=>void addPlace()}>{placeBusy?'Guardando…':'+ Guardar lugar'}</button></div></div></details><details><summary><span>●</span><div><strong>Contacto y notificaciones</strong><small>{detail.contacto_preferido||'WhatsApp'} · {detail.telefono||'sin teléfono'}</small></div></summary><p>Las novedades del servicio también aparecen dentro de UGO. Mantené actualizado el medio de contacto.</p></details><details><summary><span>?</span><div><strong>Ayuda y seguridad</strong><small>Soporte, disputas y privacidad</small></div></summary><p>Si un trabajo tiene un problema, abrí la actividad o la disputa del servicio. UGO nunca te pide la contraseña por mensaje.</p></details></div>
   <button type="button" className="ugo-client-profile-signout" onClick={()=>void auth.signOut()}>Cerrar sesión</button>
  </div>}
 </section></div>
}
