import React,{useCallback,useEffect,useMemo,useRef,useState}from'react'
import type{Service}from'../shared'
import{STATUS_LABELS}from'../shared'
import{getRoleSupabase}from'../../lib/roleSupabase'
import{getDispatchProvider}from'../../lib/dispatch/provider'
import{resolveClientSavedAddress}from'../hugoDefaultAddress'
import{loadVoiceAvailability,normalizeVoiceText,resolveVoiceCategory,voiceAvailabilityText,type VoiceAvailability,type VoiceCategory,type VoiceProvider}from'../voiceCatalog'
import{UGO_UI_EVENTS}from'../uiEvents'
import type{ClientActionHandlers,ClientHugoIntent}from'./clientTypes'
import'../voice.css'

type PaymentStatus='none'|'cash'|'pending'|'confirmed'
type Props={accessToken?:string;service?:Service|null;availableOffers?:number;paymentStatus?:PaymentStatus;clientActions?:ClientActionHandlers;onIntent?:(intent:Omit<ClientHugoIntent,'id'>)=>void}
type VoiceState='idle'|'connecting'|'ready'|'hearing'|'speaking'|'error'
type Locale='es-AR'|'pt-BR'
type Draft={category:VoiceCategory|null;description:string;address:string;when:'ahora'|'hoy'|'programar'|null;scheduleAt:string;whenLabel:string;urgent:boolean;preferredProviderId?:string|null;preferredProviderName?:string|null;serviceId?:string|null}
type NativeBridge={startListening:()=>void;stopListening:()=>void;isAvailable?:()=>boolean}
type GeminiTts={audio_base64?:string;mime_type?:string;sample_rate?:number;model?:string;voice?:string;error?:string;hugo_mensaje?:string}
type GeminiChat={hugo_mensaje?:string;model?:string}

const LABELS:Record<VoiceState,string>={idle:'Toca para hablar',connecting:'Pensando...',ready:'Te escucho',hearing:'Escuchando...',speaking:'Hablando...',error:'Voz no disponible'}
const CANCELLABLE=['buscando','ofrecido','asignado','en_camino','llegado']

function norm(v:string){return normalizeVoiceText(v)}
function localeFrom(text:string,current:Locale){const m=norm(text),pt=(m.match(/\b(quero|preciso|voce|servico|agora|nao|sim|endereco)\b/g)||[]).length,es=(m.match(/\b(quiero|necesito|vos|servicio|ahora|no|si|direccion)\b/g)||[]).length;return pt>=2&&pt>es?'pt-BR':es>=2&&es>pt?'es-AR':current}
function requestIntent(text:string){return/\b(necesito|quiero un|quiero una|quiero pedir|quiero contratar|preciso|quero um|quero uma|quero pedir|quero contratar|me hace falta|necesitaria)\b/.test(norm(text))}
function searchIntent(text:string){return/\b(busca|buscame|buscar|mostrame|mostre|encontra|encontre|quienes hay|quem tem|disponibles|disponiveis|recomendame|recomenda|recomendacion|recomendacao)\b/.test(norm(text))}
function urgency(text:string){return/\b(urgente|urgencia|ahora mismo|ya mismo|agora|emergencia)\b/.test(norm(text))}
function affirmative(text:string){const m=norm(text);if(/\b(no|nao)\b/.test(m))return false;return/^(si|sim|dale|confirmo|confirmar|confirma|hacelo|faca|pode fazer|adelante|ok|okay|de acuerdo|de acordo|correcto|correto|vamos|esta bien)\b/.test(m)||/\b(confirmar|confirmo|confirma|confirmalo|confirmar pedido|confirmar el pedido|pode confirmar|confirma o pedido)\b/.test(m)}
function retryIntent(text:string){return/\b(reintenta|reintentar|intenta de nuevo|proba de nuevo|probar de nuevo|tenta de novo|tentar de novo|continuar busqueda|seguir buscando)\b/.test(norm(text))}
function negative(text:string){return/^(no|nao|no gracias|nao obrigado|dejalo|deja|deixe|mejor no|melhor nao)\b/.test(norm(text))}
function wantsGps(text:string){return/\b(mi ubicacion actual|donde estoy|usar mi ubicacion|minha localizacao atual|onde estou|usar minha localizacao)\b/.test(norm(text))}
function savedLabel(text:string):'Casa'|'Trabajo'|null{const m=norm(text);if(/\b(mi casa|en casa|casa|hogar|minha casa|em casa)\b/.test(m))return'Casa';if(/\b(mi trabajo|trabajo|oficina|meu trabalho|trabalho|escritorio)\b/.test(m))return'Trabajo';return null}
function parseDescription(text:string){const raw=text.trim(),m=norm(raw);if(raw.length<8)return'';const issue=raw.match(/(?:rompi[oó]|rompieron|quebr[oó]|quem[oó])\b[^,.!?]*|(?:no|nao|não)\s+(?:funciona|anda|liga)\b[^,.!?]*|(?:pierde agua|gotea|vaza)\b[^,.!?]*|(?:cortar|instalar|limpiar|limpar|pintar|arreglar|reparar|cambiar|trocar|montar|consertar|revisar)\b[^,.!?]*/i);if(issue?.[0])return issue[0].trim();return/^(necesito|quiero|preciso|quero)\b/.test(m)&&m.split(' ').length<6?'':raw}
function parseWhen(text:string){const m=norm(text),now=new Date(),pad=(n:number)=>String(n).padStart(2,'0');if(/\b(ahora|ya mismo|agora)\b/.test(m))return{when:'ahora'as const,scheduleAt:'',whenLabel:'Ahora',urgent:true};if(/\b(hoy|hoje)\b/.test(m))return{when:'hoy'as const,scheduleAt:'',whenLabel:'Hoy',urgent:false};if(/\b(manana|amanha)\b/.test(m)){const d=new Date(now);d.setDate(d.getDate()+1);let hour=/\btarde\b/.test(m)?15:/\bnoche|noite\b/.test(m)?19:10;const clock=m.match(/(?:a las|a la|as|às)\s*(\d{1,2})/);if(clock)hour=Math.min(23,Number(clock[1]));d.setHours(hour,0,0,0);return{when:'programar'as const,scheduleAt:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(hour)}:00`,whenLabel:`Mañana ${pad(hour)}:00`,urgent:false}}return null}
function nextMissing(draft:Draft){if(!draft.category)return'category';if(!draft.description)return'description';if(!draft.address)return'address';if(!draft.when)return'when';return'confirm'}
function compact(value:string){return norm(value).replace(/[^a-z0-9]/g,'')}
function editDistance(a:string,b:string){const rows=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=rows[0];rows[0]=i;for(let j=1;j<=b.length;j++){const hold=rows[j],cost=a[i-1]===b[j-1]?0:1;rows[j]=Math.min(rows[j]+1,rows[j-1]+1,prev+cost);prev=hold}}return rows[b.length]}
function similarity(a:string,b:string){if(!a||!b)return 0;if(a===b)return 1;return 1-editDistance(a,b)/Math.max(a.length,b.length)}
function choiceFragment(text:string){let value=norm(text);const marker=value.match(/\b(elijo|elegi|elegir|quiero a|contrata|contratar|escolho|escolhi|quero o|quero a|contrate)\b/);if(marker?.index!=null)value=value.slice(marker.index+marker[0].length);value=value.replace(/^(a|al|el|la|o)\s+/,'');return value.split(/\b(por ejemplo|porque|que ya|ya me|confirmar|confirmo|confirma|si|sim|dale|por favor)\b/)[0].trim()}
function chooseProvider(text:string,current:VoiceAvailability|null){if(!current)return null;const m=norm(text),choose=/\b(elijo|elegi|elegir|quiero a|contrata|contratar|escolho|escolhi|quero o|quero a|contrate)\b/.test(m);const exact=current.providers.find(provider=>{const full=norm(provider.nombre||''),first=full.split(' ')[0]||'';return full&&(m===full||m.includes(full)||(first.length>=4&&m===first))});if(exact)return exact;if(!choose)return null;const fragment=choiceFragment(text),target=compact(fragment);let best:VoiceProvider|null=null,bestScore=0;for(const provider of current.providers){const full=norm(provider.nombre||''),fullCompact=compact(full);if(!fullCompact)continue;let score=similarity(target,fullCompact);for(const token of full.split(/\s+/)){const cleanToken=compact(token);if(cleanToken.length>=4&&target.includes(cleanToken))score=Math.max(score,.92)}const withoutOfficial=fullCompact.replace(/oficial$/,'');if(withoutOfficial!==fullCompact)score=Math.max(score,similarity(target.replace(/oficial$/,''),withoutOfficial));if(score>bestScore){best=provider;bestScore=score}}return bestScore>=.7?best:null}
async function reverseGeocode(lat:number,lng:number){try{const r=await fetch(`https://photon.komoot.io/reverse?lat=${lat}&lon=${lng}`),data:any=await r.json(),p=data?.features?.[0]?.properties||{};return[p.name,p.street,p.district,p.city,p.state].filter(Boolean).join(', ')||null}catch{return null}}

export function ClientVoiceHugoDock({accessToken,service,availableOffers=0,paymentStatus='none',clientActions,onIntent}:Props){
 const[state,setState]=useState<VoiceState>('idle'),[error,setError]=useState(''),[userTranscript,setUserTranscript]=useState(''),[assistantTranscript,setAssistantTranscript]=useState(''),[typed,setTyped]=useState('')
 const locale=useRef<Locale>('es-AR'),draft=useRef<Draft|null>(null),availability=useRef<VoiceAvailability|null>(null),recognition=useRef<any>(null),running=useRef(false),busy=useRef(false),native=useRef(false),inputRef=useRef<HTMLInputElement|null>(null),audioContextRef=useRef<AudioContext|null>(null),audioSourceRef=useRef<AudioBufferSourceNode|null>(null)
 const text=useMemo(()=>{if(!service)return'Decime qué necesitás. Yo completo el pedido con vos.';if(service.estado==='buscando')return'Estoy buscando profesionales disponibles para tu pedido.';if(service.estado==='ofrecido')return`Ya avisé a ${availableOffers||'varios'} profesionales.`;if(service.estado==='asignado'){if(paymentStatus==='cash')return'Elegiste efectivo. El profesional puede iniciar el viaje.';if(paymentStatus==='confirmed')return'El pago está confirmado. El profesional puede iniciar el viaje.';return'Ya encontré un profesional.'}if(service.estado==='en_camino')return'El profesional está en camino.';if(service.estado==='llegado')return'El profesional ya llegó.';if(service.estado==='en_progreso')return'El trabajo está en curso.';if(service.estado==='esperando_aprobacion')return'El trabajo terminó. Revisalo antes de aprobar.';return'UGO está siguiendo tu servicio.'},[availableOffers,paymentStatus,service])

 const pauseRecognition=useCallback(()=>{if(native.current){try{(window as any).UGOVoiceBridge?.stopListening?.()}catch{}}else{try{recognition.current?.abort?.()}catch{}}},[])
 const resumeRecognition=useCallback(()=>{if(!running.current)return;window.setTimeout(()=>{if(!running.current)return;if(native.current){try{(window as any).UGOVoiceBridge?.startListening?.()}catch{}}else if(recognition.current){try{recognition.current.start()}catch{}}},220)},[])
 const playGeminiPcm=useCallback(async(base64:string,sampleRate=24000)=>{const binary=window.atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const even=bytes.byteLength-bytes.byteLength%2,AudioContextCtor=window.AudioContext||(window as any).webkitAudioContext;if(!AudioContextCtor)throw new Error('AudioContext no disponible');const ctx=new AudioContextCtor(),buffer=ctx.createBuffer(1,even/2,sampleRate),channel=buffer.getChannelData(0),view=new DataView(bytes.buffer,bytes.byteOffset,even);for(let i=0;i<channel.length;i++)channel[i]=view.getInt16(i*2,true)/32768;const source=ctx.createBufferSource();source.buffer=buffer;source.connect(ctx.destination);audioContextRef.current=ctx;audioSourceRef.current=source;await ctx.resume();await new Promise<void>(resolve=>{source.onended=()=>resolve();source.start()});audioSourceRef.current=null;audioContextRef.current=null;await ctx.close()},[])
 const speak=useCallback(async(reply:string)=>{setAssistantTranscript(reply);setError('');pauseRecognition();setState('connecting');let spoken=false,lastError='';for(let attempt=0;attempt<2&&!spoken;attempt++){try{const response=await fetch('/api/hugo/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tts:true,text:reply,locale:locale.current})}),data=(await response.json().catch(()=>null))as GeminiTts|null;if(!response.ok||!data?.audio_base64)throw new Error(data?.error||data?.hugo_mensaje||'Gemini TTS no respondió');setState('speaking');await playGeminiPcm(data.audio_base64,Number(data.sample_rate||24000));spoken=true}catch(ttsError){lastError=ttsError instanceof Error?ttsError.message:'Gemini TTS no disponible';if(attempt===0)await new Promise(resolve=>window.setTimeout(resolve,350))}}if(!spoken){console.warn('Gemini TTS no disponible',lastError);setError('La voz de Gemini no respondió. Dejé la respuesta escrita para que el pedido no se trabe.')}busy.current=false;if(running.current){setState('ready');resumeRecognition()}else setState('idle')},[pauseRecognition,playGeminiPcm,resumeRecognition])
 const publish=useCallback((source:string,category:VoiceCategory|null,description:string|null)=>{if(category)onIntent?.({text:source,categoryHint:category.slug||category.nombre||'',urgent:urgency(source),description})},[onIntent])
 const geminiProviderLead=useCallback(async(source:string,result:VoiceAvailability)=>{const fallback=voiceAvailabilityText(result,locale.current);try{const context=JSON.stringify({categoria:result.category.nombre||result.category.slug,profesionales_reales:result.providers,resumen_operativo:fallback});const response=await fetch('/api/hugo/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'client_voice',message:`El usuario dijo: ${source}. Recomendale brevemente hasta dos opciones usando exclusivamente los profesionales reales del contexto. Priorizá disponibilidad, reputación, experiencia y trabajos realizados cuando esos datos existan.`,context})}),data=(await response.json().catch(()=>null))as GeminiChat|null;return response.ok&&data?.hugo_mensaje?data.hugo_mensaje:fallback}catch{return fallback}},[])
 const askNext=useCallback(async(source:string,current:Draft,lead='')=>{const pt=locale.current==='pt-BR',prefix=lead?`${lead} `:'',missing=nextMissing(current);if(missing==='category')return speak(prefix+(pt?'Que tipo de profissional você precisa?':'¿Qué tipo de profesional necesitás?'));if(missing==='description')return speak(prefix+(pt?'O que precisa ser feito?':'¿Qué hay que hacer?'));if(missing==='address')return speak(prefix+(pt?'Qual é o endereço?':'¿Cuál es la dirección?'));if(missing==='when')return speak(prefix+(pt?'Quando você precisa? Agora, hoje ou outro momento?':'¿Cuándo lo necesitás? ¿Ahora, hoy o para otro momento?'));const provider=current.preferredProviderName?(pt?` com ${current.preferredProviderName}`:` con ${current.preferredProviderName}`):'';return speak(prefix+(pt?`Então ficou: ${current.category?.nombre}${provider}, ${current.description}, em ${current.address}, ${current.whenLabel}. Confirmo o pedido?`:`Entonces queda: ${current.category?.nombre}${provider}, ${current.description}, en ${current.address}, ${current.whenLabel}. ¿Confirmo el pedido?`))},[speak])
 const createOrder=useCallback(async(current:Draft)=>{const sb=getRoleSupabase('client'),{data:sess}=await sb.auth.getSession(),user=sess.session?.user;if(!user||!current.category)throw new Error('Sesión o categoría no disponible');let serviceId=String(current.serviceId||'');if(!serviceId){const metadata:any={source:'hugo-conversational',voice:true,demo:false,requested_when:current.when,scheduled_at:current.when==='programar'?current.scheduleAt:null,preferred_provider_id:current.preferredProviderId||null};const{data,error:insertError}=await sb.from('servicios').insert({cliente_id:user.id,categoria_id:current.category.id,estado:'buscando',descripcion:current.description,direccion_cliente:current.address,tarifa:null,urgencia:current.urgent,metadata}).select('id').single();if(insertError)throw insertError;if(!data?.id)throw new Error('No se pudo crear el pedido');serviceId=String(data.id);current.serviceId=serviceId}const dispatch=getDispatchProvider();try{const persisted=await dispatch.getStatus(serviceId).catch(()=>null);if(persisted?.state==='offering'||persisted?.state==='matched')return serviceId;await dispatch.start({serviceId,category:current.category.slug||current.category.id,preferredProviderId:current.preferredProviderId||null});return serviceId}catch(dispatchError){try{const persisted=await dispatch.getStatus(serviceId);if(persisted.state==='offering'||persisted.state==='matched')return serviceId}catch{}throw new Error(`El pedido ${serviceId} quedó guardado, pero no pude iniciar la búsqueda. Decime “reintentar búsqueda” y sigo desde el mismo pedido.`)}},[])
 const finishOrder=useCallback(async(current:Draft,pt:boolean)=>{try{const id=await createOrder(current),name=current.preferredProviderName;draft.current=null;availability.current=null;await speak(pt?`Pronto. Pedido ${id} criado${name?` para ${name}`:''}. A busca começou.`:`Listo. Pedido ${id} creado${name?` para ${name}`:''}. La búsqueda empezó.`)}catch(e:any){const message=String(e?.message||'error');await speak(pt?`Não consegui completar a busca: ${message}`:`No pude completar la búsqueda: ${message}`)}},[createOrder,speak])
 const hydrate=useCallback(async(current:Draft,source:string)=>{if(!current.category)current.category=await resolveVoiceCategory(source);if(!current.description)current.description=parseDescription(source);if(!current.address&&!wantsGps(source)){const saved=await resolveClientSavedAddress(savedLabel(source));if(saved)current.address=saved.address}if(!current.when){const when=parseWhen(source);if(when){current.when=when.when;current.scheduleAt=when.scheduleAt;current.whenLabel=when.whenLabel;current.urgent=current.urgent||when.urgent}}},[])

 const handleDraft=useCallback(async(source:string)=>{const current=draft.current;if(!current)return false;const pt=locale.current==='pt-BR',missing=nextMissing(current),picked=chooseProvider(source,availability.current);if(picked){current.preferredProviderId=picked.id;current.preferredProviderName=picked.nombre;if(missing==='confirm'&&affirmative(source)){await finishOrder(current,pt);return true}await askNext(source,current,pt?`Perfeito, escolhi ${picked.nombre}.`:`Perfecto, elegí a ${picked.nombre}.`);return true}if(current.serviceId&&retryIntent(source)){await finishOrder(current,pt);return true}if(missing==='confirm'){if(negative(source)){draft.current=null;availability.current=null;await speak(pt?'Perfeito, não confirmo o pedido.':'Perfecto, no confirmo el pedido.');return true}if(!affirmative(source)){await speak(pt?'Preciso de uma confirmação clara. Pode dizer “sim, confirmar pedido”.':'Necesito una confirmación clara. Podés decir “sí, confirmar pedido”.');return true}await finishOrder(current,pt);return true}if(missing==='category'){current.category=await resolveVoiceCategory(source);if(!current.category){await askNext(source,current);return true}await hydrate(current,source);availability.current=await loadVoiceAvailability(current.category);publish(source,current.category,current.description||null);const lead=await geminiProviderLead(source,availability.current);await askNext(source,current,lead);return true}if(missing==='description'){current.description=parseDescription(source)||source.trim();if(current.description.length<8){await speak(pt?'Me conte um pouco mais.':'Contame un poco más.');return true}await hydrate(current,source);publish(source,current.category,current.description);await askNext(source,current);return true}if(missing==='address'){if(wantsGps(source)){if(!navigator.geolocation){await speak(pt?'Me diga o endereço.':'Decime la dirección.');return true}await new Promise<void>(resolve=>navigator.geolocation.getCurrentPosition(async pos=>{current.address=await reverseGeocode(pos.coords.latitude,pos.coords.longitude)||`GPS ${pos.coords.latitude.toFixed(6)}, ${pos.coords.longitude.toFixed(6)}`;resolve()},()=>resolve(),{enableHighAccuracy:true,timeout:10000}));if(!current.address){await speak(pt?'Não consegui usar a localização. Me diga o endereço.':'No pude usar la ubicación. Decime la dirección.');return true}await askNext(source,current);return true}const saved=await resolveClientSavedAddress(savedLabel(source));current.address=saved?.address||source.trim();await askNext(source,current);return true}if(missing==='when'){const when=parseWhen(source);if(!when){await speak(pt?'Me diga quando: agora, hoje ou amanhã.':'Decime cuándo: ahora, hoy o mañana.');return true}current.when=when.when;current.scheduleAt=when.scheduleAt;current.whenLabel=when.whenLabel;current.urgent=current.urgent||when.urgent;await askNext(source,current);return true}return false},[askNext,finishOrder,geminiProviderLead,hydrate,publish,speak])
 const handleText=useCallback(async(source:string)=>{const clean=source.trim();if(!clean)return;setUserTranscript(clean);busy.current=true;setState('connecting');setError('');locale.current=localeFrom(clean,locale.current);try{if(draft.current&&await handleDraft(clean))return;if(requestIntent(clean)){const current:Draft={category:null,description:'',address:'',when:null,scheduleAt:'',whenLabel:'',urgent:urgency(clean),preferredProviderId:null,preferredProviderName:null,serviceId:null};await hydrate(current,clean);draft.current=current;let lead='';if(current.category){availability.current=await loadVoiceAvailability(current.category);publish(clean,current.category,current.description||null);lead=await geminiProviderLead(clean,availability.current)}await askNext(clean,current,lead);return}if(searchIntent(clean)){const category=await resolveVoiceCategory(clean);if(category){const current:Draft={category,description:'',address:'',when:null,scheduleAt:'',whenLabel:'',urgent:urgency(clean),preferredProviderId:null,preferredProviderName:null,serviceId:null};await hydrate(current,clean);draft.current=current;availability.current=await loadVoiceAvailability(category);publish(clean,category,current.description||null);const lead=await geminiProviderLead(clean,availability.current);await askNext(clean,current,lead);return}}if(service){await speak(locale.current==='pt-BR'?`Seu serviço está ${STATUS_LABELS[service.estado]||service.estado}.`:`Tu servicio está ${STATUS_LABELS[service.estado]||service.estado}.`);return}await speak(locale.current==='pt-BR'?'Me diga o serviço que você precisa e eu completo o pedido por voz.':'Decime qué servicio necesitás y completo el pedido por voz.')}catch(e:any){busy.current=false;setState('error');setError(e?.message||'No pude procesar el pedido por voz.')}},[askNext,geminiProviderLead,handleDraft,hydrate,publish,service,speak])
 const stop=useCallback(()=>{running.current=false;busy.current=false;try{recognition.current?.abort?.()}catch{}try{(window as any).UGOVoiceBridge?.stopListening?.()}catch{}try{audioSourceRef.current?.stop()}catch{}try{void audioContextRef.current?.close()}catch{}audioSourceRef.current=null;audioContextRef.current=null;recognition.current=null;native.current=false;setState('idle')},[])
 const start=useCallback(async()=>{if(!accessToken){setError('Iniciá sesión para hablar con Hugo.');setState('error');return}setError('');setState('connecting');const nb=(window as any).UGOVoiceBridge as NativeBridge|undefined;if(nb&&nb.isAvailable?.()!==false){native.current=true;running.current=true;nb.startListening();setState('ready');return}const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError('El reconocimiento de voz no está disponible en este dispositivo. Podés seguir escribiéndole a Hugo.');setState('error');return}try{const stream=await navigator.mediaDevices?.getUserMedia?.({audio:true});stream?.getTracks().forEach(track=>track.stop())}catch{setError('Permití el micrófono para hablar con Hugo.');setState('error');return}running.current=true;const rec=new SR();recognition.current=rec;rec.lang=locale.current;rec.continuous=false;rec.interimResults=true;rec.onstart=()=>setState('ready');rec.onspeechstart=()=>setState('hearing');rec.onresult=(event:any)=>{let value='',final=false;for(let i=event.resultIndex||0;i<event.results.length;i++){value+=String(event.results[i]?.[0]?.transcript||'');final=final||Boolean(event.results[i]?.isFinal)}value=value.trim();if(value){setUserTranscript(value);if(final)void handleText(value)}};rec.onerror=(event:any)=>{const code=String(event?.error||'');if(code==='no-speech'||code==='aborted')return;running.current=false;setError(code==='not-allowed'?'Permití el micrófono para hablar con Hugo.':'Se interrumpió el reconocimiento de voz.');setState('error')};rec.onend=()=>{if(running.current&&!busy.current)window.setTimeout(()=>{try{rec.start()}catch{}},180)};rec.start()},[accessToken,handleText])
 useEffect(()=>{const nativeResult=(event:Event)=>{if(!running.current)return;const detail=(event as CustomEvent<{text?:string;final?:boolean}>).detail||{},value=String(detail.text||'').trim();if(value&&detail.final!==false)void handleText(value)};const nativeState=(event:Event)=>{if(!running.current||busy.current)return;const value=String((event as CustomEvent<{state?:string}>).detail?.state||'');if(value==='hearing')setState('hearing');else if(value==='connecting')setState('connecting');else if(value==='ready')setState('ready')};const nativeError=(event:Event)=>{const code=String((event as CustomEvent<{code?:string}>).detail?.code||'unavailable');running.current=false;busy.current=false;setState('error');if(code==='not-allowed')setError('Permití el micrófono para hablar con Hugo.');else if(code==='session')setError('Tu sesión venció. Volvé a iniciar sesión para usar la voz.');else setError('No pude usar el micrófono con Gemini. Podés seguir escribiendo y volver a intentar la voz.')};window.addEventListener('ugo:native-voice-result',nativeResult);window.addEventListener('ugo:native-voice-state',nativeState);window.addEventListener('ugo:native-voice-error',nativeError);return()=>{window.removeEventListener('ugo:native-voice-result',nativeResult);window.removeEventListener('ugo:native-voice-state',nativeState);window.removeEventListener('ugo:native-voice-error',nativeError)}},[handleText])
 useEffect(()=>{const open=()=>{if(!running.current)void start()};window.addEventListener(UGO_UI_EVENTS.clientHugo,open);return()=>window.removeEventListener(UGO_UI_EVENTS.clientHugo,open)},[start])
 useEffect(()=>()=>stop(),[stop])
 const sendTyped=()=>{const value=typed.trim();if(!value)return;setTyped('');void handleText(value)}
 const visual=state==='speaking'?'speaking':state==='connecting'?'thinking':state==='hearing'?'listening':state==='ready'?'ready':state==='error'?'error':'idle'
 const providerName=service?.proveedor?.nombre||'',canCancel=Boolean(service&&CANCELLABLE.includes(service.estado))
 return <section className={`ugo-real-hugo prototype-hugo state-${visual}`} aria-label="Hugo, compañero de UGO"><div className="ugo-hugo-stage-card"><div className="ugo-hugo-stage-head"><div><small>HUGO</small><strong>{text}</strong></div><span className={`ugo-hugo-stage-live state-${visual}`}><i/>{LABELS[state]}</span></div>{service&&<div className="ugo-hugo-context-card"><div className="ugo-hugo-context-main"><small>{service.categoria?.emoji||'🧰'} {service.categoria?.nombre||'Servicio UGO'}</small><b>{service.descripcion||`Servicio #${service.numero}`}</b><span>{STATUS_LABELS[service.estado]||service.estado}</span></div>{providerName&&<div className="ugo-hugo-provider-mini"><span>{providerName.slice(0,1).toUpperCase()}</span><div><small>PROFESIONAL</small><b>{providerName}</b></div></div>}</div>}{userTranscript&&<p className="ugo-hugo-user-line"><b>Vos</b><span>{userTranscript}</span></p>}{assistantTranscript&&<p className="ugo-hugo-assistant-line"><b>Hugo</b><span>{assistantTranscript}</span></p>}{error&&<p className="ugo-hugo-stage-error">{error}</p>}<form className="ugo-hugo-stage-composer" onSubmit={event=>{event.preventDefault();sendTyped()}}><input ref={inputRef} value={typed} onChange={event=>setTyped(event.target.value)} placeholder="Escribile a Hugo…"/><button type="submit" disabled={!typed.trim()}>Enviar</button></form><div className="ugo-hugo-stage-actions">{!service&&<button type="button" className="primary" onClick={()=>inputRef.current?.focus()}>Escribirle a Hugo</button>}{service&&<button type="button" onClick={()=>clientActions?.openHistory()}>Ver Actividad</button>}{canCancel&&<button type="button" className="danger" onClick={()=>void clientActions?.cancelService()}>Cancelar pedido</button>}</div></div><button type="button" className="ugo-real-orb" onClick={()=>running.current?stop():void start()} disabled={state==='connecting'} aria-label={running.current?'Cortar conversación con Hugo':'Hablar con Hugo'}><span className="ugo-orb-glass"/><span className="ugo-orb-ring ring-1"/><span className="ugo-orb-ring ring-2"/><span className="ugo-orb-icon">{state==='connecting'?'✦':state==='hearing'?'●':'⌁'}</span></button><div className="ugo-real-state"><i/><span>{LABELS[state]}</span></div></section>
}
