import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join,resolve} from 'node:path'
import {spawnSync} from 'node:child_process'
const sha='synthetic-validator-sha'
const fixture=()=>({status:'PASS',current_sha_open_incidents:0,sha,environment:'UGO TEST',production_touched:false,hugo_action:{status:'PASS',persisted_effect:true,action:'cancel_service',before:{state:'buscando'},after:{state:'cancelado'},audit_trail:{runtime_sha:sha,channel:'ugo:native-voice-tool-call'},service_id:'synthetic-fixture',cleanup_state:'DELETED'},fault_injection:{ui_session_error:{status:'PASS',message:'Sesión vencida; volver a iniciar sesión'},api_auth_error:{status:'PASS',status_code:401,next_step:'Iniciá sesión'}},performance:{status:'PASS',client_initial_load_ms:10,provider_initial_load_ms:10,admin_initial_load_ms:10,client_request_navigation_ms:10,provider_jobs_navigation_ms:10,admin_operations_navigation_ms:10,p95_ms:10,max_ms:10}})
function run(mutator){const dir=mkdtempSync(join(tmpdir(),'ugo-validator-'));try{const evidence=fixture();mutator?.(evidence);const input=join(dir,'runtime.json'),judge=join(dir,'judge.json');writeFileSync(input,JSON.stringify(evidence));const env={...process.env,UGO_RUNTIME_SHA:sha};const result=spawnSync(process.execPath,[resolve('scripts/readiness-safe-batch-judge.mjs'),input,judge],{env,encoding:'utf8'});if(result.status!==0)return result.status;return spawnSync(process.execPath,[resolve('scripts/readiness-safe-batch-sentinel.mjs'),input,judge,join(dir,'sentinel.json')],{env,encoding:'utf8'}).status}finally{rmSync(dir,{recursive:true,force:true})}}
test('accepts complete synthetic evidence (validator test only)',()=>assert.equal(run(),0))
for(const [name,mutate] of Object.entries({open_incident:x=>x.current_sha_open_incidents=1,runtime_failed:x=>x.status='FAIL',sha:x=>x.sha='stale',cleanup:x=>x.hugo_action.cleanup_state='UNKNOWN',state:x=>x.hugo_action.after.state='en_camino',missing_metric:x=>delete x.performance.admin_initial_load_ms,slow:x=>x.performance.client_request_navigation_ms=4001,api_next_step:x=>delete x.fault_injection.api_auth_error.next_step,production:x=>x.production_touched=true}))test('rejects '+name,()=>assert.notEqual(run(mutate),0))
