import React,{useCallback,useEffect,useRef,useState}from'react'
import type{Service}from'../../../mvp/shared'
import{STATUS_LABELS}from'../../../mvp/shared'
import{getRoleSupabase}from'../../../lib/roleSupabase'
import{getDispatchProvider}from'../../../lib/dispatch/provider'
import{resolveClientSavedAddress}from'../../../mvp/hugoDefaultAddress'
import{loadVoiceAvailability,normalizeVoiceText,resolveVoiceCategory,voiceAvailabilityText,type VoiceAvailability,type VoiceCategory}from'../../../mvp/voiceCatalog'
import{UGO_UI_EVENTS}from'../../../mvp/uiEvents'
import type{ClientActionHandlers,ClientHugoIntent}from'../types/clientTypes'
import{chooseHugoProvider,isHugoAffirmative,isHugoNegative,isHugoRetry,parseHugoWhen,resolveHugoGlobalCommand}from'./hugoVoiceIntent'
import'../../../mvp/voice.css'

type PaymentStatus='none'|'cash'|'pending'|'confirmed'
type HugoService=Service&{programado_para?:string|null;created_at?:string|null}
type Props={accessToken?:string;service?:Service|null;services?:HugoService[];availableOffers?:number;paymentStatus?:PaymentStatus;clientActions?:ClientActionHandlers;onIntent?:(intent:Omit<ClientHugoIntent,'id'>)=>void;onNavigateHome?:()=>void;requestComposerOpen?:boolean}
type VoiceState='idle'|'connecting'|'ready'|'hearing'|'speaking'|'error'
type Locale='es-AR'|'pt-BR'
type Draft={category:VoiceCategory|null;description:string;address:string;addressLabel:string;pickupLat:number|null;pickupLng:number|null;pickupSource:'current'|'saved'|'manual'|null;when:'ahora'|'hoy'|'programar'|null;scheduleAt:string;whenLabel:string;paymentMethod:'cash'|'pix'|null;urgent:boolean;preferredProviderId?:string|null;preferredProviderName?:string|null;serviceId?:string|null;requestDraftId:string}
type NativeBridge={startListening:()=>void|Promise<void>;pauseListening?:()=>void;resumeListening?:()=>void|Promise<void>;stopListening:()=>void;isAvailable?:()=>boolean;speak?:(text:string,locale?:string)=>Promise<void>;stopSpeaking?:()=>void}
type GeminiTts={audio_base64?:string;mime_type?:string;sample_rate?:number;model?:string;voice?:string;error?:string;hugo_mensaje?:string}
type GeminiCompanionReply={reply?:string;action?:'none'|'search_provider'|'prepare_request';category_hint?:string|null;urgent?:boolean;description?:string|null;use_current_location?:boolean;address_label?:'Casa'|'Trabajo'|null;address_hint?:string|null;when?:'ahora'|'hoy'|'programar'|null;schedule_at?:string|null;payment_method?:'cash'|'pix'|null;confirm?:boolean;model?:string;error?:string}
type PendingCancel={kind:'draft'}|{kind:'service';serviceId:string;label:string}
type StatusError=Error&{status?:number}
type SpeechRecognitionAlternativeLike={transcript?:string}
type SpeechRecognitionResultLike={0?:SpeechRecognitionAlternativeLike;isFinal?:boolean}
type SpeechRecognitionEventLike={resultIndex?:number;results:ArrayLike<SpeechRecognitionResultLike>}
type SpeechRecognitionErrorEventLike={error?:string}
type SpeechRecognitionLike={lang:string;continuous:boolean;interimResults:boolean;onstart:(()=>void)|null;onspeechstart:(()=>void)|null;onresult:((event:SpeechRecognitionEventLike)=>void)|null;onerror:((event:SpeechRecognitionErrorEventLike)=>void)|null;onend:(()=>void)|null;start:()=>void;abort:()=>void}
type SpeechRecognitionConstructor=new()=>SpeechRecognitionLike
type UgoWindow=Window&typeof globalThis&{UGOVoiceBridge?:NativeBridge;SpeechRecognition?:SpeechRecognitionConstructor;webkitSpeechRecognition?:SpeechRecognitionConstructor;webkitAudioContext?:typeof AudioContext}
type ReverseGeocodeResponse={features?:Array<{properties?:Record<string,unknown>}>}

const LABELS:Record<VoiceState,string>={idle:'Toca para hablar',connecting:'Procesando...',ready:'Te escucho',hearing:'Escuchando...',speaking:'Hablando...',error:'Voz no disponible'}
const CANCELLABLE=['buscando','ofrecido','asignado','en_camino','llegado']

function ugoWindow(){return window as UgoWindow}
function norm(value:string){return normalizeVoiceText(value)}
function localeFrom(text:string,current:Locale){const value=norm(text),pt=(value.match(/\b(quero|preciso|voce|servico|agora|nao|sim|endereco)\b/g)||[]).length,es=(value.match(/\b(quiero|necesito|vos|servicio|ahora|no|si|direccion)\b/g)||[]).length;return pt>=2&&pt>es?'pt-BR':es>=2&&es>pt?'es-AR':current}
function requestIntent(text:string){return/\b(necesito|quiero un|quiero una|quiero pedir|quiero contratar|preciso|quero um|quero uma|quero pedir|quero contratar|me hace falta|necesitaria)\b/.test(norm(text))}
function newRequestIntent(text:string){const value=norm(text);return requestIntent(text)||/\b(otro servicio|otro pedido|otro trabajo|otra cosa|nuevo servicio|nueva solicitud|nuevo pedido|mais um servico|outro servico|outro pedido|outro trabalho|outra coisa)\b/.test(value)}
function searchIntent(text:string){return/\b(busca|buscame|buscar|mostrame|mostre|encontra|encontre|quienes hay|quem tem|disponibles|disponiveis|recomendame|recomenda|recomendacion|recomendacao)\b/.test(norm(text))}
function statusIntent(text:string){return/\b(como viene|como va|estado|seguimiento|donde esta|qué pasa|que pasa|como está|como esta|acompanhar|andamento|status|onde esta)\b/.test(norm(text))}
function cancellationIntent(text:string){return/\b(cancelar|cancela|cancela el|cancela la|cancelá|cancele|desistir)\b/.test(norm(text))}
function urgency(text:string){return/\b(urgente|urgencia|ahora mismo|ya mismo|agora|emergencia)\b/.test(norm(text))}
function wantsGps(text:string){const value=norm(text);return/\b(mi ubicacion|ubicacion actual|mi direccion actual|donde estoy|aca|aqui|en este lugar|minha localizacao|minha localizacao atual|meu endereco atual|onde estou|aqui onde estou)\b/.test(value)||/\b(usar|usa|utilizar|utiliza|tomar|toma|agarrar|agarra|detectar|detecta|poner|pone|cargar|carga|usar|use|utilizar|utilize|pegar|pega)\b.*\b(ubicacion|localizacion|gps|localizacao)\b/.test(value)}
function savedLabel(text:string):'Casa'|'Trabajo'|null{const value=norm(text);if(/\b(mi casa|en casa|casa|hogar|minha casa|em casa)\b/.test(value))return'Casa';if(/\b(mi trabajo|trabajo|oficina|meu trabajo|meu trabalho|trabalho|escritorio)\b/.test(value))return'Trabajo';return null}
function parseDescription(text:string){
 let raw=text.trim().replace(/^bueno[,.]?\s*/i,'').trim(),value=norm(raw)
 if(!raw||/^(si|sí|sim|no|nao|não|dale|ok|okay|confirmo|confirmar|casa|trabajo|oficina|pix|efectivo|dinheiro|cash)$/.test(value))return''
 raw=raw
  .replace(/\b(?:y\s+)?(?:usar|usa|utilizar|utiliza|tomar|toma|agarrar|agarra|detectar|detecta|poner|pone|cargar|carga|use|utilize|pegar|pega)\s+(?:mi\s+|minha\s+)?(?:ubicaci[oó]n|localizaci[oó]n|localiza[cç][aã]o|gps)\b/gi,' ')
  .replace(/\b(?:pago|pagar|pagamento)?\s*(?:en|con|por|em)?\s*(?:efectivo|dinero|cash|dinheiro|pix)\b/gi,' ')
  .replace(/\b(?:ahora|agora|hoy|hoje|mañana|manana|amanhã|amanha)(?:\s+(?:a\s+las?|às?)\s+\d{1,2}(?::\d{2})?)?\b/gi,' ')
  .replace(/\b(?:si|sí|sim)?\s*(?:confirmar|confirmo|confirma|confirmá)\b/gi,' ')
  .replace(/\s+/g,' ').replace(/^[,.;:\s]+|[,.;:\s]+$/g,'').trim()
 value=norm(raw)
 if(raw.length<8)return''
 if(/^(necesito|quiero|preciso|quero)\b/.test(value)&&value.split(' ').length<6)return''
 return raw
}
function parsePaymentMethod(text:string):'cash'|'pix'|null{const value=norm(text);if(/\bpix\b/.test(value))return'pix';if(/\b(efectivo|dinero|en mano|cash|dinheiro)\b/.test(value))return'cash';return null}
function nextMissing(current:Draft){if(!current.category)return'category';if(!current.description)return'description';if(!current.address)return'address';if(!current.when)return'when';if(!current.paymentMethod)return'payment';return'confirm'}
function newDraftId(){try{return crypto.randomUUID()}catch{return`hugo-${Date.now()}-${Math.random().toString(36).slice(2)}`}}
function accessTokenUserId(token?:string){try{const raw=String(token||'').split('.')[1];if(!raw)return'';const value=raw.replace(/-/g,'+').replace(/_/g,'/'),padded=value.padEnd(Math.ceil(value.length/4)*4,'='),payload=JSON.parse(atob(padded));return typeof payload?.sub==='string'?payload.sub:''}catch{return''}}
function emptyVoiceDraft(category:VoiceCategory|null=null):Draft{return{category,description:'',address:'',addressLabel:'',pickupLat:null,pickupLng:null,pickupSource:null,when:null,scheduleAt:'',whenLabel:'',paymentMethod:null,urgent:false,preferredProviderId:null,preferredProviderName:null,serviceId:null,requestDraftId:newDraftId()}}
function serviceMoment(service:HugoService){const raw=service.programado_para||service.created_at||null;if(!raw)return null;const value=new Date(raw);return Number.isNaN(value.getTime())?null:value}
function sameDay(a:Date,b:Date){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function dayMatches(text:string,service:HugoService){const value=norm(text),moment=serviceMoment(service);if(!moment)return !/\b(hoy|mañana|manana|hoje|amanha)\b/.test(value);const now=new Date(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);if(/\b(hoy|hoje)\b/.test(value))return sameDay(moment,now);if(/\b(mañana|manana|amanha)\b/.test(value))return sameDay(moment,tomorrow);return true}
function serviceLabel(service:HugoService){const category=service.categoria?.nombre||'servicio',when=serviceMoment(service);return`${category}${when?` del ${when.toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}`:''}`}
function serviceSummary(service:HugoService,pt:boolean){const category=service.categoria?.nombre||'servicio',state=STATUS_LABELS[service.estado]||service.estado,provider=service.proveedor?.nombre?`${pt?' com ':' con '}${service.proveedor.nombre}`:'',when=serviceMoment(service),schedule=when?`${pt?' para ':' para '}${when.toLocaleString(pt?'pt-BR':'es-AR',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}`:'';return pt?`Seu pedido de ${category}${provider}${schedule} está ${state}.`:`Tu pedido de ${category}${provider}${schedule} está ${state}.`}
function errorMessage(value:unknown,fallback:string){return value instanceof Error?value.message:fallback}
function errorStatus(value:unknown){if(typeof value==='object'&&value!==null&&'status'in value)return Number((value as{status?:unknown}).status||0);return 0}
function ignoreError(value:unknown){void value}

async function reverseGeocode(lat:number,lng:number){
 try{
  const response=await fetch(`https://photon.komoot.io/reverse?lat=${lat}&lon=${lng}`,{signal:AbortSignal.timeout(2500)})
  if(!response.ok)return null
  const data=await response.json() as ReverseGeocodeResponse
  const properties=data.features?.[0]?.properties||{}
  const values=['name','street','housenumber','district','city','state'].map(key=>properties[key]).filter((value):value is string=>typeof value==='string'&&value.length>0)
  return values.join(', ')||null
 }catch{return null}
}

async function resolveServiceCandidates(source:string,services:HugoService[],onlyCancellable=false){
 let rows=services.filter(item=>!onlyCancellable||CANCELLABLE.includes(item.estado))
 if(rows.length<=1)return rows
 const value=norm(source),number=value.match(/(?:servicio|pedido|#)\s*#?\s*(\d+)/)?.[1]
 if(number){const exact=rows.filter(item=>String(item.numero||'')===number||String(item.id).startsWith(number));if(exact.length)return exact}
 const category=await resolveVoiceCategory(source).catch(()=>null)
 if(category){const categoryName=norm(category.nombre||category.slug||'');const filtered=rows.filter(item=>String(item.categoria_id||'')===String(category.id||'')||norm(item.categoria?.nombre||'')===categoryName||value.includes(norm(item.categoria?.nombre||'')));if(filtered.length)rows=filtered}
 const providerMatches=rows.filter(item=>{const name=norm(item.proveedor?.nombre||'');if(!name)return false;return name.split(/\s+/).filter(token=>token.length>=4).some(token=>value.includes(token))})
 if(providerMatches.length)rows=providerMatches
 return rows.filter(item=>dayMatches(source,item))
}

export function ClientVoiceHugoDock({accessToken,service,services=[],clientActions,onIntent,onNavigateHome,requestComposerOpen=false}:Props){
 const[state,setState]=useState<VoiceState>('idle'),[error,setError]=useState(''),[,setUserTranscript]=useState(''),[assistantTranscript,setAssistantTranscript]=useState(''),[voiceRunning,setVoiceRunning]=useState(false),[panelOpen,setPanelOpen]=useState(false)
 const locale=useRef<Locale>('es-AR'),draft=useRef<Draft|null>(null),availability=useRef<VoiceAvailability|null>(null),recognition=useRef<SpeechRecognitionLike|null>(null),running=useRef(false),busy=useRef(false),native=useRef(false),voicePaused=useRef(false),audioContextRef=useRef<AudioContext|null>(null),audioSourceRef=useRef<AudioBufferSourceNode|null>(null),ttsAbortRef=useRef<AbortController|null>(null),ttsSequence=useRef(0),ttsCooldownUntil=useRef(0),queuedInput=useRef<string|null>(null),pendingCancel=useRef<PendingCancel|null>(null),conversation=useRef<Array<{role:'user'|'assistant';content:string}>>([]),processTextRef=useRef<(value:string)=>void>(()=>undefined)
 const setRunning=useCallback((value:boolean)=>{running.current=value;setVoiceRunning(value)},[])

 const pauseRecognition=useCallback(()=>{voicePaused.current=true;if(native.current){try{const bridge=ugoWindow().UGOVoiceBridge;if(bridge?.pauseListening)bridge.pauseListening();else bridge?.stopListening?.()}catch(caught){ignoreError(caught)}}else{try{recognition.current?.abort()}catch(caught){ignoreError(caught)}}},[])
 const resumeRecognition=useCallback(()=>{if(!running.current)return;voicePaused.current=false;window.setTimeout(()=>{if(!running.current||voicePaused.current)return;if(native.current){try{const bridge=ugoWindow().UGOVoiceBridge;const resumed=bridge?.resumeListening?bridge.resumeListening():bridge?.startListening?.();if(resumed&&typeof (resumed as Promise<void>).catch==='function')void (resumed as Promise<void>).catch(ignoreError)}catch(caught){ignoreError(caught)}}else if(recognition.current){try{recognition.current.start()}catch(caught){ignoreError(caught)}}},80)},[])
 const stopSpeechPlayback=useCallback(()=>{ttsSequence.current++;try{ttsAbortRef.current?.abort()}catch(caught){ignoreError(caught)}ttsAbortRef.current=null;try{window.speechSynthesis?.cancel()}catch(caught){ignoreError(caught)}try{ugoWindow().UGOVoiceBridge?.stopSpeaking?.()}catch(caught){ignoreError(caught)}try{audioSourceRef.current?.stop()}catch(caught){ignoreError(caught)}try{void audioContextRef.current?.close()}catch(caught){ignoreError(caught)}audioSourceRef.current=null;audioContextRef.current=null},[])
 const playGeminiPcm=useCallback(async(base64:string,sampleRate=24000)=>{const binary=window.atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const even=bytes.byteLength-bytes.byteLength%2,AudioContextCtor=window.AudioContext||ugoWindow().webkitAudioContext;if(!AudioContextCtor)throw new Error('AudioContext no disponible');const ctx=new AudioContextCtor(),buffer=ctx.createBuffer(1,even/2,sampleRate),channel=buffer.getChannelData(0),view=new DataView(bytes.buffer,bytes.byteOffset,even);for(let i=0;i<channel.length;i++)channel[i]=view.getInt16(i*2,true)/32768;const source=ctx.createBufferSource();source.buffer=buffer;source.connect(ctx.destination);audioContextRef.current=ctx;audioSourceRef.current=source;await ctx.resume();await new Promise<void>(resolve=>{source.onended=()=>resolve();source.start()});if(audioSourceRef.current===source)audioSourceRef.current=null;if(audioContextRef.current===ctx)audioContextRef.current=null;try{await ctx.close()}catch(caught){ignoreError(caught)}},[])
 const playDeviceSpeech=useCallback(async(textValue:string,language:Locale)=>{if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined')throw new Error('Voz del dispositivo no disponible');const speech=new SpeechSynthesisUtterance(textValue);speech.lang=language;speech.rate=1.03;speech.pitch=1;speech.volume=1;await new Promise<void>((resolve,reject)=>{speech.onend=()=>resolve();speech.onerror=event=>reject(new Error(String(event.error||'Voz del dispositivo no disponible')));window.speechSynthesis.cancel();window.speechSynthesis.speak(speech)})},[])
 const speak=useCallback(async(reply:string,voiceText=reply)=>{
  stopSpeechPlayback();setAssistantTranscript(reply);conversation.current=[...conversation.current,{role:'assistant' as const,content:reply}].slice(-10);setError('')
  if(!running.current){setState('idle');return}
  pauseRecognition();setState('speaking')
  const token=ttsSequence.current,liveBridge=ugoWindow().UGOVoiceBridge
  if(!native.current||!liveBridge?.speak){
   setState('error');setError('Gemini Live no está disponible. Hugo no va a reemplazarla por la voz del navegador.');return
  }
  try{
   await liveBridge.speak(voiceText,locale.current)
   if(token===ttsSequence.current&&running.current){setState('ready');resumeRecognition()}
  }catch(liveVoiceError){
   console.error('UGO Gemini Live speaker unavailable',liveVoiceError)
   if(token===ttsSequence.current&&running.current){setState('error');setError('La voz Gemini Live falló. Tocá el orbe para reconectar.')}
  }
 },[pauseRecognition,resumeRecognition,stopSpeechPlayback])
 const publish=useCallback((source:string,category:VoiceCategory|null,description:string|null)=>{if(category)onIntent?.({text:source,categoryHint:category.slug||category.nombre||'',urgent:urgency(source),description})},[onIntent])
 const syncDraft=useCallback((current:Draft)=>{
  const detail={category:current.category?{id:current.category.id,slug:current.category.slug,nombre:current.category.nombre,emoji:current.category.emoji}:null,description:current.description,address:current.address,addressLabel:current.addressLabel,pickupLat:current.pickupLat,pickupLng:current.pickupLng,pickupSource:current.pickupSource,when:current.when,scheduleAt:current.scheduleAt,whenLabel:current.whenLabel,paymentMethod:current.paymentMethod,urgent:current.urgent,voiceJourney:true}
  const userId=accessTokenUserId(accessToken)
  if(userId){try{const key=`ugo:guided-request-draft:${userId}`,previous=JSON.parse(sessionStorage.getItem(key)||'{}');sessionStorage.setItem(key,JSON.stringify({...previous,categoryId:current.category?.id||previous.categoryId||'',categoryName:current.category?.nombre||previous.categoryName||'',categorySlug:current.category?.slug||current.category?.id||previous.categorySlug||'',description:current.description||previous.description||'',address:current.address||previous.address||'',addressLabel:current.addressLabel||previous.addressLabel||'',pickupLat:current.pickupLat,pickupLng:current.pickupLng,pickupSource:current.pickupSource,when:current.when||previous.when||null,whenConfirmed:Boolean(current.when),scheduleAt:current.scheduleAt||'',paymentMethod:current.paymentMethod||previous.paymentMethod||null,urgent:current.urgent,voiceJourney:true}))}catch(caught){ignoreError(caught)}}
  window.dispatchEvent(new CustomEvent(UGO_UI_EVENTS.clientHugoDraft,{detail}))
 },[accessToken])
 const companionContext=useCallback(()=>{const current=draft.current,active=services.slice(0,5).map(item=>`#${item.numero||String(item.id).slice(0,6)} ${item.categoria?.nombre||'Servicio'}: ${STATUS_LABELS[item.estado]||item.estado}`).join(' · '),known=availability.current?.providers.slice(0,3).map(provider=>`${provider.nombre||'Profesional'} (karma ${Number(provider.karma||0).toFixed(1)}, R$ ${Number(provider.tarifa_base||0).toFixed(0)}/h)`).join(' · ');return[`MEMORIA DEL PEDIDO: categoría=${current?.category?.nombre||'sin definir'}; qué_hay_que_hacer=${current?.description||'sin definir'}; dirección=${current?.address||'sin definir'}; cuándo=${current?.whenLabel||'sin definir'}; pago=${current?.paymentMethod||'sin definir'}; urgencia=${current?.urgent?'sí':'no'}; profesional elegido=${current?.preferredProviderName||'ninguno'}.`,active?`PEDIDOS ACTIVOS: ${active}`:'Sin pedidos activos.',known?`CANDIDATOS YA CARGADOS EN EL ORBE: ${known}`:'Sin candidatos precargados en el orbe.'].join('\n').slice(0,2200)},[services])
 const askGeminiCompanion=useCallback(async(source:string)=>{if(!accessToken)return null;try{const response=await fetch('/api/test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({role:'client',companion_mode:true,message:source,context:companionContext(),history:conversation.current.slice(0,-1)}),signal:AbortSignal.timeout(2600)}),data=(await response.json().catch(()=>null))as GeminiCompanionReply|null;if(!response.ok||!data?.reply){console.warn('Hugo Gemini companion unavailable',data?.error||response.status);return null}console.info('Hugo companion',{model:data.model||'ugo-live-data',action:data.action||'none'});return data}catch(caught){console.warn('Hugo Gemini companion unavailable; using local flow.',caught);return null}},[accessToken,companionContext])
 const askNext=useCallback(async(_source:string,current:Draft,lead='')=>{const pt=locale.current==='pt-BR',prefix=lead?`${lead.trim()} `:'',missing=nextMissing(current);if(missing==='category')return speak(prefix+(pt?'Que profissional você precisa?':'¿Qué profesional necesitás?'));if(missing==='description')return speak(prefix+(pt?'O que precisa ser feito?':'¿Qué hay que hacer?'));if(missing==='address')return speak(prefix+(pt?'Onde é o serviço? Pode dizer Casa, Trabalho ou “usar minha localização”.':'¿Dónde es el servicio? Podés decir Casa, Trabajo o “usar mi ubicación”.'));if(missing==='when')return speak(prefix+(pt?'Para quando você precisa? Agora, hoje ou outro momento?':'¿Cuándo lo necesitás? ¿Ahora, hoy o para otro momento?'));if(missing==='payment')return speak(prefix+(pt?'Como vai pagar: dinheiro ou PIX?':'¿Cómo vas a pagar: efectivo o PIX?'));const provider=current.preferredProviderName?(pt?` com ${current.preferredProviderName}`:` con ${current.preferredProviderName}`):'',full=pt?`Confirmo: ${current.category?.nombre}${provider}, ${current.description}, em ${current.address}, ${current.whenLabel}, pagamento ${current.paymentMethod==='pix'?'PIX':'em dinheiro'}. Está certo?`:`Confirmo: ${current.category?.nombre}${provider}, ${current.description}, en ${current.address}, ${current.whenLabel}, pago ${current.paymentMethod==='pix'?'PIX':'en efectivo'}. ¿Está bien?`,short=pt?`Confirma o pedido de ${current.category?.nombre}?`:`¿Confirmás el pedido de ${current.category?.nombre}?`;return speak(full,short)},[speak])
 const createOrder=useCallback(async(current:Draft)=>{const sb=getRoleSupabase('client'),{data:sess}=await sb.auth.getSession(),user=sess.session?.user;if(!user||!current.category)throw new Error('Sesión o categoría no disponible');let serviceId=String(current.serviceId||'');if(!serviceId){const metadata={source:'hugo-conversational',voice:true,demo:false,request_draft_id:current.requestDraftId,requested_when:current.when,scheduled_at:current.when==='programar'?current.scheduleAt:null,payment_method:current.paymentMethod==='pix'?'pix':'efectivo',address_label:current.addressLabel||null,pickup_source:current.pickupSource||null,preferred_provider_id:current.preferredProviderId||null};const{data,error:insertError}=await sb.from('servicios').insert({cliente_id:user.id,categoria_id:current.category.id,estado:'buscando',descripcion:current.description,direccion_cliente:current.address,tarifa:null,urgencia:current.urgent,metadata}).select('id').single();if(insertError){if(String(insertError.code||'')==='23505'){const{data:existing}=await sb.from('servicios').select('id').eq('cliente_id',user.id).eq('metadata->>request_draft_id',current.requestDraftId).maybeSingle();if(existing?.id){serviceId=String(existing.id);current.serviceId=serviceId}else throw insertError}else throw insertError}else{if(!data?.id)throw new Error('No se pudo crear el pedido');serviceId=String(data.id);current.serviceId=serviceId}}const dispatch=getDispatchProvider();try{const persisted=await dispatch.getStatus(serviceId).catch(()=>null);if(persisted?.state==='offering'||persisted?.state==='matched')return serviceId;const pickup=current.pickupLat!=null&&current.pickupLng!=null?{latitude:Number(current.pickupLat),longitude:Number(current.pickupLng)}:null;await dispatch.start({serviceId,category:current.category.slug||current.category.id,preferredProviderId:current.preferredProviderId||null,pickup,pickupFallback:'none'});return serviceId}catch{try{const persisted=await dispatch.getStatus(serviceId);if(persisted.state==='offering'||persisted.state==='matched')return serviceId}catch(caught){ignoreError(caught)}throw new Error(`El pedido ${serviceId} quedó guardado, pero no pude iniciar la búsqueda. Decime “reintentar búsqueda” y sigo desde el mismo pedido.`)}},[])
 const finishOrder=useCallback(async(current:Draft,pt:boolean)=>{
  try{
   if(requestComposerOpen)syncDraft(current)
   const id=await createOrder(current),name=current.preferredProviderName
   draft.current=null;availability.current=null;onNavigateHome?.()
   await speak(pt?`Pronto. Pedido ${id} criado${name?` para ${name}`:''}. A busca começou.`:`Listo. Pedido ${id} creado${name?` para ${name}`:''}. La búsqueda empezó.`,pt?'Pedido confirmado. A busca começou.':'Pedido confirmado. La búsqueda empezó.')
  }catch(caught:unknown){const message=errorMessage(caught,'error');await speak(pt?`Não consegui completar a busca: ${message}`:`No pude completar la búsqueda: ${message}`)}
 },[createOrder,onNavigateHome,requestComposerOpen,speak,syncDraft])

 const beginCancellation=useCallback(async(source:string)=>{const pt=locale.current==='pt-BR';if(draft.current&&!services.length){pendingCancel.current={kind:'draft'};await speak(pt?'Quer descartar este pedido antes de enviar?':'¿Querés descartar este pedido antes de enviarlo?');return true}const candidates=await resolveServiceCandidates(source,services,true);if(candidates.length===1){pendingCancel.current={kind:'service',serviceId:candidates[0].id,label:serviceLabel(candidates[0])};await speak(pt?`Confirmo o cancelamento de ${serviceLabel(candidates[0])}?`:`¿Confirmo la cancelación de ${serviceLabel(candidates[0])}?`);return true}if(candidates.length>1){clientActions?.openHistory();await speak(pt?`Encontrei ${candidates.length} pedidos que podem ser cancelados. Diga a categoria ou o horário, ou escolha em Atividade.`:`Encontré ${candidates.length} pedidos que se pueden cancelar. Decime la categoría o el horario, o elegilo en Actividad.`);return true}if(draft.current){pendingCancel.current={kind:'draft'};await speak(pt?'Quer descartar este pedido antes de enviar?':'¿Querés descartar este pedido antes de enviarlo?');return true}await speak(pt?'Não encontrei um pedido cancelável com essa descrição.':'No encontré un pedido cancelable con esa descripción.');return true},[clientActions,service?.estado,services,speak])
 const captureCurrentLocation=useCallback(async(current:Draft)=>{
  let coords:{lat:number;lng:number;label?:string}|null=null
  if(navigator.geolocation)coords=await new Promise(resolve=>navigator.geolocation.getCurrentPosition(pos=>resolve({lat:pos.coords.latitude,lng:pos.coords.longitude}),()=>resolve(null),{enableHighAccuracy:true,timeout:8000,maximumAge:15000}))
  if(!coords){try{const stored=JSON.parse(sessionStorage.getItem('ugo:last-client-location')||'null')as{latitude?:unknown;longitude?:unknown;label?:unknown;at?:unknown}|null,lat=Number(stored?.latitude),lng=Number(stored?.longitude),at=Number(stored?.at);if(stored&&Number.isFinite(lat)&&Number.isFinite(lng)&&Number.isFinite(at)&&Date.now()-at<=5*60*1000)coords={lat,lng,label:typeof stored.label==='string'?stored.label:undefined}}catch(caught){ignoreError(caught)}}
  if(!coords)return false
  const{lat,lng}=coords,address=coords.label||await reverseGeocode(lat,lng)||`Ubicación actual GPS ${lat.toFixed(6)}, ${lng.toFixed(6)}`
  current.address=address;current.addressLabel=locale.current==='pt-BR'?'Localização atual':'Ubicación actual';current.pickupLat=lat;current.pickupLng=lng;current.pickupSource='current'
  try{sessionStorage.setItem('ugo:last-client-location',JSON.stringify({latitude:lat,longitude:lng,label:address,at:Date.now()}));const sb=getRoleSupabase('client'),{data:sess}=await sb.auth.getSession();if(sess.session?.user)await Promise.allSettled([sb.from('usuarios').update({lat,lng}).eq('id',sess.session.user.id),sb.from('perfiles_cliente').update({ubicacion:`POINT(${lng} ${lat})`}).eq('usuario_id',sess.session.user.id)])}catch(caught){ignoreError(caught)}
  return true
 },[])
 const applyTurnSignals=useCallback(async(current:Draft,source:string,companion:GeminiCompanionReply|null=null)=>{
  const missingBefore=nextMissing(current),normalized=norm(source),explicitCategory=await resolveVoiceCategory(source).catch(()=>null)
  if(explicitCategory&&(!current.category||newRequestIntent(source)||/\b(no|mejor|cambia|cambiar|quise decir|nao|não|melhor|troca|trocar)\b/.test(normalized)))current.category=explicitCategory
  if(!current.category&&companion?.category_hint)current.category=await resolveVoiceCategory(companion.category_hint).catch(()=>null)
  if(!current.description){const candidate=String(companion?.description||parseDescription(source)).trim();if(candidate.length>=8)current.description=candidate}
  const localWhen=parseHugoWhen(source),localPayment=parsePaymentMethod(source),gpsRequested=wantsGps(source)||Boolean(companion?.use_current_location),label=savedLabel(source)||companion?.address_label||null
  let lead=''
  if(gpsRequested){const ok=await captureCurrentLocation(current);lead=ok?(locale.current==='pt-BR'?'Localização atual carregada.':'Ubicación actual cargada.'):(locale.current==='pt-BR'?'Não consegui acessar o GPS.':'No pude acceder al GPS. Revisá el permiso de ubicación.')}
  else if(label){const saved=await resolveClientSavedAddress(label);if(saved){current.address=saved.address;current.addressLabel=saved.label;current.pickupLat=saved.latitude;current.pickupLng=saved.longitude;current.pickupSource='saved';lead=locale.current==='pt-BR'?`${saved.label} carregada.`:`${saved.label} cargada.`}}
  if(!current.address&&companion?.address_hint&&companion.address_hint.trim().length>=5){current.address=companion.address_hint.trim();current.addressLabel=locale.current==='pt-BR'?'Endereço informado':'Dirección indicada';current.pickupLat=null;current.pickupLng=null;current.pickupSource='manual'}
  if(!current.address&&missingBefore==='address'&&!gpsRequested&&!label&&!localWhen&&!localPayment&&!isHugoAffirmative(source)&&!isHugoNegative(source)&&source.trim().length>=5){current.address=source.trim();current.addressLabel=locale.current==='pt-BR'?'Endereço informado':'Dirección indicada';current.pickupLat=null;current.pickupLng=null;current.pickupSource='manual'}
  if(localWhen){current.when=localWhen.when;current.scheduleAt=localWhen.scheduleAt;current.whenLabel=localWhen.whenLabel;current.urgent=current.urgent||localWhen.urgent}
  else if(companion?.when==='ahora'||companion?.when==='hoy'){current.when=companion.when;current.scheduleAt='';current.whenLabel=companion.when==='ahora'?(locale.current==='pt-BR'?'agora':'ahora'):(locale.current==='pt-BR'?'hoje':'hoy');current.urgent=current.urgent||companion.when==='ahora'}
  else if(companion?.when==='programar'&&companion.schedule_at&&new Date(companion.schedule_at).getTime()>Date.now()){current.when='programar';current.scheduleAt=companion.schedule_at;current.whenLabel=new Date(companion.schedule_at).toLocaleString(locale.current==='pt-BR'?'pt-BR':'es-AR');current.urgent=false}
  const method=localPayment||companion?.payment_method||null;if(method)current.paymentMethod=method
  current.urgent=current.urgent||urgency(source)||Boolean(companion?.urgent)
  return lead
 },[captureCurrentLocation])
 const refreshAvailability=useCallback((category:VoiceCategory)=>{void loadVoiceAvailability(category).then(result=>{if(draft.current?.category?.id===category.id)availability.current=result}).catch(error=>console.warn('Hugo provider availability unavailable',error))},[])
 const handleGlobalCommand=useCallback(async(source:string)=>{const pt=locale.current==='pt-BR';if(pendingCancel.current){const pending=pendingCancel.current;if(isHugoAffirmative(source)){pendingCancel.current=null;if(pending.kind==='draft'){draft.current=null;availability.current=null;await speak(pt?'Certo. Descartei esse pedido antes de enviar.':'Listo. Descarté ese pedido antes de enviarlo.');return true}const ok=await clientActions?.cancelService(pending.serviceId);if(ok){onNavigateHome?.();await speak(pt?`Pedido ${pending.label} cancelado.`:`Pedido ${pending.label} cancelado.`);return true}await speak(pt?'Não consegui cancelar agora. O pedido continua como estava.':'No pude cancelar ahora. El pedido sigue como estaba.');return true}if(isHugoNegative(source)){pendingCancel.current=null;await speak(pt?'Certo, não cancelo.':'Perfecto, no cancelo.');return true}await speak(pt?'Confirma o cancelamento? Diga sim ou não.':'¿Confirmás la cancelación? Decime sí o no.');return true}const command=resolveHugoGlobalCommand(source);if(command==='home'){onNavigateHome?.();await speak(pt?'Pronto, voltamos ao início.':'Listo, volvimos a Inicio.');return true}if(command==='activity'){clientActions?.openHistory();await speak(pt?'Abri sua atividade.':'Abrí tu Actividad.');return true}if(/\b(aprobar trabajo|confirmar trabajo|trabajo esta bien|trabalho esta bom|aprovar trabalho)\b/.test(norm(source))){if(service?.estado!=='esperando_aprobacion'){await speak(pt?'Não há um trabalho aguardando sua aprovação.':'No hay un trabajo esperando tu aprobación.');return true}const ok=await clientActions?.approveService();await speak(ok?(pt?'Confirmação enviada pelo fluxo protegido do serviço.':'Confirmación enviada por el flujo protegido del servicio.'):(pt?'Não pude confirmar. Abra o serviço para revisar evidência e pagamento.':'No pude confirmarlo. Abrí el servicio para revisar evidencia y pago.'));return true}if(/\b(ya pague|pague en efectivo|ja paguei|paguei em dinheiro)\b/.test(norm(source))){if(service?.estado!=='esperando_aprobacion'){await speak(pt?'Não há um pagamento em dinheiro pendente para este serviço.':'No hay un pago en efectivo pendiente para este servicio.');return true}const ok=await clientActions?.approveService();await speak(ok?(pt?'Pagamento confirmado. UGO fecha o serviço quando as regras de pagamento estiverem cumpridas.':'Pago confirmado. UGO cierra el servicio cuando se cumplen las reglas de pago.'):(pt?'Ainda não posso confirmar esse pagamento. Revise o fechamento do serviço.':'Todavía no puedo confirmar ese pago. Revisá el cierre del servicio.'));return true}if(/\b(calificar|calificacion|estrellas|avaliar|avaliacao)\b/.test(norm(source))){clientActions?.openReview();await speak(pt?'Abri a avaliação do serviço concluído.':'Abrí la calificación del servicio completado.');return true}if(command==='cancel'||cancellationIntent(source))return beginCancellation(source);return false},[beginCancellation,clientActions,onNavigateHome,speak])
 const handleDraft=useCallback(async(source:string)=>{
  const current=draft.current;if(!current)return false;const pt=locale.current==='pt-BR'
  if(current.serviceId&&isHugoRetry(source)){await finishOrder(current,pt);return true}
  const picked=chooseHugoProvider(source,availability.current?.providers||[])
  if(picked){current.preferredProviderId=picked.id;current.preferredProviderName=picked.nombre||null;syncDraft(current);await askNext(source,current,pt?`Perfeito, escolhi ${picked.nombre}.`:`Perfecto, elegí a ${picked.nombre}.`);return true}
  let lead=await applyTurnSignals(current,source,null),companion:GeminiCompanionReply|null=null
  // Keep the hot voice path local. Gemini companion is only a semantic fallback
  // when deterministic UGO parsing still cannot identify the service or task.
  if(!current.category||!current.description){companion=await askGeminiCompanion(source);if(companion){const aiLead=await applyTurnSignals(current,source,companion);if(!lead)lead=aiLead}}
  if(current.category){publish(source,current.category,current.description||null);syncDraft(current);refreshAvailability(current.category)}else syncDraft(current)
  const missing=nextMissing(current)
  if(missing==='confirm'){if(isHugoNegative(source)){draft.current=null;availability.current=null;await speak(pt?'Perfeito, não confirmo o pedido.':'Perfecto, no confirmo el pedido.');return true}if(isHugoAffirmative(source)||Boolean(companion?.confirm)){await finishOrder(current,pt);return true}}
  await askNext(source,current,lead||(companion?.reply||''));return true
 },[applyTurnSignals,askGeminiCompanion,askNext,finishOrder,publish,refreshAvailability,speak,syncDraft])
 const handleText=useCallback(async(source:string)=>{
  const clean=source.trim();if(!clean)return;stopSpeechPlayback();setUserTranscript(clean)
  if(busy.current){queuedInput.current=clean;return}
  busy.current=true;conversation.current=[...conversation.current,{role:'user' as const,content:clean}].slice(-10);setState('connecting');setError('');locale.current=localeFrom(clean,locale.current)
  try{
   if(await handleGlobalCommand(clean))return
   if(draft.current&&await handleDraft(clean))return
   if(statusIntent(clean)){const candidates=await resolveServiceCandidates(clean,services,false);if(candidates.length===1){await speak(serviceSummary(candidates[0],locale.current==='pt-BR'));return}if(candidates.length>1){clientActions?.openHistory();await speak(locale.current==='pt-BR'?`Tenho ${candidates.length} pedidos que coincidem. Diga a categoria, o profissional ou o horário, ou escolha em Atividade.`:`Tengo ${candidates.length} pedidos que coinciden. Decime la categoría, el profesional o el horario, o elegilo en Actividad.`);return}}
   if(searchIntent(clean)&&!requestIntent(clean)){const category=await resolveVoiceCategory(clean).catch(()=>null);if(category){const current=emptyVoiceDraft(category);current.urgent=urgency(clean);draft.current=current;publish(clean,category,null);syncDraft(current);const result=await Promise.race([loadVoiceAvailability(category).catch(()=>null),new Promise<null>(resolve=>window.setTimeout(()=>resolve(null),1400))]);if(result){availability.current=result;await askNext(clean,current,voiceAvailabilityText(result,locale.current))}else{refreshAvailability(category);await askNext(clean,current,locale.current==='pt-BR'?`${category.nombre}, certo.`:`${category.nombre}, perfecto.`)}return}}
   const directCategory=await resolveVoiceCategory(clean).catch(()=>null)
   const localRequest=Boolean(directCategory)||newRequestIntent(clean)||wantsGps(clean)
   if(localRequest){const current=emptyVoiceDraft(directCategory),lead=await applyTurnSignals(current,clean,null);draft.current=current;if(current.category){publish(clean,current.category,current.description||null);refreshAvailability(current.category)}syncDraft(current);await askNext(clean,current,lead);return}
   const companion=await askGeminiCompanion(clean)
   let suggested=directCategory
   if(!suggested&&companion?.category_hint)suggested=await resolveVoiceCategory(companion.category_hint).catch(()=>null)
   if(companion?.action==='prepare_request'||companion?.action==='search_provider'){const current=emptyVoiceDraft(suggested),lead=await applyTurnSignals(current,clean,companion);draft.current=current;if(current.category){publish(clean,current.category,current.description||null);refreshAvailability(current.category)}syncDraft(current);await askNext(clean,current,lead||(companion?.reply||''));return}
   if(companion){await speak(companion.reply||'Contame un poco más y lo resolvemos juntos.');return}
   await speak(locale.current==='pt-BR'?'Me conta o que você quer resolver. Eu te ajudo a encontrar a pessoa certa.':'Contame qué querés resolver. Yo te ayudo a encontrar a la persona indicada.')
  }catch(caught:unknown){setState('error');setError(errorMessage(caught,'No pude procesar el pedido.'))}
  finally{busy.current=false;const queued=queuedInput.current;queuedInput.current=null;if(queued)window.setTimeout(()=>processTextRef.current(queued),0)}
 },[applyTurnSignals,askGeminiCompanion,askNext,clientActions,handleDraft,handleGlobalCommand,publish,refreshAvailability,services,speak,stopSpeechPlayback,syncDraft])
 useEffect(()=>{processTextRef.current=value=>{void handleText(value)}},[handleText])

 const stop=useCallback(()=>{setPanelOpen(false);setRunning(false);busy.current=false;queuedInput.current=null;voicePaused.current=false;stopSpeechPlayback();try{recognition.current?.abort()}catch(caught){ignoreError(caught)}try{ugoWindow().UGOVoiceBridge?.stopListening?.()}catch(caught){ignoreError(caught)}recognition.current=null;native.current=false;setState('idle');setError('');window.setTimeout(()=>{},0)},[setRunning,stopSpeechPlayback])
 const start=useCallback(async()=>{setPanelOpen(true);if(!accessToken){setError('Iniciá sesión para hablar con Hugo.');setState('error');return}setError('');setState('connecting');const nb=ugoWindow().UGOVoiceBridge;if(nb&&nb.isAvailable?.()!==false){native.current=true;setRunning(true);voicePaused.current=false;try{await nb.startListening();setState('ready');return}catch(caught){console.warn('Gemini Live no disponible; usando reconocimiento del dispositivo.',caught);try{nb.stopListening()}catch(stopError){ignoreError(stopError)}native.current=false;setRunning(false)}}const SR=ugoWindow().SpeechRecognition||ugoWindow().webkitSpeechRecognition;if(!SR){setError('El reconocimiento de voz no está disponible en este dispositivo. Revisá el permiso del micrófono y tocá el orbe para reintentar.');setState('error');return}try{const stream=await navigator.mediaDevices?.getUserMedia?.({audio:true});stream?.getTracks().forEach(track=>track.stop())}catch{setError('Permití el micrófono para hablar con Hugo.');setState('error');return}setRunning(true);voicePaused.current=false;const rec=new SR();recognition.current=rec;rec.lang=locale.current;rec.continuous=false;rec.interimResults=true;rec.onstart=()=>setState('ready');rec.onspeechstart=()=>{stopSpeechPlayback();setState('hearing')};rec.onresult=(event:SpeechRecognitionEventLike)=>{let value='',final=false;for(let i=event.resultIndex||0;i<event.results.length;i++){value+=String(event.results[i]?.[0]?.transcript||'');final=final||Boolean(event.results[i]?.isFinal)}value=value.trim();if(value){setUserTranscript(value);if(final)void handleText(value)}};rec.onerror=(event:SpeechRecognitionErrorEventLike)=>{const code=String(event.error||'');if(code==='no-speech'||code==='aborted')return;setRunning(false);setError(code==='not-allowed'?'Permití el micrófono para hablar con Hugo.':'Se interrumpió el reconocimiento de voz.');setState('error')};rec.onend=()=>{if(running.current&&!busy.current&&!voicePaused.current)window.setTimeout(()=>{if(running.current&&!voicePaused.current)try{rec.start()}catch(caught){ignoreError(caught)}},100)};rec.start()},[accessToken,handleText,setRunning,stopSpeechPlayback])
 useEffect(()=>{const nativeResult=(event:Event)=>{if(!running.current)return;const detail=(event as CustomEvent<{text?:string;final?:boolean}>).detail||{},value=String(detail.text||'').trim();if(!value)return;setUserTranscript(value);if(detail.final===false){setState('hearing');return}void handleText(value)};const nativeState=(event:Event)=>{if(!running.current)return;const value=String((event as CustomEvent<{state?:string}>).detail?.state||'');if(value==='hearing'){stopSpeechPlayback();setState('hearing')}else if(value==='connecting')setState('connecting');else if(value==='speaking')setState('speaking');else if(value==='ready'&&!busy.current&&!voicePaused.current)setState('ready')};const nativeError=(event:Event)=>{const code=String((event as CustomEvent<{code?:string}>).detail?.code||'unavailable');setRunning(false);busy.current=false;setState('error');if(code==='not-allowed')setError('Permití el micrófono para hablar con Hugo.');else if(code==='session')setError('Tu sesión venció. Volvé a iniciar sesión para usar la voz.');else setError('No pude mantener la sesión de voz con Gemini Live. Podés seguir escribiendo y volver a intentar la voz.')};window.addEventListener('ugo:native-voice-result',nativeResult);window.addEventListener('ugo:native-voice-state',nativeState);window.addEventListener('ugo:native-voice-error',nativeError);return()=>{window.removeEventListener('ugo:native-voice-result',nativeResult);window.removeEventListener('ugo:native-voice-state',nativeState);window.removeEventListener('ugo:native-voice-error',nativeError)}},[handleText,setRunning,stopSpeechPlayback])
 useEffect(()=>{const open=()=>{if(!running.current)void start()};window.addEventListener(UGO_UI_EVENTS.clientHugo,open);return()=>window.removeEventListener(UGO_UI_EVENTS.clientHugo,open)},[start])
 useEffect(()=>()=>stop(),[stop])
 const visual=state==='speaking'?'speaking':state==='connecting'?'thinking':state==='hearing'?'listening':state==='ready'?'ready':state==='error'?'error':'idle'
 return <section className={`ugo-real-hugo prototype-hugo state-${visual}`} aria-label="Hugo, controlador por voz del cliente">{panelOpen&&<div className="ugo-hugo-voice-controller" role="status" aria-live="polite"><small>HUGO · CLIENTE</small><strong>{LABELS[state]}</strong>{assistantTranscript&&<span>{assistantTranscript}</span>}{error&&<span className="ugo-hugo-stage-error">{error}</span>}</div>}<button type="button" className="ugo-real-orb" onClick={()=>voiceRunning?stop():void start()} aria-label={voiceRunning?'Cortar conversación con Hugo':'Hablar con Hugo'}><span className="ugo-orb-glass"/><span className="ugo-orb-ring ring-1"/><span className="ugo-orb-ring ring-2"/><span className="ugo-orb-icon">{state==='connecting'?'✦':state==='hearing'?'●':'⌁'}</span></button><div className="ugo-real-state"><i/><span>{LABELS[state]}</span></div></section>
}
