import crypto from'node:crypto'
import{createClient,type SupabaseClient}from'@supabase/supabase-js'

export type ApiReq={method?:string;headers?:Record<string,string|string[]|undefined>;query?:Record<string,string|string[]|undefined>;body?:unknown}
export type ApiRes={status:(code:number)=>ApiRes;json:(body:unknown)=>void;setHeader:(name:string,value:string)=>void;end:(body?:string)=>void}

const TEST_URL='https://tmossnqfwfwjrtzwcbmm.supabase.co'
const env=(name:string)=>String(process.env[name]||'').trim()
export const googleConfigured=()=>Boolean(env('GOOGLE_CALENDAR_CLIENT_ID')&&env('GOOGLE_CALENDAR_CLIENT_SECRET')&&env('GOOGLE_CALENDAR_STATE_SECRET'))
export const serviceClient=()=>{const key=env('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw Object.assign(new Error('SUPABASE_SERVICE_ROLE_KEY no configurada.'),{status:503});return createClient(env('VITE_SUPABASE_URL')||TEST_URL,key,{auth:{autoRefreshToken:false,persistSession:false}})}

function bearer(req:ApiReq){const raw=req.headers?.authorization;const value=Array.isArray(raw)?raw[0]:raw||'';return value.replace(/^Bearer\s+/i,'').trim()}
export async function requireProvider(req:ApiReq){const token=bearer(req);if(!token)throw Object.assign(new Error('Autenticación requerida.'),{status:401});const admin=serviceClient(),{data,error}=await admin.auth.getUser(token);const user=data.user;if(error||!user)throw Object.assign(new Error('Sesión inválida.'),{status:401});const{data:row,error:roleError}=await admin.from('usuarios').select('tipo').eq('id',user.id).maybeSingle();if(roleError||row?.tipo!=='proveedor')throw Object.assign(new Error('Esta integración es exclusiva del proveedor.'),{status:403});return{userId:user.id,admin}}
export const appBase=(req:ApiReq)=>{const configured=env('UGO_PUBLIC_BASE_URL');if(configured)return configured.replace(/\/$/,'');const host=Array.isArray(req.headers?.host)?req.headers?.host[0]:req.headers?.host;const proto=Array.isArray(req.headers?.['x-forwarded-proto'])?req.headers?.['x-forwarded-proto'][0]:req.headers?.['x-forwarded-proto'];return String(proto||'https')+'://'+String(host||'localhost')}
export const redirectUri=(req:ApiReq)=>env('GOOGLE_CALENDAR_REDIRECT_URI')||appBase(req)+'/api/calendar/callback'

const b64=(value:Buffer|string)=>Buffer.from(value).toString('base64url')
export function signState(userId:string){const payload=b64(JSON.stringify({uid:userId,nonce:crypto.randomUUID(),exp:Date.now()+10*60*1000})),secret=env('GOOGLE_CALENDAR_STATE_SECRET');if(!secret)throw Object.assign(new Error('Google Calendar no está configurado.'),{status:503});const sig=crypto.createHmac('sha256',secret).update(payload).digest('base64url');return payload+'.'+sig}
export function verifyState(value:string){const[encoded,sig]=String(value||'').split('.');const secret=env('GOOGLE_CALENDAR_STATE_SECRET');if(!encoded||!sig||!secret)throw Object.assign(new Error('Estado OAuth inválido.'),{status:400});const expected=crypto.createHmac('sha256',secret).update(encoded).digest('base64url'),a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw Object.assign(new Error('Estado OAuth inválido.'),{status:400});const payload=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8')) as{uid?:string;exp?:number};if(!payload.uid||!payload.exp||payload.exp<Date.now())throw Object.assign(new Error('La conexión a Google Calendar venció. Reintentá.'),{status:400});return payload.uid}

export function googleAuthorizeUrl(req:ApiReq,state:string){if(!googleConfigured())throw Object.assign(new Error('Google Calendar todavía no está configurado en UGO.'),{status:503});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.searchParams.set('client_id',env('GOOGLE_CALENDAR_CLIENT_ID'));url.searchParams.set('redirect_uri',redirectUri(req));url.searchParams.set('response_type','code');url.searchParams.set('access_type','offline');url.searchParams.set('prompt','consent');url.searchParams.set('include_granted_scopes','true');url.searchParams.set('scope','openid email https://www.googleapis.com/auth/calendar.events');url.searchParams.set('state',state);return url.toString()}

async function tokenRequest(body:URLSearchParams){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const payload=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw Object.assign(new Error(String((payload.error_description||payload.error)||'Google OAuth rechazó la solicitud.')),{status:502});return payload}
export async function exchangeCode(req:ApiReq,code:string){return tokenRequest(new URLSearchParams({code,client_id:env('GOOGLE_CALENDAR_CLIENT_ID'),client_secret:env('GOOGLE_CALENDAR_CLIENT_SECRET'),redirect_uri:redirectUri(req),grant_type:'authorization_code'}))}
export async function refreshAccess(refreshToken:string){const payload=await tokenRequest(new URLSearchParams({refresh_token:refreshToken,client_id:env('GOOGLE_CALENDAR_CLIENT_ID'),client_secret:env('GOOGLE_CALENDAR_CLIENT_SECRET'),grant_type:'refresh_token'}));const token=String(payload.access_token||'');if(!token)throw Object.assign(new Error('Google no devolvió un access token.'),{status:502});return token}

export type CalendarConnection={proveedor_id:string;google_email:string|null;calendar_id:string;refresh_token:string;scope:string|null;connected_at:string;updated_at:string}
export async function connectionFor(admin:SupabaseClient,userId:string){const{data,error}=await admin.from('proveedor_calendar_conexiones').select('proveedor_id,google_email,calendar_id,refresh_token,scope,connected_at,updated_at').eq('proveedor_id',userId).maybeSingle();if(error)throw error;return(data||null)as CalendarConnection|null}
export async function googleJson(accessToken:string,url:string,init:RequestInit={}){const response=await fetch(url,{...init,headers:{Authorization:'Bearer '+accessToken,'Content-Type':'application/json',...(init.headers||{})}});if(response.status===204)return null;const payload=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok){const nested=payload.error as{message?:string}|undefined;throw Object.assign(new Error(nested?.message||'Google Calendar HTTP '+response.status),{statusCode:response.status})}return payload}
export const calendarUrl=(calendarId:string,suffix='')=>'https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(calendarId)+'/events'+suffix
export const httpError=(res:ApiRes,error:unknown)=>{const status=Number((error as{status?:number})?.status)||500;res.status(status>=400&&status<600?status:500).json({error:error instanceof Error?error.message:'Error inesperado.'})}
