export type Prospect={id:string;external_id:string|null;nombre:string;categoria:string;telefono:string|null;email:string|null;website:string|null;direccion:string|null;ciudad:string|null;pais:string|null;fuente:string;score_confianza:number;estado:string;notas_hugo:string|null;created_at:string;updated_at:string;contactado_at:string|null;aprobado_at:string|null;pipeline_etapa:string;recruitment_score:number;contactos_intentos:number;ultimo_canal:string|null;ultimo_contacto_at:string|null;proximo_contacto_at:string|null;no_contactar:boolean;invitation_token:string|null;invitation_expires_at:string|null;invitation_revoked_at:string|null;invitation_opened_at:string|null;invitation_claimed_at:string|null;converted_user_id:string|null;source_campaign_id:string|null}
export type DemandRow={slug:string;nombre:string;emoji:string|null;pedidos_30d:number;proveedores_activos:number;brecha:number;prioridad:string}
export type Campaign={id:string;nombre:string;categoria:string|null;zona:string|null;canal:string;estado:string;created_at:string;total:number;enviados:number;respondieron:number;interesados:number;convertidos:number}
export type EventRow={id:string;canal:string;tipo:string;direccion:string;estado:string|null;mensaje:string|null;metadata:unknown;created_at:string}
export type DuplicateGroup={duplicate_key:string;total:number;prospect_ids:string[]}
export type GmailStatus={configured:boolean;connected:boolean;email:string|null;updatedAt:string|null}

export const STAGES=[['nuevo','Nuevo'],['listo','Listo'],['contactado','Contactado'],['respondio','Respondió'],['interesado','Interesado'],['registro_iniciado','Registro iniciado'],['documentos_pendientes','Documentos'],['aprobado','Aprobado'],['activo','Activo'],['no_interesado','No interesado']]as const
export const CATEGORY_LABELS:Record<string,string>={electricista:'Electricista',plomero:'Plomero',limpeza:'Limpieza',chaveiro:'Cerrajería',pintura:'Pintura',carpintaria:'Carpintería',jardinagem:'Jardinería',climatizacao:'Climatización',ti_redes:'TI / Redes',reformas:'Reformas',marido_aluguel:'Servicios generales',mudanca:'Mudanzas',automotivo:'Automotivo'}
export const demandScoutKey=(slug:string)=>({electricidad:'electricista',plomeria:'plomero',limpieza:'limpeza',cerrajeria:'chaveiro',pintura:'pintura',jardineria:'jardinagem',reparaciones:'reformas'}as Record<string,string>)[slug]||slug
export const stageLabel=(stage:string)=>STAGES.find(([id])=>id===stage)?.[1]||stage.replaceAll('_',' ')
export const safePhone=(value?:string|null)=>String(value||'').replace(/\D/g,'')
export const safeWebsite=(value?:string|null)=>{try{const raw=String(value||'').trim();if(!raw)return'';const u=new URL(/^https?:\/\//i.test(raw)?raw:'https://'+raw);return['http:','https:'].includes(u.protocol)?u.toString():''}catch{return''}}
export const legacyState=(stage:string)=>stage==='activo'||stage==='aprobado'?'aprobado':stage==='no_interesado'?'rechazado':['contactado','respondio','interesado','registro_iniciado','documentos_pendientes'].includes(stage)?'invitado':'prospecto_pendiente'
