-- Runtime-governed model router registry and telemetry. Secrets never persist here.
create table if not exists public.autonomous_model_candidates(id uuid primary key default gen_random_uuid(),provider text not null,model_id text not null,free_tier boolean not null default false,eligible boolean not null default false,benchmark_score numeric(8,4),benchmark_threshold numeric(8,4) not null default 0.8,availability text not null default 'UNKNOWN' check(availability in('UNKNOWN','AVAILABLE','DEGRADED','UNAVAILABLE')),last_benchmarked_at timestamptz,last_error text,updated_at timestamptz not null default now(),unique(provider,model_id));
create table if not exists public.autonomous_model_routes(id uuid primary key default gen_random_uuid(),task_class text not null unique,primary_candidate_id uuid references public.autonomous_model_candidates(id),fallback_candidate_id uuid references public.autonomous_model_candidates(id),max_cost numeric(14,6) not null default 0 check(max_cost>=0),status text not null default 'UNCONFIGURED' check(status in('UNCONFIGURED','READY','DEGRADED','DISABLED')),updated_at timestamptz not null default now());
create table if not exists public.autonomous_model_metrics(id uuid primary key default gen_random_uuid(),candidate_id uuid not null references public.autonomous_model_candidates(id),task_class text not null,correlation_id uuid not null,quality_score numeric(8,4),latency_ms integer check(latency_ms>=0),success boolean not null,cost numeric(14,6) not null default 0 check(cost>=0),failure_code text,created_at timestamptz not null default now());
alter table public.autonomous_model_candidates enable row level security;alter table public.autonomous_model_routes enable row level security;alter table public.autonomous_model_metrics enable row level security;
do $$begin create policy model_candidates_superadmin_read on public.autonomous_model_candidates for select to authenticated using(private.is_superadmin());create policy model_routes_superadmin_read on public.autonomous_model_routes for select to authenticated using(private.is_superadmin());create policy model_metrics_superadmin_read on public.autonomous_model_metrics for select to authenticated using(private.is_superadmin());exception when duplicate_object then null;end$$;
create or replace function public.superadmin_record_model_benchmark(p_provider text,p_model_id text,p_free_tier boolean,p_score numeric,p_threshold numeric,p_available boolean,p_error text default null)
returns public.autonomous_model_candidates language plpgsql security definer set search_path=public,private,auth as $$
declare v public.autonomous_model_candidates%rowtype;begin if auth.uid() is null or not private.is_superadmin() then raise exception 'SUPERADMIN_REQUIRED' using errcode='42501';end if;if p_score<0 or p_threshold<=0 then raise exception 'INVALID_BENCHMARK';end if;
 insert into public.autonomous_model_candidates(provider,model_id,free_tier,eligible,benchmark_score,benchmark_threshold,availability,last_benchmarked_at,last_error)values(lower(btrim(p_provider)),btrim(p_model_id),p_free_tier,p_available and p_score>=p_threshold,p_score,p_threshold,case when p_available then'AVAILABLE'else'UNAVAILABLE'end,now(),nullif(btrim(p_error),''))
 on conflict(provider,model_id)do update set free_tier=excluded.free_tier,eligible=excluded.eligible,benchmark_score=excluded.benchmark_score,benchmark_threshold=excluded.benchmark_threshold,availability=excluded.availability,last_benchmarked_at=now(),last_error=excluded.last_error,updated_at=now() returning * into v;return v;end$$;
revoke all on function public.superadmin_record_model_benchmark(text,text,boolean,numeric,numeric,boolean,text) from public;grant execute on function public.superadmin_record_model_benchmark(text,text,boolean,numeric,numeric,boolean,text) to authenticated;
insert into public.autonomous_model_routes(task_class,max_cost,status)values('AGENT_CONSULTATION',0,'UNCONFIGURED'),('CORPORATE_ANALYSIS',0,'UNCONFIGURED'),('QA_DIAGNOSIS',0,'UNCONFIGURED')on conflict(task_class)do nothing;