-- Voice of Client / Provider governed feedback-to-QA loop.
create table if not exists public.autonomous_experience_signals(id uuid primary key default gen_random_uuid(),actor_role text not null check(actor_role in('CLIENT','PROVIDER')),service_id uuid,signal_type text not null,privacy_safe_payload jsonb not null default '{}'::jsonb,source text not null,correlation_id uuid not null default gen_random_uuid(),created_at timestamptz not null default now());
create table if not exists public.autonomous_experience_patterns(id uuid primary key default gen_random_uuid(),pattern_key text not null unique,actor_role text not null check(actor_role in('CLIENT','PROVIDER','BOTH')),hypothesis text not null,signal_count integer not null default 0,qa_scenario_id uuid references public.autonomous_qa_scenarios(id),status text not null default 'OBSERVED' check(status in('OBSERVED','TESTING','CONFIRMED','REJECTED','REMEDIATING','MEASURING','CLOSED')),pre_metric jsonb not null default '{}'::jsonb,post_metric jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
alter table public.autonomous_experience_signals enable row level security;alter table public.autonomous_experience_patterns enable row level security;
do $$begin create policy experience_signals_superadmin_read on public.autonomous_experience_signals for select to authenticated using(private.is_superadmin());create policy experience_patterns_superadmin_read on public.autonomous_experience_patterns for select to authenticated using(private.is_superadmin());exception when duplicate_object then null;end$$;
create or replace function public.superadmin_register_experience_pattern(p_pattern_key text,p_actor_role text,p_hypothesis text,p_signal_ids uuid[])
returns public.autonomous_experience_patterns language plpgsql security definer set search_path=public,private,auth as $$
declare v public.autonomous_experience_patterns%rowtype;n integer;begin
 if auth.uid() is null or not private.is_superadmin() then raise exception 'SUPERADMIN_REQUIRED' using errcode='42501';end if;
 select count(*) into n from public.autonomous_experience_signals where id=any(coalesce(p_signal_ids,'{}'::uuid[]));
 if n=0 then raise exception 'EVIDENCE_SIGNALS_REQUIRED';end if;
 insert into public.autonomous_experience_patterns(pattern_key,actor_role,hypothesis,signal_count,status)values(p_pattern_key,p_actor_role,p_hypothesis,n,'OBSERVED')on conflict(pattern_key)do update set hypothesis=excluded.hypothesis,signal_count=excluded.signal_count,updated_at=now() returning * into v;return v;end$$;
revoke all on function public.superadmin_register_experience_pattern(text,text,text,uuid[]) from public;grant execute on function public.superadmin_register_experience_pattern(text,text,text,uuid[]) to authenticated;