-- UGO TEST persists non-production services with ambiente='demo'. Production is a separate prohibited project.\n-- Verification-first QA: caller assertions are ignored; verdicts derive from persisted UGO TEST state.
create or replace function public.autonomous_run_qa_service_scenario(p_scenario_id uuid,p_simulator_results jsonb,p_chaos_result jsonb default '{}'::jsonb)
returns public.autonomous_qa_runs language plpgsql security definer set search_path=public,private,auth as $$
declare s public.autonomous_qa_scenarios%rowtype;r public.autonomous_qa_runs%rowtype;o jsonb:='{}';ok boolean;missing text[]:='{}';expected jsonb;sid uuid;
begin
 if coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode='42501';end if;
 select * into s from public.autonomous_qa_scenarios where id=p_scenario_id and status='ACTIVE';if s.id is null then raise exception 'ACTIVE_SCENARIO_REQUIRED';end if;
 sid:=s.service_id;if sid is null then raise exception 'REAL_TEST_SERVICE_BINDING_REQUIRED';end if;
 if not exists(select 1 from public.servicios where id=sid and ambiente='demo')then raise exception 'BOUND_TEST_SERVICE_REQUIRED';end if;
 if s.scenario_key='provider-radius' then o:=jsonb_build_object('provider_within_20km',exists(select 1 from public.ofertas_servicio where servicio_id=sid and distancia_km<=20),'outside_provider_rejected',not exists(select 1 from public.ofertas_servicio where servicio_id=sid and distancia_km>20));
 elsif s.scenario_key='payments' then o:=jsonb_build_object('payment_recorded',exists(select 1 from public.pagos where servicio_id=sid),'cash_acknowledged',exists(select 1 from public.pagos where servicio_id=sid and metodo='efectivo' and fecha_confirmacion is not null),'ledger_isolated',not exists(select 1 from public.pagos where servicio_id=sid and(cliente_id is null or proveedor_id is null)));
 elsif s.scenario_key='service-lifecycle' then o:=jsonb_build_object('service_id_isolated',true,'request_created',true,'provider_accepted',exists(select 1 from public.ofertas_servicio where servicio_id=sid and estado='aceptada'),'arrival_verified',exists(select 1 from public.servicio_estado_eventos where servicio_id=sid and estado_nuevo='llegado'),'start_evidence',exists(select 1 from public.evidencias_servicio where servicio_id=sid and tipo='antes'),'finish_evidence',exists(select 1 from public.evidencias_servicio where servicio_id=sid and tipo='despues'),'client_approved',exists(select 1 from public.servicio_estado_eventos where servicio_id=sid and estado_nuevo='completado'),'payment_recorded',exists(select 1 from public.pagos where servicio_id=sid),'completed',exists(select 1 from public.servicios where id=sid and estado='completado'),'bilateral_rating',(select count(distinct autor_tipo)>=2 from public.resenas where servicio_id=sid));
 else raise exception 'DETERMINISTIC_RUNTIME_PROBE_NOT_IMPLEMENTED:%',s.scenario_key;end if;
 expected:=coalesce(s.deterministic_judge->'required_assertions','[]');select coalesce(array_agg(x),'{}')into missing from jsonb_array_elements_text(expected)x where coalesce((o->>x)::boolean,false)=false;
 ok:=cardinality(missing)=0 and not coalesce((p_chaos_result->>'unexpected_failure')::boolean,false);
 insert into public.autonomous_qa_runs(scenario_id,status,simulator_results,chaos_result,judge_result,diagnosis,remediation_request,permanent_regression,started_at,finished_at)values(s.id,case when ok then'PASSED'else'FAILED'end,o,coalesce(p_chaos_result,'{}'),jsonb_build_object('passed',ok,'missing_assertions',to_jsonb(missing),'source','PERSISTED_TEST_STATE'),'Deterministic persisted-state probe',case when ok then null else'Remediate failed persisted assertions and rerun'end,ok and s.source_type='REGRESSION',now(),now())returning * into r;
 update public.autonomous_quality_coverage set scenario_id=s.id,last_run_id=r.id,status=case when ok then'COVERED'else'FAILING'end,updated_at=now()where coverage_key=s.coverage_key;return r;
end$$;
revoke all on function public.autonomous_run_qa_service_scenario(uuid,jsonb,jsonb) from public,anon,authenticated;grant execute on function public.autonomous_run_qa_service_scenario(uuid,jsonb,jsonb) to service_role;