-- Canonical department specialists are catalogued without inventing authority or execution.
-- DISABLED means no trigger, executor or permissions have been validated for this specialist.
-- Existing operational department agents and exactly six D14 auditors remain untouched.
insert into public.autonomous_agents(department_id,agent_key,name,capability,authority_class,status,model_provider,model_id,permissions) values
(1,'corporate-strategy','Corporate Strategy','Corporate Strategy: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(1,'priority-resource-orchestrator','Priority & Resource Orchestrator','Priority & Resource Orchestrator: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(1,'exception-coordinator','Exception Coordinator','Exception Coordinator: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(1,'outcome-learning','Outcome Learning','Outcome Learning: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(1,'executive-intelligence','Executive Intelligence','Executive Intelligence: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'dispatch-agent','Dispatch Agent','Dispatch Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'matching-agent','Matching Agent','Matching Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'provider-radius-agent','Provider Radius Agent','Provider Radius Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'gps-validation-agent','GPS Validation Agent','GPS Validation Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'travel-monitoring-agent','Travel Monitoring Agent','Travel Monitoring Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'arrival-geofence-agent','Arrival / Geofence Agent','Arrival / Geofence Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'service-lifecycle-agent','Service Lifecycle Agent','Service Lifecycle Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'realtime-operations-agent','Realtime Operations Agent','Realtime Operations Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'operational-recovery-agent','Operational Recovery Agent','Operational Recovery Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(2,'incident-operations-agent','Incident Operations Agent','Incident Operations Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(3,'client-support-agent','Client Support Agent','Client Support Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(3,'client-journey-agent','Client Journey Agent','Client Journey Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(3,'billing-support-agent','Billing Support Agent','Billing Support Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(3,'complaint-agent','Complaint Agent','Complaint Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(3,'retention-agent','Retention Agent','Retention Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(3,'client-feedback-agent','Client Feedback Agent','Client Feedback Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(3,'voice-of-client-agent','Voice of Client Agent','Voice of Client Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-recruitment-agent','Provider Recruitment Agent','Provider Recruitment Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-onboarding-agent','Provider Onboarding Agent','Provider Onboarding Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-activation-agent','Provider Activation Agent','Provider Activation Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-supply-agent','Provider Supply Agent','Provider Supply Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-quality-agent','Provider Quality Agent','Provider Quality Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-retention-agent','Provider Retention Agent','Provider Retention Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-fairness-agent','Provider Fairness Agent','Provider Fairness Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'provider-support-agent','Provider Support Agent','Provider Support Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(4,'voice-of-provider-agent','Voice of Provider Agent','Voice of Provider Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(5,'market-intelligence-agent','Market Intelligence Agent','Market Intelligence Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(5,'acquisition-agent','Acquisition Agent','Acquisition Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(5,'growth-experiment-agent','Growth Experiment Agent','Growth Experiment Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(5,'revenue-growth-agent','Revenue Growth Agent','Revenue Growth Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(5,'expansion-agent','Expansion Agent','Expansion Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(5,'territory-intelligence-agent','Territory Intelligence Agent','Territory Intelligence Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(6,'case-manager','Case Manager','Case Manager: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(6,'evidence-analysis-agent','Evidence Analysis Agent','Evidence Analysis Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(6,'fraud-detection-agent','Fraud Detection Agent','Fraud Detection Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(6,'abuse-detection-agent','Abuse Detection Agent','Abuse Detection Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(6,'dispute-resolution-agent','Dispute Resolution Agent','Dispute Resolution Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(6,'appeals-agent','Appeals Agent','Appeals Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(6,'critical-escalation-agent','Critical Escalation Agent','Critical Escalation Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'financial-controller','Financial Controller','Financial Controller: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'payment-agent','Payment Agent','Payment Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'reconciliation-agent','Reconciliation Agent','Reconciliation Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'provider-balance-agent','Provider Balance Agent','Provider Balance Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'cash-payment-agent','Cash Payment Agent','Cash Payment Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'refund-agent','Refund Agent','Refund Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'treasury-control-agent','Treasury Control Agent','Treasury Control Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(7,'financial-risk-agent','Financial Risk Agent','Financial Risk Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(8,'software-engineering-agent','Software Engineering Agent','Software Engineering Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'debugging-agent','Debugging Agent','Debugging Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'code-review-agent','Code Review Agent','Code Review Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'security-agent','Security Agent','Security Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(8,'devops-agent','DevOps Agent','DevOps Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(8,'observability-agent','Observability Agent','Observability Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'technology-radar-agent','Technology Radar Agent','Technology Radar Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'r-d-agent','R&D Agent','R&D Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'model-router-agent','Model Router Agent','Model Router Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'database-reliability-agent','Database Reliability Agent','Database Reliability Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(8,'realtime-reliability-agent','Realtime Reliability Agent','Realtime Reliability Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'qa-director','QA Director','QA Director: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'client-simulator','Client Simulator','Client Simulator: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'provider-simulator','Provider Simulator','Provider Simulator: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'admin-system-simulator','Admin/System Simulator','Admin/System Simulator: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'p0-journey-tester','P0 Journey Tester','P0 Journey Tester: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'chaos-agent','Chaos Agent','Chaos Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'deterministic-judge','Deterministic Judge','Deterministic Judge: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'meta-qa-agent','Meta-QA Agent','Meta-QA Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'regression-agent','Regression Agent','Regression Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'release-gate-agent','Release Gate Agent','Release Gate Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(9,'quality-coverage-agent','Quality Coverage Agent','Quality Coverage Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(10,'legal-intelligence-agent','Legal Intelligence Agent','Legal Intelligence Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'contract-agent','Contract Agent','Contract Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'privacy-agent','Privacy Agent','Privacy Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'consumer-protection-agent','Consumer Protection Agent','Consumer Protection Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'labor-risk-agent','Labor Risk Agent','Labor Risk Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'compliance-agent','Compliance Agent','Compliance Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'policy-agent','Policy Agent','Policy Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'ip-protection-agent','IP Protection Agent','IP Protection Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'ip-gate-agent','IP Gate Agent','IP Gate Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(10,'corporate-protection-agent','Corporate Protection Agent','Corporate Protection Agent: governed specialist; execution pending validated contract','RED','DISABLED',null,null,'[]'::jsonb),
(11,'brand-agent','Brand Agent','Brand Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(11,'creative-agent','Creative Agent','Creative Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(11,'marketing-campaign-agent','Marketing Campaign Agent','Marketing Campaign Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(11,'community-agent','Community Agent','Community Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(11,'pr-reputation-agent','PR/Reputation Agent','PR/Reputation Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(11,'localization-agent','Localization Agent','Localization Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(11,'marketing-experiment-agent','Marketing Experiment Agent','Marketing Experiment Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'product-strategy-agent','Product Strategy Agent','Product Strategy Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'product-manager-agent','Product Manager Agent','Product Manager Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'ux-research-agent','UX Research Agent','UX Research Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'ui-ux-agent','UI/UX Agent','UI/UX Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'design-system-agent','Design System Agent','Design System Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'accessibility-agent','Accessibility Agent','Accessibility Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'product-analytics-agent','Product Analytics Agent','Product Analytics Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb),
(12,'product-experiment-agent','Product Experiment Agent','Product Experiment Agent: governed specialist; execution pending validated contract','YELLOW','DISABLED',null,null,'[]'::jsonb)
on conflict(agent_key) do nothing;
-- Prevent accidental promotion of a catalog-only agent through a stale broad model connector.
-- A specialist becomes executable only after a separate migration implements a trigger,
-- concrete capability, deterministic verification and an independent runtime gate.
