-- UGO integrated disputes: Client <-> Provider <-> Admin
-- Applied to production Supabase on 2026-09-06.

alter table public.disputas add column if not exists numero bigint generated by default as identity;
alter table public.disputas add column if not exists cliente_id uuid references public.usuarios(id);
alter table public.disputas add column if not exists proveedor_id uuid references public.usuarios(id);
alter table public.disputas add column if not exists monto_disputado numeric;
alter table public.disputas add column if not exists resolucion_favor text check (resolucion_favor in ('cliente','proveedor'));
alter table public.disputas add column if not exists estado_servicio_previo public.servicio_estado;
alter table public.disputas add column if not exists ajuste_financiero_pendiente boolean not null default false;

update public.disputas d
set cliente_id=s.cliente_id,
    proveedor_id=s.proveedor_id,
    monto_disputado=coalesce(d.monto_disputado,s.tarifa)
from public.servicios s
where s.id=d.servicio_id
  and (d.cliente_id is null or d.proveedor_id is null or d.monto_disputado is null);

create table if not exists public.disputa_mensajes (
 id bigint generated by default as identity primary key,
 disputa_id uuid not null references public.disputas(id) on delete cascade,
 autor_id uuid not null references public.usuarios(id),
 autor_rol text not null check (autor_rol in ('cliente','proveedor','admin')),
 mensaje text not null check (char_length(trim(mensaje)) between 2 and 2000),
 evidencias jsonb not null default '[]'::jsonb,
 created_at timestamptz not null default now()
);

alter table public.disputa_mensajes enable row level security;

drop policy if exists disputa_mensajes_select on public.disputa_mensajes;
create policy disputa_mensajes_select on public.disputa_mensajes for select using (
 private.is_admin() or exists (
  select 1 from public.disputas d
  where d.id=disputa_id
    and private.es_participante_servicio(d.servicio_id,auth.uid())
 )
);

drop policy if exists disputa_mensajes_insert on public.disputa_mensajes;
create policy disputa_mensajes_insert on public.disputa_mensajes for insert with check (
 autor_id=auth.uid() and exists (
  select 1 from public.disputas d
  where d.id=disputa_id
    and private.es_participante_servicio(d.servicio_id,auth.uid())
 )
);

drop policy if exists disputas_admin_select on public.disputas;
create policy disputas_admin_select on public.disputas for select using (private.is_admin());

create or replace function public.abrir_disputa(
 p_servicio_id uuid,
 p_motivo text,
 p_evidencias jsonb default '[]'::jsonb
)
returns public.disputas
language plpgsql
security definer
set search_path=public,private
as $$
declare
 v_uid uuid:=auth.uid();
 v_s public.servicios;
 v_d public.disputas;
 v_role text;
begin
 if v_uid is null then raise exception 'No autenticado'; end if;
 select * into v_s from public.servicios where id=p_servicio_id;
 if v_s.id is null then raise exception 'Servicio no encontrado'; end if;
 if v_uid<>v_s.cliente_id and v_uid is distinct from v_s.proveedor_id then
  raise exception 'No participás de este servicio';
 end if;
 if v_s.estado not in ('asignado','en_camino','llegado','en_progreso','esperando_aprobacion','completado','disputado') then
  raise exception 'El servicio todavía no admite disputa';
 end if;
 if char_length(trim(coalesce(p_motivo,'')))<8 then raise exception 'Describí mejor el problema'; end if;

 select * into v_d from public.disputas where servicio_id=p_servicio_id limit 1;
 if v_d.id is not null then return v_d; end if;

 insert into public.disputas(
  servicio_id,abierta_por,cliente_id,proveedor_id,monto_disputado,motivo,evidencias,estado_servicio_previo
 ) values(
  v_s.id,v_uid,v_s.cliente_id,v_s.proveedor_id,v_s.tarifa,trim(p_motivo),coalesce(p_evidencias,'[]'::jsonb),v_s.estado
 ) returning * into v_d;

 update public.servicios
 set estado='disputado',updated_at=now()
 where id=v_s.id and estado<>'completado';

 update public.pagos
 set estado='disputado',updated_at=now()
 where servicio_id=v_s.id and estado in ('autorizado','retenido');

 v_role:=case when v_uid=v_s.cliente_id then 'cliente' else 'proveedor' end;
 insert into public.disputa_mensajes(disputa_id,autor_id,autor_rol,mensaje,evidencias)
 values(v_d.id,v_uid,v_role,trim(p_motivo),coalesce(p_evidencias,'[]'::jsonb));

 perform private.crear_notificacion_unica(
  case when v_uid=v_s.cliente_id then v_s.proveedor_id else v_s.cliente_id end,
  'disputa_abierta','Se abrió una disputa',
  'UGO abrió una revisión sobre el servicio #'||v_s.numero,
  jsonb_build_object('servicio_id',v_s.id,'disputa_id',v_d.id),
  'disputa:'||v_d.id||':abierta'
 );

 insert into public.audit_log(evento,actor_id,entidad_tipo,entidad_id,detalles)
 values('disputa_abierta',v_uid,'disputa',v_d.id,jsonb_build_object('servicio_id',v_s.id));
 return v_d;
end
$$;

create or replace function public.responder_disputa(
 p_disputa_id uuid,
 p_mensaje text,
 p_evidencias jsonb default '[]'::jsonb
)
returns public.disputa_mensajes
language plpgsql
security definer
set search_path=public,private
as $$
declare
 v_uid uuid:=auth.uid();
 v_d public.disputas;
 v_s public.servicios;
 v_role text;
 v_m public.disputa_mensajes;
begin
 if v_uid is null then raise exception 'No autenticado'; end if;
 select * into v_d from public.disputas where id=p_disputa_id;
 if v_d.id is null then raise exception 'Disputa no encontrada'; end if;
 select * into v_s from public.servicios where id=v_d.servicio_id;
 if v_uid<>v_s.cliente_id and v_uid is distinct from v_s.proveedor_id then
  raise exception 'No participás de esta disputa';
 end if;
 if v_d.estado not in ('abierta','en_revision') then raise exception 'La disputa ya fue resuelta'; end if;
 if char_length(trim(coalesce(p_mensaje,'')))<2 then raise exception 'Escribí un mensaje'; end if;
 v_role:=case when v_uid=v_s.cliente_id then 'cliente' else 'proveedor' end;
 insert into public.disputa_mensajes(disputa_id,autor_id,autor_rol,mensaje,evidencias)
 values(p_disputa_id,v_uid,v_role,trim(p_mensaje),coalesce(p_evidencias,'[]'::jsonb))
 returning * into v_m;
 update public.disputas set estado='en_revision',updated_at=now()
 where id=p_disputa_id and estado='abierta';
 return v_m;
end
$$;

create or replace function public.admin_resolver_disputa(
 p_disputa_id uuid,
 p_resolucion text,
 p_favor_de text
)
returns public.disputas
language plpgsql
security definer
set search_path=public,private
as $$
declare
 v_uid uuid:=auth.uid();
 v_d public.disputas;
 v_s public.servicios;
begin
 if not private.is_admin() then raise exception 'Solo admin'; end if;
 if p_favor_de not in ('cliente','proveedor') then raise exception 'Resolución inválida'; end if;
 if char_length(trim(coalesce(p_resolucion,'')))<8 then
  raise exception 'La resolución requiere una explicación';
 end if;

 update public.disputas
 set estado=case when p_favor_de='cliente'
                  then 'resuelta_cliente'::public.disputa_estado
                  else 'resuelta_proveedor'::public.disputa_estado end,
     resolucion=trim(p_resolucion),
     resolucion_favor=p_favor_de,
     resuelta_por=v_uid,
     resuelta_at=now(),
     updated_at=now(),
     ajuste_financiero_pendiente=(
      p_favor_de='cliente' and exists(
       select 1 from public.pagos p
       where p.servicio_id=disputas.servicio_id and p.estado='disputado'
      )
     )
 where id=p_disputa_id and estado in ('abierta','en_revision')
 returning * into v_d;

 if v_d.id is null then raise exception 'Disputa no encontrada o ya resuelta'; end if;
 select * into v_s from public.servicios where id=v_d.servicio_id;

 if p_favor_de='proveedor' then
  update public.servicios
  set estado=coalesce(v_d.estado_servicio_previo,'esperando_aprobacion'::public.servicio_estado),updated_at=now()
  where id=v_d.servicio_id and estado='disputado';
  update public.pagos set estado='retenido',updated_at=now()
  where servicio_id=v_d.servicio_id and estado='disputado';
 else
  update public.servicios
  set estado='cancelado',cancelado_at=coalesce(cancelado_at,now()),updated_at=now()
  where id=v_d.servicio_id and estado='disputado';
 end if;

 insert into public.disputa_mensajes(disputa_id,autor_id,autor_rol,mensaje)
 values(v_d.id,v_uid,'admin','Resolución: '||trim(p_resolucion));

 perform private.crear_notificacion_unica(
  v_d.cliente_id,'disputa_resuelta','UGO resolvió la disputa',
  'Revisá la resolución del caso del servicio #'||coalesce(v_s.numero::text,''),
  jsonb_build_object('servicio_id',v_d.servicio_id,'disputa_id',v_d.id,'favor_de',p_favor_de),
  'disputa:'||v_d.id||':resuelta:cliente'
 );
 if v_d.proveedor_id is not null then
  perform private.crear_notificacion_unica(
   v_d.proveedor_id,'disputa_resuelta','UGO resolvió la disputa',
   'Revisá la resolución del caso del servicio #'||coalesce(v_s.numero::text,''),
   jsonb_build_object('servicio_id',v_d.servicio_id,'disputa_id',v_d.id,'favor_de',p_favor_de),
   'disputa:'||v_d.id||':resuelta:proveedor'
  );
 end if;

 insert into public.audit_log(evento,actor_id,entidad_tipo,entidad_id,detalles)
 values('disputa_resuelta',v_uid,'disputa',v_d.id,
  jsonb_build_object('favor_de',p_favor_de,'servicio_id',v_d.servicio_id,'ajuste_financiero_pendiente',v_d.ajuste_financiero_pendiente));
 return v_d;
end
$$;

grant execute on function public.abrir_disputa(uuid,text,jsonb) to authenticated;
grant execute on function public.responder_disputa(uuid,text,jsonb) to authenticated;
grant execute on function public.admin_resolver_disputa(uuid,text,text) to authenticated;
