import { createHash, randomBytes } from 'node:crypto'
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://trfsjuseqjxlhrxuvdsm.supabase.co'
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'sb_publishable_bbCcM7ElzH-iGAQw8Qefzg_ZmO0sKH8'
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY
const GEMINI_MODELS = Array.from(new Set([
  process.env.GEMINI_MODEL,
  'gemini-3.5-flash-lite',
  'gemini-3.5-flash',
  'gemini-3.7-flash',
].filter(Boolean) as string[]))

type Coordinates={latitude:number;longitude:number}
type RoutingCandidate={providerId:string;location:Coordinates}
function bearer(req:any){const raw=String(req.headers?.authorization||'');return raw.startsWith('Bearer ')?raw.slice(7).trim():''}
function extractJson(text:string){const cleaned=String(text||'').replace(/```json/gi,'').replace(/```/g,'').trim();try{return JSON.parse(cleaned)}catch{}const start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start>=0&&end>start){try{return JSON.parse(cleaned.slice(start,end+1))}catch{}}return null}
function validCoord(value:unknown):value is Coordinates{if(!value||typeof value!=='object')return false;const v=value as Record<string,unknown>,lat=Number(v.latitude),lng=Number(v.longitude);return Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lng)&&lng>=-180&&lng<=180}
function osrmCoord(c:Coordinates){return`${Number(c.longitude)},${Number(c.latitude)}`}
function osrmBase(){const raw=String(process.env.OSRM_BASE_URL||'').trim().replace(/\/+$/,'');if(!raw)throw Object.assign(new Error('OSRM_BASE_URL no configurado'),{status:503});if(!/^https?:\/\//i.test(raw))throw Object.assign(new Error('OSRM_BASE_URL inválido'),{status:503});return raw}
async function osrmJson(url:string){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(url,{signal:controller.signal,headers:{accept:'application/json'}}),data:any=await response.json().catch(()=>null);if(!response.ok||!data||data.code!=='Ok')throw Object.assign(new Error(data?.message||`OSRM ${response.status}`),{status:502});return data}finally{clearTimeout(timeout)}}
async function routing(req:any,res:any){try{const body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{}),action=String(body.action||''),base=osrmBase();if(action==='route'){if(!validCoord(body.origin)||!validCoord(body.destination))return res.status(400).json({error:'Coordenadas inválidas'});const data=await osrmJson(`${base}/route/v1/driving/${osrmCoord(body.origin)};${osrmCoord(body.destination)}?overview=full&geometries=geojson&steps=false`),route=data.routes?.[0];if(!route)return res.status(404).json({error:'Ruta no encontrada'});return res.status(200).json({distanceMeters:Number(route.distance||0),durationSeconds:Number(route.duration||0),geometry:route.geometry||null})}if(action==='table'){if(!validCoord(body.destination)||!Array.isArray(body.candidates))return res.status(400).json({error:'Solicitud inválida'});const candidates=(body.candidates as RoutingCandidate[]).filter(c=>c&&typeof c.providerId==='string'&&validCoord(c.location)).slice(0,50);if(!candidates.length)return res.status(200).json([]);const coordinates=[...candidates.map(c=>c.location),body.destination as Coordinates],destinationIndex=coordinates.length-1,sources=candidates.map((_,index)=>index).join(';'),data=await osrmJson(`${base}/table/v1/driving/${coordinates.map(osrmCoord).join(';')}?sources=${sources}&destinations=${destinationIndex}&annotations=duration,distance`),durations:Array<Array<number|null>>=data.durations||[],distances:Array<Array<number|null>>=data.distances||[];const ranked=candidates.map((candidate,index)=>({...candidate,etaSeconds:Number(durations[index]?.[0]??Number.MAX_SAFE_INTEGER),distanceMeters:Number(distances[index]?.[0]??Number.MAX_SAFE_INTEGER)})).filter(item=>Number.isFinite(item.etaSeconds)&&item.etaSeconds<Number.MAX_SAFE_INTEGER).sort((a,b)=>a.etaSeconds-b.etaSeconds||a.distanceMeters-b.distanceMeters);return res.status(200).json(ranked)}return res.status(400).json({error:'Acción de routing inválida'})}catch(error:any){const status=Number(error?.status)||502;return res.status(status).json({error:error instanceof Error?error.message:'Routing no disponible'})}}

function baseUrl(req:any){const explicit=String(process.env.APP_URL||'').trim().replace(/\/$/,'');if(explicit)return explicit;const proto=String(req.headers?.['x-forwarded-proto']||'https').split(',')[0],host=String(req.headers?.['x-forwarded-host']||req.headers?.host||'').split(',')[0];return host?`${proto}://${host}`:''}
function mpConfig(){return{clientId:String(process.env.MERCADO_PAGO_CLIENT_ID||process.env.MERCADO_PAGO_APP_ID||'').trim(),clientSecret:String(process.env.MERCADO_PAGO_CLIENT_SECRET||'').trim()}}
function serviceClient(){if(!SUPABASE_SERVICE_KEY)throw Object.assign(new Error('SUPABASE_SERVICE_KEY no configurada'),{status:503});return createClient(SUPABASE_URL,SUPABASE_SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})}
async function authenticatedProvider(req:any){const token=bearer(req);if(!token)throw Object.assign(new Error('Sesión requerida'),{status:401});const sb=serviceClient(),{data,error}=await sb.auth.getUser(token);if(error||!data.user)throw Object.assign(new Error('Sesión inválida'),{status:401});const{data:profile}=await sb.from('usuarios').select('tipo').eq('id',data.user.id).maybeSingle();if(profile?.tipo!=='proveedor')throw Object.assign(new Error('Solo proveedores pueden vincular Mercado Pago'),{status:403});return{sb,user:data.user}}
function b64url(input:Buffer){return input.toString('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function mercadoPagoOAuth(req:any,res:any){try{
  const cfg=mpConfig(),redirectUri=`${baseUrl(req)}/api/test`;
  if(req.method==='GET'&&req.query?.code&&req.query?.state){
    if(!cfg.clientId||!cfg.clientSecret||!SUPABASE_SERVICE_KEY)return res.redirect(302,`${baseUrl(req)}/?app=provider&mp=error`)
    const sb=serviceClient(),state=String(req.query.state),code=String(req.query.code),{data:stateRows,error:stateError}=await sb.rpc('mp_oauth_consume_state',{p_state:state});if(stateError||!stateRows?.[0])return res.redirect(302,`${baseUrl(req)}/?app=provider&mp=invalid_state`)
    const providerId=stateRows[0].proveedor_id,verifier=stateRows[0].code_verifier
    const tokenResponse=await fetch('https://api.mercadopago.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:cfg.clientId,client_secret:cfg.clientSecret,code,grant_type:'authorization_code',redirect_uri:redirectUri,code_verifier:verifier||undefined,test_token:false})}),payload:any=await tokenResponse.json().catch(()=>({}));if(!tokenResponse.ok||!payload.access_token){console.error('MP OAuth token exchange failed',{status:tokenResponse.status,message:payload?.message||payload?.error});return res.redirect(302,`${baseUrl(req)}/?app=provider&mp=error`)}
    const{error:storeError}=await sb.rpc('mp_oauth_store_credentials',{p_proveedor_id:providerId,p_mp_user_id:String(payload.user_id||''),p_access_token:String(payload.access_token),p_refresh_token:payload.refresh_token?String(payload.refresh_token):null,p_public_key:payload.public_key?String(payload.public_key):null,p_scope:payload.scope?String(payload.scope):null,p_token_type:payload.token_type?String(payload.token_type):null,p_expires_in:Number.isFinite(Number(payload.expires_in))?Number(payload.expires_in):null,p_live_mode:payload.live_mode==null?null:Boolean(payload.live_mode)});if(storeError){console.error('MP OAuth credential store failed',storeError);return res.redirect(302,`${baseUrl(req)}/?app=provider&mp=error`)}
    return res.redirect(302,`${baseUrl(req)}/?app=provider&mp=connected`)
  }
  if(req.method!=='POST')return res.status(405).json({error:'Método no permitido'})
  const{sb,user}=await authenticatedProvider(req),action=String(req.body?.action||'status')
  if(action==='status'){const{data,error}=await sb.rpc('mp_oauth_status',{p_proveedor_id:user.id});if(error)throw error;const row=data?.[0]||{connected:false};return res.status(200).json({connected:Boolean(row.connected),mpUserId:row.mp_user_id||null,expiresAt:row.expires_at||null,liveMode:row.live_mode??null,connectedAt:row.connected_at||null,configured:Boolean(cfg.clientId&&cfg.clientSecret)})}
  if(action==='disconnect'){const{error}=await sb.rpc('mp_oauth_disconnect',{p_proveedor_id:user.id});if(error)throw error;return res.status(200).json({ok:true,connected:false})}
  if(action==='connect'){
    if(!cfg.clientId||!cfg.clientSecret)return res.status(503).json({error:'Faltan MERCADO_PAGO_CLIENT_ID / MERCADO_PAGO_CLIENT_SECRET en el servidor.'});if(!redirectUri)return res.status(503).json({error:'APP_URL no disponible.'})
    const state=b64url(randomBytes(32)),verifier=b64url(randomBytes(48)),challenge=b64url(createHash('sha256').update(verifier).digest());const{error}=await sb.rpc('mp_oauth_create_state',{p_proveedor_id:user.id,p_state:state,p_code_verifier:verifier});if(error)throw error
    const auth=new URL('https://auth.mercadopago.com.br/authorization');auth.searchParams.set('client_id',cfg.clientId);auth.searchParams.set('response_type','code');auth.searchParams.set('platform_id','mp');auth.searchParams.set('state',state);auth.searchParams.set('redirect_uri',redirectUri);auth.searchParams.set('code_challenge',challenge);auth.searchParams.set('code_challenge_method','S256');return res.status(200).json({authorizationUrl:auth.toString(),redirectUri})
  }
  return res.status(400).json({error:'Acción OAuth inválida'})
 }catch(error:any){console.error('Mercado Pago OAuth failed',error);const status=Number(error?.status)||500;return res.status(status>=400&&status<600?status:500).json({error:error instanceof Error?error.message:'Error OAuth'})}}

async function callGemini(geminiKey:string,body:any){let lastStatus=0,lastError='Gemini no respondió';for(const model of GEMINI_MODELS){const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':geminiKey},body:JSON.stringify(body)});const payload:any=await response.json().catch(()=>({}));if(response.ok)return{response,payload,model};lastStatus=response.status;lastError=payload?.error?.message||`Gemini respondió ${response.status}`;const retryable=response.status===404||response.status===429||response.status===503||/high demand|overloaded|temporar|no longer available|not found|new users/i.test(lastError);console.warn('Hugo Gemini fallback',{model,status:response.status,retryable,message:lastError});if(!retryable)break}throw Object.assign(new Error(lastError),{status:lastStatus||502})}
async function geminiHealth(res:any){const geminiKey=process.env.GEMINI_API_KEY?.trim();if(!geminiKey)return res.status(503).json({ok:false,keyConfigured:false,error:'GEMINI_API_KEY missing'});try{const{response,payload,model}=await callGemini(geminiKey,{contents:[{role:'user',parts:[{text:'Respondé únicamente OK.'}]}],generationConfig:{maxOutputTokens:40,temperature:0}});const text=payload?.candidates?.[0]?.content?.parts?.map((p:any)=>p?.text||'').join('').trim()||'';return res.status(response.ok&&text?200:502).json({ok:Boolean(response.ok&&text),keyConfigured:true,model,googleStatus:response.status,response:text||null})}catch(error){return res.status(502).json({ok:false,keyConfigured:true,error:error instanceof Error?error.message:'network error'})}}

export default async function handler(req:any,res:any){
 res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(200).end();if(req.method==='GET'&&req.query?.code&&req.query?.state)return mercadoPagoOAuth(req,res);if(String(req.query?.mp_oauth||'')==='1')return mercadoPagoOAuth(req,res);if(req.method==='GET'&&String(req.query?.health||'')==='1')return geminiHealth(res);if(req.method==='POST'&&String(req.query?.routing||'')==='1')return routing(req,res);if(req.method!=='POST')return res.status(405).json({error:'Método no permitido'})
 try{
  const token=bearer(req);if(!token)return res.status(401).json({error:'Sesión requerida'});const geminiKey=process.env.GEMINI_API_KEY?.trim();if(!geminiKey)return res.status(503).json({error:'GEMINI_API_KEY no está configurada en Vercel'})
  const authClient=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const{data:authData,error:authError}=await authClient.auth.getUser(token);if(authError||!authData.user)return res.status(401).json({error:'Sesión inválida'})
  const requestedRole=req.body?.role==='provider'?'provider':'client',expectedRole=requestedRole==='provider'?'proveedor':'cliente';const userClient=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const{data:profile}=await userClient.from('usuarios').select('tipo').eq('id',authData.user.id).maybeSingle();if(!profile||profile.tipo!==expectedRole)return res.status(403).json({error:'El rol de la sesión no coincide con esta aplicación'})
  const message=String(req.body?.message||'').trim().slice(0,1200);if(!message)return res.status(400).json({error:'Mensaje requerido'});const context=String(req.body?.context||'').slice(0,2400);const history=Array.isArray(req.body?.history)?req.body.history.slice(-10):[];const roleText=requestedRole==='client'?'Cliente que busca contratar un servicio.':'Proveedor que recibe y ejecuta servicios.'
  const system=['Sos Hugo, asistente operativo de U.G.O.','Respondé en español rioplatense, breve y directo.',roleText,'MEMORIA: tratá el Contexto y la MEMORIA DEL PEDIDO como hechos ya confirmados por el usuario.','NUNCA vuelvas a preguntar un dato que ya figure en la memoria del pedido o en el historial.','Si el usuario corrige un dato, reemplazá el dato anterior por el nuevo.','Preguntá únicamente el próximo dato realmente faltante para poder preparar el pedido.','Si categoría, descripción, dirección y presupuesto ya están informados, no hagas más preguntas de relevamiento: confirmá o prepará la búsqueda.','No inventes profesionales, precios, pagos ni estados.','Detectá categoría y urgencia cuando corresponda.','Devolvé SOLO JSON válido:','{"reply":"máximo 22 palabras","action":"none|search_provider|prepare_request","category_hint":null,"urgent":false,"description":null}',`Contexto: ${context||'Sin servicio activo.'}`].join('\n')
  const contents=[...history.map((turn:any)=>({role:turn?.role==='assistant'?'model':'user',parts:[{text:String(turn?.content||'').slice(0,700)}]})),{role:'user',parts:[{text:message}]}]
  const{payload,model}=await callGemini(geminiKey,{system_instruction:{parts:[{text:system}]},contents,generationConfig:{responseMimeType:'application/json',maxOutputTokens:180,temperature:0.1}});const raw=payload?.candidates?.[0]?.content?.parts?.map((p:any)=>p?.text||'').join('')||'';const parsed=extractJson(raw);if(!parsed?.reply)return res.status(502).json({error:'Gemini no devolvió una respuesta válida'})
  return res.status(200).json({reply:String(parsed.reply).slice(0,300),action:['none','search_provider','prepare_request'].includes(parsed.action)?parsed.action:'none',category_hint:parsed.category_hint?String(parsed.category_hint).slice(0,80):null,urgent:Boolean(parsed.urgent),description:parsed.description?String(parsed.description).slice(0,500):null,model})
 }catch(error:any){console.error('Hugo Gemini endpoint failed',error);const status=Number(error?.status)||500;return res.status(status>=400&&status<600?status:500).json({error:error instanceof Error?error.message:'Error interno de Hugo'})}
}
